### ISSUE TITLE
Nested Dll loading issue with vNet-style D.I.

### ISSUE THREAD

**Issue by NeverOddOrEven** [dotnet/orleans#1018]
When nesting the DLLs used by the Grain assembly in the "Applications/appname" deployment path, the D.I. framework cannot resolve references into the grain assembly and other assemblies grains depend upon.

As an example, I have my ConfigureServices method in a class in my Grain assembly. The silo Xml configuration points at the Grain assembly, and the correct class.

```
<Defaults>
   ...
   <Startup Type="Abc.Grains.ConfigureServices,Abc.Grains" />
</Defaults>
```

Results in:

```
[2015-11-12 16:44:29.195 GMT     1      ERROR   100105  OrleansSiloHost 127.0.0.
1:11111]        !!!!!!!!!! ERROR starting Orleans silo name=Apollo Exception=Exc level 0: System.InvalidOperationException: Can not locate the type specified in the configuration file: 'Abc.Grains.ConfigureServices,Abc.Grains'.
   at Orleans.Runtime.Startup.ConfigureStartupBuilder.ConfigureStartup(String startupTypeName)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config, ILocalDataStore keyStore)
   at Orleans.Runtime.Silo..ctor(String name, SiloType siloType, ClusterConfiguration config)
   at Orleans.Runtime.Host.SiloHost.InitializeOrleansSilo()
```

**Comment by attilah** [comment]
Orleans is taking care of the initial assembly loading. If the resolve fails I think that is an assembly loading issue and an orleans issue, not DI issue.

Is Orleans taking care of loading all assemblies from "Applications/appname" path?

**Comment by NeverOddOrEven** [comment]
@sergeybykov looked at this briefly. I understood his comment to mean that the code for setting up D.I. was running before the assemblies in the Applications/appname path were being loaded. (Hopefully I am not characterizing his remarks incorrectly)

**Comment by amccool** [comment]
remove the comma ,   I dont believe the Activator.CreateInstance style is being used.    Orleans has already loaded assemblies (by the folder) and only needs to find the Type (not the assembly)

**Comment by NeverOddOrEven** [comment]
Created a demo in my fork
https://github.com/NeverOddOrEven/orleans/commits/AddNewSampleUsingNestedAssembliesWithDI/Samples/NestedApplicationHelloWorld

**Comment by NeverOddOrEven** [comment]
This behavior manifests when the Startup type is present in a nested application. At construction time, the global IServiceProvider is built, and it looks to find the assemblies in the Startup type (configuration). However, the call to SiloAssemblyLoader has not yet been made, and therefore this resolution fails. 

The other aspect to consider is that it is a global provider. There may need to be an IServiceProvider associated with each nested Application. 

Finally, are these assemblies loaded in the same AppDomain as the rest of the Orleans runtime, or are they run in an independent AppDomain?

**Comment by attilah** [comment]
Because the current implementation of SiloAssemblyLoader is filtering on assemblies which ones are containing a Grain or a Provider instantiating a SiloAssemblyLoader would only be a partial solution, that why I'll not proceed that path.
That would not cover the case when someone has only the Startup type in an Assembly and no Grains or  Providers.

Since we already tackling the problem of assembly discover and loading for the whole system in https://github.com/dotnet/orleans/pull/2025 I'm closing this issue.

Startup type location will be addressed by a separate PR.

Meanwhile from your custom host you can use the UseStartupType extension method on the ClusterConfiguration type instead of xml configuration, of course it involves to have a reference in your host project, but as we're moving toward programmatic config in the future it is not an issue.
