### ISSUE TITLE
Unordered attribute

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#106]
This one is not documented anywhere but is visible on API's public surface.. It' also the only one which targets grain interface (all other attributes target grain implemenation classes).

What does it do?

**Comment by gabikliot** [comment]
By default calls to a grain are ordered. You can mark the grain as unordered and then ordering is not maintained.

One place it is used now is if the grain is stateless worker it is implicitly unordered. We take advantage of that in the way we pick gateways. For ordered grains all msgs to the same grain go via the same gw, to maintain order. For stateless workers msgs sent to a stateless worker grain will be round robined between different gateways. That way if let’s say you have one client and 10 silos, and you have some heavy operation you want to load balance across multiple stateless workers on multiple silos, this will happen since we will send msgs to different gateways and each gateway will have local stateless workers.

**Comment by yevhen** [comment]
@gabikliot 
> One place it is used now is if the grain is stateless worker it is implicitly unordered. 

So that attribute doesn't make sense in conj with `StatelessWorker`, right?

I'm not sure I completely understand what *order* means here. I'd like to understand why it's needed and when I (as developer) would want to change it? What would you write in the documentation? What are the use-cases?

P.S. Awaiting the task naturally orders message delivery, from the perspective of single sender (per-session order).  But, when there multiple autonomous senders - then order doesn't really matter. They cannot make decisions that rely on global order, since there is no global ordering in Orleans.

**Comment by sergeybykov** [comment]
'Ordered' is probably too strong of a claim here. Client (frontend) when talking to silos (gateways) tries to maintain order by sending messages to a particular grain through a single gateway (via consistent hashing). In other words, even though a client is connected to a number of gateways, it spreads messages across them via a consistent mapping based on the target grain IDs.

Now, StatelessWorkers are a special case. They may have multiple activations per grain ID, and even on different silos. If client were to send messages to a StatelessWorkers grain with the 'ordering' scheme described above, it would only send them to a single gateway, which would limit its throughput. StatelessWorkers are a good fit for scenarios when they perform a functional operation with no affinity to a context. An example is the Presence sample. In these scenarios is it desirable to evenly spread messages across all gateways, and often time a single ID is used for all StatelessWorkers grain activations in the system. Hence, Unordered is automatically implied for StatelessWorker grains.

**Comment by yevhen** [comment]
Ok. It looks like this attribute is something internal, no?

**Comment by sergeybykov** [comment]
I can't think of another use case for it other than StatelessWorker off the top of my head. So it is kind of internal in that sense.

**Comment by yevhen** [comment]
Answered. Thanks!
