### ISSUE TITLE
Using SystemStoreType ="SqlServer": mis-configuration and startup issues.

### ISSUE THREAD

**Issue by vincentzh** [dotnet/orleans#1088]
I have three Silos,but all requests just go to ```Silo3``` Server.
And if ```Silo3``` suddenly break down,All requests haven't redirected to ```Silo1``` or ```Silo2``` server.

[here are client and server configuration files](https://gist.github.com/vincentzh/6ad75c65bc26d6b2cf2c)

please tell me what I missed.

**Comment by sergeybykov** [comment]
Do you see all three silos listed as Active in the `OrleansSiloInstances` table in SQL?

**Comment by gabikliot** [comment]
you have different `DeploymentId="Silo1" ` is all 3 silo configs. And client connects only to silo 3.

**There should be only one silo config file, exactly the same for all silos**. No need to manually specify `Networking Address="192.168.1.125"`, just the Port ss enough.

**Comment by vincentzh** [comment]
@sergeybykov yes,there are all active.
@gabikliot I empty ```address``` attribute and use same ```DeploymentId```.all silos work.

a new question:
the ```silo3``` status doesn't be updated in database after  ```silo3```  suddenly break down.
then the ```silo2``` will break down later.[here is log]https://gist.github.com/vincentzh/6be1f526fce212583784)

is it a bug?

**Comment by gabikliot** [comment]
Looks like maybe your firewalls are misconfigured. You need to allow Orleans process ports 11111 and 30000. Also, make sure you are using the same bits everywhere and same config on all silos. The folders from where you are running them looks different (C:\Users\Administrator\Desktop\SiloHost1, D:\OpenSource\Orleans_Demo\SiloHost\bin\Debug). Maybe there is no problem, but looks suspicious.

**Comment by veikkoeeva** [comment]
@vincentzh It indeed looks like you have a firewall issue as soon as assemblies have been loaded, you start to get socket exceptions with the message " No connection could be made because the target machine actively refused".For instance, machine `192.168.1.125:11111` after scanning the assemblies cannot connect to `192.168.1.126:11111`. I wonder what is `192.168.1.126:53912` that I see in the logs, though. 

You can see help to configuring firewall [here](https://github.com/dotnet/orleans/tree/master/Samples). If it is easier, you can try to run all the silos on the same computer, you just provide a different port to them (e.g. see the samples).

**Comment by vincentzh** [comment]
@veikkoeeva and @gabikliot  thanks you replies,I will try it.

**Comment by vincentzh** [comment]
the problem is resulved.I will close this issue.
