### ISSUE TITLE
Streams: Why does the observer need to know about the stream provider?

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1142]
My [observer client](https://github.com/amamh/orleans-PipeStreamProvider/blob/master/Client/TestObserver.cs#L12-L17) is getting a stream from some grain and subscribing to it.

Orleans requires the client to know about the provider in its config file.
I understand that requirement for clients that will actually write to the stream, but for clients that only need to observe, I think it makes more sense not to require them to know about the provider's implementation.

Why can't the observing client simply request the stream from my grain and subscribe to it without knowing about the providers implementation?

**Comment by amamh** [comment]
I think I see why it's needed now. It's because the provider provides the [GetConsumerInterface](https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Internal/IInternalStreamProvider.cs#L25) method which the consumer needs.

**Comment by gabikliot** [comment]
In your code, you have `stream.SubscribeAsync`. That call is implemented internally via the Stream Provider. So Stream Provider code has to be present and loaded on the client machine. But this example, in your code, demonstrates that the client does not have to interact with the Stream Provider directly. The Stream Provider only needs to be loaded. The reason is that `stream.SubscribeAsync` is implemented differently for different stream providers: different stream providers use different pub subs, may use different delivery mechanisms, etc...

Alternatively, your `Subscribe2` example uses StreamProvider directly, which is also totally fine.
