### ISSUE TITLE
Telemetry behaviour is not the same as Logging, FileTelemetryConsumer is initialized when should not

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1165]
Telemetry has different behaviour and around interpreting `<Tracing />` configuration compared to previously used Logger. 
Particularly: Telemetry setup handles `<Tracing TraceToFile` attribute in the config in the same way as Logger, although Telemetry is using it for `FileTelemetryConsumer`.

Logger expects file format in TraceToFile if traces need to be written to file. Or it also allows _"false"_, _"none"_ and empty string "" values, which can be used to disable file logging.

Telemetry doesn't interpret it in same way - if one will put "false" or none "there" - telemetry will be enabled and start writing to Client-{DateTime}.log file. It can cause many issues, because app is often not allowed to write to the assembly folder. 

I think it's also the cause in #1156, at least it's the cause for my other comment on telemetry - at that point I has no tracing to file enabled anywhere but telemetry was writing data on the disk

Workaround to disable file-based telemetry collection is to set it to empty string, like below:

```
<Tracing TraceToFile="" ...></Tracing>
```

I think it's very important not to break expected behaviour as many may have 
`<Tracing TraceToFile="false"></Tracing>` in config, and the issue appears only in runtime - when telemetry writes data to a folder without permissions.

I'd propose to use completely separate configuration for telemetry and turn it off by default for everything. Also avoid to reuse any existing pieces of Tracing configuration for Telemetry configuration.

**Comment by gabikliot** [comment]
Agree on all points: "not to break expected behavior" and "to use completely separate configuration for telemetry and turn it off by default".

**Comment by galvesribeiro** [comment]
Hello there!

I will look at the issue of the config file is not being respected. 

Does this happen on client and server as well, right?

Regarding the design of the Telemetry API: If you look on the original Issue #992 I suggested during all it that Telemetry APIs was created as a completely different API than current logs in order to avoid disrupt the current APIs and in the future, after it evolve, we can even deprecate it. At the beginning @sergeybykov agreed with me on that point. After some input and a some people fighting so hard to not get a new API and instead inject method on Logger class, I decided to not discuss anymore and agreed with the suggestions and add the telemetry methods on it, instead of have it on a separated API and config.

Anyway, if now, we are going to get back on the original design no problem, I'm even more happy to do that way since it was the way I had planned. 

I tried so hard to explain that Telemetry/APM is something and Logging is something else that eventually happens to be inside telemetry but the community decided to make it as a single thing, so I did it. But lets keep it in the past...

I can change everything on #992 and put it as a different API. Anyone against it?

**Comment by centur** [comment]
I've noticed it on a client-side, haven't tested it for server-side as I do need explicit logging there :) Will give it a go tomorrow.

One extra note - can we please avoid mass re-writes ? This is a big change already, and I bet it's affecting not only me. Given all minor quirks related to a current release - I feel that now I want to stay on a stable ground a bit longer.

I've skimmed through #992 drama and not quite understand how decision behind putting methods on the Logger interface or on a separate Telemetry interface affects the fact that old and new logging\telemetry read same config value differently. Also it's not affecting "unexpected default behaviour" which we discussed a bit on gitter

**Comment by galvesribeiro** [comment]
Yes I agree. The config being ignored is something unacceptable! That was tested and I don't know (yet) what happened and will investigate.

FYI, the argument people were using when the decision was made is that they don't want to touch on the current Logger interface and neither they want to introduce a new public API, which I argued a lot a bout it on #992 but looks like weren't able to persuade them :)

From the developer perspective, there will be no changes. The Logger will keep having its Log methods, the config will get respected again, etc. The only thing is that the Telemetry Methods will be moved to somewhere else so IF the developer had configured it, something like `Grain.TelemetryManager.TrackXXX()` as was stated on the first design at #992. So, no big deal... Will keep the current log intact, and people can opt in for Telemetry API, which was suggested from the very beggining.

**Comment by kobynet** [comment]
Having the same issue, both in client and server, i am actually getting System.IO.IOException because   log file is being used by another process.

**Comment by galvesribeiro** [comment]
Thank you @kobynet for confirm it. Will investigate that.

**Comment by jason-bragg** [comment]
Related to legacy code which is being deprecated.
