### ISSUE TITLE
Project logo and branding

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1171]
Hi all, I want to raise an issue  to discuss potential project branding and logo. Throw your logo ideas here and lets discuss it. Orleans sticker is the one I really keen to put on my laptop.

A little input to start with :

Logo shape - Hexagonal, as mentioned in Gitter - http://hexb.in/ can be a nice starting point.
It'd be great if we can highlight Virtual Actors nature of the framework  and maybe Distributed nature:
Guy Fawkes mask, half of it is real and coloured, half of it - cloudy and misty - kind of virtual, not real.

As one of ideas for long logo (with a text) - some geeky sign but readable, maybe  "|| leans" like (Or)leans. O in (Or) part can be the sticker logo in hex form

**Comment by jthelin** [comment]
For reference, this is the "current" logo originally created by our friends in DevDiv, and which was used at the time when Orleans was built as an SDK drop.

https://raw.githubusercontent.com/dotnet/orleans/gh-pages/Icons/Orleans/OrleansSDK_128x.png

I definitely +1 the process of Orleans community ideas for creating a new logo / branding though. :)

**Comment by ghuntley** [comment]
# Branding
MSFT has a internal policy/routine to name projects after Cities. Orleans was the chosen name and has since become public without going through the usual rebranding process. Orleans is now pretty well known in the distributed systems community but not yet really known in the broader community thus rebranding may not be too late.

* MSR have commented that at least one enterprise client that has not adopted Orleans because of the word "Project". Client is judging the book by the cover/internal policy that forbids dependencies that include those words.
* Dropping "Project" from "Project Orleans" means it will be really hard to find answers on StackOverflow/Google as "Orleans" conflicts with multiple cities.
* "Orleans" has really good brand recognition within the distributed systems community.
* The "Orleans Framework" has been commonly used and said during presentations and talks.

My suggestion? Drop "Project Orleans" and become "Orleans Framework".

Create website at http://www.orleansframework.net and docs at http://docs.orleansframework.net

I own the [.net|.com] domains, happy to transfer ownership over to the .NET foundation.

# Logos

Up to grabs, I like the current logo but would be interested in seeing what the community comes up with.

# Stickers

Once logo is sorted out the next logical step is stickers. :-)

**Comment by angshuman-agarwal** [comment]
- "Avalon" => WPF
- "Indigo" => WCF
- Geneva => WIF
- **"Orleans"** => _WAF_ ("**W**indows **A**ctor **F**oundation")

**Comment by centur** [comment]
Recap of gitter discussion (all credits go to corresponding commentators there):

* OrleansFx (Orleans Framework)
* OrleansDFx (Orleans [Distributed] Framework)
* FabricFx 
* GrainFx
* The Distributed .NET Framework (aka fu service fabric)
* Schrodinger's Actor

Some logo concepts:

https://files.gitter.im/dotnet/orleans/7dBe/blob
https://files.gitter.im/dotnet/orleans/pt6K/blob
https://files.gitter.im/dotnet/orleans/Ytdj/blob

Opinions on naming:

Many ppl like OrleansFx - keeps "Orleans" tie, eases googling, good for tagging, sticks to CoreFx positioning.


>ghuntley: In topic of branding, I'm against appending Windows against the name. Ie Windows Actor Framework sets wrong tone especially with current movements with DNXCore and Open Source/Open at Microsoft.

> ReubenBond : Agree with @ghuntley re: WAF. People have a strong distaste for WCF (unfairly, I think, but still)

**Comment by angshuman-agarwal** [comment]
"Fx" suffix gives the idea of "**F**ore**x**" (as in currency trading).

**Comment by centur** [comment]
NancyFx, ActorFx and CoreFx teams probably disagree with this. For me personally - Fx is short for Framework first, and maybe then - Forex.

**Comment by angshuman-agarwal** [comment]
Well, for me, may be a different angle to look at [naming convention](http://www.investopedia.com/terms/f/forex.asp?header_alt=c). Just my viewpoint as that suffix still doesn't strike right (intuitive).

**Comment by Joshua-Ferguson** [comment]
@angshuman-agarwal 
   Agree, but I guess Microsoft is pretty good at re-branding stuffs (with codenames)

    "Avalon" => WPF
    "Indigo" => WCF
    "Geneva" => WIF
    "Astoria" => "WCF Data services"
    "Orleans" => WAF ("Windows Actor Foundation")

I would think Orleans Actor Foundation\Framework (OrleansAFx ?) would be better to differentiate from being a Windows only framework. OrleansFx & OrleansDFx also look good.

**Comment by angshuman-agarwal** [comment]
> better to differentiate from being a Windows only framework

Sorry - Did not quite get this reasoning ?

**Comment by jthelin** [comment]
> > better to differentiate from being a Windows only framework

> Sorry - Did not quite get this reasoning ?

A few years ago, i commented: "Microsoft needs to decide whether it is a software company, or a Windows company." 

I think the results of that vote are now fairly clear: 
Inside Microsoft there is probably as much work going on now with non-Windows platforms (iOS, OSX, Linux, Mono, Android, etc) as there is on Windows.

Including "Windows" in the name would be -1 IMHO, because it sends completely the wrong signal. 

Even Azure has "rebranded" from Windows Azure [~2008] to Microsoft Azure now for entirely similar reasons - it is "cloud" focused, not tied to specific OS.

"Cloud Actor Framework" might be another tagline option.

> Microsoft is pretty good at re-branding stuffs (with codenames)

Well, frequency of doing something is very different from that being successful.

Microsoft's product names are legendary in the marketing industry, and unfortunately not for the right reasons!
https://www.youtube.com/watch?v=EUXnJraKM3k
http://www.networkworld.com/article/2266200/software/the-10-worst-microsoft-product-names-of-all-time.html

**Comment by gabikliot** [comment]
+1 on Cloud Actor framework. Orleans Cloud Actors. ActorFx is also ok.

-1 on explicitly including Windows OR Microsoft in the name.

**Comment by ReubenBond** [comment]
>  ActorFx is also ok.

What would Brian Grunkemeyer (@briangru) say? Is [ActorFx](https://actorfx.codeplex.com/) still alive inside of MS at all?

I like the name ActorFx: it's authoritative and to the point. Maybe we could also adopt some ActorFx concepts into our project :stuck_out_tongue: They have some "cloud collections" which are conceptually similar to what I'd like to see in Orleans for storing unbounded data on grains.

**Comment by gabikliot** [comment]
Ohh, right, I meant of course OrleansFx. ActorFx is taken by that other project. I don't think we want to get into competing names and creating confusion. Maybe Sergey thinks differently? 

+1 on OrleansFx.

+1 on adding collection.

**Comment by centur** [comment]
Don't you feel that ActorFx is very generic, like CloudFx or PlatformFx - it has no individuality, same as VirtualActorsFx - it tags with the the concept but it can't make project to stand out of the crowd, Orleans in the name - does. Getting back to Microsoft names - all internal names like Avalon or Indigo or Astoria - they all are easy to recall and talk about, when they were renamed to more enterprise-friendly 3-letter alphabet soup acronyms - it simply lost the individuality.

What would you prefer to have in your stack - Katana \ Helios or OWIN self-host\IIS ? Kestrel or NextGenLibuvBasedHttpWebServer ?

**Comment by ReubenBond** [comment]
No problems, I agree with all of that @centur & @gabikliot. ActorFx isn't *too* generic, but I agree that there's little flair.

**Comment by briangru** [comment]
ActorFx is not currently being worked on or used within Microsoft.  It was a little too early, and built on a platform that wasn’t quite ready for the public at that point in time.  All of our documentation spoke of the “Actor Runtime”, which was a very early version of Azure Service Fabric.  https://azure.microsoft.com/en-us/services/service-fabric/

One of the ways ActorFx inspired future work was a feature within Azure Service Fabric called Reliable Actors.  You can read more about it here:
https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reliable-actors-introduction/
https://azure.microsoft.com/en-us/documentation/articles/service-fabric-reliable-actors-patterns-introduction/

That being said, ActorFx also included our first steps towards a “Base Class Library for the Cloud”, with Cloud Collections being our contribution in that space (as well as some plumbing for notifications of collection changes through LINQ queries).  While the collections were hosted in a highly available fabric in the cloud, the point was to use them from mobile devices and from Windows apps.  The protocol was built around JSON, to allow clients implemented in other languages on other platforms to interoperate as well.  Google Drive’s Realtime APIs expose basically the same feature set, plus one extra feature we didn’t build (a cloud-based String type, to be used as a core primitive in interactive text editors).  I think Cloud Collections was a very valuable concept and one that should live on in some form.

In a perfect world, we should either port these Cloud Collections to Orleans, or to the Reliable Actors implementation on top of Azure Service Fabric.  Of course, both could be done as well, providing a potential for performance testing the various platforms, and perhaps providing tradeoffs between highly available collections and mostly-available ones (depending on how robust the implementation on Orleans is – checkpointing on top of a replicated reliable store would be mostly sufficient).

I’m not aware of any plans from Sergey and company in this space.

**Comment by ReubenBond** [comment]
Thanks for chiming in, @briangru - I may have derailed the discussion a bit. I will be bringing up Cloud Collections at our roadmap meeting in Jan. SF Reliable Actors are much more similar to Orleans than to ActorFx, but SF Reliable Services' Distributed Collections look similar to ActorFx' collections. We can definitely build such collections on Orleans. Orleans can also leverage Service Fabric for storing collections locally.

**Comment by Joshua-Ferguson** [comment]
+1 Cloud Actor Framework, +0 ActorFx (a bit generic sounding)

If its called, Orleans Cloud Actor Framework it can be shortened to OrcaFx which comes with a built in mascot.

**Comment by centur** [comment]
Orcas was used before - VS2008 was Orcas
https://en.wikipedia.org/wiki/List_of_Microsoft_codenames
my votes are 

+1 for OrleansFx
+1 for any similar name which keeps Orleans name and identity
-1 for very generic names and 3 letter acronyms

**Comment by sergeybykov** [comment]
I think Orleans is a distinct enough brand already. OrleansFx is good because it follows the recognizable naming pattern and is neutral to the Orleans brand itself. OrleansFx would also help disambiguation with New Orleans, especially in searches.

ActorFx to me is out of question. It's a different project.

In general, I feel that stressing actors isn't really that necessary, and can even be counter-productive as few people out there are familiar with the actor model. Erlang and Akka have worked well brand wise without mentioning actors explicitly. I think actors are more of an implementation detail. The core value of Orleans isn't actors per se, but rather it's innate support for building distributed systems, its productive programming model, and scalability and performance "by default". Besides, Orleans is more than just actors today, e.g. Orleans streams.

I see the marketing message along the lines of "Orleans/OrleansFx - a framework for easily building of scalable cloud services." Even though the "cloud" part isn't 100% technically accurate as Orleans can as easily be used on premises, I think it is still good because that's the main market we are targeting.

I think our prospective users are looking for a framework to get the job done - to build future proof cloud services with least effort, good time to market, and no lock-in. Most of them don't care if it's actor based or not. Because of that, I think it is better to stress the value proposition of Orleans rather than its implementation details, at least at the elevator pitch level. For example, we found that "distributed C#" explanation coined by @gabikliot works really well as a conversation starter, even though it is obvious not 100% accurate either.

**Comment by craigsmitham** [comment]
+1 @sergeybykov

**Comment by jthelin** [comment]
[Off topic] Ah memories! 
`OrCAS` was also the name of the EJB server my startup company created - derived from "Orbware Component Application Server"
http://www.serverwatch.com/article.php/1126961
https://en.wikipedia.org/wiki/Cape_Clear_(software_company)

Was that really over 15 years ago? .... feeling ~~old~~ mature.

**Comment by jthelin** [comment]
+1 to keeping the "Orleans" name in there somewhere - that is already starting to build up some brand equity, although more still required.
https://twitter.com/JorgenThelin/status/680495131674345472

The other thing to keep in mind before settling on a new name is that the relevant Twitter handle and domain name registration are still available!

**Comment by gabikliot** [comment]
I have a question about naming.
I think we all decided to remove the word "Project" from the name.
Have we all settled on just having it Orleans?

For example, I just noticed that the Twitter Account now names it as "Microsoft Orleans". The handle is still: https://twitter.com/projectorleans, but on the page itself it says: "Official account for Microsoft Orleans."
The io page also says "Microsoft Orleans", instead of Orleans or Project Orleans.
Where did the "Microsoft" came from?
Are they adding Microsoft now to all products that started/originated/supported by MSFT: Microsoft Core.Net? Microsoft ASP.NET?

I am OK if that is what we all pick here together, but lets not change it yet again without agreeing.
My vote to simply keep it as **Orleans**.

It's not Typesafe's Akka, and not LinkedIn's Kafka, its not Yahoo's Hadoop.
If we seek adaption everywhere, lets really be open and not keep or even imply "inventor's rights".

**Comment by sergeybykov** [comment]
@gabikliot That was merely a change from "Microsoft Project Orleans" to "Microsoft Orleans".

**Comment by gabikliot** [comment]
How about we just remove "Microsoft"?

**Comment by sergeybykov** [comment]
@gabikliot 
My recollection is that several people expressed the opinion that it is better to keep "Microsoft" as an indicator that Microsoft actively funds the project, and it's not an abandonware.

Why are you so concerned about it?

I personally don't have a strong opinion one way or the other. I just don't think there is a need to change the naming in a haste. "Project" was odd, and as we learned it was keeping some potential users away. I don't see the same problem with "Microsoft" for a .NET-based technology.

**Comment by gabikliot** [comment]
I am not concerned, and neither I am suggesting to change anything in haste. I am raising the question, since this is the issue to raise those questions.
For example, twitter https://twitter.com/projectorleans says now Microsoft Orleans, which is just confusing.

**Comment by richorama** [comment]
My suggestion is a logo like this:

![orleans2](https://cloud.githubusercontent.com/assets/353138/15657747/d098af96-26ab-11e6-9663-6cbc6fc4565c.png)

It needs some tidy up, and should preferably available in a vector format. I don't know if anyone has the necessary skill/resource to make that happen?

It's based on the dot net foundation logo, but using hexagons to represent grains concept.

I think it would translate well onto laptop stickers, mugs, t-shirts and print media.

**Comment by angshuman-agarwal** [comment]
I feel it should be something on lines of nodejs logo - https://goo.gl/Kj1uAh

**Comment by ghuntley** [comment]
@richorama I like it.

re: vector 

I can make this happen.

**Comment by ghuntley** [comment]
@richorama I like it.

re: vector 

I can make this happen. 

re: dropping "project"

Yes.

re: "Microsoft" Orleans

No feelings either way, agree that it is important to demonstrate that Orleans is not abandonware and is internally funded. Had an interesting conversation on the weekend with a notable and respected old timer in the .NET community who remarked that Orleans won't be taken seriously by clients until it's a line item that can be sold with support.

Customer -> "I've heard about Orleans -> Microsoft Sales Rep -> "It's not supported, Service Fabric is - you can buy support for Service Fabric"

This commercial pressure can be offset via case studies, such as the recent one done with VISA.

**Comment by richorama** [comment]
I think you get pretty good support with Orleans, without paying for it...

**Comment by veikkoeeva** [comment]
@sergeybykov, @richorama I see @ghuntley's point in that it needs to look like there is MS staff working on it. The other one is that paid support probably comes in that there is a large community of people who can get help on the channel and elsewhere and people familiar or enthusiastic with it there will be help available. I'd like to divulge more, but maybe I could put it so the open nature and non-Azure with conventional relational makes it an interesting look in places currently. This is no way off from Azure, it looks good in that one can go to Azure, even simulatenously, and it it is not mutually exclusive with SF.

**Comment by ReubenBond** [comment]
What do people think of this?

![orleans logo](https://cloud.githubusercontent.com/assets/203839/15736027/5ec79080-28e0-11e6-873d-346179fbf9c0.png)

**Comment by richorama** [comment]
I prefer your logo @ReubenBond

**Comment by richorama** [comment]
The only problem is the cutline when creating die cut stickers. Perhaps for a sticker or something you would just use the hexagon?

![untitled](https://cloud.githubusercontent.com/assets/353138/15739567/7d5d469e-28a8-11e6-8056-596bcc0d06ad.png)

**Comment by richorama** [comment]
Could I suggest switching to a non-arial font? This is `Segoe UI Light`:

![orleans](https://cloud.githubusercontent.com/assets/353138/15747280/ee99cb92-28d1-11e6-8791-10a92d89804e.png)

**Comment by sergeybykov** [comment]
No objections or other ideas have been raised in 13 days. Let it be the one. No need to split hair I think. Thank you, @ReubenBond and @richorama!

**Comment by richorama** [comment]
I wonder if @martinwoodward has any buget/resource for marketing? I'm thinking of a new website template, stickers, etc...

**Comment by martinwoodward** [comment]
Stickers definitely. If you want to submit a PR to add your logo to the dotnet/swag repo I'll do the honors. Agree that the hexagon might work best as a die cut sticker. Just let me know.

Regarding website template, what are the requirements there? I could then get some quotes and see if I can find budget for that.

**Comment by richorama** [comment]
Thanks @martinwoodward! 

@ReubenBond has the original source files, I'm happy to do the PR, but I don't have the SVG format, etc... Reuben, could you supply these?

In terms of a website template, we're currently using jekyll and gh-pages to build a static site: http://dotnet.github.io/orleans/

It would be nice to have a better looking template, which could fit in with the colours and style of the logo. 

The vscode documentation looks really nice (as an example): https://code.visualstudio.com/docs/d

**Comment by sergeybykov** [comment]
Looks like this is all covered now.
