### ISSUE TITLE
Building a workflow engine in Orleans

### ISSUE THREAD

**Issue by SeanFarrow** [dotnet/orleans#1200]
Hi,

I was just wondering whether there was any support for the process manager (or saga) pattern in Orleans. I know pub/sub/observer is supported and wondered whether anyone had written a sample of a process manager.
I know other frameworks such as NServiceBus support this natively and am trying to compare my options for a large project I'm involved in.
Any help/advice appreciated.
Kind regards
Sean.

**Comment by jthelin** [comment]
Xref: http://www.codeproject.com/Articles/731007/A-Look-At-NServiceBus-Sagas

> So what is a "Saga"? Well in NServiceBus, a "Saga" is a long running workflow that has these basic characteristics:
> - It is potentially (though not always) long running
> - Is made up of a number of different steps (these are encoded as message handlers in NServiceBus)
> - May be persisted to some backing store (RavenDB / MSMQ / SQL Server). This ensures that Sagas are durable
> - Sagas are reliable thanks to the MSMQ underlying transport usage
> - May be restarted after being stopped
> - May be completed

**Comment by gabikliot** [comment]
Are you asking about workflow? I don't know what "process manager" or saga is. If you are asking about how to implement workflow in Orleans, I can provide details.

**Comment by SeanFarrow** [comment]
Hi,

I’m basically looking to implement a long-running process.
Cheers
Sean.

**Comment by gabikliot** [comment]
Why do you need Actor model to kick off a process?

**Comment by rore** [comment]
@gabikliot Can you provide some details about the multistep workflow you mentioned? Sounds interesting.

**Comment by veikkoeeva** [comment]
In addition to what @jthelin wrote:
A few resources on sagas that I find are good:
* [Applying the Saga Pattern by Caitie McCaffrey](https://speakerdeck.com/caitiem20/applying-the-saga-pattern) (of Halo and Orleans fame)
* In general, and with .NET example code, the Azure queuing guru Clemens Vasters [Sagas](http://vasters.com/clemensv/2012/09/01/Sagas.aspx).

As observations.

**Comment by lmagyar** [comment]
What about WF4 from System.Activities? That is very like a Saga, though it uses complete state persistence of the activity executor ("saga execution coordinator" equivalent in WF) instead of log/event source.
* I've already put successfully the WorkflowInstance/ActivityExecutor behind a grain to run on Orleans scheduler, wrapped to be async/await, added idempotency (for forward recovery), auto-reactivation (in case of any crash), it handles persistence and reminders with Orleans instead of SqlWorkflowInstanceStore, can execute activities on the "tail" of an already replied public Grain request/method call, etc., but this is only on a POC/experiment level! With rudimentary tests only!
* I've separated the "what" and "when", the "what" part is POCO strategies and commands, and only the "when" part is WF/Activity. Basically you don't need to write any Activity to use it, just drag&drop the generic ReceiveRequest, SendResponse, SendRequest, ReceiveResponse activities in the designer.
Though I need several weeks to dare to upload it to Github, and I have to update it to Orleans v1.1.0. :/

**Comment by gabikliot** [comment]
@rore, basically I was thinking about the following:
You divide the workflow into steps, each step is a separate grain call.
When step is done as part of the step the grain checkpoints the step result and calls the next grain to do the next step.
In addition, you use reminders to ensure that flow eventually finishes, in presence of failures. Start one reminder per flow, when the flow starts. The reminder will be tight to that flow only, and when woken up it will check the last checkpointed step and if the workflow did not finish, it will re-kick the grain of the first not finished step.

This is a very simple scheme to get started.
I believe @galvesribeiro is using such a scheme in his service, to process credit card transactions. He moved away to this architecture from the traditional Windows Workflow Foundation. He can provide more details.

Once you have this, you can actually go ahead and make it more generic. The logic in the base grains will be responsible to "move the flow forward" (kick the next step) while the application grains will only encode the step logic. And you will have some way to describe the flow graph to the base grain - either by static annotation on the grain step methods (FlowName = MyFLow, StepNumber=X) or by dynamic runtime information exposed by the application grain to the base grain. Also, in this general framework, instead of creating one reminder per flow, you can have a predefined pool of reminders ("flow reliability service") which periodically scan all checkpointed steps (can be partitioned by flow Id) and resume the stuck ones.

The benefits you get from Orleans when building such a workflow are: 
a) if you are just building a simple one or two flow scenario just for your service, you can go with option one, its easy to build, native part of with Orleans, and you take zero dependencies on any other system.
b) if you are building a general purpose workflow service (like I presume you are asking about), the advantage are the virtaul actors - you don't need to pre-allocate any resources/pre-create any services to execute the workflow logic, plus the reminders, which can be used to build periodic database scanner (checkpoints database in this case).

**Comment by lmagyar** [comment]
@gabikliot WF4 does exactly the same, step = activity, when step finishes, WF4 executor checks the flowchart/state machine what to do next, and sends the appropriate delegate/Task to the scheduler. There is cancellation, compensation, error handling, parallelism, fancy designer, etc. out of the box, and I believe the overhead is minimal or less, than a custom general workflow: the executor persists only it's "instruction pointer" in the flowchart/state machine (yes I oversimplified), it does not persists the complete flowchart, that was WF3.5. The original WF4 persistence did exactly what you described: periodic check in the SQL database for runnable but not running (ie. crashed) WFs, I replaced this with flow specific reminders exactly as you described.

I know everybody is horrified only by the words "Workflow Foundation". I really would like to know if there is a real disadvantage using it, or only the high complexity, steep learning curve and poor documentation is the cause? Orleans replaces I think at least 80% of the pain in the original WF4, I absolutely agree with you: the virtual actors are invaluable!!!!!!!!

**Comment by veikkoeeva** [comment]
@lmagyar I don't know about horrified about the "Workflow Foundation" words, but as a tangential, it'd be cool if someone implemented an inference engine on actors. For the lack of better examples, I refer to [Planning in Games: An Overview and Lessons Learned](http://aigamedev.com/open/review/planning-in-games/) wherein game characters could be seen as actors. I believe, although I have never used that WF4 implements a forward-chaining engine ([Rete](https://en.wikipedia.org/wiki/Rete_algorithm)?) and it'd be interesting to have such a thing "natively" in Orleans.

**Comment by galvesribeiro** [comment]
Hey got summoned here! So let me drop my 2 cents.

@lmagyar I was a very hard user of WF since its first release. It is an awesome piece of tech which make business process to be modeled very quickly with its "fancy designer". 

As @gabikliot mentioned, he helped me to move from WF to Orleans by simplifying my processes and rely on (static) actors instead of (dynamic) activities to define my business workflow. I missed some features like for example the ability to change a customer/tenant transaction process on the fly as I used to do on WF but it gave me other quick wins by using Orleans.

I maybe didn't invested (the deserved) enough time in order to adapt WF runtime to Orleans task scheduler.

WF has its own thread model based on SynchronizationContext, its own persistence model and its own failure handling. I do believe that we can get WF to leverage Orleans Runtime features and I would like to see and help your work on that so far(it could be a nice project to be added to OrleansContrib) however, we are making a big effort to move Orleans to coreCLR and System.Activities is currently a blocker to it. I've spoke with WF teAm sometime ago and they are starting a full redesign of it. The main problem is that System.Xaml and System.Transactions (main dependencies of WF) were not OSS-ed, which makes dificult to have it ported as is today.

So, I think the combination of Virtual Actors with a Workflow Engine is something extremely powerfull and I(we) could start an issue to support at core runtime some Workflow/process execution engine like WF after it got coreCLR support. 

What do you think?

**Comment by lmagyar** [comment]
@veikkoeeva A real inference engine would be also invaluable. :) Sadly WFx is only plain procedural programming (simplified: it executes an UML activity diagram), nothing inference, nothing Rete. WF3 has a standalone rule engine, simple forward-chaining, no Rete, this is the only part of WF3 that is not obsolete, but as I know it hasn't developed forward, no equivalent in WF4 (that is why it is not obsolete inside WF3 I suppose). IMHO WF4 is best for business transactions.

**Comment by lmagyar** [comment]
@galvesribeiro WF and Orleans both single threaded, it was a one-liner, only reentrant grains required some queuing on incoming requests (I used/modified/repaired AsyncEx for this). I've rewritten persistence based on WorkflowApplication, I hope the activities/extensions won't notice the change, and as I remember failure handling is in ActivityExecutor, it hasn't changed. SqlWorkflowInstanceStore persists "reminders" and the state in one step, it was a little bit tricky to serialize the steps of reminder update and state write to survive a crash during persistence. - But it is only on experiment level, I need few weeks to facelift it. :)

Yes, I know, it is not coreCLR compliant, this contrib won't be portable. :( But if Orleans+WF4 works, I think it's much more scalable than the "plain" WF4. But to make it a reason for coreCLR support, I need lot of help, I'm not an expert of WF, not an expert of Orleans, I'm not a well experienced developer, just reckless to play with them. Really.

I've never used the update functionality of the WF4, it really exceeds my brains capacity. In my concept, all the "algorithmic" logic goes into POCO classes, and the WF only contains the "flow". If you need to change the structure of the flow on the fly, I have no experience with it (in our payment system, we had no need to modify the flow on the fly, it changes nearly only once a year, all the logic is in POCO, any developer can update/test that, without knowing anything about WF). This adds composition to the WF, who draws the flowchart, knows only the strategies (strategy pattern) it uses, absolutely no knowledge about the connected, continuously changing partner systems, even the data of the business transaction is outside of the WF's scope. The connected systems' interface modules are publishing the concrete strategy implementations, we compose a WF at run time using them.

**Comment by galvesribeiro** [comment]
> WF and Orleans both single threaded, it was a one-liner, only reentrant grains required some queuing on incoming requests (I used/modified/repaired AsyncEx for this).

Never used AsyncEx. I always tough it was not so good hehehe, maybe bad impression.

> I've rewritten persistence based on WorkflowApplication, I hope the activities/extensions won't notice the change, 

We should evaluate a way to leverage Orleans persistence frameworks to make the Activities persistence there. Not just a checkpoint, but the whole workflow state (including WF variables and argument values). You probably should implement a persistence participant for a high level injection or for a deep integration use a Store itself (more here https://msdn.microsoft.com/en-us/library/dd489420(v=vs.110).aspx )

> and as I remember failure handling is in ActivityExecutor, it hasn't changed. 

Orleans exception propagation should be leveraged.

> SqlWorkflowInstanceStore persists "reminders" and the state in one step, it was a little bit tricky to serialize the steps of reminder update and state write to survive a crash during persistence.  

Again, Orleans storage could be leveraged.

> But it is only on experiment level, I need few weeks to facelift it. :)

Just put anything you have when you can on your github :) don't be shy :P

> Yes, I know, it is not coreCLR compliant, this contrib won't be portable. :( But if Orleans+WF4 works, I think it's much more scalable than the "plain" WF4. But to make it a reason for coreCLR support, I need lot of help, I'm not an expert of WF, not an expert of Orleans, I'm not a well experienced developer, just reckless to play with them. Really.

Well, it can still be a nice **DNX451** contrib that don't work on **DNXCORE50**. It is just a matter of set the right target framework on project.json and you are good. No problem at all. 

> I've never used the update functionality of the WF4, it really exceeds my brains capacity.  In my concept, all the "algorithmic" logic goes into POCO classes, and the WF only contains the "flow". If you need to change the structure of the flow on the fly, I have no experience with it (in our payment system, we had no need to modify the flow on the fly, it changes nearly only once a year, all the logic is in POCO, any developer can update/test that, without knowing anything about WF). This adds composition to the WF, who draws the flowchart, knows only the strategies (strategy pattern) it uses, absolutely no knowledge about the connected, continuously changing partner systems, even the data of the business transaction is outside of the WF's scope. The connected systems' interface modules are publishing the concrete strategy implementations, we compose a WF at run time using them.

The update is pretty simple. You just save your Workflow definition file (.xaml) - in my case - on Azure blob storage, and load the WorkflowApplication based on that XAML so, whenever you need to update the logic, just change the WF in the designer and save it to the blob. This way we could keep multiple workflow definitions for the payment transaction process (for e-commerce and for physical terminals) for each of our customers (tenants) without even need to shutdown or reboot the silo. Pretty easy to do it. Actually we have a set of pre-defined custom Activities so the XAML was used to guide its flow. 

I believe many of Workflow Foundation(v4+) pieces could be extended/replaced to be "special grains" so it can leverage basic Orleans Runtime. It is something that must be designed "to" Orleans.

**Comment by galvesribeiro** [comment]
AH, and about Saga, etc, just to clarify, any WF-based workflow is actually a long-running workflow by definition. The only difference is if you call the Persistence APIs (by one of the several ways on WF framework) or not.

Regarding Strategy pattern compared with Activities, I believe activities are more like Static classes with static methods. We only encapsulate actions on it like *EncryptPINActivity*, *ParseTracksActivity*, etc. The persistence is of the Workflow State, not the Activity State.

**Comment by lmagyar** [comment]
@galvesribeiro I was way too short, there are some misunderstanding. :)
**Persistence:** It uses Orleans State persistence and Reminders!
**Exceptions:** They are propagated before a grain incoming request's response has been sent, but after WF runs on the tail of the request, the grain must/can handle/log the exception, by default the WF is aborted on an unhandled exception and will be reloaded on the first incoming request or by the reactivation reminder.
**Update:** I thought you updated the WF definitions behind already running WF instances, because that is also possible in WF4, but rocket science for me. Certainly you can use newer and newer WF definitions for the *new* WF instances, but the already running WF instances will use the definitions they were created with. (OK, this is the situation in our live "plain" WF4 environment, in the experimental project the WF definition is a parameter of the ctor, if it doesn't match the persisted version, load fails... Though I plan to use Orleans' DI.)
**Strategy pattern:** We agree on the "static classes with static methods". Based on your example there is a TerminalStrategy with EncryptPIN and ParseTracks method/command, and there is a general Activity that can start these methods (the method/command name is a parameter of the Activity, the concrete Strategy is the parameter of the grain that is backed by the WF, the grain and the WF communicates only the names of the incoming/outgoing methods/commands: the incoming requests are Bookmarks, those are already strings, so I used strings for the other direction, I like symmetry. It will be easy to understand after you see the code.)

I've already started the facelifting, keep calm, I must finish it before my surgery in mid January. :) Yes I'm shy, this is my first OSS project, and it's much more complex than I expected.

**Comment by galvesribeiro** [comment]
Hahahah Ok, I see...

The point is, the way you are stating you will have 1 grain type per WorkflowApplication... My Idea was to have a WF running on several grains for example, each Activity would be a single grain type, which is invoked by the main workflow which is hosted on a single grain. So, you have 1 Grain for the WorkflowApplication, + 1 Grain for each activity that is running inside of it. The whole challenge was to coordinate the threads inside the workflow with the grains since it doesn`t even support async/await and use events to notify stuff like persistence, exception handling, tracing, etc.

re Update, we can update a running/persisted workflow with a new definition. There is a merge/update operation supported by the engine.

**Comment by lmagyar** [comment]
With my concept you can call external grains in each outgoing command, but you don't have to do this, you can put everything inside the grain that is backed by the internal WF. It depends on the situation, and the WF definition doesn't know anything about this. This way it is easy to keep the necessary info in 1 consistent State and minimize the unnecessary inter-grain communication.

**Comment by galvesribeiro** [comment]
I understood. That was the first suggestion @gabikliot  made to me when I was joining Orleans world however, this way, I couldn't leverage the "distributed" part/features of Orleans on a single process by spreading its parts along silos on the cluster. This was 1 scenario. But you could be right. We could host the Worflow itself on a single Grain, and make the real operations to happen on other grains by the activity calls. Interesting... 

I'm just curious how to deal with async/await/Task/Task<T> if the current WF implementation doesn't use it and instead uses its own SynchronizationContext.... Just be warned that .Wait() and .Result are not good things todo on Orleans. 

By that time I even started my own WF engine, which worked as a concept. The Workflow definition was 100% coreCLR compliant, and was serializable as Json. I just had a hard time to get Expressions working. But that is another subject :)

**Comment by lmagyar** [comment]
WF uses IAsyncResult, it's easy to "convert" back and forth to Task. I used AsyncEx, because Task.Factory.FromAsync() uses TPL scheduler instead of Orleans, but AsyncEx had to be repaired for the CompletedSynchronously case (it was a problem in .Net40 also, see referencesource).

WF uses SynchronizationContext.Post() to execute delegates, I redirect it to Orleans scheduler with Task.Factory.StartNew(), this is the one-liner. But works, as I've tested, it hasn't escaped the scheduler.

I prefer to use already existing code: if I write a general engine, I will end up with an ActivityExecutor. :) Though coreCLR compliance is an issue.

**Comment by galvesribeiro** [comment]
Hey @lmagyar did you have a chance to look at it and maybe push to some repo somewhere?

**Comment by lmagyar** [comment]
Yes, I'm working on it day and night, really, next week I will upload it!

**Comment by gabikliot** [comment]
Hi @Imagyar!
Were you able to make any progress on the workflow work? It sounds very interesting.

**Comment by lmagyar** [comment]
Yes, the Core finally works again, rudimentary tests are green again (I've added xml doc and comments, but at several places refactoring was easier than explaining some weird concept). Now I add new Sample/Demo and some description Readme files. Approx. 2 days and I upload it!

**Comment by galvesribeiro** [comment]
Good new @imagyar! Looking forward to get it :)

**Comment by lmagyar** [comment]
Finally I did it: https://github.com/lmagyar/Orleans.Activities (there is only a Hello Word sample, elaborate sample soon)

**Comment by galvesribeiro** [comment]
@lmagyar you are the man! Nice code and docs/diagrams!

I'll test it in details asap and report back my findings...

Also, if you allow it, I would like to add it to Orleans/Contrib repo so we can get contributions centralized there from everyone.

When you have time, come on Gitter and lets talk about the project.

Good work!

Thanks!

**Comment by lmagyar** [comment]
Thank you, it's an honor to be in contrib. :) After the meetup I'll be on gitter.

**Comment by galvesribeiro** [comment]
:+1:
