### ISSUE TITLE
AzureTableStorage Provided limits the state's size to 64kB of raw/string data

### ISSUE THREAD

**Issue by piotrwitkowski** [dotnet/orleans#1217]
This is due to the fact, that it attempts to serialize the grain state to a single azure table "column". 

This could be easily extended to approx. 1MB by slicing serialized stream into 64kB chunks and storing them into sequential "columns"

**Comment by jthelin** [comment]
The general recommended best practices are to keep grains small and loosely coupled, although there are times it is necessary to vary those "rules".
http://research.microsoft.com/apps/pubs/default.aspx?id=244727
- Loosely coupled, isolated, mostly independent
- Grain Sizing - For throughput, usually better to use many smaller grains than few large grains,
but overall best to choose grain size & types based on application domain model, Example: Users, Orders, etc

There is already a community written `OrleansBlobStorageProvider` that uses Azure Blob storage instead of Table store, which allows up to 4MB of state to be stored per grain.
https://github.com/OrleansContrib/OrleansBlobStorageProvider

If you wanted to go beyond that size, it would be theoretically possible to write a storage provider that uses Azure Page storage or Azure File storage instead, but i don't think anyone has looked at that specifically yet. 
https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/#storage-limits

HTH.

**Comment by piotrwitkowski** [comment]
Thanks for the feedback Jorgen. In my scenario I reuse an existing azure table copying util for backup purposes so adding new storage type is not ideal. Also some of my serialized (and packed) data may exceed the 64kB boundary. Plugging into "fat" azure tables would be easiest to implement otherwise I would need to extend the backup solutions to handle blobs / files.

I'd be happy to contribute to that enhancement (assuming extension to the existing azure table provider with backward compatibility).

**Comment by jthelin** [comment]
Yes, additional enhancements and contributions from the community are always welcome :)
http://dotnet.github.io/orleans/Contributing

**Comment by veikkoeeva** [comment]
> If you wanted to go beyond that size, it would be theoretically possible to write a storage provider that uses Azure Page storage or Azure File storage instead, but i don't think anyone has looked at that specifically yet.
https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/#storage-limits

I'll cross-reference https://github.com/dotnet/orleans/issues/1176. The relational storage limit is basically the limit of the underlying file-system, I think. A recent improvement is also asynchronous streaming to and from the underlying relational storage that should improve performance and stability in this kind of a scenario.

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1587.
