### ISSUE TITLE
Unable to add orleans cloud service silo worker to an azure virtual network

### ISSUE THREAD

**Issue by sirkirby** [dotnet/orleans#1232]
I've followed the instructions here http://dotnet.github.io/orleans/Advanced-Concepts/Using-Azure-Web-Apps, but with no success. I'm able to create and add the web app to the virtual network, but when I add it and then publish my cloud service, I receive "The virtual network does not exist". I did find some information that the new "resource manager" based virtual network may not be compatible with cloud services. Is this true? and if so, how can I work around this aside from deploying my web app as a web role in the same cloud service. Thank you!

**Comment by galvesribeiro** [comment]
Hey @sirkirby,

The new Azure Resource Manager(ARM) does not have (yet) Cloud Services on it. If you are creating a new vNetwork using ARM(default in new portal) instead of Classic Management APIs(only option on old portal) you can't use on Cloud Services by setting the .csconfig file.

In order to it work, the vNet must be created with one of the two options:
1. By using the old portal
2. By using the new Portal but selecting on the first screen on the wizard to use Classic management APIs.

Then you should be able to use both Cloud Service services on the same vNet and even on different subnets inside the same vNet.

Note that there was an annoying bug on the new Portal (idk if they already fixed that) which concats the Resource Group name to the vNet name if you create it using the new Portal and Classic APIs mode so even if you add to the .csconfig the right name, you still get the same error. The workaround is to create the vNet from the old Portal however, if you do that, you are not able to add the vNet to the same Resource Group and instead Azure will create a Resource Group behind the scenes with the same vNet name. This happens because old portal does not have the concept of Resource Groups.

Actually this is an Azure common issue since their migration from old -> new Portal wasn't just a new UI and instead, they introduced the ARM and the Resource Groups model to the APIs which breaks some stuff that used to work.

Even if it is not directly related to Orleans, feel free to reply here or ping me on our Gitter channel if you have any problems and I'll try help. I had several problems in the past with vNets since I have a pretty complex deployment on our environment even involving multiple vNets and in diff geo-location.

I hope it helps!

**Comment by sirkirby** [comment]
Apparently the bug still exists. I was able to create the Classic vnet and get my Web app connected....however I still get the error when deploying the cloud service worker. I'll try again with your suggestion of creating the vnet in the old azure portal.

**Comment by galvesribeiro** [comment]
Shame on Azure Portal team :-1: 

This was reported by many people (including me). Note that after you create the classic Vnet on new portal, look at the resource name or even better, try get the name from the powershell cmdlets... You will see exactly what I mentioned. Creating it from old portal should work for you. 

Let me know if you got it working or fall in problems.

**Comment by sirkirby** [comment]
Creating the network, subnets, and gateway in the manage.azure.com portal did the trick! I now have my web app and cloud service workers on the same vnet. I really appreciate your help with this!

Hopefully this gets cleaned up by the Azure team in the near future.

**Comment by galvesribeiro** [comment]
Glad to help @sirkirby! Feel free to close this issue and if you want more help ping again by reopen it.
