### ISSUE TITLE
Cleanup NuGet Packages

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#125]
Creating this issue as placeholder for discussions of any further cleanup and enhancements to the Orleans NuGet package contents and structure.

Initial discussion centered around PR #123 and PR #124

**Comment by ThomasWeiss** [comment]
Is it possible to use Orleans from NuGet only, without installing with the msi?
Right now, trying to install from NuGet (Microsoft.Orleans.Server, for example) always fails for me:
```
Install failed. Rolling back...
Install-Package : Unable to uninstall 'Microsoft.WindowsAzure.ConfigurationManager 2.0.0.0' because 'WindowsAzure.Storage 1.7.0.0' depends on it.
```

**Comment by veikkoeeva** [comment]
As you noticed, there are some dependency issues with the Nuget packages in Orleans. [This PR](https://github.com/dotnet/orleans/pull/100) should fix this particular one.

As a general note, at least the current version of Nuget handles dependencies somewhat lackingly. A good writup on dependency handling issues is at [Paket FAQ](http://fsprojects.github.io/Paket/faq.html).

As a related note, when PR 100 is generally done, should we run "Update-All" on all of the project dependencies? There are some packages which would get an update. Also, what I experience is that many Nuget packages bump version regularly in order to include update dependencies frequently. Perhaps Orleans ought to adopt the same routine.

**Comment by sergeybykov** [comment]
Yes, the biggest blocker here is https://github.com/dotnet/orleans/issues/79 which is being worked on by @veikkoeeva and @gabikliot. Once it is fixed (hopefully, very soon), we'll update the nugets to remove the fixed version reference.

The workaround of force-uninstalling ConfigurationManager may actually work, although we haven't tried it.

**Comment by sergeybykov** [comment]
I hope https://github.com/dotnet/orleans/pull/165 should fix the burning dependency/installation issues, now that we moved off the 1.7 storage. I'm pretty sure this is not the final version of the nugets, just a step in the general direction.

**Comment by sergeybykov** [comment]
1.0.3 NuGet packages with dependency on Azure Storage 4.2 have been published to nuget.org.
