### ISSUE TITLE
Provider of type Orleans.Providers.SqlServer.SqlStatisticsPublisher name 'SqlServer' was not loaded.Please check that you deployed the assembly in which the provider class is defined to the execution folder. 

### ISSUE THREAD

**Issue by vincentzh** [dotnet/orleans#1300]
I created a web api as Orleans Client.
 I always get the error after restart IIS
 ```Provider of type Orleans.Providers.SqlServer.SqlStatisticsPublisher name SqlServer was not loaded.Please check that you deployed the assembly in which the provider class is defined to the execution folder. ``` 
then I must  republish web api to fixed it.

how to resolve it?

**Comment by veikkoeeva** [comment]
@vincentzh Drive-by commenting, it results from https://github.com/dotnet/orleans/blob/a64fa8953e764ac391ebd549d395ac66374b545f/src/Orleans/Providers/ProviderLoader.cs#L67. It's called from https://github.com/dotnet/orleans/blob/a64fa8953e764ac391ebd549d395ac66374b545f/src/Orleans/Providers/StatisticsProviderManager.cs#L26 and that in turn from https://github.com/dotnet/orleans/blob/fde0ba29adcddda6b6080d70f1dd15971bbccede/src/Orleans/Runtime/OutsideRuntimeClient.cs#L158 in the client case, I believe.

How do you restart the IIS? I wonder if the AppDomain is really recycled and/or where the assemblies end up. Do you have `AlwaysRunning` set?

**Comment by vincentzh** [comment]
@veikkoeeva I restart IIS manually,and I don't set the autoStart="AlwaysRunning".that is why I get the same error when I visit the web api with many hours in between

**Comment by vincentzh** [comment]
I still get the error after I set AutoStart="AlwaysRunning",so I think this is a bug.

**Comment by vincentzh** [comment]
I guess the problem is  https://github.com/dotnet/orleans/blob/master/src/Orleans/Providers/ProviderTypeLoader.cs#L54,
in web project,we should use `BuildManager.GetReferencedAssemblies()` to instead of `AppDomain.CurrentDomain.GetAssemblies()` to  load assemblies.

**Comment by vincentzh** [comment]
I found a temporary solution:
Add the code in `Application_Start()` 

```
 Assembly.Load(typeof (SqlStatisticsPublisher).Assembly.GetName());
```

**Comment by sergeybykov** [comment]
@vincentzh Is there a way to reproduce this in a unit test? That would help figure out what's going on there and why the assembly is failing to get loaded at the right time.

**Comment by veikkoeeva** [comment]
@vincentzh Ah, my apologies, I missed your note on `AlwaysRunning`. It looked me to that the AppDomain is not unloaded and consequently or the assembly does not find it for some other reason. It's difficult to tell from here what's the problem, but [Fuslogvw](https://msdn.microsoft.com/en-us/library/e74a18c4(v=vs.110).aspx) should give you some insight as to where the assembly is tried to loaded and why the loading fails. I don't remember if the logs could tell something about too, I believe it should give quite detailed information on assembly loading and failure thereof when set to `Verbosity3`.

**Comment by vincentzh** [comment]
@sergeybykov I just confirm that it happened after IIS recycle,I don't know how to use a unit test to reproduce it.  :)
@veikkoeeva the problem is not about why the loading fails.it is about the OrleansSqlUtils hasn't be load in AppDomain after IIS recycled.

Only Orleans.dll be found in https://github.com/dotnet/orleans/blob/a64fa8953e764ac391ebd549d395ac66374b545f/src/Orleans/Providers/ProviderTypeLoader.cs#L54 
then, `fullConfig.Type` is `Orleans.Providers.SqlServer.SqlStatisticsPublisher` ,but  `typename` is not equal to `fullConfig.Type` in https://github.com/dotnet/orleans/blob/a64fa8953e764ac391ebd549d395ac66374b545f/src/Orleans/Providers/ProviderLoader.cs#L183,

I guess we should get OrleansSqlUtils.dll too from https://github.com/dotnet/orleans/blob/a64fa8953e764ac391ebd549d395ac66374b545f/src/Orleans/Providers/ProviderTypeLoader.cs#L54.

**Comment by veikkoeeva** [comment]
@vincentzh The problem you see is real, no doubt. So, we can conclude

1. The AppDomain is indeed unloaded upon recycle.
2. The AppDomain is re-loaded upon restart since the ProviderTypeLoader is run.
3. For some reason when reloading without redeploying the type `Orleans.Providers.SqlServer.SqlStatisticsPublisher` isn't found in the loaded assemblies.
4. The reason to to `3.` looks like being that only `Orleans.dll` is in the list of assemblies.

Does that reasoning make sense? I wonder if [Fuslogvw ](https://msdn.microsoft.com/en-us/library/e74a18c4%28v=vs.110%29.aspx) would shed more insight. Why isn't the assembly loaded? Could it be some process has a hang of it (as you may know, IIS can be tuned in various ways on how it uses threads and processes)? You try disabling [show copying](http://www.ipreferjim.com/2012/04/asp-net-appdomains-and-shadow-copying/) or not just recycling the AppPool, but [restarting the the whole IIS](http://tecadmin.net/restart-iis-via-command-line/) to see if there is a difference.

@sergeybykov I suppose you don't have an idea here? Or @jthelin?

**Comment by sergeybykov** [comment]
@veikkoeeva I don't at the moment. IIS works in mysterious way to me. I suspect once we add support for loading an explicit list of assemblies, this may go away.

**Comment by sergeybykov** [comment]
I don't see what we would do here.
