### ISSUE TITLE
Builds for OrleansContrib

### ISSUE THREAD

**Issue by martinwoodward** [dotnet/orleans#1334]
Creating a new issue to discuss the question of builds for https://github.com/OrleansContrib/ as raised by @amccool / @richorama / @sergeybykov in #1205 

https://github.com/dotnet/orleans/issues/1205#issuecomment-174725692

Basically is there a build process etc or should we set something up?

**Comment by martinwoodward** [comment]
As @richorama [notes](https://github.com/dotnet/orleans/issues/1205#issuecomment-174720686) you can use Travis. Personally I use AppVeyor for these types of projects as that's really easy to set up for and free to run for OSS projects.  The .NET Foundation has a Pro-FOSS account with AppVeyor and though individual projects in the https://github.com/OrleansContrib/ are not usually in the .NET Foundation if anyone needed access to a Pro-OSS account for OrleanContrib stuff then drop me a line (martin@dotnetfoundation.org) and we can have a chat about getting you set up.

**Comment by richorama** [comment]
Thanks for creating the issue!

As it stands, there's nothing set up.

One thing to be mindful of, is that OrleansContrib isn't necessarily all .NET (there is currently [one node.js project](https://github.com/OrleansContrib/node-orleans) written in JavaScript). I'm hoping that there will be an increasing trend in projects written in not-.NET. As the API into Orleans becomes standardised (as is on the roadmap) we should see clients written in a variety of languages.

Therefore I don't think a 'one size fits all' approach will work in the long term. However, I can see the value in having the convention/advice/best practice of having a standard platform that we're all familiar with. I also see that _most_ projects will be .NET.

Up until now I've been using [TravisCI](https://travis-ci.org/) to build a [few pieces](https://travis-ci.org/OrleansContrib) but this has been problematic because it's a mono build running on linux. Visual Studio unit tests don't work, and there was a problem with the Orleans templates on xbuild.

I've been playing with [AppVeyor](https://www.appveyor.com/) and I'm very impressed. I have just moved [this project](https://github.com/richorama/ra-db) on to it, which took about 5 minutes.

It's free for OSS, it builds using msbuild, it seems to be up-to-date.

Any thoughts?

**Comment by martinwoodward** [comment]
I agree that doing it on a case-by-case basis makes most sense - depends on what you are building and what the project maintainers feel most comfortable with. If you do need any help from the .NET Foundation though let me know.

**Comment by richorama** [comment]
thanks @martinwoodward  - appreciated!

**Comment by richorama** [comment]
I tried moving [OrleansBlobStorageProvider](https://github.com/OrleansContrib/OrleansBlobStorageProvider) over to AppVeyor as an experiment. 

It builds, but the unit tests fail is it is unable to start a silo.

I expect the build it not allowed to open ports :¬)

https://ci.appveyor.com/project/richorama/orleansblobstorageprovider/build/1.0.6#L426

**Comment by sergeybykov** [comment]
It's unclear from the output if it is port related or maybe a missing file of file system permission. Is there a way to get the silo log?

**Comment by richorama** [comment]
I'll look into it..

**Comment by martinwoodward** [comment]
If you get stuck, always worth dropping a note at their support site - the community always seems pretty good at helping get an answer or logging an issue with AppVeyor if needed http://help.appveyor.com/

**Comment by richorama** [comment]
Ha success! 

https://ci.appveyor.com/project/richorama/orleansblobstorageprovider/build/1.0.7

My bad. It was attempting to connect to the Azure Storage Emulator (which obviously wasn't there).

To fix it I set an environment variable for a real azure storage account in the appveyor settings, which the unit tests pick up and use instead of the emulator.

**Comment by amccool** [comment]
+1 on appveyor, I'm using it for my GH projects as well.  And many thanks for starting this issue up!!

**Comment by richorama** [comment]
ok, I'll start moving my projects across...

**Comment by sergeybykov** [comment]
:+1:

**Comment by richorama** [comment]
I think this thread can be closed. I believe we've reached a consensus :¬)
