### ISSUE TITLE
Strange behaviour of single host silo on start.

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1366]
This is an issues to attach logs of failing silo init from a Gitter chat with @sergeybykov 
Quick recap: 
Due to some event my Silo (single instance, Cloud Service-hosted role) was declared dead ("why" is out of scope). I've restarted the that instance side by side with webrole and while they were "Restarting" - I've cleaned up OrleansSiloInstances table records ( but I haven't deleted the table itself)

When Silo host instance  got back online - it added more than one record to OrleansSiloInstances table. When it stabilized - I saw these records in the table: [OrleansSiloInstances Table Content.csv.txt](https://github.com/dotnet/orleans/files/114960/OrleansSiloInstances.Table.Content.csv.txt)

After I connected to that VM via RDP I found these logs :

[DBCloud.ActorsHost_IN_0-StartupError-2016-02-03-00.38.37.480Z.txt](https://github.com/dotnet/orleans/files/114941/DBCloud.ActorsHost_IN_0-StartupError-2016-02-03-00.38.37.480Z.txt)
[DBCloud.ActorsHost_IN_0-StartupError-2016-02-03-00.37.46.517Z.txt](https://github.com/dotnet/orleans/files/114942/DBCloud.ActorsHost_IN_0-StartupError-2016-02-03-00.37.46.517Z.txt)
[DBCloud.ActorsHost_IN_0-StartupError-2016-02-03-00.36.45.986Z.txt](https://github.com/dotnet/orleans/files/114943/DBCloud.ActorsHost_IN_0-StartupError-2016-02-03-00.36.45.986Z.txt)

**Comment by gabikliot** [comment]
1) please attach the full logs, in addition to the startup error files (no need for same start up errors again)
2) why would you "cleaned up OrleansSiloInstances table records .. while they were "Restarting" ? Clean it up when nothing is running and don't modify it while the service is running/starting/restarting.

I can't really say much if you were deleting/messing up wit the table while it is running.
**NEVER mess up with the table while silo is running!**
Next time, do a full 100% stop, make sure nothing is running, delete the full table-  just delete the table -  and do a clean start. Then send full silo logs, plus startup errors if any, plus table snapshot like you did now. Alternatively, if the service was running ok, all was good, then service died and you restarted it - also an OK scenario, still - DO NOT touch the table! If it fails to start, send the logs+errors+table copy.

When you manually restate the service, are you sure Azure did not restart the prev. instance as well, so you had 2 instances trying to run at the same time?

**Comment by gabikliot** [comment]
BTW, it appears that the service is running fine:

"7b8bec1e194d4c20ae5fee3cf6c00083","100.79.154.28-11111-192155949","2016-02-03T01:29:32.4414240Z","100.79.154.28","7b8bec1e194d4c20ae5fee3cf6c00083","0","192155949","RD0003FF6C5E53","2016-02-03 01:29:33.134 GMT","DBCloud.ActorsHost_IN_0","11111","30000","DBCloud.ActorsHost","2016-02-03 00:39:09.120 GMT","**Active**",""

**Comment by centur** [comment]
Yes, it's running fine now. 

Ok lets assume that mess was caused by record deletion. Given that I have only single silo instance for each silo I can delete only 1 row per active deployment ( which wasn't active really, as it was rebooting ). This may explain 1 dead row, but not 3.

Attached StartupError logs show that silo got (409 Conflict) 3 times before wrote successful record.

**Comment by gabikliot** [comment]
Could it be that you started one instance and also azure started one at the same time? Do u have full logs?

**Comment by centur** [comment]
Unfortunately I don't have full logs.

I'm not clear on what do you meant by me "started one instance and also azure started one at the same time". The only thing I can think about is it somehow related to prev deployment. I tried to correlate that in chat but tangled things up and decided to separate. 
So "previously on timeline" (if that helps anything)

* I deployed a new build package to the staging slot (different deploymentID, should not interfere with one in Prod). To save costs for dev env we always have 1 instance of worker role and 1 instance of webrole (no SLA but whatever - it's dev)
* I waited for staging VMs to stabilize and then did a VIP swap.
* Called our health endpoint and some others from WebAPI and saw a green light. So I've deleted old environment in staging slot.
* Then suddenly new build silo died ( gave timeouts and stopped to respond to clients) - checked SiloInstances table and saw it's marked as dead (the context is still the same - 1 instance of silo in prod, no running build in staging, how can it mark itself dead ?)
* I decided to restart Web and worker instances and to reduce the noise in the tables - clean them up. So I send restart to instances in prod and (because it takes some time) - quickly deleted statistics tables but just cleaned up SiloInstances one (I was assuming that silo was still rebooting), as started to refresh it to see when silo begin to bootstrap.
* After some time I saw what's in the snapshot of the table - Silo adds a record then marks it dead, adds another - dead again, stabilised on the 4th entry.

As Sergey pointed in chat.- I checked the VM for logs and found what's attached above. 
I know that it's pretty strange case and doubt it can be easily reproduced, I just trying to understand how single silo deployment can mark it's own record as dead ?

**Comment by gabikliot** [comment]
> I just trying to understand how single silo deployment can mark it's own record as dead ?

Silo may decide to kill itself. If the silo runs alone (only one), I can not think right now what could cause a healthy running silo to decide to kill itself. The good news - the cause is in the log. So next time grab the log please.

When silo starts, if it finds an older instance of itself in the table (same ip:port but earlier epoch), it also marks that older instance as Dead (if not Dead already). So if the silo lets says tried to start, fails, tries again 3 times and eventually succeeds, that explains why you see 3 Dead rows and one Active row. The last Active instance marked all previous active instances as Dead.

Now the question you may be asking: why the first silo died? And why it took 3 silo restarts while you only deleted the table one time?
I do not have the answers and it really does not make sense to speculate. If we had logs, I would most probably have the answers. Given the info we have, I can only say:

From the external standpoint, it all looks very good - despite some unexplained failures and mistaken deletes of the table "under the foot" of the trying to start silo, the system overall self-stabilized and recovered relatively quickly. The first silo appears to start at 00:36 and the last Active one started at 00:39. So in 3 minutes (which is prolonged basically by different timeouts in the silo attempts), the system self healed. Looks pretty remarkably and awesome to me actually! 

Why it failed in the first place and why it took 3 attempts - both important questions which I would love to answer, but unfortunately without logs there is nothing we can do.
