### ISSUE TITLE
OneShot retrigger timer. Disposed Timer keeps invoking the callback on the period

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#1371]
Not sure if this bug has been reported, but couldn't find any discussion. 
I am running Orleans 1.0.10 (.Net 4.5)

Use case: 
A device on the field needs to wait a blanketing time after service to calibrate.
The implementation uses grains and basically the PSEUDO goes like this

        private async Task OnService()
        {
            //Register OneShot and wait for the angle to stabilize
            _tmrCalibrateAfterService = RegisterTimer(OneTimeCalibrateCallback, this, TimeSpan.FromMinutes(STABLE_TMO), TimeSpan.FromMinutes(30));

            Debug.WriteLine(string.Format("{0:G}\t[{1}] RegisterTimer OneTimeCalibrateCallback", DateTime.Now, HwIdentity));
        }

and the callback:

        private async Task OneTimeCalibrateCallback(object grain)
        {
            //Cancel the timer by disposing it.
            _tmrCalibrateAfterService.Dispose();

            await CalibrateAsync();
        }

Problem 1) I am seeing the calibration every 30 minutes (as the period), even the timer has been disposed.

Problem 2) If I service the device twice before the **dueTime** expires, it is registering 2 different timers and now both are kicking every 30 minutes.

My goal is to build a **Retrigger OneShot timer**
If the Registration occurs before the dueTime expires, restart the dueTime to the new setting, but don't start a new timer.
Also when dispose, don't kick periodically.

Question 3) Does the timer stop the grain from deactivation?

Regards,
Uri

**Comment by sergeybykov** [comment]
Just like with `System.Threading.Timer`, to register a one-off timer you need to pass a `TimeSpan.FromMilliseconds(-1)` as the period argument. I don't see that in your code snippet.

1) Is it possible that you overwrite `_tmrCalibrateAfterService`, and hence don't dispose the timer you intend to?

2) You probably need to keep track of the fact that the timer has already been registered to avoid registering more than one.

3) Presence of a timer by itself doesn't prevent a grain from getting garbage collected. But invocation of a timer callback does reset the idle time of the grain. So it the timer keeps firing before the grain becomes eligible for garbage collection, it will prevent it from getting collected.

**Comment by gabikliot** [comment]
Everything is correct in what Sergey wrote, except for last bullet - http://dotnet.github.io/orleans/Advanced-Concepts/Timers-and-Reminders, "When activation collection is enabled, the execution of a timer callback does not change the activation's state from idle to in use. This means that a timer cannot be used to postpone deactivation of otherwise idle activations."

If you want to postpone deactivation, use `DelayDeactivation`: http://dotnet.github.io/orleans/Advanced-Concepts/Activation-Garbage-Collection

In general, timer dispose works correctly. I am pretty sure it disposes the timer correctly, and no tick will happen after dispose. I am very confident we don't have a bug there. We  achieve this strong guarantee, as opposite to .NET Timer which does not strongly guarantee that, since we fully control the scheduler (and have turn based concurrency, meaning there are no races).

The bug is most probably in your code, exactly where Sergey pointed out.

**Comment by sergeybykov** [comment]
@gabikliot Thanks for correcting me! Can't rely on memory 100%.

**Comment by gabikliot** [comment]
@ukluk , were you able to fix your code and validate the fix?

**Comment by sergeybykov** [comment]
I'll close it. @ukluk please reopen if something isn't working as expected.

**Comment by gabikliot** [comment]
:+:
