### ISSUE TITLE
PVS-Studio: Double-checked locking implementation in Orleans.StreamImpl looks dangerous.

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1398]
[Double-checked locking] pattern implemented a bit dangerous. Does this even valid to lock on non-static non-volatile object ? [Jon Skeet's article on similar matter][Implementing the Singleton Pattern in C#]

**V3054 Potentially unsafe double-checked locking. Use volatile variable(s) or synchronization primitives to avoid this. Orleans StreamImpl.cs 142**
**V3054 Potentially unsafe double-checked locking. Use volatile variable(s) or synchronization primitives to avoid this. Orleans StreamImpl.cs 144**

```
        private readonly object initLock; // need the lock since the same code runs in the provider on the client and in the silo.

...
 internal IInternalAsyncObservable<T> GetConsumerInterface()
        {
            if (consumerInterface == null)
            {
                lock (initLock)
                {
                    if (consumerInterface == null)
                    {
                        if (provider == null)
                            provider = GetStreamProvider();
                        
                        consumerInterface = provider.GetConsumerInterface<T>(this);
                    }
                }
            }
            return consumerInterface;
        }     
```

[Double-checked locking]: https://en.wikipedia.org/wiki/Double-checked_locking 
[Implementing the Singleton Pattern in C#]: http://csharpindepth.com/Articles/General/Singleton.aspx

**Comment by gabikliot** [comment]
I don't think there anything wrong with this code.
Static is required when you implement Singleton pattern, this is not a Singleton pattern, although it looks similar.
Volatile is NOT required, since there is a lock in between the checks, and the lock serves as a memory barrier. See: https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Microsoft_.NET_.28Visual_Basic.2C_C.23.29

Since initLock is readOnly, this pattern is gold.

**Comment by sergeybykov** [comment]
By design.
