### ISSUE TITLE
Orleans refuses to start when using SqlServer storage

### ISSUE THREAD

**Issue by jinhong-** [dotnet/orleans#1408]
I am actually trying to use SQL as the membership provider for orleans. For whatever reason, when i tried to use the configuration for SqlServer system store, orleans will always refuse to start.

I set this value in the configuration.
<SystemStore SystemStoreType ="SqlServer"
                 DeploymentId="OrleansTest"
                 DataConnectionString="Data Source=.\SQLExpress;Initial Catalog=Orleans;Integrated Security=True;Pooling=False;Max Pool Size=200;Asynchronous Processing=True;MultipleActiveResultSets=True" AdoInvariant="System.Data.SqlClient" /> 

Seems like it gets stuck somewhere during the startup phase with the last line of log being this:
"MembershipOracle starting on host"

**Comment by jinhong-** [comment]
I managed to resolve this.I should have used the .sql script that was bundled with the nuget package itself. I used the one here https://github.com/dotnet/orleans/blob/master/src/OrleansSQLUtils/CreateOrleansTables_SqlServer.sql which i got linked from http://dotnet.github.io/orleans/Advanced-Concepts/Configuring-SQL-Tables

**Comment by veikkoeeva** [comment]
@jinhong- Nice to see you made progress and updated here. If you come up ideas for documenting or anything that helps in deploying or debugging, please do share here. I think here is OK if you already have an idea you just want to drop somewhere, or you could open an issue, or if you prefer chatting, pop by to make a few notes at [Gitter](https://gitter.im/dotnet/orleans). Maybe we should provide an Hello World example with relational storage to make it a bit more apparent the database is not deployed automatically (maybe one where the script is wrapped to a database project)?

Now that you are experimenting, I should point out there is an unfortunate bug as described at https://github.com/dotnet/orleans/issues/1365.

**Comment by combrinckd** [comment]
Hi, I am unsure as to what script you used to fix the issue. I have tried both from the link as well as from nuget and still the host does not want to start, with the last line being the same as you said. Any suggestions?

**Comment by veikkoeeva** [comment]
@combrinckd You should use the script in the Nuget package to deploy the database. After you deployed the database, did you manage to open it with the exact same connection string you gave to Orleans?

If you take the script from Orleans master here and try with binaries from the Nuget package, it might not work due to some incompatibility. I don't remember if there were any in this particular case, but that is a possibility.

**Comment by combrinckd** [comment]
Ok, I am looking at this again after a while now. I have created the tables with the correct script, and now I have commented out most of the config already and yet it still doesn't start the local silo when I want to use SQL. Any suggestions at this point will be greatly appreciated.

My Config file
[config.txt](https://github.com/dotnet/orleans/files/136078/config.txt)

My log file
[log.txt](https://github.com/dotnet/orleans/files/136081/log.txt)

**Comment by veikkoeeva** [comment]
@combrinckd I'm on the move currently, but it looks like Orleans tries to reach the DB and then just hangs. There are plenty of reasons that can cause it. Some notes:
* To me your connection string looks atypical due to having only `localhost` defined without an instance (and no integrated security). It's likely OK, but might there is something about configuration somewhere.
* Setting up the state provider for relational is currently a bit difficult if you haven't actualy deployed the scripts (they are currently separate).

To do some smoke testing, could you try the settings [here](http://dotnet.github.io/orleans/Advanced-Concepts/Configuring-SQL-Tables)? The reason I ask is that LocalDb should be installed with Visual Studio and and accept integrated security. This way we should be able to rule out much of the configuration issues. If you are using Visual Studiop 2015, you could open the *View -> SQL Server Object Explorer* and create a database named *Orleans*. See the attached image.


![sqlserverobjectexplorer](https://cloud.githubusercontent.com/assets/5158694/13144442/4f322020-d653-11e5-890a-92d312265ad9.png)

**Comment by combrinckd** [comment]
Hi @veikkoeeva 
Ok, so after I completely removed all content from the Nuget packages folder (deleting everything) and uninstalling Orleans Nuget packages, then reinstalling the latest version for Orleans nuget packages again, it picks up the settings and starts up. 
Doing the same on the clients also seemed to have done the job. Previously I just updated the packages from nuget manager, which as you know then leaves the old version (1.0.10) of the Orleans nuget packages still in the solution package folder. By having this still there, it seems to still use something from version 1.0.10 which then causes the issues I've been having. 
So, for now it looks like it is running as expected.

Thanks very much for the assist!!!

**Comment by veikkoeeva** [comment]
@combrinckd No problem on my part. :) Maybe this should be closed now, @sergeybykov. :)

**Comment by sergeybykov** [comment]
Thank you, @veikkoeeva!
