### ISSUE TITLE
AzureQueueStreamProvider violates at-least-once delivery

### ISSUE THREAD

**Issue by gabikliot** [dotnet/orleans#1416]
As was mentioned in https://github.com/dotnet/orleans/issues/1410#issuecomment-181136279 
`AzureQueueStreamProvider` uses a `NoOpStreamDeliveryFailureHandler` which results in a situation that even if a stream message was not delivered to the consumers, it will be deleted from the queue, thus failing to guarantee at-least-once delivery.

I am pretty sure that the initial version of `AzureQueueStreamProvider` provided that property, but later on the code underwent a lot of refactoring and iterations, and this property was lost.
It should be pretty easy to fix it.

One way is to modify `IStreamFailureHandler.OnDeliveryFailure` to accept also the failed batch. In AzureQueueStreamProvider implement it by marking some boolean flag `failedToDeliver` on the `AzureQueueBatchContainer`. When calling `MessagesDeliveredAsync` in `AzureQueueAdapterReceiver`, just skip the `IBatchContainers` that have this `failedToDeliver`  flag set and don't delete them from the queue.

**Comment by gabikliot** [comment]
Any feedback on that @jason-bragg ? Do you agree with the fix strategy?

**Comment by jason-bragg** [comment]
@gabikliot 
I think that would work, but I suspect we can take this approach without passing the batch to the call.  The sequence token is being passed, so we should be able to match messages that failed delivery by the token.

In the long run, I don't think this is the correct solution, because the IStreamFailureHandler is intended to communicate these errors to the application.  Application developers should plug in their own IStreamFailureHandler with their own error handling logic, so using it for proper functioning of the provider would be contrary to it's intended usage.

I don't have a good solution to this yet.

**Comment by gabikliot** [comment]
I agree that `IStreamFailureHandler` was originally added with different intention.
OK, lets brainstorm a different solution. If we don't find a better one, we can go back to  `IStreamFailureHandler`.

How about we pass this info via `IBatchContainer` itself. Add 2 properties: `NumDeliveryAttemps` and `NumFailedDeliveryAttemps`. The agent will increment those, and then the queue adapter can act accordingly. No need to involve `IStreamFailureHandler` at all. Ad those counters can actually be useful, to some other future adapter, to do some other smart "adaptations", like decide too do something with this msg after X `NumDeliveryAttemps`. Or maybe we only need one property: `NumFailedDeliveryAttemps`.

**Comment by gabikliot** [comment]
@jason-bragg , any comments?

**Comment by jason-bragg** [comment]
@gabikliot 
Managing this data through the IBatchContainer is an option, but it's the cache that currently communicates delivery information to the receiver.  In the short term, I suggest we record delivery errors via the IQueueCacheCursor, and use that information to modify what the SimpleQueueCache reports during its purge cycle.

**Comment by gabikliot** [comment]
@jason-bragg , please provide more concrete details about your suggestion:  what fields to add to IQueueCacheCursor, and how it will work. I don't immediately see how it will work, since cursor moves, meaning we will need to store something in the data itself.
I already suggested 2 alternatives, so if you have a third option, please be more specific.

**Comment by jason-bragg** [comment]
@gabikliot 
My suggestion was more about ownership of responsibility rather than implementation.  If there is general agreement that it makes sense for the cache to be (remain) responsible for tracking and reporting delivery state, I'll make a pass at some implementation details.

    public interface IQueueCacheCursor : IDisposable
    {
        IBatchContainer GetCurrent(out Exception exception);
        bool MoveNext();
        void Refresh();
        void RecordDeliveryFailure();
    }

The cache keeps a list of items that could not be delivered and the call adds the current item to that list. When SimpleQueueCache.TryPurgeFromCache is called, it assembles a list of purged items, then removes any items, from both the purged items list and the failed to deliver list, which are common to both lists.

In this way, only items that are delivered will be passed to the IQueueAdapterReceiver.MessagesDeliveredAsync call.

This approach is not ideal, because the TryPurgeFromCache is expected to return any items that were purged from the cache, not just those that have been delivered.  This is why I'm suggesting this as a short term solution.

**Comment by jason-bragg** [comment]
In the longer term, Unfortunately, I suggest something more radical. :/

Items come from the receiver, into cache, then are delivered.  Once delivered, the cache purges the items, and receiver is told about the purged items, assuming that purged items were delivered.  All of this is managed via the agent through a series of receiver and cache calls, as the agent negotiates between the two.  In my view, this negotiation by the agent is unnecessary and limiting. 

I suggest a tighter coupling of the cache and receiver, and for delivery errors to be propagated through the consumer’s cursor.  Consider a receiver interface something like:

    public interface IQueueAdapterReceiver
    {
        Task<IList<Tuple<StreamId,StreamSequenceToken>> QueryStreamActivity(TimeSpan timeout);
        IStreamCursor GetStreamCursor(Guid streamGuid, string streamNamespace, StreamSequenceToken token);

        Task Initialize(TimeSpan timeout);
        Task Shutdown(TimeSpan timeout);
    }

This is a cache+receiver hybrid.  It reports stream activity via the QueryStreamActivity call, which replaces the GetQueueMessagesAsync call.  When this is called, streams with activity on them are registered or activated as is currently the case for all the streams returned by GetQueueMessagesAsync, but instead of the agent being involved in negotiating between the receiver and the cache, the receiver adds items directly into the cache.  When a consumer is registered to read a stream it gets a stream cursor (which replaces the IQueueCacheCursor).  Any delivery errors are reported on the IStreamCursor and how/when queue data is cleaned up is up to the implementation, allowing much more flexibility.  This flexibility is introduced by removing the responsibility of negotiating between the receiver and the cache from the agent.  In this model, the agent is only responsible for managing subscriptions and delivering events to consumers.

**Comment by gabikliot** [comment]
I think efficient implementation is important here, not less and maybe even more that the question of ownership of responsibility. I am actually not sure who's responsibility it is to track delivery status: cache, adapter or batch itself. **The more important thing for me is: you gather requirements and scenarios and adjust/refactor/align your interfaces accordingly, to fit all requirements.**

In this particular case, it does not make much sense to build yet another list of items that could not be delivered. We can mark them in the item itself. Less state, much more natural. That is why I suggested `IBatchContainer.NumFailedDeliveryAttemps`. It is good for all sorts of tracking/telemery, write back maybe to some other places, ... Imagine in the future we will want to write those items into another storage. The writes are done in the adapter, not in the cache. How would you communicate that? Add another interface between cache and adapter? Why, if we already have it this way, in the data itself?

What is wrong with `IBatchContainer.NumFailedDeliveryAttemps` option?

As for the future/radical longer term - lets discuss it when the longer term arrives.

**Comment by jason-bragg** [comment]
Compromise?
Add the NumFailedDeliveryAttemps to the AzureQueueBatchContainer, and set it via the cursor?

> I think efficient implementation is important here, not less and maybe even more than the question of ownership of responsibility.

I disagree.  Ownership of responsibility IS very important, as the adapter is an integration point.   The efficiency of the implementation is important, but implementations can be optimized and tuned, the interfaces of the integration points (influenced strongly by responsibilities) are, imo, a higher priority.

At the heart of my suggestion is the conclusion that the interaction between the receiver and cache are not generalizable enough for the agent to negotiate between the two components, so it shouldn't do so.  The agent should manage subscriptions and deliver events and the receiver should manage the queue and cache messages as needed.  This means that information needed to manage the queue (like delivery failures, should be communicated to the receiver in some way.  My specific suggestion was to do this via the cursor, but I'm open to other suggestions.  The delivered batch is never passed back to the receiver, so putting it in there does not fit this approach.

> You gather requirements and scenarios and adjust/refactor/align your interfaces accordingly, to fit all requirements.

I'm unclear where my proposal violates this.  The following is my view, at this time.  It's subject to change, but this position has been forming over some time.
The agent should be responsible for managing subscribers and delivering messages from the queue.  It should not know about the cache or negotiate between it and the receiver.  The agent should not care if there is a cache or not.  The fact that the agent manages these things limits the supportable patterns.  There are many examples of this.
- issue #756.  In this case the user wanted to implement a more complex cache that would have readers from various points in the queue.  Since the agent negotiates between the single receiver and the cache this pattern could not be supported.  Had the agent simply focused on subscription management and delivery, there would be no issue.
- Azure Queue stream provider requires that events be deleted from the queue in a timely manner, while EventHub requires that receiver checkpoints be written.  Because the agent is responsible for negotiating between the agent and receiver, a mechanism was put in place that suited the azure queue stream provider needs, but was not well suited for eventhub checkpoints.  Had the agent not been involved, each adapter could have easily negotiated these interactions appropriately for the type of queue.  
- The EventHub stream provider must cache data for extended periods of time.  To do this the structure in the cache differs from the structure of the data transmitted to the consumer in the IBatchContainer.  Because the agent involves itself in negotiating between the receiver and the agent, this would mean that the receiver would need to construct one batch container to get queue data into the cache, then a different batch container to get the data from the cache to the consumer.  By removing the agent from negotiating between the receiver and the cache, the adapter can directly convert the received data to the cached format, then into a batch container when delivered, which is faster and cleaner.

The above are not the only issues with the current pattern but they are the most noteworthy.  By limiting the agent’s responsibilities to managing subscriptions and delivering messages, the agent would be simpler and enable a wider range of queue management and caching patterns.

> What is wrong with IBatchContainer.NumFailedDeliveryAttemps option?

While I am not, at this time, in a position to spend time refactoring the agent to fit the above pattern, I am quite hesitant to introduce more logic that relies on the current pattern.  Marking the delivery failure in the batch is effective only if the batch is eventually passed back to the receiver.  This is the case for the Azure Queue Stream Provider, but not for the EventHubStreamProvider, as this assumes that the batch that is being delivered is also the same batch that is being passed back to the receiver, during the purge.  By marking this in the cursor, we make it the responsibility of the cache and if/when the negotiation between the cache and receiver is removed from the agent, this will effectively be telling the receiver directly.

>It is good for all sorts of tracking/telemery, write back maybe to some other places, ... Imagine in the future we will want to write those items into another storage. The writes are done in the adapter, not in the cache. How would you communicate that? Add another interface between cache and adapter? Why, if we already have it this way, in the data itself?

Do you mean write the messages that failed to deliver to another storage?  I'm somewhat unclear on what you're getting at, as the cache is part of the adapter.  If the cursor is from the receiver and we tell the cursor the message was not delivered, the receiver could write failed messages to storage any way it wanted.  It's an implementation detail, but it would have all the information it needed..  though it's quite possible I misunderstood what you meant.  Please feel free to clarify.

**Comment by gabikliot** [comment]
> Add the NumFailedDeliveryAttemps to the AzureQueueBatchContainer, and set it via the cursor?

Sounds good to me, BUT:

The cursor is part of a generic SimpleCache, we don't have a special AzureQueue cache, so the cursor works with IBatchContainer, not with AzureQueueBatchContainer. So how I can do that without adding `NumFailedDeliveryAttemps ` to `IBatchContainer`.

How about the following compromise:
Cursor.RecordDeliveryFailure

**Comment by jason-bragg** [comment]
I took a look at the code, and we're already tracking other info related to the batch in the cache, so we can keep the delivery failure flags with that info.

**Comment by jason-bragg** [comment]
AzureQueueStreamProvider violates at-least-once delivery bug fix #1491

**Comment by gabikliot** [comment]
Fixed via #1491.
