### ISSUE TITLE
TestingSiloHost throws an Exception when instantiating silo

### ISSUE THREAD

**Issue by creyke** [dotnet/orleans#1449]
OneTimeSetUp: System.Exception : Exception during test initialization: 
Exc level 0: System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Orleans.Runtime.Silo+SiloType,OrleansRuntime, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Orleans.TestingHost.TestingSiloHost.LoadSiloInNewAppDomain(String siloName, SiloType type, ClusterConfiguration config, AppDomain& appDomain)
   at Orleans.TestingHost.TestingSiloHost.StartOrleansSilo(SiloType type, TestingSiloOptions options, Int32 instanceCount, AppDomain shared)
   at Orleans.TestingHost.TestingSiloHost.<InitializeAsync>d__16.MoveNext()

**Comment by creyke** [comment]
I believe this to be a bug? @jdom appears convinced of this also.

**Comment by jdom** [comment]
Hi @creyke, there's not too much context there. I suppose it has to do with the way NUnit shadow-copies files to run the tests. I imagine you test project might not be strongly referencing some DLLs so they might not be copied automatically by the NUnit runner. I would tend to look for issues in that regard.

I created a very simple repro app with tests in both MsTest and NUnit. Please see attached: [OrleansTestingDemo.NUnit.zip](https://github.com/dotnet/orleans/files/143124/OrleansTestingDemo.NUnit.zip)

Also, this exception in particular I have seen before, and was work-around by calling `SerializationManager.InitializeForTesting()` before the constructor that starts up the silo is invoked. I haven't nailed the cases where it would happen, but that exception can basically occur for many reasons, so please try making sure all assemblies are present for the runner to use. If there is a way to disable shadow copying, you might try that too.

**Comment by gavinrunsdavies** [comment]
Hi @jdom. Firstly thanks for the attached app with nUnit tests. It's proved very useful in trying to setup our Orleans prototype project for unit testing.

A couple of observations first. 
1) @creyke above error seems to be down to NCrunchs execution of the nUnit tests
2) The tests run ok with the Visual Studio nUnit test runner
3) I could not get them to run with nUnit 2.6 from the command line only nUnit 3. This i'm happy with.

When trying to set up the tests in our test project using the same Orleans version etc I get 

Error : Tests.HelloWorldSiloTests.SayHelloTestnUnitTest
System.InvalidOperationException : Cannot find generated GrainReference class for interface 'GrainInterfaces.IHello'  

This is after copying the tests and code in to or project (albeit we have the interfaces and Grains in the same project). 

After comparing the two solutions etc it seems that the TestingSiloHost relies on the GrainCollection (or GrainInterfaces) to have the Code Generator and templates included from NuGet:

  <package id="Microsoft.Orleans.OrleansCodeGenerator" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.Orleans.Templates.Interfaces" version="1.1.2" targetFramework="net461" />
This seems a little odd, and not idea as it is not need to run the code in a production Silo.

Is this a bug with the TestingSiloHost and does it need to be brought up to date with the rest of the Oreleans code base?

**Comment by jdom** [comment]
I'm not sure I followed your set up. Are you not using the code generator from NuGet in prod? Are you using runtime code generation?
Is the issue arising from having both interfaces and grain implementations in the same project?

**Comment by gavinrunsdavies** [comment]
I'm not using the code generator from NuGet in production and no runtime code generation the Silo run fine without these.

I had considered the same thing about the interfaces and grain being in the same project but if I added the NuGet packages (sorry these should have showed in the original post) the test passes.
` <package id="Microsoft.Orleans.OrleansProviders" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.Orleans.TestingHost" version="1.1.2" targetFramework="net461" />
 `

**Comment by jdom** [comment]
I'm still struggling to understand. You added those packages to your test project and it now works? So there is no issue other than you where missing some assemblies in the test project that runs the silo?

**Comment by gavinrunsdavies** [comment]
Sorry, these packages were added to the Grains project not the test project. I haven't tried just adding them to the test project - do you think that would resolve it?

**Comment by jdom** [comment]
I'm pretty sure the test project already has TestingHost. Nevertheless, as I mentioned in the attached demo app, you also need to add OrleansProviders to it (to the test project), so yes, if it's not there already, it might solve your issue.

**Comment by gavinrunsdavies** [comment]
Sorry, my bad. Somehow managed to include the wrong packages in the comment above. Should have been
`<package id="Microsoft.Orleans.OrleansCodeGenerator" version="1.1.2" targetFramework="net461" />
  <package id="Microsoft.Orleans.Templates.Interfaces" version="1.1.2" targetFramework="net461" />
  `

The Provider and TestingHost packages are in the test project. Re-reading the above comments I can now see why it's confusing!

**Comment by jdom** [comment]
I see, now that makes more sense :)

Before going into solution mode, a few things:
For Orleans to work, you must use either compile-time or run-time code generation. It does not work without it.
- Compile-time codegen has the advantage that you'll see errors in Visual Studio when you build, for example if a certain serializer is missing or the types cannot be generated. This approach only supports c# projects.
- Run-time codegen runs when the silo is starting up. It has the advantage that it works with binaries directly, regardless of the language they are implemented in, and will scan the deployment directory for grains and interfaces (so you could deploy a new dll and just use it). With this magic, there are some drawbacks, such as only finding out about issues at runtime (where sometimes the dev environment is different than the prod environment, like a missing DLL and several other deployment implications/headaches). Also you pay the cost of generating it every time the silo starts up (albeit minimal, it shouldn't take VERY long anyway).

If you can, I'd recommend you choose compile-time codegen. Your usage code would look identical, it's just a matter of when the compilation happens.

Since you are currently not referencing `Microsoft.Orleans.Templates.XXX` (where XXX is either Interfaces or Grains) in you grains project, then you are probably using run-time code generation (since that nuget package is what you need to do it at compile time). For runtime codegen to work, your silo host is referencing (or is deployed alongside) the OrleansCodeGenerator.dll (from the `Microsoft.Orleans.OrleansCodeGenerator` nuget package, which is what enables runtime codegen).
If you can't change your project to use compile-time codegen, then you would need to add the OrleansCodeGenerator nuget package to your test project, so that it can start up the in-memory silo using runtime codegen too, similar to the prod environment.

**Comment by gavinrunsdavies** [comment]
Thanks for the comprehensive reply @jdom that explains a lot (and was insightful for me too!). I'll chat it over with @creyke in the morning.

**Comment by gabikliot** [comment]
@jdom , this explanation deserves a doc page.  I am sure a lot of people will be confused between compile-time and run-time code generation, and this is important enough to explain in a page in our documentation.

**Comment by jdom** [comment]
Yes, I agree.  I'll do that

**Comment by Eldar1205** [comment]
Question regarding the compile-time codegen: To have it do I need only install Nuget package Microsoft.Orleans.Templates.Grains or do I also need to create grain classes using the template?

**Comment by sergeybykov** [comment]
@Eldar1205 You only need the NuGet package. In 1.2.0 we are introducing `Microsoft.Orleans.OrleansCodeGenerator.Build` that replaces both of the `Microsoft.Orleans.Templates.*` packages. Althoght we'll keep them as meta-packages for some time.

**Comment by sergeybykov** [comment]
@ReubenBond do you think there's anything to do here, now that we have the IL-based run time codegen, besides a doc page?

**Comment by chrisbrook83** [comment]
Hi all, I've just started exploring Orleans - it looks good!

Further to @gavinrunsdavies comment, you still get the `Type is not resolved for member 'Orleans.Runtime.Silo+SiloType...` error if you're using nUnit 3. 

This is because of a [breaking change](https://github.com/nunit/nunit/issues/742#issuecomment-121964506) in nUnit 3, whereby it no longer sets `Environment.CurrentDirectory` to where your test DLLs are :(

**You can work around it** by running this line somewhere in your test, before you start Orleans:
`Environment.CurrentDirectory = AppDomain.CurrentDomain.BaseDirectory;`

In order to avoid the need to do this though, it would require some code changes to `TestCluster.LoadSiloInNewAppDomain` and also the `SiloAssemblyLoader` (it probes the 'current' directory to find grain assemblies, too). I'll test it some more tomorrow, and submit a pull request if that'd be helpful?

**Comment by ReubenBond** [comment]
@chrisbrook83 that would be helpful, we could consider this for a fix in the 1.x series, but I believe our 2.x approach of explicit assembly loading is much cleaner.

**Comment by chrisbrook83** [comment]
@ReubenBond  Agreed - explicit loading sounds preferable. Thanks!
