### ISSUE TITLE
Best way to maintain a list of active grains?

### ISSUE THREAD

**Issue by amamh** [dotnet/orleans#1465]
I have a number of grains of type A and I want to have another grain of type B (or anything else) to be able to give me a list of ID's for all active type A grains.

I thought of having grain B as:

        Task Register(string key);

        Task Unregister(string key);

        Task<List<string>> GetAll();

But that is a bad idea because this will have to be a single grain that all A grains call when they activate/deactivate, so it's a bottleneck.

My questions are:

- **Is it possible to make this grain Reentrant to get rid of the bottleneck? The problem is that "List" is not thread-safe and I have a feeling that using "lock" inside a grain is a bad idea.**
- **Is there another way to maintain a list of active grains of type A?** There has to be a better way of doing this.

**Comment by sergeybykov** [comment]
There is nothing better way at the moment. There are separate relevant discussions of adding support for querying and about broadcast messaging.

You can make B reentrant. Using a List is safe because the grain is still single-threaded even if reentrant. However, reentrancy can only help here if within the methods you await other async operations, e.g. IO or calls to other grains. If methods are simple with a single turn, then reentrant won't give you anything.

To avoid the bottleneck, you could consider partitioning a single B into a grain pool of multiple B grains, where each A grain would register with a B grain deterministically picked based on its own ID, e.g. by calculating a modulo. For querying, you would have to fan out a call to all B grains and merge their responses.

**Comment by gabikliot** [comment]
Just to add the obvious (for a random person reading this issue) that what you are asking about is non-idiomatic in Orleans and basically breaks the fundamental abstraction of Virtual Actors. With Virtual Actors you should NOT be asking or be interested to know "all active type A grains" (I presume by active you mean those that have activation in memory).

**Comment by amamh** [comment]
@gabikliot  Thanks, but what if I want to have a monitoring grain that keeps track of how many grains are currently alive for example?

@sergeybykov 

> Using a List is safe because the grain is still single-threaded even if reentrant. 

Thanks for pointing that out.. there was some serious misunderstanding on my part. I thought that Reentrant means multiple calls can execute in parallel. I have read the documentation again and I understand now it means methods can interleave but are still single threaded.


I think since I had the wrong idea of what "Reentrant" means, this issue should be closed now.

**Comment by gabikliot** [comment]
We have statistics API via management grain for that.
