### ISSUE TITLE
ObserverSubscriptionManager<T>.Notify silently remove an observer when action raise an exception

### ISSUE THREAD

**Issue by jesuspsalas** [dotnet/orleans#147]
When evaluating the notification action (in the Notify method) if an exception is propagated from the action to orleans code exception is swallow (not logged) and observer is silently removed from observers collection (treat as failed)

Clearly the intention is to allow the notify process to continue for all observers with no disruption however if action evaluation fails is not clear why Orleans should treat the observer as failed.

Proposed fixes:

1) Log the exception
2) Keep the observer it in the observers list
3) Provide an event handler/callback to manage this situation on grain allowing to eventually chose to set the observer as failed (so Orleans will remove observer from observers collection)

**Comment by sergeybykov** [comment]
I think we made a mistake of including ObserverSubscriptionManager into the runtime. In hindsight, it should have been just a sample of one simple way of delivering notifications to observers.

The proposal makes perfect sense to me. A PR would be great.

That being said, we hope that observers will eventually become obsolete altogether as streams, we think, provide a more powerful, flexible and reliable alternative.

**Comment by jesuspsalas** [comment]
Sergey, as it is part od the runtime lets fix the class with and set an Obsolete attribute to notice this class will eventually be deprecated..

I'll prepare the PR

**Comment by sergeybykov** [comment]
I think we shouldn't mark it deprecated just yet. Not until we at least have great documentation and samples for streaming. Thank for working on the PR, Jesus!

**Comment by gabikliot** [comment]
Added throwing the Exception in this case. The observer is still removed.

**Comment by yevhen** [comment]
I don't agree on that matter. Observers have _fire-n-forget_ semantics, ie one-way. So exceptions should not be propagated back to server grain. I'm actually completely surprised by this behavior. I was under impression that exception will be raised only if observer failed in a hard way, ie garbage collected, nothing there.

I'd like to discuss that further, since I'd like to able to distinguish between these kinds of failures. Also, why you're doing something which is completely opposite to semantics, that is described everywhere in Orleans docs and samples? I mean being one-way back-channel from grain to outside silo world, which is how I was thinking about observers.

Thoughts?

**Comment by yevhen** [comment]
Ah, part me. I've just tested this with both actor-to-client and actor-to-actor scenarios and everything seems to be right. If client (outside silo observer) notification handler fails with exception, it is logged to console and is not propagated back to a publishing grain. Same with actor-to-actor scenario (inside silo observer), with only difference that exception is not logged at all. So the only case when exception is raised is when the observer reference got out of reach (ie, crashed or GCed).

Now, I even more confused. What's this issue is all about? Is it just about ObserverSubscriptionManager<T> not re-throwing observer failure exception when the observer is hard-failed? 

This looks legit to me. Otherwise, if you're interested in managing this yourself, just don't use this helper class at all. It was created specifically to tame this scenario, ie automatically removing failed observer references.

**Comment by gabikliot** [comment]
Yes, it is just an issue with ObserverSubscriptionManager.
No change in the observer semantics.

The exception in the ObserverSubscriptionManager will be re-thrown ONLY if there is an immediate exception on the caller site (like the observer reference itself is bad, or GCed like you wrote, or corrupted or out of memory exception, etc...).
If you were not to use ObserverSubscriptionManager but just call the observer directly, you will get this call-side exception anyway. The issue here was that ObserverSubscriptionManager used to catch and swallow this exception, which is wrong I think.

And I completely agree with:
"Otherwise, if you're interested in managing this yourself, just don't use this helper class at all. It was created specifically to tame this scenario, ie automatically removing failed observer references."

**Comment by gabikliot** [comment]
So now feels like the issue can be closed. 
The ObserverSubscriptionManager does not eat the exception any more, but still removes corrupted observer from the list, as per ObserverSubscriptionManager's semantics. Different Observer Management semantics can be implemented via a different helper class.
