### ISSUE TITLE
Considerations when upgrade from 1.0.9 to 1.1.2 ?

### ISSUE THREAD

**Issue by hyha600** [dotnet/orleans#1473]
Hi,

We are upgrading from Orleans 1.0.9 to 1.1.2, besides required code changes, we are facing exceptions when load 1.0.9's GrainStates and Reminders, are there any known-issues when upgrade? like breaking changes with old data?

**Comment by sergeybykov** [comment]
I'm almost sure 1.0.10, 1.1.1 and 1.1.2 are not backward compatible with 1.0.9 because of the serializer change and likely some other changes. I'm afraid a manual conversion of stored data to the new format is needed.

**Comment by hyha600** [comment]
Thanks Sergey for fast response, then is there any best practice to read/load the binary content (grainstate) independently from an active Orleans environment ? or anyway to convert them into readable JSON?

**Comment by sergeybykov** [comment]
The version story is still in its infancy. It should get better developed as part of the storage API improvements that @jason-bragg has been thinking about.

One option I can think of is that you could use serializers generated in your code with 1.0.9 for state objects to deserialize persisted state and export it into JSON or reserialize with 1.1.2. Reminders are a bit trickier because they are internal, but it should be possible to migrate them in a similar way using 1.0.9 sources.

Maybe there is a better way to do it that I can't think of right away.

**Comment by hyha600** [comment]
Thank you, now we are creating a migration tool that uses a 1.0.9 silo host with mocked grains for that task.

**Comment by sergeybykov** [comment]
Could you share the tool and/or write a doc page for others.
