### ISSUE TITLE
How to scale cache with highly variable hot pieces

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1490]
From Gitter by @creyke:

>Consider a cluster of multiple, complex data structures, each represented by a grain instance, each with a vastly varying load profile. The data in these grains could be required by over 80% of client requests, or less than 1%... it's impossible to programmatically infer which of these is true for a given grain in advance. Some hot grains, some cold grains, and the load profile is consistently changing basically. Data cannot be stale (more than 100ms) and polling to cache data into a stateless worker with a sub second TTL on its model is arguably heavy as the data objects are complex... temptation from an application developer perspective would therefore be to use stateless workers which scale magically, hydrate initial state from the grain that backs them, after making an implicit stream subscription to get deltas.
When a grain is "hot" it will be for some time (maybe at least an hour) so there is huge value in layered caching, it's just a case of identifying the best way to both scale cache grains dynamically, and distribute data to them efficiently both in terms of time and CPU.

**Comment by sergeybykov** [comment]
Assuming this is read-only cache from the client requests perspective that gets updated by some internal process, I see two parts of the potential solution.

It is tempting to use a layer of `StatelessWorker` grains as targets for client requests for automatic scale-out and locality. Let's call them Reader grains. Multiple activation of the same `StatelessWorker` grain within a silo can either each have a copy of the data or use a shared data structure in a safe manner, e.g. if the update process performs pointer swaps. This part is relatively straightforward. The downside of this approach is that each silo will eventually end up with one or more activation of each cache grain. Not sure if this is a problem.

The more interesting part is about how to deliver updates to the data structures used by the  Reader grains. That's where the idea of `StatelessWorker` grains subscribing to streams came from. The problem here, streams or not, is that `StatelessWorker` grains aren't externally addressable (from outside of their silos).

If we leave the notion of `StatelessWorker` grains as is, we need a normal remotely addressable grain in each silo that will act as a writer for the Reader grain. Let's call it Writer. Writer grain can subscribe for updates, via a stream or not, and update the Reader by calling it of by directly swapping the shared data structure. One approach would be to use a `[PreferLocalPlacement]` grain as a Writer and have Reader grain activate one with a random ID from within its `OnActivateAsync()`. We may need a little bit of coordination here to avoid activating multiple reader grains by that part is easy.

With silos restarting we will end up with more than one Writer grain per silo because the ones from rebooted silos will get reactivated somewhere else by updates to their subscriptions in addition to the new Writers getting activated by Readers. But this inefficiency can be eliminated with a bit of local coordination.

I mentioned directly accessing shared data structures by different grain activations several times. Technically, this would be a violation of grain isolation. But we aren't religiously opposed to such violations of the pure model if they are done for significant performance gains and safely.

**Comment by sxam** [comment]
Hi,
I have one more question on the subject. The idea came to us since one of the guys pointed out that I can, in fact, control the number of stateless grains in a silo by using the number in the attribute - StatelessWorker(1) . Hence, that guarantees that I have maximum 1 stateless grain per silo. Now, this is also a drawback, of course, since it reduces scalability for Reader grains to number of silos the service is deployed in. But, let's assume we will go for it. But now how can I approach specific Silos (lets even assume I have their ips) and tell them explicitly that I want to get Your stateless grain of type X (and since there is only one per silo that way I will be able to revoke all of them). Is there some management API that can help me approach a specific Silo and ask for Its local stateless grain?

**Comment by sxam** [comment]
Another remark  - @sergeybykov , you proposed the following:
"I mentioned directly accessing shared data structures by different grain activations several times"
But it seems problematic since the cached info we need is not divided by ids and not general. For example, its metadata per some site and if Stateless layer grains receives "getMetadataForSite(11)" then how will they access some static metadata in Reader grain. Reader grains could, of course, hold static Dictionary with metadata for all sites in the system, reading it from single Master grain. But I am afraid its too much to handle, even with all this 3 layers structure. I would keep grains per Site separated.
So this is a problem I don't currently know how to overcome.

**Comment by creyke** [comment]
To a certain level of concurrency there may be a straightforward solution to scaling concurrency of real time data on a single silo. If a stateless worker acts as a proxy to another grain which in turn implicitly subscribes to a stream from the persistent grain, the stateless workers can, as they scale, generate a unique GUID on activation, throw away say 96bits of it, and use the other 32 to randomly address and therefore activate the real intermediary grain that backs it. The other 96bits can be used to define the virtual instance of that grain. The intermediary grain would then implicitly subscribe on activation to the stream from the persistent grain. Effectively stateless workers elastically scale and take a real grain with them as they are created or deactivated. To do this cross-silo, where you need more traders than a single server can provide, you would need a way of (before any elastic scaling) synchronising a QueuedGrain<X,Y> across each silo in a cluster. Similar to the functionality in the meta cluster which providers OneInstancePerCluster. I believe there is something internal which could potentially be exposed at the application level?

So for me, this proposal could solve (with an extra hop) elastic scaling of stream consuming grains on a single node, and that leaves the missing piece being how (it may already be possible) to synchronise a single grain across each node in a cluster.

**Comment by gavinrunsdavies** [comment]
@sergeybykov your comment "The problem here, streams or not, is that StatelessWorker grains aren't externally addressable (from outside of their silos)." above. Is this still true? We're calling a Stateless Worker grain from a Grain Client outside the silo and are not seeing the work (CPU) distributed across the cluster when we put it under load.

**Comment by sergeybykov** [comment]
>Is this still true?

Yes.

>We're calling a Stateless Worker grain from a Grain Client outside the silo and are not seeing the work (CPU) distributed across the cluster when we put it under load.

The load should be distributed more or less evenly. How man silos do you have in the cluster? Do you see in the logs or metrics the client connecting to all of them?
