### ISSUE TITLE
ETag in GrainState is not latest - Blob storage provider NOT saving ETag - expected?

### ISSUE THREAD

**Issue by hyha600** [dotnet/orleans#1492]
Hi,

We found that Blob storage provider is not saving ETag within persisted States as Table provider did, is that expected?

Also, when looking Table-Provider code, seems like grainState(in memory) ETag is the latest while the one saved into storage(serialized with State props) is the 2nd latest, does that value have any use?

Thank you in advance :)

**Comment by gabikliot** [comment]
I am not sure about your first point.
Is not that the code that uses etag on the writes:
https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs#L235
and here is the code that records etag on the reads
https://github.com/dotnet/orleans/blob/master/src/OrleansAzureUtils/Providers/Storage/AzureBlobStorage.cs#L201

As for table, I am again not sure what you mean by latest and 2nd latest. I do think the Table store provides works correctly and stores the right etag where it should. If you think otherwise, please provide a more detailed explanation.

**Comment by hyha600** [comment]
I think the code referenced answered my question, thank you :)
