### ISSUE TITLE
Cron expression for reminders

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#1505]
It would be great if reminders could be created with specified cron expressions, not just with due time and time period.

**Comment by sergeybykov** [comment]
I'm afraid this would make high scalability harder to achieve due to potentially every grain having a compute piece (execution of the expression) associated with it and requiring periodic re-execution.

https://github.com/dotnet/orleans/issues/947 is trying to improve scalability of reminders by reducing the amount of state the Reminder Service has to keep in memory by grouping reminders within a quantum of time. With nearly free-form expressions, I don't see how we could group reminders/ticks from different grains.

I see another potential form of this idea - if cron-like reminders were defined not at the grain level, but at the cluster level instead, so that one could define a relatively small number of global expressions.

**Comment by veikkoeeva** [comment]
I don't know if this make any sense, but what about an idea that timers could also be outsourced to some external place, managed by Orleans, but stored elsewhere, and they call back to Orleans? [Clustered Scheduled Tasks](https://blogs.msdn.microsoft.com/clustering/2012/05/31/how-to-configure-clustered-tasks-with-windows-server-2012/) come into mind, also running schedules agents in [relational storage](https://technet.microsoft.com/en-us/library/hh393535%28v=sql.110%29.aspx). I have no idea if it'd make Orleans internals needlessly convoluted or be just a no-problem-issue and a runtime headache for those using it.
