### ISSUE TITLE
Add factory methods for non-statically-typed GrainReferences

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#1511]
As a follow up a gitter chat:

> **centur**  : I have a question about factory proxy generation - so far its only Factory.GetGrain<IGrainInterface>(). Is it possible to create a proxy if I have grain Id and grainType as instance of Type object ?
> e.g. something like Factory.GetGrain(grainId, typeof(IGrainInterface)) ?
> 
> **sergeybykov** :  Looking at what GrainFactory.GetGrain<> actually does, it should be totally doable if a couple of types/method were public.
> 
> ```
> public TGrainInterface GetGrain<TGrainInterface>(string primaryKey, string grainClassNamePrefix = null) where TGrainInterface : IGrainWithStringKey
>         {
>             return Cast<TGrainInterface>(
>                 GrainFactoryBase.MakeGrainReference_FromType(
>                     baseTypeCode => TypeCodeMapper.ComposeGrainId(baseTypeCode, primaryKey, typeof(TGrainInterface)),
>                     typeof(TGrainInterface),
>                     grainClassNamePrefix));
>         }
> ```
> 
> ...
> We need to be careful with exposing those methods publicly because of the potential unsafety of those operations. For example, the code above still needs to cast the reference object to TGrainInterface via the generic method. I need to play with the code to see if a clean experience is possible here.

The concept I'm chasing here is to have an ability to create grain proxies without generic parametrized method like 

```
string grainId = "abc"
Type grainType = typeof(IHelloGrain)
GrainFactory.GetGrain(grainId, grainType)
```

As per current code it can be simply achieved by adding extra methods to IGrainFactory interface (and without making any other methods publicly available).
Implementation looks straightforward too as internally `TGrainInterface Cast<TGrainInterface>(IAddressable grain)` uses it's non-generic equivalent.

Would like to hear feedback on gotchas and risks of such extension.

**Upd**: not as straightforward as I thought initially, when I dug deeper

**Comment by veikkoeeva** [comment]
+1 For this one. I had a toy project wherein I wrote an application-side extension (using reflection) doing exactly this. It was in order to be able to choose grains tobe called via run-time configuration.

**Comment by centur** [comment]
@veikkoeeva can you share your signatures and add more details to the usage pattern, as I stumbled over some quirks (which doesn't really allows me to do what I want even with a reflection hack) and not sure it's even possible now.

My initial idea was that I somehow can obtain strongly typed instance of IHelloGrain without using typed var anywhere, e.g.
```
var proxy = GrainFactory.GetGrain(grainId, typeof(IHelloGrain).ConvertTo(typeof(IHelloGrain))
```
but I'm not 100% sure this is even possible in C#

Seems that I can do only something like this

```
Interface IHelloGrain: IBaseGrain
IBaseGrain proxy = GrainFactory.GetGrain(grainId, typeof(IHelloGrain)
```

Which is still good enough for my particular scenario.

**Comment by veikkoeeva** [comment]
@centur I need to get home and see if the code is still around on my old harddrive (I can attach it, no problem). Basically what I did was only that given a string representing a type and and ID (I used GUID, but the end result should be the same) and by refletion assembled a call that would have been a call with generics in compile-time. It looked something like [this](http://stackoverflow.com/questions/4738280/use-reflection-to-call-generic-method-on-object-instance-with-signature-someobj), but there were some quirks on if one should use also the assembly version, fully qualified name etc. etc.

**Comment by veikkoeeva** [comment]
@centur Meh, I couldn't find. But I tried to poke around about some of the functions I used. In addition to the one link, maybe [this](http://stackoverflow.com/questions/33762064/calling-method-with-generic-type-using-class-name-as-string) is useful. If you have had time to think about this, you've probably been *on the hoods*. In that case I just reinforce the notion there was not that much else to it (I remember there were some additional wrinkles, though) when doing as a client-side helper function.

To continue what I wrote earlier, my demo case was to receive any kind of input and match it to handlers either immediately or maybe later and even change handlers on the fly. One of the ideas was that if the amount of input data was large, I could read it byte-by-byte and determine the most efficient handler to make transform it to something more strongly typed or just discard (duplicates etc.).

**Comment by centur** [comment]
Well, I think my blocking issue was how to cast the object back to the type which is stored in the Type variable. [This link](http://stackoverflow.com/questions/232535/how-do-i-use-reflection-to-call-a-generic-method) shows ho generic methods can be called via reflection, it's not a big problem. the problem is the code after that - how can you use resulted object as a strongly typed. So far I don't know the answer and think it's impossible without dynamic runtime, which is another story..

**Comment by veikkoeeva** [comment]
@centur I had an interface (a few of them and a switch-case), the interfaces were basically `IStuff` with `DoStuff`, but I wanted the underlying code to be strongly typed due to other reasons (testing, other prorgramming and error handling). I don't think there is a way around that you have to know something abou the returned type, something about its shape and the signature of the function to be called (the heuristic instantiate and call functions can be arbitrary).

The code was some exploratory programming where the I had some basic rules as strings: if this kind of input seen, call a grain of this type and its function. The intention was to pass these around as strings via a database and even try different versions of the same code. I didn't have a strong *business case* for the code at the time and it felt it got a bit complicated. Namely in that if one loads binaries, say, from a disk, using reflection may not be necessary to create rules how to match input to rules processing input either by creating local processor classes or call grains directly. I had some ideas that should input be processed on the edge grains or distributed quickly around etc. and that's where I left.

This is vague, but I don't have a better recollection on those nights. :) I ran a file search on Notepad++ the last evening, but it didn't turn out anything. I have a few more places to look at this evening, but not something I'd be hopeful of find anything.

By the way: http://stackoverflow.com/questions/18052562/cast-to-a-reflected-type-in-c-sharp. Pretty much the ways I was trying with for what I remember.

**Comment by ReubenBond** [comment]
@centur wrote:
> how can you use resulted object as a strongly typed

At some point you need to know the type of the object if you want to be able to call methods against it in a statically type-safe manner.

As far as creating a grain reference using a runtime-provided type, though, we could certainly add that kind of functionality. It would be up to the user to provide the correct key (string, guid, long, compound), though - even if we ensured there were runtime assertions.

For a bit of info, if you have a grain which implements multiple distinct interfaces, like so:
```C#
class MegaGrain : Grain, IUserGrain, IMonkeyGrain { /* ... */ }
```
Then you can retrieve a grain reference:
```C#
var userGrain = grainFactory.GetGrain<IUserGrain>("frank");
```
Later you can cast that grain to a different interface:
```C#
var monkeyGrain = userGrain.AsReference<IMonkeyGrain>();
```
Note that this would not work:
```C#
var monkeyGrain = (IMonkeyGrain)userGrain; // invalid cast!
```

Inside `.AsReference<T>`, a new `GrainReference` is created (from the generated code) which wraps the old grain reference and provides the methods of the requested interface.

So grain references can be cast, but not necessarily via C#'s casting mechanism, since work may be needed behind the scenes.

**Comment by ReubenBond** [comment]
I believe that we ought to add something like this, since it's useful for many library/tooling/helper scenarios.

We have an option here. One option is that we either add an interface which adds these methods or we add these methods to `IGrainFactory`:

```C#
GrainReference GetGrain(Type interfaceType, Guid key, string keyExtension);
GrainReference GetGrain(Type interfaceType, long key, string keyExtension);
GrainReference GetGrain(Type interfaceType, Guid key);
GrainReference GetGrain(Type interfaceType, long key);
GrainReference GetGrain(Type interfaceType, string key);
```

The other option is that we expose `GrainId` and a way to create `GrainId` instances (similar interface to the above) and then add a single method to `IGrainFactory`:
```C#
GrainReference GetGrain(GrainId id);
```

See #1123 for a discussion on grain identity. My hope is that we can readdress grain identities in the 2.0 timeframe

**Comment by ReubenBond** [comment]
Coming back to this, @centur and others, how does this seem as an API?
```C#
public interface IGrainReferenceFactory
{
    GrainReference GetGrain(Type interfaceType, Guid primaryKey, string keyExtension, string grainClassNamePrefix);
    GrainReference GetGrain(Type interfaceType, long primaryKey, string keyExtension, string grainClassNamePrefix);
    GrainReference GetGrain(Type interfaceType, Guid primaryKey, string grainClassNamePrefix);
    GrainReference GetGrain(Type interfaceType, long primaryKey, string grainClassNamePrefix);
    GrainReference GetGrain(Type interfaceType, string primaryKey, string grainClassNamePrefix);
}
```

**Comment by centur** [comment]
It's a bit old issue for me to recall the context really. From what I re-read here and the signature of proposed interfaces -I'd say that `grainClassNamePrefix` would be difficult to obtain. 
Can we have default value there so if no custom prefix was defined - caller doesn't need to pass anything or Orleans will pick a current default from attribute ?

**Comment by ReubenBond** [comment]
`grainClassNamePrefix` can be null/empty. I could set it as a default value, but because of the string parameters, there's a scope for ambiguity

**Comment by centur** [comment]
from a potential consumer of that api perspective - the parameter purpose looks unclear and not obvious how to obtain the default \specific value for it, so I proposed some defaults for non-sophisticated users of this interface

**Comment by veikkoeeva** [comment]
@centur Maybe it would be clearer if the interface and class type would be next to each other and not separated by the ID types. Otherwise some of the unclarity might be because the grain ID isn't a struct wrapping various ways to create it in a constructor (and have an `explicit byte[]` conversion, paging in @lwansbrough for potential interest) but just a combination of the various ID source types.

@ReubenBond Could https://github.com/dotnet/orleans/issues/602 be thought about in this context? E.g. that the API would be broadly usable also in that context sans adjustments? It looks to me it could be the same API for both. Could this API potentially (also) return multiple references albeit currently prototyped to return just one?

**Comment by centur** [comment]
Guys, I'm happy with any interface, just let me know what to put there if I don't know how Orleans is working under the hood with it ? What is the default value ?  
Naturally for me - the fewer parameters consumer of interface needs to supply - the better. If to do some simple action I have to construct a monster payload that is required for the sake of flexibility under motto "someone may want to use it someday" - I won't use it. We, ourselves, designed few "not very good" solutions just because we were chasing some vague mystical flexibility that noone really used (but which introduced confusions and bugs).

**Comment by veikkoeeva** [comment]
@centur To recap a bit, as for example, would it look clearer if it were
`GrainReference GetGrain(Type interfaceType, string grainClassNamePrefix, Guid primaryKey, string keyExtension);`? But I wonder if this had the potential to return multiple grains? If there could be potentially multiple grains returned, should the return type be a collection or how to signal which one is chosen?

My thought about #602 was to see if there's something to explore in order to avoid complexity in the future.

**Comment by sergeybykov** [comment]
>@centur Maybe it would be clearer if the interface and class type would be next to each other and not separated by the ID types.

I think that would be more confusing, as it would deviate from the order of arguments of GetGrain<T>.

>But I wonder if this had the potential to return multiple grains?

It should never return multiple references back, just like GetGrain<T> never does.

**Comment by lwansbrough** [comment]
It's fairly standard to simply include the type as the first parameter with the rest of the method signature unchanged. I'd suggest you take that route for clarity.

**Comment by ReubenBond** [comment]
These were added in #5674
