### ISSUE TITLE
Message receiver - Out Of Memory during deserialization

### ISSUE THREAD

**Issue by FranKieCZ** [dotnet/orleans#1544]
After deploying our solution into production we experienced several Out Of Memory issues. The current setup is 2 silos in cluster (going to be extended to couple of tens) with Orleans 1.0.10. Running on own HW, **NOT Azure**

The exception was occurring several times during 1 hour. Our monitoring tool showed that machines had more than 2GB of free memory in that moment.

Stack trace:

`!!!!!!!!!! Exception deserializing message body    
Exc level 0: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Boolean& safeToUse)
   at Orleans.Serialization.BinaryTokenStreamReader.ReadBytes(Int32 count)
   at Orleans.Serialization.SerializationManager.DeserializeArray(Type resultType, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.BuiltInTypes.DeserializeDictionary[K,V](Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.BuiltInTypes.DeserializeImmutable[T](Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.DeserializeBody(List'1 bytes)
2016-03-09 05:26:21,740: [216] ERROR [2016-03-09 11:26:21.740 GMT   216    ERROR      101017    Runtime.Messaging.IncomingMessageAcceptor    XXXXXXXX:11111]    !!!!!!!!!! Exception trying to process 5286660 bytes from endpoint XXXXXXXXXX
Exc level 0: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Orleans.Serialization.BinaryTokenStreamReader.CheckLength(Int32 n, Boolean& safeToUse)
   at Orleans.Serialization.BinaryTokenStreamReader.ReadBytes(Int32 count)
   at Orleans.Serialization.SerializationManager.DeserializeArray(Type resultType, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.BuiltInTypes.DeserializeDictionary[K,V](Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.BuiltInTypes.DeserializeImmutable[T](Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.BuiltInTypes.DeserializeInvokeMethodRequest(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream)
   at Orleans.Serialization.SerializationManager.Deserialize(Type t, BinaryTokenStreamReader stream)
   at Orleans.Runtime.Message.DeserializeBody(List'1 bytes)
   at Orleans.Runtime.Message..ctor(List'1 header, List'1 body, Boolean deserializeBody)
   at Orleans.Runtime.IncomingMessageBuffer.TryDecodeMessage(Message& msg)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor.ReceiveCallbackContext.ProcessReceivedBuffer(Int32 bytes)`

What can be wrong:

1) Machines were truly OOM and monitoring was not accurate
2) Issue with message serialization (buffer) in Orleans.

Next steps:
1) Monitor if the error will happen again
2) @sergeybykov mentioned that they've never had OOM even with long running services.

the problem could be in code where Message Buffer is allocated - if it gets too fragmented there might be problem to allocate a contiguous block of memory => OOM.

Some other ideas:

@veikkoeeva : This all makes me think if the buffering part could be improved by allocating one large heap and doling out slices of it instead of allocating multiple small ones (maybe multiple times, I don't know). If that's so, maybe even having two separate buffers where "header sized" slices are given out.

**Comment by jason-bragg** [comment]
This looks to be happening while trying to process a network message.  Specifically, de-serializing the body.  Do you have a sense of what this data is?  There seems to be a dictionary in the body, do you know how big it is?

One can get an out of memory exception even with lots of free memory if attempting to allocate a large contiguous block.  The code in question allocates a large block of the requested size if the requested data size is larger than our block size (default 4k).

**Comment by veikkoeeva** [comment]
@jason-bragg I'll add a note to Gitter, [here](https://gitter.im/dotnet/orleans?at=56e098273194fbd11095a0da) and [here](https://gitter.im/dotnet/orleans?at=56e066375bd94b5e371f0575) and [here](https://gitter.im/dotnet/orleans?at=56e072eb2af4d4de1b6f1da9).

Mind you, I was speculating in midst of everything else. I came a bit curious on how buffer management goes. I haven't yet looked the last show, but I will.

**Comment by FranKieCZ** [comment]
@jason-bragg 
the data are usually dictionary with string key and list of objects as value, the size may vary from couple of kB to lower MB (< 10). But most of the data size will be up to 1 MB.

**Comment by jason-bragg** [comment]
@veikkoeeva, @FranKieCZ 

>I came a bit curious on how buffer management works. 

I'll let you dig in on your own, as I'm sill new to some of this too, so I don't want to misinform you.  However, while I'm of the opinion there are improvements we could make to the network buffering (buffer pool), I don't believe there is anything fundamentally wrong with it.

While more investigation is warranted, my suspicion is that this OOM is due to allocating and freeing lots of large blocks, which fragments the memory sufficiently to lead to allocation failure for large blocks.

Options:
More memory.
Send lists of smaller buffers rather than large contiguous buffers.
Add large block pool to serialization/networking to pool large data blocks.  This can mitigate the issue, but will not eliminate it.

**Comment by gabikliot** [comment]
Can you please provide details of what data are you sending? Did it ever used to work before or not? 

Finally, as with any such issue, my first reaction is to ask you to share your full silo log, at info level.

**Comment by sergeybykov** [comment]
The suspicion on Gitter is that it's LOH, unrelated really to Orleans.

**Comment by gabikliot** [comment]
No need to suspect anything. Silo log will have full GC details.

**Comment by sergeybykov** [comment]
@FranKieCZ shared some stats already on Gitter.

**Comment by gabikliot** [comment]
Ohh, I see. I didn't know. OK, good.

**Comment by ReubenBond** [comment]
For posterity, [here's the message](https://gitter.im/dotnet/orleans?at=56e0a5ea3194fbd11095a541) I think @sergeybykov is referring to:
```
5:05:29 AM    266.337    Runtime.GC.LargeObjectHeapSizeKb
5:06:02 AM    12304.96    Runtime.GC.LargeObjectHeapSizeKb
5:07:03 AM    266.337    Runtime.GC.LargeObjectHeapSizeKb
5:09:19 AM    13785.56    Runtime.GC.LargeObjectHeapSizeKb
5:10:30 AM    266.337    Runtime.GC.LargeObjectHeapSizeKb
5:11:32 AM    12231.6    Runtime.GC.LargeObjectHeapSizeKb
5:12:04 AM    266.337    Runtime.GC.LargeObjectHeapSizeKb
5:14:49 AM    14154.01    Runtime.GC.LargeObjectHeapSizeKb
5:15:30 AM    266.337    Runtime.GC.LargeObjectHeapSizeKb
5:17:03 AM    13902.97    Runtime.GC.LargeObjectHeapSizeKb
5:17:04 AM    266.337    Runtime.GC.LargeObjectHeapSizeKb
5:20:19 AM    13159.92    Runtime.GC.LargeObjectHeapSizeKb
...and so on....
```

**Comment by veikkoeeva** [comment]
@jason-bragg Mm, I don't know more than just flipping through code in GitHub, dangerous, eh. I don't want to trick you to go a wild goose chase, but if someone knows alreayd where to look, I'd be interested to take a look at some later date equipped with better information.

That theory on allocating and releasing blocks that fragments memory looks like the one everyone is looking at now. While it might the application code fragments the heap enough to cause this problem, the gist of what I was thinking is if the socket buffering could contribute to the problem by pinning blocks of memory thus preventing the GC from compacting the heap. That is, this would be an interplay between the application and socket code. I'll be the devil's advocate in the following and tease out of the worst case scenario with the information we have (as I've understood it). This for all reading here, not just for @jason-bragg, chime in. :)

It looks like as if new, contiguous large chunks of memory would be allocated if the incoming (also outgoing?) messages are larger than 4 kB pieces. If these buffers are then handled to the socket, it will pin them. If the `Buffer.BlockCopy` path is involved here, it looks like using `P/Invoke`, while calling the underlying C library (I might be wrong here), and would that also pin the buffers temporarily to memory (if someone knows to answer to this)?

It looks like the socket library allocates new `byte[]` buffer for `grain identification` headers and hands them to the socket. I don't know how the .NET heap allocation works in this regard, but if it allocates these chunks "badly", it looks like, together with the larger chunks that it has the potential to fragment the heap and together with pinning prevent GC from compating it as efficiently as possible.

Does the socket code allocate new 4 kB pieces and gives them to the `Socket`? The crux of this question is if the `Socket` buffer maintains (a fairly constant) size or can it grow and shrink. If the list of 4 kB chunks can grow and shrink, there might be unknowingly much pinning in memory. The other thing is that if this is a list of buffers, they might be dispersed in memory "badly" and if pinned, the GC cannot move the blocks and de-fragment the heap.

I think notable here is that the messages being serialized and deserialized are on the larger side, so the .NET heap allocator needs to find a larger contiguous block of memory to them. If there are plenty of pinned blocks distributed "badly" in memory, the allocator cannot find one nor can the GC compact the heap when it tries to sweep it. Together with the application code holding large blocks of memory the factor play in as seen.

**Comment by veikkoeeva** [comment]
@jason-bragg That was well explained, thanks for taking the time to share your hard-earned knowledge. Indeed it looks like the magnitude of pinning shouldn't be a significant contributing factor in this case.

**Comment by jason-bragg** [comment]
While I'm not convinced this is related to pinning, I don't want to rule it out entirely, at least in the warmup phase of the service.

@FranKieCZ's comment:
>The thing, which is weird to me is the fact that it happened several times but during 1 hour, and the rest (16hours) it was running just fine.

The above comment does raise a question of what was happening at that time?
Had the service just started (warming up)?  Was the service under abnormal load?  Was there something else using up resources? ..  ? .. I don't really know..? 

What I do know is that at 4k per block a single 1Meg message would use up 256 4k blocks.  This is all of the pre-allocated blocks, meaning that new blocks would need to be allocated.  These new blocks would initially not be compacted into gen2 memory, so they could cause fragmentation.  Since our networking layer could pass as much as all of these to the socket, such a call could be as harmful, pinning wise, as 256 sockets pinning 1 buffer each, magnifying the pinning problem as related to socket count.  All these blocks would eventually settle and not trigger pinning issues, but how disruptive this could be in the meantime is not clear.  Given that the problem seemed to magically go away, which would happen as the blocks become compacted into gen2, it seems to me at least a distant possibility that a service sending very large messages could have memory issues from fragmentation related to pinning while warming up.

The above concern is why I suggested tinkering with the buffer settings.  If modifying them alters the behavior, that would lend some credibility to this potential.  In any case, if most of the messages are around 1mb or larger, a larger block size (256k) would at very least be more efficient, while possibly minimizing pinning, since larger buffers means fewer pinned buffers, and 250*256k buffers means one would have ~64Meg of pre-allocated (and most likely pre-compacted) memory available for networking buffers.

**Comment by veikkoeeva** [comment]
@jason-bragg I remember the 4 kB blocks were allocated individually? One optimization could be to allocate a large block and then chop that into a pool of 4 kB blocks (as in [here](https://msdn.microsoft.com/en-us/library/bb517542(v=vs.110).aspx), starting from [here](https://msdn.microsoft.com/en-us/library/system.net.sockets.socketasynceventargs(v=vs.110).aspx)). On a larger note, on a few occassion there has been discussion if bringing in [RecyclableMemoryStream](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream) could be beneficial. Do you have opinion? If it would be beneficial, are there places you would see it could work?

To me personally Orleans feels a bit like "embedded system in cloud" in that mostly a fixed number of threads are pinned to cores and one goes for throughput and there is this single-threaded guarantee. It would kind of complete the picture to preallocate memory buffers and manage them in some smart way in a centralized way. OK, I'm just pondering now, so I'll quit before I make too much noise (or too a dumb remark).

**Comment by gabikliot** [comment]
>To me personally Orleans feels a bit like "embedded system in cloud" 

Good analogy! That is indeed exactly what it is. Complex low-level-optimized runtime inside, simple easy-to-use programming model outside. That was the whole point of this project from day zero.

One large block, chopped into multiple segments makes sense. We thought about it.
Another idea was to have a buddy system - a set of blocks of different (exp. increasing) sizes, for different usages: headers will use small buffers, larger bodies will use large buffers.

**Comment by FranKieCZ** [comment]
one update - i checked logs from last 2 days and it seems the root of the issue with out of memory in our case was a situation when one grain (decompress) received unusually big portion of data (the input data are usually <100kB but this time it was ~3MB), after decompression there was a object of size ~30MB and that caused the out of memory once and after it took some time (~1hour) until the memory got GC and less fragmented....

That's our guess we have now...

**Comment by sergeybykov** [comment]
Are you running with ServerGC? It seems strange that you are getting into an OOM situation when the memory should be GC'ed and defragmented automatically.

**Comment by jason-bragg** [comment]
@FranKieCZ 
Thanks for the update.  Glad you guys were able to track it back to a particular anomaly.  Seems safe to conclude there is no evidence of pinning issues, and now you all have a scenario you can repro in test or dev environments.  If you find anything that points back to Orleans, please let us know.

@veikkoeeva 
>One optimization could be to allocate a large block and then chop that into a pool of 4 kB blocks 

C# sucks at buffer management.  I am aware of no means (without using unsafe code) to cut a large byte[] into many smaller byte[].  Best I've seen is using SegmentArrays structures to point to various parts of the buffer.  The problem with this is that we also use segment arrays to indicate the part of the block we've serialized data into, so that would requires some sort of segment arrays that used segment arrays instead of actual buffers, which gets confusing real fast.  Besides, due to memory compaction during garbage collection, I'm unconvinced this extra complexity would buy us much.

The links you provided refer to the use of SocketAsyncEventArgs, which we've investigated using, but don't currently use.  There remain a number of potential optimizations we could due, like moving to SocketAsyncEventArgs, improved buffering, and the like, but every performance pass gets us less and less savings but tend to introduce comparable levels of risk, so there is a diminishing return here.  "Can do" and "should do" not being the same, I encourage prototyping performance enhancements over speculation, to build confidence that the gain justifies the risk.  Due to the complexity of the serialization, buffering, and networking layers, I also encourage refactoring and simplification as much if not more than performance enhancements. 

RecyclableMemoryStream
This caught my interest as a potential replacement for the stream provider message cache.  Though I've not really spent time digging into the implementation or prototyping anything with it.  A requirement of our networking buffering layer is that it needs to efficiently integrate with our serialization layer (which RecyclableMemoryStream seems like it could do) and our networking socket layer (which I'm less sure RecyclableMemoryStream would do).  It would be interesting to prototype, but without further investigation, that's about all I can say :/

I want to make it clear, i'm not trying to stomp on your dreams of improving the networking layer, quite the opposite, I very much encourage improvements.  It's just that much of the code has been orphaned and refactored many times, so its rather fragile and unintuitive, and as such, predicting its performance characteristics has been challenging.  The result of this is that I've moved to an approach of rapid prototyping first, to vet an idea.  As I learn more about the system and what works, I champion specific improvements that I have strong reason to believe will produce meaningfull gains.  Our load tests are not yet public (in GitHub), but if there are enhancements you'd like to try out and they get pass your private load testing, I'd be happy to push a branch through our load tests to vet it.

**Comment by gabikliot** [comment]
>it's just that much of the code has been orphaned and refactored many times, so its rather fragile and unintuitive,

Well, I will have to strongly disagree with that negative statement. Especially with the fragile and unintuitive part. The refactoring contributed positively to the code being mostly well structured and pretty robust actually (there were very very few, if at all, bugs in the networking/messaging stack in the last couple of years).

> predicting its performance characteristics has been challenging

As of any low level, already-well-optimized code.

**Comment by veikkoeeva** [comment]
@jason-bragg For what I know, your work on this layer has been stellar. I wrote it already on the channel. I do apologize if I came across as too pressing. It was not my intention, wrote that too to @sergeybykov on the channel.

What I meant (I actually tried to explain [here](https://gitter.im/dotnet/orleans?at=56e324a0c7364f7926be3463) and [here](https://gitter.im/dotnet/orleans?at=56e314166fde057c2685f537)) using other people's code that pinning has surprising effects. In those examples I tried to explain it is about magnitude (as you too mentioned) and perhaps unfortunate interactions with the application code. It looks like some of the examples could desribe this situation. I'm not sure. It's about magnitude and some interaction patterns, as we agree.

That being written, it might be possible introduce more stability. Unfortunately I lack time to write such code currently and I don't have the code I've written. I once wrote pretty much the example given in MSDN when `SocketAsyncEventArgs` was first introduced, with the difference that instead of stack I used a lock-free queue to avoid "hot head" (taking and giving of buffer index) on the stack. The example allocates a large buffer and gives out offsets, or perhaps better put, ranges, to it. I'm not sure if `RecyclableMemoryStream` does that. From the quick looks of it, it does, but it introduces a few more buffers for small and large chunks.

As a conclusion, I don't know if there is such interaction here that might play inadvertidly in this situation. It depends. What I have tried to exemplify here (or perhaps better in the channel, see links) is that if one has "free" memory allocations that will be pinned, there might be a more stable way of doing it. It might or it might not matter in this case -- or any case with regards to Orleans.
