### ISSUE TITLE
Heartbeat setting in GrainClient or Client Configuration.

### ISSUE THREAD

**Issue by loneshark99** [dotnet/orleans#1545]
This is a question. 

Is there some kind of HeartBeat setting / duration I can set in the GrainClient or the Orleans Client configuration to keep the tcp connection active. 

Thanks.

**Comment by sergeybykov** [comment]
You don't need to - the client keeps connection alive until you uninitialized it or the app domain gets unloaded.

**Comment by loneshark99** [comment]
I am connecting to the silo from the client using <Gateway Address="servername" Port="30000"/>. If I don't access for certain period of time > 10 mins then I am seeing following exception and the application hangs.

  <Gateway Address="localhost" Port="30000"/>

WARNING	100158	Messaging.GatewayClientReceiver/gwy.tcp://xx.xx.xx.xx:30000/0	10.125.78.40:0]	Exception receiving from gateway gwy.tcp://xx.xx.xx.xx:30000/0: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond	
Warning: 0 : [2016-03-10 01:07:07.165 GMT    16	WARNING	100913	Messaging.GatewayConnection/GatewayClientSender_gwy.tcp://xx.xx.xx.xx:30000/0	10.125.78.40:0]	Marking gateway at address gwy.tcp://xx.xx.xx.xx:30000/0 as Disconnected	
if I restart the application, everything works fine.


Thanks.

**Comment by gabikliot** [comment]
Please share both silo and client logs, at info level.

**Comment by gabikliot** [comment]
Also, this is a Warning in the log. Nothing bad by itself. Do you get any exception in the application? If not, the all is fine, this is just a warning which you can ignore.

**Comment by gabikliot** [comment]
@loneshark99 , do you have the logs to share? Without them there is not much we can help with.

**Comment by loneshark99** [comment]
Actually we are not using with the orleans standard deployment model.  We have opened the public tcp ports on the Azure VM where orleans is deployed.  

  <InputEndpoint name="OrleansSiloEndpoint" protocol="tcp" port="11111" localPort="11111" />
  <InputEndpoint name="OrleansProxyEndpoint" protocol="tcp" port="30000" localPort="30000" />

And then in the ClientConfiguration we are connecting to that Gateway using the below clientconfiguration.

<Gateway Address="servicename.cloudapp.net" Port="30000"/>

I think since in the recommended deployment model, OrleansClient and Orleans are both in the same virtual network , heartbeat is not required.  But with the way we are using it will have to go through different firewalls etc. the tcp connection drops and it just hangs with the logs I posted earlier.

If we send the traffic to the orleans cluster after every few minutes then this issue does not happen.Just to keep the connection open.

**Comment by gabikliot** [comment]
At any event, even if Azure does close the connection, you should NOT see any impact in your application: all grain calls should succeed, since Orleans will automatically re-open closed connections.
You will see the warning in the log, just like the warning you posted above, but there should be no application impact. If that is not what you see, then we should investigate.

As to why/if Azure decides to shoot off the TCP connection - it sounds strange to me. You might want to open this with Azure support. Sounds like an infrastructure bug to me. Or perhaps some mis-configuration.

**Comment by simonycs** [comment]
The problem is when client establish a TCP Connection to an Orleans Azure Service, which is a long live, there are many network devices(i.e firewall) in between that will monitor all the TCP Sessions. There are TCP Connection Idle settings on all the network devices which will kill the sessions that have been idled over the setting value, typically in minutes. When that happens, both the client and server would not know because it is simply removed from the network devices sessions. However, when the client or server try to send any traffic over, the packets will be dropped because it is not in the active sessions any more. What you typical see in the network trace, is a bunch of retries with a TCP Reset that gives up.  We have implemented a temp fix in the application layer that send a dummy request every 30 seconds and we do not see that problem any more. However, we are still concerned there were no retries after the TCP Connection Timeout which we typically see in other Applications. I guess we need to dive into the OrleansClient Code to find out.

**Comment by gabikliot** [comment]
Did you see my comment from above?

>At any event, even if Azure does close the connection, you should NOT see any impact in your application: all grain calls should succeed, since Orleans will automatically re-open closed connections.
You will see the warning in the log, just like the warning you posted above, but there should be no application impact. If that is not what you see, then we should investigate.

If you do see application errors, this is NOT what we  expect. In such a case, please  provide a full silo and client logs, both at Info level.

**Comment by simonycs** [comment]
We did observe Application Timeout after we sit the client idle for over a few mintues. The reason is Orleans client and Server does not know the connection has been silently killed. We implemented a heartbeat mechanism in our client and the issue went away.

The issue can be reproed if you use a Orleans Client connect to a Silo Gateway(the VIP of Cloud Service, you will not see the issue if you have Client and Server deployed on the same VNnet because there is no layer 3/4 devices in between). let it idle for say 30 minutes, try send some traffic over, you should see the Application Error.

**Comment by sergeybykov** [comment]
This sounds like "by design" to me. If the socket from client to gateway stays open, Orleans has no idea that the connection was actually closed. I'm not convinced we should try to detect such situations at the Orleans Runtime layer.

**Comment by simonycs** [comment]
We do not expect Orleans to detect such failure, However, it seems like Orleans client could not recover from such state by reestablishing a new connection at least from our experience.

**Comment by sergeybykov** [comment]
@simonycs How would you except `OrleansClient` to recover if it's unaware of the connection loss?
