### ISSUE TITLE
Question: Why Orleans Logger TrackException & TrackTrace are seperated?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1640]
I fail to understand why there is a separation between tracing & exception reporting in new telemetry consumers APIs. I think the `ILogConsumer` and `Error`/`Warning`/etc. methods on `Logger `made much sense - The developer can choose to trace according to desired severity, and add an exception for warnings as well as for errors. I can emulate this with the logger's `TrackTrace` by printing the exception info to the trace, but then I ask myself what usage is there for `TrackException` if the severity can't be specified?

**Comment by galvesribeiro** [comment]
Hi @Eldar1205,

As much as we usually use Trace to track problems, its not necessarily true that it is only used to track exceptions.

Trace can reproduce steps of what is happening on the code but not necessarily errors. By definition, this new API was created to handle all kinds of telemetry from Orleans silo, not to behave just as a logger. Most of the APM tools in the market handle exceptions differently than traces. In APM world, traces are what is most close to logging however, you can do more than that like for instance send properties about the environment when that trace was called. 

When we talk about the APM/Telemetry, you are not doing just a single log for that event. You can correlate several events, traces, metrics, exception by using a correlation ID so when you are tracking some performance problem for example, you can have rich data totally correlated for a single request.

Have a look at this graphic from our Azure Application Insights:
![image](https://cloud.githubusercontent.com/assets/4714040/14269082/937a6b24-fab7-11e5-8b8e-ac611d7d9219.png)

This show the related data on a time basis, so I know what happened on my cluster close to some even.

Or even more, look at this one that has some metrics about my requests:

![image](https://cloud.githubusercontent.com/assets/4714040/14269104/cde13770-fab7-11e5-9a57-b35e3ec8c889.png)

Does that make sense for you? The new telemetry API was designed to not just replace the logger API (since log/trace is part of telemetry/APM definition), but to give the user the flexibility of having enhanced APM data right from Orleans clusters.

> what usage is there for  TrackException  if the severity can't be specified

Unhandled Exceptions in APM world are errors by definition, cause they shouldn't happen :) If you want to track it as a warning, just send a Trace about it.

I hope that help.

**Comment by Eldar1205** [comment]
Thanks for amazing and fast response, very helpful :)
