### ISSUE TITLE
Should OrleansTestHost have access to Orleans internals?

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#1648]
I suggest we grant OrleansTestHost access to Orleans internals, and expose the manipulation of Orleans internals via test hooks as need arises.

Orleans currently has two sets of tests.  Tester and TesterInternal. 

TesterInternal is intended to contain white box tests of Orleans internals.
Tester is intended to test the public Orleans APIs and simulate user scenarios.

For this reason, TesterInternal alone has been granted access to Orleans internals.  This intentional separation makes it difficult to test valid user scenarios that depend on specific Orleans behaviors that are controlled by Orleans internals.  This includes things like fault injection, silo failures, grain directory behaviors, and placement policy decisions.  These sorts of test must currently be added to OrleansInternal, which is not desirable because they are public api tests (not internals tests) that simply require some specific Orleans behaviors.  This limitation becomes more pronounced when we recognize that tests using OrleansTestHost are similarly limited.  Anyone developing tests in the Orleans repository, at least, has the option of adding their tests that depend on specific Orleans behaviors to TesterInternals, but teams using the OrleansTestHost to test their service specific logic have no means of performing similar tests.

I suggest we grant OrleansTestHost access to Orleans internals and when test scenarios require Orleans to act in very specific ways, we expose test hooks via OrleansTestHost to allow test to manipulate Orleans internals to induce the specific behaviors.  As teams using Orleans test host encounter the need to induce specific Orleans behaviors, they may contribute more test hooks to OrleansTestHost, which enables these new capabilities for the wider community.  (OSS to the rescue!)

Thoughts/Concerns?

**Comment by veikkoeeva** [comment]
I'm concerned this turns into a matter of a [fait accompli](https://en.wiktionary.org/wiki/fait_accompli) by creating a situation where pain is numbed enough to not to drive perhaps a more fundamental solution. It looks to me the solution to some extent is to add configurable points of behavior using DI. That is, instead of objects taking some initial parameters, storing them into private variables and then manipulating internally a partial set of these depending on function calls, the objects could be composed into taking objects the behavior of which they depend on. A few recent classes I've been looking at that look like suitable candidates for such recomposition could be [Silo](https://github.com/dotnet/orleans/blob/cc90465640710d82b2fc40bc9749af992faf41cf/src/OrleansRuntime/Silo/Silo.cs#L54) and maybe [Catalog](https://github.com/dotnet/orleans/blob/cc90465640710d82b2fc40bc9749af992faf41cf/src/OrleansRuntime/Catalog/Catalog.cs#L139). I don't know how afar this could go or how quickly and I have a feeling I comment with too little information, but I make myself a fool here and lower the bar for more through examples and comments!

**Comment by jason-bragg** [comment]
@veikkoeeva 
I've two concerns about using DI for this.

1. Our DI support currently depends on nugets that are still pre-production, meaning Orleans DI is still incomplete and quite limited.  These nugets have been in pre-release state for quite some time and I am unaware of any specific release date.  This precarious state makes me quite uncomfortable about building other capabilities on top of DI.
2. DI would be great for replacing components that are commonly supported extension points, like providers, but for Orleans internals, which are not intended to be replaced and of which both the interfaces and implementations are not publically accessible, DI alone wouldn't be suffice to solve this.  There would still need to be some test infrastructure to expose these capabilities in a way where test developers can provide their own test implementations.

In general, I suspect that if the Orleans internals was more modular and used something like DI to provide internal component implementations at runtime, then the test framework could support public extension points that decorate or replace the default implementations.  With this, what you described, if I'm understanding your proposal, could work, but that's a lot of dependent conditions that are not currently met.

**Comment by veikkoeeva** [comment]
@jason-bragg 

Reading the last paragraph, I think we're on the same page. Your concerns are valid and my preference, as seem to be yours too, is making progress. Phrasing otherwise, maybe one way putting this is that if in principle there are no concerns to move towards "composed structure", for the lack of better terms, how could that be unlocked? It may be a lot of engineering effort, but perhaps if there were a way, it could be done in chunks by the community.

For a concrete test,  I could imagine injecting components that inject faults to their normal functionality (e.g. fail every hundredth call to some function), inject a simple logger that collects the messages to a list and then query it via LINQ it's been logged correctly.

**Comment by ReubenBond** [comment]
We have test hooks exposed via the testing host now, and tests are able to access internals directly if needed.
