### ISSUE TITLE
Default port 22222 conflicts with RedGate Ants Profiler Service

### ISSUE THREAD

**Issue by philippecp** [dotnet/orleans#1663]
Given the error for port conflict is the totally unintuitive "An attempt was made to access a socket in a way forbidden by its access permissions" and that it is likely that other developers will use Orleans and have RedGate's Ants Profiler installed, should the default ports in the project templates be changed to avoid conflict?

I should also add that I spent several hours figuring why TestingSiloHost was ignoring port for primary silo specified in xml file and using hardcoded port 22222 until I finally found that I had to explicitly pass a TestingSiloOptions to constructor overriding BasePort. It would be nice if other devs didn't have to go through that. I'm thinking that [unit testing documentation page](http://dotnet.github.io/orleans/Step-by-step-Tutorials/Unit-Testing-Grains) should explicitly say that xml configuration is ignored.

**Comment by sergeybykov** [comment]
We can easily use a different number.

Re: `TestingSiloOptions` and overrides. @jdom is almost done revamping the `TestingSiloHost` story in https://github.com/dotnet/orleans/pull/1643 for 1.2.0 release.

**Comment by jdom** [comment]
So #1666 now falls back to using whatever `ClusterConfiguration.LocalhostPrimarySilo()` returns, which is still 22222. Should we explicitly set another port, or should we fix the former so even in production it doesn't use 22222?

Nevertheless, we will encourage using `TestCluster` from #1643 starting in 1.2.0, which uses random ports, so this would be a non-issue. I would argue we don't need to do any other changes, since whatever we do will land on 1.2.0 anyway, where there wont be any config files by default.

**Comment by sergeybykov** [comment]
We can update `ClusterConfiguration.LocalhostPrimarySilo()` to use a different port with a separate PR. Production config defaults to 11111.

**Comment by sergeybykov** [comment]
After some deliberation, we think it's probably not a good idea to change the default port. It is trivial to override the default. While it does require an extra line of code, changing the default to 33333 could potentially impact existing users. And there's no guarantee that 33333 won't conflict with something else.
