### ISSUE TITLE
Can I access other silos from within a silo

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [dotnet/orleans#1687]
Is it possible to access other silo's from within a silo?

My use case is this: We would like to have a silo with all of our business logic grains, and another silo with all of our database-grains. The business logic grains will of course use the database-grains. The purpose of separating the two is that we can "mock" the database grains in an automated test by simply replacing the silo with the database grains with a corresponding silo mocking the database.

Thanks

**Comment by sergeybykov** [comment]
This is not directly supported, and even if it was, it would be an anti-pattern - to try to use a silo as an isolation container. Silo are meant to be simply an abstraction over available compute resources that are shared by all grains in the cluster and can be added/removed to/from a cluster on an as needed basis for resource management or as a result of a failure.

There are other, more straightforward, ways to achieve mocking, for example, by passing an explicit class name prefix to `GetGrain()` methods of `GrainFactory`, so that you can switch between production and test versions of the grain class by changing a single string in config.

**Comment by FenrisWolfAtMiddleEarth** [comment]
Right. Understood.

As I see it, passing an explicit class to GetGrain / GrainFactory is more for unit-testing. That is at least how we use it. I am looking for the next step in our CI / CD pipeline, which is integration test.

But I guess what would work just as well is in our CI / CD pipeline is to have the database-grains in one dll and then take that out of the silo in the integration-test step and replace them with mocking-grains from a separate dll.

Thanks for your input. It is much appreciated.

**Comment by sergeybykov** [comment]
>As I see it, passing an explicit class to GetGrain / GrainFactory is more for unit-testing.

Yes, but no necessarily. You can also have multiple grain classes that implement the same grain interface, and explicitly choose the desired grain class to use.
