### ISSUE TITLE
Receiving null reference error when accessing grain state.

### ISSUE THREAD

**Issue by jason-bragg** [dotnet/orleans#1703]
**Symptom**
State-full grains may encounter null reference exceptions when accessing their state after clearing their grain state  when using AzureTableStorage with default settings.

This issue was reported in thread "Client Stream Producers are not being removed" #1421 with the following exception:

Forwarding failed: tried to forward message NewPlacement Request S10.0.0.4:11111:198880849*grn/FAEFC6C8/cd01e998@f36746b0->S10.0.0.4:11111:198880849*grn/716E8E94/11590da3+SMSProvider_DeviceStatus@a6179db0 #4015[ForwardCount=2]: global::Orleans.Streams.IPubSubRendezvousGrain:GetAllSubscriptions() for 2 times after Failed InvokeActivate to invalid activation. Rejecting now. System.NullReferenceException: Object reference not set to an instance of an object.
   at Orleans.Streams.PubSubRendezvousGrain.<OnActivateAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<CallGrainActivate>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Scheduler.SchedulerExtensions.<>c__DisplayClass1_0.<<QueueTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Orleans.Runtime.Catalog.<InitActivation>d__50.MoveNext()

**Fix**
This issue is being addressed in PR "Azure table storage provider returning null grain state - fixed" #1702 and will be in Orleans 1.2.0.

**Workaround**
If you encounter this issue and are not in a position to upgrade to 1.2.0 (or it's not out yet), you can work around this issue by doing the following:

1.   Add the setting DeleteStateOnClear=true to your AzureTableStorage storage provider settings.
2.   Go to table storage and delete any empty grain state entities from table "OrleansGrainState".  An entity is 'empty' if it has empty or missing "Data" and "StringData" properties. If either property has value, the entity is not empty. Remove only the entities that have no data in either property.
3.   Bounce service.

**Comment by centur** [comment]
If you don't mind - I add this link on the quite similar discussion on gitter where the same problem was mentioned https://gitter.im/dotnet/orleans?at=56c6a69fd3c5915029e49768

It'd be nice to know the difference between "non-existing State" and "State with a physical backing row but Null data". But  this touches the question around behavior of "DeleteStateOnClear" flag, that is implemented by few providers, using this flag erases the row thus there is no way to detect whether it's non-existent state or the one that was cleared.

**Comment by gabikliot** [comment]
The beed for a clarity on that subject is exactly what I pointed for in the fix issue. Perhaps the right thing is totally remove the Clear API, only leave delete and users can "clear" by nulling fields. As an argument in favor, the underlying storage dies not provide clear, only delete.

**Comment by centur** [comment]
I think ClearStateAsync (which is IIRC acts as delete when "DeleteStateOnClear=true" and set State to null otherwise) or an equivalent functionality is important - we are using it all the time when we need to explicitly clean data from underlying storage:
1  To avoid storage cluttering (temporary data for long running workflows)
2  We want to ensure that sensitive data was 100% erased from the system (and this is a big thing for anyone who is dealing with personal, private or commercial secret data, tbh).

Maybe it'll be less confusing if we will have ClearStateAsync which acts as Delete all the time (or name it  DeleteStateAsync in 2.0) and instead of having vague switch 'DeleteStateOnClear' we allow user to do something like `State = ResetStateToDefault()` which will reset the state object to default instance - null or initialized with default ctor(). Pretty similar to your proposal, except having a method to 'clear' state, instead of nulling all fields one by one manually.

**Comment by gabikliot** [comment]
I think we need to provide only full delete. The clear can be an extension, or better not add anything at all. App can clear as it wants.

**Comment by centur** [comment]
I agree that full delete is far more frequent scenario than 'clear'

**Comment by sergeybykov** [comment]
In the current model, which is not to say it can't evolve, virtual actors are eternal and so is actor's state. With that in mind, in my opinion, a `DeleteState` operation doesn't make semantic sense - because there is no `DeleteGrain` operation. `ClearState` has the semantics of resetting grain's state to its initial uninitialized condition. `DeleteStateOnClear` is not part of the programming model. It is only config parameter for a specific storage provider, just like a connection string or a storage key.

So, I think within the current programming model the API is correct. If we decide to change the model to, say, remove `State` property entirely and simply pass read state to `OnActivateAsync` and let grain pass whatever state POCO object it wants explicitly to `WriteState`, then the API and its semantics will have to change.

Now there is a separate, although related, question about distinguishing empty grain state from uninitialized one, which I think in fact is a question of breaking the 'eternal' part of the virtual actor model to give app code an indication that a grain is being activated for the first time (ever or since its state has been deleted). I my opinion, it is better to have a separate boolean flag for that, possibly explicitly passes to `OnActivateAsync` than to set `State` property to null. We could bake such a flag into the current persistence API. If we evolve the API to passing grain state directly to `OnActivateAsync` and remove `State` property, then passing null would be a fine option.

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1702.
