### ISSUE TITLE
Always active grains - what to watch out for?

### ISSUE THREAD

**Issue by fsimonazzi** [dotnet/orleans#1721]
We're evaluating a design which requires some grains to be always active. The initial implementation used a "keep alive" reminder, now it uses the DelayDeactivation method with a TimeSpan.MaxValue argument.

While this works, there's bound to be a downside to keeping grains always active, thus robbing the Orleans runtime the opportunity to allocate resources in the most efficient way. In this particular case, the grains involved could be quite a few (in the order of several tens of thousands).

Given these, here are some questions:
- First to confirm, does DelayActivation with TimeSpan.MaxValue prevent the grain from ever be deactivated?
- What is the failure mode when resources are exhausted?
- What would you say is a reasonable usage scenario for always-active grains? Clearly the feature exists so it's a supported scenario, as opposed to using reminders to keep the grain activated, but it seems like a power tool to be used with care. Is there a typical design pattern to take advantage of the feature?
- We're thinking some more thinking is needed to minimize the need for always active grains: probably splitting larger grains to the "always active" part does not need to keep the rest active as well.
- How well would this work with load balancing? We want the grains to be always active, but not necessarily in the same silo. There's a question about a related issue at https://github.com/dotnet/orleans/issues/1428, but it's not exactly the same scenario; we need to have listeners on different service hub subscriptions, one grain per topic.

Thanks!

**Comment by sergeybykov** [comment]
@fsimonazzi There are patterns to accomplish what you need. For example, a bootstrap provider would run upon startup of every silo. Hence, it can guarantee that the needed grains are activated by making a call to each. It would help to understand the next level of details of what you are trying to achieve though. There is a chance there an alternative design.
>First to confirm, does DelayActivation with TimeSpan.MaxValue prevent the grain from ever be deactivated?

Yes.
>What is the failure mode when resources are exhausted?

There isn't an explicit failure mode today. Depends on the type of resources. Most workloads we see are CPU bound. So they naturally throttle themselves. Next one is .NET GC that starts getting slow at Gen 2 collections after the object graph exceeds a certain threshold. At some point, a silo becomes too slow to respond to liveness pings, gets voted dead, and reboots.

>What would you say is a reasonable usage scenario for always-active grains? Clearly the feature exists so it's a supported scenario, as opposed to using reminders to keep the grain activated, but it seems like a power tool to be used with care. Is there a typical design pattern to take advantage of the feature?

This is where it would help to better understand the requirements. Grains are reactive in nature. In general, they need an external stimulus to execute. Timers and reminders are such stimuli. But there may be other design options.

>We're thinking some more thinking is needed to minimize the need for always active grains: probably splitting larger grains to the "always active" part does not need to keep the rest active as well.

Likely, that's the case. Again, hard to tell without more details.

>How well would this work with load balancing? We want the grains to be always active, but not necessarily in the same silo. There's a question about a related issue at #1428, but it's not exactly the same scenario; we need to have listeners on different service hub subscriptions, one grain per topic.

By default load balancing in Orleans relies on random distribution of grain activations, which works well for sufficiently large numbers of activations. There are other strategies, too.

**Comment by jdom** [comment]
Sergey replied to key things.
One additional thing to have in mind that is often overlooked, is that is that there's a case that even if  a silo doesn't die, some activations in it might be deactivated regardless of `DelayActivation`. So if you only create an instance in a bootstrap provider for example, you can't assume it will be *always active* as you mentioned, given the distributed nature of the grain directory.

One concrete example: 
Bootstrap provider on silo A created an *always active* grain X (using `PreferLocalPlacement') that got registered in directory partition on silo B. Silo B dies and loses the directory record of X. Silo A learns that B died, and deactivates X.

If instead the bootstrap provider makes sure a pool of activations are running (and/or with a reminder), then you can make sure that eventually there will be N number of grains activated at all times, randomly load-balanced (avoid PreferLocalPlacement in this case, otherwise the entire pool will mostly run in 1 silo).

BTW, looks like your scenario arises from the need for pulling events from EventHub. Did you consider using the EventHub stream provider instead and see if it fits your needs?

**Comment by fsimonazzi** [comment]
Thanks @sergeybykov and @jdom. I'll be providing some more concrete details, but what I got so far is very helpful. This specific situation is not using EventHub but some much finer-grained source of data.
