### ISSUE TITLE
Do we still need to add generated code to grain interfaces/classes projects?

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1730]
The original reason for including generated code into the target project was IntelliSense for generated factory classes. Before that we compiled generated code into a separate assembly and then merged it to the app one with ILMerge. Although ILMerge didn't work for FSharp assemblies.

Factory classes are long gone, and we don't need IntelliSense anymore. We could compile generated code into a separate assembly (per target project), just like we do with run time codegen. However, that complicates deployment.

If we implement https://github.com/dotnet/orleans/issues/1729, we will have to separate generated code into a separate assembly. ILMerge is not an option for that reason I think.

**Comment by ReubenBond** [comment]
@sergeybykov generating a separate assembly might be good for other reasons: it means that we do not need to use our current bootstrapping process for code generation. Instead, we can have a project whose sole purpose is to hold generated code. Then we don't need to compile each assembly twice (once without codegen, once with). Because we can now skip accessibility checks (great find!), our external assembly can have full access to the user's code.

The end result should hopefully allow us to simplify the access checks performed in the code generator. Those access checks are by far the most complicated part of the entire process.

Of course, there is a minor downside in that if users want to have AOT codegen then they would need to create a project for that and ensure that the resulting assembly is copied alongside their grain code. It's possible that there are ways around this issue.

**Comment by benjaminpetit** [comment]
Fixed
