### ISSUE TITLE
Race condition during Shutdown silo gracefully

### ISSUE THREAD

**Issue by lyjdamzwf** [dotnet/orleans#1771]
Hi,
I have a SiloHost instance, and want to shut silo down gracefully. I did it in this way:

> m_siloHost.ShutdownOrleansSilo();
> m_siloHost.Dispose();

Everything is fine when I test it in Visual  Studio debug mode but if one or more Grain active during Shutdown.
It would output some warnings like below:

> [2016-05-17 03:58:26.563 GMT    54      WARNING 100502  Catalog 127.0.0.1:12111] UnregisterManyAsync 1 failed.
> Exc level 0: System.InvalidOperationException: Grain directory is stopping
> [2016-05-17 03:58:26.574 GMT    54      INFO    100539  Catalog 127.0.0.1:12111]
>         Done FinishDestroyActivations #0 - Destroyed 1 Activations.
> 

And the ShutdownOrleansSilo would block for ten minutes.

I found this is because in Silo's constructor:

> if (Debugger.IsAttached)
> {
>     initTimeout = StandardExtensions.Max(TimeSpan.FromMinutes(10), globalConfig.MaxJoinAttemptTime);
>     stopTimeout = initTimeout;
> }

I'm confused with that, should I do something with that wanring? It that correct?
If it is correct, why the silo need to wait for 10 minutes?

**Comment by gabikliot** [comment]
The race condition is benign. You don't need to do anything. Its just means it will not unregister from the directory, but since directory is stopping anyway, it does not matter.

The 10 min only applies if you have debugger attached. This is so when you stop inside some runtime code with debugger attach, things don't start timing out immediately. Without that it was impossible to step through, since all remote calls tasks were timing out.
