### ISSUE TITLE
Serialization error in Orleans state

### ISSUE THREAD

**Issue by mayamai** [dotnet/orleans#1773]
Hi,

I am trying to add another string  property to the saved state in Orleans, and got a serialization  error on string type (see below.) How can I update scheme without getting these errors? 
The error:
orlenas unsupported type 'System.String' encountered. Perhaps you need to mark it [Serializable] or define a custom serializer for it?"}

The Alert added property is:
[Serializable]
class Alert{
..
 public string InstanceIdString { get; set; }
}

The serialized state includes:
[Serializable]
public class MyAlertsState{

LinkedList<Alert> _alerts = new LinkedList<Alert>();
…
}

The Orleans version is: V4.0.30319

Thanks,
Maya.

**Comment by sergeybykov** [comment]
Are you getting the error trying to serialize or deserialize state? Are these types defines in the grain interface/class assembly?

BTW, V4.0.30319 is not Orleans version. It must be .NET.

**Comment by mayamai** [comment]
Te error is with deserialization of the former state.
Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, BinaryTokenStreamReader stream) at ..
BTW-My Orleans version is 1.1.3.

**Comment by sergeybykov** [comment]
Currently, there is no auto-versioning support that would automatically properly deserialize an old version of object into a new one. You have two options I think:

1) Convert data in storage with a tool. You can use old generated serializer code to deserialize and new one to serialize back in the new format.
2) Take the new generated serializer code as a basis, tweak it to handle deserialization of old format correctly, and remove `[Serializable]` from the type, so that Orleans codegen wouldn't generate a conflicting serializer for it.

**Comment by mayamai** [comment]
1. Is there an existing tool for such migration?
2. As I understand,the second option means tweaking the old de-serializer code to support both versions (until all former state are re-written). Right?    

Thanks again!

**Comment by sergeybykov** [comment]
>1. Is there an existing tool for such migration?

I'm not aware of it.

>2. As I understand,the second option means tweaking the old de-serializer code to support both versions (until all former state are re-written). Right?

Old or new, whichever is easier, to support both versions. The problem with "until all former state are re-written" is how do you know that.
