### ISSUE TITLE
Json Serialization for StreamSubscriptionHandleImpl

### ISSUE THREAD

**Issue by brinkrob** [dotnet/orleans#1777]
The `StreamSubscriptionHandleImpl` class is currently unable to be serialized to grain state when grain state is stored via `AzureTableStorage` with `UseJsonFormat="true"`.

The problem is that the private members are not serialized by Newtonsoft, and therefore when the object is deserialized, `this.streamIpml` is not set, making `IsValid` false, making it impossible to `ResumeAsync` the handle.

It serializes fine if NOT using the `UseJsonFormat` option.

Looking at the Newtonsoft.Json documentation it appears we have a couple options.

1) Mark the private properties with the `[JsonProperty]` attribute (as described here: http://www.newtonsoft.com/json/help/html/serializationguide.htm)
2) Provide a `DefaultContractResolver` (as described here: http://stackoverflow.com/questions/24106986/json-net-force-serialization-of-all-private-fields-and-all-fields-in-sub-classe)

I feel that Option 1 is the most targeted to get what we'd want in this case. But Option 2 would solve this problem in a generic sense, at the risk of serializing a lot more than we need in other cases.

Thoughts?

**Comment by gabikliot** [comment]
Option 1 (`[JsonProperty]`) is the better option. Its explicitly marks in the object what we care about to persistent and what not and will work the same way across all converters and json settings.

**Comment by jason-bragg** [comment]
I concur with @gabikliot, for the reasons he provided and because this is how we've serialized private data in other classes.

While this is a real bug that should be fixed, I discourage storing the stream subscription handle.  My reason for this is that Orleans persistence does not yet have good backwards compatibility support.  This means that, should we need to modify the subscription handles (to address bugs, for instance), there is not a good means to read the old data.  There are ways to work around this, but avoiding it entirely is, IMO, a better option.  Rather than storing the subscription handles, active stream handles can be obtained from the stream itself using the GetAllSubscriptionHandles() call.

Something like:

    IList<StreamSubscriptionHandle<TBlarg>> subscriptions = await stream.GetAllSubscriptionHandles();
    if (subscriptions.Count >= 1)
    {
        // if a subscription is found, resume processing it
        await subscriptions.First().ResumeAsync(OnNextAsync, OnErrorAsync);
    }
    else
    {
        // if no subscription is found, create one by subscribing
        await stream.SubscribeAsync(OnNextAsync, OnErrorAsync);
    }

Using something like the above logic, a client or grain can resume consuming from an existing subscription without storing the subscription handle, hence avoiding the risk posed by the lack of backwards compatibility.

If you have your own persistence logic and better control over data versioning, this is less of an issue (still an issue, just less of an issue..)

**Comment by DixonDs** [comment]
@jason-bragg Just a small note that documentation (http://dotnet.github.io/orleans/Documentation/Orleans-Streams/Streams-Programming-APIs.html) is actually encouraging saving a subscription handle as one option: "The consumer may have persisted the handle it was given back from the original SubscribeAsync operation and can use it now. "

**Comment by jason-bragg** [comment]
@DixonDs
Thanks for pointing that out. 
I took a look.  The documentation lists both options, store the handle, or request it from the stream, which is technically accurate.  Both are currently supported.  While I discourage storing the handle, the behavior is supported, and was the preferred solution in the original implementations.

I'm not sure my preference for the alternative approach belongs in the documentation.  Do you have a strong opinion on this?  My view on this point is quite malleable.

**Comment by benjaminpetit** [comment]
Fixed in 2.0
