### ISSUE TITLE
External Task in a Grain

### ISSUE THREAD

**Issue by lukode** [dotnet/orleans#1788]
Hi,

Just trying to get an external Task to work from a grain and failing miserably. Probably deadlocking myself as the execution just stops. I have tried following the examples from [here](http://dotnet.github.io/orleans/Advanced-Concepts/External-Tasks-and-Grains) but those don't compile (getting "The 'await' operator can only be used within an async method."). So instead of `await` I tried `t1.Wait()` and `Task.WaitAll(t1)` - but that's when the execution stops.

Would you have any pointers/ideas that may help?

**Comment by sergeybykov** [comment]
`.Wait()` is disallowed in grain code. I'm pretty sure that's the reason for the deadlock you are seeing I updated the code snippets in http://dotnet.github.io/orleans/Advanced-Concepts/External-Tasks-and-Grains to make the method signature `public async Task MyGrainMethod()`, so that `await` can be used inside it.
