### ISSUE TITLE
Change visibility of AsyncLock to public

### ISSUE THREAD

**Issue by bwanner** [dotnet/orleans#1797]
Within Orleans there is an internal class [AsyncLock](https://github.com/dotnet/orleans/blob/cc90465640710d82b2fc40bc9749af992faf41cf/src/Orleans/Async/AsyncLock.cs) that allows to create a mutex that can await async operations.

I discussed making `AsyncLock` public with @sergeybykov who brought up that Orleans in general is not intended to be a general purpose library. I opened this issue to gauge if there is valid common interest in having `AsyncLock` available for Orleans applications.

`AsyncLock` can be useful when dealing with reentrancy to create non-interleaving methods: Say you have a reentrant grain A where `A.MyMethod()` is supposed to be executed without interleaving. When `MyMethod()` is making another grain call `AsyncLock` can be used to await this call while still keeping a section of the code locked.

Feel free to bring up any other uses of this feature or say why you would/wouldn't like it to be public.

**Comment by jdom** [comment]
If what we want is for 2 request for the same grain to not interleave, in theory you could write up something that doesn't rely on a Semaphore(Slim) at all, since grain execution is single threaded (for example by using a TaskCompletionSource if there is contention).

If the intention is to use the lock across several grain activations in a Silo, then that's another story, although not generally recommended, and should be used with caution for cases when it is practical.

**Comment by gabikliot** [comment]
I would also discourage usage of `AsyncLock` since it relies on `SemaphoreSlim`.
Instead, I would use `Tasks` and `TaskCompletionSource`, like @jdom suggested.

**Comment by bwanner** [comment]
Implementing a custom lock using `TaskCompletionSource` seems to be the way to go here, did not think of that :). Maybe that feature can be added to a custom library in OrleansContrib.
