### ISSUE TITLE
Improve error message for corner case os a silo trying to join an empty cluster

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#1862]
If all silos get killed abruptly without a chance for them to update the membership table, the killed silos stay in the membership table listed as `Active`, and a new silos starting later with the same deployment ID fails to join the dead cluster because it fails to connect to the silo that are listed as `Active`.

This mostly happens at development time, when a developer kills a single running silo process, and then restarts it with the same deployment ID. The error message just says "No connection could be made because the target machine actively refused it", which isn't very helpful.

If we could add some logic to detect such cases and improve the error message, that would help developers understand the situation and resolve it quickly.

**Comment by gabikliot** [comment]
There is a time limit on that behavior. 
After a coupe of minutes (don't remember exactly how much, but configurable), this will stop happening and the new silo WILL be able to join, even if all silos are Active in the table (but really dead). We basically consider Active for pinging and joining ONLY if the silo also wrote I am Alive into the table for last X minutes. Otherwise, without this time limit, we would have a "never able to join" situation, which breaks "eventual" property and means our alg can sometimes get stuck for ever. Which would not be good.
So in dev you can just change this limit .

**Comment by gabikliot** [comment]
Also worth noting that this whole feature of validating ping before joining was added as a best effort mechanism to solve the misconfigured azure firewall issue. 
We can simply disable this feature. It would be a one line fix ( or have it off by default, with option to turn on).
Hopefully azure fixed the firewall issue by now. It has been 4 years now, maybe five, since we saw it.

**Comment by sergeybykov** [comment]
The point of this issue is to help developers figure out what's going on. It would be fine I think if the error message included a link to a doc page.

Independently, we could consider making the connectivity tests off by default as you suggested.

**Comment by gabikliot** [comment]
I would even suggest making the production setting off by default.

**Comment by sergeybykov** [comment]
@gabikliot Sorry, what the difference between *"we could consider making the connectivity tests off by default as you suggested"* and *"I would even suggest making the production setting off by default"*? Did I miss some subtlety here?

The concern with not performing connectivity tests I can think of is that network partitioned parts of a cluster may start killing each other with no eventual winner, unlike in today's case where one of them eventually wins.

**Comment by gabikliot** [comment]
Ohhh, its the same. I misunderstood you. I thought you meant connectivity unit tests.

OK, I will look at both error msg and configuration.

**Comment by shayhatsor** [comment]
@sergeybykov , you wrote:
> This mostly happens at development time, when a developer kills a single running silo process, and then restarts it with the same deployment ID.

AFAIK, this would not be problem, since the silo knows it is of a newer epoch and "kills" its older epoch entries. An example scenario that can cause frustration is when you have two silos and you kill both. Then when you immediately restart one of them you'd get the error. Cancelling the connectivity tests makes sense to me, because it allows the membership protocol to handle the situation as usual and only decide that a silo is down when it's voted as such. Also, it's important to note that in development time, people usually use in-memory membership table and run in a single silo. In that case, the problem is mute.

**Comment by sergeybykov** [comment]
Resolved via https://github.com/dotnet/orleans/pull/1866.
