### ISSUE TITLE
Upgrade to RTM DependencyInjection

### ISSUE THREAD

**Issue by attilah** [dotnet/orleans#1875]
I'd like to update the DI part to the final version, but we need some minimal changes what we need to discuss:

- [ ] 1. Can we make DI mandatory (with default implementation is using the .Net Core default container). It means that no Activator.CreateInstance fallback.
- [ ] 2. Make OrleansRuntime.dll reference Microsoft.Extensions.DependencyInjections.Abstractions to remove the reflection based loading of the OrleansDependencyInjection assembly contained IStartupBuilder implementation
- [ ] 3. Do we want to keep this IStartupBuilder implementation? (I say no, it came as a workaround when you decided to move DI to a separate assembly while it is not final).
- [ ] 4. Remove DefaultServiceProvider and if no startup type configured then use the default DI implementation. As I see it involved OrleansClient too, so in this case we've to move the implementation there. Since in most cases there is already a DI on client part of a system, it would make sense to make DI pluggable from our side, but that must be a separate PR.

Discuss it "fast" so we can go "live" with .Net Core 1.0 DependencyInjection support ;-) (the rest of .Net Core will have to wait).

**Comment by sergeybykov** [comment]
I think 2 (including removal of OrleansDependencyInjection altogether) is no-brainer change that we waited to make. Everything else is up for discussion. So let's make the change for 2 first.

I am concerned about making something mandatory. I think we have two very related but not identical questions here: app DI and Orleans Runtime DI. App DI is critical to get right and convenient because it's part of the programming model. Runtime DI shouldn't impact application code. If we end up with the same solution for both, great. If we don't, I think it's fine, too.

**Comment by attilah** [comment]
What about 3?

That type only exists because of the reflection based loading I think. Came at the same time.

**Comment by sergeybykov** [comment]
Then it should be removed with `OrleansDependencyInjection`.

**Comment by attilah** [comment]
https://github.com/dotnet/orleans/pull/1878

**Comment by davidfowl** [comment]
Is Orleans also using the Startup.ConfigureServices pattern?

**Comment by attilah** [comment]
Yes, a similar (dumber) one what you did. We've a very similar requirement, so more will come from Asp.Net Core to Orleans from Startup, Configuration, Hosting, etc parts with time.
