### ISSUE TITLE
Question: Can grain with persistent state can be renamed?

### ISSUE THREAD

**Issue by Eldar1205** [dotnet/orleans#1895]
Hi, I had a grain with full name ManagedEventHubs.ConsumerGrain and I wanted to refactor it to ManagedEventHubs.Consumption.ConsumerGrain. When I tried to deploy with this rename I saw errors trying to create grains activation and I assume there will also be problems reading persistent state since the grain full name is part of the grain key is storage. I'd like to know if Orleans has built-in support for renaming grains, something like HTTP 301 Moved Permanently that browsers react to with automatic redirect? 

If such built-in support doesn't exist, how would you recommend to implement that in application code?

**Comment by shayhatsor** [comment]
You're raised two issue here:
1) 
> When I tried to deploy with this rename I saw errors trying to create grains activation

I guess you mean that you have a cluster with `ManagedEventHubs.ConsumerGrain` and you've added a silo that contains the renamed `ManagedEventHubs.Consumption.ConsumerGrain` ? This won't work because a cluster must have the same assemblies in all silos.

2)
> I assume there will also be problems reading persistent state since the grain full name is part of the grain key is storage

This is more related to the storage provider you're using. The Azure one uses the internal grain key as the storage key, which creates this hard coupling.

**Comment by Eldar1205** [comment]
Regarding 1, I didnt add a silo but upgraded the cluster version using in
place upgrade. Orleans gave me activation errors due to the rename
בתאריך 2 ביול' 2016 19:49,‏ "Shay Hazor" <notifications@github.com> כתב:

**Comment by sergeybykov** [comment]
The current form of declarative persistence is rather simplistic, and doesn't support a number of more advanced scenarios. While quite a bit can be done at the storage provider level, we need to think how to enable some of those features in the model (e.g. via metadata attributes) and how to evolve the API.
