### ISSUE TITLE
Optimization: Use of object pooling on the hot path

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#1910]
Poking around the code, there are a few places on the hot path which allocate new `Message`, `CallbackData`, and `InvokeMethodRequest` objects.

I believe we should be pooling/recycling these objects instead of putting pressure on the GC.

This issue is for discussing whether or not this is a desired optimization, concerns, and anything else relevant before someone embarks on implementing it.

NB: object pooling is already used in some parts of Orleans, for example in some of the Streams provider code.

**Comment by shayhatsor** [comment]
👍

**Comment by sergeybykov** [comment]
Sounds like a great idea.

**Comment by gabikliot** [comment]
We use object pooling in mostly 2 places: buffers for regular messages and in event hub adapter for carefully optimized compact memory layout (work by @jason-bragg ).
I would start by trying one at a time, call back data is probably the easiest to try first. Invoke method request next. Another thing to try is just cut on the number of distinct objects, try inline some fields instead, compact headers. 
In general I   am in favor, but need to be careful. In theory pooling too much may have the opposite effect: you will have more gen 2 objects vs otherwise they might have gone into gen 1. Do just try carefully one at a time.

**Comment by dVakulen** [comment]
Indeed great idea, I've started implementing pooling for  <code>Message</code> (the messages seems to have bigger impact on GC than the other two (<code>CallbackData</code> and <code>InvokeMethodRequest</code>)  some time ago, but got distracted by other things. I can resume the implementation.

**Comment by ReubenBond** [comment]
@dVakulen that would be great :) How are you implementing the pool, is it with a `ConcurrentBag` or something else?

**Comment by dVakulen** [comment]
@ReubenBond Yes, just took it from the [MSDN](https://msdn.microsoft.com/en-us/library/ff458671(v=vs.110).aspx), and planning to compare perfomance with thread local one https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/Streams/Common/PooledCache/ObjectPool.cs.

**Comment by AlgorithmsAreCool** [comment]
@dVakulen 

Here are my unsolicited thoughts :) 

These are two of other object pool implementations currently in use. 

### Roslyn Object Pool
https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/SharedCollections/ObjectPool%601.cs

- lock free, thread safe
- Bounded size
- Nice debug tracing features for detecting leaks
- Includes fast path only one item in use at a time

### CoreFX Object Pool

https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/ObjectPool%601.cs

- Lock free, Thread safe
- Bounded size

#### A couple of thoughts

Both of these pools are bounded in max size which prevents a usage spike from creating lots permanent garbage. I would recommend considering adding a bounded size to any object pool implementation you use. 

These two pool designs are basically the same except for the single-use optimization in the roslyn pool. They both make a 'best effort' to return objects to the pool correctly, but do not do so precisely because in general, we are not scared of dropping a few objects to the GC under heavy contention if >99% of pool requests are served correctly and we spend less time bookkeeping.

The ConcurrentBag is a great collection that provides fast, precise semantics under high concurrency. But i think it is *slightly* inferior for object pooling for the following reasons:

- It uses locks occasionally to sync important structures
- It provides a higher level of bookkeeping precision than what we actually need
- Uses TheadLocal caches with a stealing mechanism that requires more CPU and memory overhead than the other implementations 

I hope these help

**Comment by dVakulen** [comment]
Thank you, @AlgorithmsAreCool. for the references, but currently the main problem isn't the way of the implementation of the objects pool, but finding places in which to place the call for returning of the object to the pool. For example there's 400 references to the <code>Message</code> class, which has to be analyzed to find out where it's lifetime ends. Currently I'm implementing approach based on using AOP for catching of the callstacks on accessing of the class's methods and then analyzing them to detect the dead end method of this objects. If anyone has a better idea - please, post your thoughts..

**Comment by dVakulen** [comment]
Also I have considered Roslyn's and CoreFX's implementations before, and I think that we do not want the bounded size pool for those case to not create additional bottleneck, but to implement some shrinking strategy, so that the performance can be predictable at the peaks (including backpressure) and memory pressure could be reduced after those peaks.

**Comment by gabikliot** [comment]
@dVakulen , that is exactly the reason why I suggested to start with callback data, it's much easier.

**Comment by AlgorithmsAreCool** [comment]
@dVakulen Yes lifetime management is definitely the hard problem here. Perhaps it would be best for me to suggest object pool tuning *after* we have usages for the pool first. :)

I have a horrendous idea about a way to approximate object lifetimes that i will try to test this weekend. If it yields any fruit i'll let you know

**Comment by dVakulen** [comment]
@AlgorithmsAreCool My way of finding out places in which to dispose worked out - already reduced <code>Message</code> allocations across 700 subsequent grain calls from 1400 to 31. But still interested in that horrendous idea of yours, so if you can - could you please post it here?

**Comment by AlgorithmsAreCool** [comment]
My crazy idea was to use a little IL generation library i wrote to inject telem calls into accesses of the Message members. Then map out data flows and use those to heuristically determine lifetimes. Unfortunately I've been swept away at work and haven't been able to make sizable progress on this.

**Comment by dVakulen** [comment]
@AlgorithmsAreCool That's pretty similar to what I did, except I used PostSharp instead of custom IL gen. library.

**Comment by ReubenBond** [comment]
This issue is too general to be actionable. We have pooling in use in some places and we can use pooling to improve performance in other places, but we will address those on a case-by-case basis
