### ISSUE TITLE
CreateOrleansTables for PostgreSql and Oracle

### ISSUE THREAD

**Issue by rohail99** [dotnet/orleans#1926]
Hello,

I see that there is a version of CreateOrleansTables for MS SQL Server and MySql, but was wondering if one can be added for PostgreSql and Oracle.

**Comment by sergeybykov** [comment]
In principle, it would be good to add one. In practice, @veikkoeeva and @shayhatsor likely know if there are any roadblocks for that.

**Comment by shayhatsor** [comment]
@rohail99, it was the primary design goal - Allow use of any backend that has an ADO.NET provider. we've recently updated the [Relational Storage](http://dotnet.github.io/orleans/Runtime-Implementation-Details/Relational-Storage) article and added a "Guidelines for adding new ADO.NET providers" section.

**Comment by veikkoeeva** [comment]
@rohail99 It shouldn't be too difficult. There shouldn't be any roadblocks, but on my behalf I help in any way I can. I was actually contemplating for PostegreSQL myself. I'm usuably reasonable reachable via Gitter.

Testing can be a bit of a rough spot. But at least what comes to testing relational storage providers (https://github.com/dotnet/orleans/pull/1682) works, I just wrote about it in Gitter https://gitter.im/dotnet/orleans?at=57837431bdafd19107617d42. I haven't pushed the latest set (should today) and there's an issue in that it isn't actually in master yet and there might be an objection to it (but it's also better than what's currenly on display).

If you go ahead, you can copy come across bugs or something to fix in the current one. I think I saw at least one in that the membership `outer join` turns into an `inner join` because of the `deploymentId` in the where clause. It basically means there needs to be records on `OrleansMembershipTable` with the condition. Either it doesn't matter anymore (I don't remember) and it should be clarified, or then fixed.

**Comment by shayhatsor** [comment]
@veikkoeeva said:
> Testing can be a bit of a rough spot.

In the current state of the system (the code that's in master) it is easy to add system store tests. When @veikkoeeva completes #1682, it'll be easier.

**Comment by veikkoeeva** [comment]
Should this be closed, @sergeybykov ?
