### ISSUE TITLE
Serializer in static class is not registered

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#1976]
The following serializer is **not** registered on silo start:

``` csharp
[RegisterSerializer]
public static class MySerializer
{
    public static void Register()
    {
        SerializationManager.Register(typeof(MyClass), DeepCopy, Serialize, Deserialize);
    }

    static MySerializer()
    {
        Register();
    }

    // [...]
}
```

The following code works:

``` csharp
[RegisterSerializer]
public class MySerializer
{
    public static void Register()
    {
        SerializationManager.Register(typeof(MyClass), DeepCopy, Serialize, Deserialize);
    }

    static MySerializer()
    {
        Register();
    }

    // [...]
}
```

As you can see: The latter serializer is in a non-static class (though all methods are static).

**Comment by jdom** [comment]
That's weird. I wonder whether this is just working because of the static constructor being executed by "luck", or whether this is for some reason explicitly skipping that type after it found that it has the `RegisterSerializerAttribute` on it (by looking at the code, I'm leaning towards the former).

To nail it down, can you:
a) verify whether the the 2nd option (with a non-static class) works even after removing the `RegisterSerializer` attrbute from it?
b) let me know whether `MySerializer` is defined in the grain interfaces assembly.

**Comment by peter-perot** [comment]
@jdom: to item (b): Yes, it is in the grain interface assembly.

Currently I'm on holidays, but I'll return to this issue in September. Stay tuned.

**Comment by jdom** [comment]
I did see this myself too. For some reason static classes are skipped before we even check whether they have a RegisterSerializer attribute

**Comment by jason-bragg** [comment]
Not applicable in 2.0
