### ISSUE TITLE
Investigate Need for Tag in GrainDirectory

### ISSUE THREAD

**Issue by sebastianburckhardt** [dotnet/orleans#1981]
There is quite a bit of code to return version numbers from the code that registers new addresses in the directory (see `AddressAndTag` struct). Instead of just an address, an address plus a version number is returned.

It appears to me that the version tag is not actually used in the codebase.
The only place where it is passed is `DirectoryCache.AddOrUpdate`
but all implementations of `DirectoryCache` that I can find simply ignore it.

Unless there are objections (e.g. secret implementations of DirectoryCache that actually need this version number), I would like to refactor the code to remove it. It will make the code easier and a tiny bit faster.

**Comment by sebastianburckhardt** [comment]
I think there is a space leak in the grain directory. The `GrainInfo` objects are never removed from `GrainDirectory.partitionData` even after all activations have been deactivated. This would appear to create problems for applications that keep creating new grains over time.

**Comment by gabikliot** [comment]
@sebastianburckhardt , I finally remembered to take a look.
The version IS used, by adaptive cache, here:
https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/GrainDirectory/AdaptiveDirectoryCacheMaintainer.cs#L165

You can see the logic directly inspects and relies on that.
What I cannot say safely at this point is if the logic there is correct/necessary/optimal. It has been too many years since I had a deep understanding of this code. From a brief look now, it does seem like it is doing the right thing. AdaptiveCache and AdaptiveDirectoryCacheMaintainer are the default ones, so this code is definitely used.

If you want to revisit this code and maybe find that the version/tag are not required and this code can be safely changed (basically, challenge the algorithm used there), I will be ready to discuss it with you.

**Comment by sebastianburckhardt** [comment]
Ok, I understand now - thanks for clarifying. Not sure how I missed this.

The algorithm seems fine to me... I can see that the tag provides an efficient way to validate that cached directory entries are not out of date. Definitely more efficient than sending and diffing a list of activation ids. 

I agree that using structs instead of tuples could perhaps reduce memory management overhead, but changing this is probably not a high priority.

**Comment by gabikliot** [comment]
Agreed. 
So going to close that issue for now, since s we resolved it.
