### ISSUE TITLE
Reminders is failed to be parsed when grain is in F# module

### ISSUE THREAD

**Issue by raol** [dotnet/orleans#1982]
Reminder entry is written incorrectly when grain is inside F# module. I'm using orleankka, but I've checked its codebase, and they don't modify the posted reminder.
But it's written incorrectly in the OrleansReminders table.

```
RowKey = GrainReference=00000000000000000000000000000000060000005b91acda+ReminderActor+ReminderActor:TestReminder-BrokenReminder
GrainReference = GrainReference=00000000000000000000000000000000060000005b91acda+ReminderActor+ReminderActor:TestReminder
```

It causes reminder to work correctly when it's scheduled during silo lifetime, but later, when silo is redeployed, it fails on parsing reminder entry.
Log is below

```
Server stack trace:
at Orleans.Runtime.UniqueKey.Parse(String input)
at Orleans.Runtime.GrainReference.FromKeyString(String key)
at Orleans.Runtime.ReminderService.AzureBasedReminderTable.ConvertFromTableEntry(ReminderTableEntry tableEntry, String eTag)
at Orleans.Runtime.ReminderService.AzureBasedReminderTable.<ReadRow>d9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.ReminderService.LocalReminderService.<GetReminder>d26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.PublicOrleansTaskExtensions.<BoxAwait>d8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Orleans.Runtime.InsideRuntimeClient.<Invoke>d57.MoveNext()
```

You can find sample projects that demonstrate the issue described here:
https://github.com/raol/orleannka-reminders

Please let me know if I should create separate pure orleans application to make it easier for you to debug the problem.

**Comment by veikkoeeva** [comment]
@raol A hunch seeing those `+` signs, would it work if you took the module definition off? I'm not entirely sure, but if you use F# types from modules in C# Orleans, the code used to break to serialization. The reason was &ndash; still is? &ndash; the types in modules get compiled to inner classes and Orleans doesn't handle them properly (I remeber looking at `TypeUtils`, for instance, where it doesn't handle the whole syntax (for instance, see [here](https://msdn.microsoft.com/en-us/library/w3f99sx1(v=vs.110).aspx) for nested classes).

**Comment by raol** [comment]
@veikkoeeva, when module is replaced with namespace, everything works correctly, so problem is in nested classes.
But I see at least 2 possible solutions to the problem. I'm kind of new to orleans codebase, hence there is a probability that you've already considered these workarounds, but have decided not to implement them. Sorry if so.
1. You can change "+" symbol in the grain reference to some value that does not interfere with `TypeUtils`, i.e. `#`. So in my case grain reference will  look like
```
GrainReference=00000000000000000000000000000000060000005b91acda#ReminderActor+ReminderActor:TestReminder-BrokenReminder
```
But such fix will introduce another issue with back compatibility. 

2. Another option is replace `+` in typename with some symbol. And when reference is, resolved replace it back to `+`. Probability that someone used nested classes (expect F#) is really low, and this change seems safe to me.

**Comment by veikkoeeva** [comment]
@raol This nested class problem will manifest also in grain-to-grain calls, which is somewhat problematic for F# code organization, as you've noted. My knowledge on this is very superficial, I don't know what would be needed to remedy this situation in a systematic fashion.

I mentioned [TypeUtils](https://github.com/dotnet/orleans/blob/d1b0915776a8f0f10712913890846f4a859f7cd9/src/Orleans/CodeGeneration/TypeUtils.cs) because I know there is custom parsing and it *might* be relevant. I don't know if it is. There *might* be problems in [TypeUtilities](https://github.com/dotnet/orleans/blob/faa31892de58b530c50c1720960c66590ecfce27/src/Orleans/Serialization/TypeUtilities.cs) too, though I think not likely.

In any event, I'm only throwing this here around. I think @ReubenBond could have an idea and also @sergeybykov. Though I can't, naturally, put burden about this to neither one. :)
