### ISSUE TITLE
Replace Logger with Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by adamhathcock** [dotnet/orleans#2029]
https://github.com/aspnet/Logging

Basic change:
- Keep `LogManager` (replace with 2.0 and proper DI?)
- `LogManager` maintains an instance of `ILoggerFactory` which it uses to create `ILogger` instances

Effects:
- Pushes logging concerns to M.E.Logging and all the loggers that already integrate with it and ASP.NET Core
- Logging levels change
- APM methods on the abstract `Logger` have to go somewhere else.  (I feel like these should be on a class called Logger anyway)

Probably more things but I'm new to this code base.  This feels like the right thing to do to me when as moving to .NET Core is a goal.

**Comment by adamhathcock** [comment]
If there's basic agreement, I can start on this.

**Comment by veikkoeeva** [comment]
Ping @jdom, @sergeybykov. Seems related to #2030.

**Comment by jason-bragg** [comment]
I am very much in favor of integrating an existing logging abstraction in lieu of maintaining an Orleans specific version.  Logging is not really our value add..

My preference would be for us to mature our dependency injection, and utilize it for logger implementation injection and move towards some well supported logging abstraction, as suggested here.

I am of the opinion that support for Microsoft.Extensions.Logging can be introduced via dependency injection independent of Orleans logging, after which Orleans logging can be refactored to call through to Microsoft.Extensions.Logging, souley to maintain backwards compatibility, while it is being deprecated.

I guess what I'm suggesting is to use DI and M.E.L to support and alternative logging system then deprecate the current one rather than continuing to maintain it.

**Comment by adamhathcock** [comment]
I'd only start with the static `LogManager` just to be a halfway house as DI isn't fully implemented.

**Comment by sergeybykov** [comment]
Completed in 2.0.
