### ISSUE TITLE
Consider amending testing documentation to include a simpler approach

### ISSUE THREAD

**Issue by sudsy** [dotnet/orleans#2042]
Being a bit of a newb at Orleans I was writing a small application and unit tests as a trial within our group.

I found that the [guidance](http://dotnet.github.io/orleans/Step-by-step-Tutorials/Unit-Testing-Grains) on unit testing actually was better for integration testing and the approach actually made it painful to mock dependencies to have a truly isolated unit test.

I would propose that there should be some additional documentation about testing grains by simply instantiating the grain directly and mocking away the calls to instantiate grains or streams.

Again, I am happy to contribute this if required.

**Comment by ashkan-saeedi-mazdeh** [comment]
@sudsy  Having mocked runtime and stream and ... is a nice approach for unit testing, What I wrote there back then was due to lack of any docs on unit testing and the fact that I did not try mocks,
If you think you can add to that documentation, It will be great, Add the mocked version of tests to the page and send a PR and the guys will review it.

A lot should be mocked however if the grain calls other grains and also use persistence and streams.

Partially related to it and generally related to test experience is the silo based testing experience.
Also when we want to use Silos, there are multiple approaches, I added #2028 in this regard and we should decide how actually the `TestCluster` should work out of the box. The `TestingSiloHost` is to be deprecated soon due to lack of support for full programmatic config. Tests need to be converted internally however yet so it will be around for now.

@jdom  told me about the `TestCluster` a few days ago and I tried to convert my tests to that and the out of the box experience wasn't as easy as `TestingSiloHost`

**Comment by sudsy** [comment]
I have pushed a sample of how I am doing unit testing with Moq and xUnit.

- It uses a single threaded task scheduler to emulate the Orleans scheduler
- It mocks Grainfactory, Streams and Persistence
- The sample test runs in 500ms on my machine

You will notice a hack in CollectorGrain.cs which I am hoping can be avoided.

``` csharp
 //This is a workaround required because the Grainfactory property is not virtual
        public new virtual IGrainFactory GrainFactory
        {
            get
            {

                return base.GrainFactory;
            }
        }
```
If we could change the GrainFactory property to be virtual, this hack wouldn't be required. I would then rewrite the test to remove the module.
