### ISSUE TITLE
Improved Orleans Host Model

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#2066]
This issue try to describe a proposal for a new hosting model in Orleans to enable a more "micro-services-like" deployment and maybe start enabling scenarios like "_Orleans as a Service_"
# The/Some problems

Lets see first some common problems this try to address and later how to do it.
## Deployment Model/Experience

Today people can deploy and host Orleans in a variate of ways but we've noticed that the easiest way and the one people like most, is the ability to pack their code in some format and push a single file to their server. This is common in PaaS (Platform as a Service) world like _Azure Cloud Services_ but what about on-premises users or the users that use regular VM, IaaS (Infrastructure as a Service) or even bare metal?

While in the _"hard-mode"_ (VM/IaaS) you will need to among a ton of other things, manage the application deployment, config files, and what else you need to get all the files together and start the process by yourself.

What if we could have a package format that works across PaaS and IaaS/on-prem (and even cross-platform when we finish #368) and an uniform deployment model that can be integrated in any CI/CD environment easily?
## Running the Silo

Today everyone has to build their own hosting app by either coding a console app, a Windows Service or using some extensions like `AzureUtils` that has a custom Silo for it. The newcomers to Orleans usually tend to use it on Azure Cloud Services because it is easy to use by using the current extensions and easy to pack because you have Azure SDK tooling to do the packing job for you. Nice right? But that are tons of limitations on Cloud Services as well and what about the other platforms and IaaS/VMs? What if we have an unified way to deploy our code by command-line, API, or whatever and the silo load the application from the dlls inside the package? What if we can easily manage multiple instances of the silo from a single place and they can host multiple versions of the same app in parallel? Multiple versions that can be for different tenants or even different deployments? YAMS takes care of keeping a .exe running and if it die, it just restart it, but it has no mean to monitor the application/service internal health. What if you want specify tags across a set of services that can be correlate with the silo types and deploy only those that has that tag to for example, guarantee an specific set of machines that has an specific hardware (GPU for instance)?
## Health and Monitoring

Today people have to make magic to integrate multiple external tools to extract metrics from a cluster. The Telemetry APIs make easier to push metrics from a single Silo to the outside world, but it is not intent to report health. What if you need to get machine level KPIs? What if you need to, based on those metrics take actions like for instance auto-scale by adding more VMs? What about having a Dashboard to present built-in KPIs aggregated for all machines, all Orleans clusters, or Grains across all deployments? How can you report the inner service health so you can maybe take an action if a service is unhealthy or make a upgrade rollback?
# The idea
## Big picture

Instead of having ad-hoc silo hosts (that together build 1 Orleans cluster for 1 deployment ID) and manage them individually, we would have a pool of machines joining to a pseudo-cluster where each machine has an agent called `OrleansHostAgent.exe` that is basically a Windows Service (or Linux Daemon). This service spin up 1 Process for each Orleans Silo node assigned to that server (virtual)machine and keeps them running in case they crash. It is also responsible of reading the application packages from a feed, deploy instances of it in new processes, handle package (and configuration) updates and capture/aggregate metrics from each one of those processes.

Basically this would be a very high level view of it:

![image](https://cloud.githubusercontent.com/assets/4714040/17687434/51d12c4c-634b-11e6-8890-9086ecb70194.png)
## The Agent

This component is the only thing that would be deployed to a server machine in the first place. Once it start, it would check to a centralized data store for the pseudo-cluster configuration about what packages are registered to run on that _type_ of node so it can download the required application packages and spin up the silo processes for each of them.

![image](https://cloud.githubusercontent.com/assets/4714040/17687438/5e710440-634b-11e6-8831-b4b2db02c892.png)
### Application Feed

The applications would be packed as regular Nuget packages. So there is no magic on the packing itself. The user only need to push the grain interfaces and implementations inside that package. If it only depends on external nugets, all the dependencies would be installed once the service is installed and leverage all the current versioning and packaging infrastructure already provided by Nuget.

This component would be responsible for host a private Nuget feed where it will host the Orleans application packages and backed by a configurable storage. It also allow the the usage of public/external feeds so the developer can just import full blow Orleans micro-services that were published on nuget.org for example and spin up silo processes for it on right away. (thanks to the @danvanderboom for the tip!)
### Metrics

This component basically collect metrics from the machine like CPU, Memory, Disk, Network regardless of the Silo process metrics and write to a configurable sink. It also can aggregate metrics for each silo process and grains (more on that later).
### Health

This components exposes a protocol from which silo processes can report their own health based on whatever the application running in the process consider healthy to be.
### Tooling

This component establish a protocol for management operations to be made and the integration with external tools for development and debugging.
### API

This API may be defined by a public surface for RPC or IPC channel so the Health and Tooling components can be reach from outside the agent. For example, this is the channel from where a Silo process can send its health status update and/or metrics from the process and/or specific grains along with any other custom global metric that the developer want to expose across the pseudo-cluster. This is also how external tools like PowerShell cmdlets would interact to the pseudo-cluster or to an specific node.
### Storage

The storage layer behave just as a persistence layer that would be configurable and behave as a single point of true for the configuration of the pseudo-cluster, a sink for the metrics and store the packages of the Orleans applications.
### Application Manager

This component basically manage all the application versions, updates, deployment, rollback, everything related to the lifecycle of each application running inside the Silo Processes registered for this agent. 
## The Silo Host

![image](https://cloud.githubusercontent.com/assets/4714040/17687443/6f1bb7fe-634b-11e6-8196-31b86cd6f8f7.png)

This component is the actual Silo host. It is a nothing more then a regular `SiloHost` implementation. From here one the silo functionality is no different then it is Today. The only thing is that the `SiloLoader` must find a silo implementation on the package that was deployed for this process. Maybe looking for an interface or being specific at its startup where the Agent pass as a startup parameter to this host so it can load the appropriate assembly and call the `Silo.Start()` method. 

Besides that, either Health and Metrics Reporters are the ones that a grain or silo code can invoke to report if the micro-service is healthy or not, and push the metrics from that specific process among any other custom metrics. The Agent proxy is just a client implementation of the Agent's RPC/IPC.
## Development Tools

Basically instead of having just Visual Studio templates, we will have more elaborated tooling that can provide package and publish just like the ones in Azure Cloud Service tools and present live metrics for a local running pseudo-cluster and its applications. The experience of **_"Right click -> Package/Publish Orleans Application"**_ would be nice :smile:

So, thats it. Does it make sense? I think this requires almost 0 changes on Orleans code. This whole hosting layer can be made around it so it would be an optional feature. 

I appreciate any new ideas to complement that so we at some point can come up with a plan to execute it.

Thanks!

**Comment by danvanderboom** [comment]
A few things. First, great idea and nicely articulated post about it!

Could Orleans extensions (like TelemetryConsumers, StorageProviders, and StreamProviders) also be delivered in the same type of deployment packages as used by grains and grain interfaces? I imagine a scenario where an Orleans Nuget package of grains could have a dependency on another package which contains a custom streaming provider used by that and other packages. With side-by-side hosting of multiple versions of the same Orleans grains on a silo, this would mean figuring out which host to install the extension packages into, keeping track of different extensions within each host... something that probably needs to happen anyway.

Could grains be packaged separately from grain interfaces? Would it make sense for a grain package to reference its interface package, so that the interfaces could be shared via packages with the other modules which need to reference those grains? Or is that too granular? (I'm guessing most people are going to package a number of grain types per assembly, not one-grain-per-assembly.)

I'm skeptical that this could all be implemented without modifying Orleans core, but being able to make this sort of hosting model work purely through extensions and external processes would be impressive.

re: "Application Manager" 
- Application Lifecycle Manager?
- Orleans Module Lifecycle Manager?
- Orleans Package Lifecycle Manager?
- ??

**Comment by danvanderboom** [comment]
I think we need to introduce the concept of an OrleansHostAgent-level extension, not just extensions to silos (also using Nuget). Then we could write an IXXXTelemetryConsumer extension for the machine level, install it there instead of in the silo, but using the same interfaces. A telemetry consumer at the host agent level could collect CPU, memory, and disk utilization and other machine-level metrics. Silo telemetry consumers could collect metrics from the grain loggers, silo extension loggers, etc. This would then have to be routed to the OrleansHostAgent, where it gets aggregated at the machine level.

**Comment by danvanderboom** [comment]
In the [MetricsTracker telemetry consumer extension](https://github.com/danvanderboom/Orleans.TelemetryConsumers.MetricsTracker), silo metrics are cached in the same process as the silo host, so it's "easy" to efficiently communicate those metrics to a single, aggregate cluster metrics grain somewhere in the cluster (without having to go through an Orleans client).

In this imagined future where an OrleansHostAgent is collecting and aggregating metrics data, I'm guessing there would be a need to use the Orleans client library to communicate with the cluster. If that's the case, I think it will be imperative that the Orleans client isn't static any more, and that multiple Orleans clients can be used from within the same process (such as by multiple extensions).

**Comment by danvanderboom** [comment]
Some kind of JSON/XML manifest could be defined to describe an Orleans system. Command line installer tool could read that manifest, pull all the packages down to that server, configure things in the environment as needed, boot up the OrleansHostAgent, and go.

Also an "Export Orleans cluster manifest" would be a fun option. Save a copy of your whole system, it's config, packages, etc, to resurrect on another set of machines, in another environment.

Orleans.DeepCopy

**Comment by sergeybykov** [comment]
Interesting. My initial impression is that this sounds like YAMS on steroids (in a good way) or a light-weight Service Fabric. Which immediately turned my brain into the "build vs. buy" analysis mode.

Do you envision taking YAMS as a base and add the missing functionality to it or building something from scratch?

Sounds mostly general purpose, not really Orleans specific, to me.

I believe Octopus Deploy uses NuGet packages for deployment. But it's not OSS and it requires SQL for metadata.

**Comment by adamhathcock** [comment]
I'm a newcomer but what I like the least is non-self hosting scenarios where I have to configure a black box binary to host my "user land" code.  Bad IIS memories are coming to mind with this scenario.

In the ASP.NET Core land, one of the best things was that you run the publish command and do xcopy deployment.  Then you just have a single exe to run as a service/daemon.  If I need N services, I just configure them as such.

Maybe my use-case isn't the target for this plan.  Just don't make it so I can't do xcopy deployment :)

**Comment by danvanderboom** [comment]
@adamhathcock Orleans is xcopy deploy-able now, and I don't think that will ever change. We are talking about building an additional/alternative deployment mechanism (based on Nuget packages) and a "Orleans package management" service to monitor the health of silos (supporting more than one silo per machine). Deployment to your cluster, rather than Powershell scripts and xcopy, would involve building a Nuget package for your Orleans project (adding a build step to build the Nuget), and publishing that (with a new VS/VSCode project menu plugin, or part of your CI process after tests pass) to a private Nuget feed.

**Comment by danvanderboom** [comment]
@sergeybykov It seems like this should be entirely external to Orleans itself, as @galvesribeiro has explained. I was assuming until reading your post that this would need to be Orleans-specific, taking some dependencies on the Orleans Nuget packages, for example, to access its abstractions in order to understand the health and status of silos. But now I suppose it's possible for a non-Orleans-specific YAMS-like process management tool to expose a generic API and protocol for doing application health checks, upgrading Nuget packages _for whatever system they're being pulled in to support_.

Which then makes me wonder: does something like this already exist? Need to do some serious Intergooglesearching.

**Comment by danvanderboom** [comment]
@galvesribeiro Where will the OrleansHostAgent log events, exceptions, detections of invalid states, etc? Or how can its logging provider be routed to a custom sink? If we're building monitoring tools and dashboards, one of the things we'll want to monitor is the activity of the OrleansHostAgent? When did it upgrade those packages? What was in them? Were there any errors install them? Did it have to back out the upgrade? Did it log an errors rolling back? These will be important things to surface in our system management tools.

**Comment by sergeybykov** [comment]
@danvanderboom 
>@sergeybykov It seems this should be entirely external to Orleans itself, 

That's my feeling, too.

**Comment by sergeybykov** [comment]
I'm closing this as an external. Feel free to reopen if you think that's not the case.
