### ISSUE TITLE
Immutable attribute in PCL

### ISSUE THREAD

**Issue by stuart-beattie** [dotnet/orleans#210]
I tried to submit a store app with a reference to the Orleans dll which subsequently failed certification. I had referenced the assembly in order to mark certain shared objects with the immutable attribute. Now I am faced with removing these attributes, removing the assembly reference and changing a bulk of server code to wrap every function declaration using the immutable class. This is not ideal. If the attributes could be moved to a separate PCL assembly I think that would be very useful.

**Comment by sergeybykov** [comment]
@onyultd Interesting. Could you please provide more context. Why is Immutable such a special case? Nothing else is a problem for certification? Immutable is just an Orleans-specific optimization hint (by convention). Are you using it for marking arguments of grain methods?

**Comment by onyultd** [comment]
I have a PCL library containing data transfer objects marked with the Immutable attribute. So my PCL library references the Orleans assembly. This library is referenced by my store (windows phone) app and by my web service. When these objects are sent to my web service they are then passed to the orleans runtime (and I mark them as immutable for performance). The certification failed because of the packaged Orleans assembly. I have subsequently removed the attributes and the Orleans reference from my PCL library and wrapped the service calls using the Immutable<T> class. It would be nice to be able to use the attributes in a PCL library though.

**Comment by gabikliot** [comment]
If Orleans run on [coreclr] (https://github.com/dotnet/coreclr), would that solve the PCL problem? Meaning, would you be able to reference it directly from your store app?

Another option to solve this is to come up with an additional attribute that will signal Orleans to treat this type as Immutable. This attribute has to be a standard attribute, already defined somewhere in the .NET framework. As an example, for serialization, if we encounter a type in your application assembly tat is marked as [Serializable], we generate an Orleans specific serializer, although in theory those 2 are unrelated.
So if we can suggest a similar attribute that can be used to signal "Immutable", it can be easily supported.

**Comment by yevhen** [comment]
@gabikliot Gabriel, another solution could be to support "bind-by-convention" a.k.a weak binding. That's very similar to how `async\await` is supported by C# compiler. Just change the code to check whether the class is marked with the attribute which type name is "ImmutableAttribute", rather then checking the presence of <Orleans.Immutable> attribute. That will allow developers to define the metadata in their own application and get rid of strong dependency on framework (assemblies).

**Comment by gabikliot** [comment]
A good idea.

**Comment by onyultd** [comment]
Sounds good. Or alternatively split the core Orleans assembly in two. One of which containing the attributes and any other dependent objects that may be reasonable to access from a shared class library.
