### ISSUE TITLE
Expose one shot timers

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2144]
As far I see, `RegisterTimer` call with `Constants.INFINITE_TIMESPAN` passed as the period creates one-shot timer, executed once. And this is used internally in a number of places. I think it might be useful if this feature is explicitly available in public API. For instance, in `RegisterTimer` method, `period` could be optional nullable `Timespan` so that `null` means the created timer is never repeated.

**Comment by sergeybykov** [comment]
In the timer API we tried to mimic the .NET timer API one to one, so that there's no discrepancy for developers to learn and remember. `System.Threading.Timer` doesn't appear to expose a feature like that. While I agree that would be handy to not have to pass `period` argument for one off timers, passing a `null` I'm afraid might be a bit confusing, as it would be equivalent to passing `Constants.INFINITE_TIMESPAN`.

**Comment by DixonDs** [comment]
The exact public API is up for discussion, I guess, and there are some other options like method overload, extension methods etc. Two things are important here though: 1) `Constants.INFINITE_TIMESPAN` is an internal constant 2) the feature doesn't appear to be documented anywhere.

**Comment by sergeybykov** [comment]
`Constants.INFINITE_TIMESPAN` is just our internal shortcut for -1 ms that follows the documented behavior of .NET timers - https://msdn.microsoft.com/en-us/library/ah1h85ch(v=vs.110).aspx. It would probably help to update the XML docs for parameters of `RegisterTimer` to match the MSDN descriptions.
