### ISSUE TITLE
Explicit removal of stream producer?

### ISSUE THREAD

**Issue by Kwal** [dotnet/orleans#2148]
I have a situation where an API layer is utilizing SMS based streams for 'one time events' such as the creation or removal of an entity and there should be no need to use the given stream/namespace combination again if the call to OnNextAsync completes successfully.

Although all of the consumers (implicit grain subscriptions) are removed from the rendezvous grain, the producer (which from what I can tell is the GrainClient) is not. This appears to prevent the overall cleanup of rendezvous grain from storage.

Is my understanding of this correct? If so, is there a way to explicitly remove the client as a producer for a given stream/namespace combination?

**Comment by jason-bragg** [comment]
A producer grain -should- cleanup its stream resources when it deactivates.  This means state will remain as long as the grains are active, but should go away when they are collected after being idle.  Silos that are shutdown may not deactivate its grains so those states may not be cleaned up.

What storage provider are you using?
Are you confident producers are not getting cleaned up, or are the remaining states empty?  Depending on the storage provider and settings, storage providers will not always delete the grain state when there are no more producers and consumers.  It may just store an empty state.  If you're using azure table storage provider you can set  DeleteStateOnClear = true to tell the provider to delete the entity when clearing the grain state rather than storing an empty state.

**Comment by Kwal** [comment]
We're currently using a custom storage provider that serializes to JSON and it is setup to null out the state if the grain is in fact cleared.

> A producer grain -should- cleanup its stream resources when it deactivates

Does the GrainClient (used outside of the Orleans runtime) utilize a grain when publishing to a stream?

Just to be clear on the producer, we're using code similar to this from a Web API controller:

`var streamProvider = GrainClient.GetStreamProvider("Default");`
`var stream = streamProvider.GetStream<Foo>(foo.Id, nameof(Foo));`
`await stream.OnNextAsync(foo);`

**Comment by jason-bragg** [comment]
Ah, I assumed grain to grain.  Bad assumption on my part.
Client should clean up state by calling GrainClient.Uninitialize() before the client shuts down.

**Comment by Kwal** [comment]
Ah, gotcha.

We've typically tried to keep our client initialized - this would make it seem like we'd want to move to more of a per-request initialization. Is there any reason to avoid that?

**Comment by jason-bragg** [comment]
>per-request initialization. Is there any reason to avoid that?

Unclear, I've not tried that, but I don't think initialization is light, so I'd suspect performance issues.  Maybe a periotic re-initialization?  Every 5 minutes?

This does seem like it could be a problem for long running clients or clients that crashed, hence didn't clean up at all.  I suspect you could extend IAsyncStream to be an IAsyncDisposable, allowing users to dispose of streams themselves rather than waiting for grain deactivation or client shutdown.  This could be done in your own fork of the repository and if it worked could be submitted as a PR to the master repository.

**Comment by Kwal** [comment]
Perhaps the best way to handle it is to utilize a grain that acts as the sole producer so it can clear/deactivate itself when it is done publishing.

Thanks for the feedback 👍

**Comment by gabikliot** [comment]
Seems like the one time streams you are describing are more similar to what @ReubenBond  calls Ad-hoc observable streams https://github.com/dotnet/orleans/issues/1931, which are ephemeral and not persistent like the regular virtual streams.

**Comment by Kwal** [comment]
I'm attempting to utilize a StatelessWorker to do the publishing as opposed to publishing directly via a GrainClient in the API, but I'm actually experiencing the same behavior e.g. the activation for the StatelessWorker grain is not being GC'd by the runtime thus not allowing the rendezvous grain to be cleaned up.

I know that attempting to subscribe from a StatelessWorker will produce undefined behavior, but would producing also be an issue?

**Comment by Kwal** [comment]
It looks like there is a Cleanup method in the internal StreamImpl class (https://github.com/dotnet/orleans/blob/e2e0c5b2a12a7c831224f89a3c550e0d9c60a0d1/src/Orleans/Streams/Internal/StreamImpl.cs#L65).

A quick test calling this (via reflection) seems to have done the trick. Would there be an issue with exposing this on IAsyncStream?

**Comment by jason-bragg** [comment]
Producing from a stateless worker won't work.  We can go into why if you're interested, but in general, that pattern is not supported.

>Cleanup method in the internal StreamImpl ... Would there be an issue with exposing this on IAsyncStream?

This was what I had in mind when I proposed having IAsyncStream inherit from IAsyncDisposable.  In the implementation the DisposeAsync could call the internal Cleanup.

I'm not 100% opposed to exposing the cleanup call itself, but I think having a cleanup call creates an unclear usage pattern.  For instance, what happens if someone calls cleanup then produces more data?  Can one still subscribe to a stream that has been cleaned up?  What happens when one calls cleanup on a stream that one is consuming data from?  Does it unsubscribe?  These questions can all be answered, but the point is that the call pattern itself raises these questions and makes it unclear how to use the api.

IMO, an asynchronous disposable pattern is more clear.  One disposes of the stream object when one has no more use of it, and it becomes invalid for any future calls.  Since it can't produce any more, it would clean up its calls in the pubsub system, but does not have any effect on subscriptions, which are still managed by the subscription handle.

I'm very open to other views, but if we're to modify the public surface to address this, which is reasonable in my view, we need to think through how this effects the usage patterns and expected behavior.

**Comment by jason-bragg** [comment]
Taking a step back.. 
Have you considered using implicit subscriptions?

**Comment by Kwal** [comment]
The consumers in this case are using implicit subscriptions and they are removed from the rendezvous grain as expected. It's just the producer that is still hanging around and not being cleaned up.

**Comment by jason-bragg** [comment]
Oh, if you've no explicit subscription in you're environment, you should be able to configure the stream provider to only use implicit subscriptions.  With this config setting you will not need the pubsub storage at all.

"PubSubType" = "ImplicitOnly"

**Comment by Kwal** [comment]
For the purposes of what we're doing with these streams, using 'ImplicitOnly' works quite well.

That being said, having some type of disposal mechanism for a given stream would be useful. I'll see if I can put together a PR for the IAsyncDisposable as discussed above and link it to this issue.

Thanks for all of your help @jason-bragg
