### ISSUE TITLE
[Question] Streaming API and handling of failures

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#2247]
I have a question regarding streaming API as documented here: https://dotnet.github.io/orleans/Documentation/Orleans-Streams/Streams-Programming-APIs.html

I understand that a reactivated producer grain can reconnect to an existing stream, and that a consumer grain gets automatically reactivated when a message comes in but the grain is currently deactivated.

My questions:

1) When the consumer throws an exception when the message is received, will the exception get propagated back to the producer? My guess: no, the streaming API is designed in a way that the producer just fires and forgets.

2) When the producer publishes a message but the message cannot be transported to one of the subscribed consumers (for some reason, say due to network issues), what happens? (a) The message lost. (b) The producer gets an exception.

If (2a) was the correct answer, how will I ensure that every registered consumer will receive the message?

If (2b) was the correct answer, I simply would reissue the message.

Thanks in advance.

**Comment by gabikliot** [comment]
The answer depends on which type of stream provider you are using. The semantics vary between stream providers. We deliberately designed it this way, since we believe it is not possible  (or very hard) to come up with unified semantics for all possible types of streaming implementation.

1) For SMS: if configured not with FireAndForget, the exc will indeed be propagated back to the producer. With fire and forget it will not. For queue base streams, it is indeed one way, so no.
2) In SMS - it gets an exc if NOT FireAndForget, or lost if yes FireAndForget.
In Queue based streams - if the msg got enqueued, the streaming infra will try to deliver a couple of times, and if failed, there is a special behavior that can be set, per stream provider, to specify what to do. One popular choice is to treat it as poison msg and store it in a different durable,table.

**Comment by peter-perot** [comment]
Thank you. I just see that the docs have been enhanced with much more details in the meantime. Perfect!
