### ISSUE TITLE
Should we automatically retry when we encounter SiloUnavailableException?

### ISSUE THREAD

**Issue by benjaminpetit** [dotnet/orleans#2283]
Following #2282 

If we detect that a gateway failed, should we retry automatically to "reroute" all the message not yet sent to another gateway?

There is no risk to duplicate request here if we make sure to retry only messages not sent, but we have to preserve call ordering.

**Comment by gabikliot** [comment]
You are talking about msgs queued on the particular GW  in the client (that is, the msg was already addressed via this GW and is now in the GW sent queue, but not pushed via socket yet).

Yes, I think that would be nice. We can indeed save all those msgs. 
Looks at `GatewayConnection.Stop`. 
1) When we call base.Stop(); we should go to base (AsynchQueueAgent), 
2) take all the queued msgs (requestQueue) 
3) clear the msg.TargetSilo and msg.TargetActivation
4) and just resend it via msg center (MsgCenter.SendMessage(msg))

Taking msgs from requestQueue will ensure that the msg was not sent yet (since it is BlockingCollection and is already synchronized/thread safe internally), so you don't need any extra lock or flag on the msg.

**Comment by benjaminpetit** [comment]
Yes, that is this use case I was talking about.

Not sure it will add lot of complexity if we bundle fixes for this and #2282. I will try to send a PR addressing both issues

**Comment by gabikliot** [comment]
I prefer not to bundle fixes.

**Comment by gabikliot** [comment]
Resolved via #2298. If a gateway fails but a client still has queued but yet not sent msg to this gateway, we now re-route them (via a new gateway). If the msg was already sent, we don't reroute it.
