### ISSUE TITLE
Non-generic StreamSubscriptionHandle

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2311]
I have a scenario when I want to collect subscription handles in the list and call `UnsubscribeAsync` on each of them at some point. It would help if we have some non-generic parent abstract class or interface that would hold `UnsubscribeAsync`.

It could be also useful if can call `SubscribeAsync` on a stream object without specifying the generic method type. For instance, there could be a scenario when I want to do some action on any event from the multiple streams regardless of the specific event types.

**Comment by jason-bragg** [comment]
I’ve been quite discontent with the subscription handle for some time so I understand your pain.  My preference would be to do a single large breaking change rather than fix the many issues one by one.  The reason for this is that the StreamSubscriptionHandle was intended to be a serializable class, but it’s only implementation (StreamSubscriptionHandleImpl) was not build with any consideration for backwards compatibility, so changing it is not just a compile time breaking change, it could alter persisted state.

For more advanced usage scenarios like you’ve described, I’ve used a disposable wrapper.  Something like the below.  I’ve only ever done this in the application layer, but it’s something that can be considered for the framework.

    [Serializable]
    public class DisposableStreamSubscriptionHandle<T> : StreamSubscriptionHandle<T>, IAsyncDisposable
    {
        private readonly StreamSubscriptionHandle<T> handle;

        public override Guid HandleId => handle.HandleId;
        public override IStreamIdentity StreamIdentity => handle.StreamIdentity;

        private DisposableStreamSubscriptionHandle(StreamSubscriptionHandle<T> handle)
        {
            if(handle == null) throw new ArgumentNullException(nameof(handle));
            this.handle = handle;
        }

        public override Task UnsubscribeAsync()
        {
            return this.handle.UnsubscribeAsync();
        }

        public override Task<StreamSubscriptionHandle<T>> ResumeAsync(IAsyncObserver<T> observer, StreamSequenceToken token = null)
        {
            return this.handle.ResumeAsync(observer, token);
        }

        public override bool Equals(StreamSubscriptionHandle<T> other)
        {
            if (other == null)
            {
                return false;
            }

            DisposableStreamSubscriptionHandle<T> otherDisposable = other as DisposableStreamSubscriptionHandle<T>;
            if (otherDisposable != null)
            {
                return otherDisposable.handle.Equals(this.handle);
            }
            return handle.Equals(other);
        }

        public Task DisposeAsync()
        {
            return handle.UnsubscribeAsync();
        }
    }

I am open to other alternatives, as I really do not like the current state of the handles, but have not had time to fix them.  If anyone has the time to invest in cleaning up the subscription handles, I’d be happy to provide more details on some of their shortcomings.

**Comment by DixonDs** [comment]
@jason-bragg I think it would help if you list all shortcomings known to you just for further reference in case someone wants to pick this up and think about a new design of the subscription handles.

**Comment by jason-bragg** [comment]
Below are some issues from memory, though I suspect I'm missing some.
At a high level we need a simpler sequence token that can be modified (some versioning strategy), works well with rx style expressions, can simplify sequence token management and event deduplication, does not depend on static data, and that plays will with the subscription information in the pub-sub system.

Shortcomings:

- Type specific
-Limits containment. (this issue)
-Complicates development of extensions (like Select) which may perform transforms on the data.

- Current implementation includes the entire stream implementation as serializable state rather than minimum persistent data.
-Fragile, wasteful, difficult to maintain.

- No backwards compatibility serialization support.
-Hinders non-breaking changes.

- Sequence Token is not stored.  Sequence token can be entirely hidden from the user if made as part of the handle.
-Users now have to store the sequence token as well as the handle.
-Users now have to perform custom deduping when necessary.  This can be entirely handled within the stream infrastructure (requiring no user logic) if handle contains authoritative token.

- Subscription is also stored in the pubsub system. 
-If application stores this information as well, we have duplicate persistence of the same data, which can now be out of sync.

- Resume/Unsubscribe operations are not passed the stream provider, requiring access to some sort of static to get access to the stream provider.

- RX style expression support.

If we wish to continue modeling off RX patterns something like the following should be possible.

    IAsyncObservable<MyEvent> stream = streamProvider.GetStream<MyEvent>(id);
    await this.handle = stream.Where(e => !Ignore(e))
                              .Select(e =>new CatalogEntry{ Event = e, Catalog = FindCatalog(e.Catalog))
                              .SubscribeAsync(ProcessCatalogEntry);

then later resume using something like

    await this.handle.Resume(ProcessCatalogEntry);

with the underlying streaming system managing the reactive expression tree and sequence token, and performing event deduplication for the user.

**Comment by jason-bragg** [comment]
My previous post touches on some issues with the handle as it exists today, as the result of the SubscribeAsync call, but I'm not convinced this is a pattern we want to continue going forward.  Reactive extension patterns do not map well to distributed asynchronous event processing.  Deviating from this pattern, howerver, is a much bigger change.  I note this mainly to communicate that problems we encounter with the handle are not necessarily separate from the larger streaming model and the asynchronous reactive extensions patterns we've built it on.
