### ISSUE TITLE
Migrate samples to 2.1

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#2359]
The samples (https://github.com/dotnet/orleans/tree/master/Samples) are on 1.2.3 now. Shouldn't be to difficult to migrate them to 1.3.0.

**Comment by serbrech** [comment]
Here is the list of the sample projects to track progress :

- [ ] Adventure
- [ ] AdventureDotNetCli
- [ ] AzureWebSample
- [ ] Chirper
- [ ] FSharpHelloWorld
- [ ] GPSTracker
- [ ] HelloWorld
- [ ] Presence
- [ ] ServiceFabric
- [ ] StorageProviders
- [ ] TicTacToe
- [ ] Tutorial.Minimal
- [ ] TwitterSentiment
- [ ] UnitTesting.Minimal
- [ ] VBHelloWorld

It also looks like I'll need to update the visual studio version because of tooling dlls referencing vs11 paths.

**Comment by serbrech** [comment]
Could you take a quick look at the package.config here? more package had updates available than I expected https://github.com/serbrech/orleans/commit/c02f48b0d234f0cbd1050ab66ad46d69386391c9
see in particular the System.*
Reason for that is the new dependency on System.Collection.Immutbale, which suggested an update to all the other ones too.  
Just want to be sure before I proceed with all the other sample projects

**Comment by attilah** [comment]
Thanks for taking this issue! ;-)

As a rule of thumb we require the lowest dependency version from all packages, so please - if for other dependencies it is not a requirement - don't upgrade to "latest and greatest" :-) stick to the versions of packages what Orleans is using in its current master branch (which always will be the next release).

**Comment by serbrech** [comment]
Oh, that's not closed yet though, I'll keep working through the different Samples.
@attilah

**Comment by attilah** [comment]
I don't know why was this closed :-O

**Comment by jdom** [comment]
Thanks a lot for doing this. BTW, we plan to release 1.4.0 really soon though, does it make sense to wait 1 week until it's released and update to it instead?
Otherwise, you can also run `Build.cmd`, and that would generate 1.4.0 packages locally so you can reference them (there is now a nuget.config that will automatically pick them up). Check out HelloGeoSample for an example doing this.

**Comment by serbrech** [comment]
after struggling with the first couple projects, I know exactly which packages need to get updates. So I'll try to write a script to run the apropriate nuget updates commands, and the subsequent packages.config edits.
That should cover 90% of the updates, and it will help for future releases too.

**Comment by serbrech** [comment]
so, I have a solution that I will finish tomorrow, but it would be so much easier if this was implemented in nuget : 
https://github.com/NuGet/NuGet.Client/pull/1044.

Today, you can do : ```nuget.exe update MySolution.sln -Id "MyPackage"```

And that will update the package and all its dependencies  
The problem is that nuget updates the dependencies to *their latest*, and we cannot tell it to resolve them to their lowest...  
Concretely in Orleans' case,  it means that we drag down `System.Collections.Immutable 3.1.0` while the rest of Orleans uses 1.1.3.7.
And `System.Collections.Immutable` in version 3.1.0 has heaps of other dependencies that are really not needed in this case... Silly snow ball effect.

So instead, I update first the Immutables package to 1.1.37 manually, and then run the update commands, and nuget is happy...

Baah

**Comment by jokin** [comment]
I modified the HelloWorld.NetCore  sample to work with the tech preview 3, Should we create an issue to track the migrations to 2.0.0 also?

**Comment by sergeybykov** [comment]
I think we can reuse (rename) this issue for migrating samples to 2.0.0. Once 2.0.0 is out, it won't make sense to migrate to 1.5.0 anymore.

**Comment by jokin** [comment]
ok, right now the netcore sample is not included in the issue, and the changes so it can buid with the preview are really straightforward ( https://github.com/jokin/orleans/commit/6ef8586c6f1cf331024162b6aa3ed9a45a3f7eb5 ) I Will watch the issue.

**Comment by sergeybykov** [comment]
Now that 2.1 is out, it also makes sense to leverage the [new codegen package](https://www.nuget.org/packages/Microsoft.Orleans.CodeGenerator.MSBuild/).

**Comment by ReubenBond** [comment]
All samples have been migrated to a newer 3.x version
