### ISSUE TITLE
Conceptual Reminders\Timers issue with Production\Staging deployment and VIP swap.

### ISSUE THREAD

**Issue by centur** [dotnet/orleans#2432]
We continue to work around the surfaced issues with Prod\Staging style of the deployment. 
It might be that we are doing something wrong with Timers and reminders but it seems that there is a logical problem with this area:

We are using reminder to resurrect the grain and internal timer on it to do some periodic work (in our case - sync information about user from external service to our local copy, as they are throttling us and we have to have a partial copy of their state). 

With Production\Staging deployment this "guarantees" to have two activations  of the same grain, across 2 clusters, which is periodically writing the State and breaking eachother ETags. With one of our cases - external data it's more or less ok - we ended up having the latest state, no matter whether it was written by an instance on Prod or Staging slot. Logs have some error entries but now we know who causes them...

But some other applications are not so "healthy" - we are using timers to run poor-man-queue, doing a quick implementation of an Azure Queue which sits inside the Silo, in memory, periodically backing itself to the storage and using Orleans timer to ping-pong tasks between Pending and Processing pipelines if timeout (of timer) expires and caller hasn't reported that it completed the picked job. This fails with Prod\Staging deployment.

I understand that this is partially our own fault and we should not have such hacky thing in the code, but use real Azure Queues instead, but I can see some very valid timers and reminders cases which will fail in Production\Staging deployment scenario. 

Are we missing something, are timers and reminders not designed to work in such scenarios (what's about "born in cloud" motto - Prod staging and vip swap is also born in cloud :( ). Is there a known solution to such problems ? 

Also it feels that such typical Production\Staging deployment breaks the main assumption of Orleans - Single valid activation of the grain, and the only thing that stops everything from falling apart completely is that the lion share of what we've built is very reactive, thus staging deployment will not receive any incoming calls - so will not cause any conflicts ( which also means - we can't really warm-up staging at all, because it will immediately break once it starts to receive traffic - all warmed up data may be outdated and with broken etags). 

Is this something that we can talk about and address this outside of Orleans? It feels like this is a bigger conceptual issue with a reliable deployment and the state model - every orleans cluster would be in the situation when there is 2 valid activations using the same shared state - during the deployments.

Keen to hear any input and thoughts on this

**Comment by sergeybykov** [comment]
There are two answers at the moment.

1. If Staging and Production are joined with a vNet and share the same deployment ID, they can run as part of the same cluster. 

2. With the Global Single Instance part of the geo-distribution now integrated in 1.3.0, Staging and Production can be treated as part of a multi-cluster with each grain getting activated in only one of them at any point of time. This way Staging and Production can be added to and removed from the multi-cluster without violating the single-activation guarantee. I think we still have an issue with reminders firing in both clusters though.

@benjaminpetit is about to publish a PR that is meant to add support for heterogeneous silo, so that different silos in a cluster could have different sets of grain classes deployed. This will allow, among other things like HW-specific deployments, for Staging to introduce or retire grains classes while still running within the same cluster with Production.

Another feature @benjaminpetit is exploring is support for explicit versioning of grain classes with lazy in-place upgrade.

We plan to discuss all these aspects of the upgrade/versioning story in the next community meetup.

**Comment by centur** [comment]
If I understand correctly - sharing the same DeploymentId between staging and production may be dangerous as in case of non "forward and backward compartible" interface changes - this may produce some weird chains of calls. We intentionally separated Staging and Production by id to prevent such unpredictable flows ( also we never configured vNET between prod and staging to keep it fully physically isolated). 

With regards to multi cluster configuration - this may be an option in the future, but I'm reading documentation and not sure we are ready to switch to this model - we need a thorough testing before we can try it...

**Comment by talarari** [comment]
@centur did you manage to get this to work? we really want to do a staging/prod swap, currently doing rolling upgrade which sucks because every deployment we get timeout errors.

@sergeybykov  "I think we still have an issue with reminders firing in both clusters though." - is this still the case?

we're really missing samples or docs on how to do a staging/prod deployment, which is kind of basic this day and age, but it feels like this is just impossible with orleans.

**Comment by centur** [comment]
@talarari We have it working as per initial post, it was just an issue with 2 grain activations writing into the same state and throwing errors for a period of 2 active deployments. We are writing data consistently it's just errors in logs that we don't like. I'm keen to hear any opinions on how this can be solved. 

The idea I have in mind for doing it differently is to split our grain from reminder to 2 separate grains - one has a reminder and produces messages into some queue, another one - pulls from that queue via virtual streams. And from some other conversations - you can configure stream to start in disabled state and send a message to it so it will start pulling from queue. This is not very different from having this reminder grain disabled on start and switch it to running state by explicit call to some method (e.g. `Task StartPullingData()` ) and call that method on vip-swap or health check. 

This still has smell of not very good design and will not work well for any complex scenario like blue\green deployment when you need to have production and staging (old and new version) to run in parallel for a long time. We would need to design differently for such cases and I haven't thought about this yet.

Also we are moving away from Storage providers model to SQL for some grains and we are planning to change that grain and make SQL updates to the data rather than via grains - this would allow us to make updates only if record is outdated and in theory - would allow us to eliminate the clash between 2 grain activations - they will be cooperating over updates to the table, not competing
