### ISSUE TITLE
Allow configuration of per-type age limit as attribute

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2434]
Checking the documentation here http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Activation-Garbage-Collection.html I see that it is possible to set the per-type age limit in the server configuration. I think it might be handy if you can set it as attribute applied to the grain implementation class.

**Comment by sergeybykov** [comment]
The downside of specifying age limits in the code is that one has to recompile it in order to adjust them. That's the main reason we put in the config. But I guess we could use the config settings as overrides to get both benefits - simpler "80% case" with attributes, and still have the config overrides for advanced "20%" cases.

**Comment by DixonDs** [comment]
@sergeybykov Yes, that's true, but it is better to have that choice. In the end of the day you can say the same about programmatic configs, `maxLocalWorkers` param in `StatelessWorkerAttribute` and a lot of other things.

**Comment by sergeybykov** [comment]
Resolved via #4890.
