### ISSUE TITLE
Azure Queue Stream Provider and DeploymentId

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2442]
Currently, when `AzureQueueStreamProvider` uses DeploymentId to create target queue names, this is done in `AzureQueueDataManager` as follows:
```
QueueName = deploymentId + "-" + queueName;
```
The issue is that it is easy to get a non-valid Azure queue name if DeploymentId contains upper-case letters, starts from a digit etc.

Are there better ways to use DeploymentId to construct unique per-deployment queue names but at the same time allow any DeploymentId value? Maybe instead of prefixing with plain DeploymentID value, we can prefix with its hash in some compatible form?

**Comment by jason-bragg** [comment]
For azure tables we have some code to 'sanitize' names/keys, ensuring that it fits the table store rules.  I suspect we can write something like that for the azure queue stream provider.

When it comes to deployment specific queues, my preference would be to simply allow users to specify the queue name directly rather than build one for them.  If they want a deployment specific queue, they can build a deployment specific queue name.  Though that change would on be backwards compatible.

**Comment by DixonDs** [comment]
@jason-bragg  If we go with the first option, I think it is still better to use not only sanitized deployment id, but also some hash of it to ensure that there are no collisions after sanitization.

I think the second option is clearer (and the user not always even wants deployment specific queue names), but yes, it is not backward compatible.

So maybe we can do the first option now (which seems to be a pretty quick fix), but also implement the second option for 2.0?

**Comment by sergeybykov** [comment]
Sanitization has been implemented in #4001.

In addition, we still want to make queue names configurable. But we'll probably do that post 2.0.0.

**Comment by xiazen** [comment]
we made azure queue name configurable through AzureQueueOptions. Close this due to resolved.
