### ISSUE TITLE
Expose system targets to application code

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#2444]
This idea has been discussed more than once in the past. It has been brought up again in https://github.com/dotnet/orleans/issues/2421#issuecomment-262569302.

>So I've been looking for other solutions as my pattern is really opposing being shoe-horned into Orleans Streams.
My first thought was using the IGrainObserver pattern, with a Grain per EventStore Stream, however it would need to be brought to life on Startup, perhaps using a Reminder, then I would have many Reminders ticking for no reason once the Grain was alive.
However I then dug into Reminders further, and it looks like Reminders are implementing exactly what I am after. They can be load balanced across silos, can invoke Grain operations, be registered from a Grain, callback that grain, are persisted and deal with silo loss/addition.
I think some minor adjustments to a copy of LocalReminderService would work very well for this. Unfortunately it looks like a lot of objects LocalReminderService interacts with are Internal, and the Silo also lacks any hooks to register SystemTarget objects.
This is a pity as it really looks like a good fit for what I need here - do you have any plans to take some Internal classes and expose them? Also - am I missing some hook where I am able to register a SystemTarget? The Service would need to be alive before any Grains are activated otherwise they could call a Target that did not yet exist.

I see at least two potential ways, likely complementary, to expose such functionality to application code.

1. Partitioned system service. Essentially a generalized version of the Reminder service, but with an application system target class instead of `LocalReminderService`, e.g. `GrainService`, and a corresponding equivalent to `ReminderRegistry` proxy class, e.g. `GrainServiceClient`. We only create a single `LocalReminderService` system target per silo today, but it shouldn't be too difficult to make that number configurable. In this approach, callers are completely oblivious to partitioning and routing, and it's the responsibility of the `GrainService` to react to repartitioning events and changes to the ring range it owns.

2. Ad-hoc system targets created at run time by application code. This would be similar to how we create pulling agents for stream providers. Application code, a bootstrap provider or grain code or DI, would explicitly create an app system target, e.g. we could call it a `PinnedGrain`, and pass its reference to whatever app code needs to talk to it. The grain reference will be valid for as long as the silo the system target was created on is alive. After that, it will throw on an attempt to send a message via it. In this approach, it's the responsibility of the code creating `PinnedGrains` to manage them and partition the load across them.

**Comment by jamescarter-le** [comment]
Thanks @sergeybykov - This change would enable people to write services requiring such Ring based activations much easier, seeing as how currently the internal restrictions prevent us from doing that.

Without knowing Orleans internals thoroughly, Option 1 would give us developers a way to write such services without having to delve too deep into how the IRingRange works, just like we can calls Grains with confidence, not being PHD's in distributed application design.

I'm happy to look at contributing to this, if someone was to summarize the tasks involved, perhaps with some direction I could get the grunt work done for a project owner to take to completion. 

Many thanks for your support.

**Comment by jamescarter-le** [comment]
I'm going to look to start implementing this feature during the week. If you have any prompts for me before I begin that could help ensure code you can easier approve that would be appreciated.

**Comment by sergeybykov** [comment]
I wanted to see how easy it'd be to refactor `LocalReminderService` into a subclass of an intermediate public class like `GrainServiceClient`, and `ReminderRegistry` as a subclass of public `GrainServiceClient`. If we can do that, than the rest should be, hopefully, straightforward.

**Comment by ReubenBond** [comment]
Rather than exposing `SystemTarget`, which is exciting but perhaps not ideal, what if we added support for fixed placement to `Grain`s? Do you think that could be made to work instead?

It's not same as a `PinnedGrain`, it's a grain which has a `[FixedPlacement]` attribute and has references created via (for example) a `GetGrain` overload which takes a `SiloAddress`.

Under the hood, similar changes are required, but this gives us the benefit of identical scheduling and lifetime management to grains without exposing an internal concept.

I think it's worth discussing, since this is a fairly big deal.

**Comment by gabikliot** [comment]
I think I agree with @ReubenBond. There are st

**Comment by sergeybykov** [comment]
I'm concerned of potentially mixing the abstractions here, which will likely cause confusion. Grains are virtual actors with eternal lifetime. A system target bound to a silo address is nothing like that. I think having a separate notion for that, like `GrainService` (name is approximate, of course), would more clearly delineate the differences and set expectations.

**Comment by jason-bragg** [comment]
I’ve been thinking about the system target problem, as they are utilized in the persistent stream provider, for some time now.  The use of system targets is among the hindrances external developers face when developing comparable streaming solutions.  While this problem does not precisely map to the needs of @jamescarter-le, the similarities are sufficient to suspect that the possible solutions I’ve been contemplating may be applicable.

Solution 1:  Balanced grain placement policy.
Since neither the Membership protocol nor the Consistent Ring Provider are publicly accessible and there is no means of placing grains on specific silos, the application layer has little support for balancing critical resources across the cluster.  These capabilities would, however, be available to a placement policy.  Rather than exposing these systems as well as system targets to the application layer, we could expose a balanced placement policy which ensures balanced resource placement.  Like the queue balancer, this system could use an underlying balancer algorithm to support different load balancing criteria.

Solution 2: Orleans silo services + grain extensions.
If we exposed the ability to install grain extensions to the application layer and extended the provider model (OrleansSiloService?) to support application logic running in the context of a system target, application developers could develop per silo callable logic.  Silo services which installed grain extensions at runtime could be configured (as providers) ensuring balanced per silo placement.  One difficulty in this approach would be obtaining the address of these systems, but this is solvable at the application layer if needed.

**Comment by ReubenBond** [comment]
Regarding the use of grain extensions, that was a consideration when writing #2446 - the idea was to have potentially multiple grain extensions of the same type and different id.

@sergeybykov I agree that there's potential for trouble with conflation (`Grain` = Virtual Actor, `SystemTarget` = 1972 Actor), but that doesn't mean `SystemTarget` is the right approach, it's just the easy one.

Downsides of using `SystemTarget`:
* They have to be started & registered explicitly - they do not have managed lifecycle.
* They can only be activated locally, i,e, Silo B cannot activate a SystemTarget on Silo A
* Dependencies which are internal to `SystemTarget` must be passed in by the end-user because the system does not control construction/initialization. There's a good chance that we will make a breaking change to `SystemTarget` for #467 so that dependencies are passed in instead of using globals. (eg, `InsideRuntimeClient`, `GrainTypeManager`, maybe `RuntimeContext`)

Upsides of using `SystemTarget`:
* It exists
* It's clearly not a `Grain`
* It has a scary name, which is good since we don't want users to use `SystemTarget` whimsically.
* Most of the supporting infrastructure is fairly appropriate already and just needs to be made public.

I'm not completely against exposing `SystemTarget`, but I hope that the pros and cons have been considered in the context of something which will be around for a long time.

**Comment by ReubenBond** [comment]
Sergey helped to clarify that this change doesn't directly expose the ability for consumers to create their own `SystemTargets`, so I'm fine with the design of this change as-is (but have not reviewed the specifics)

**Comment by jamescarter-le** [comment]
Happy to continue work on this once consensus has been reached.

**Comment by ReubenBond** [comment]
@jamescarter-le I'm happy with the general direction, so please feel free to keep going :) I won't be pushing back

**Comment by jamescarter-le** [comment]
Thanks I will push forward this week and hopefully have something for you all to review come the start of next week.

**Comment by sergeybykov** [comment]
To clarify and share what @ReubenBond and I discussed offline.

The path we are pursuing with @jamescarter-le is Option 1 in my comment above and pretty much Solution 2 in @jason-bragg's one.

The idea here is that each silo will automatically activate instances (initially one per silo, later we can extend it to also support N) of the application `GrainService` subclass. No application code would be used for creating them. Routing of requests will be performed based on consistent hashing of the partition key (grain reference initially) and mapping the hash to the ring ranges owned by silo (later on by subdividing the silo range into N slices if necessary). No application code will be needed to route requests to the partitioned service or to handle silo addresses.

Initially, `GrainService` (or whatever name we end up using) will simply extend `SystemTarget`, which has to be made public for that, in order to minimize the amount of refactoring needed to make the scenario work. Later on, we can refactor `GrainService` to not extend `SystemTarget` and `IGrainService` to not extend `ISystemTarget`, and add codegen and other support for that. However, such refactoring will not impact the API and behavior of the classes used by application code, and hence won't be disruptive.

**Comment by ReubenBond** [comment]
For the intent of this particular issue, this was resolved by #2531 / #2459
