### ISSUE TITLE
Support one-shot reminders

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2454]
It would be great to have similar experience with reminders as with timers in regard to having a possibility creating a one-shot reminder. For timers it is possible by passing `TimeSpan.FromMilliseconds(-1.0)` as the period.

On the related note, the following check in `ReminderRegistry.RegisterOrUpdateReminder` seems to be redundant currently:
```
if (periodTm < -1)
    throw new ArgumentOutOfRangeException("period", "Cannot use negative period to create a reminder");
```
as below we have a check for period to be no less than 1 min:
```
if (period < Constants.MinReminderPeriod)
{
    string msg = string.Format("Cannot register reminder {0} as requested period ({1}) is less than minimum allowed reminder period ({2})", reminderName, period, Constants.MinReminderPeriod);
    throw new ArgumentException(msg);
}
```

**Comment by sergeybykov** [comment]
This would require a write to the reminder table after a successful firing of the reminder because the semantics would be subtly different.

Today, if a reminder fails to fire for some reason, for example, if the cluster is down at the time the reminder is scheduled for, no attempt is made to fire it at a later point, and no tracking is performed via storage. The fallback here is that the reminder will fire again after the next period elapses. This provides eventual reliability and put the responsibility of stopping the reminder explicitly on the application.

With a one-shot reminder, we would have to record it in the table differently, and automatically remove it after a successful firing. The reminder service would have to have a logic to retry the reminder upon a failure to deliver it. What should be the retry period? Should it exponentially increase? Should the service eventually give up in case of consistent failures to deliver?

With all these considerations, it looks more and more like a different feature, not a variation of the reminder behavior. While it is, of course, doable, I think the effort like this is not worth it when the same effect can be achieved with a single line of application code that would unregister reminder upon successful completion of the operation.
