### ISSUE TITLE
Security scan of orleans

### ISSUE THREAD

**Issue by tsibelman** [dotnet/orleans#2463]
I encountered this service build by Coverty to opensource community https://scan.coverity.com
It scans your code for known vulnerabilities and give a detailed report of issue. 

What do you think about starting this process for Orleans ?

**Comment by veikkoeeva** [comment]
I'm greatly in favour of all activity like this. In the current climate, which seem to tighten still, this would signal clearly a mature approach.

**Comment by sergeybykov** [comment]
I don't see right away how they handle false positives.

**Comment by tsibelman** [comment]
@sergeybykov can you elobarate,  what do you mean ?  I understand that they going to have some degree of false positives during analysis, but what are you looking for exactly are you looking for a way to mark such issuese as not real issues ?

**Comment by veikkoeeva** [comment]
I'll provide a bit more details, currently in the project I am in, we take Nuget packages offline and do some checks already. This is not the only project and customers are wondering aloud how much of an impediment would it be to require some sort of an analysis report or assurance security issues have been considered. I'm not exactly sure of the exact reason for this, but at least in Europe [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) is coming and could result in hefty fines (maybe even someone going to jail) if there's a breach due to neglicence.

Maybe this is the reason there has reasonably been interest to create Roslyn analyzers and other tools to provide quick security analysis.

**Comment by sergeybykov** [comment]
@tsibelman When @centur run static analysis with PVS-Studio, there was a certain level of noise in the results - http://shcherbak.me/post/139216516264/checking-microsoft-orleans-with-pvs-studio-for-fun. That's why I wonder 1) how much noise Coverity will produce, and 2) if there are ways to mark false positives for exclusion, so that the report will not scream "56 security issues!" when there are actually zero. For managed code the signal-to-noise ratio is often not great.

I guess we can try and see how useful and flexible the report is.

@veikkoeeva By quickly glancing at GDPR, isn't it about data protection and privacy?

**Comment by veikkoeeva** [comment]
@sergeybykov It is. It mandates breaches should be reported and fines are hefty and someone might be held accountable. Part of the strategy to prevent breaches is to use pathed software, patched libraries. Which results in making sure libraries are appropriately patched and that is checked somehow so it looks good one isn't resting on the laurels. I'm likely stating the obvious here, but I want to be sure and perhaps this is useful for future readers. :)

**Comment by sergeybykov** [comment]
I produced a build and submitted it (140 MB!) for analysis. We'll see what it says.

**Comment by sergeybykov** [comment]
It says "197 Outstanding Defects" but doesn't show them to me until they verify the project ownership.

**Comment by tsibelman** [comment]
Very interesting

**Comment by sergeybykov** [comment]
I suspect those "defects" are nearly all false positives. That's why that was my first question.

**Comment by tsibelman** [comment]
Sergey I found your project on their site would appreciate if you approve me to take a look there.

**Comment by sergeybykov** [comment]
@tsibelman I gave you access. Looks like a lot of noise there. There must be a way to at least exclude /test/*, but I didn't see an option right away.

**Comment by tsibelman** [comment]
Thanks I will check it out

**Comment by tsibelman** [comment]
@sergeybykov looks like they have ability to mark issues as false positive, I marked all from the test folder as such.   Also I assigned 3 small issues that looks like bugs on you.

**Comment by sergeybykov** [comment]
I see 115 reported issues, and a few I looked at appear bogus.

**Comment by sergeybykov** [comment]
@tsibelman I fixed the 3 bugs you assigned to me in #2639. Thanks!

I just submitted 1.4.0-beta build for analysis.

**Comment by tsibelman** [comment]
Nice, I could add pull request for some of the issues there but I need to know your opinion about different classes of issues they found do we want to fix them or not, for example I see they do not recommend using double lock probably because of the reasons found here http://csharpindepth.com/Articles/General/Singleton.aspx#dcl

**Comment by sergeybykov** [comment]
Looks like https://scan.coverity.com/ is gone and redirects to https://brb.synopsys.com/ which says:
>This service is temporarily unavailable.
Please try again later. We apologize for any inconvenience.

**Comment by sergeybykov** [comment]
I'll close this issue because nobody has been looking into this for a long time. Can reopen when somebody has time.
