### ISSUE TITLE
Fire and forget long running actor method

### ISSUE THREAD

**Issue by MishaUliutin** [dotnet/orleans#2504]
Let's assume we have actor Test which has method Start. In method Start actor should make up to 20 consecutive http requests and every request could take up to 2 sec. Final result is not matter for client, which calls Start method of actor test, so basically main responsibility for client is activate actor and start it and ideally method Start of Test actor should run some background task and immediately returns to client. Reminders looks overkill for this and Timers does not prevent actor deactivation, so what is best practices for such task?

**Comment by jason-bragg** [comment]
I'll restate to verify that I understand the desired scenario.

You want a client to kick off some sort of action on the cluster, but the client does not care about the results, so it does not need to wait for action to complete.
The action you want to kick off is the generation of 20 consecutive http calls, each of which can take up to 2 seconds.

If that is correct, you should be able to spin off another task in the grain and simply return from the grain call.  Something like:

    public interface ITestRunnerGrain : IGrainWithIntegerKey
    {
        Task StartTest();
    }

    public class TestRunnerGrain : Grain, ITestRunnerGrain 
    {
        public Task StartTest()
        {
            StartTestInternal().Ignore();
            return TaskDone.Done;
        }

        private async Task StartTestInternal()
        {
            for(int i=0; i<10; i++)
            {
                await HttpCall();
            }
        }
    }

**Comment by MishaUliutin** [comment]
> I'll restate to verify that I understand the desired scenario.

> You want a client to kick off some sort of action on the cluster, but the client does not care about the results, so it does not need to wait for action to complete.

yes, you are correct

> If that is correct, you should be able to spin off another task in the grain and simply return from the grain call. Something like:

hmm, probably I misunderstood something, but I was under impression that Orleans Runtime deactivates Actor when all messages have been processed and there is no message in the Actor queue and there is nothing in your code which can prevent Actor from deactivation.

**Comment by gabikliot** [comment]
For that scenario we have an option for a grain to ask to delay it's deactivation.

**Comment by jason-bragg** [comment]
As @gabikliot stated, one can delay deactivation, but I didn't think deactivation would be an issue in this case.  Deactivation does not occur immediately after all messages are processed.  Grains waits a period of time before deactivating, known as the collection age.

The default is 2 hours, but is configurable by setting the collection age limit.
ClusterConfiguration.Globals.Application.SetDefaultCollectionAgeLimit or for per grain type limits
ClusterConfiguration.Globals.Application.SetCollectionAgeLimit.

The system will deactivate the grain after the grain has received no grain calls for the collection age limit.  So by default it will wait 2 hours after the start call before shutting down the grain, well past the expected 40 seconds necessary to perform the operation.

If you've a strong concern about the grain shutting itself down, you can expose the web calls as part of the grain interface and have the grain call itself, but this is less performant.  Since each web call is performed as a grain call, the grain will always have messages to process until all of the web calls are complete.  Something like the below:

    public interface ITestRunnerGrain : IGrainWithIntegerKey
    {
        Task StartTest(int count);
        Task HttpCall(int callId, int max);
    }

    public class TestRunnerGrain : Grain, ITestRunnerGrain 
    {
        public Task StartTest(int count)
        {
            CallNext(0,count);
            return TaskDone.Done;
        }

        private async Task HttpCall(int callId, int max)
        {
            await HttpCall();
            callId++;
            CallNext(callId,count);
        }

        private void CallNext(int callId, int max)
        {
            if(callId < max)
            {
                GrainFactory.GetGrain<ITestRunnerGrain>(GetPrimaryKeyLong()).HttpCall(callId,max).Ignore();
            }
        }
    }

* I stress, this should not be necessary with even a 5 minute collection age.
