### ISSUE TITLE
Client is choosing "auto-assigned" network adapter

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#2538]
On machines that have network adapters used for different things (VPN, pcap, phone emulators) the `GrainClient` is sometimes grabbing a network adapter that is on the "auto-assigned" APIPA address 169.254.x.x

I would prefer to not have to specify the adapter I want in order to prevent this from happening.
At first glance it appears similar to #1243 and #1244.

**Comment by veikkoeeva** [comment]
Also the same as https://github.com/dotnet/orleans/issues/2054 and also https://github.com/dotnet/orleans/issues/1136 (constains further links).

**Comment by sergeybykov** [comment]
If we allowed to specify a subnet like we do for silos, would that solve the problem?

**Comment by amccool** [comment]
While part of me would rather have something that "just doesn't use the APIPA address" I don't know if that is even feasible.   Specifying the subnet is probably the correct answer, and at least provides for "configuration" solution.

**Comment by galvesribeiro** [comment]
It goes more than just that... It is a problem that we were discussing last year regarding allowing multiple NICs on the silo. 

Today the very same problem happen if (for example) you run a silo on your machine and you have a VPN on your machine configured... It may or may not (totally random) bind the socket to the VPN's virtual NIC IP, which ofc leads to clients (which looked up on membership table the wrong IP from the VPN network) being unable to connect to the silo.

We had some ideas in the past on how to handle this but IIRC that requires a lot of changes on how we address entities in Orleans (i.e. activations and Silo Identity) and since it wasn't a priority by that time, we moved away...

This affect multiple scenarios not just VPN or APIPA addresses...

**Comment by sergeybykov** [comment]
On the silo side we support the Subnet parameter. Doesn't is solve the problem? My understanding is that the issue here is that there is no such setting on the client side. Am I wrong?

**Comment by veikkoeeva** [comment]
@galvesribeiro Having static routes on the virtual switch also leads to similar problems.

**Comment by galvesribeiro** [comment]
I'm not aware of the subnet parameter but if this filter out the other networks it should fix the problem @amccool is facing. However, I should still advise that other problems still happen like I suggested and the static routes one from @veikkoeeva

**Comment by sergeybykov** [comment]
https://github.com/dotnet/orleans/blob/master/src/Orleans/Configuration/GlobalConfiguration.cs#L133 is where `Subnet` is defined.  
>However, I should still advise that other problems still happen like I suggested and the static routes one from @veikkoeeva

Is `Subnet` a sufficient/good solution for that if we add similar functionality to client config and logic?

**Comment by sergeybykov** [comment]
If adding `Subnet` option to client config is all that needed here, then we already have https://github.com/dotnet/orleans/issues/2062 open for that.

**Comment by amccool** [comment]
#2062 is good enough, close this.
