### ISSUE TITLE
AzureSilo Config TableName

### ISSUE THREAD

**Issue by mauriciomagni** [dotnet/orleans#2544]
Hello
In AzureSilo's Config it is possible to configure TableName (by default OrleansGrainState). I was expecting to be able to configure TableName in AzureClient; I could no find how to set that value.
Even changing TableName in the AzureSilo the AzureClient kept working, this raised a couple of questions:
1. How does AzureClient know about AzureSilos?
2. Having multiple silos (with different grains each), should I use different GrainState tables or just one is good enough?
Thank you

**Comment by sergeybykov** [comment]
There seems to be some confusion here. Grain state isn't visible or accessible to clients. So the `TableName` setting, when it comes to grain state, makes sense only on the silo side.

The cluster membership protocol, on the other hand, is what, among other things, allows clients to discover silos to connect to them. That's kind of the answer to your first question.

>2. Having multiple silos (with different grains each), should I use different GrainState tables or just one is good enough?

All silo use the same configuration because grains are not permanently affiliated with any silo, and only get activated on a particular silo for some time. Hence, all silos need to write and read grain state to/from the same storage, table-based or nor.

**Comment by mauriciomagni** [comment]
Quite clear! very thank you @sergeybykov
