### ISSUE TITLE
Persistent Streams Question: How to begin a implementation?

### ISSUE THREAD

**Issue by marianogenovese** [dotnet/orleans#2548]
This is not an issue. I need info/guidance/advices to try to implement Orleans Streams with Redis as Storage.

My idea is oriented to use the lists of redis as queues (persistence mechanism) and over the lists create streams in orleans (providers of streams / hub of events?) the events that are written in redis are distributed to N subscribers I am also interested in the recovery of streams and also that can be rewindable.

Producers may be external (just doing a lpush in a Redis List) but they may also be other Orleans grains.

Navigating between the issues I found the following information:
Issue #1304  :
Ephemeral in memory streams - SMS Stream Provider.
Persistent Non recoverable streams - Azure Queue Stream Provider.
Persistent recoverable streams - Event Hub Stream Provider (in development - incomplete)

I think the closest thing to what I need is Event Hub Stream Provider.

Also i found this: https://github.com/jamescarter-le/OrleansEventStoreProvider this implementation is a good source of example?

Another interesting issue: #2421 

Any ideas/advices/guidance?

cc: @jason-bragg

**Comment by sergeybykov** [comment]
The key question to determine if the provider should be based on the Azure Queue provider or the EventHub one is whether or not you want/can make it rewindable. That is if stream consumers will be able to subscribe and resume consumption from specific offsets of the streams like the EventHub provider does.

**Comment by marianogenovese** [comment]
In my case, the consumers make a linq query over orlenas streams. This linq query can be over a non rewindable stream or run over a rewindable stream (the consumer will use a date token to indicate where to start). I think the best is EventHub.

**Comment by sergeybykov** [comment]
The rewindable case is more flexible, but also more complex. For example, you likely don't want the Redis lists to grow indefinitely. This will require some cleanup process that would trim old events from them. The EventHub services does that automatically, and keeps only a limited time window of events available (by default last 24 hours). Does Redis have anything built-in like that?

I'm also not sure how Linq will integrate with async, Task-based, streaming APIs. You'll need to make sure you don't block threads there.

**Comment by marianogenovese** [comment]
About the window of events, yes there is a limitation because redis dont have anything built-in, some external monitor grain to make a cleanup is needed.

**Comment by sergeybykov** [comment]
It would be more logical to make it part of the stream provider logic, so that it does not depend on a piece of the application.

**Comment by marianogenovese** [comment]
I agree with you, there is something about recovery capability? Is there something I should think about?

**Comment by sergeybykov** [comment]
In theory, the recovery logic should be already encapsulated in the pulling agent logic, and the adapter should not worry about it. I wonder if @jason-bragg has more thoughts on this.

**Comment by jason-bragg** [comment]
@marianogenovese

Your question seems to indicate that you've read up a bit on the state of Orleans streaming, though there is always work on-going so some of the information you've read may be out of date.  The EventHubStream provider, for instance, has been released and is being used in production environments, so you could model off of it for a recoverable stream provider.  Additionally, we've added another ephemeral stream provider the MemoryStreamProvider which, like the EventHubStreamProvider, is a recoverable stream provider but keeps the events in memory, as it's mainly for development use.  While the MemoryStreamProvider is an ephemeral stream provider (as the data is queued up in memory) it is simpler than the EventHubStreamProvider so it may be a better candidate to model off of.

As you are probably aware by this point, the streaming infrastructure is complex but quite useful if your requirements fit what the system was intended to do, but due to the complexity, it may be simpler to build your own solution if your scenario deviates significantly.

If you need ordered reliable streams, your backend repository (redis) will need to be ordered and reliable, and you should be aware that the stream provider built for this type of stream (PersistentStreamProvider) only supports recoverability for transient errors (failures that last for short periods of time, <~5 minutes..).  There is a fair amount of flexibility here, but the main point is that the existing recoverability does not support unbounded rewinding.

I suggest that you look closely at your requirements and contrast them with the features of the persistent stream provider.  If they fit well then all you should need to do is write an adapter for redis.  However, If the features don't line up well, then custom logic to deal with redis queues combined with one of the ephemeral stream providers may be more practical.

**Comment by marianogenovese** [comment]
@jason-bragg Thanks for your comments. To be more precise in the questions that I will ask in the future, there is some sample implementation that I can review and use EventHubStreamProvider?

**Comment by jason-bragg** [comment]
I don't know of any sample code using EventHubStreamProvider.  The best we have at this point are our test harnesses.

EHImplicitSubscriptionStreamRecoveryTests cover some common recoverability scenarios.  We simulate transient and non-transient stream processing errors.

In the transient error test, in the ImplicitSubscription_TransientError_RecoverableStream_CollectorGrain, faults are injected at several points in the event processing:
At the initial grain activation.
At the first event, before it is processed.
At the first event, after it is processed.
At the 33rd event, after it is processed.
At the last event, before results are written.

In the non-transient error test, the ImplicitSubscription_NonTransientError_RecoverableStream_CollectorGrain injects faults (after the 32nd event) until recovery fails and a streaming error is reported to the grain (via the OnErrorAsync), then the rest of the stream is processed without issue.  This test simulates a "poison message" scenario.

EHClientStreamTests tests streaming from the Orleans client against the EventHubStreamProvider.

EHSubscriptionMultiplicityTests tests stream subscription management.

All of these tests deal with the user  stream providers and the behaviors tested 'should' be uniform across all stream providers, so you should see similar test cases for other stream providers.  For instance, the recoverability test is also run against a GeneratorStreamProvider , (GeneratedImplicitSubscriptionStreamRecoveryTests) which is a stream provider intended to allow users to deterministically generate event streams for stream processing testing.

**Comment by marianogenovese** [comment]
Thanks @jason-bragg, another question to follow with my custom implementation of EventHubStreamProvider is some example of this type of provider with a queue system. I mean, i need to see where and what i need to implement a custom EventHubStreamProvider with Redis for example. With a PersistentStreamProvider there are many examples like https://github.com/jamescarter-le/OrleansEventStoreProvider and even i have implemented a custom PersistentStreamProvider (basic but works to understand how orleans streams works and to analyze if streams are my choice to follow) with Redis as backend but with EventHubStreamProvider i see there is no doc yet or even a example. I need to figure it out what to do to implement my provider there some code in orleans repo to review?

**Comment by jason-bragg** [comment]
I suspect there may be a misunderstanding here.

You mentioned seeing various examples of custom PersistentStreamProviders, but not similar examples for custom EventHubStreamProviders.  The PersistentStreamProvider is the general provider infrastructure for any stream provider that is backed by an external persistent queue.  EventHub, Azure queues, EventStore, Redis, ...  The EventHubStream provider _**is**_ a PersistentStreamProvider, along with all of the rest.  To implement your own persistent stream provider one must develop a custom queue adapter, as all of the others (and EventHubStreamProvider) have done.  The EventHubStreamProvider is just another example one can model off of.

I was not suggesting customizing the EventHubStreamProvider. but modeling off of it (or the MemoryStreamProvider) as those providers use a pooled message cache which allow for recoverability.

If you'd like to see an example of customization of the EventHubStreamProvider (as it is customizable), you can look at the StreamPerPartitionEventHubStreamProvider used in EHStreamPerPartitionTests.  This stream provider customizes how events from event hub are associated with a stream, creating as single stream per event hub partition.  It's not the most advanced scenario, and will not likely address your needs but it is useful for exploring some of the customizable aspects of the EventHubAdapter.  The EventHubAdapter _**does not**_ support reading from different queue types.  It is fundamentally designed to read from EventHub.

> I have implemented a custom PersistentStreamProvider

Then your already on the way.  Maybe we can start there.  This means you've written some sort of custom queue adapter for Redis, and defined a stream provider that uses that adapter, correct?  What is insufficient about this initial implementation?

**Comment by marianogenovese** [comment]
Oh I see what you are trying to explain to me, so could you tell me what the characteristics of an EventHubStreamProvider are? Implementing a PersistentStreamProvider has made me understand the operation a bit, for example streams that can be rewindable (via tokens) but I would like to understand the scenario of recovery of streams, what are the differences between an EventHubStreamProvider and a PersistentStreamProvider I understand that they share some since a EventHubStreamProvider inherits from PersistentStreamProvider.

**Comment by jason-bragg** [comment]
I'll start with some details about how persistent stream providers work.  This is general and I'm leaving out many details.. but for the most part:

The persistent stream provider reads events from a data store (EventHub, azure queue, ..?) using an IQueueAdapterReceiver provided by an implementation of IQueueAdapter specific to the data store.

Events are stored in an implementation of IQueueCache (also provided by the queue adapter).  The persistent stream provider (PersistentStreamPullingAgent) delivers events from the cache to stream consumers.  The implementation of the cache determines how long messages are available for delivery for recovery purposes.  The persistent stream provider and related infrastructure currently includes two types of caches.  A simple cache which supports caching until the events are delivered at least once to all consumers, and a pooled cache which supports transient error recovery limited only by the size of the cache; the bigger the cache the longer the recovery time.

Now I'll go into the EventHub and Memory stream providers.  Both of these providers are considered recoverable stream providers because they both use the pooled cache, which supports a longer recovery window.  The EventHub stream provider can be configured to support hundreds of megs or even gigs of messages, allowing a longer recovery window.  Some production services we run on this tech have caches that store 30 minutes of data.  In these environments any outage that recovers in under 30 minutes can be recovered from automatically.

This is different from the Azure Queue stream provider, which uses the simple cache.  For this provider, as soon as events are delivered to all of the consumers they can be purged from the cache, so if there is an outage and the grain needs to rewind the stream to a previous point to reprocess lost results, the data is not there and the operation will fail.

So what does this mean for you...?
You'll probably need to implement a custom IQueueAdapter that provides an IQueueAdapterReciever that can read from redis.
You'll probably need to implement an IQueueCache using the pooled cache. for recovery reasons.  I'd suggest modeling off the one in the MemoryStreamProvider first, then looking at the one in the EventHubStreamProvider for more advanced features like backpressure and checkpointing, as the cache in the memory stream provider is simpler and clearer for a new users.  You can also write your own custom implementation of IQueueCache if you're not fond of the pooled cache or simple cache.

Once you've something you think works you can use the ImplicitSubscritionRecoverableStreamTestRunner used in EHImplicitSubscriptionStreamRecoveryTests to run the recovery scenarios against your shiny new redis stream provider.

**Comment by marianogenovese** [comment]
@jason-bragg thanks again, i have a clear picture now. EventHubStreamProvider is based on your systems needs and on top of Azure Event Hub caracteristics. I have another question, the instances of IQueueAdapter, IQueueAdapterReciever, IQueueCache where they reside? I mean on the producer side I guess IQueueAdapterReciever resides, on the consumer side maybe IQueueAdapter and IQueueCache. This question is based on a premise: what if a producer generate MB or GB of messages this not come to a memory overflow in some point? so what if i have a cache that read from a queue system like redis?

**Comment by jason-bragg** [comment]
On the producer side, the IQueueAdapter is used to write messages into the queue (QueueMessageBatchAsync).  The IQueueAdapterReciever and IQueueCache are not instantiated or used on the producer side.

On the consumer side, for the most part, the IQueueAdapter is not really used at all.  Consumers use the stream pub/sub system to subscribe to a stream and receive events packed in IBatchContainer(s).

Between the producer and consumer sides, pulling agents acquire an IQueueAdapterReciever and an IQueueCache from the IQueueAdapter, read messages from the IQueueAdapterReciever, add the messages to the IQueueCache, and deliver messages from the cache to the consumers (according to subscription information from the pub/sub system) in the form of IBatchContainer(s).

There is a pulling agent (and hence a receiver and cache) per queue reported by the IStreamQueueMapper.  These queues are load balanced across the cluster.  In EventHub there is a queue per event hub partition, so if your hub has 16 partitions, and your cluster has 4 silos, each silo will spin up 4 agents, reading and caching the messages from 4 event hub partitions, and sending those events to consumers subscribed to those streams.

So a messages flow through the system would look something like:
1) A message is produced on the producer side, and is written (via the IQueueAdapter.QueueMessageBatchAsync call) to storage immediately,
2) Agent reads message from storage (via the IQueueAdapterReciever) and places it into the message cache (IQueueCache)
3) Agent gets the subscription information for the stream the message is associated with from the pub/sub system and sets up message delivery for all subscribers to that stream.
4) Each consumer of a stream gets a cursor into the cache and messages are delivered to it from the cache until it unsubscribes.
5) The message is read from the cache via the cursor as an IBatchContainer and is delivered to each subscribed consumer.
6) On the consumer side, messages are read from the IBatchContainer and passed to consumers OnNextAsync call to be processed using application logic.

**Comment by jason-bragg** [comment]
@marianogenovese,  I don't mind providing information about the streaming infrastructure, as I hope one day to move a lot of this material to the docs, but given that redis is not really a queue storage service like azure queues, event hub, kafka, ... I remain skeptical whether the PersistentStreamProvider path is the right path for Redis.
You know your system, but the persistent stream infrastructure, as you've seen, is non-trivial.
When I think about how to stream data from Redis, I keep coming back to a simpler pattern of just spinning up producer grains that read a specific set of data from redis, then write that data as events onto any of the ephemeral stream providers.

**Comment by marianogenovese** [comment]
How to deal with a case when a new consumer wants to consume from old events (name it: back in time) to new events (real time) with a custom datetime token (replaying from a specific date/time and continue receiving events from the stream) and in the cache dont have all this old events but in remains in the storage system how to recover this events from the storage system when the consumers use the same cache?

**Comment by jason-bragg** [comment]
> "the cache dont have all this old events but this old events remains in the storage system"

The current infrastructure does not support this behavior.  As is, the code will only allow consumers to request older data while it's still in the cache.  The requirements of the current systems were derived from the need to recover from transient errors.

One may be able to support this behavior with a custom IQueueCache.  Since redis is already a cache, it may be possible to implement an IQueueCache that, rather than caching messages obtained from the receiver, instead uses data directly from the redis cache.
