### ISSUE TITLE
is StatelessWorker single-thread  necessary?

### ISSUE THREAD

**Issue by weitaolee** [dotnet/orleans#258]
StatelessWorker Grain may have many activations. if one client and 10 silo. Message processing is not in order.    
     Do ,why make  StatelessWorker Grain  single-thread? if not single-thread, will improve throughput.    
     Imagine why? 
     Do you want to control the maximum request count in one StatelessWorker grain? like the example code TweetDispatcherGrain,  HashtagGrain which is a  common grain  could do this. Doesn't need   TweetDispatcherGrain controls the maximum amount of request.    
     Please consider giving a new implementation for StatelessWorker Grain. if something wrong ,please correct me.

```csharp
[StatelessWorker]
public class TransferTransactionProcessManager : Orleans.Grain, ITransferTransactionProcessManager
 { 
        private int counter = 0;
        async Task ITransferTransactionProcessManager.ProcessTransferTransaction(Guid fromAccountId, Guid toAccountId, decimal amount)
        {
            counter += 1;
            Console.WriteLine("<---------------------before delay" + counter + "----------------------------------->");
            var tcs = new TaskCompletionSource<int>();

            Task.Delay(5 * 1000).ContinueWith((t) =>
            {
                Console.WriteLine("<---------------------------delay"+counter+"----------------------------------->");
                tcs.SetResult(1);
            });
            await tcs.Task;
            return;
         }
}
```
console 
```
<---------------------before delay1----------------------------------->
<---------------------------delay1----------------------------------->
<---------------------before delay2----------------------------------->
<---------------------------delay2----------------------------------->
<---------------------before delay3----------------------------------->
<---------------------------delay3----------------------------------->
```

**Comment by sergeybykov** [comment]
The main reason for the single-threaded execution of grain activations is to prevent concurrency issues and a need for thread synchronization in the grain code. A StatelessWorker grain may have private data structures that in general would have to be protected with locks in case of a multi-threaded execution. So the thought is that having multiple single-threaded activations is safer than a single multi-threaded activation.

**Comment by weitaolee** [comment]
if I have two choices    
A : make concurrency safe by myself,and get better throughput     
B : make concurrency safe by single-threaded execution of grain.

I perfer A much more than B.

**Comment by sergeybykov** [comment]
If a grain becomes such a bottleneck that it makes you consider making it multi-threaded, I would take a harder look at the decomposition of the app logic. The grain model assumes that grains are small enough pieces of state and logic that none of them individually requires a lot of resources. Such an approach has its limits, of course, but in our opinion it helps scalability a great deal.

Leveraging thread synchronization mechanisms from within grain code can easily reduce throughput or block execution altogether by preventing other grains from running. If you believe you have a need for such a multi-threaded high throughput component, I would suggest to consider putting it outside Orleans.

**Comment by weitaolee** [comment]
I only looking for a way to improve StatelessWorker grain. not have a specific app logic.

    of course, but in our opinion it helps scalability a great deal.    

I agree with you about this. 

maybe I use [StatelessWorker] and    [Reentrant],so when [await tcs.Task;] , grain should proccess the next request, maybe I change code like this 
```csharp
[StatelessWorker]
    [Reentrant]
    public class TransferTransactionProcessManager : Orleans.Grain, ITransferTransactionProcessManager, IRemindable
    { 
        async Task ITransferTransactionProcessManager.ProcessTransferTransaction(Guid fromAccountId, Guid toAccountId, decimal amount)
        { 
            Console.WriteLine("<---------------------before delay ----------------------------------->");
            var tcs = new TaskCompletionSource<int>();

            Task.Delay(5 * 1000).ContinueWith((t) =>
            {
                Console.WriteLine("<---------------------------delay----------------------------------->");
                tcs.SetResult(1);
            });
            await tcs.Task;
            return;
    }
}
```

it should console ,but no.  maybe Reentrant can improve for this?
```
<---------------------before delay ----------------------------------->
<---------------------before delay ----------------------------------->
<---------------------before delay ----------------------------------->
<---------------------------delay----------------------------------->
<---------------------------delay----------------------------------->
<---------------------------delay----------------------------------->
```

**Comment by gabikliot** [comment]
You have lots of alternatives: 
1) use a set of StatelessWorker grains and round robin between them. 
2) use Thread Pool for concurrency (Task.Run) and manage locking yourself.
3) Consider re-design, as Sergey suggested.

Actors are single threaded, by definition. I doubt we will consider changing such a fundamental guarantee of our programming model.

**Comment by alan-geller** [comment]
A subtle reason for keeping actors single-threaded is that it lets the Orleans scheduler make some simpli8fying assumptions about processor usage that allow it to run very efficiently in most situations. By default, Orleans allocates a worker thread per logical core, and runs a single actor per worker thread. There’s no preemption; it’s cooperative multiprocessing.

Because the number of threads matches the number of logical cores, in general the threads don’t block and there are no thread context switches. This isn’t quite true because of threads used for messaging and other IO, but the number of thread switches per minute on Orleans is much, much lower than is common on more highly multi-threaded platforms. In particular, the number of context switches per minute doesn’t go up when system load increases.

All of this lets Orleans run smoothly at over 90% CPU usage, where (in my experience) typical rule of thumb is to limit servers to no more than 80% usage because otherwise context switch (and other kernel) overhead will bring things to a screeching halt…

Doing a bunch of multithreaded computation within a grain will break this assumption and likely make the silo as a whole perform worse. If you split the computation out of the grain and run it in a logically separate compartment that you make asynch requests to, as if it were an IO service, then you can play with the Orleans config to tell the Orleans scheduler to use fewer worker threads; this will let the silo run smoothly on one set of cores while the computation runs using its own separate set.

**Comment by weitaolee** [comment]
Thanks for correct me. I have a wrong understand about grain single-thread.
