### ISSUE TITLE
Stream batching APIs are not fully implemented

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2685]
Currently `OnNextBatchAsync` creates a single message for all events passed in `OnNextBatchAsync` which may lead to Azure Queue message size limit of 64KB to be breached. Is it by design to create a single message per batch or can we detect the size of the resulting message in Azure Queue stream provider and split into multiple messages accordingly?

**Comment by sergeybykov** [comment]
It is by design. Re-batching at the provider level seems possible. Although I'm not sure if there could be implications. Wonder what @jason-bragg thinks.

**Comment by jason-bragg** [comment]
Some context on this issue can be found in a previous attempt to address it in "Support messages over the max CloudQueueMessage size #2582 "

>Is it by design to create a single message per batch or can we detect the size of the resulting message in Azure Queue stream provider and split into multiple messages accordingly?

It is by design.  We've considered handling large messages using PersistentStreamProviders and have concluded that doing so in a general (or even specific) way is non-trivial.  My preference would be for the stream provider infrastructure to be constrained to the limits of the underlying persistent queuing system.  This is 64kb message for azure queues.

There are (at least) a couple different approaches that do not involve solving this within the PersistentStreamProviders:
*  Multi-part messages - A large message can be broken into smaller pieces on the producer side, sent, and reassembled on the consumer side.  This is similar to #2582.  This multi-part messaging can be done at the application layer or as a stream provider decorator over any existing stream provider.
*  Externally persisted message -A large message can be persisted to external storage (azure blob for instance) on the producer side, identifying information can be sent over the stream, and the large message can be read from the external storage on the consumer side.  This can be done at the application layer or as a stream provider decorator over any existing stream provider.

**Comment by DixonDs** [comment]
@jason-bragg I am aware of the related discussion, but I think here the case is a bit different here. If you split a big batch into smaller batches on the producer side, you don't have to reassemble the original message on the consumer side, thus there should be no additional failure cases to worry about.

**Comment by jason-bragg** [comment]
@DixonDs,
I apologize for the delayed response.  I see your point.  You're not suggesting breaking up a single event that is too big, but rather breaking a single batch of events into multiple batches.

I think this is reasonable, but should probably be a configurable switch, as I can easily envision an application batching a set of messages that it expects to receive and process together.

The stream batching api's have been grossly neglected, and there are a number of problems with those apis.  Earlier in the evolution of streams I'd advocated removing them until we had an opportunity to think through the pattern and implement batching correctly.  This remains my position.

For this problem (ignoring my preference to remove batching entirely until we can think through the pattern), I am still of the opinion that this would be best implemented as a stream provider decorator, rather than within the stream providers themselves.  The reason for this is that a single solution would address this issue in all stream providers, and it would not change the serialization patterns of the existing stream providers, which would break backwards compatibility.
