### ISSUE TITLE
Using a grain to continuously spawn other grains indefinitely

### ISSUE THREAD

**Issue by lwansbrough** [dotnet/orleans#2765]
We have a limited number of "data factory" grains (less than 10) that are in charge of collecting information from an external process (a queue) and creating new grains based on the gathered information. The activation and subsequent method calls on these new grains tend to take time, so we don't want to wait for the new grain invocations to complete before moving onto the next grain creation. These grains we're creating handle their own failures internally, so there's really no information that the data factory needs from the grain once it's been invoked.

The queue we pull from is periodically refilled: when we call the external process it'll check if there is any items in the queue, if not, it'll go and find some. This fetching process is usually measured in hundreds of milliseconds or seconds.

Our grain code for the data factories looks like this (stripped down for clarity):

```c#
[Reentrant]
public class ContinuousDataFactoryGrain : IContinuousDataFactoryGrain
{
    private bool isRunning = false;

    public async Task Resume()
    {
        if (isRunning) return;

        isRunning = true;

        var externalProcessGrain = GrainFactory.GetGrain<IExternalProcessGrain>("someSpecificIdentity");

        while (isRunning)
        {
            var externalDataId = await externalProcessGrain.GetNextId();
            var someGrain = GrainFactory.GetGrain<ISomeGrain>(externalDataId);
#pragma warning disable CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
            someGrain.DoWorkThatTakesAWhile();
#pragma warning restore CS4014 // Because this call is not awaited, execution of the current method continues before the call is completed
        }
    }

    public Task Pause()
    {
        isRunning = false;
        return TaskDone.Done;
    }
}
```

As you can see, we mark the grain as re-entrant to allow for pausing the execution of the while loop. We *do not* wait on `someGrain`'s process because it can take a while and we have hundreds or thousands of `externalDataId`s to process per second.

In the event of a silo failure, the current "next ID" for the `ExternalProcessGrain` is persisted, so deactivating and reactivating the `ContinuousDataFactoryGrain` would result in it picking up from where it left off (approximately.) Please note that eventually we don't have control over the flow of the data that is entering our system. That means we can't receive a sort of "push" event from the process that's creating the data; we're polling for the data from an HTTP resource.

My question is: Is there a better way to do this in Orleans? I'm curious if Orleans will have a problem with a grain method that runs "forever."

**Comment by sergeybykov** [comment]
First, a couple of questions.

1. Do you really need `ContinuousDataFactoryGrain` to be the middleman between `IExternalProcessGrain`s and `ISomeGrain`s? Wouldn't it be more scalable to have the `IExternalProcessGrain`s` fetch next IDs and invoke `ISomeGrain`s with those IDs on their own (for example, with a frequent timer) instead of having the `ContinuousDataFactoryGrain` acting as a bridge between them? Seems like a more scalable pattern if hey talked directly and independently from `ContinuousDataFactoryGrain` after maybe an initial kick.

2. Do you really not care if `DoWorkThatTakesAWhile()` call fails? You don't necessarily have to await every single call independently. But you could still put the returned Task into a List/Dictionary and check for its completion or failure periodically, and report/log failures. `Task.WhenAny` is another option to consider for awaiting a bunch of `Task`s for a first one to complete/fail.

`ContinuousDataFactoryGrain` could be a good candidate for the newly introduce `GrainService` feature. With one (at the moment) instance of a grain service automatically created per silo, you can easily created an effectively partitioned factory service if you divide responsibility between the instances via consistent hashing. With each factory instance spawning respective `IExternalProcessGrain`s which in turn would spawn `ISomeGrain`s in the cluster, you should get good distribution and scalability, while reliability of the factories will be guaranteed via the `GrainService`. If you can avoid the factories from being middlemen between `IExternalProcessGrain`s and `ISomeGrain`s, then I presume the factories won't have much work to do, and one instance of them per silo should be more than enough.

>We do not wait on someGrain's process because it can take a while and we have hundreds or thousands of externalDataIds to process per second.

If you need to process 100Ks of IDs per second, I suspect you'll need a sizable cluster, unless those IDs can be batched and batch-processed (to cut the messaging cost). Do you already have an idea of the cluster size you need for such throughput?

Did I misunderstand something in the requirements?

**Comment by mauriciomagni** [comment]
Hello @sergeybykov 
In the sample exposed by @lwansbrough there is a not awaited call:
<someGrain.DoWorkThatTakesAWhile();>
My question is: does Orleans guarantee the execution of DoWorkThatTakesAWhile even if it is not awaited? My concern is based on that IIS does not guarantees the execution of not awaited requests.
In my case, I need to call and forget a task that could require some minutes to be executed; I am wondering if I need to setup a Worker Role instead of running this process in an Orleans grain.
Thank you,
Mauricio.

**Comment by sergeybykov** [comment]
>does Orleans guarantee the execution of DoWorkThatTakesAWhile even if it is not awaited? 

Yes, the method will start executing.

>In my case, I need to call and forget a task that could require some minutes to be executed; I am wondering if I need to setup a Worker Role instead of running this process in an Orleans grain.

You can do that. It is advised to call `.Ignore()` on the returned `Task` to explicitly indicate that failures should be ignored. Otherwise, they'll get logged.

**Comment by lwansbrough** [comment]
@sergeybykov 

1.) Good observation. I was thinking the same as I wrote out the question. It was implemented before the design for our system changed quite dramatically, and now as I look at it, its purpose is somewhat limited. There's definitely a possibility that it can be removed entirely as a middleman.

2.) I do care, however the process is internally retried within the grain several times (and finally logged in a failure queue if all tries fail.) I figured it's better to have a grain internally handling as much of its failures as possible to reduce the strain on that single ContinuousDataFactory grain, especially in a highly parallelized process like this. But perhaps I could implement something like `Task.WhenMost` (since most calls shouldn't take long at all) and then check if there are any errors in the completed tasks. If there are more than X% errors, wait for the rest to complete and take some action.

3.) The new grain service feature you mentioned certainly sounds interesting. Is there more documentation on that somewhere?

4.) Hundreds *or* thousands, not hundreds *of* thousands! Fortunately! Speaking of cluster size, we expect our throughput to be *very* similiar Halo 5's online services. Are details on that cluster's size publicly available?

**Comment by sergeybykov** [comment]
>3.) The new grain service feature you mentioned certainly sounds interesting. Is there more documentation on that somewhere?

Unfortunately, no docs yet. https://github.com/dotnet/orleans/tree/master/test/Tester/GrainServiceTests is an example. https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/ReminderService/LocalReminderService.cs is another one. A doc contribution would be greatly appreciated. :-)

>4.) Hundreds or thousands, not hundreds of thousands! Fortunately! Speaking of cluster size, we expect our throughput to be very similiar Halo 5's online services. Are details on that cluster's size publicly available?

Good. Sounds much easier now. :-)
No, we cannot share such details of Halo services, unfortunately.

**Comment by lwansbrough** [comment]
@sergeybykov Thanks for your help! I'll look into this.
