### ISSUE TITLE
Only the very first call to the grain behaves differently

### ISSUE THREAD

**Issue by AwsomeCode** [dotnet/orleans#2777]
If my call is not awaited only the very first call to grain behaves like Reentrant / message is not queued . Other call are like behave like normal.

Check out the below image in Silo CMD window first call is like  Reentrant or message is not queued. 

![image](https://cloud.githubusercontent.com/assets/11809653/23315454/4b78d032-faec-11e6-9762-697dc4a74e24.png)

**Comment by sergeybykov** [comment]
>behaves like Reentrant / message is not queued .

I'm not sure I understand what you meant here. I see that the first "I run2" gets printed before the first "I run1". Is that what you mean by the above statement? It is peculiar, but the order of execution isn't guaranteed in this case because the two calls are issued almost in parallel.

What happens I think is that the two calls trigger two racing activation processes for the grain. Only one of them wins the race, by design. The log message from Catalog mostly covered by the overlapping windows says: "Tried to create a duplicate activation X, but we'll use Y instead." Assuming that the order of console messages is correct (a dangerous assumption, to eliminate it, you need to have the grain log via `TraceLogger` instead of writing directly to console), the second call won the activation race, and that's why it got executed first.

So, the behavior I see is by design.

**Comment by AwsomeCode** [comment]
Sir. Thanks for the explanation. It is the race of the activation.
