### ISSUE TITLE
DI: allow ctors with parameters for Startup class

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2842]
It would be great to have similar experience to ASP.Net Core `IWebHostBuilder` which allows to specify configure some services before calling `Startup` like follows:
```
new WebHostBuilder()
	.ConfigureServices(
		services => services.AddSingleton(someContext))
	.UseStartup<Startup>()
```
then it allows to have `Startup` ctor with parameter `SomeContext someContext` which is injected before `Startup` is called.

In my particular scenario, I am trying to pass SF `StatelessServiceContext serviceContext` to Orleans `Startup`

**Comment by ReubenBond** [comment]
Hi @DixonDs, we're working on it and the Service Fabric use-case has typically been the one I've mentioned. You may have seen that the next release will include a new `ClientBuilder` which follows a similar pattern to ASP.NET

**Comment by jdom** [comment]
Yes, I'm currently playing with it a little bit here: https://github.com/jdom/Orleans.Hosting, but will come up with a more formal proposal really soon. Ideally we would support a very similar config/startup story as in ASP.NET Core, but in that prototype I was tinkering with stuff that it's not currently supported in ASP.NET Core, such as individually configured named providers (unless I missed an example of it, that's why I'd love some input, either now or after my proposal).

**Comment by jdom** [comment]
The upcoming generic host in `Microsoft.Extensions.Hosting` (only in pre-release form for now) will not support the Startup class natively, so we decided to align with that and not support it either. Nevertheless, what you wanted to accomplish should now be doable with `SiloHostBuilder` too.
