### ISSUE TITLE
Wrong nuget dependendcies for Microsoft.Orleans.OrleansServiceBus 1.3.1

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2887]
Currently it is open-ended like ` Microsoft.Orleans.OrleansRuntime (>= 1.3.1) `, but it seems that `Microsoft.Orleans.OrleansServiceBus` 1.3.1 cannot work with `Microsoft.Orleans.OrleansRuntime` 1.4.0 due to breaking changes to public API of `IQueueCacheCursor` introduced in https://github.com/dotnet/orleans/pull/2622

Ideally, according to semver such breaking changes can be introduced in major releases only. In this particular case, I would say to reupload `Microsoft.Orleans.OrleansServiceBus` 1.3.1 with corrected dependencies.

**Comment by sergeybykov** [comment]
In general, I think this is a fundamental issue with specifying versions of NuGet dependencies. We are trying to predict the future - whether or not a future version of a dependency package will be backward compatible. The only way I'm aware of that avoids this is to fix versions of dependencies (=1.3.1). I personally don't like that because it would cause additional friction for legitimate backward compatible upgrade cases.

When it comes to versioning of Orleans NuGets, we have more flexibility, and we could have those internal dependencies be of a fixed version. I don't see much benefit in doing that for two reasons.

1) Most (all?) our users today upgrade all Orleans packages together. We do not test permutations of versions to guarantee that a mix of versions will work. At the same time, we aren't preventing somebody from upgrading individual Orleans packages if needed.

2) In 2.0 we plan to move away from updating all Orleans packages in lockstep. For example, we want to have an assembly/package with just a small set of core interfaces that will rarely change. Also, we want to be able to publish individual updated packages when there are improvement and fixes in their code, regardless of changes to the rest of the codebase.

**Comment by DixonDs** [comment]
>The only way I'm aware of that avoids this is to fix versions of dependencies (=1.3.1).

Other way is to use [semver](http://semver.org/) as it is indented to be used. If you bump the major version every time you introduce breaking API changes, you can set dependencies to be up to the next major release i.e. [1.3.1, 2.0.0) in this case.

**Comment by sergeybykov** [comment]
Yes, we deviated from semver from the start because we knew we would have breaking changes with pretty much every release, and we would probably release 15.0.0 by now. So we use minor version in lieu of major, and in our case instead of [1.3.1, 2.0.0) it could be [1.3.1, 1.4.0). I still wonder how much real value it would add compared to what we do today.
