### ISSUE TITLE
Update to WindowsAzure.ServiceBus 4.0.0

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2910]
Any issues if OrleansServiceBus is updated for WindowsAzure.ServiceBus 4.0.0? If that's fine, I could prepare a PR, though it is as trivial as changing the dependency version.

**Comment by sergeybykov** [comment]
I wonder what @jason-bragg thinks.

**Comment by jason-bragg** [comment]
I'd intended to update to the latest 3.4.x release, but had not planned to move to 4.0 yet.  My preference is to lag behind a little when moving major releases.  Is there a need for 4.0?  If there is no immediate need I'd prefer to hold the move to 4.x until 4.1.x is out.

As far as the upgrade itself, the change tends to be trivial, but the testing can be a bit rough, as it requires setting up and configuring a hub.  It's further complicated by the fact that we've integrated with two versions of SB, one in main, and one in the 2.0 tree.  This is intended to be temporary, and we want to get back to a single version, but until we do, it can complicate an upgrade.

**Comment by DixonDs** [comment]
> Is there a need for 4.0?

The current OrleansServiceBus code is binary incompatible with 4.0.0, and since we had other internal package requiring >4.0.0 used in the same solution, it caused some issues.

**Comment by jason-bragg** [comment]
I touched base with some of our larger deployments and none are on 4.0 yet.  These deployments are awaiting changes in the 1.5 release, so we're not in a position to consider upgrading SB to 4.0 until after the 1.5 release.
You may need to run on a custom nuget for a time. :/

**Comment by sergeybykov** [comment]
Discussed with @jason-bragg this one more time. We think it would be better to upgrade the dependency to 4.0.0 in 1.5.0

**Comment by xiazen** [comment]
Hmmmmm I don't know how long upgrade to 4.0.0 itself would take, but according to @jason-bragg it is trivial. So I think it's just a matter of flip some fingers? 

As for testing , I think we can reuse our existing hub, since their server should be compatible with 4.0.0. If that's not the case somehow, my experience with configuring a hub is not bad. Unless I missed something, I don't think testing would be trivial. 

And for the 2.0 tree problem, it is really a question of should we delay this upgrade and wait for 2.0 or not. If upgrading is trivial, IMO we shouldn't wait.

So I agree with the team's decision, and I typed those because I was assigned and I feel like I should say something :D

**Comment by sergeybykov** [comment]
The rational for upgrading to 4.0 in 1.5.0 is so that we wouldn't block users of 1.5.0 from upgrading to 4.0, which presumably they'll want to do eventually/soon anyway. If somebody for some reason has to stay on 3.4 but wants to upgrade to 1.5.0, we could consider workarounds or releasing a special version of `Microsoft.Orleans.ServiceFabric` package. Hopefully, that won't be needed though.

**Comment by jdom** [comment]
PR in https://github.com/dotnet/orleans/pull/3127
