### ISSUE TITLE
Notifying Bootstrap Provider of Silo Shutdown

### ISSUE THREAD

**Issue by richorama** [dotnet/orleans#2967]
I have a bootstrap provider (the Orleans Dashboard) which requires notification of silo shutdown, as it needs to [gracefully terminate log streaming](https://github.com/OrleansContrib/OrleansDashboard/issues/43). 

* The `Close` method on the bootstrap provider does not seem to get called.
* Creating an instance of a `ISiloStatusListener` and registering it with an instance of `IMembershipOracle` does not seem to work either (methods don't get called).

```cs
var oracle = providerRuntime.ServiceProvider.GetService(typeof(IMembershipOracle)) as IMembershipOracle;
oracle.SubscribeToSiloStatusEvents(this);
```

I understand that the bootstrap provider was initially intended for registering startup code, but I've seen a few examples of people using (abusing) it for longer running tasks. It would be nice to shut these down gracefully.

**Comment by benjaminpetit** [comment]
The `BootstrapProviderManager` should already call `Close()` on all registered provider.

See https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/Silo.cs#L895-L899 and https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Core/BootstrapProviderManager.cs#L38-L46

I manually checked in BootstrapProvidersTests that the `Close()` method are indeed called. Do you have an easy repro?

**Comment by richorama** [comment]
Hmm. Try the Orleans dashboard and press F5 on the test host?

The bootstrap provider is called 'dashboard'

**Comment by benjaminpetit** [comment]
I see several issues in https://github.com/OrleansContrib/OrleansDashboard/blob/master/TestHost/Program.cs

First you never call `Silo.Stop()` or `Silo.Shutdown()`, so silos never execute the termination sequence.

Secondly there is a bug in `DevSilo`: the `InitSilo` method is called in the new AppDomain created, so in your parent AppDomain, `DevSilo.hostWrappers` is always empty. Instead of doing all this work, you could use directly `Orleans.TestingHost.TestCluster`.

I will close this issue, we can continue this discussion in https://github.com/OrleansContrib/OrleansDashboard if you want or need help to migrate to `TestCluster`.

**Comment by richorama** [comment]
Ah ha, thank you!
