### ISSUE TITLE
Observers don't recover after host restart

### ISSUE THREAD

**Issue by nidu** [dotnet/orleans#2977]
Hello.

Orleans 1.3.1.

I have asp net MVC web app which subscribes to Orleans grain via [observers](https://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Observers.html). If i restart host - grain becomes accessible and methods can be invoked but observers are not notified anymore.

Should they recover automatically or should some configuration be done or is there some easy way to track grain availability to manually refresh subscriptions?

**Comment by xiazen** [comment]
seems like the subscription map in the observed grain didn't persist through host restart. If you just store the subscription map in memory, the map will be lost after observed grain deactivate. 

I think you can persist subscription map through grain state using persistence, so that the subscription map can be preserved between observed grain activation and deactivation.

**Comment by sergeybykov** [comment]
>If i restart host 

Do you mean you restart silos?

If you restart the whole cluster, then the registration of client observers will be lost. Unlike grains, client observers aren't virtual, and cannot be automatically reactivated after a restart.

**Comment by nidu** [comment]
Yes, restart host. What would you recommend them? I'd like observers to
just keep on working after silo restart. Should I switch to streams or
track silo availability somehow and resub?

**Comment by sergeybykov** [comment]
The general recommendation is for client to periodically, e.g. once a minute, to re-subscribe, and for producers (grains) to detect and drop observers that haven't re-subscribed for a long enough period of time, e.g. 5 minutes.

The fundamental challenge here is that silos/grains can never be sure if a client/observer disappeared temporarily or for good. We don't want them to indefinitely try to send messages to clients that will never come back. Streams also give up on unresponsive client subscribers after a while.

**Comment by nidu** [comment]
Then if I wanna be sure each event is delivered observers is not an option?

Is there an easy way to detect dropped observers and grains? Or can it be
done automatically?

**Comment by sergeybykov** [comment]
>Then if I wanna be sure each event is delivered observers is not an option?

Correct. Observers are a best effort mechanism. To ensure delivery, a higher level protocol is needed.

>Is there an easy way to detect dropped observers and grains? Or can it be
done automatically?

Grains are eternal. They are never dropped, as they get automatically reactivated upon a new message to them. With streams, there's a configurable corner case where we give up on a 'poison' message after a few unsuccessful attempts to deliver it. But there is a notification interface for that.

Observers are inherently unreliable (because they are usually on web frontends that can reboot), and a higher level protocol, e.g. with periodic re-subscriptions like I mentioned above, is needed to detect their disappearance.
