### ISSUE TITLE
Allow sending stream messages from silo outside of grain code

### ISSUE THREAD

**Issue by DixonDs** [dotnet/orleans#2994]
Currently, it is not allowed to send messages to streams from silo but outside of the grain context - `InvalidOperationException` is thrown in `SiloProviderRuntime.GetStreamDirectory` to prevent that.

It is obvious for me why subscribing is not allowed (we must have data about the subscribing grain), but what could be an issue if we allow to send messages outside of the grain context? Somehow, logically, it is no different as sending messages from Orleans clients.

**Comment by sergeybykov** [comment]
There is a difference in case of the SMS stream provider - producers need to get notified about every new consumer subscribing to the stream. Shouldn't be a concern for persistent streams, I think.

**Comment by centur** [comment]
also for persistent streams and external senders - is there a standalone nuget or sample that would allow us to serialize our data object with all Streams related details? if I understand correctly - serialized message carries more than just a data payload, so stream pullers can read the message and extract stream Id and namespace from  it for further dispatching. Is there any specification planned, that would allow interoperability with external codebase that doesn't have any reference to orleans (say java or go) but still capable to send messages to e.g. Azure Queues ?

**Comment by galvesribeiro** [comment]
Yes... Publishing and receiving messages from a `GrainService` is also not allowed. I was talking with @ReubenBond a while ago about it. Looks like the `GrainService` has no Activation Context, which (for obvious reasons) is only set into a grain. The `GrainService` can get the stream provider, the stream, everything works, except when you are going to  publish or subscribe to the stream... 

Would be good to have it.

**Comment by gabikliot** [comment]
For what @galvesribeiro , I had a fix for that about 2 years ago:
https://github.com/dotnet/orleans/pull/608
It was de-prioritized and then forgotten and PR closed. You can try to resurrect. It won't be easy, since the code changed a lot since then. And the internals of how to do it is somewhat tricky.

For what @centur  asked: "standardization of streaming internals" - I don't know of any such plans. Our strategy was: if you want a lot of customization, just write a full blown custom stream provider. Your own agents, everything. It should be mostly possible (maybe a small number of classes would need to be made public).
These are the options we envisioned: 
http://dotnet.github.io/orleans/Documentation/Orleans-Streams/Streams-Extensibility.html
"Writing a Completely New Stream Provider"

**Comment by gabikliot** [comment]
I have provided enough context and details in https://github.com/dotnet/orleans/pull/608 so that it should be possible to trace the changes and redo it now.

**Comment by mjameson-se** [comment]
This does seem to work now (both sending and receiving messages from outside of a grain). I was getting strange behavior when trying to subscribe before the Orleans silo was fully started, which is why I googled the terms which led me here, but having resolved that it is working for me. The documentation wasn't clear whether this should work and should probably be improved in this area.

**Comment by galvesribeiro** [comment]
The current way you can send/receive messages from outside grain code to a stream are:

1. Use a `IClusterClient` that connects to the cluster and send/receive messages from a stream. This implies that the backing stream is using messages using Orleans formatting
2. Create a custom DataAdapter and register with the stream provider (look at the EventHub Stream provider tests for an example) so you can use non-standard message formatting and avoid the need to have a `IClusterClient` (i.e. send/receive messages from a stack other than .Net)
