### ISSUE TITLE
Migrate code samples from CodePlex

### ISSUE THREAD

**Issue by jkonecki** [dotnet/orleans#30]
*6. Migrate and update samples from Codeplex [Small/Medium]* from [Ideas for Contributions](https://github.com/dotnet/orleans/wiki/Ideas-for-Contributions)

@sergeybykov @gabikliot - could you please provide some guidance on where the samples should be placed and what kind of updates should be made?

**Comment by sergeybykov** [comment]
Gabi already ported three samples. He'll figure out where to put them, and we'll use them as a seed. Most of the samples likely require some trivial updates due to the recent API changes. But I also think it would help to take a fresh look, and see fi they are good ones, can be made better, and if there are significant gaps. We have created over the years organically, and that's not necessarily a good thing, I think. That's why I think a fresh perspective could help.

**Comment by gabikliot** [comment]
I published 3 samples that we already ported. They are in the Samples folder next to src folder. The samples expect the Orleans binaries to be pointed by ORLEANS-SDK environment variable, which is set as part of installing msi.

**Comment by jkonecki** [comment]
Thank you Gabi.

I'll take a look at the rest and try to come up with some suggestions for more.

**Comment by gabikliot** [comment]
Great, thank you!

**Comment by jkonecki** [comment]
@gabikliot could you please reopen the issue? I haven't ported all the samples yet... ;-)

**Comment by sergeybykov** [comment]
Reopened. :-)

**Comment by gabikliot** [comment]
BTW, there is no need to port the UnitTester sample. We included it already in the main tree.

**Comment by sergeybykov** [comment]
I believe this is done now.

**Comment by gabikliot** [comment]
Yes, was finished in https://github.com/dotnet/orleans/pull/234 and https://github.com/dotnet/orleans/pull/220.
