### ISSUE TITLE
Implementing DiagnosticsSource for cross silo tracing

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#3093]
Hi,

At the moment it is possible to correlate activities by propagating the current activityId in the RequestContext.

In NETStandard, the System.Diagnostic.Trace.CorrelationManager.ActivityId  is not supported.

When integrating application insights in our silo and client code for tracing, we are looking for a way to correlate these traces.

It seems like System.Diagnostics.Activity (https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md#overview) is the recommended replacement. 

It would be nice to be able trace grain to grain calls, by instumenting orleans with a DiagnosticsSource (https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/DiagnosticSourceUsersGuide.md) 

The implementation could be based on the System.Net.Http diagnostic handler implementation: https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs

A combination of ```RequestContext``` properties and an ```Interceptor``` could implement this, I think.

**Comment by jdom** [comment]
Interesting. I don't know exactly what that would mean in terms of how to configure the monitoring, but it would be nice to align better. It's very confusing to compare DiagnosticSource with the other Microsoft.Extensions.Logging abstraction, because typically you would configure the latter to send logs to some persistent storage, where having a correlated activity would be very useful, and I just didn't learn yet how that would work if we mix the two.
Having said that, there's currently an Orleans-specific way to do correlation in the 2.0 TP in case you were not aware, which is by using the `RequestContext.ActivityId` directly (see https://github.com/dotnet/orleans/pull/2961).

**Comment by rikbosch** [comment]
I think DiagnosticsSource's purpose is.. well diagnostics of not-serializable in-process data. The ```ILogging``` abstraction is for serializable data. One complements the other this way.

I've come up with a basic implementation of a diagnosticssource for use in a silo. You can find it here https://gist.github.com/rikbosch/fe31f5b4c3b029d8b57f238a91913a35

It's based on code from the aspnet core ApplicationHost and requires a preview of the ```System.Diagnostics.DiagnosticSource``` nuget package.

The same could be implemented in the grainclient, giving activitytracing accross service boundaries.
