### ISSUE TITLE
Reduce use of locks

### ISSUE THREAD

**Issue by dandago** [dotnet/orleans#3116]
Taking a look at Orleans source code I notice that it relies heavily on locks, especially the exclusive kind.

Perhaps after review, some of those could be replaced by either lock-free atomic operations (the ones you get from the `Interlocked` class in .NET, which include not just incrementing but also compare & swap) or concurrent collections.

This could potentially improve performance by eliminating bottlenecks in the core code.

I am not extremely familiar with the Orleans source code so I'm just placing this suggestion here and welcome any feedback.

**Comment by gabikliot** [comment]
We use the following principles throughout the stack:
1) relying on single threaded execution of our scheduler: a lot of logic runs inside System targets and those are single threaded like grains. That completely eliminates any need for locks.
2) heavy use of concurrent collections. I don't think we ever have any collection that is protected by global lock, unless maybe used only in initialization.
3) optimize for hot path: much more care was put into optimizing the messaging code path vs. other, background of infrequent code paths.

That all said, it is totally possible that we still have some occasional locks (definitely not heavily) that could be further optimized. If you are up to try to find those, this could be useful.
Suggestions:
1) submit your changes one at a time. don't bundle multiple unrelated changes.
2) benchmark: measure perf. before and after. Include benchmark results in your CL.

After your CL is reviewed, the team has a number of different end to end benchmarks (we call them load tests), that run run daily. They will be able to asses the performance improvement in  your CL and make sure it does not degrade the performance. A lot of times we see that some change improves a lot in the micro benchmark, but not much end to end. Even if this is the case, we can consider accepting the change given that it does not complicate the code too much and there are no correctness concerns. Sometimes one micro improvement does not improve end to end results, but then combined with other later improvements it may suddenly become beneficial too.

BTW, just 'Interlocked' instead of lock is not always better. It really depends a lot on the usage pattern. Taking a free lock is very efficient, maybe comparable to 'Interlocked'. You need to benchmark and measure.

**Comment by gabikliot** [comment]
Here is a just a random writeup on lock vs. Interlocked:
http://blog.moxen.us/2010/08/22/lock-spinlock-and-compareexchange-performance/

"As you can see from the data, the performance of lock() is fairly close to an optimized, lockless approach. Everything else is actually slower.

So, unless you’re really fighting for every last ounce of muscle from your application, coding obscure, complicated classes which use CompareExchange is not going to provide you with a substantial benefit. Stick with lock(), or use one of the concurrent classes in .NET 4.0 if you can."

**Comment by DixonDs** [comment]
@gabikliot 
>I don't think we ever have any collection that is protected by global lock, unless maybe used only in initialization.

To be fair, there is a bunch of such places. For example, search for "lock" in `SerializationManager` (https://github.com/dotnet/orleans/blob/3a7e3c7f413219128c192b5175af3b2fe448b497/src/Orleans/Serialization/SerializationManager.cs)

At same time, IMO, this discussion is not really productive in the _general_ case - all cases should be tackled one by one as there is no silver bullet for all performance issues in concurrent code like change X to Y everywhere.

**Comment by sergeybykov** [comment]
>At the same time, IMO, this discussion is not really productive in the general case - all cases should be tackled one by one as there is no silver bullet for all performance issues in concurrent code like change X to Y everywhere.

I agree with this sentiment. A set of issues about specific locks would be better because we'd be able to investigate and measure them one by one without getting into a blanket general discussion of X vs. Y.

**Comment by gabikliot** [comment]
List of locks or an issue per suspicious lock would be the best.

Most of the locks in SerializationManager are in initialization, but there are actually a couple not that look maybe suspicious - in all Get/Has methods:

https://github.com/dotnet/orleans/blob/3a7e3c7f413219128c192b5175af3b2fe448b497/src/Orleans/Serialization/SerializationManager.cs#L1073

**Comment by ReubenBond** [comment]
@gabikliot we can remove those locks by replacing those collections with  `CachedReadConcurrentDictionary<K,V>`. It caches a `ConcurrentDictionary` in a `Dictionary`. It invalidates the cache on write and regenerates it after N successive reads.

**Comment by dandago** [comment]
As I said before - I am not that familiar with the source code and wanted to encourage review to identify potential performance issues. The title itself says "reduce" usage of locks (as opposed to "remove") - I am well aware that removal of locks would not have a significant impact everywhere. But if there are a few hotspots that can benefit from this, then I believe it is worth taking a look.

You guys who know the code inside out are much better suited to know which classes are heavily used at runtime and thus may benefit from lock removal.

@gabikliot where can I find the load tests that you mentioned?

**Comment by gabikliot** [comment]
The tests are not on GitHub.

We of course already looked and constantly looking at places to optimize. This is an ongoing process that is already done for years.

**Comment by ReubenBond** [comment]
Closing. There aren't many locks left that I am aware of, particularly contended ones.
