### ISSUE TITLE
QueueAdapter doesn't have  option to close any resources used by the adapter

### ISSUE THREAD

**Issue by bobanco** [dotnet/orleans#3118]
Hello folks, 
currently `IQueueAdapter` doesn't have  option to close any resources used by the adapter if we are acting as producer, only `IQueueReceiver` has `Shutdown` method which in terms can be used to close any resources used by the Stream consumer, like long lived connection to the queuening engine like RabbitMQ.
 I'm implementing [RabbitMQ Stream Provider](https://github.com/bobanco/Orleans.Providers.RabbitMQ)
and when i shutdown the silo it hangs and all consumer connections opened to the RabbitMQ are still there untill i explicitly kill the connection from the management GUI and then the silo shutdowns. 
it would be good if we have `IQueueAdapter.Shutdown(Timespan timeout)` method so we can also close all of the resources used by the producers as well.

**Comment by jason-bragg** [comment]
Hello @bobanco,
I'm not strictly opposed to a shutdown operation on the agent, though I'd like to think through the architecture a bit more first.

In the interim, the PersistentStreamProvider is an IProvider, which supports an asynchronous Close().  Since specialization of PersistentStreamProvider is required to use a custom adapter, I suggest considering tracking resources by provider name, and cleaning them up in custom Close() logic for your provider.
Something like:

    public class MyStreamProvider : PersistentStreamProvider<MyAdapterFactory>, IProvider
    {
        Task IProvider.Close()
        {
            await RabbitMQResources.CleanupResources(this.Name);
            await base.Close();
        }
    }

**Comment by bobanco** [comment]
Hi @jason-bragg ,

i will try to manage with this for now, Thanks for your help.
