### ISSUE TITLE
[Question] Bootstrapping DI and logging

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#3132]
I have a simple question: when bootstrapping my services in the `Startup` class using dependency injection I want to do some logging using Orleans logger. But how will I get a logger instance in my `ConfigureServices` method?

**Comment by jdom** [comment]
Hmmm, interesting question, but it is currently not possible. The logging infrastructure should be configured by then, but it's not really accessible from the startup type.
If this is temporary just to troubleshoot a few things, what you can do for now is use reflection to get the logger. Note that this might not be supported in the future, especially since we are looking to migrate to `Microsoft.Extensions.Logging` in the release following 1.5 (but this hack will work in 1.5 still). Nevertheless, once we move to that, the logger will be usable when configuring the silo, so hopefully no hack will be necessary.

Toy get the logger via reflection, you'd have to do something like this:
```csharp
// Call LogManager.GetLogger(this.GetType().Name) with reflection, as it's internal
var getLoggerMethod = typeof(LogManager).GetMethod("GetLogger", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static, null, new Type[] { typeof(string) }, null);
Logger logger = (Logger)getLoggerMethod.Invoke(null, new object[] { this.GetType().Name });

logger.Info("Now I can use the logger");
```

**Comment by peter-perot** [comment]
@jdom Thank you, it works! :-)
