### ISSUE TITLE
How to access client ip address at 'server side interceptors' or 'RequestContext'?

### ISSUE THREAD

**Issue by jayeonsu** [dotnet/orleans#3172]
I need to block harmful clients that access to silos or grains, according to their ip addresses.

I looked into 'server side interceptors' and 'RequestContext', only to find them unhelpful to get client's ip address. (I can't use 'RequestContext.Set("ip", CLIENT_IP)' because it can be falsified.)

Is there any way to check client's ip address at server side?

**Comment by jdom** [comment]
Are your silo clients not trusted? Be aware that Orleans has zero security features as it assumes that the silos are fully trusted by the client, and they are typically the ones in the frontend performing some validation and defense against any potential attacks.
Even the connection from client to silo is currently not encrypted.
Because of those assumptions, I'm not aware of ways to do auth or black/white listing of clients.

**Comment by jayeonsu** [comment]
@jdom 

I thought that it was too verbose to wrap silo clients and expose them via my own API.
So I wished orleans could have some features for security.

btw, at long last I've decided to expose them via my own API.

Thanks for your answer. :)
