### ISSUE TITLE
Allow reentrancy within a grain call chain

### ISSUE THREAD

**Issue by sergeybykov** [dotnet/orleans#3184]
There've been multiple request for this narrow deadlock prevention feature - to allow reentrancy for calls to grains that are already part of the call chain. For example, if grain A calls grain B, and while executing the invoked method B calls back to A, today that B->A call will deadlock and eventually time out, unless A is marked as `[Reentrant]`. The proposal here is to allow the B->A call to execute (while A is awaiting its call to B) even if A is not marked as `[Reentrant]`.

The argument for this change is that reentrancy within a single call chain is relatively safe compared for reentrant parallel execution of multiple independent requests, and that the benefit of avoiding deadlocks within a call chain would save a significant amount of developer's cognitive effort of avoiding cycles in call chains, some of which may not be obvious, and finding the root causes of deadlock timeout happening at run time.

If we were to implement this, we could make this behavior either the default or an explicit opt-in via a configuration switch. The opt-in options appears safer because if doesn't change the default behavior. However, if we made this the default, the only cases that would be potentially impacted are those that would cause a deadlock today anyway. So it seems to me that making reentrancy within a call chain the default behavior is actually pretty safe, even though it would technically be a breaking change.

We would need to pass additional information with every message, which could have a performance impact. That's a potential argument for opt-in, unless we find no measurable performance difference.

**Comment by gabikliot** [comment]
I think this is already implemented in our code base, just disabled.
We have deadlock detection phase one implemented and it does what u described above. Upon detecting a cyclic deadlock, it now throws deadlock exc. In your proposal, we will change it to allow concurrency.
Unless we deleted that code when we went open source. But I think it is still there.

:-)
Isn't that nice?

**Comment by gabikliot** [comment]
https://github.com/dotnet/orleans/blob/2af52f7401b6f06b6c7f3d100349b889478591e0/src/OrleansRuntime/Core/InsideRuntimeClient.cs#L285
and we even have a test.

**Comment by dVakulen** [comment]
@gabikliot  Just wanted to write that the part is that there's already tests for this.

**Comment by sergeybykov** [comment]
@gabikliot Nice! I completely forgot about the deadlock detection feature that's been disabled for years, and didn't think we could reuse it. IIRC at the time there was a suspicious performance drop because of which we never enabled the feature. Need to retest now.

**Comment by gabikliot** [comment]
Yes, there was a perf. drop. The reason was, I am pretty sure, since we put too much info into the header. We put a lot of ids and strings (grains, etc...) so we can give a full history of the request path, with all grain names, in the exception (that was especially important for heterogeneous silos). But that can be optimized and include only activation ids, or even their hash.
Once you do that, I hope the perf impact will be tiny. The you can enable it always.

The 2nd part of this, after deadlock is detected, will be to allow concurrent execution. You need to be careful. We will be mixing non reentrant and reentrant modes, and the code in activation data was not written to handle that I am afraid. That was one of the reasons we scraped out ReadOnly. Since it was much harder to handle the mixed mode.

So that will be a 2nd part of this project. Totally doable I think, but need to be very careful and thorough.

**Comment by sergeybykov** [comment]
Resolved via #3185.

**Comment by oreporan** [comment]
Question, I see you spoke about covering the case of A -> B -> A 
Will this also cover stream calls in the chain?
We have A that calls B, and B streams to many A types.
I assume its covered since under the hood its just more Grain calls right?

**Comment by dVakulen** [comment]
@oreporan The await on publishing of events into the stream completes when the item has been accepted and does not wait for consumers to processed it. So yes, the stream calls in chain also covered.
