### ISSUE TITLE
[Question] Calling GetReminder/UnregisterReminder in Task.Factory.StartNew task

### ISSUE THREAD

**Issue by sgratwohl** [dotnet/orleans#3225]
Is it 'safe' to call GetReminder and UnregisterReminder from outside of a direct grain method like in a task started with `Task.Factory.StartNew`?

```c#
private async Task SomeGrainMethod()
{
	var fireandforget = Task.Factory.StartNew(async () =>
	{
		var othergrain = GrainFactory.GetGrain<IOtherGrain>(Id);
		await othergrain.DoSomething();

		var rem = await GetReminder(MakeOtherGrainToDoSomethingReminder);
		if (rem != null)
		{
			await UnregisterReminder(rem);
		}
	});
}
 ```

Thanks!

**Comment by sergeybykov** [comment]
What is the reason for running this code as a separate task? A task started with `StartNew` will execute on the same Task Scheduler associated with the grain. So you can as well put the code inside `SomeGrainMethod` instead.

Not awaiting a task, especially one that makes grain calls or calls into runtime APIs, is not a recommended pattern, in particular because of [lack of] error handling. At the very minimum, you better call `fireandforget.Ignore()` so that an exception in case of an error doesn't get thrown on the finalizer thread.

But again, I would start with what exactly you are trying to achieve by executing the code in such a manner instead of putting it directly into the grain method.

**Comment by sgratwohl** [comment]
There is a grain `IModelGrain ` that holds a state and provides an interface to interact with and modify that state. It should be accessible with as little latency as possible because the state is often read by clients.
One of the tasks that processes the state could run up to 20 seconds. Because of that I created another Grain `IWorkerGrain ` that takes the state (with an ETag-like marker) and handles the long running work and then calls the
ModelGrain back with the result. If the ETag is still valid the state is then accepted from the ModelGrain. 

```c#
public class ModelGrain : IModelGrain
{
	public async Task StartLongWorkingTask()
	{
		var ff = Task.Factory.StartNew(()=>{
				try
				{
					var worker = GrainFactory.GetGrain<IWorkerGrain>(this.GetPrimaryKey());
					await worker.InitWork(State.SomeObjectWithETag);
					await UnregisterReminder("StartLongRunningTaskReminder");
				}catch(Exception e)
				{// log}
		});
	}
	
	public async Task ReceiveAnswerFromLongWorkingTask(SomeObjectWithETag obj)
	{
		// update state if ETag valid
	}
	
	public Task<Immutable<SomeObjectWithETag>> ShowState(){...} 
}

public class WorkerGrain : IWorkerGrain
{
	public async Task InitWork(SomeObjectWithEtag obj)
	{	
		//trycatch and has also a reminder to make sure that the task is not lost on error
		obj = DoSomethingThatTakesAges(obj);
		var modelgrain = GrainFactory.GetGrain<IModelGrain>(this.GetPrimaryKey());
		await modelgrain.ReceiveAnswerFromLongWorkingTask(obj);
	}
}
```

If `ModelGrain::StartLongWorkingTask` would call `WorkerGrain::InitWork` without `Task.Factory.StartNew` there would be a deadlock.

`StartLongRunningTaskReminder` is a reminder that calls `StartLongWorkingTask` and its purpose is that if something went wrong in `StartLongWorkingTask` `InitWork` will be called again. 

I hope it is understandable what I'm trying to achieve and thank you very much in advance for your input.

The whole thing works quite good and is very easy to use so I hope I didn't do something fundamentaly wrong! ;)

**Comment by sergeybykov** [comment]
This is good context, makes it much clearer.

It seems like the problem you are really solving is the circular reference between `ModelGrain` and `WorkerGrain` An alternative would be to mark `ModelGrain` as `[Reentrant]`. Since it looks like `ModelGrain` is the one that initiates activity of the corresponding `WorkerGrain`, it shouldn't be too difficult to control interleaving within `ModelGrain`.

Another alternative is to have `InitWork` only record the need to start the work (e.g. by scheduling an immediate timer), and have `WorkerGrain` notify `ModelGrain` over an observer interface.

To your original question
>Is it 'safe' to call GetReminder and UnregisterReminder from outside of a direct grain method like in a task started with Task.Factory.StartNew?

With reminders specifically you may be fine because `UnregisterReminder` calls to an "external" Reminder Service. Although in general, it's a slippery slope where if you try to use other features later, they may get into a race with, for example, deactivation process in an non-deterministic and difficult to figure out way. Hence, my recommendation so far would be to mark `ModelGrain` as `[Reentrant]`.

**Comment by sgratwohl** [comment]
Then I'll avoid that potential slippery slope and try to make InitWork only record the need to start the work. I think that this is a safer approach for this project because ModelGrain has some other methods that change the model and I don't want them to allow interleaving.  Thank you for the help and clarification!
