### ISSUE TITLE
Kubernetes Documentation

### ISSUE THREAD

**Issue by ChrisBellew** [dotnet/orleans#3269]
Hi there,

Firstly, I love the great work you're doing...especially getting Orleans compatible with .NET Core!

Just wondered when we might see some documentation for running Orleans on Kubernetes? Ideally with some info about autoscaling.

The doco (3 months ago) says "Coming soon..."

Thanks again :)
Chris

**Comment by galvesribeiro** [comment]
Hello @ChrisBellew thanks for ask.

I'll try to produce that part of the document this weekend. I started with a sample by the time I wrote that doc page but had some issues with K8s networking and since people were asking a lot for Swarm first and it was ready, I decided to release it first and take a look on K8s later on.

Will keep this issue updated.

Thanks for pushing it!

**Comment by christianhuening** [comment]
are there any updates on the docs?

**Comment by galvesribeiro** [comment]
Have a look on https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes

There is a membership provider for kubernetes, simple doc and samples.

Pretty easy to get it running with it.

**Comment by ReubenBond** [comment]
We have documentation on how to use Orleans with Kubernetes now: https://dotnet.github.io/orleans/docs/deployment/kubernetes.html
