### ISSUE TITLE
grain distribution in silo

### ISSUE THREAD

**Issue by balakannanmca** [dotnet/orleans#3336]
Cloud service is running with four instances. In cloud service starting, one or two instances are taking some time start.  In that time, grains activated in active cloud service instances. 
So grains didn't distributed equally in silos. One silo was fully loaded. Other one was free. 

How can i ensure that grain distributed equally in silos?

**Comment by sergeybykov** [comment]
When new silos join a cluster, there is no forced redistribution of already activated grains. Only new activation get distributed across all silos. Over time, as new grains get activated and idle ones get collected, you'll reach a balanced distribution across all silos.

You can choose to add a `[ActivationCountBasedPlacement]` attribute to your grain classes to expedite balancing. It makes all new activations to go to silos with lower counts of grains. There's a danger with that though of overloading the newly started silos by putting a disproportional share of new, and hence actively used, grains to a small number of newly joined silos and overloading them. That's why the default placement strategy is more conservative.

**Comment by elqueffo** [comment]
Is there a way to access activation counts per silo of a grain? This way the grain could check "balance" and decide to DeactivateOnIdle itself to be relocated.

**Comment by yevhen** [comment]
> Is there a way to access activation counts per silo of a grain? This way the grain could check "balance" and decide to DeactivateOnIdle itself to be relocated.

:+1: Will save us some additional lines of code. Smth like `ManagementGrain.GetActivationCount(Silo.CurrentSiloName, typeof(IGrain))`
