### ISSUE TITLE
Adjustments to RowKey on OrleansSiloStatistics

### ISSUE THREAD

**Issue by richorama** [dotnet/orleans#34]
Before I go and write the code for this, I thought it would be worth having the discussion.

## Current design

Presently the scheme for the PartitionKey / RowKey fields on OrleansSiloStatistics is as follows:

PartitionKey: `SiloName:Date`
RowKey: `DeploymentId:Epoch:counter`

For example:

PartitionKey: `17b8149c37384e16aa5672193dc8daa1:2014-08-15`
RowKey: `S100.74.190.62:11111:145792311:000001`

## Problems

Table storage can only return values in the alphabetical order of the partition/row keys. It would be nice to have the keys laid out such that a simple query (just fetch 1000 entities from the table) always retrieves the latest records written to the system.

A technique for doing this is documented here: http://blog.smarx.com/posts/using-numbers-as-keys-in-windows-azure

It would also be nice to have a deterministic way of retrieve the data, without knowing the machine names, i.e. just supply a date range to retrieve all data in that period.

## Suggested solution

My suggestion is this format:

PartitionKey: `Date:SiloName`
RowKey: `EpochCountdown:DeploymentId:counter`

Where EpochCountdown is a padded string, counting down the seconds to the end of the epoch.

Note that the order of the keys has also been changed.

PartitionKey: `2014-08-15:17b8149c37384e16aa5672193dc8daa1`
RowKey: `854207689:S100.74.190.62:11111:000001`

## Impact

This technique gives you a date-first approach to reading the data, and makes it harder to query by a single machine.

I would have to make some adjustments to my [SiloMon](http://www.silomon.net/) project!

Otherwise, I'm not sure how widely used this table is?

## Other thoughts

Is colon `:` the best character to use as a separator? It's a character used by the silo name. Perhaps using a dollar `$` would be better?

**Comment by gabikliot** [comment]
Richard
Currently for silo statistics we have:
PartitionKey:  DeploymentId:Date 
RowKey:  SiloName:Counter

https://github.com/dotnet/orleans/blob/master/src/Orleans/AzureUtils/StatsTableDataManager.cs

it is not what you wrote above. (yes, it is a bit confusing, with all the different tables). Every different table has a bit different key schema. Can you please update your suggestion based on that?
In general, we are very open to changing the schema for stats table. Anything that will make it easier to use.

OK for using $ for separation in the silo stats table instead of ":", which is reserved to silo address.

BTW, don't confuse silo address (ip:port:epoch) with silo name which is usually role instance name in Azure (MyOrleansWorkerRole_1).

Also, if we are changing silo stats table, we need to change client stats table accordingly.

**Comment by jason-bragg** [comment]
@richorama 
When referencing table storage reads, it’s unclear if you are referring to querying ordered data from a partition or from the table itself.  For performance reasons table scans should be avoided, so I’ll assume you’re referring to the ordering of the row keys within a partition.

If we’re constraining the discussion to partition reads, having the date in the partition key will reduce the number of rows per partition, which is a good thing, so I’d suggest we leave it in there.  When thinking about this, consider performance characteristics of deployments with hundreds of silos that could run for years.

The epoch countdown is a useful convention, we tend to refer to it as a reverse order timestamp, but terminology aside it is useful for ordering table store data.  What I’m not clear on is what systems are querying these rows.  If silos query this partition for these rows, we may need to keep the silo name first.  Main thing hear is to understand the current and expected calling patterns.  Unfortunately, I can’t speak to that.

To the point made by @gabikliot about PartitionKeys/RowKeys being unclear.  My preference is to always have some qualifying prefix to clarify the row or partition type.
For instance:
PartitionKey: deploymen:DeploymentId:Date
RowKey: silo:siloName:Counter

With this you can perform fairly specific (and fast) row key queries by RowKey ranges.
example RowKey from "silo:" to "silo:~" queries all silo rows for a deployment day while "silo:mySilo:" to "silo:mySilo:~" queries all silo rows for my silo.

Again, critical thing here is to understand the required query patterns, and since we only have partition and row keys to efficiently organize by, we're far more constrained than traditional databases.

**Comment by gabikliot** [comment]
About querying pattern, one thing for sure: this is NOT a table that silos will read to get stats about each other at runtime. For that we have metrics table and also direct silo to silo calls to update each other about their perf. stats/metrics. 
This is also not for other online tools to query it at runtime, to make fast online dynamic decision. Think for example Azure auto scale. It will not use that, I think.

This table was envisioned for offline analysis. Think about throwing all your periodic stats into Hadoop to do some crunching periodically. We basically came up with that table when we did that work:
(http://research.microsoft.com/apps/pubs/?id=217109)
In this work we demonstrated different types of offline perf analysis, like anomaly detection. Something that you do when you need to go deep into why your system works the way it works. Not fast online control decisions, like auto scaling, but rather deep, full data, including historical data analysis.

That was at least the vision. It may change of course.

@jthelin-microsoft took a key part in that work, including designing this table, so he may have an opinion as well.

**Comment by richorama** [comment]
Thanks all, allow me to be clearer!

The objective of the change are:

1. To provide a deterministic way of retrieving records for a given date range (across all silos/clients)
1. To order the rows in the partition according to the date (latest first)
1. To order the partitions according to date (latest first)
1. To not have to know which silos/clients are contributing to the stats (i.e. having to supply the silo name in the query is a disadvantage).

This allows a naive query to just pull the latest records, and you can iterate through until you get to the end end of the last period you queried.

It won't matter if your query crosses partitions (except from a performance perspective).

You could supply any date range, and query that partition or key range.

* I take the point that partitions should be small (perhaps they should be just an hour?)
* It's also possible to write to multiple tables, using different key schemes, therefore indexing the data in several ways (although I'm not suggesting this).

Perhaps this is a better scheme for Silo Stats:

PartitionKey: `DeploymentId$ReverseTimestampToTheNearestHour`
RowKey: `ReverseTimestampToTheNearestSecond$SiloName$counter`

And for client stats:

PartitionKey: `DeploymentId$ReverseTimestampToTheNearestHour`
RowKey: `ReverseTimestampToTheNearestSecond$ClientName$counter`

Does anybody actually use these tables (other than me?).

**Comment by jason-bragg** [comment]
The suggested pk/rk pattern would provide the behavior you seek, but may result in prepend performance problems.
http://azure.microsoft.com/en-us/documentation/articles/storage-performance-checklist/#subheading28

I am not aware of the write frequency of these records, so I can’t advise if this would have any real performance implications.  I’d suggest investigating the rate in which these writes occur.

If this format is accepted, I’d request timestamp format be defined as part of the row key definition.

**Comment by richorama** [comment]
@jason-bragg for the silo statistics, one record  is written for every active grain type, plus an extra 2, every 5 seconds, for every silo.

So 100 silos with 10 grain types would be `(100 * (10 + 2) / 5) = 240` writes per second on average.

I haven't got a precise number for the client statistics, but I expect it's the same order of magnitude.

Table storage should handle 2000 writes per partition per second (albeit that's probably for append rather than prepend). However as our writes are to a single partition, they could be batched.

Therefore I don't think we're talking about a high load load on the system.

**Comment by sergeybykov** [comment]
By default, stats are logged to the table every 30 seconds.

**Comment by jthelin-microsoft** [comment]
Under the covers, the periodic writes to the table are done as an Azure bulk update (`AzureTableDataManager.BulkInsertTableEntries`), so I believe in practice it should work out as just one write per silo per period.

Also note that the Statistics / Metrics Publisher is intended to be an extensibility point, so it _should_ be fairly easy to write a new publisher implementation that replaces the current one(s), and compare performance / usability. 
I say "should" because this extensibility point has only had limited testing / exposure when the SQL provider was added, so there could well be some rough edges in that plugability point. :8ball: 

My general rule of thumb is that at least 3 data points are needed to establish any kind of trend, and the same applies to API's: 3 implementations required for an existence proof :)

**Comment by jthelin-microsoft** [comment]
It is useful to take a step back and try to understand the different usage scenario(s) that @richorama envisages here.

The intent of the original choice of partition / row keys was to deliberately spread the overall stats data for specific cluster / deployment across *multiple* partitions. This was based on the usage assumption that stats was mostly *write-once-consume-many-times* operation, so allowing consumers to do parallel reads across multiple partitions should in theory give lower query latency.

My concern would be that if you don't have something like DeploymentId as part of the PartitionKey, then we degenerate into having to do a full scan across all rows in all partitions to retrieve all the data for a specific deployment.

As @gabikliot points out, currently for silo statistics table uses keys:
* PartitionKey = `DeploymentId:Date`
* RowKey = `SiloName:Counter`

So I think @richorama latest proposal above preserves our original design intent for allowing easy investigation of performance characteristics of a _single_ cluster which the [PAD] paper described.

* PartitionKey =  `DeploymentId$ReverseTimestampToTheNearestHour` 
* RowKey =  `ReverseTimestampToTheNearestSecond$SiloName$counter` 

I am not sure how this new key scheme will interact with the "prepend performance problems" which @jason-bragg pointed to, but it sounds like it may not be relevant if we only need to do 1 bulk write per silo every 30 seconds.

I suggest to code up the change for detailed PR review now, because it sounds like we are converging on a firm proposal. 

I suggest we also should add some explicit documentation of the key format(s) into the wiki so it becomes part of the official stats storage schema definition rather than having to hunt through the depths of the code to find it ;)

PAD: Performance Anomaly Detection in Multi-Server Distributed Systems][PAD]
[PAD]: http://research.microsoft.com/apps/pubs/?id=217109

**Comment by jthelin-microsoft** [comment]
And @richorama, if you haven't already done so, please complete a .NET Contribution License Agreement (CLA) because I think this definitely will count as a non-trivial contributions to this project :)
https://github.com/dotnet/corefx/wiki/Contribution-License-Agreement-%28CLA%29

**Comment by gabikliot** [comment]
The partitions with current @richorama  design will be smaller then before: before it was one partition per deployment per day, now it is one partition per deployment per hour. So we are only improving it.
Row keys are basically the same, just ordered differently.
Client row key included something called client epoch, and I don't think we need it anymore.

**So I see that this change only improves on the current code. So I am totally for it.**

The other question if there is even a better way. This will need to take @jason-bragg point about prepend and envisioned query pattern and look at the amount of written data (BTW, we write every 5 min by default, not 30 sec). We don't have to answer it now, w.r.t this pull request. We can put this question on the side and just proceed with the fix, since this fix only improves the current situation.

**Comment by richorama** [comment]
Ok, I'll code it up!

@jthelin-microsoft I signed a CLA a while back for some contributions I made to Azure repos. I hope that CLA still stands?

**Comment by jthelin-microsoft** [comment]
Hmm. I'll have to check with the CLA Admins whether the same CLA can be applied to both Azure and .NET but I think it might be different because Azure projects point to this CLA doc rather than the .NET one:  http://azure.github.io/guidelines.html#cla

**Comment by jthelin-microsoft** [comment]
@richorama, I have now clarified things with the CLA folks, and they said that the Azure CLA is not applicable for this .NET project. 
The Azure source code is owned by Microsoft so your previous CLA is still good for contributions to those projects. 
However, the .NET source code [of which Orleans project is part] is owned by ".NET Foundation" which is separate legal entity and so separate CLA is required. 
https://github.com/dotnet/corefx/wiki/Contribution-License-Agreement-%28CLA%29

Please don't shoot the messenger here :)

**Comment by richorama** [comment]
@jthelin-microsoft no problem, I have signed the dotnet CLA (which is a slick process!)

**Comment by jthelin-microsoft** [comment]
Cool. Thanks for doing that @richorama 

Yes, i was impressed with the slickness of the DocuSign process too -- much better than the bad old days (not that long ago!) when you would have had to print, sign and fax or s-mail the forms back!

@gabikliot - The PR #34 for this change is assigned to you if you would like to confirm and approve the merge into master.

**Comment by gabikliot** [comment]
Closed via #95.
