### ISSUE TITLE
Can not work with Nuget Package manager in sample projects VS2017

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#3436]
When I try to go to install tab of Nuget Package Manager in VS2017 in sample project, it shows an error like the attacked screenshot. Sometimes the error in output is "Could not resolve path %ProjectPath%\..\binaries\NugetPackages", sometimes it is nothing.

![nuget](https://user-images.githubusercontent.com/5682459/30806559-2e0f5890-a203-11e7-9987-85c26d7066c0.jpg)

**Comment by jokin** [comment]
there is a nuget.config file in the samples directory with the reference to a local repo
`<add key="Orleans-local" value="..\Binaries\NuGet.Packages\" />`

I don't know if it's needed for any of the build steps, but if you remove the line (or the file because that the only repo it contains) it will work.

**Comment by ashkan-saeedi-mazdeh** [comment]
@jokin  Thanks , Created a PR #3454 if that is an issue, Otherwise the core team will reject it. 

But my samples definitely started working and that should not have been there I guess.

**Comment by jdom** [comment]
Resolved via #3454. Good catch
