### ISSUE TITLE
Call Grain Methods from EventProcessor Hosted within Silo Worker Role

### ISSUE THREAD

**Issue by parkerhillius** [dotnet/orleans#344]
I am trying to implement a simple EventProcessor to pull events off of an Azure Event Hub and deliver to the appropriate grain, until the Orleans Event Hub integration has been completed. At which time we will switch to that implementation.

In the Silo WorkerRole.Run() I am registering my EventProcessor with the Event Hub. When processing events within the ProcessEventsAsync(), I am activating and invoking a grain as such:
var grain = GrainFactory.GetGrain<IGrain>(grainId);
grain.Method(event);

I am getting the following exception when calling the grain.Method(event):
System.Data.InvalidExpressionException: Trying to send a message on a silo not from within grain and not from within system target (RuntimeContext is not set to SchedulingContext) RuntimeContext.Current=null TaskScheduler.Current=System.Threading.Tasks.ThreadPoolTaskScheduler
   at Orleans.Runtime.InsideRuntimeClient.SendRequestMessage(GrainReference target, Message message, TaskCompletionSource`1 context, Action`2 callback, String debugContext, InvokeMethodOptions options, String genericArguments)
   at Orleans.Runtime.InsideRuntimeClient.SendRequest(GrainReference target, InvokeMethodRequest request, TaskCompletionSource`1 context, Action`2 callback, String debugContext, InvokeMethodOptions options, String genericArguments)
   at Orleans.Runtime.GrainReference.InvokeMethod_Impl(InvokeMethodRequest request, String debugContext, InvokeMethodOptions options)
   at Orleans.Runtime.GrainReference.<InvokeMethodAsync>d__0`1.MoveNext()

Do I have to instantiate an Orleans Client if I want my silo to directly process the messages coming from the Eventhub?

Any advice on how to work around this issue, while heading in the direction of eventually implementing the Orleans Event Hub integration would be greatly appreciated. Has a rough timeline been established for the Orelans EventHub integration?

**Comment by gabikliot** [comment]
You are trying  to instantiate EventProcessor  in the same worker role with the silo, but the problem is that you are sending msgs to the grain from an arbitrary thread and not from within Orleans context.
There are a couple of options to solve this:
1) **Run EventProcessor  from a different role**. Have a special role with what even number of instances you want, initialize Orleans client in that role (from Orleans perspective it will be a regular Orleans client), also instantiate EventProcessor in that instance and just send msgs.
2) If you do not want to have extra roles, and want to **run in the same instance with the silo**, you need to create either another process in this role or another app domain and implement option 1 in that app domain. So, in that app domain/process you will initialize Orleans client and instantiate EventProcessor.

> Do I have to instantiate an Orleans Client if I want my silo to directly process the messages coming from the Eventhub?

To process, not. To process you don't need anything from Orleans. But to send msgs to a grain you do have to be in the "Orleans context", which means either inside a grain on the silo or with initialized client if on the client.

> Has a rough timeline been established for the Orelans EventHub integration?

EventHub integration in the way described above is already working, no problem. We have people using it this way.
Having EventHub stream provider (integrating EventHub with Orleans streaming) is work in progress, but we don't have a timeline when this is will be finished yet.

**Comment by jkamstra** [comment]
Can't wait to see or learn more about EventHub with Orleans streaming work stream (pardon pun). How can we help?

**Comment by gabikliot** [comment]
Jeff, we are now in the process of refactoring the adapter APIs, which will make plugging Event Hub adapter much easier. Once we are done, we can see together how the community can help. Thank you!

**Comment by gabikliot** [comment]
@jkamstra, PR https://github.com/dotnet/orleans/pull/367 included the first step in refactoring the queue adapter APIs. We will be doing more, but  I think that already now it is in a shape that anyone should be able to write an adapter to his queuing system. We do plan to write an Event Hub adapter, but I can't promise when. If anyone wants to write one and contribute it, this would very nice.
