### ISSUE TITLE
What is the purpose of specifying multiple seed nodes?

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#3507]
In my development scenario with 2 silos, I am using MembershipTableGrain as Livenesstype and have only 1 seed node pointing to my primary node with the second silo being secondary node.

I can see in Globals that seed node is an array of addresses therefore **what is the purpose of specifying multiple seed nodes?**

**Comment by sergeybykov** [comment]
Support for multiple seed nodes is there for historical reasons. In early prototypes of Orleans we had that. I'm almost sure it doesn't work anymore with more than one seed (a.k.a. primary) node configured. Should probably remove that in 2.0.

**Comment by xiazen** [comment]
It is confusing indeed. So We are thinking about reducing the confusion there by changing `List<SeedNode> SeedNodes` to be `IpEndpoint SeedNode` in 2.0. 

But we are also migrating off GlobalConfiguration in 2.0, so that GlobalConfiguration will become obsolete after 2.0. So there maybe not much value in 2.0 to fix it. 

Or there's a third option: update the documentation on SeedNodes and warn user to not use more than one seed nodes. 

Which one do you like personally?

**Comment by Kimserey** [comment]
> Support for multiple seed nodes is there for historical reasons. In early prototypes of Orleans we had that. 

I got confused because I thought that if the seed node stated as primary would go down, the membership state together with the primary status would be passed to the next seed node alive.

> Or there's a third option: update the documentation on SeedNodes and warn user to not use more than one seed node.

I think this would be enough since GlobalConfiguration will be obsolete.

**Comment by gabikliot** [comment]
What Sergey said: we should remove seed nodes and move to a single primary node.

**Comment by xiazen** [comment]
But `GlobalConfiguration` are going to be deprecated in 2.0, its settings will be break down into a collection of smaller options (Microsoft.Extensions.Options) .  Do you still think it is worthy to fix it?

**Comment by sergeybykov** [comment]
Since we are deprecating `GlobalConfiguration` in 2.0, it doesn't seem like a worthwhile effort to change it with regards to seed/primary nodes.
