### ISSUE TITLE
MSSql Orleans Table creation hangs

### ISSUE THREAD

**Issue by jake-bauer** [dotnet/orleans#3524]
I have pulled down and am attempting to execution the database creation statement for MSSQL and it is hanging. I am using SQL Server 2017 with a stock configuration. Before I killed it it ran for 45 minutes after I killed it I received the error message  `Msg 5069, Level 16, State 1, Line 1
ALTER DATABASE statement failed.
Msg 5069, Level 16, State 1, Line 1
ALTER DATABASE statement failed.`

**Comment by jake-bauer** [comment]
Upon some further investigation it appears that there may be an issue with how the optimistic locking is being configured at the start of the script, if executed with a database that already has tables in it.

**Comment by sergeybykov** [comment]
I wonder what @veikkoeeva thinks about this.

**Comment by veikkoeeva** [comment]
@jake-bauer, noticed this. This is what I commented to Gitter
> I tried with RC and didn't have a problem. The script tries to set the DB to snapshot isolation level that's a DB wide setting. It can be locked for a long period of time due to some obscure reasons sometimes. Are you repeteadly experiencing this problem?

I should have the latest SQL Server installed tomorrow and I can re-check. Your note about that alter statement indicates the snapshot setting is causing trouble. I don't think you should experience it repeteadly and in any case you can set it manually also. It's likely a blocking issue due to some reason.

**Comment by jake-bauer** [comment]
Restarting the sql server solved the problem for me
