### ISSUE TITLE
Microsoft.Orleans.ServiceFabric For .Net Core ?

### ISSUE THREAD

**Issue by hanxinimm** [dotnet/orleans#3604]
![image](https://user-images.githubusercontent.com/13499426/32063382-99a1fcac-baa9-11e7-8f59-546c85f9cae3.png)

**Comment by attilah** [comment]
The .Net Standard and .Net Core support just became available with [Service Fabric 6.0](https://blogs.msdn.microsoft.com/azureservicefabric/2017/09/25/service-fabric-6-0-release/) release.

Since the [NuGet packages](https://www.nuget.org/packages/Microsoft.ServiceFabric.Services/3.0.219-preview) are still in preview we did not move to it yet, but it will be considered to be aligned with our 2.0 release.

**Comment by sergeybykov** [comment]
From 2.0.0 on, we plan to publish updates to individual NuGet packages when needed without necessarily updating all of them at the same time every time. `Microsoft.Orleans.ServiceFabric` is a good candidate for that, as it can be updated with changes to its dependencies without touching the rest of the codebase.
