### ISSUE TITLE
Orleans takes the IDE006 problem

### ISSUE THREAD

**Issue by rocketRobin** [dotnet/orleans#3613]
# Orleans take the IDE006 problem # 
when I dev orleans ,my vs 2017 community can't intellisence , the `alt`+`enter` or `ctrl`+`.` not work , even can't help to generate imp of interface, can't compleate namespace ! 

this problem appera at my two PCs.
![default](https://user-images.githubusercontent.com/9987850/32130649-fc8e63a2-bbce-11e7-9128-a9a907887ed5.png)

**Comment by rocketRobin** [comment]
when i restart vs the problem gone, but why?

**Comment by jan-johansson-mr** [comment]
VS2017 causes some issues for me too (others than you describe), so I guess VS is still a little "rough" (I've given feedback to MS about the issues I hit, so I hope it can help MS strengthening VS further)...

**Comment by sergeybykov** [comment]
@rocketRobin Make sure you have the latest updates to VS installed. I suspect there isn't much we can do on the Orleans side here.

**Comment by attilah** [comment]
I see on the screenshot that you've updates (yellow flag), are you on the latest version of VS? I'm asking because their release cadence is pretty fast and it's worth to update to the latest stable release always.

With early versions of VS2017 we also had problems with intellisense and some around test code, but nothing now with the latest 15.4.1.

I think this issue is not Orleans related, so I am going to close it, if something Orleans + VS related comes up feel free to reopen it.

**Comment by rocketRobin** [comment]
Ok, thanks, I will try that.
