### ISSUE TITLE
Provide documentation for Orleans transactions

### ISSUE THREAD

**Issue by eisendle** [dotnet/orleans#3646]
Although Orleans transaction are announced in this [tweet](https://twitter.com/sergeybykov/status/923799065548038144) for the 2.0 release, there is no documentation about it. Would be nice to know how transactions are used in Orleans ;)

**Comment by ReubenBond** [comment]
Hi @eisendle, documentation for transactions is coming. In the meantime, you can find a description in this paper: https://www.microsoft.com/en-us/research/publication/transactions-distributed-actors-cloud-2/

The programming model has changed somewhat since the paper was published. The current best place to look for those changes is the transactions test code.

**Comment by ReubenBond** [comment]
For anyone who comes across this issue, a sample project demonstrating transactions was just merged: https://github.com/dotnet/orleans/pull/3653

**Comment by sergeybykov** [comment]
Initial documentation has been published to http://dotnet.github.io/orleans/Documentation/2.0/Transactions.html and a sample has been added. Both will evolve over time, of course. But I think there's enough to close this issue.

**Comment by ekalachev** [comment]
Hello guys! [Link](http://dotnet.github.io/orleans/Documentation/2.0/Transactions.html) to documentation doesn't work. Can you please update it?

**Comment by ReubenBond** [comment]
http://dotnet.github.io/orleans/Documentation/grains/transactions.html
