### ISSUE TITLE
Publish the TesterInternal as Nuget package

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#3657]
Hi,

same days ago I started to help maintaining the MongoDB provider for Orleans. Our goal is to publish a stable 1.0 as soon as possible and be ready when Orleans 2.0 RTM is out. 

We would like to improve our tests and I saw that TesterInternal provides a lot of useful base classes for writing provider tests.

Can you publish this project as  a Nuget package? I tried to copy the code and to add Orleans as a git submodule or building manually, but I had problems with all approaches.

**Comment by jdom** [comment]
Well, we already discussed a little bit over [Gitter](https://gitter.im/dotnet/orleans?at=5a049e8ff257ad910975015c), and apparently you got TesterInternal working for now.
You can even just copy the parts that you need from it in a project called the same, so that it has internals visible to it.
Having said all that, it should be temporary. Ideally we want to get to something like #2011 and have proper test kits.
We already started with a similar approach for new fetures, such as the Transactions extensibility points (for example see [GoldenPathTransactionManagerMemoryTests](https://github.com/dotnet/orleans/blob/8151d3e700ac6221f4cb1bde483cda4da0e108f5/test/Orleans.Transactions.Tests/Memory/GoldenPathTransactionManagerMemoryTests.cs), which just provides the set up but just inherits from a base class that has the functional tests.
We should do the same thing for stream and storage providers, and release them as separate nugets. It shouldn't be to difficult if you want to take a stab at extracting it for the MongoDb provider.
