### ISSUE TITLE
Orleans how to retrieve database timeout and implementation of eventually consisten.

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#3664]
Orleans how to retrieve database timeout and implementation of eventually consisten.

**Comment by sergeybykov** [comment]
Can you provide more details? It's not clear to me what you mean by the database timeout and what's the connection with eventual consistency.

**Comment by sundong1982** [comment]
A database operation timed out in grain，simple massage stream not to retrieve

**Comment by sergeybykov** [comment]
I don't believe there's a simple recipe for dealing with timeouts and retires. One tool we use is `.WithTimeout` extension method that allows to limit wait time for an async operation, so that it can be failed and retired. But retrying an operation that may or may not succeeded is tricky, unless the operation is idempotent.
