### ISSUE TITLE
Silo deadlocks when PubSubRendevousGrain is GC-ed in the same cycle with a Provider

### ISSUE THREAD

**Issue by ca-ta** [dotnet/orleans#378]
I've just stumbled upon this during testing:

Given a ```PubSubRendevousGrain``` grain **A**, managing stream **x** and another grain, **B**, publishing to stream **x**:

If **A** and **B** are deactivated during the same Orleans GC cycle, ```Catalog.CleanupStreams``` never returns. 
The silo hosting the grains deadlocks, further requests to grain **B** timeout and the silo eventually commits suicide.

One way to repro is to use the local silo, set the GC to 1 minute and craft a scenario where one subscribes to stream **x** and then immediately pushes an event to stream **x** from grain **B** (e.g. as a side-effect of calling a method on **B**). 

I haven't tested with a multi-silo scenario - I suspect the problem exists in that case as well.

Here's a relevant log excerpt (had to wait for the silo to die):
```
[...] Directory:
[...] 
++   [Activation: [...]*grn/5644FBDE/...@bfee5e85 #GrainType=TestGrain State=Deactivating NonReentrancyQueueSize=0 EnqueuedOnDispatcher=0 CurrentlyExecutingCount=0 NumRunning=0]
++   [Activation: [...]*grn/716E8E94/...@b77a5cbd #GrainType=Orleans.Streams.PubSubRendezvousGrain State=Deactivating NonReentrancyQueueSize=1 EnqueuedOnDispatcher=0 CurrentlyExecutingCount=0 NumRunning=0]   Messages queued within ActivationData: [Request [...]*grn/5644FBDE/...@bfee5e85->[...]*grn/716E8E94/...@b77a5cbd #185: Orleans.Streams.Orleans.Streams.IPubSubRendezvousGrain:UnregisterProducer()]

[...]	
```

While battling the above, I've wondered if there is an reasonable way in place for testing this type of activation/deactivation scenarios. Ideally we'd have a way to manually GC a known set of grains during testing - and also to set short timeouts for the deactivation operation. I haven't dug through all the tests/test harnesses in detail - please let me know if such facilities exists and I've missed them.

**Comment by gabikliot** [comment]
I will be looking into this,. 
One clarification: are you sure it causes silo to commits suicide? Even if there is a deadlock between grains, silo by itself should not have been impacted. Is it possible that just your test is finished/ request timeouts and throws and the test is exiting because of that and as a result silo is just stopping?

As for how to test GC: definitely we have ways to do that. You can both configure GC per grain type and also use DeactivateOnIdle. http://dotnet.github.io/orleans/Advanced-Concepts/Activation-Garbage-Collection.

If you have a stable short repro, with this issue only, it would be great!

**Comment by ca-ta** [comment]
Thanks!

The issue seems to be that the deadlock occurs during the deactivation cycle - the deactivation cycle never finishes, and that seems to throw a big wrench into the silo. That's about all I've got, unfortunately - I don't know enough about that part of the code to speculate further.

I do not have an isolated repro (I run everything in the Azure emulator), but I suppose I can concoct one. 

Regarding the GC configuration:
* Yes, I am aware of the ```AgeLimit``` settings - that's how I stumbled upon the issue - I set the GC to 1 minute just to verify how the system I'm building behaves in the face of a large number of grain activations/deactivations. Imagine my panic when it all ground to a halt... :-)

Regarding GC testing: I was wondering if it would be possible - for testing purposes only - add facilities to:
* instruct the silo to deactivate all grains (or all grains of certain types) during the next GC cycle.
* trigger a GC cycle on-demand 

I am suggesting this because, currently, one cannot create quick-running (unit) tests that can reproduce bugs in this class. Something like the above could allow us to run these kind of tests faster (and hence more frequently).

**Comment by gabikliot** [comment]
I will look into how to allow easier GC testing. Just triggering the cycle is easy. We have TestHookups class in the silo that can be used to call into internals. The hard part about this particular case is that the Activation GC data structure is organized based on time, so just triggering and attempting next cycle would not actually collect it. One needs to "advance the time" or start messing up with the internals of  this data structure, which is of course undesirable, since it has a danger of introducing a bug. I will think if there is some trick to solve it easily.

**Comment by ca-ta** [comment]
Cool! I agree that changing the GC is not something to be taken lightly, hence my asking for your help.

speaking of which: I have a reliable repro,  implemented within the existing test harness.
You'll have to wait three minutes (and may want to wait some more for the silo to crash), but hey... :-)

I'll submit a PR shortly.

**Comment by gabikliot** [comment]
Wanted to give heads up: I have the fix fully implemented, testing it more thoroughly now and will push later on.

**Comment by ca-ta** [comment]
@gabikliot:  Awesome - can't wait to see the fix (and get a better understanding of the fault scenario)

**Comment by gabikliot** [comment]
Fixed via https://github.com/dotnet/orleans/pull/399.

So the issue was related to one grain calling another grain inside it OnDeactivateAsync and how we deactivate grains when they are GCed.
When we decide to GC a grain, we first put it in Deactivating state, which essentially says: this grain is locked for any future requests until it is fully deactivated. If it receives a request, the request is queued and forwarded to the new activation of this grain only after this activation is fully deactivated (that is what guarantees that we only have one activation).
As part of the deactivation process we call OnDeactivateAsync on all deactivating grains. Since we don’t allow any requests into a grain until fully deactivated, it means OnDeactivateAsync is non reentrant (even if the grain itself is reentrant).
Now if grain A sends a msg to grain B inside its OnDeactivateAsync and B is also deactivating now, this msg cannot be delivered to B until B is done deactivating, and thus the call in A cannot be finished until B is deactivated, and this means OnDeactivateAsync on A cannot finish until B is fully deactivated.

The bug was that we were calling all OnDeactivateAsync on all currently deactivating grains in parallel (that part is OK), but then joining all tasks and awaiting them all. That means B cannot finish its deactivation until A finishes its OnDeactivateAsync. Deadlock!

Now, this is actually only a temporal deadlock. All calls in Orleans, without exclusion, have a guaranteed time-out, so once A’s call to B times out, usually after 30 sec, A’s OnDeactivateAsync is unblocked, maybe throws but that is OK, both A and B now finish their OnDeactivateAsync and we proceed, finishing the deactivation. The call from A to B is still queued and later forwarded to the new activation of B and is received.
So everything recovers, both grains and of course silo itself is in no way impacted.
But in your case you also set the timeout to 1hour, so both grain were locked for 1 hour. 

The fix I did was very simple: we call OnDeactiavateAsync in parallel, but don’t await them all, process them as they finish and this allows B to finish its deactivation. Now A’s call is forwarded to the new activation of B, A finishes its OnDeactiavateAsync and completes deactivation.

Another part was that actually none of your application grains were doing anything in the OnDeactiavateAsync. This part was specific for streaming: for stream producer grains we have a code that runs like as if it was called from  OnDeactiavateAsync. It essentially does  cleanup from pub sub. This is just a curtesy, even if this call never happens  or times outs, all works fine. We will have some garbage in the pub sub and later on clean it up through other ways./So there was no visible impact on the application semantics. But the grain was indeed blocked for the timeout duration.


This was a really cool bug. Thanks for finding and reporting it!

**Comment by ca-ta** [comment]
@gabikliot: Gabi, thanks for the fix and thorough explanation!

Indeed, my primary concern was that the grain does indeed end up being locked for the duration of the timeout - I thought this should not happen during normal silo operation, if at all possible.

**Comment by gabikliot** [comment]
For reentrant grains this is the case - grain does indeed never end up being locked, except for `OnActivateAsync` and `OnDeactivateAsync`. Those two, by their definition as being part of the activation lifecycle, are non reentrant. 
And for non reentrant grains it is true for all (non reentrant) methods.
Any non reentrant method can potentially block for the duration of the timeout.
