### ISSUE TITLE
Codegen is generating code for AspNetCore types

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#3786]
After update to beta2 today, one of my projects fail to build because codegen is generating code for some AspNet types. 

![image](https://user-images.githubusercontent.com/4714040/33900354-444e5680-df55-11e7-9b04-7f3a93892366.png)

I tried to remove obj/ and bin/ and rebuild but got the same problem.

It may be related to #3771

**Comment by ReubenBond** [comment]
@galvesribeiro could you give me build output text when your csproj has `<OrleansCodeGenLogLevel>Trace</OrleansCodeGenLogLevel>`?

**Comment by galvesribeiro** [comment]
Sent on Gitter @ReubenBond.

**Comment by ReubenBond** [comment]
Thanks @galvesribeiro. I see the issue and I'll try to fix it today.

Issue is that our 'backing field to auto property' heuristic is not checking for an exact type match between field and property, so when the subclass overrides a base property (`public new string Prop`), it may have a type mismatch. See the MVC ControllerContext code here: https://github.com/aspnet/Mvc/blob/7e26af908ef068407961479d21539079f5ffadfb/src/Microsoft.AspNetCore.Mvc.Core/ControllerContext.cs#L47

Meanwhile, this should be alleviated with the fix for #3771.

**Comment by galvesribeiro** [comment]
Thanks @ReubenBond! Looking forward to get the updated packages.
