### ISSUE TITLE
What is the difference between AddAzureQueueStreamProvider and AddAzureQueueStreamProviderV2?

### ISSUE THREAD

**Issue by Kimserey** [dotnet/orleans#3812]
In Orleans.Streaming.AzureStorage, there are 2 confusing extensions:

- AddAzureQueueStreamProvider
- AddAzureQueueStreamProviderV2

What are the differences? Is V2 superseding the other one? If I just start to use Orleans Stream, should I use V2?

**Comment by jason-bragg** [comment]
The serialization of messages in azure stream provider initially used the fallback serializer, and hence couldn't take advantage of serialization features provided by our custom serialization.  This was, in a way, a bug as we'd intended it to use our custom serialization.  We could not simply 'fix' the bug, however, because it was already in use in many production environments, which would break if we changed the serialization format.

Instead, we refactored the provider to support a plugable data adapter responsible for serialization, so the old format could continue to be supported, a new 'fixed' serialization could be introduced, and user defined serialization could be used.

Version 2 use a data adapter which uses generated seriazers, as was originally intended.

It should be noted that this was an issue because our serialization does not support versioning or format changes, and this is still the case.  If you expect to make changes to your streamed data over time, you may want to consider developing your own data adapter to control and version the data as needed.
