### ISSUE TITLE
Orleans x Service Fabric

### ISSUE THREAD

**Issue by mvbaffa** [dotnet/orleans#384]
Hi,

Reading about Service Fabric in the Azure web site it seemed to that this is a similar to Orleans.

Read This: http://azure.microsoft.com/en-us/documentation/articles/service-fabric-reliable-actors-introduction/

What is the real difference between them ?

Thanks in advance

**Comment by gabikliot** [comment]
Hi

Service Fabric Actors is **another implementation of the virtual actor model pioneered by Orleans**, with different tradeoffs. 

There are 4 major differences:
1) Orleans is **open source** while SF is not.
2) Orleans **can run anywhere** where .NET 4.5 can run and is not tight to any hosting fabric, while SF Actors are tightly coupled with SF. For example, there is a demand to make Orleans CoreCLR compatible (https://github.com/dotnet/orleans/issues/29#issuecomment-97694888 and https://github.com/dotnet/orleans/issues/368). We expect that to be a very modest amount of effort. Orleans silos can also easily run as a SF stateless service, as has been demonstrated by @ReubenBond .
3) Orleans have been **running in production since 2011** and powering some major services within Microsoft. SF actors is a new implementation (as opposite to the Service Fabric itself).
4) Orleans and SF have made a number of **different tradeoffs** w.r.t. to a number of runtime issues, such as consistency/availability and more, although the documentation is a little light on some of that kind of details: http://azure.microsoft.com/en-gb/documentation/articles/service-fabric-reliable-actors-introduction/.

**Comment by mvbaffa** [comment]
I have discovered now that Service Fabric does not run on Windows 7.

I will be implementing a new application and I would like decide which option to use: Orleans or Service Fabric.

My doubt is if Microsoft will maintain both.

Thanks

**Comment by ashkan-saeedi-mazdeh** [comment]
Disclaimer I'm a game developer and game development tools developer by profession and only worked on Orleans stuff from the manual and has been interested in concepts related to distributed programming as a hobby/general interest. I've known and followed Erlang and found out about Orleans later on when MS published the first papers about it.


As a few examples of tradeoffs. 
- SF acotrs save all state after each method call but Orleans puts the control in hands of the developer.
- At least for now the storage providers for SF are limited (Maybe I'm wrong and new storage providers can be easily created and added to the SF hosting environment).
- Interleaving calls in Orleans are possible but it doesn't seem to be the case for SF acotrs.
- I am not sure but it seems Orleans concepts of streams are not directly included in SF actors.
- Orleans on the other hand is not specific to a hosting environment so doesn't have by default any of the upgrading and autoscaling properties of SF hosting environment, however as @gabikliot said, @ReubenBond created an Orleans setup as a stateless service.

**Comment by ReubenBond** [comment]
> At least for now the storage providers for SF are limited (Maybe I'm wrong and new storage providers can be easily created and added to the SF hosting environment).

You can create your own using an API similar to Orleans.

**Comment by richorama** [comment]
I thought I saw somewhere in the SF documentation that you can enable
re-entrancy for actors, so interleaving is supported.

**Comment by ashkan-saeedi-mazdeh** [comment]
Sorry guys for the inaccurate info. I should investigate more before posting the next time. I suddenly felt the urge to clearify things a bit , I read much about Orleans and played with it but did not investigate the SF too much.

**Comment by mvbaffa** [comment]
Hi,

As I told you I need some assistance to decide which one I will choose. You that have much more experience in Orleans could help me in some questions:

1) Can I deploy Orleans Actors on Promise;
2) Can I embed Orleans in a Windows Service. That is can I deploy my actors on Premise and embed my Orleans host;
3) I am not an expert in Erlang but I have developed some prototypes:
    . How can spawn worker processes (actors) in Orleans;
    . How Can control and monitor the lifecicle of my workers;
    . How can I develop a supervisor of my processes (actors) for fault monitoring (very important);
    . Is there a Finite State Machine in Orleans, if not which library are you using.

Thanks in advance

**Comment by gabikliot** [comment]
1) yes, of course you can deploy Orleans Actors on Premises. See http://dotnet.github.io/orleans/Step-by-step-Tutorials/On-Premise-Deployment
2) Yes, you can embed Orleans in a Windows Service. Orleans is just a .NET library. So just like you can embed any .NET code as Windows Service, you can do the same with Orleans. https://github.com/dotnet/orleans/blob/master/src/OrleansHost/WindowsServerHost.cs is how to start  Orleans as Windows process. You can embed that as Windows Service.
3) I am not an expert in Erlang either.
a) you don't directly spawn actors in Orleans. You don't directly create them. Instead we have a  different concept of Virtual Actors, when we create them. You can read about it in our paper: http://research.microsoft.com/apps/pubs/default.aspx?id=210931. This greatly simplifies the programming, as you don't need to deal with a lot of issue that the runtime is doing for you now.
b) actor controls its own lifecycle. 
c) We don't have a build in supervision model. It is not necessary with Virtual actors, since the runtime now provides reliability of actors, not the supervising code. One can still build a supervision hierarchy if he wants, by himself, based on actors and periodic heartbeats between actors or other way. We can discuss it in more details. But the main point is: you might not need to.
d) There is no Finite State Machine in Orleans. You can use what ever .NET library you can find.

Please notice that the last 2 points about  supervision model and Finite State Machine do not belong to this issue. This is about Erlang vs. Orleans, not Fabric Actor vs. Orleans. Fabric Actor are based on Orleans's Virtual Actor model and thus also do not have supervision model. As far as I know they also don't have Finite State Machine.

Gabi

**Comment by mvbaffa** [comment]
Thank you very much it was important to me you information.

**Comment by gabikliot** [comment]
Another important difference between Orleans and Fabric Actors is support for streaming, provided in Orleans via [Orleans-Streams](http://dotnet.github.io/orleans/Orleans-Streams/) and is not (at least currently) present in Fabric Actors.

**Comment by gabikliot** [comment]
It is also important to note that an-unchanged Orleans application could be hosted as a service on Service Fabric. In such a setup one can take benefit from Service Fabric hosting and management capabilities, without compromising any of Orleans' features.
See more details [here](https://www.youtube.com/watch?v=w__D7gnqeZ0&feature=youtu.be).

**Comment by SiqiLu** [comment]
@ReubenBond 

> > At least for now the storage providers for SF are limited (Maybe I'm wrong and new storage providers can be easily created and added to the SF hosting environment).

> You can create your own using an API similar to Orleans.

I read many documents about Service Fabric, but found nothing about create storage providers for SF. Could you please give some information about custom storage providers? Thanks.

**Comment by ReubenBond** [comment]
@SiqiLu just so I'm clear, are you asking about how to create a state provider for Service Fabric Reliable Actors, or Orleans? If the former, then you need to implement [IActorStateProvider](https://msdn.microsoft.com/en-us/library/azure/microsoft.servicefabric.actors.runtime.iactorstateprovider_methods.aspx) if the latter, then you need to implement [IStorageProvider](http://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Grain-Persistence.html).

**Comment by SiqiLu** [comment]
@ReubenBond Thank you a lot. I want to know how to create a state provider for Service Fabric, But could not find any documents about that. But how to config the IActorStateProvider to the Service Fabric runtime?

**Comment by sergeybykov** [comment]
>But how to config the IActorStateProvider to the Service Fabric runtime?

This is a question that belongs in the Service Fabric docs/forum.

**Comment by SiqiLu** [comment]
Yes. I am sorry about this.

**Comment by sergeybykov** [comment]
@SiqiLu No problem at all.

**Comment by gabikliot** [comment]
Orleans has been integrated and can now run on Service Fabric (#2542), hosting Orleans silo as Service Fabric stateless service.
