### ISSUE TITLE
【2.0.0-beta3】When the invalid Silo exists in Consul, other SiloHost will be reported to be wrong in startup

### ISSUE THREAD

**Issue by LuceLuo** [dotnet/orleans#3906]
![tim 20180125183508](https://user-images.githubusercontent.com/8308243/35383995-e7ee81cc-01fe-11e8-8576-31ccf13c277a.png)
![tim 20180125183416](https://user-images.githubusercontent.com/8308243/35383999-ea87006c-01fe-11e8-9c01-2db504e1fee5.png)

**Comment by sergeybykov** [comment]
This behavior is by design - the newly started silo is trying (be default) to validate that it can open TCP sockets to all silos already listed in the cluster. Since the invalid entry lists an existing silo as `Active` (3), the starting silo is trying and failing to connect to it, assumes it being its own fault, and exits.

It will stop trying to validate connectivity to the invalid entry silo after the entry expires - in `GlobalConfiguration.IAmAliveTablePublishTimeout` x `GlobalConfiguration.NumMissedTableIAmAliveLimit`. By default that's 5m x 2 = 10 minutes.

You can turn off the startup connectivity validation by setting `GlobalConfiguration.ValidateInitialConnectivity` to `false`.

**Comment by LuceLuo** [comment]
@sergeybykov 

Thank you for your reply. Now Silo is ready to start, but Client will still connect the failed Silo. What configuration do we need to add on the Cilent side?

At present, the port of Silo is random, and each start port will be different. Should a fixed port be used?

I think Orleans should be the function of eliminating invalid Silo, but the invalid Silo is not removed. Is it not right for me to use it?

![tim 20180129102246](https://user-images.githubusercontent.com/8308243/35491079-4d742438-04df-11e8-9895-694492ea503e.png)

**Comment by sergeybykov** [comment]
>Now Silo is ready to start, but Client will still connect the failed Silo. What configuration do we need to add on the Cilent side?

Client should automatically blacklist the failed silo (gateway) and continue to use the remaining ones. No additional configuration is needed.

>I think Orleans should be the function of eliminating invalid Silo, but the invalid Silo is not removed.

Silos that continue to run in the cluster should vote the failed one dead within (by default) 30 seconds after its failure. Is that not what you are seeing? The detection time can be [configured to be shorter](http://dotnet.github.io/orleans/Documentation/Runtime-Implementation-Details/Cluster-Management.html).

**Comment by LuceLuo** [comment]
@sergeybykov 

- Maybe the way I wrote is not right, so it can't start. I think we should join the retry mechanism. If the client needs to try several times later, will he add the invalid silo to the blacklist?

- I did not open multiple silo when I was testing, is this the reason that the invalid silo has not been removed?
