### ISSUE TITLE
Log string formatting cleanup

### ISSUE THREAD

**Issue by veikkoeeva** [dotnet/orleans#395]
There has been cleanup of codebase lately as evidenced by [recently closed PRs](https://github.com/dotnet/orleans/pulls?q=is%3Apr+is%3Aclosed).

In the same vein, I propose definding and making use [IFormatter/ICustomFormatter classes](https://msdn.microsoft.com/en-us/library/system.icustomformatter.format%28v=vs.110%29.aspx). Specifically there are a few places where strings are formatted for printing or other consumption, like in [Utils](https://github.com/dotnet/orleans/blob/master/src/Orleans/Utils/Utils.cs) or otherwise scattered around where typically looking like [this](https://github.com/dotnet/orleans/blob/master/src/Orleans/AzureUtils/AzureTableDataManager.cs#L220).

It apperas using an Orleans specific formatter would make the code more concise and printing more uniform while at the same time offering further formatting options should such a need arise. Perhaps opening possibilities for minor optimizations (less allocations?) and further string interpolation in C# 6.0 (just a guess).

As for an example, I have introduce one that prints amongst other things null values and dates (to database, this feature is not ready yet) [here](https://github.com/dotnet/orleans/blob/a64fa8953e764ac391ebd549d395ac66374b545f/src/OrleansSQLUtils/Storage/SqlFormatProvider.cs) (- edit fixed link on 2015-12-17).

**Comment by gabikliot** [comment]
Sounds like a good idea to me.

**Comment by amccool** [comment]
Has the use of System.Diagnostics.Tracing.EventSource been ruled out?  And/Or does System.Diagnostics.TraceSource have a place at the table.  Leveraging Trace with all the available TraceListeners makes for a more configurable diagnostic experience.  But getting all that data in a single string is overwhelming.   Example, at least for exceptions it would be good to be able to put the exception title in the message and place the stacktrace into the data.

**Comment by sergeybykov** [comment]
The approach so far has been that one can create a class that implements `ILogConsumer` and redirects the output to `System.Diagnostics.Tracing.EventSource`, and registers it by adding it to `TraceLogger.LogConsumers`.

This was done before `System.Diagnostics.Tracing.EventSource` was even publicly available. Maybe now it's time to rethink this, and add a built-in listener for it enabled by default.

**Comment by jdom** [comment]
Sorry about reviving this old thread, but at some point I would also like to have a more semantic way of producing logs. If you have a flat API and then implement a LogConsumer that implements EventSource, you already lost a lot of the richness and fidelity of the event and its payload, so there is not a lot of value in using EventSource (other than to send it to the same sinks as the logs in the rest of your app, but mainly as a flat concatenated string).

If you start from the other end, and have a strongly typed and rich way of "producing" the log events, you can later on decide to flatten it to a text representation, but you don't have to if you don't want to (such as you could be using Azure Tables and having each payload argument as a different column).

**Comment by veikkoeeva** [comment]
@jdom You have a point here. I remember from the very early days some issue where it was discussed if the log message should have more structure. In the context of this specific issue, it could mean some of the sinks use a common formatter.

To get more concrete, on top of my head, something like (comparison semantics and immutability omitted):

    public struct LogMessage
    {
        public int Code; //Some code that identifier the message.
        public int Severity; //Is this needed or decided by by sink from the Code?
        public string Source; //This could be set dynamically or [CallerMemberName] + [CallerLineNumber].
        public string Message; //The message. An exception stack too or should this have a field for it?
    }

Then some helper method, which might be sink specific (or they can reuse the same one) that can determine from `Code` if this is an error message or not and what would be the severity. Orleans would put all messages to a common sink, where specific loggers are registered to handle them. Maybe an arrangement would help debugging too when the call stack is available. I don't know, writing from a mobile, hope this makes sense. :)

**Comment by jdom** [comment]
hmmm, I think I'm not talking about strongly typing the TraceSource approach (but still inherently use strings as messages). I'm talking about semantic logging, either using `EventSource` or a similar approach, where the log producer (app logic) instead of doing this:

```log.WriteVerbose(333, "Client with ID {0} said '{1}'", clientId, message[.ToString()])```

they would do:

```log.ClientSaidSomething(client, message)```

Then it's up to the implementation to define the eventId, severity, how to flatten the payload depending on the sink, polish the friendly message by having a central location to make it's easier to enforce consistency, allow sampling, etc.

Then if you want a flat text file, you can have it without extra effort, but if you want something richer, such as sending to azure tables (and having dynamic columns), or sending to Splunk, Loggly, ElasticSearch, you can do that without loosing important metadata (such as the argument names to be able to query by them).

**Comment by veikkoeeva** [comment]
@jdom I'd make `ClientSaidSomething` as an extension method or something to that effect, which would then create `LogMessage` for further consumption. Might not be necessary. I don't have a strong opinion except that it looks like we share an idea of cleaning up logging.

**Comment by jdom** [comment]
The point is to disallow flattening of the message early to fit into a `LogMessage`, because some log sinks might need the extra richness. Unless of course if the LogMessage has a lot of metadata about it such as the parameter names and not just the values, but why reinvent the wheel and instead have a defined schema such as when using [EventSource](https://msdn.microsoft.com/en-us/library/system.diagnostics.tracing.eventsource(v=vs.110).aspx) or similar, that avoids the perf hit of having a completely dynamic schema and paying the price in each occurrence of the event.

**Comment by ReubenBond** [comment]
I believe this is complete to a satisfactory degree.
