### ISSUE TITLE
Orleans Templates (announcement)

### ISSUE THREAD

**Issue by nehmebilal** [dotnet/orleans#397]
Hi all,

Just to let the community know that we (**Microsoft BigPark Studios**) just published [OrleansTemplates](https://github.com/OrleansContrib/OrleansTemplates) to [OrleansContrib](https://github.com/OrleansContrib). 

*OrleansTemplates* is a Visual Studio solution template that contains projects for Grains, GrainInterfaces, Local Silo and REST Api. It supports placing **ASP.NET routing** attributes **directly** on the Grain Interface and generates (using Roslyn) the corresponding **Web API** for it. It also offers other attributes that you can place on the Grain interface or implementation to save you from writing boiler-plate code.

Please take a look at [OrleansTemplates](https://github.com/OrleansContrib/OrleansTemplates) and open an issue **there** if you have any questions.

Best,
Nehme

**Comment by gabikliot** [comment]
Thank you @nehmebilal !
This was a great contribution by **Microsoft BigPark Studios**.

**Comment by ashkan-saeedi-mazdeh** [comment]
@nehmebilal  It's a great initiative which makes it easy to test Orleans in the environments which an Orleans client is not available and also for rapid development of real applications because at the end it will be needed for every project to only expose a subset of the grains and grain methods for public consumption as a service and who likes to write boiler-plate code.

You guys rock!!!
