### ISSUE TITLE
Orleans and Project Horton

### ISSUE THREAD

**Issue by HornerGrahame** [dotnet/orleans#398]
I understand that project Horton will allow the developer to execute linq queries over the graph; could you please give an update to the status of this project and if the team/Microsoft are looking to open source Horton?

**Comment by gabikliot** [comment]
Horton project does not allow to execute linq queries over the graph. It allows to execute **regular language expression queries** over the graph. Its not the same as linq, but there are a lot of similarities.
Regular language expression are path patterns over the graph and Horton matches those patterns to the graph data and returns all matching paths. See some examples here:
http://research.microsoft.com/pubs/162643/icde12_demo_679.pdf

We are not currently doing any further development of Horton. It was essentially our first big application on Orleans years ago and since then we got enough customers with their services so we stopped investing in Horton.
We still have the code and it is mostly operational on Orleans. We have not decided yet about open sourcing it or not.

**Comment by HornerGrahame** [comment]
Thanks for the update; so if Horton is not a live project and is not at present planed to be released or Open Sourced, is Project Trinity is active as they seem on the face of it to match well if Orleans distributed actor/graph model?

**Comment by gabikliot** [comment]
I was following project Trinity closely a couple of years ago, when we were working on Horton, but I can't tell if it is active now or not. You better ask them.
