### ISSUE TITLE
Writer/Reader Pattern (and the problems therein)

### ISSUE THREAD

**Issue by berdon** [dotnet/orleans#4062]
In doing some performance optimization we ended up having a grain that was hit often for both state updates and state reads. In order to reduce contention and handle the load we separated the grain into a writer grain and a reader grain.

## Writer Grain
* The writer grain receives updates as normal and marks a dirty flag and an update flag
* The writer grain uses a Timer to periodically writes to storage (WriteStateAsync) if the dirty flag is set (clearing the dirty flag)
* The writer grain uses a Timer to periodically update observing Reader Grains of updates if the update flag is set (clearing the update flag)

## Reader Grains
* Reader grains subscribe to state updates from the Writer grain rather than polling to reduce constant call overhead
* Reader grains are marked as Reentrant as their state can only be written via a single entity
* Reader grains are marked as :bomb: StatelessWorkers :bomb: to take advantage of local-placement and silo based scaling

The only issue with this pattern is that StatelessWorkers subscribing to an observer don't receive updates as someone outside of the inner workings of Orleans might expect. Only one IGrainObserver is tracked by the SubscriptionManager and thus only one worker receives the updates.

In chatting with Sergey I've thought of a couple of potential work-a-rounds.
* Randomly select an integer 0-X as a primary key when accessing a Reader Grain
* Poll for state updates in the stateless workers

The first will work but it feels hacky. It almost feels like "recreating" stateless workers in a way. Additionally, this won't allow for leveraging local placement to avoid silo hopping. The second will also work, depending on getting each stateless worker spun up and polling but I'm worried about the congestion caused by each worker constantly polling the writer grain.

**Comment by veikkoeeva** [comment]
This seem to crop up in closely related patterns. I cross-reference (even if not worded for this exact scenario/solution proposal): https://github.com/dotnet/orleans/issues/446, https://github.com/dotnet/orleans/issues/447, https://github.com/dotnet/orleans/issues/610 and recently https://github.com/dotnet/orleans/issues/3841 and some other linked from these discussions.

It looks like this pattern is a common one (I simplify):
1. Observe state change (user initiate, system initiated).
2. Distribute the change to relevant parties efficiently, by pushing.
3. Do updates via a manager so state is appropriately persisted.

**Comment by galvesribeiro** [comment]
@veikkoeeva that approach would bring the bottleneck to the `manager` from item 3.

In a particular project I'm using EventStore as my storage for an EventSourcing grain. The events are write/append-only on that grain. Whenever the internal state changes, a message is published to a stream and all interested parties can update their state about it. That follow the concept of projections where multiple grains can have different shapes of the same data. Besides that, I have a CosmosDB storage that persist some queriable/flat representation of that projection and a Stateless worker that does only queries against that CosmosDB collection.

I didn't saw performance problems for our use case but, you have 2 issues that you may consider when doing that approach:

1. Make sure the stream provider you use to publish messages of the projection is reliable. Otherwise, you will miss update messages and your read-only storage will be outdated.
2. You must be tolerant to eventually consistent nature of this solution. As you are relying on an async message (the projections stream message) to update the read-only storage, you may lag behind depending on your architecture.

If you cover 1 and are ok with 2, you will have a reliable scenario which is kind of CQRS/ES.

**Comment by berdon** [comment]
@veikkoeeva Those are good links - especially @jason-bragg's [comment](https://github.com/dotnet/orleans/issues/3841#issuecomment-356701195). I wonder how one might make that apply when dealing with a single writer grain on one silo when wanting DI access across all silos to the updating cache object? You'd still need to somehow sync the object across silos.

**Comment by DarkCow** [comment]
I've removed all my observers and replaced with streams for this reason. If observers didn't exist in Orleans I wouldn't particular miss em.

To sync the objects across, you use explicit stream subscription on each stateless worker to a known broadcast streamID/stream namespace... Perhaps Guid.Empty/typeof( MyObject ).Full name

Then the writer grain calls OnNext with his object...

**Comment by Arshia001** [comment]
@berdon control commands are the way I ultimately chose to publish the updates (as you can see from #3841). Is this setup somehow inappropriate for your needs? If it is, why?

**Comment by sergeybykov** [comment]
Jumping late to this thread. One way to think about `[StatelessWorker]` is that they are auto-scalable functions. They are not remotely and individually addressable. That makes them bad candidates for stateful logic even tough they can hold some state in memory.

>In chatting with Sergey I've thought of a couple of potential work-a-rounds.
Randomly select an integer 0-X as a primary key when accessing a Reader Grain
Poll for state updates in the stateless workers
The first will work but it feels hacky. It almost feels like "recreating" stateless workers in a way. Additionally, this won't allow for leveraging local placement to avoid silo hopping

The popular pattern I was suggesting here is Grain Pool. In it we use N normal grains and pick one of them (randomly, round-robin, etc.) for each request via a simple "façade" function. Unlike `[StatelessWorker]` grains, these grains are individually and remotely addressable, and hence can subscribe for updates easily.

Placement is an orthogonal concern. By marking the reader grain class with `[PreferLocalPlacement]` we can achieve pretty good initially locality. A custom placement director is a more advanced option, but I'm not sure if it would really be needed.
