### ISSUE TITLE
oAuth permission required to download nightlies

### ISSUE THREAD

**Issue by ghuntley** [dotnet/orleans#409]
Accessing either of the two links referenced in the README.MD to download nightlies as a non-MSFT employee/ non-orleans team member results in the following workflow + error:

![oauth](https://cloud.githubusercontent.com/assets/127353/7585657/597be1e0-f8e8-11e4-824b-ce00a95efdcc.png)
![error](https://cloud.githubusercontent.com/assets/127353/7585659/5c4df91c-f8e8-11e4-8b6d-9bd2978afd40.png)

**Comment by gabikliot** [comment]
@richlander , @mmitche , any idea how I fix that? I though everyone would have access to: http://dotnet-ci.cloudapp.net/job/dotnet_orleans/ws/Binaries/Release/.
Thanks!

**Comment by mmitche** [comment]
@gabikliot Sorry I totally missed this.  Let me check into it.

**Comment by mmitche** [comment]
I think what you want is archival of artifacts.  That's accessing the node itself.  What needs to be archived?  Everything under Binaries?

**Comment by jthelin** [comment]
Yes, Binaries directory tree.

**Comment by mmitche** [comment]
Okay, I'm setting it up to upload publicly accessible artifacts to Azure storage.  This is vs. storing on dotnet-ci, which I'm starting to switch away from where available to save space.  There is also an option to download all artifacts in a zip file.

http://dotnet-ci.cloudapp.net/job/dotnet_orleans/

Right now I have it set up so that it uploads the artifacts under a virtual path that includes the build number (this means it will keep archives of more than one build).  This might mean that downloading artifacts programatically is a tad more difficult, since you'll need to know the last stable/successful build:

http://dotnet-ci.cloudapp.net/job/dotnet_orleans/lastStableBuild/buildNumber

My intention is eventually to make the build number transparent when dealing with artifacts (like it is for traditional artifact upload).  If the above process is a problem, let me know and I can switch you back to traditional storage.

**Comment by gabikliot** [comment]
Sounds good. Thank you @mmitche !

**Comment by jthelin** [comment]
Cool. Thanks @mmitche 

@ghuntley -- I updated the ReadMe doc to point to the new build archive location, and so build drops should be open access now. :)
http://dotnet-ci.cloudapp.net/job/dotnet_orleans/lastStableBuild/Azure/

**Comment by gabikliot** [comment]
Great!
Thanks Jorgen and Matt!
