### ISSUE TITLE
One-Box Deployment Scenarios

### ISSUE THREAD

**Issue by jthelin** [dotnet/orleans#411]
Transferring the discussion about One-Box deployment scenario from #408 

@veikkoeeva Wrote:

The scenario I have in mind is to run "cluster" locally. I'll get to the point later, but allow me to take a bit of your time and paint scene.

An example project could be two servers with Windows Services and whatnot, two web frontends and then an Orleans system of say, three silos. Having this working on a single developer machine by simply pressing F5 will allow even more novice developers form a picture how the overall system is supposed to interact with its constituent pieces and mocked integration points. It's easy to draw a A4 sized poster having nice pictures and then mapping the projects to appropriate nodes (e.g. a deployment diagram). Arrangement such as this allows also [exploratory testing](https://en.wikipedia.org/wiki/Exploratory_testing), real testers, do testing "real time" (not only hitting the system on sprint late or something like that). For instance, every time feature branch hits master, a tester can either continue testing with the local version or pull the newest from origin master.

Maybe less rational idea is that it's nice to _feel the system_. That is, it's not just tests running occasionally or dumping something to servers (in enterprise setting, access to servers isn't granted), but when developing the front-end, one could have the silos and others systems up (on one's leisure) and debug the web front-end against "a live system". The "feel the system" here, while not real servers, relays some feel of how the topology fits together and how the grains and other parts work together and that knowledge is to some extent transferable to reasoning the real system too.

One could run something like [chaos monkey](http://techblog.netflix.com/2010/12/5-lessons-weve-learned-using-aws.html) (heh, this is a bit like the colocation mentioned in the blog post) during a coffee break with coworkes just for the fun of it and observe the system and see it should be doing what planned. Part of the "feel the system" is feeding into human curiosity and pattern recognizer mind to spot what has not been thought about and make a good use of debugger that is readily available if something unexpected happens (as it will).

I noticed [OrleansHostWrapper](https://github.com/dotnet/orleans/blob/5e964005d0cb88f38f30123ba079ddb46513adbf/src/OrleansVSTools/VSProjectSiloHost/OrleansHostWrapper.cs) while developing my [gist](https://gist.github.com/veikkoeeva/4414609e828375c898f3), but I don't wish the wrapper to bundle an arguments parser (I'd prefer something like [UnionArgParser](https://nessos.github.io/UnionArgParser/tutorial.html) in any event) and whatnot together. I'd like to be a bare-bones cluster manager I can run both in my testing project (with the framework of my choice) as easily as in my gist. Moreover, I'd like to be able to shut down, restart and add silos at my leisure. Easy configurability and the possibility to decide if running in the same process or even in separate processes (this might have production usage too). My gist has some problems in that I'll change the naming stuff, redo a bit about the [configuration part](https://gist.github.com/veikkoeeva/4414609e828375c898f3#file-gistfile1-fs-L93) and many other things. One issue is that I may want to run an Orleans cluster in a console application (or more likely with [TopShelf](http://topshelf-project.com/)) in a faul-tolerant style when I get the SQL server part done. My hunch is that it should be nearly as fast as in-memory system.

Arranging a projects like this has worked rather well, at least in the projects I've been involved in. :) The last one, which is on the finishing lines (makes me too busy), has several servers running IIS, Windows Services, reverse proxies (with things like TLS termination), integration points and so forth and this has worked well. We stub out integration points and don't run reverse proxies (we could configure IIS Express instances if it it made sense), but otherwise the system locally mimicks that of production. Common problems are that, for instance, front-end developers may find that, for some reason, the data loading/inserting feels sluggish. The reason could be as simple as overly broad query to database, missing index (or bad index as loading data to system from an integration point soiled them), too much data put on the line or whatever, but it can be examined quickly, on the spot, in debugger, when it occurs sometimes as simply as checking the call stack. Which makes the more web oriented guys on occassion step through stored procedures too in order to trace something down (but that's another story, though great in educational sense).

So, in essence, I'd like to have an easy way to have the silos running like the APIs and front-ends on IIS Express on my example project and it'd be super-nice if I could put the same arrangment to test projects and run a more formal battery through it (as in the example project). In the particular project example I mentioned, we have the code and we share the test data with outside testers. It takes mere seconds to bulk-load about 300 MiB to LocalDb and if so needed, if the testers have found something, we can just backup their database, load it in on local system and see how it might have happened.

Assuming in future Orleans relational database there's less destruction on data (i.e. less UPDATE and DELETE clauses), it could be sensible to just load data in for troubleshooting locally and observe the system state or run analytical queries to dig out certain aspects. This scenario, and the above configurability in local debugging and testing (and production) may also explain my enthusiasm on having DI and interceptors and whanot so as to have the possibility to have a good visualization on what happens in the system should there be a need.

I'm not sure if this answers any of your questions or gives thoughts. This is more of a "systems thinking" point for me. In any event, what I'm after isn't doable in this PR (probably not even in several ones) and my vision is not something that is necessarily a shared one. Though if you have questions, I'm glad to answer them.

**Comment by jthelin** [comment]
One thing that has proved quite useful to us for deploying a group of silos to on-premise server machines are the PowerShell scripts in RemoteDeployment directory.
https://github.com/dotnet/orleans/tree/master/misc/scripts/RemoteDeployment

More info about what those scripts do and how they work is in the docs:
http://dotnet.github.io/orleans/Step-by-step-Tutorials/On-Premise-Deployment

While those scripts are most commonly used for deploying and start silos on multiple machines, they can also be used to start multiple silos on the same machine if Deployment.xml points to same hostname. For example:
``` xml
<Nodes>
    <Node HostName="localhost" NodeName="Primary" />
    <Node HostName="localhost" NodeName="Node2" />
    <Node HostName="localhost" NodeName="Node3" />
<Nodes /> 
```
It is most common to use the high level ```DeployOrleansSilos.ps1``` and ```UndeployOrleansSilos.ps1``` scripts, but there are also lower level ```StartOrleansSilo.ps1``` and ```StopOrleansSilo.ps1``` scripts that are used under the covers to start and kill silos respectively -- either local or remote machines. 

With a few tweaks those script could turn into a simple Chaos Monkey tool to add and remove silos into your One-Box cluster and see how everything deals with the various failure conditions. :smile: 

We do something similar to that in our internal Reliability test suite, where we systematically kill silos (either singly, or a group) and make sure that the cluster stabilizes again in a reasonable time window [depending on the liveness config settings being used] and adding new silo nodes back into the cluster successfully.

It sounds like from your description about that you are also looking for ways to host silo inside IIS front end process too? A few people have tried that various times, but usually switch to spawning silos as external .exe processes on the FE machines because IIS has nasty habit of randomly recycling hosting app domains at too frequent intervals. :crying_cat_face: 

Hope that give a few ideas to start exploring this topic. I am sure that other people would be interested in some or all of these alternate hosting mechanisms that you have in mind too.

**Comment by veikkoeeva** [comment]
@jthelin Just to be sure, I'm not interested in running silos in IIS, not even with ``AlwaysRunning`` and ``serviceAutoStartEnabled`` on (a bit difficult to comment on that more as I don't see point in such an arrangement). In simple terms it's abour programmatic access to create a cluster of silos and control them. In the example I tried to paint a picture of a more realistic ``.sln`` in some imaginary project with other ``.csproj``s and dependencies and how someone might work daily.

I wonder if there should be a difference in starting a silo either locally or elsewhere or in test or in testing or in local development or should it be just configuration? Sure, locally one has to mind port collisions (how about allocating just some random free ones from the ephemeral range?), but that looks like a configuration issue. It would feel ideal if one could use the same topology locally, testing and elsewhere. But what comes to testing, it looks like that in addition to plain configuration, one needs also "hooks" to succesfully test and observe system aspects. Of course I would like to see a "control grain" or something (there is one, I know), from which I can manage the silo along with putting one up with DI and interceptors and whatnot. Maybe, thinking from the side of Orleans, the simplicity of this *one-box-deployment* in every situation is something to strive for as it would mean the system is "well composed".

I saw the scripts before doing my [little gist](https://gist.github.com/veikkoeeva/4414609e828375c898f3), but I ended up to the gist because I wanted to know more about silo hosting and then it feels (is?) more dynamic than the ``hostname`` XML fragment you -- in combination with the PS scripts. Currently I don't need *the* command line thing in the existing wrappers. I just want to have a bunch of silos talking to each other. Likely I would like to run the silo locally with SQL Server and observe the "reliability behavior", amongst other things, in every turn (SQL Server ought to be a lot faster than the emulated storage engine). Then I might also want to tweak backends and rather much anything with a knob on it in *some fashion* that's difficult to describe now or even if it were possible, I'd like to roll a solution without trying to bend existing scripts or wrappers to do my bidding.

Ohops, I forgot to add. Naturally I like to start the cluster from ``bin\<configuration>`` or what has been configured. Like it were a "normal system", then the other projects start from their respective ``normal`` places. And about my gist, it really is incomplete, but as you can imagine, it shouldn't need that much tweaking to allow me to run, say, in SQL Server configuration (I also change naming so that it throws with the same name etc. instead of rewriting etc.). To me, at this point, it looks simpler than the other models for what I want currently. Should it become more complex?

**Comment by jthelin** [comment]
I am taking an F# training course in early June so that I will be able to eventually understand all the subtleties of @veikkoeeva 's gist snippet :) but it is doing roughly the same thing as the OrleansTestingHost code as you say - starting multiple silos [plus client] in same process with each in different app domains.

I was thinking that a more "realistic" One-Box config would run each silo / client in different processes on same machine [different IP ports, essentially] as a mini-cluster.

The biggest difference between one-process and multi-process hosting is that .NET CLR in a single process shares some resources (most notably the [Managed Heap](https://msdn.microsoft.com/en-us/library/ee787088.aspx#the_managed_heap) ) between all app domains in that process. 

So it is slightly more efficient to do single-process hosting but also more change for performance and resource contention between app domains.

Conversely, it is slightly easier and cleaner to kill a process than unloading an app domain.

I guess which approach is best depends on what scenario you are trying to emulate?

There are probably some extra command-line params / config file settings that could be added to make one-box hosting simpler too. One I can think of being useful would be IP port command line param, but there may be others too.

**Comment by veikkoeeva** [comment]
@jthelin Indeed, roughly the same as the testing pieces currently, as I ported the idea rather straightforwardly. You are correct about running the silos in diffrent processes. FYI: [F# for fun and profit](http://fsharpforfunandprofit.com/) and other [nice to know material](https://sergeytihon.wordpress.com/), but let's move things forward with regard to this after June. C# is fine too. :)

The rough idea I have in my mind is that the ``SiloClusterManager`` has a handle to the cluster, however they are run then (e.g. in different processes, in the same process but different AppDomains). Just to clarify, I'm not satisfied with the gist, but perhaps it gives the gist of it. :) To point out a few things, I think I want to throw if a silo with a same name is being added (one can provide a constructor function to append a sequence ID if needed), then if I want to run in reliable configuration in a single machine, the gist won't flow without minor modifications, then having choice between in-process AppDomains, different processes (perhaps MAF), maybe Azure (it's done already). Mostly I'm doing this for my own pleasure and added degrees of freedom, but also to see if the whole thing could be just configuration. Like serializing ``ClusterConfiguration`` and some added parameters through a serializer and then deserializing it back and giving to ``SiloClusterManager`` in the case of this gist.
