### ISSUE TITLE
Cannot find an invoker for interface

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#4111]
I am porting the contrib Mongo provider to RC1 and get an exception in this line:

https://github.com/OrleansContrib/Orleans.Providers.MongoDB/blob/rc1/Test/Client/Program.cs#L30: `Cannot find an invoker for interface Orleans.Providers.MongoDB.Test.GrainInterfaces.IHelloWorldGrain (ID=173128308,0x0A51BA74).`

The code is generated:

![image 1](https://user-images.githubusercontent.com/1236435/36899208-67b4d4de-1e1e-11e8-8873-78018f3619ee.png)

And the invoker is also registered:

![image](https://user-images.githubusercontent.com/1236435/36899266-9c58996e-1e1e-11e8-9e89-0d37f35f7709.png)

What is wrong?

**Comment by sergeybykov** [comment]
The screenshot if for the client side. Is the grain interfaces assembly deployed and registered on the silo side?

**Comment by SebastianStehle** [comment]
Stupid me.

**Comment by nvella88** [comment]
@sergeybykov Why so we need to do this? I encountered the same issue and Google led me here. Basically, I am serving the grain interfaces from a NuGet package we support and this solution fixed the issue for me. We are using Orleans 2.

 @SebastianStehle This was really a big coincidence seeing a post from you!

**Comment by sergeybykov** [comment]
@nvella88 
>Why so we need to do this?

Are you asking why we need an invoker class? Since we are making a remote call to an object (grain) on another machine, we need a way to call a requested method on it. We can do it in a late bound fashion (via Reflection) or early bound - via a generated invoker class. The latter is faster. That's why we generate invoker classes at compile time and add them into the grain interface assembly.

**Comment by nvella88** [comment]
Let me make it a bit clearer, for the sake of people who might encounter the issue in the future.
When I called `await myGrain.DoWork(command);` I was presented with System.TypeAccessException: 'Named type "MyCommandObject" is invalid: Type string "MyCommandObject" cannot be resolved.' or with some tweaking to the error mentioned by Sebastian. 

Adding this line of code `builder.AddApplicationPart(typeof(IMyGrain).Assembly);` while building the SiloHost solved my issue. I believe this is because of the statement you provided correct?

**Comment by sergeybykov** [comment]
>I believe this is because of the statement you provided correct?

Yes and no. You need to tell the silo which grain classes to load. That can be done in more than one way. How were you doing that before you added `builder.AddApplicationPart(typeof(IMyGrain).Assembly);`?

**Comment by nvella88** [comment]
Because previously we were doing                
` .ConfigureApplicationParts(parts => parts.AddApplicationPart(typeof(MyGrain).Assembly).WithReferences())`

I presume `.WithReferences()` was lost with some code re-writing. Does this make sense?

**Comment by sergeybykov** [comment]
`parts.AddApplicationPart(typeof(MyGrain).Assembly).WithReferences()` should have been sufficient.

**Comment by nvella88** [comment]
I thought so. Thank you for the clarification!
