### ISSUE TITLE
[Question] Silo shutdown and OnDeactivateAsync

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#4113]
I've been digging through the docs and the issues, but I didn't find an answer to the following question:

_When a silo is shut down, what happens inside a grain's_ `OnDeactivateAsync` _method when another grain is referenced from there, which in turn is getting (or has got) deactivated due to silo shutdown?_

And, to make things more obvious, imagine all silos have been shut down except for the last one; and now that last one is also shutting down, i.e. there are no other silos online. Say you reference another grain in `OnDeactivateAsync`, which already got deactivated - will an exception be thrown in this case? Or will that referenced grain become reactivated? If so, how will the reactivated grain eventually get deactivated? Is the silo trying to drain the silo from grains by retrying a deactivation again and again (until a timeout)?

**Comment by sergeybykov** [comment]
To clarify, when you are saying "you reference another grain", I suspect you mean "you call another grain", right? Merely holding a reference to a grain doesn't impact that grain in any way.

When silo gets into the `ShuttingDown` state, no new activations can be placed to it. So in your example of the last silo of the cluster shutting down, the grain call to a grain that is not already activated on that last silo will fail.

**Comment by peter-perot** [comment]
> To clarify, when you are saying "you reference another grain", I suspect you mean "you call another grain", right?

Yes, I call a method of another grain.

> _[...]_ the grain call to a grain that is not already activated on that last silo will fail.

Is there a special exception thrown, which lets me determine why the call failed?

**Comment by sergeybykov** [comment]
I believe it's an `OrleansException`, but I don't remember which subclass exactly.

**Comment by peter-perot** [comment]
I wonder how to correctly implement a cleanup in `OnDeactivateAsync`, which involves calling other grains.

Of course since grain calls are not guaranteed to succeed, one must always keep in mind that such a cleanup could be half-done (otherwise we would need some sort of distributed transaction).

So, is it generally bad practice to call other grains in `OnDeactivateAsync`?

To be specific:, there are cases where I deactivate other grains from `OnDeactivateAsync`. Those "other grains" have a `Deactivate` method (defined in their public grain interface) which in turn calls `DeactivateOnIdle`.

When those "other grains" are activated, nothing special happens - they simply get deactivated forcibly.

When those "other grains" are _not_ activated, they temporarily get activated, just to deactivate them afterwards.

And the latter case could be a problem when the silo is shutting down gracefully.

But forced deactivation is not the only use-case (you might make the point that I should not deactivate grains forcibly, but let them alone until activation garbage collection comes into place). There are use-cases where I want - for example - unregister something in such "other grains".

What is the correct way to accomplish this, and how to do it right when a silo is shutting down gracefully? Should I simply ignore those exceptions you mentioned?

**Comment by sergeybykov** [comment]
In general, `OnDeactivateAsync` is not supposed to be used for anything significant, other than a best effort notification of some other party that the grain is getting deactivated. I almost regret having `OnDeactivateAsync` in the API altogether. Because it's not 100% guaranteed to be invoked, is error prone, and has no good failure handling ability.

Similarly, forced deactivation is meant to be an optimization mechanism for releasing large resources, especially unmanaged ones.

With that in mind, I don't see a good way of accomplishing what you described in a clean way. I'd suggest to reframe the interactions between grains as one-way notifications of a grain shutting down, so that it is not concerned with success/failure of what that triggers, and there is less of expectation that such operations will succeed. And if the requirements allow you to get out of the business of explicitly deactivating grains, I'd do that as much as possible.

**Comment by peter-perot** [comment]
Thank you @sergeybykov.
