### ISSUE TITLE
does orleans2.0 rc1 support client discovery?

### ISSUE THREAD

**Issue by quaider** [dotnet/orleans#4114]
at client side, the hello demo use `UseStaticClustering` to conntect to the silo, 
but in real world, silo may be dynamic， i means that the client doesn't know about the place of silo.
so how to support client discovery? just like below or anthor way
```xml
<ClientConfiguration xmlns="urn:orleans">
  <SystemStore SystemStoreType="SqlServer"
               DeploymentId="target deployment ID"
               DataConnectionString="SQL connection string"/>
</ClientConfiguration>
```

**Comment by sergeybykov** [comment]
Yes, static clustering is used primary for development. For most other cases, you need to configure a clustering provider. The XML configuration option is getting deprecated. Take a look at the more modern programmatic configuration API - http://dotnet.github.io/orleans/Documentation/2.0/Configuration2.0.html. Instead of `UseDevelopmentClustering`, you can use one of the other `UseXYZClustering` methods. The SqlServer provider got renamed to AdoNet, as it now supports multiple SQL databases.
