### ISSUE TITLE
Interceptor use problems？？？

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4137]
Use interceptors to do permission verification, return insufficient rights message, the client can not receive the message, because the message can not be converted, is there any solution?

![image](https://user-images.githubusercontent.com/28291464/37013715-7e9d3950-2136-11e8-8aab-38216d202968.png)

**Comment by ReubenBond** [comment]
@aqa510415008 could you show use the code? It looks as though you're modifying `context.Result`, but you're modifying it to `AuthorizeResult` for some method which returns `User`, so there's an `InvalidCastException`.

**Comment by aqa510415008** [comment]
@ReubenBond   IGranis.User inherit AuthorizeResult 
![image](https://user-images.githubusercontent.com/28291464/37014292-8e8dd744-213a-11e8-9406-7106da9f2a2e.png)

**Comment by ReubenBond** [comment]
@aqa510415008 you cannot cast a base class to its sub class. In the case of an authorization error, you could throw an exception.

Otherwise, you need some way to create a `User` from an `AuthorizeResult`. However, I would advise you *do not* do that since it can easily lead to errors in your code.

**Comment by aqa510415008** [comment]
If authorization interception, authorization fails, I need to inform the client, but I can not let him into `Grain,` is there any way?

**Comment by ReubenBond** [comment]
Yes, there is a way: see above.

I also mentioned some ways to do this in another issue, here: https://github.com/dotnet/orleans/issues/4069#issuecomment-368269104

**Comment by ReubenBond** [comment]
@aqa510415008 you could throw an exception when auth fails instead of creating that result using reflection.

Usually you want many methods to require auth, not just one or two methods. So requiring that you return something assignable to `AuthorizeResult` on every message will become cumbersome. Additionally, `Activator.CreateInstance` requires a parameterless constructor, which restricts how you construct your types.

Note that you could also use `RequestContext` to specify the authorization result and simply return `null` from the method if you want to avoid using exceptions.

**Comment by aqa510415008** [comment]
@ReubenBond Thank you, throwing an exception is a good way. The way I was before is very unreasonable, very reluctantly
