### ISSUE TITLE
RequestContext not available in next operation

### ISSUE THREAD

**Issue by wiezykrwi** [dotnet/orleans#4168]
We have a Grain that uses the RequestContext to pass along the user information. When we use the same Grain instance twice in our calling code, the second call no longer has access to the RequestContext, which seems normal since it (the second operation) is completed on another thread. However it would seem to me that the RequestContext should be migrated to the new thread, or am I completely missing the point?
Should every Grain instance be used only once? Likely refetching the instance would resolve the issue (not tested, will try this out later).

Client:
RequestContext.Set("User", User.Id);
var grain = ClusterClient.GetGrain<OurGrain>();
grain.Operation1();
grain.Operation2();

OurGrain:
Operation1():
RequestContext.Get("User") => Fine

Operation2():
RequestContext.Get("User") => null

**Comment by sergeybykov** [comment]
`RequestContext` is mean to be set per grain call.

Since a grain can be called in parallel by multiple callers (clients and other grains), between `grain.Operation1()` and `grain.Operation2()` it could have processed a number of requests from other callers, and you probably don't want those calls to be process with the request context you set before `grain.Operation1()`. Likewise, you most likely don't want `grain.Operation2()` to operate with a context set by other caller. Hence, the behavior of request context only use for a single call.

**Comment by Jens-G** [comment]
Old thread but ran into same situation today. And found it a bit unexpected, as the OP did. 

**Suggestion:** Can we have some sort of an optional flag that allows to have values persistent on a per-key basis?
Would be perfectly fine to have the default set to the current behaviour.
