### ISSUE TITLE
How does Orleans unit test? Is there an instance or document?

### ISSUE THREAD

**Issue by aqa510415008** [dotnet/orleans#4202]
How does Orleans unit test? Is there an instance or document?

**Comment by martinothamar** [comment]
You can use the Orleans TestCluster-class. Alternatively there's [OrleansTestKit](https://github.com/OrleansContrib/OrleansTestKit) which I really like. Running tests with the TestCluster is pretty slow since it actually runs an Orleans-silo.

Are you on a specific version of Orleans? I have an example for TestCluster on 2.0.0-beta3: [https://github.com/martinothamar/Orleans.StorageProvider.Redis/tree/2.0.0-beta3/Tests/Orleans.StorageProviders.Redis.Tests](https://github.com/martinothamar/Orleans.StorageProvider.Redis/tree/2.0.0-beta3/Tests/Orleans.StorageProviders.Redis.Tests)

**Comment by sergeybykov** [comment]
There is an old doc - http://dotnet.github.io/orleans/Tutorials/Unit-Testing-Grains.html.
