### ISSUE TITLE
Current streams not suitable for event-based communication

### ISSUE THREAD

**Issue by csyszf** [dotnet/orleans#4238]
I'm building a microservices system, which need to implement event-based communication.
The current streams orleans using is more like "subscriber-driven", which means:
1. the subscriber subscribe a (event)stream.
2. Handle events
so subscribers(actors) need to be exists(actived) and subscribe stream manually, and too many subscribers will cause heavy overload.

but what we needs is "event-driven":
1. orleans recieves an event.
2. orleans active specific actor to handle this event

There's some alternative for "event-driven"
1. use one or few EventRecieverActor to deliver events to target actors.
2. use an orleans client as EventReciever
for the first way, EventRecieverActors should be always active, and it's difficult to control their placement,
and the second way seems will cause more network traffic, client --> silo cluster --> actors, The error probability may increase.

for now i'm using the second way to implement event-based communication.

and it will be nice if orleans' runtime supports this feature

**Comment by jason-bragg** [comment]
It is likely that I'm misunderstanding what you're describing, but it sounds like the behavior you're looking for may currently be supported using implicit subscriptions.  Implicit subscriptions map streams to grains by stream namespace and will automatically activate a grain per stream Guid to process all events on that stream.

If you're referring to orleans streams grouping events into streams rather than delivering them individually, each to their own grain, there are some customizations one can do to get this behavior, but you're correct, this behavior does not exist out of the box.  This is because activating a grain to process a single event is too costly for the performance targets we were shooting for when initially developing streams.

**Comment by csyszf** [comment]
@jason-bragg thanks for your reply
sorry i forgot implicit subscription.
my purpose is to ensure all events which will effect one grain should always be processed in single thread.
since implicit subscription, it's easier to implement that by

> use one or few EventRecieverActor to deliver events to target actors.


just defining a fixed map for every  [kafka partition --> stream guid --> EventRecieverActor]
I'll try to clear the other obstacles.

thanks a lot.
