### ISSUE TITLE
WorkGroup X took elapsed time and Task pressure

### ISSUE THREAD

**Issue by berdon** [dotnet/orleans#4283]
I've been investigating grain client timeouts and, with that, a large number of WorkGroup timeout warnings. After a fair amount of logging, commenting, and digging around, I think I've distilled it down into being Task pressure on the scheduler. I'll try to describe out scenario, summarize the investigatory steps and findings, and then provide a simple example that results in the same warnings.

# Our Usage
We use Orleans as a means of importing, normalizing, processing, and ultimately storing data from external data sources into a cloud based database. Additionally, as new data and updates to old data come in, we update external clients with the normalized and processed data.

Each document that comes in has a primary key to which we use to create an import grain. This import grain does some work to map external source IDs to normalized ones and then passes the normalized data to a "model" grain who's primary key is the mapped external primary key. These "model" grains use a custom storage provider that reads/writes to the cloud based database. This call also calls update on registered observers which end up flowing through to externally connected clients subscribed to document changes.

That's a pretty brief description of what we're trying to accomplish. I can dig into how we're doing it if necessary but I don't want to get side tracked on the approach yet.

# Investigations
- Eliminated possible blocking calls (Task.Run all the things)
- Added logging with timestamps around turns (start, stop, and around await calls)
- Added logging to the database to check query times

## Findings
- The timing logs ended up not really correlating well to any of the "WorkGroup X took elapsed time"
- The timing logs showed pretty random and sporadic long duration tasks (explained below)

### Sporadic long-running tasks
One of the best examples I encountered was when investigating some long execution database calls in a WriteStateAsync call to a storage provider. Generally, the database call would take 100-150ms (keep in mind these are called via Task.Run). The database's logs were showing 10-40ms for the actual query. While attempting to determine the difference here I noticed that individual statements in the code would sometimes very dramatically in how long they "took" and the query itself was not always the thing that took 100-150ms. An example is:

1. Do some small amount of work
2. Do some other small amount of work
3. Build a 200-300 character string using $"" interpolation
4. Execute query

"Generally" step 4 would take 100-150ms; however, _sometimes_ steps 1 or 2 or 3 would take 150ms and step 4 would take 10-40ms.

### Conclusions
So, based on that, I put together a simple grain call that generates a bunch of Tasks and I end up seeing the same "WorkGroup X took elapsed time" warnings.

### Is this normal and/or expected?
We do generate a number of tasks throughout many of our grains. Not an inordinately large number but it's probably 1-10 per document.

I would expect this type of behavior spinning up a large number of threads that would then end up having to compete for CPU core time. Thus I feel like this is probably normal given a large number of Tasks would end up competing for Thread time? What seems strange to me; however, is that the warning message implies the WorkGroup was _started_, preempted, and then completed.

# Simple Example
## Grain Client
The client just calls a grain's Echo method 100 times. Each iteration is a new grain.
```C#
while (!quit)
{
    var duration = new ExecutionTime();
    var grain = client.GetGrain<IEchoGrain>(Guid.NewGuid());
    for (var i = 0; i < 100; i++)
    {
        var _ = grain.Echo("Some message here");
    }
    Console.WriteLine($"Duration: {duration}");
    await Task.Delay(1000);
}
```

## Grain
The grain creates 100 Task.Delay(500) tasks and then Task.WhenAll's them. Note: I've tried most variations of using Task.Run and not.

```C#
public class EchoGrain : Grain, IEchoGrain
{
    public async Task<string> Echo(string message)
    {
        var tasks = new List<Task>();
        for (var i = 0; i < 100; i++)
        {
            var task = Task.Run(() => Task.Delay(500));
            tasks.Add(task);
        }
        await Task.Run(() => Task.WhenAll(tasks));
        return message;
    }
}
```

**Comment by berdon** [comment]
@sergeybykov suggested using @dVakulen's changes in PR #3792. I built that and got things working but am still seeing the "WorkGroup X took elapsed time" warnings.

**Comment by dVakulen** [comment]
The "WorkGroup X took elapsed time" warning message shows total execution time of grain method, incuding waiting for async actions, such as database call or `Task.Delay`, and thus may not reflect actual load on CPU. Offloading of such actions to .NET task scheduler doesn't bring much benefit ([explanatory  article on the matter](https://blog.stephencleary.com/2013/11/there-is-no-thread.html)).

It is expected behavior for example above: the `Echo` grain method takes 500 ms to complete, while the default warning threshold is 200 ms. 
Execution time numbers from real example also suggests presence of that warning due to high latency of accessing of the cloud storage. It's excessive appearances can be avoided using `TurnWarningLengthThreshold` property of `NodeConfiguration` (e.g. it can be adjusted from default of 200 ms to 300 ms).

**Comment by berdon** [comment]
I'm not seeing the total length of the grain call in these warnings. I'm seeing arbitrary amounts that don't correspond to the grain call at all. Ie. In my example I see various times ranging from 200ms to 1-2s.

**Comment by berdon** [comment]
Doing some tweaking to the example, I made the Echo call [OneWay], added an observer to the echo grain for a response, and issue an Echo call to a new grain 100 times a second. Doing this, the silo becomes unresponsive after a few minutes.

**Comment by berdon** [comment]
@dVakulen: For some context to why I'm looking into these warnings in the first place:

We see a gradual increase in grain call times in our system until we start hitting 30s grain client timeouts. We've raised this timeout to 2m but we still continue to see an increase until we hit the 2m mark as well. Eventually, we have to restart the silos at which point grain calls are "fast" again (until they slow back down).

**Comment by jason-bragg** [comment]
**_Regarding the example:_**

Please check my math on this..

Each grain call spins up 100 500ms task delays in parallel, so a single grain call should take at least (but not much more than) 500ms.

A grain can only process one grain call at a time, and the client is spinning up 100 grain calls without waiting for each, so they are all in flight at the same time.  This means that the last of the 100 calls, each taking a minimum of 500ms, should complete no sooner than 50 seconds after it's called.

For this to not trigger a timeout (default 30 seconds) you'll need to increase the ResponseTimeout in the SiloMessagingOptions and ClientMessagingOptions.

The bursts of 100 grain calls occur in 1 second intervals and take ~50 seconds to complete, so the cluster should have roughly ~5000ish grain calls in flight at any point in time.  This should be fine.

Given that each grain call takes a minimum of 500ms and processes 100 call bursts, the SchedulingOptions.TurnWarningLengthThreshold default of 200ms seems insufficient.

> We see a gradual increase in grain call times in our system until we start hitting 30s grain client timeouts. We've raised this timeout to 2m but we still continue to see an increase until we hit the 2m mark as well. Eventually, we have to restart the silos at which point grain calls are "fast" again (until they slow back down).

The behavior described in the above quote is usually caused by overloading individual grains, not overloading the system as a whole.  For instance, if a grain takes 10 ms to process a call, there is no way for it to process even 100 calls per second without being overloaded.

On average, how long does a grain call take? (time spent in the grain call)
On average, how many grain calls are made per grain per second?
If the product of these numbers even approaches 1 second, the system will have problems.

A good rule of thumb (from my experience) is that the number of grain calls a grain can handle is:

    AverageCallsPerSecond = 1000 / (AverageTimeSpentInGrainCallMs+1)

So a grain that spends 1ms in it's grain call may handle around 500 calls per second, while a grain that spends 500ms will handle just under 2.  More than this, the grain may not be able to keep up and will eventually hit timeouts similar to what you're seeing.

I'm not claiming that the above is what's happening in the service, as I'm not nearly familiar enough with it to form such a conclusion, only that such is a common cause of the symptoms described.

**Comment by berdon** [comment]
@jason-bragg Your math seems right. You can remove the await on the Task.WhenAll() so the 100 Task.Delay(500)'s execute without blocking and you'll still get the WorkGroup warnings.

**Comment by lmagyar** [comment]
Shouldn't you add the `[OneWay]` to the method declaration inside the **interface** and not to the **implementation** inside the class? (Just asking, my knowledge about the internals are epsilon compared to yours'.)

**Comment by berdon** [comment]
@lmagyar I believe, [OneWay] is tagged to interface methods. I generally put them on both or comment as such to make it obvious to others that the method is a one-way.

**Comment by sergeybykov** [comment]
@berdon Do you still think there's an Orleans issue here that we need to investigate?
