### ISSUE TITLE
Redundant Dictionary allocation in RequestContext.Set ?

### ISSUE THREAD

**Issue by MelnikovIG** [dotnet/orleans#4313]
There is a extra allocation of `Dictionary` with copying values from another `Dictionary` if it exists.
https://github.com/dotnet/orleans/blob/3f27bea31633e55dbf4cbdb96b1562021da2226b/src/Orleans.Core.Abstractions/Runtime/RequestContext.cs#L84-L89

Looks like comments outdated and article by link too. Does it make sense since  `CallContextData` based on `AsyncLocal<T>` not `CallContext` anymore? I tried remove this allocation and all still works fine. Could you investigate this question?

**Comment by kutensky** [comment]
Hi @MelnikovIG. Approach proposed by you couldn't be done. Even if we use AsyncLocal, Value that is stored is a reference type. So when we enter a new thread and AsyncLocal copies Value of instance from previous thread, it copies a link. So when we edit dictionary, we edit the same dictionary that was used in previous thread. That's why need to reallocate dictionary each time we call Set.
It would be great if we could understand that this call of Set method is the first per current thread, but AsyncLocal class doesn't provide such feature. So allocating a dictionary each time we call Set is the only way to make sure that it doesn't depend on dictionaries from other threads.

**Comment by ReubenBond** [comment]
Fixed by @kutensky in #4435
