### ISSUE TITLE
Multi cluster and practical use discussion

### ISSUE THREAD

**Issue by quaider** [dotnet/orleans#4353]
assume that there are some 3 teams(A, B, C),
- team **A** provide silos with `Authentication and Authorization` and some User Services，its grain interface may be cluster A: `IAuthGrain`  
- team **B** provide `Order service` , its grain interface may be   cluster B: `IOrderGrain`
- team **C** provide  `Inventory service`, its grain interface may be cluster C: `IInventoryGrain`
each team develops its own services independently，my question is:

1. How should they eventually integrate together？
2. Does each team's silo or other project must refference all of there grain interfaces?  A refference `IOrderGrain` 、`IInventoryGrain` and `IAuthGrain`? I think it's not always feasible.
3. What is the best practice in such a scene?  
use one cluster or multi cluster?  if multi cluster, can orleans work on other cloud server?
each team must predefine there grain interfaces which will be refferenced（used） by other teams?

**Comment by quaider** [comment]
thanks for you valuable advice @jason-bragg , In fact, I'm trying to introduce micro-service architecture, I don't think there should be a dependency between services, such as `Inventory silo` must refferenced other teams interfaces, 

assume in futrue, team D may deploy a new `Analysis Silo` provide some analysis services, this causes changes to all silos（interfaces define changes, _not sure if it be_）, which increase the job of other teams. In my opinion, the `Analysis Silo` is dispensable, we can load or unload it in an easy way which should not affect the services running on other silos.

This is some of the questions in my actual development, In order to simplify, i use a single-cluster to build the silos services

**Comment by quaider** [comment]
what  i want to do is just as below, i'm not sure, so is it the right way? @jason-bragg @sergeybykov 
![20180330234340](https://user-images.githubusercontent.com/12459496/38143681-383864ca-3474-11e8-914a-74118623893c.png)

**Comment by sergeybykov** [comment]
The simplest approach here I think is to treat the 3 microservices as 3 independent Orleans clusters *with* 3 frontend layers for them to communicate with each other. A call from one microservice to another would be an HTTP call. This way each of the microservices can be deployed and managed independently.

Note that this doesn't mean they have to necessarily run on different physical servers. All these 6 clusters (3 clusters of silos + 3 sets of frontends) can share the same physical infrastructure, so long as they are logically isolated and use different ports.

Look at https://github.com/gigya/microdot for how they do this.

From that baseline, if you do want to combine 2 or all 3 services into a single cluster of silos, you can do that, and I suggest you look at the heterogeneous cluster feature for that. It allows to allocate different silos to different sets of grain classes. Microservices running within the same Orleans cluster can invoke each other's grains directly instead of going over HTTP.

**Comment by ReubenBond** [comment]
Closing for now. We can reopen and continue the discussion if there's anything to add.

**Comment by Zonciu** [comment]
@sergeybykov If I use heterogeneous cluster, is that means all stateless worker grains must be deployed in all silos, even it is only be used by one microservice(a group of silos offer a service)?

**Comment by sergeybykov** [comment]
Stateless worker grain classes have to be deployed in all silos that might originate (from grains hosted there) or receive (from clients) calls to them.
