### ISSUE TITLE
No implementation of IHostEnvironmentStatistics was found

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#4389]
Warning	100708	Orleans.Runtime.NoOpHostEnvironmentStatistics]	No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet.

What should I write in StartSilo

**Comment by benjaminpetit** [comment]
If you are using .net 4.6 on Windows (not .net core), you can install the NuGet package `Microsoft.Orleans.OrleansTelemetryConsumers.Counters` and register it with the method `UsePerfCounterEnvironmentStatistics()` on your client and SiloHost builder.

**Comment by sundong1982** [comment]
@benjaminpetit i'm using .net core:(

**Comment by benjaminpetit** [comment]
Don't lose hope! :)

If you don't plan to use load shedding -- you can ignore this warning.

If you want to use it, you need to provide your own implementation of `IHostEnvironmentStatistics`, depending on the environment you are using.

**Comment by sundong1982** [comment]
@benjaminpetit  thx:)

**Comment by Kritner** [comment]
Not sure about when this issue was originally opened, but now you are able to use `builder.UsePerfCounterEnvironmentStatistics()` for your Silo/Client builders to get stats on .net core in a  windows runtime environment.

This issue is one of the higher up google results when googling how to get `LoadShedding` working - which requires these stats be available - so figured I'd update the comment!

Thanks to @martinothamar for pointing me in the right direction on [gitter](https://gitter.im/dotnet/orleans)! :)

**Comment by sergeybykov** [comment]
Maybe we should add a validator for `LoadSheddingOptions` that would check that an implementation for `IHostEnvironmentStatistics` is configured? It could also check that `LoadSheddingLimit` doesn't exceed 100%.
