### ISSUE TITLE
Azure Queues Orleans.Streams.QueueCacheMissException 

### ISSUE THREAD

**Issue by dsarfati** [dotnet/orleans#4426]
We are using 2.0.0 with Azure Queues we are getting a `QueueCacheMissException` on some of our streams, while other streams are working as expected. We are basically using the default configuration to use streams with a small load. I found some info on configuring a cache size, but I havent found any examples in the Tests or Samples.

```
Item not found in cache. Requested: [EventSequenceTokenV2: SeqNum=28, EventIndex=0],
 Low: [EventSequenceTokenV2: SeqNum=29, EventIndex=0], High: [EventSequenceTokenV2:
SeqNum=29, EventIndex=0]
```

```
Exception while retrying the 0th time reading from queue default-2
```

Configuration:
```
.AddAzureQueueStreams<AzureQueueDataAdapterV2>("Default", ob => ob.Configure(options =>
                    {
                        options.ConnectionString = queueConnection;
                    }))
```

**Comment by dsarfati** [comment]
Thanks for the info. I don't understand why our cache size would need to be increased. It was a very small load, and our messages are pretty small. Is there something I can look at to see why we filled the cache?

**Comment by xiazen** [comment]
Oh I thought you want to configure your cache size to be bigger, maybe I misunderstood you.To see if you filled cache, try see if you see `CacheFullException` in your log

**Comment by dsarfati** [comment]
I'm not seeing any `CacheFullException`, just the `QueueCacheMissException`. When I researched this exception I found that some are setting a bigger cache size. I'm just trying to figure out if it is normal to set a larger cache size or if this is an indicator of another problem within our system.

**Comment by jason-bragg** [comment]
When you say small load, can you hint at some rough numbers?
For instance, about how many streams are active at any point in time?
What does the throughput per stream look like (in events per second)?
How long does a stream usually live?
Asking because I’ve found that the idea of ‘small load’ can vary greatly from person to person. 😊

In general, cache miss exceptions shouldn’t happen except under error conditions, though the behaviors and causes can be stream provider specific.

If you do not have a handler for the OnErrorAsync, I’d start with adding one that logs any errors sent to the grain.  This can help correlate the error with grain activity to help understand how the system got into this state. 

The most common cause of cache misses using azure queues (from what I’ve seen) is when users pass a sequence token to a stream when resuming processing.  This is the norm for recoverable streams, but azure queue streams are not recoverable, so sequence tokens passed to a resume will usually lead to a cache miss.

A silo outage, which triggers a queue to be moved to a different silo may also cause a cache miss.

Cache size changes ‘shouldn’t’ really effect cache misses and the error indicates that there is only a single message in the cache. 

Low: [EventSequenceTokenV2: SeqNum=29, EventIndex=0],
High: [EventSequenceTokenV2: SeqNum=29, EventIndex=0]

These are the lowest and highest events in the cache.  We can see that they are the same, so there is only a single event.  What’s not clear is why an earlier message is being requested.

**Comment by sergeybykov** [comment]
@dsarfati Any update?

**Comment by dsarfati** [comment]
We were not able to easily resolve this with code. We ended up taking down the system for a short period of time and completely clearing the queue storage account. Our best guess is that there was either an unhandled exception that was thrown in the stream callback that caused this loop or that there was a change to the code base that caused the generated interface id to change, resulting in a never-ending loop of stream providers attempting to process a message with the old interface id.

**Comment by xiazen** [comment]
Any Update?

**Comment by xiazen** [comment]
close it now. feel free to reopen. Sorry we couldn't help much.
