### ISSUE TITLE
Questions related to reliability

### ISSUE THREAD

**Issue by tdinucci** [dotnet/orleans#4458]
Your implementation of the Actor pattern is obviously more geared around intuitiveness and implicit reliability than other implementations.  I do really like how intuitive things are however have 2 questions:

1. You obviously support streams which means one grain can fire off some request into a stream and then exit.  My question is; should streams be optional?  My understanding from reading the docs is that the most simple and intuitive route to follow is to not use them and to block (asynchronously) while dependant grains execute. However I think that I could easily get into more trouble using Orleans in this way than I would by developing traditional locking code.

Say I have a Grain A which depends on Grain B, which depends on Grain C, etc.  If Grain C maintains state but A and B don't then are potential activations of A and B blocked until C completes, even though work could be performed in A and B during this period - perhaps A and B don't even always lead to C.

Hopefully it's clear what I'm trying to say.  In a sentence, it makes perfect sense to make grains atomic however I'm not so sure about chains of grains.  

Have I misinterpreted the architecture? Assuming I haven't, I'll repeat that I know I can use streams and there will be certain patterns I can follow to help me here.  I'm just wondering if there is any value in going the simple/intuitive route (if indeed it's better than a more traditional approach)?

2. I understand why streams are reliable and it's very nice to have this.  I'm not clear how to best use them though.  I'll give an example to demonstrate my question - along with some extra detail so you can correct me if I'm missing something fundamental:

Grain A posts a message to Stream A (it blocks while it's posting to the stream but after this can then return and handle further activations).  Now if for whatever reason the message posted to the stream isn't processed as expected (e.g. the grain which consumes the message doesn't die but somehow drops the message).  I'm assuming I have to build checks into my system for this type of thing?

If it is the case that I've got to build these checks into my system I'm wondering if it's worth paying the cost for the reliable stream?

**Comment by jason-bragg** [comment]
**Regarding 1**

Streams, imo, are separate from the actor model.  Streams are a feature we support and are integrated with the actor model but are logically separable and opt-in only.  Our implementations of streams are built (wisely or not) on top of the actor model which constrains the feature to limitations of the actor model, but that is mostly an implementation detail.

The behavior of streams, unfortunately, is very implementation specific.  For instance, the type of chaining behavior you describe is a concern when using the simple messaging streams (SMS), but would not be a concern while using any of the persistent streams (Memory Streams for instance).  This is due to the fact that the OnNextAsync task on a persistent stream resolves when the event is successfully stored in the queue rather than upon successful processing of the event by all subscribers (as is the behavior in SMS).

**Regarding 2**

Streams are not necessarily reliable, we support various levels of reliability.

SMS and Memory streams are not reliable, as they keep messages in memory and can lose messages under some error conditions.

Some persistent streams support limited recovery of unordered data.  Azure queue is an example of this.  It should reliably deliver all messages at least once to each subscriber, but the data is unordered, and duplicates are possible (even likely).

Some persistent streams support ordered reliable data.  EventHub stream provider is an example.  These streams will deliver events in order with ordering information in the form of sequence tokens which can be used to remove duplicate events or rewind the stream to an earlier point in order to recover from transient errors.

Unfortunately streaming, while conceptually simple, is non-trivial and means different things to different people.  Prior to a deeper dive into the subject, I advocate users consider their application needs.  While we make efforts to simplify the usage patterns, the ordered, reliable, recoverable, high speed processing of events in a distributed system is not something that we’ve managed to deliver an entirely simplified model of, nor have we managed to avoid technical tradeoffs which only the application developer can choose to make. :/

**Comment by jason-bragg** [comment]
@tdinucci,

>Grain A posts a message to Stream A (it blocks while it's posting to the stream but after this can then return and handle further activations). Now if for whatever reason the message posted to the stream isn't processed as expected (e.g. the grain which consumes the message doesn't die but somehow drops the message). I'm assuming I have to build checks into my system for this type of thing?

As described in my previous post, this sort of recoverable stream processing is only supported by persistent streams and may vary by implementation.  For ordered reliable streams, the expected behavior is that should an event delivered to a subscriber to be processed fail, the streaming infrastructure will retry until it succeeds or a set retry period is reached.  If the streaming infrastructure eventually gives up on delivering the event, the application layer is notified of this via the OnErrorAsync and a local callback to an IStreamFailureHandler, should the application provide one.  The local callback is necessary as the OnErrorAsync is unreliable, because if the grain is unreachable for event delivery then it may not be available for error notification.

The reliability in the recoverable streams is geared towards transient errors, allowing resilience against temporary outages (usually less than 5 minutes).  It doesn't ensure the processing of poison messages or message processing under other non-recoverable or long standing errors, only notifying the application layer that these have occurred, so either user or automated action can be taken.

These behaviors are tested using the ImplicitSubscritionRecoverableStreamTestRunner.

**Comment by jason-bragg** [comment]
@tdinucci

>chains are effectively synchronous and all grains within the chain are locked. Is this correct?

I'm unfamiliar with mail boxes, but regarding chaining behaviors, the default behavior for a chain of A->B->C would be that A,B, and C would not be able to process other grain calls until C returns, at which time only A and B would be unavailable until B returns, and so on.  Streaming, if configured to use a persistent stream, would avoid this since an event generated on a stream consumed by A could generate a new event on a different stream to be consumed by B and so on, avoiding blocking for long call chains at the cost of putting the event in a queue between each grain.  Am I understanding your question?

>Is the assurance that if a message fails to be processed it's retried or just if it fails to be delivered?

Either.  Delivery of a stream event to a consumer is performed as a grain call.  If the grain call does not succeed (due to application error, timeout, grain activation failure, duplicate activation, ..?), it will be redelivered.  This retry logic will persist for a configured period of time (default is 1 minute).  In the case of a silo failure, this retry logic may reactivate the grain on another silo.  If this leads to data loss from processed messages which may not have been persisted yet, the grain can rewind the stream to the last point the grain stored processed results and reprocess the lost events.  This ability to rewind the stream is limited by the amount of data the stream provider is configured to cache for recovery purposes.  The larger the cache, the further back in time a recovering grain can rewind its stream.

**Comment by tdinucci** [comment]
@jason-bragg you have understood my questions and answered them.  Thanks very much for your time!

**Comment by martinothamar** [comment]
For the grain call chain locking in the absence of streams, there is the `OneWay`-attribute which can be added to methods on the grains interface. When a grain calls on that attributed method it will immediately return. Not sure how persistent streams compare to this attribute in terms for performance and reliability.
