### ISSUE TITLE
Document placement policies

### ISSUE THREAD

**Issue by kmyrtue** [dotnet/orleans#4537]
Dear Orleans Team

I have been trouble shooting my application for the past 2 months, because I wasn't gaining any benefit from adding additional silos. Can you create a topic in your documentation regarding placement location [PreferLocalPlacement] and so on. My problem was that every time Grain A was called by my clients, Grain A had to call 3 instances of Grain B, when placement was set to random, these were activated on the different silos, but when I changed Grain B to prefer local placement, it always activated them with Grain A so the RPCs where minimized.

I have looked through the entire documentation (I am pretty sure it is mentioned in one of the scientific papers published or a blog post somewhere, since that was the only reason I ended up thinking about it).

I found this description today that saved my day. http://richorama.github.io/blog/2015/01/02/grain-placement-in-orleans/

**Comment by jason-bragg** [comment]
We should document the placement strategies we support as well as how developers can provide their own.

**Comment by sergeybykov** [comment]
Need to also document how to add custom placement policies.

**Comment by cmeyertons** [comment]
Any movement here? I’ve scoured the web looking for examples or docs and only came some issues mentioning placement:

#5679 

 We have a large batch system that processes a graph of nodes of varying sizes (typically with a very large mother node in the center of an hourglass shape). We can have hundreds of these graphs processing at once. 

We know the weight of each node from a prior run and need to implement a placement strategy so that we can prevent a bunch of mother nodes from toppling one silo.

**Comment by ReubenBond** [comment]
Similar to #6376 and similarly fixed in https://github.com/dotnet/orleans-docs/pull/39
