### ISSUE TITLE
need a Orleans.Transactions.SqlServerStorage or  Orleans.Transactions.AdoNet

### ISSUE THREAD

**Issue by sundong1982** [dotnet/orleans#4569]
Will this add to the later version?

**Comment by veikkoeeva** [comment]
@sergeybykov, @jdom, @ReubenBond, @xiazen What would be needed to for this in ADO.NET? I see the shape of the data could be derived [from here}(https://github.com/dotnet/orleans/blob/master/src/Azure/Orleans.Transactions.AzureStorage/TransactionalState/StateEntity.cs), then maybe a bit configuration, but are there pointers what other classes? I'm gathering the required work here to to add the pieces and then tests (which might become a source of friction too), I see some documentation at http://dotnet.github.io/orleans/Documentation/2.0/Transactions.html.

**Comment by veikkoeeva** [comment]
Or perhaps a better question would be, how much in flux is the feature still? Cross-referencing https://github.com/dotnet/orleans/pull/4568/ and related to my previous questioned, indeed, maybe just to take a look at the two existing libraries to estimate some of the work needed.

**Comment by jason-bragg** [comment]
The transaction system is still very much in flux.

**Comment by sundong1982** [comment]
@veikkoeeva thx

**Comment by jason-bragg** [comment]
The plan is still to support storage abstractions for transactions so they can run against a variety of storage systems, but these surfaces are still in flux.  I encourage others to experiment with these systems to help us vet them, but I am of the opinion that the system is still to immature to start building out a full set of storage implementations.

**Comment by veikkoeeva** [comment]
@jason-bragg Out of curiosity (no need to exhaust if this is a bad question), could the transaction utilize [TransactionScope](https://msdn.microsoft.com/en-us/library/system.transactions.transactionscope.aspx)? Or otherwise be like `using(var transaction = new DistributedTransaction(grain1, grain2, grain3)) { /* ... */ }`?

**Comment by jinhong-** [comment]
Transactions seems to be out of beta phase and production ready. Anyone working on building a adonet transaction storage?

**Comment by veikkoeeva** [comment]
@jinhong- I'm not aware of at least. I'm not sure if there's a set of documentation or guidance either to help adding to other providers such as ADO.NET. Do you have a case at hand?

**Comment by xiazen** [comment]
There's a testkit out for testing custom transaction storage provider. Please look for `Microsoft.Orleans.Transactions.TestKit.xUnit`, which is testing nuget for xUnit. If that is not your testing framework, you can still use `Microsoft.Orleans.Transactions.TestKit.Base`, where all the base class of the test collections are. Just you will need to write extra code to hook it up with your testing framework. 

As for docs, I think @jason-bragg wrote something, but I will let him explain the details, since I don't remember what docs is there exactly.

**Comment by jinhong-** [comment]
@veikkoeeva At the moment transactions only works on Azure Table and we are not running Orleans in Azure. We need some sort of alternative to run transactions outside of Azure basically. At the moment we are exploring the usage of CockroachDB for scale out, which means that have a ADO.NET provider that can support the PostgreSQL dialect should theoretically work

**Comment by sergeybykov** [comment]
>At the moment transactions only works on Azure Table and we are not running Orleans in Azure.

That's incorrect. You should be able to run transactions over any storage provider.

**Comment by jinhong-** [comment]
@sergeybykov Do you mean running it using the storage bridge? I read it on the [transactions documentation](https://dotnet.github.io/orleans/Documentation/grains/transactions.html) that we should only use it for development purposes because it is not as efficient compared to the native transaction storage implementation. Does this still hold true?

**Comment by xiazen** [comment]
yes I think that still holds the truth.

**Comment by jsteinich** [comment]
We have used the transaction storage bridge in production without issue.

The big difference between the bridge and native is how the data is stored and what operations a transaction needs to do with the storage.
In the bridged storage, all pending transaction states are stored inside a list in a single record. As a transaction goes through the phases, states are added, updated, and removed from that list.
In the native storage, states are stored as separate records. This generally means that writes are smaller and inserts are more common.

I can't speak to what support the Orleans team will provide, but outside of that, determining what storage access patterns are acceptable for your application and storage is an evaluation that you'll need to make.

**Comment by gatm50** [comment]
Hi @ReubenBond if I am interested in contributing with an Implementation for AdoNet ( we are using Postgresql, but I don't think it will too much extra effort to add support for other databases) should I create a PR on the Orleans repository or should be on the OrleansContrib repository?

**Comment by ReubenBond** [comment]
I agree with what @jsteinich says. Essentially, that the storage bridge is likely sufficient for most cases.
Writing a specialized transaction storage provider is very nuanced, undocumented, and I don't recommend it unless the other options have been exhausted and it has been deemed necessary.

I would like to open-source some internal transaction storage providers which are used at Microsoft which target Cosmos DB. Those would serve as additional examples for how to write a transaction storage provider.

@gatm50 I recommend creating a separate repository on OrleansConrtib once it's ready. If it gets good mileage in production across a few projects then we can consider moving it to the main repository at some point, but I also think that OrleansContrib is a fine place for providers - even providers which the team contributes to directly (such as Redis & CosmosDB)
