### ISSUE TITLE
Why is Microsoft.Orleans.Clustering.ServiceFabric not available for v2.0.0?

### ISSUE THREAD

**Issue by jsukhabut** [dotnet/orleans#4588]
Why is Microsoft.Orleans.Clustering.ServiceFabric not available for v2.0.0?

It is available for v2.0.0-rc2 but not v2.0.0.

**Comment by sergeybykov** [comment]
The community discovered a fundamental issue in the implementation we had, and we pulled the package for now. @ReubenBond had an idea of a proper implementation, but we ran out of time for 2.0.0 to try to get it in.

**Comment by jms69** [comment]
@ReubenBond can you share your idea on the proper implementation?

I am having issues using Azure Storage for clustering in Service Fabric.  If the Azure membership table is clean, all is well.  Repeated deleted, update, and upgrades of an application causes silos to never discover each other.

**Comment by sergeybykov** [comment]
The Azure Table clustering provider is the most used and tested one, and it should just work with SF because it is completely independent from the hosting infrastructure. Just need to make sure the same `clusterId` is used for all silos, and accessible IP addresses are configured for their endpoints.

Can you share more data (configuration and logs) about how you are setting it up?

**Comment by ifle** [comment]
@jms69 I have small unrelated to this issue question.
When you deploy the webapi frontend? On SF or Service App?
I try to find the best way for us to deploy the silo's and frontend applications.

**Comment by jms69** [comment]
@ifle WebAPI frontend is another stateless service in SF.  There is AuthN in the API layer.  The WebAPI just protects and wraps the silo calls which does not have security.

**Comment by ifle** [comment]
Thanks. We have the classic asp.net application and can't use stateless service. In our case the best solution are containers.

**Comment by sergeybykov** [comment]
@jms69 I see at least two related aspects here.

1. Why silo that are getting shut down don't manage to update their status in the membership table. 

The process of a graceful shutdown takes some time: to deactivate all grains, hand off directory partitions, etc. The last step in the shutdown process is updating silo's status in the membership table.

I suspect that in this case silos aren't given enough time to complete the process successfully and get killed before they are done, which leads to the inconsistent states in the table. I suspect this is aggravated by shutting down *all* silos at once. To confirm that, you can try to stop silos (ungracefully) instead of shutting them down.

2. When a new cluster is starting with the same Cluster ID as a previously run cluster, and the membership table contains fresh incorrect entries listing as `Active` silos that are actually aren't running, this slows down startup of the new cluster by up to a few minutes until those incorrect entries expire because the newly starting silos validate (by default) their connectivity with all `Active` silos in the cluster.

If you a new cluster with a new Cluster ID, this obviously won't happen. Otherwise, 2 is inherently dependent on 1.
