### ISSUE TITLE
.\Build.cmd and .\src\Build.cmd don't like spaces in path

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#461]
Steps to reproduce:

1) Get branch into path similar to "C:\Users\Elan\Downloads\New folder (2)\orleans-1.0.8"
2) Run .\Build.cmd 
3) Observe Build Failure:
![image](https://cloud.githubusercontent.com/assets/234704/7875181/99d32072-0587-11e5-9ea2-7163b7f5bdef.png)

4) Correct .\Build.cmd" by putting quotes around line 1
5) Rerun .\Build.cmd
6) Observe Build Failure:
![image](https://cloud.githubusercontent.com/assets/234704/7875193/d324b5e8-0587-11e5-8806-31892439526f.png)

7) Correct issue in .\src\Build.cmd by putting quotes around line 12
8) ReRun .\Build.cmd
9) Observe Failure:
![image](https://cloud.githubusercontent.com/assets/234704/7875358/ffd7332a-0589-11e5-9b13-589002c0d5e5.png)

Several other files have this issue.

**Comment by jthelin** [comment]
I hope that merging PR #491 will have fixed any remaining problem not already covered by PR #462.

Everything looks good when I tested on my machine with spaces in directory name, so I will close this issue for now.

Please feel free to re-open this issue if things are not fixed in your environment.

**Comment by ElanHasson** [comment]
Thanks.. Just got back from vacation. Appreciate the assist.
