### ISSUE TITLE
How to make per data per column in relational database for specific grain<T>?

### ISSUE THREAD

**Issue by mokezhuhy** [dotnet/orleans#4640]
Hi, I have learnt orleans for several days, and I want to change a exist project which the entity framework core and code first is used to orleans. However, I can't figure out how to map the state of the grains, which stored in different tables. Is there any example?

Thank you, very much.

**Comment by aqa510415008** [comment]
@mokezhuhy 
I write a framework here, you can learn from    [Zop.Orleans](https://github.com/aqa510415008/Zop/tree/master/src/Zop.Orleans)

**Comment by mokezhuhy** [comment]
Thank you for you reply, the framework of yours looks great. Is there any example to introduce how to use it? @aqa510415008 

Thanks again.

**Comment by csyszf** [comment]
I think Grain<T> is a complete/universal solution for state persistence
so if you want implement your own way to read/write state(map to relational db's columns), just implement your own ReadStateAsync/WriteStateAsync/..., and hook them into grain lifecycle
and maybe abstract it like MyStateGrain<TState>

**Comment by JillHeaden** [comment]
Could someone write up an example of how to map the states of grain stored in different tables?
Possible title: **How to make per data per column in relational database for specific grain<T>.** (?)

Considerations (which I pulled from the question above in an attempt to consolidate this information):
- Using Grain<T>as a complete/universal solution for state persistence
- Implementing your own ReadStateAsync/WriteStateAsync/..., and hook them into grain lifecycle and maybe abstract it like MyStateGrain
- Database transaction, failure handling and so on

I would be glad for anyone's rough notes about this.

**Comment by veikkoeeva** [comment]
Maybe one question is that why not use state from the grain as in every application as usually is separate tables and joins are needed? Maybe Zop.Orleans is the answer. :)

@csyszf Indeed, the current default provider has the idea of one table that is a bag for all types.

@JillHeaden See the need about separate tables. In the current system one might just create separate tables per type and modify the queries accordingly, even on the fly (requires a bit of post 2.0 work, discussed elsewhere). Certainly separating `Storage` table into a separate schema and filegroup are desirable from security, performance, compliance (GDPR) and disaster recovery perspectives. However, it's not possible for the framework to quess these parameters. Though Orleans works just fine if the interface holds, i.e. the parameter types, names and associated queries are respected.

With regards to `Storage` specifically other design considerations were a well performing index even when fragmented (so, low maintenance, but it requires a few states to avoid potential deadlocking due to index range locks). In addition to picking up schema, one could modify the table to be in-memory one (and use compiled procedures) for performance and the rest of Orleans wouldn't notice (provided the interface holds, i.e. parameter names and types with the query keys Orleans uses).

The same goes with return values. The script should have commented that it checks the version number or exception to determine either failure or success and acts accordingly. More notes at https://gitter.im/dotnet/orleans?at=5b179c9c160c567d16093610 and at https://github.com/dotnet/orleans/issues/4625#issuecomment-394990359.

Maybe some of this feels complicated, I mean schemas and filegroups and mostly people just want things to work, but they're rather essential for a well running application. :)

**Comment by veikkoeeva** [comment]
@mokezhuhy Maybe the easiest way to migrate an old application with tables would be to use it from grains as the old application uses? I.e. some grains call the business logic functions of your application like they used to and then they use EF like they used to. If you can drop states as "blobs" to database, you can still query, if needed, the database and see the grains clearly by type, cluster and ID there in case that's important. The way `Storage` works in general is that Orleans tries to quickly locate the grain using the hashed, narrow index, and do a disk look-up for the actual data (RID in SQL Server parlor) and resolved hash collisions with real name comparison (usually there are none, but it's possible).

**Comment by sergeybykov** [comment]
Looks like this has been answered. Feel free to reopen if not.
