### ISSUE TITLE
Overridden method OnDeactivateAsync not called if CollectionAge set in seconds range

### ISSUE THREAD

**Issue by rdcm** [dotnet/orleans#4651]
Dependencies:

```
    <PackageReference Include="Microsoft.Orleans.Core" Version="2.0.3" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Orleans.OrleansCodeGenerator.Build" Version="2.0.3" />
    <PackageReference Include="Microsoft.Orleans.OrleansConsulUtils" Version="2.0.0" />
    <PackageReference Include="Microsoft.Orleans.OrleansProviders" Version="2.0.0" />
    <PackageReference Include="Microsoft.Orleans.OrleansRuntime" Version="2.0.3" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="2.0.3" />
```

Silo host configuration:
```
                .Configure<GrainCollectionOptions>(options =>
                {
                    // Set the value of CollectionAge to 10 minutes for all grain
                    options.CollectionAge = TimeSpan.FromMinutes(10);
                    // Override the value of CollectionAge to 5 minutes for MyGrainImplementation
                    options.ClassSpecificCollectionAge[typeof(SessionGrain).FullName] = TimeSpan.FromSeconds(30);
                })
```

Overridden  grain methods:
```
        public override async Task OnActivateAsync()
        {
            _session = await _sessionRepository.Get(Guid.NewGuid());
        }

        public override async Task OnDeactivateAsync()
        {
            await _sessionRepository.Save(_session);
        }
```

With TimeSpan.FromMinutes( ... ); OnDeactivateAsync work as expected.

**Comment by sergeybykov** [comment]
I'm not sure setting `CollectionAge` to less than a minute is even supported with the default collection quantum of 1 minute. Regardless, do you know if the grain gets deactivated at all? I suspect this might be the issue - the grain isn't getting collected, and because of that, `OnDeactivateAsync` doesn't get called.

**Comment by rdcm** [comment]
For grain with short life cycle(30 seconds), finalizer succefully called, after  `OnActivateAsync`.

OrleansDashboard not detect this grain. Does this mean that grain not appear into "silo"? How can I verify that the grain was successfully created in silo?

**Comment by sergeybykov** [comment]
By "finalizer" do you mean `OnDeactivateAsync`? If that's the case, does that mean that you are not seeing the problem you put in the title: "Overridden method OnDeactivateAsync not called if CollectionAge set in seconds range"?

>OrleansDashboard not detect this grain.

What does this mean exactly? My understanding is that Dashboard shows periodic snapshots, so a particular grain that gets deactivated quickly may not get captured and reflected in a snapshot. People more familiar with Dashboard might correct me.

>Does this mean that grain not appear in "silo"?

A grain can only get activated in a silo.

>How can I verify that the grain was successfully created in silo?

Generally, a grain gets activated because something (another grain or a client) calls its method. The caller should see a response from the grain. In addition, the grain can execute nearly any code: log events, write to storage, make calls to web services, etc. So there are many ways to discover that the grain is executing. But the most direct one is its responses to invocations.

**Comment by rdcm** [comment]
>By "finalizer" do you mean OnDeactivateAsync?

No. I mean this:

```
        ~PlayerGrain()
        {
            Console.WriteLine("destructed");
        }
```

>What does this mean exactly?

No PlayerGrain on snapshots. This behavior does not look like memory leak in silo, but `OnDeactivateAsync` not called. 

Are there other cases when `OnDeactivateAsync` may be not called? I consider this method for placement in it logic for save grain state to store. The loss of state is an undesirable case.

**Comment by richorama** [comment]
The dashboard calls the management grain once a second to collect the results from `GetSimpleGrainStatistics`, which includes the number of activations of each grain type. 

So unless the grain is active for <1 second, it should appear in the dashboard.

**Comment by sergeybykov** [comment]
@rdcm Sounds like what you described shouldn't be happening. Could you double-check that `PlayerGrain`s get activated but the Dashboard never shows them.

**Comment by rdcm** [comment]
@sergeybykov 
My results after sending several requests to controller. All grains successfully invoke `OnActivateAsync` method.
If it matter, i run this code in docker container with consul.

Silo host settings:

```
                .UseDashboard(opt =>
                {
                    opt.Port = settings.Dashboard.Port;
                })
                .Configure<GrainCollectionOptions>(options =>
                {
                    options.CollectionAge = TimeSpan.FromMinutes(1);
                    options.ClassSpecificCollectionAge[typeof(PlayerGrain).FullName] = TimeSpan.FromSeconds(30);
                })
```
Default refresh interval:

```
public int CounterUpdateIntervalMs { get; set; } = 1000;
```

Controller code:

```
        [HttpGet("test")]
        public async Task<IActionResult> Get()
        {
            var session = _grainFactory.GetGrain<ISessionGrain>(Guid.NewGuid());
            var player = _grainFactory.GetGrain<IPlayerGrain>(Guid.NewGuid());

            await Task.WhenAll(session.SayHello(), player.SayHello());

            return Ok(new { state = "Ok" });
        }
```

Dashboard screen:
https://gyazo.com/ed71c6ab42e70fe73b46e7f6abf90300

**Comment by sergeybykov** [comment]
I suggest you try calling `ManagementGrains`'s `GetSimpleGrainStatistics` and `GetDetailedGrainStatistics` methods programmatically to check that the runtime actually reports those grains. If that ends up being the case, then it would point to Dashboard as the culprit I think.
