### ISSUE TITLE
What does it take to run Orleans on AWS?

### ISSUE THREAD

**Issue by attilah** [dotnet/orleans#473]
Orleans currently has some Azure ties, system store for example.

What modifications needed to make it run on AWS only services?

**Comment by gabikliot** [comment]
That's a great question, thank you!

There are 2 parts to this answer: Hosting and System Store.
**Hosting**:
As being a library, Orleans can essentially be hosted anywhere: Azure, on Prem, AWS or any other Cloud provider. Being cross platform not tight to any specific hosting model has been our goal.

On AWS you will deploy your own VMs with Windows and .NET 4.5 and run Orleans inside. That should work out of the box. 
In the future, you would be able to do even better. When Orleans will run on coreclr (we have an open issue on that #368 and #407) you will be able to host coreclr directly on Linux for example. Or you could run Orleans on Mono. And by deploying with Docker, you will be able to host the same OS (Windows or Linux) inside Docker and deploy across any Cloud provider. That is of course when Docker will be fully supported by windows and Azure, which seems to be coming pretty soon.

**System Store**:
System Store is an internal runtime component where runtime stores some of its critical meta data, basically the cluster configuration (what we call membership) and persistent reminders. One can think about System Store as a configuration service for Orleans. A lot of other distributed platform take a hard dependency on Zookeeper for example to store cluster configuration. Orleans instead initially took a hard dependency on Azure Table Storage to store its cluster configuration. But this has been a  while ago and since then, based o customers feedback, we provided a pluggable System Store. What Orleans comes now out of the box is Azure Table and SQL server. More options for system store are being added now by the community.
Specifically for AWS the options are:
1) **Use Azure Table**. One can run host Orleans in AWS and still use Azure Table for system store. All you will need is Azure storage account. Orleans will automatically use this account to store the system store data inside Azure Table, while running in AWS.
2) **Use the existing SQL server option**. In this option you will nee to deploy an instance of SQL server inside your AWS deployment (or maybe host this SQL server somewhere else and just allow Orleans to access it) and configure Orleans to use that SQ server.
3) **Use Zookeeper**. Adding Zookeeper as another system store is currently work in progress (issue #382) and will hopefully be done some time soon. In this option you will deploy a ZK cluster along side Orleans cluster inside your AWS service and configure Orleans to sue ZK for system store.
4) **Write AWS based system store**. For example, one can build an Orleans system store based on AmazonSimpleDB. The [conditional put feature of Amazon Simple DB](http://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/ConditionalPut.html) is equivalent to eTag mechanism in Azure Table store that we are using and it thus should be relatively easy to build such a AmazonSimpleDB based system store. This is perhaps the best option, since as opposite to SQL and ZK in this option you do not need to manage SQL or ZK cluster. It is a fully managed system store option, since AmazonSimpleDB  is managed for you by AWS. Thus it is the most robust of all options. We hope that the community will build such a system store and open source it, for everyone to use. We can provide guidance and help. More details on how to do that can be found here https://github.com/dotnet/orleans/issues/382#issuecomment-99548820.

**Comment by jthelin** [comment]
FYI, PR #493 is now merged in to master branch and adds support for using ZooKeeper for cluster membership rather than Azure Table.

**Comment by ElanHasson** [comment]
@gabikliot will Orleans run on mono today?

**Comment by sergeybykov** [comment]
@ElanHasson We never tried but @richorama showed Orleans running on Mono quite a while ago.

**Comment by gabikliot** [comment]
Check this out: https://github.com/chgeuer/docker-playground/blob/master/docker-readme.md
Running Orleans on Docker and Mono.
