### ISSUE TITLE
Orleans performance issue with GetGrain and saving to Event Store

### ISSUE THREAD

**Issue by darrrrek** [dotnet/orleans#4730]
I'm using Orelans (2.0.3) with SQL database (2017). Database is on the same host where application is located. Currently I'm struggling with performance issue for:

```
var purchaseGrain = _grainFactory.GetGrain<IPurchaseGrain>(id);
await purchaseGrain.Create(id, command);
```

**Create** method for test purposes do nothing and looks like:

```
public Task Create(Guid id, CreatePurchaseCommand message)
        {
            var @event = new PurchaseCreatedEvent
            {
                Id = id,
                Name = message.Name,
                Type = message.Type
            };

            return Task.CompletedTask;
        }
```

Time execution of this part takes a long time:

```
var purchaseGrain = _grainFactory.GetGrain<IPurchaseGrain>(id);
await purchaseGrain.Create(id, command);
```

Example time execution in miliseconds:
20-40ms

I have also problem with the following part:

```
protected async Task Publish(IEvent @event)
        {
            RaiseEvent(@event); //Rise event works very fast
            await ConfirmEvents(); // here is long time execution issue
        }
```

Example execution time in miliseconds for **ConfirmEvents**:
20-50ms

Those delays causes that I can't process more than 15-30 messages/s.

Everything is working on my local machine with CPU intel core i7, 16 GB of RAM.
Please let me know, which configruation should I provide to find the reason of this long time execution.
Thanks for any help !

**Comment by jason-bragg** [comment]
The Create call doesn't seem to do much so I see no reason why it should be slow.  Is every create call taking that long, or just the first?  The first call may take longer because the grain needs be activated and it's state loaded from storage before the call can be processed.  I'm not familiar with the SQL providers, but a 20-40ms storage call would not surprise me.

The Publish call is also, to my knowledge, a storage call, so 20-50ms does not surprise me.  For a single grain, persisting on every call, the messages/sec will not be high.

If you want to check to see if it's the storage layer (SQL) slowing down the application, configured the service to use the memory storage and see how fast it is.  This should give you a baseline of your best case performance.

If storage is your bottleneck, you'll likely need to scale across multiple grains (10 grains == 150-300 messages/sec), or batch events into single storage calls.

@veikkoeeva, probably has a better idea of what sort of performance you should suspect from the SQL providers.

**Comment by veikkoeeva** [comment]
Indeed, having something an in-memory provider would yield contrast. Especially if SQL Server has cached the table to memory, the queries ought to be quite fast. I just took https://codeopinion.com/event-sourced-orleans-grain/ and run under XUnit to LocalDb and from raising an event to confirming takes about 25 ms for one grain on my SSD.

The indexing should get faster when there are more grains. When there isn't state (the version of a state is `NULL`), a pessimistic lock is taken for rows. If there aren't any grains or one or two grains, the locking overhead can skew results to a higher end.

If you'd like to compare and have a test project to share, I can run it and give back the results.

Somethhing like

```
SET STATISTICS TIME ON;
SELECT * FROM Storage;
SET STATISTICS TIME OFF;

SET STATISTICS PROFILE ON;
SELECT * FROM Storage;
SET STATISTICS PROFILE OFF;
```
would yield some further comparison for system performance.
