### ISSUE TITLE
Exception thrown during OnActivateAsync not posted to client?

### ISSUE THREAD

**Issue by mokezhuhy** [dotnet/orleans#4748]
I try this: a grain implemented Grain(T), while the entity T can not be found in storage during OnActivateAsync, a EntityNotFoundException will be thrown. And the exception will not be posted to the client. How can I handle this error?

**Comment by mokezhuhy** [comment]
Hi @ReubenBond , is my scenario, a grain corresponds to an entity stored in database, and if the entity does not exist in the database, an exception will be thrown during the grain activation. However the exception is not sent to the client side, and just displayed on the server side. 

In my opinion, the silo should not create an new entity that does not exist(e.g. a lottery that may contain information on the prize, but currently the silo does it). Something wrong with me?

More info see here #4640 

Thank you.

**Comment by ReubenBond** [comment]
In this case, you are sending an exception to the client which the client does not know how to deserialize (because the exception is defined in a silo-only assembly).

You can move the exception to a common assembly or wrap the exception in a known, serializable type.

**Comment by mokezhuhy** [comment]
@ReubenBond , the EntityNotFoundException is defined in a common assembly, both client side and server site had referred to it, and I can directly new a new EntityNotFoundException.

**Comment by stephenlautier** [comment]
This issue is quite severe as it will cause the client (request from the web) to never complete (see screenshot).

We tried to handle it with the `IncomingCallFilter`, as 
 https://dotnet.github.io/orleans/Documentation/grains/interceptors.html#exception-conversion however errors on `OnActivateAsync` won't be captured as its not part of the interception.

To be honest, I don't see adding the library on the client a solution (ok for a quick workaround), as basically we would need to add all libraries on the client just as we have on the server, as they might have specific exceptions.

I believe we need a way to handle activations similar to the call filters e.g. pluggable middleware globally. Just thinking now, perhaps we can use the `DefaultGrainActivator` and wrap that? A drawback as it is it doesn't allow pluggability so we would need to handle it ourselves.

![image](https://user-images.githubusercontent.com/3908723/56037899-c6679000-5d30-11e9-9516-231983cc2d11.png)

**Comment by ReubenBond** [comment]
OnActivateAsync exceptions are already propagated back to callers but the problem in this particular issue is:

* The `EntityNotFoundException`  type does not have a serialization constructor (of the form `public EntityNotFoundException(SerializationInfo info, StreamingContext context) : base(info, context)`) - Exception types are serialized using `BinaryFormatter`, so they need to conform to the `System.ISerializable` pattern (which requires that constructor).
* Deserialization exceptions from *response* messages were not being propagated to callers.

The latter is fixed in #5998

**Comment by stephenlautier** [comment]
@ReubenBond thanks for your explanation. 

Re the `EntityNotFound` what I wanted to achieve is to add a global try/catch wrapper (middleware/handler or so) for unknown errors to be logged and rethrown as simpler known errors during Activation. 
Especially since if you use a library method within Activation and they can throw `Exceptions`  which are not properly serializable its a bit painful to add try/catch on each Grain's activation.

What we ended up doing is a base Grain(s) for us with try/catch in order to avoid this from happening
