### ISSUE TITLE
Event hub stream provider questions

### ISSUE THREAD

**Issue by galmicrosoft** [dotnet/orleans#4758]
Hi All,

I have some questions regarding streaming in Orleans in general, and specifically streaming using Event Hub Stream Provider.
I’ll briefly describe my scenario: I have a worker role (non-Orleans) that gets messages from an event hub. Each message belongs to some provider (there can be thousands of providers). The worker role then sends the message to a grain for this specific provider using streaming (there’s a separate stream for each provider grain). The processing of each message by the grain may take some time, and that’s why I want to send the message over a persistent queue, to decouple the sending from the handling of the message (unlike SMS provider). 
In addition, there’s an accumulation of data in the grain itself, and it in its turn sends the accumulated data to another service. That’s why I want the stream to be rewindable – if the silo crushed before the grain had sent the data batch, I want to process the messages from the begging of the batch.
That’s why the event hub stream provider seems like the correct choice, and that’s how I was thinking of using it:
When the first message of the batch arrives to the grain, I will save its token in the (persisted) state of the grain. When the batch is sent, I’ll update the token to the last message received, and use a flag to indicate that I want to get messages with a newer token (the first message of the next batch). In this way, if the silo crushes before I’ve sent the batch, the grain will start processing messages from the last token saved.
1.	Can I consider event hub stream provider as ready for production systems? I don’t see any documentation for it, but I see it’s been released long time ago and it’s been used by 343 industries.
2.	How many different streams does the event hub stream provider support? In the documentation states that “By default Orleans Streaming is targeted to support a large number of relatively small streams”. So it’s seems ok, but I wanted to be sure.
3.	When I played with the event hub stream provider I tried to pass null to the StreamSequenceToken parameter on ResumeAsync, expecting it to provider new events. But every time I started the Silo I got all the events that I previously sent. I have a workaround for this that I mentioned above, but I’m wondering what the reason for this behavior is. 

Thanks!
Gal

**Comment by jason-bragg** [comment]
@galmicrosoft, I apologize for the delayed reply.  Eventhub streams are being used in production in 343 and other internal groups.  We are still improving the system, so using it may mean code changes between Orleans releases, but I suspect it's a viable solution for what you're doing.

We don't yet have much documentation on the Eventhub streams, so the best place to look to learn about them is our tests.
https://github.com/dotnet/orleans/tree/master/test/Extensions/ServiceBus.Tests

For recovery patterns similar to what you've described you may want to check out the stream recoverability tests:
https://github.com/dotnet/orleans/blob/master/test/Extensions/ServiceBus.Tests/Streaming/EHImplicitSubscriptionStreamRecoveryTests.cs

Special attention should be given to the types of faults generated in the recovery test grains as most of those cover edge cases that have been encountered in production services.  They cover recovery from transient errors and expected behaviors for non-transient errors like poison messages.
https://github.com/dotnet/orleans/blob/master/test/Grains/TestGrains/ImplicitSubscription_TransientError_RecoverableStream_CollectorGrain.cs
https://github.com/dotnet/orleans/blob/master/test/Grains/TestGrains/ImplicitSubscription_NonTransientError_RecoverableStream_CollectorGrain.cs

In addition, eventhub streams can be customized to read data formats other than the default format, so you may be able to use eventhub streams to read from the original hubs and process the data directly rather than reading it, then writing back into Orleans streams to be processed.  This is admittedly and advanced capability and will incur a greater learning curve, but in the end it may save an additional hop through eventhub.

**Comment by galmicrosoft** [comment]
Thanks @jason-bragg :)
The tests are really helpful for me, this is a very similar scenario to what I have.
You mentioned an option to read directly from the first EH. Do you have an example for it?

Gal

**Comment by jason-bragg** [comment]
@galmicrosoft We've an issue to clean up the extensibility point, which has some details in it (Stream data adapter #4621), but we've no working samples or tests for that capability, unfortunately.

Closest thing we have is a test data adapter which treats all of the data in a partition as being in the same stream.

https://github.com/dotnet/orleans/blob/master/test/Extensions/ServiceBus.Tests/TestStreamProviders/StreamPerPartitionEventHubStreamProvider.cs

We recognize that the patterns used for customizing the data format are poor, hence the issue #4621, but it is possible and would likely make your service more efficient.

**Comment by rafikiassumani-msft** [comment]
We are closing this issue due to a lack of activity for the past 3 years. Please use the following issue as recommended by `jason-bragg`  to track further updates on this: #4621
