### ISSUE TITLE
Service fabric clustering graceful shutdown

### ISSUE THREAD

**Issue by talarari** [dotnet/orleans#4777]
Hey, We are currently using service fabric clustering in orleans 1.5.3.
We're experiencing a lot of noise (errors, slow execution) while doing a rolling upgrade. 
From what i've read here:
https://github.com/dotnet/orleans/blob/a2ad7e375af89f7920c3c6f272b972d5f3710774/src/OrleansServiceFabricUtils/OrleansCommunicationListener.cs#L120
it looks like this is an ungraceful shutdown, which could cause this, am i right?
I tried to change CloseAsync to do shutDownOrleansSilo instead of stop, had no effect at all.

My assumption is that graceful shutdown does not work with service fabric clustering, only with table membership clustering (the silo marks itself as shutting down, finish requests and dont take any more work).
Is this  true?

**Comment by ReubenBond** [comment]
@talarari 
> My assumption is that graceful shutdown does not work with service fabric clustering, only with table membership clustering (the silo marks itself as shutting down, finish requests and dont take any more work).

Yes, there is no way to signal to the Service Fabric Naming Service that the silo is preparing to terminate, which means that requests will keep coming until the end.

We stopped publishing that package because of issues like this. I hope to be able to address some of these issues so that we can create a better user experience on Service Fabric.

For now, my recommendation would be to use Service Fabric for hosting but not clustering.

**Comment by talarari** [comment]
We switched to table membership and things are looking better. Thanks.
