### ISSUE TITLE
Allow the Grain state to define Partition key and Row key for Table Storage

### ISSUE THREAD

**Issue by aRajeshKumar** [dotnet/orleans#4779]
While enabling the state to persist in the storage, we should have a mechanism to override the Partition Key /Row key so that data can be stored and retrieved effectively.

**Comment by ReubenBond** [comment]
How would you like the key selection to work? I imagine you could use a lambda when configuring the particular storage provider. Clearly the configuration would need to be per-storage-provider, since the concept of a partition key doesn't apply to SQL, for example.

Alternatively from a lambda, you could have an interface which is registered using the same name as the storage provider.

Note that the conversion would need (want) to be unique or you might have grains clashing with each other in unexpected ways.

**Comment by arajeshkumar** [comment]
Storage provider option should be able to override the PartitionKey and RowKey. (Example: TableName can be overridden for TableStorage and ContainerName for Blob storage)

SQL table also requires a primary key so that the data can be indexed correctly. So, the need to have a mechanism for this (though I am not sure about it right at the moment).

**Comment by ReubenBond** [comment]
Are you saying you'd like a single string for partition key?

It's different to TableName because this is a per grain key, not a global key.

Generally we position the persistence model as a simple and simplistic solution which is not supposed to suit all use cases (not an ORM by any means). That being said, I'm not opposed to exposing more knobs to make it suit more use cases.
