### ISSUE TITLE
Serialization errors on exceptions thrown from grain methods cause client timeouts

### ISSUE THREAD

**Issue by JoshCollinsMSFT** [dotnet/orleans#4793]
Take grain interface:

```
interface IFoo
{
    Task DoSomething();
}
```

If, for whatever reason, DoSomething() encounters an unhandled exception that reaches the runtime, and the runtime cannot serialize it back to the client, the runtime sends nothing back to the client causing an eventual client timeout.

The expected behavior is the client would receive some generic serialization failed exception.  Without this these types of issues are very difficult to debug.

**Comment by ReubenBond** [comment]
I believe the issue and crux of the fix is as follows:

```diff
+@@ -117,12 +126,13 @@ protected override void OnMessageSerializationFailure(Message msg, Exception exc
             {
                 messageCenter.SendRejection(msg, Message.RejectionTypes.Unrecoverable, exc.ToString());
             }
-            else if (msg.Direction == Message.Directions.Response && msg.Result != Message.ResponseTypes.Error)
+            else if (msg.Direction == Message.Directions.Response && msg.ForwardCount < this.options.MaxForwardCount)
             {
                 // if we failed sending an original response, turn the response body into an error and reply with it.
                 // unless the response was already an error response (so we don't loop forever).
                 msg.Result = Message.ResponseTypes.Error;
                 msg.BodyObject = Response.ExceptionResponse(exc);
+                msg.ForwardCount++;
                 messageCenter.SendMessage(msg);
             }
```

Perhaps using ForwardCount like that is inappropriate and the message should be tagged in another way.

Alternatively, we could skip this check, since this method is only ever called upon serialization failure and therefore the only exception which we should see here is SerializationException (must ensure there's no InnerException, must also verify that assertion)
