### ISSUE TITLE
ClientBuilder cause to "'The runtime has encountered a fatal error. The address of the error was at 0x6b6541c3, on thread 0x58c4"

### ISSUE THREAD

**Issue by ifle** [dotnet/orleans#4807]
I have crash .NET in web application during initialization of Orleans Client. 
I use .NET 4.6.2 and can provide the project that reproduce this error. 
This error happen in case when application try startup second time and silo is still unavailable.
The reproduce steps:
1. Web Application start up.
2. orleans client initialization try to connect to silo. After several attempts it's failed
2. User again navigate to the page. Web application try again start up and failed with .NET fatal error when called Build function of ClientBuilder

I debugged with SourceLink.
That happen in ApplicationPartManager.PopulateFeature function

![image](https://user-images.githubusercontent.com/1140474/43445466-10041e68-94af-11e8-9933-e7ba2a1b7fba.png)

**Comment by ReubenBond** [comment]
I can guess a couple of things:
1. Mismatched assemblies (try full clean via git clean -xfd after committing your work, ensure package versions are consistent, and try again)
2. RAM malfunction.

The particular error code is what happens when trying to dereference a null pointer at the native level, or otherwise accessing unmapped or inaccessible memory, but that error can also occur with faulty RAM.

Just wild guesses, but worth a shot.

**Comment by ifle** [comment]
Thanks @ReubenBond 
1. Do you mean version conflicts?
2. We can reproduce it on our Azure test environment too.

**Comment by ReubenBond** [comment]
I mean conflicts/inconsistencies between different assembly versions. I wonder where exactly the error is coming from... That method doesn't do anything exotic. It can force some assemblies to be loaded, though, and some type initializers to be called, so it's possible that one of those things are causing this error

**Comment by ifle** [comment]
It makes sense. I will check. Thanks

**Comment by ifle** [comment]
Conflicts between different assembly versions cause to this error. After fixing all works fine. 
@ReubenBond Thanks a lot.
