### ISSUE TITLE
Remove the callchain information for the OneWay message

### ISSUE THREAD

**Issue by linluxiang** [dotnet/orleans#4808]
Recently I've met a deadlock exception caused by a OneWay message. As far as I know, the sender of the one-way message will not wailt for the response of the message. This means that, even if the callee calls the function on the same grain, the message will be added to the next position of messaging queue and will not cause a deadlock. So we should add a check on the line below, if it is a OneWay message, the call chain information should not be passed to next calls. 

https://github.com/dotnet/orleans/blob/e2b25a695767ae5746ffe47218c1331427997894/src/Orleans.Runtime/Core/InsideRuntimeClient.cs#L292

I don't know if I'm correct. If the thought is correct, I will make a pull-request to fix it.

**Comment by ReubenBond** [comment]
@linluxiang why should OneWay calls be any different? As far as interleaving of messages is concerned, I believe they should act the same.

Consider this scenario
```
1. GrainA calls a regular method on GrainB
  2. GrainB calls a OneWay method on GrainA
  3. GrainB waits (with retries of 2) for GrainA to call one of its methods to set some condition
4. Grain B returns the original method
```

In this scenario, it shouldn't matter if 2. is implemented using a OneWay method or not: they are in the same call chain.

I may not be understanding the issue correctly

**Comment by linluxiang** [comment]
@ReubenBond I think for Step 3, the GrainB will not wait for GrainA to call it back if it's a OneWay method. Am I correct? Because OneWay methods are void function() and cannot be awaited.

**Comment by ReubenBond** [comment]
@linluxiang What I am saying is that grain B could wait for a call from Grain A, since it's all within the same call chain, that should be expected to work.

```C#
public class GrainB : Grain, IGrainB
{
  private int wasCalled = 0;

  public async RegularMethod(IGrainA grainA)
  {
    while (this.wasCalled == 0)
    {
      grainA.OneWayMethod();
      await Task.Delay(1000);
    } 
  }

  // GrainA will call this method when it receives OneWayMethod()
  public CallbackFromGrainA()
  {
    this.wasCalled++;
    return Task.CompletedTask;
  }
}
```

This example is contrived, but I think it demonstrates the idea that OneWay methods should not behave differently.

**Comment by linluxiang** [comment]
@ReubenBond  Yes your example will definitely causes a deadlock. But the deadlock detection module will throw a DeadlockException for the code below which actullay does not cause a deadlock.

```
public class GrainB : Grain, IGrainB
{
  public async RegularMethod(IGrainA grainA)
  {
      // Return immediately and will not cause a deadlock.
      grainA.OneWayMethod();
  }

  // A DeadlockException will be thrown here.
  public CallbackFromGrainA()
  {
    return Task.CompletedTask;
  }
}
```

From my point of view, the deadlock decection module should only detect the deadlocks caused by framework, not the ones caused by business logic. For example, for a deadlock callchain GrainA calling GrainB calling GrainC calling GrainA. A oneway function call will break this call chain and not cause a deadlock from the framework point of view. My suggestion is that, the deadlock detection should do this "Breaking callchain", which means remove the callchain information when it receives a OneWay message.

For the deadlocks caused by logic, like the example you gave above, we could found it when the calls to RegularMethod is timedout.

**Comment by ReubenBond** [comment]
@dVakulen do you have thoughts on this? My inclination is towards no change, but input is valued

**Comment by dVakulen** [comment]
@ReubenBond Assuming that simpler patter is expected to be more common in code bases - the one way retrieving of additional information from calee might trigger much more false `DeadlockException`, than could be revealed for artificial replacements of simple two-way call.

But it's also choice between false negatives and positives, and the deadlock detection mechanism is specifically designed to detect some cryptic cases, which would be hard to find in other way. Lessening the amount of cases it handles doesn't seem to be viable way. 

Most optimal alternatives are to make configurable either the resetting of  call chain information on `OneWay` message, or behavior of deadlock detection  - instead of throwing exception, such information could be just logged, so that the program flow could continue in presence of such false positives and actual problems would able to be detected.

**Comment by Xanatus** [comment]
I think there should be at least some way to opt out of a call chain somehow.
When OneWay messages don't do that, then there is no way at all to do it at the moment.

What that means is that when CallChainReentracy is allowed, there is no way at all to escape out of interleaved methods (esspecialy timers) which limits their use a lot.

Since the this.AsReference() trick isn't working anymore, I was hoping for OneWay messages to achive the same effect.
Maybe we could have an alternate Attribute to cancel callshains at will?
