### ISSUE TITLE
In the silo startup process,it will throw error:System.Reflection.ReflectionTypeLoadException

### ISSUE THREAD

**Issue by HermesNew** [dotnet/orleans#4817]
Hello,

The version of Orleans is 1.5.4 .
This is the error message:

[2018-08-04 07:51:13.235 GMT     1	WARNING	101723	CodeGenerator	192.168.31.68:20003]	Exception loading types from assembly 'Services.ES.Implement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null': 
Exc level 0: System.Reflection.ReflectionTypeLoadException: 无法加载一个或多个请求的类型。有关更多信息，请检索 LoaderExceptions 属性。
   在 System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   在 System.Reflection.RuntimeAssembly.get_DefinedTypes()
   在 Orleans.Runtime.TypeUtils.GetDefinedTypes(Assembly assembly, Logger logger)
Exc level 1: System.TypeLoadException: 未能从程序集“Services.ES.Implement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”中加载类型“Services.ES.Implement.AccountIndexServiceGrain”。

Although throw the error,it's working properly. I want to know why it will show the error? And how to fixed this error?

**Comment by HermesNew** [comment]
I used  Assembly.DefinedTypes  to test the Assembly, I didn't find any exceptions.

**Comment by ReubenBond** [comment]
This error is caused by the assembly loading which Orleans versions prior to 2.0 performed. It is not a worrisome error. It occurs when the assembly loader tries to load Assembly A using "reflection-only loading" and then examine the types in A but encounters a type which belongs to Assembly But which has not been loaded yet.

If you wanted the errors to go away, you can force every referenced assembly to load before starting Orleans. It's not a worrisome error, though.

In Orleans 2.0, we allow you to manually specify which assemblies to examine. There is a behavior to load assemblies by default but without using "reflection-only loading". Additionally, Orleans 2.0 does not need to examine many types in each assembly, so there is much less issue. Because it doesn't use reflection-only loading, it can load assemblies on-demand when examining types.

So the error you're seeing isn't something to worry about and the behaviour is improved in 2.0.

**Comment by HermesNew** [comment]
ok,thanks.
