### ISSUE TITLE
ManagementGrain.ForceActivationCollection with zero ageLimit causes undesired effects

### ISSUE THREAD

**Issue by alirezajm** [dotnet/orleans#4908]
Calling ManagementGrain.ForceActivationCollection(TimeSpan.Zero) collects every grain, including system grains and the ManagementGrain itself. Which effectively almost restarts the silo and causes the said grain call to timeout.

Shouldn't this exclude some grains (management grain, pubsub, etc.)? or at least make the TimeSpan.Zero value an invalid one? 

I can't think of a scenario where current behavior would be useful.

**Comment by alirezajm** [comment]
@benjaminpetit any word on this?

**Comment by ReubenBond** [comment]
I'm not convinced that we should be doing anything to prevent the user from calling with a zero or very short timespan.

If you'd like to submit a PR to implement a minimum value, then please feel free. I wouldn't be opposed to merging it.

Some grains are already excluded from activation collection, so we could add a mechanism to exclude more grains or to exclude them more generally (eg an attribute, like the recently added attribute in #4890). I would be wary of a general mechanism, though, since it's an anti-pattern to have activations live forever.
