### ISSUE TITLE
Rebalance grains to new server on request

### ISSUE THREAD

**Issue by debarisi** [dotnet/orleans#4925]
Hi,

Is there any option to migrate grain with its state to a new silohost?

For now, we created our own solution.

1. Monitor number of silohost
2. Monitor number of grains on each silo host
3. When new siloHost join cluster - Call DeactivateOnIdle on grains that are on the busiest server 

Maybe to have an easy implementation for archiving the same solution?

1. Fetch statistics - number of siloHosts, number of grain (one type) per siloHost
2. Rebalance grains (Need to be atomic)
    a) Take the state of grain
    b) Deactivate grain on SiloHost 1
    b) Activate grain on SiloHost 2 (do not call onActivate event!)
    c) Load grain state on SiloHost 2

Best,

Dean

**Comment by sergeybykov** [comment]
In our experience, rebalancing of load is a challenging task that easily leads to many pitfalls. That's the main reason we've been conservative about trying to do it.

Since usually each silo holds a number of actively used grains as well as a larger number of idle ones waiting to get deactivated, the simple number of activations doesn't necessarily correlate with the load. That's the danger of `[ActivationCountBasedPlacement]` - it forces new activations to be placed on the silo with the lowest *number* of grains, but that means that most of those activations will be actively used, and hence create a disproportional load on a new silo despite seemingly low number of grain when compared to other silo with lots of idle grains.

Then there's cost of activation, which is very application specific and depends on the amount of state that needs to be loaded and processed plus other initialization work the grain might need to do.

One approach that we've seen people apply is to code in their grains to deactivate random grains at a certain rate. This creates a constant flow of new activations (used grains getting reactivated) and speeds up rebalancing. On the other hand, this approach creates unnecessary churn and load when there aren't any changes in the cluster.

Maybe there are better approached, but that's where we are at so far.

**Comment by debarisi** [comment]
@sergeybykov  Thanks for detail explanation.

We are aware of the problems you mention above. 
What we were thinking is that `[ActivationCountBasedPlacement]` is the perfect fit for auto-rebalancing grains to new nodes.
Also, auto-rebalancing should be configurable so that problems you mention like the cost of activation, can be fine-tuned by a developer.

Best,
Dean

**Comment by sergeybykov** [comment]
>What we were thinking is that [ActivationCountBasedPlacement] is the perfect fit for auto-rebalancing grains to new nodes.

Can you elaborate on what you mean by that? Say I have 50 silos running with 1 million grain activations across them, some are active (let's say 10%), most are idle. I'm adding 10 more silos to the cluster. How do I get to a balanced distribution of a) active 100K grain or b) both active 100K and idle 900K across now 60 silos?

**Comment by debarisi** [comment]
I totally understand what you are trying to point to me.
Our situation is little different in our scenario, our grains are 'workers' and they have constantly something to do so answer would be B.

Our example 
Data that we are processing is 'live stream of data' and because of a high burst of new data (on different grains) that needs to be processed we need to add more servers and it takes some time for a new server to deploy and be ready for use. For that time burst of new activation is already activated on current servers. 
That's why we now manually call `DeactiveOnIdle`.
We are not talking about 100k grains, we are talking about 1k new grain activations in few seconds.

For the scenario that you mention above, probably, there is no simple solution. Everyone who is building application needs to know their needs and strategy how to apply grain balancing.
It is hard to know if idle grains could become active or not, or vice versa.

So, to keep it short. Rebalance only if you understand your data. 

I will close this discussion. For rebalance, there is a solution and we used it :) 

Best,
Dean
