### ISSUE TITLE
SQL Schema files should be mentioned in the documentation

### ISSUE THREAD

**Issue by skyflyer** [dotnet/orleans#4962]
The files are available in the [repo](https://github.com/dotnet/orleans/tree/master/src/AdoNet/Orleans.Clustering.AdoNet) but are not referenced in the 2.0 documentation. They are, referenced in the [1.5 documentation](https://dotnet.github.io/orleans/1.5/Documentation/Deployment-and-Operations/Configuration-Guide/Configuring-SQL-Tables.html). 

Perhaps these pages are a good candidate to mention how to setup cluster membership table:
* https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/server_configuration.html
* https://dotnet.github.io/orleans/Documentation/deployment/cluster_management.html

Other persistence specifics (i.e. how to setup Azure Table Storage, Consul, etc.) should be documented as well.

**Comment by ReubenBond** [comment]
I believe this was fixed in #6118. Docs are available at https://dotnet.github.io/orleans/docs/host/configuration_guide/adonet_configuration.html

There is no setup required for Azure Table Storage other than configuring the connection string, as documented in the "typical configurations" doc. We should consider per-provider docs, however.
