### ISSUE TITLE
Question: Use Orleans for distributed report generation?

### ISSUE THREAD

**Issue by FranKieCZ** [dotnet/orleans#503]
We would like to use Orleans to load balance the report generation process.  The concern we have is that some reports execute in seconds and some can take hours (extreme case) depending on the payload. 

Currently we have a process that allows a user to schedule a pre-defined report to run at a specified time  and we use a 3rd party report library to execute the report logic.  Internally the report library will execute some SQL and format the report. Within the report library there are essentially two phases in the process:

1. SQL Server running queries(s) - Orleans grain would be waiting for response.
2. Report engine formatting - Orleans grain would be busy running report engine format procedures.

Due to the two phases two reports may have vastly different resource needs due to how long the SQL process takes vs. the formatting and we don’t have a way to split the report generation into multiple steps.

Q: Does the large range in processing times and resource needs deter us from using Orleans?

**Comment by ElanHasson** [comment]
@johnazariah  is doing distributed reporting and put together a presentation on it: https://vimeo.com/97315938

**Comment by veikkoeeva** [comment]
@FranKieCZ Do you mean the library does the processing and Orleans just does waiting or that if Orleans code consumes CPU cycles?

I don't think the large processing time needs to be a problem, but maybe the question is that what should be in the database and why actively wait instead of starting the reporting procedure and checking the outcome periodically from some output (e.g. like output staging table).

I remember seeing a Word document on Orleans processing patterns somewhere in GitHub that touches upon some of this.

**Comment by sergeybykov** [comment]
@veikkoeeva Did you mean https://github.com/hataytuna/Distributed/blob/master/Applied%20Actor%20Model%20with%20Orleans%20v1.1.pdf?

**Comment by sergeybykov** [comment]
@FranKieCZ In general, Orleans is designed for low latency requests to grains with IO and long compute operations offloaded from Orleans threads to .NET thread pool or someplace else.

Orleans silo normally runs one app thread per CPU core for efficiency. Because of that anything that blocks a thread (e.g. by synchronously waiting for an IO operation) or performing a long running compute operation is taking away a precious resource and reduces system's responsiveness.

The recommended patterns are 1) to use asynchronous operations everywhere, for example when talking to a database; and 2) executed a short request to start a long running process somewhere, and then either asynchronously wait for its completion or poll periodically with a timer.

**Comment by veikkoeeva** [comment]
@sergeybykov That is the one. I better save it. :)
