### ISSUE TITLE
Small issues running Orleans2.1 ClusterClient on Mono/Unity/Android

### ISSUE THREAD

**Issue by slango0513** [dotnet/orleans#5097]
Hello, I am running Orleans 2.1 ClusterClient on Mono/Unity/Android. The common features work fine but following small problems:

1. 
https://github.com/dotnet/orleans/blob/b0fa5401891a2490bf99b95dca5d11c80df593d2/src/Orleans.Core/Runtime/RuntimeVersion.cs#L18

This line will throw an exception from GetVersionInfo because "thisProg.Location" param is empty under Android. 
The purpose of this line is only to print log, but it prevents the ClusterClient from launching under Android.
Hope that a checking of whether the file exists here can be added before calling GetVersionInfo, like:
`if (!File.Exists(thisProg.Location)) { return ApiVersion/"or some string else"; }`

2. 
https://github.com/dotnet/orleans/blob/b0fa5401891a2490bf99b95dca5d11c80df593d2/src/Orleans.Core/Configuration/ConfigUtilities.cs#L439

In this line, "netInterface.OperationalStatus" is always OperationalStatus.Unknow under Android/iOS, which will cause continuous continue and finnally to the bottom OrleansException throw.
I am currently changing this line to: 
`... != OperationalStatus.Up && netInterface.OperationalStatus != OperationalStatus.Unknown`
This change may not be universal, so I thought adding a property in ClientMessagingOptions would good, like:
`Func<NetworkInterface, bool> NetworkInterfaceFilter { get; set; }`
which can be configured during ClusterClient building and invoked in this line.

A question in addtion, how will the address returned by this method GetLocalIPAddress be used by ClusterClient?

Thanks!

**Comment by Vhab** [comment]
I know this doesn't directly answer your question, but it's probably useful information.

Unless you have a very specific use-case where you fully trust the Android client and the entire network path between (eg. using it only on an internal network or across a VPN bridge into a private network), you're probably going the wrong route with communicating with Orleans.

You should not publicly expose the Orleans silo to the internet as there's no security layer authenticating clients, nor restricting their access.

A more common setup is a simpler public API over http, signalr, or other transport you can secure, which then communicates with the Orleans cluster using the Orleans client.
Or since the latest version, with some extra setup, embed a public API directly inside the same silo process and communicating using the new direct client.

That said, if non of this is the case, feel free to ignore this reply :)

**Comment by slango0513** [comment]
Yes as you said, it's not a common way, the Android devices are untrusted clients.

The reason that made me choose this solution is mainly on long connections.

The game is latency sensitive. SignalR.Redis was considered, but its distributed cache causes some unnecessary delay. I am not familiar with front-end dev, so I failed to find a load balancing strategy that is as good as Orleans' PreferLocalPlacementAttribute to keep the latency below 50ms.

Later, a member of our community recommended a compromise solution, they are using Orleans as game servers with no gateway, which running in product environment for years. All the ports are mapped by firewall, and an authen token is required for connection. This gave me some confidence, but I am still not sure whether it is okay to expose the cluster to the public network.

Thanks again, any suggestions are welcome.

**Comment by sergeybykov** [comment]
>but I am still not sure whether it is okay to expose the cluster to the public network.

Our general answer is it's not okay to expose silo endpoints directly into the wild. A frontend tier with authentication and DDoS protection is required for any service of value. As @Vhab already mentioned, in 2.1 a frontend can be co-efficiently hosted in the same process as a silo, if you want to minimize the number of network hops.

**Comment by sergeybykov** [comment]
@slango0513 Are you okay to close this?
