### ISSUE TITLE
Replace compile-time code generation of GrainReference subclasses (stubs)

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#511]
This is a sub issue for #474 (Minimize/eliminate the usage of code generation in Orleans). Motivations for this are covered in that issue, so I won't reiterate.

@gabikliot mentioned some different techniques for eliminating the need for compile-time code generation of `GrainReference` subclasses including the possibility of using dynamic method invocation, reflection, or runtime code generation (eg, using Roslyn. See #40).

I believe that runtime code generation is the most optimal approach: it has the best amortized performance at runtime. Other options might be sufficient, though. The performance of `dynamic` has apparently improved somewhat, so that might now be a viable option.

**Comment by gabikliot** [comment]
I think doing runtime code generation is a good solution, and not trying to dismiss it in any way.
But I do think that looking at potential alternatives is worthwhile as well. That way we can compare different solutions and pick the better one.
An alternative solution that I was thinking about is based on [`DynamicMetaObject`](https://msdn.microsoft.com/en-us/library/system.dynamic.dynamicmetaobject(v=vs.110).aspx). There are more details [here](http://blogs.msdn.com/b/cburrows/archive/2008/10/28/c-dynamic-part-ii.aspx).

Essentially, this solution does not generate any code. Instead, it creates a dynamic dispatch object, which will implement the concrete application grain reference. 
This dispatch object will be created once per grain reference type and cached, so it will only incur the large cost of creating the dispatch object upon the first `GrainFactory<IMyGrainType>.GetGrain()` call.
Of course, using `DynamicMetaObject` does **not** mean that we are sacrificing strong typeness: the resulting application code will be still strongly typed, since `GetGrain()` will return a strongly typed grain reference.

The advantage of this approach is that we are completely out of the business of code generation (static or dynamic). 

I did NOT prototype this solution, so can't be really sure it can work until tried.

**Comment by alan-geller** [comment]
In general, I think if you can get the same perf (or pretty close) without any code gen, I’d avoid it. On the other hand, if there’s a big price to pay for dynamic dispatch, I’d go with code gen.

In my experience code gen tends to be more fragile than reflection. I think there’s also a tendency for language specifics to sneak into code gen and cause bugs for non-C# users in a way that doesn’t happen for reflection. If you’re doing runtime IL generation, this is obviously less of an issue, though…

An aside on perf: when I was writing the serialization code for Orleans I came across a number of articles pointing out that you can get much better performance by wrapping a MethodInfo.Invoke inside of a Delegate -- multiple orders of magnitude better. I'm not sure if this is still true in the latest version of the CLR, but it was true in 4.0. Some references:
http://blogs.msmvps.com/jonskeet/2008/08/09/making-reflection-fly-and-exploring-delegates/ 
http://byterot.blogspot.com/2012/05/performance-comparison-of-code.html
http://snipplr.com/view/29683/converting-methodinfo-into-a-delegate-instance-to-improve-performance/
http://www.thejoyofcode.com/Performance_of_Method.Invoke_vs_a_Delegate.aspx

**Comment by ElanHasson** [comment]
There may be some knowledge to be gained from how Entity Framework is doing
it.

Just a thought.

**Comment by veikkoeeva** [comment]
@ElanHasson You are referring to *compiled delegates*, I think and judging from the links by @alan-geller he is writing about the same thing. Dapper and many of the fast serializers use this technique. In fact, I was thinking too, but it's not a priority currently. :)

http://www.mindscapehq.com/blog/index.php/2011/11/27/reflection-performance-and-runtime-code-generation/
http://www.palmmedia.de/Blog/2012/2/4/reflection-vs-compiled-expressions-vs-delegates-performance-comparision

One thing worth checking is if these methods are CoreCLR compatible. All of these approaches have their merits, I think, kind of unforunately.

**Comment by ReubenBond** [comment]
Entity Framework 7 uses Roslyn as well as Expression Trees. I'm not sure if they do any Expression Tree-based code generation, but they probably do.

Dapper mostly uses IL.Emit()

ASP.NET Razor uses Roslyn liberally.

Here is the approach I've been taking:
* Use static methods whenever possible
* Use compiled/cached Expression Trees next
* Use Roslyn-based CodeGen when the other two will not suffice
* Avoid dynamic
* Avoid reflection in the hot path, but use it liberally to support the above techniques.

**Comment by sergeybykov** [comment]
Resolved by https://github.com/dotnet/orleans/pull/528.
