### ISSUE TITLE
How do you get all the grain collections?

### ISSUE THREAD

**Issue by summitn** [dotnet/orleans#5114]
For example, there are many users grain, one of them needs to change the name, and the name cannot be the same as other users, what should be done at this time ~
What I can think of at the moment is to use a grain like user management to manage all users grain, but it doesn't feel reasonable, because that grain will become very big, can anyone tell me what to do

**Comment by sergeybykov** [comment]
Work on indexing is in progress in https://github.com/OrleansContrib/OrleansV2.Fork.Indexing.

**Comment by philbe** [comment]
The indexing feature allows you to define an indexed property as "unique", which ensures that there are no two grains with the same value of that property. The current implementation works with latest Orleans release. However, it has not undergone enough testing for production use. And its API will change to use facets rather than inheritance for a grain to pick up indexing functionality.

**Comment by sergeybykov** [comment]
@summitn Did you get enough information?
