### ISSUE TITLE
Make the logs to print more clear Grain/Interface identity.

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/orleans#5146]
I'm trying to diagnose several performance issues like _from nothing_ the silo starts to eat 100% CPU and profiling on async code is, a nightmare...

Thousands of those messages are printed when the scenario happens:

`[2018-10-24 12:59:34.308 UTC] hostid=XXXXXXXXX env=dev shard=devsvc proc=silo level=WARN log=Orleans.Runtime.CallbackData Response did not arrive on time in 00:00:30 for message: IsAlwaysInterleave Request S10.123.6.17:11111:278069385*grn/F8588497/00000000+cf03f099-e162-41e3-9d12-abc02245aea4@38484092->S10.123.6.17:11111:278069385*grn/9C2A0175/00000000+cf03f099-e162-41e3-9d12-abc02245aea4@757ca091 #1966753: . Target History is: <S10.123.6.17:11111:278069385:*grn/9C2A0175/00000000+cf03f099-e162-41e3-9d12-abc02245aea4:@757ca091>. About to break its promise.`

Among others where the TypeCode (i.e. `*grn/F8588497/`) is printed on it but we don't have it referenced anywhere in code being generated because codegen stores the interfaceId IIRC...

So, what we are trying to do is to have a way to map those IDs to our grains, so at our log server we can make it replace the IDs at the logs on-the-fly so it can help us detect issues.

**Comment by benjaminpetit** [comment]
Yes we definitely want to fix that... But it's not as easy as it sounds to fix.

Instances of `GrainId` are created via static factory methods (in `GrainId` itself). `GrainId` types lives in `Orleans.Abstractions`. We use a static factory pattern to being able to "intern" instances.

The mapping `TypeCode -> Class` would be in the `IGrainTypeResolver`, type that is internal in `Orleans.Core`.

A solution could be to make this factory non static and get it though DI when needed. But if I remember correctly, we were a bit concern about using DI every time we want to create a new GrainId…

There might be a better solution to this ; it wasn't a priority so I didn't looked more deeply into this. But if you have any suggestion... :)

**Comment by codesee** [comment]
Similarly, I have a problem that is very similar to the above, and there is currently no way to solve this problem. In order for the apps to work, I have to restart Silo every half day.
I hope to solve this problem as soon as possible, thank you.

**Comment by sergeybykov** [comment]
@codesee Can you elaborate on why you have to restart the silo? I don't immediately see a connection here.

**Comment by codesee** [comment]
@sergeybykov [The orleans client connection to the silo often occurs timeout](https://github.com/dotnet/orleans/issues/5161)

**Comment by codesee** [comment]
@sergeybykov 
Because the following messages appears in the log：

`Orleans.Runtime.CallbackData Response did not arrive on time in 00:00:30 for message: IsAlwaysInterleave Request S10.123.6.17:11111:278069385*grn/F8588497/00000000+cf03f099-e162-41e3-9d12-abc02245aea4@38484092->S10.123.6.17:11111:278069385*grn/9C2A0175/00000000+cf03f099-e162-41e3-9d12-abc02245aea4@757ca091 #1966753: . Target History is: <S10.123.6.17:11111:278069385:*grn/9C2A0175/00000000+cf03f099-e162-41e3-9d12-abc02245aea4:@757ca091>. About to break its promise.`

The orleans client will no longer be able to connect to the orleans server(silo)，causing the entire orleans-based applications to be unavailable.If I restart the silo, the application will be available again.

For details, please see:[The orleans client connection to the silo often occurs timeout](https://github.com/dotnet/orleans/issues/5161)

**Comment by sergeybykov** [comment]
@codesee So this is a separate issue that we'll discuss in #5161. Thanks for opening it.

This issue though is narrowly for the inconvenience of needing to look up type codes while looking at logs. Just to be clear.

**Comment by ReubenBond** [comment]
Fixed in #6774
