### ISSUE TITLE
cannot call from inside of grain

### ISSUE THREAD

**Issue by danpat04** [dotnet/orleans#5162]
It could look like dumb, but I could not solve the problem, and found nowhere but here to ask.

I'm planning to use the Orleans and testing some simple codes.
The Grain implementation is something similar to the codes to this.
```
public class TestGrain : Orleans.Grain, ITestGrain
{
    private readonly ILogger logger;

    public TestGrain(ILogger<TestGrain> logger)
    {
        this.logger = logger;
    }

    Task<bool> FirstCall(int secondGrainId)
    {
        var secondGrain = GrainFactory.GetGrain<ITestGrain>(secondGrainId);
        var response = secondGrain.SecondCall();
        this.logger.LogInformation("Responded");
        return response;
    }

    Task<bool> SecondCall()
    {
        this.logger.LogInformation("SecondCall called");
        return Task.FromResult(true);
    }
}
```

I could see "SecondCall called". but couldn't see "Responded".
I tried to get some informations from debug log, but there was nothing (at least on my thought).
Could you help me out?

**Comment by sergeybykov** [comment]
Our Gitter chat is a good place to ask quick questions - https://gitter.im/dotnet/orleans.

The above code isn't quite right if you intended to log "Responded" after a response arrive from `SecondCall`. `secondGrain.SecondCall();` is an asynchronous call. It immedately returns a `Task<bool>`, before the call even reaches `secondGrain`. You can change the code as follows to achieve the desired behavior.
```csharp
async Task<bool> FirstCall(int secondGrainId)
{
        var secondGrain = GrainFactory.GetGrain<ITestGrain>(secondGrainId);
        var response = await secondGrain.SecondCall();
        this.logger.LogInformation("Responded");
        return response;
}
```

This way, it will log "Responded" only after the response has been received (because of await).

**Comment by danpat04** [comment]
Thank you. It looks dumb, but it helped much.
I'll try on gitter next time.

**Comment by sergeybykov** [comment]
No worries. Async stuff is non-obvious. Takes some time to get used to.
