### ISSUE TITLE
SMS stream resending last message to new subscribers

### ISSUE THREAD

**Issue by bboyle1234** [dotnet/orleans#5173]
A feature that I would really like to see implemented in SMS streams is the configurable option to have the stream resend the "most-recently-sent" message to any NEW subscriber.

In other words, the stream would keep a copy of the last message sent on that stream, and immediately send it when a NEW subscription is made, just to that new subscription.

In this way, messages can be sent periodically (or rarely) on an SMS stream and new subscribers can be brought immediately up to date with the last-sent-message when they subscribe, without any extra plumbing code.

For my use case, the "last-sent-message" would not need to be persisted. It could be just kept in memory, but I see the advantage and disadvantages of storing it as well. If the SMS stream is having messages sent rapidly, it would "slow down" the stream by writing every message to storage before sending it, so if storage is to be used, there may have to be some configuration regarding the "max write rate" to keep the stream running optimally at high messaging rates.

Can we add this feature to SMS streams?

**Comment by sergeybykov** [comment]
This seems like a concept mismatch to me - mixing of transient data (SMS events) and persistent state (last event). What complicates it even more is the fact that with SMS streams there isn't a central event delivery authority because events travel directly from producer(s) to consumer(s). One consequence of that is that there isn't really a notion of "last event", as two or more producers might send events to consumers in parallel without any shared queue on the way that would order them.

**Comment by bboyle1234** [comment]
Thanks @sergeybykov
