### ISSUE TITLE
Ignored RegisterAsStreamProducer error on EventHub streams

### ISSUE THREAD

**Issue by darthkurak** [dotnet/orleans#5196]
Hi. Im testing EventHub stream providers on high throughputs with a lot streams. (32k).
I observed when launching my orleans on existing eventhub with populated data (32 partitions, 1000 partionsKeys per partition) that orleans spams my pubsub storage on blob azure and get a lot errors. Orleans works further, and im ending up with a lot of streams not being processed due to this errors, because they are never retried.
I changed this to MemoryStorage and that part pass with success, but then errors occur on loading grain states (initial check as i doesn't have any grain saved yet). 
My questions are:
1. If Orleans has some retry mechanism for getting pubsub storage and grain state storage?
2. Why Orleans spam pubsub storage when using Implicit subscription? What is purpose for that?

**Comment by jason-bragg** [comment]
>or it is count to MaxDeliveryTime and pulling agent will retry message? (retry activation - retry grain state load?)

Ah, yes.  If a grain fails to activate, the pulling agent will retry delivery up to the MaxDeliveryTime, which will reactivate the grain.  If the grain has state in storage and the activation fails due to storage issues, the redelivery and reactivation will act as a  retry mechanism for storage.  The retry logic in this case is related to streams and not directly related to grain storage recovery, so I didn't make the connection, but in your pattern, yes, grain storage should have a retry mechanism.

**Comment by HermesNew** [comment]
@jason-bragg If I use  AddMemoryGrainStorage("PubSubStore")，Can it be configure stream provider to use ImplicitOnly PubSub?

**Comment by jason-bragg** [comment]
If you use ImplicitOnly, you do not need any configured PubSubStore
