### ISSUE TITLE
Orleans azure deployment 

### ISSUE THREAD

**Issue by 2mike2** [dotnet/orleans#524]
Hi, 
I have an Orleans application with silos planned to be deployed as azure worker roles and an existing client application hosted as azure web roles. If I want silos and client to live in separate deployments, I need to specify the deployment ID of silos during AzureClient initialization when web roles started. So when a new silo version is deployed I need to roll all my clients roles with the new deployment ID. Is it right or is there a better practice for aligning the clients when silos deployment changed?
Thanks.

**Comment by sergeybykov** [comment]
You don't necessarily have to use Azure's Hosted Service deployment ID (that's what AzureSilo class does). Instead you can instantiate SiloHost class directly, and pass it your own deployment ID that's independent from Hosted Service deployment. Similarly on the client side, instead of using AzureClient with its logic of using Hosted Service deployment ID, you can use GrainClient directly pass your own deployment ID.

One other thing to ensure is direct network connectivity between these client and silo deployments. You may need to use an Azure Virtual Network for that.

**Comment by 2mike2** [comment]
Thank you for getting back. 
1. By connectivity issue you mean that client deployment wont have access to the silo endpoints (the TCP ports) unless it is in the same deployment as silo or in the same virtual network as you've suggested?
2. If I use SiloHost class directly in azure worker and use the appropriate initialize / start / stop interfaces, are there any other nuances I should be aware of when SiloHost is used in worker role as opposed to AzureSilo?

**Comment by sergeybykov** [comment]
1. Yes. My understanding is two hosted services cannot talk to each other's internal endpoints unless connected with a vNet.
2. The other thing that's a bit complicated with Azure is finding location of the config file, especially client config in web role. But that code is in ClientConfiguration.StandardLoad() that is used by GrainClient underneath.

**Comment by 2mike2** [comment]
Ok,Thank you.

**Comment by sergeybykov** [comment]
No problem.

**Comment by 2mike2** [comment]
On the worker side, I see that AzureSilo class has a couple of start overloads that accepts deploymentId:
public bool Start(string deploymentId, RoleInstance myRoleInstance, ClusterConfiguration config)
so can I use it for providing custom deploymentId instead of using SiloHost?

**Comment by sergeybykov** [comment]
These overloads have been recently refactored/removed (post 1.0.8).

**Comment by gabikliot** [comment]
Hi @2mike2 . Do you still have open questions on this issue? Can it be closed?

**Comment by 2mike2** [comment]
Yes. thank you.
