### ISSUE TITLE
Logger names in transactions

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#5252]
Currently the logger name used throughout most of the transaction system is unique per resource. While this can be helpful when tracing transactions, it also makes it more difficult for someone not very familiar with the internals to turn on debug logging for just transactions. In my case this was compounded by having logging settings that don't print the logger name.

Perhaps a compromise between what is there now and more standard logger names is to prefix the logger name with `Orleans.Transactions` to allow a simple source filter to work.

**Comment by jason-bragg** [comment]
Logging for transactions is broken out by transaction infrastructure, which should all be prefixed by "Orleans.Transactions" and grain state, which should be filterable using "{GraintypeName}.{stateName}".  The reason for this was that we surmised that application developers would most interested in their grain's behaviors, so the grain states (including transactional states) were associated with the grain rather than the transactions feature.

Given the following grain with a transactional state:

    public class MyGrain: Grain, IMyGrain
    {
        protected ITransactionalState<MyState> state;

        public MyGrain(
            [TransactionalState("state")]
            ITransactionalState<MyState> state,
            )
        {
            this.data = data;
        }
    }

One should be able to set the log level for the entire grain, including it's state with

            hostBuilder.ConfigureLogging(builder => builder.AddFilter("MyGrain", LogLevel.Debug));

or just for the transactional state 'state' with

            hostBuilder.ConfigureLogging(builder => builder.AddFilter("MyGrain.state", LogLevel.Debug));

With the above explanation, does the logging pattern still seem off.  I'm asking in part because I'm not 100% convinced that the way we organized the logging is really the best, and I'm working on updating the docs, so if this is fine but unintuitive, I may want to clarify this behavior in the updated docs.

**Comment by jason-bragg** [comment]
Looking at our debug logging as it relates to transactions, we've been very inconsistent with our use of 'trace' and 'debug'.  We need address this, but in the interim, you may want to set log level to trace rather than debug.

**Comment by jsteinich** [comment]
My expectation was that I could enable "Orleans.Transactions" and get everything.

My start point was a transaction failing because of some other transaction failing so I was simply trying to get more insight into why the transaction was failing. Before trying to enable the logging I had gotten to the point of knowing which transaction was causing the problem, so I could have looked up which grains were involved.

I'll admit that our use of transactions is probably a bit different than others will be, but I'd say the broad scope is preferable to the grain scope.
