### ISSUE TITLE
Compilation error `error CS0579: Duplicate GeneratedCodeAttribute attribute` when used with webapi project

### ISSUE THREAD

**Issue by avinash0161** [dotnet/orleans#5265]
I have a webapi project created using `dotnet new webapi` which calls Orleans client and silo. The Orleans client and silo projects were working fine initially as a console application. But after inclusion of webapi project, I am getting a compilation error `error CS0579: Duplicate 'global::System.CodeDom.Compiler.GeneratedCodeAttribute' attribute`. The project and the associated bin-log can be found [here](https://drive.google.com/drive/folders/1k8pXqQ7l4VpaxWX7CW2_EtQC_YPtasSv?usp=sharing)

**Comment by avinash0161** [comment]
The strange thing is that the build error gets fixed if I delete the SiloHost project's obj folder and then build again.

**Comment by avinash0161** [comment]
Some restructuring appears to fix the issue. Earlier the solution was such that webapi.csproj was at the same level as other projects folders. This appears to create some conflicts. After I moved webapi.csproj and the webapi project files into their own folder, everything seems to work fine.

```
Earlier:

Client
    |_ client.csproj
    |_ OrleansClient.cs
SiloHost
    |_SiloHost.csproj
    |_SiloWrapper.cs
Engine
    |_Engine.csproj
    |_OrleansEngine.cs
Controllers
    |_APIController.cs
Program.cs
Startup.cs
webapi.csproj

After restructuring:
Client
    |_ client.csproj
    |_ OrleansClient.cs
SiloHost
    |_SiloHost.csproj
    |_SiloWrapper.cs
Engine
    |_Engine.csproj
    |_OrleansEngine.cs
Webapi
    |_Controllers
            |_ APIController.cs
    |_ Program.cs
    |_ Startup.cs
    |_ webapi.csproj
```

**Comment by ReubenBond** [comment]
Thanks for posting the info, @avinash0161.

The log makes the issue more apparent, and yes restructuring your project is the right approach.

![image](https://user-images.githubusercontent.com/203839/50166489-0a271d00-029c-11e9-8e56-454be455bfd3.png)

I believe the issue is how the project system is including and excluding .cs files in your project. It includes all files recursively and excludes all files under `obj/` and `bin/`. So by having some projects nested inside of another you are recursively including all of the temporary .cs files generated into `obj` and `bin` and they are not being excluded because the exclusion pattern doesn't match.

I think we should also remove the assembly-level `[GeneratedCode(...)]` attribute, it's not necessary and we have another (similar) attribute which serves an actual purpose.

**Comment by ReubenBond** [comment]
I'll close for now, but I opened #5270 anyway because I believe it's best to avoid adding this attribute.
