### ISSUE TITLE
Support customizable type name formatting

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#5298]
Currently Orleans allows users to customize Type resolution (conversion from some `string` to `Type`) but does not support customization of Type formatting (`Type` -> `string`).

There are occasionally issues with how Orleans formats type names, but requirements for backwards compatibility restricts what changes we can make. For example, we have seen some issues with nested generics in static types (which is common in F# because of how it expresses modules as CLR types) #4012. Also see #5292, where an F# type is unable to be recovered after serialization.

Type name serialization also plays a significant part in the version-tolerance story, since users often like to rename/move types (#2653)

Allowing for customization of type formatting may provide a nice escape hatch for users who experience such problems as well as providing a path for offering more robust defaults in the future (for example, by using `RuntimeTypeNameFormatter` instead of our current `OrleansTypeName` impl)

**Comment by mindlink** [comment]
Hello! We've run into a scenario where this is an issue and looks like not something that's possible in 3.x.

Specifically - using a generic grain type that subscribes to a stream, because the generic type is serialized with the full version of the library, once we make changes and publish a new version of the library, Orleans is unable to restore the stream subscription because the versions don't match.

Are there any potential escape hatches here? Short of taking steps to eliminate the generic types, or fix the version of the library.

As we're using streams here and persistence, migrating to Orleans 7 is still a significant technical challenge - it would be great to be able to do this, but I expect we'll need some help from the core team in uplifting serialized type information that's persisted (for example performing an offline migration from Orleans 3.x type serialization to Orleans 7.x type serialization).

**Comment by ReubenBond** [comment]
This is supported now, via the `[Alias("my_name")]` attribute or by registering one or more [`ITypeConverter`](https://learn.microsoft.com/en-us/dotnet/api/orleans.serialization.itypeconverter?view=orleans-7.0&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Orleans.Serialization.ITypeConverter)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue) implementations (eg, one per type if you wish)
