### ISSUE TITLE
Support customizable Actor type name

### ISSUE THREAD

**Issue by Johnny-Bee** [dotnet/orleans#5308]
Hi guys,
I have multi tenant system and I would like to see all my Actor types in the same cluster for comfort and convenience.
A multi-tenant system means that the same actor type is deployed with different configuration because he will use different persistence, queues, etc related to his tenant and the health check will be done based on this tenant configuration.
This solution allows me to isolate the traffic/activity by tenant and to scale a tenant independently to the other on the same K8 cluster.

The registration of the actor is based on the silo/actor type.
For example, based on this kind of registration I cannot make the distinction because actor type   HelloWorldType deployed on the tenant A and B on same K8 cluster.

In your book you said "(Orleans is not currently intended for a multi-tenant environment)": https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/Orleans-MSR-TR-2014-41.pdf
But @jkonecki succeed to use Orleans on his multi-tenant system: http://gigi.nullneuron.net/gigilabs/microsoft-orleans-use-case-reservations-system/

On ProtoActor we had the Actor kind concept and it's not related to the Actor Class Name it could be anything which is great!...

Source: https://github.com/AsynkronIT/protoactor-dotnet/blob/74d71f0c9eb14925da59ade42cbec4f2e4a2252f/src/Proto.Remote/Remote.cs

Example: https://github.com/AsynkronIT/protoactor-dotnet/blob/74d71f0c9eb14925da59ade42cbec4f2e4a2252f/examples/ClusterHelloWorld/Node2/Program.cs

But now that we moved to Orleans we cannot compute the actor type name...

We think that the solution could be to prefix the actor type name with the tenant name, for example: 
- Tenant_A_ActorType_HelloWorldType
- Tenant_B_ActorType_HelloWorldType

It could be great if we can customize the actor type name.

We found the VersionAttribute it's not the same but it's something...
But I would prefer to have a more flexible way to indicate the tenant.

What do you think?

**Comment by jkonecki** [comment]
Just to add a bit of context - I've implemented multitenancy by including
tenant in Actor Id instead of Actor Type.

I don't want to reject this PR in any way as the proposed approach may be
better for various reasons. I would like to just share my opinion that for
me (and the systems I've been working on) tenant relates more to the
identity than behaviour. There may be some change in actors behaviour for
different tenants based on some configuration, but I don't see two
instances running for two different tenants as being 'of a different type'.
This is a purely semantic view.

Including tenant in actor identity allows me to check if one actor can call
a different actor by validating their IDs only. I'm sure similar thing
could be achieved with Types.

**Comment by sergeybykov** [comment]
I see two options here: 1) tenant ID embedded in grain ID (as @jkonecki already mentioned) or 2) cluster per tenant. 2) may work for a small number of tenant with silos for different tenant sharing physical resources (VMs).
