### ISSUE TITLE
Cannot resume stream after silo restart

### ISSUE THREAD

**Issue by srollinet** [dotnet/orleans#5310]
In my application, I use a SMS provider and I have some issues when the silo restarts
The architecture is basically that:
- The system has a single silo and 2 clients.
- I use a single stream with only 1 grain that publish events
- The 2 clients subscribe directly to the stream.

The problem is when the silo restarts, I cannot resume the event subscription
- Sometimes after the restart, the stream continues working, but this is not frequent
- Calling `ResumeAsync()` doesn't change anything. Is it on purpose? Am I missing something?

I made a simplified repro project that isolate and illustrate the issue: https://github.com/srollinet/OrleansStreamIssue

In the real application, I use Ado storage and clustering and I call ResumeAsync only when I detect a connection lost. By the way, it seems that the ClusterConnectionLostHandler is not systematically called when the silo crashes.

Bonus question: Is there a better / more robust solution to handle this use case? I have seen some examples with observers but I don't know what is the preferred way in this case.

**Comment by srollinet** [comment]
Any news or workaround about this issue?
I have to decide if we continue using the Orleans streams or if we have to use an alternative, such as a third party message bus

**Comment by jason-bragg** [comment]
I apologize for the delayed reply.
In the case of a client losing connection to a silo, any subscription to a stream from that client will be cleaned up (removed), so resuming the subscription won't work because the subscription is gone.  Rather than caching the subscription handle locally, I suggest querying the stream (GetAllSubscriptionHandles) to acquire the active handle if it still exists, and resuming it if it does, but if none is returned (it's been cleaned up), resubscribing to the stream.

More information on this can be found in previous issues:
https://github.com/dotnet/orleans/issues/3484
https://github.com/dotnet/orleans/issues/2226
