### ISSUE TITLE
Message / Request Priority

### ISSUE THREAD

**Issue by berataydin** [dotnet/orleans#5321]
Hi, we are using Orleans as back-end in our IoT project, briefly it relies on ConnectionPoint's and Devices. Devices are connected to CP's. Each CP support only one connection in the same time so it's very suitable for CP's to work within single-threaded nature of grains. There are various reminders on CP for each Devices, like read device setup, read device data, heartbeat, health-check and some other domain specific operations. CPGrain is not re-entrant, and we are using asynchronous socket for communication.

My question is; there is being multiple request by reminders on the CPGrain's mailboxes naturally, but we also have some instant request that must be run instantly, so expected behavior would be like that, even if there are 20 messages in the mailbox, cancel current process first (we can handle it with grain cancellation token) and **process instant request before other requests in the mailbox (that is I am asking for) is there a way to do that with Orleans**

Currently we are using priority queue in CPGrain to schedule and prioritize messages/requests, but we have to check queue with timer to process. So we are loosing natural flow of Orleans by this custom solution, besides lower time interval for that timer would result with high CPU consumption, contrary higher time interval would result higher latency. Do you have any suggestion?

**Comment by sergeybykov** [comment]
A short answer is that there is no notion of priority of incoming requests and the runtime never cancels execution of a request. So requests to a grain always start executing in the order of their arrival. There were requests to allow reordering of incoming requests based on priority or other considerations. But that hasn't been implemented so far.

A longer answer is based on the assumption that processing of requests and reminder callbacks doesn't take a significant amount of time on the thread, and the latency is primarily determined by asynchronous IO calls. Please correct me if that's not true for your application.

If my assumption is correct, then full or partial reentrancy might be a way to achieve what you are looking for. Toady `[Reentrant]` is a class level attribute. So it applies to all method of the grain. @jason-bragg is currently looking at making it also a method level, so that individual methods could be marked for reentrancy. That would allow to make 'priority' methods reentrant, and they would be able to start executing whenever the currently running methods hits an `await`. 

There is also the `[AlwaysInterleave]`, which is a method level attribute. I personally consider it more of a 'hack', but it can also be useful until we improve and extend the reentrancy story. Semantics of `[AlwaysInterleave]` are different from `[Reentrant]` - it allows to interleave with other grain methods, but not with those also marked as `[AlwaysInterleave]`.

What's not clear to me in your description though is that you are talking about potentially having 20 messages in a grain's queue. What is the reason for such a jam? You mentioned reminders. But they are intended to fire relatively infrequently, and mostly for fault tolerance purpose. Is a grain is managing a single device, I would assume it shouldn't get too many messages. Is that a real case or a potential corner case you want to be prepared for?

**Comment by berataydin** [comment]
Ok let me explain my situation more detailed.

In some situations, we have more than 20+ devices connected to same ConnectionPoint (up to 32 devices). Each CP is a grain because of we have only one socket connection to communicate for all devices that are connected to same CP. 
We are polling all devices per 5 minutes (read 400+ register data per device), so when the time is up we will have 20 poll request in our message queue at the same time. Each poll taking 5 to 10 seconds to finish(but all the communication is non-blocking as I told before).

So when there are 20 poll request in the queue that are currently processing, **there may come instant request from user interface like _'Read Device Setup'_, this request have more priority because when device polling is a background process that can be handled later, but this request is coming from UI by user interaction that must be replied asap, but it takes time to response because there are already 20 currently processing polling message in the queue.**

First we designed each Device as a grain, but it would be meaningless because they have to use same connection that is related with Connection Point.
Also there is a Device model object that involves all register of device that is very heavy to serialize, so ve designed CP as a grain and devices are members by following Orleans Best Practices.
 
We couldn't be sure about using [Reentrant] because of our ConnectionPointGrain is statefull, has complex state operations and coarse grained by its nature. We were thinking about [AlwaysInterleave] working on some PoC currently.

**Comment by berataydin** [comment]
> With CP grain being non-reentrant, poll requests at the end of the queue might take up to 200 seconds to start executing. Is that correct?

Yes it's true.

> What are you concerns about [Reentrant]? Grain is still single-threaded. Are you worried about the complexity of thinking through possible interleaving cases? [AlwaysInterleave] will let you interleave read methods marked with it while awaiting inside poll requests. Is that what you think you need?

Rather than complexity there are some operations like ReadDeviceSetup that shouldn't be interleaved so Grain can not be Re-entrant. In the light of these information, it looks best option for us signing all the other methods with [AlwaysInterleave] except critical one's like ReadDeviceSetup. Thank you very much.
