### ISSUE TITLE
AzureQueues stops being processed when large and growing number of streams uses it

### ISSUE THREAD

**Issue by nik-dor** [dotnet/orleans#5362]
I test Orleans for the use case when large number of independant messages should be processed in the fastest and scalable way. My first approach was to send each message to unique stream in the same namespace. So if message has id = GUID, then it is sent to stream <GUID, "Namespace">. On the processing side I used implicit subscription grain ProcessingGrain with attr [ImplicitStreamSubscription("Namespace")]. So as many there are messages to process that many streams and grains are created. After message GUID is processed stream <GUID, "Namespace"> and  ProcessingGrain <GUID> is not needed anymore, so I configured ProcessingGrain to be Deactivated after 5 minutes. Not active streams are cleared from Orleans after StreamPullingAgentOptions.StreamInactivityPeriod that was left with the default value = 10 min.
Stream: AzureQueueStreamProvider
Clustering: AzureStorageClustering
Monitoring: Orleans Dashboard 2.2.0

I tried these load scenarios:
- 100-1000 msgs/sec
- 1-2 silos
- 1-8 queues in Azure Queue

Enviroment:
- Orleans 2.2.3
- Windows 10 or Windows Server 2016 Datacenter, both x64
- .Net Core 2.2.0

and in all scenarios real Azure Queues were stopped being processed after 10-40 minutes of work. So pulling agents just don't pull messages anymore. Logs show that PubSubCacheSize grows all the time and at value 250-400k mentioned fail occurs. 
Old Grains are successfully deactivated and streams too, but after fail occurs streams are not cleared. So value of PubSubCacheSize goes up and down, but then on value of 250-400k it is not cleared anymore. At the same time all processing grains are eventually deactivated.

After chatting on gitter, I understood that I need to try a solution of pool of streams with fixed number of them to avoid this situation of unbounded number of streams. 

- But anyway I think it is an issue that system just stops process streams with even no message in logs. It looks like everything is fine but messages just accumulate in Azure Queue. 
- Also I don't understand why if inactive streams are cleared after StreamInactivityPeriod and all grains are deactivated the described pattern of 1stream\msg is not working one? It seems to me that up to some load the system should feel fine. New messages create new objects in the system, but at that time old objects (streams system info and grains) have been cleared already.

Besides of my (actually not recommended in the docs) scenario, please consider another one:
The system creates a group of grains per some event, e.g. conference. These grains use persistant stream like AzureQueue for some communication. Conferences should not know about each other, so each conference=group of grains uses its own stream Id = Conference Id. The frequency of new conferences creation can be high, comparable with my test, 100-500/sec. Here each stream is used many times but like in my test, when the conference ends, stream is not needed anymore. It will never be used again. So number of streams in system can slowly grow. So now it looks similar to my test. 
And I'm afraid that on some load Orleans will stop process streams and create new ones because of some reason. May be because it can't handle situation when speed of new streams creation is more than speed of clearing inactive streams?

Thanks!

**Comment by jason-bragg** [comment]
Streaming is conceptually simple, but technically complicated as there is an extremely wide range of usage patterns.  Supporting all possible usage patterns optimally is non-trivial.  Orleans streams, while seeking to be a general streaming framework has been jointly developed with a set of streaming services, and the patterns those services use are where the system has been most optimized and hardened.

The usage pattern you’re describing is not a pattern any users have needed, mainly because it’s arguably not stream processing.  It’s more like queue processing using streams, as stream affinity and ordering are not relevant.

Having said that, the pulling agents stopping delivering messages without generating errors is unexpected behavior, and we don’t have any testing around how many stream/second can be introduced.  If this is a pattern you need supported, we’re happy to work with you to address any shortcomings you find.

> in all scenarios real Azure Queues were stopped being processed after 10-40 minutes of work

What was the configured inactivity time?

> Also I don't understand why if inactive streams are cleared after StreamInactivityPeriod and all grains are deactivated the described pattern of 1stream\msg is not working one?

This pattern should 'work', it's just not a scenario we've tested or optimized for.

> Here each stream is used many times but like in my test, when the conference ends, stream is not needed anymore. It will never be used again. So number of streams in system can slowly grow.

The number of streams in the system is based on the number of streams active within the configured stream inactivity period (StreamPullingAgentOptions.StreamInactivityPeriod).  The pubsub cache size will be roughly this number divided by the number of queues used, assuming streams are mostly evenly balanced across the queues.  This may fluctuate over time but should not grow indefinitely.

So if one generates 1000 events per second, with 1 event per stream, this is 1000 streams/second.
If the StreamInactivityPeriod is set to 1 minute, this means there should be 60000 streams active in the system at any point in time.
If there are 8 queues then each pulling agent would have, on average 7500 active streams.
Is this not the behavior you're seeing?

> May be because it can't handle situation when speed of new streams creation is more than speed of clearing inactive streams.

This should only be the case if streams continue to run longer and longer over time.  For instance, imagine if each new stream was active one minute longer than the previous stream, in this case the rate of clearing streams would not keep up with the rate of adding new streams.  However if streams were mostly bounded in active time (to use the meeting example, most meetings are less than 2 hours), then overall the rate of clearing streams would keep up with the rate of adding them and one would simply need to provision their system to support the load.

**Comment by nik-dor** [comment]
Sorry for late answer.

> So if one generates 1000 events per second, with 1 event per stream, this is 1000 streams/second.
If the StreamInactivityPeriod is set to 1 minute, this means there should be 60000 streams active in the system at any point in time.
If there are 8 queues then each pulling agent would have, on average 7500 active streams.
Is this not the behavior you're seeing?

Tested cluster with 2 silos with this described configuration. And the same fail situation occured. Number of active streams was 7500 or less, but then one pulling agent stopped pull new messages. Then another. After 1 night of work, 6 of 8 pulling agents stopped pull new messages.
Tested StreamInactivityPeriod = 10 sec and saw the same behaviour. But number of active streams didn't exceed 1000. Also tried to decrease number of msgs/sec to 500.

500 streams/sec seems to me not a very high rate to make pulling agent fail. May be the reason is in my grain? And pulling agent is just in a state when it thinks that old messages are not processed, so it shouldn't pull new ones?
Although, my grain code is dummy new arrays creation and          

```
await Task.Delay(10);
var task1= Task.Delay(100);
var task2= Task.Delay(100);
await Task.WhenAll(task1, task2);
```

> The usage pattern you’re describing is not a pattern any users have needed, mainly because it’s arguably not stream processing. It’s more like queue processing using streams, as stream affinity and ordering are not relevant.

I agree, it's a queue processing. It's not related to streams. 
May be Orleans can provide some built-in functionality to handle this pattern? For example, ability to change pulling agent behaviour from sending one message to all subscribers per time, so no new message can be handled in a stream while old one is in processing, to parallelizing "stream" processing - taking batch of messages from a queue and sending all of them at once to different grains, so they process all messages in parallel. 
To bound parallelism, there can be a setting for pulling agent, e.g. NumberOfWorkers, so pulling agent never will create more grains than NumberOfWorkers.
Imho, it would be very useful, because there are millions of use cases where we don't need a stream, but we need just to process a queue of "tasks" as fast as we can and properly using server resources.

**Comment by jason-bragg** [comment]
We'd discussed supporting queue processing separate from streams, but never settled on whether the need was sufficient.  Placing this in the backlog to revisit in milestone planning.
