### ISSUE TITLE
Question about Transaction

### ISSUE THREAD

**Issue by danpat04** [dotnet/orleans#5366]
I need some advice on using Orleans.Transaction.

To use Orleans.Transaction it is required to declare TransactionOption on the Grain interface.
It means that if you make a method that can be called in or not in Transaction, you have to double it.

So I thought this way would be easier to use this way.
```csharp
await wallet.PerformUpdate(balance => balance.Pop(100));
 
 
var inventoryGrain = GetGrain<InventoryGrain>(userId, TransactionOption.Join);
await inventoryGrain.AddItem("Healing Potion");
```
Like the code above, I thought it would be nice if a transaction starts when requester wants to.
This way there's no way to find out the method's TransactionOption on the declaration.

```csharp
public interface ISomeGrain : IGrainWithStringKey
{
    [Transaction(TransactionOption.Create)]     
    Task<TReturn> NoneTransactionalRequest<TReturn>(MethodInfo mi, params object[] parameters);

    [Transaction(TransactionOption.Join)]
    Task<TReturn> TransactionalRequest<TReturn>(MethodInfo mi, params object[] parameters);
}
```
So we made a custom layer and call it `Service` layer.
A Service is matched with a Grain.
When a Service request something to another Service, It sends through Grain.
And at Grain level, we decide which way to go, NoneTransactionalRequest or TransactionalRequest.

If the request is NoneTransactionalRequest, create a new transaction.
if the request is TransactionalRequest, join the current transaction.

Here are the questions.
First, I want to know how you think of this way.
Second, Is this way of using Orleans.Transaction is too much?

**Comment by danpat04** [comment]
I thought I could get an immediate reply.  
Is this a hard question? or need more details?

**Comment by jason-bragg** [comment]
> To use Orleans.Transaction it is required to declare TransactionOption on the Grain interface.

Yes.  This is the case because most of the options (other than create) are relevant to the caller, so the information needs exist on the interface.

> It means that if you make a method that can be called in or not in Transaction, you have to double it.

Yes.  Transactions deal with persisted state.  This state can only be operated on transitionally.  If is invalid to read or modify this state outside the context of a transaction.

> If the request is NoneTransactionalRequest, create a new transaction.
if the request is TransactionalRequest, join the current transaction.

One should be able to get this behavior by marking the transaction CreateOrJoin.  If the call is made from within a transaction, it will join it.  If the call is made from outside the context of a transaction it will create one.

**Comment by danpat04** [comment]
Thanks for the explanations.
But my real questions were at the bottom of the issue.

> First, I want to know how you think of this way.
Second, Is this way of using Orleans.Transaction is too much?

**Comment by jason-bragg** [comment]
@danpat04,

> I want to know how you think of this way.

I don't think this is approach is necessary.
I think you can get the same result with the supported TransactionOption CreateOrJoin.

"One should be able to get this behavior by marking the transaction CreateOrJoin. If the call is made from within a transaction, it will join it. If the call is made from outside the context of a transaction it will create one."

> Is this way of using Orleans.Transaction is too much?
No, I don't think so, it's not too much, but it's just not necessary.

**Comment by hihack** [comment]
Hi there,
I'm new to Orleans. I'm still learning from the  #documentation.

In my experience, transaction are related to BUSINESS LOGIC layer. 
I'm currently thinking in Orleans as a INFRAESTRUCTURE layer. ¿Maybe i'm wrong?

In the furure, if i want to change Orleans library for another library in the infrastructure layer, i should keep transaction operation logic in business layer, not in Orleans layer. Again...¿maybe i'm wrong?

So, i think that the solution proposed by danpat04 is more accurately. I dont know if its posible to develop inside Orleans..

With current Orleans solution, ¿can you manipulate transaction logic (create, join, commit,rollback) from business layer instead of Orleans layer?

Thanks for your reply.

Regards,
Santiago
