### ISSUE TITLE
can i get more than then thousand streams?  any limit or side effect in large count stream?

### ISSUE THREAD

**Issue by SmartKarren** [dotnet/orleans#5375]
i am building mqtt server broker cluster by orleans. 

one stream named cluster stream  to share mqtt packet between brokers in cluster,
each broker has it`s own stream named broker stream.
broker grain subscribe from cluster stream  or publish mqtt packet to cluster stream.
client connect to one broker, publish or subscribe mqtt packet in broker.

my question is
should i get a stream for each client(over ten thousand clients), route mqtt packet at grain side.
or just one stream one broker only, process mqtt packet at grain client side and route to mqtt client.

can anyone give me some suggestions?

**Comment by sergeybykov** [comment]
Fundamentally, there is no hard limit on the number of streams. Practically though, some data structures will be stressed with too many streams. It's hard to tell where the limit after which one would experience the negative effects because it depends on a number of environmental factors. But thousands and tens of thousands of concurrently used streams sounds fine to me.
