### ISSUE TITLE
TestClusterBuilder.AddSiloBuilderConfigurator

### ISSUE THREAD

**Issue by Cephei** [dotnet/orleans#5393]
Please consider creating an overload for `AddSiloBuilderConfigurator<T>` that allows you to provide a func for `ISiloBuilderConfigurator.Configure()` and not just a type name. I'm finding it very difficult to write functional tests that depend on being able to mock dependencies registered with `UseServiceProviderFactory`'s DI container. I basically have to write a new `ISiloBuilderConfigurator` concrete type for each test if the mock behavior varies.

Anyone have a good solution for this? I have no way of injecting via constructor into the `ISiloBuilderConfigurator` other dependencies that might help mitigate this.

**Comment by xiazen** [comment]
I think this has been brought up by someone before, see #4670. and the issue then is the difficulty to serialize a lambda. Because back then, regardless of whatever form silo configuration is, it needs to be serialized into an app domain. 

But right now, we have a choice to run a silo in an app domain or in process, maybe we can do this now. I will look into this
