### ISSUE TITLE
Stream subscription from startup task doesn't quite work

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#5444]
https://github.com/dotnet/orleans/issues/587 indicated that it should be possible to access streams from a startup task when using the direct client. This is sort of true, but still has some issues.
For example:
```c#
await subscribe to stream
```
done directly from `IStartupTask.Execute` results in `InvalidOperationException("Attempting to GetCurrentActivationData when not in an activation scope")`.

However, doing:
```c#
await Task.Run(async () => await subscribe to stream);
```
works just fine.

The issue appears to be caused by https://github.com/dotnet/orleans/blob/65405fdfc5dff5c1722f1391d29fe2fed17ddb33/src/Orleans.Runtime/Core/InsideRuntimeClient.cs#L758
since the startup task is running in an Orleans context and pushing to the thread pool breaks out and allows the `HostedClient` to be used.

After subscribing in the workaround manor, the stream does seem to work as expected.

**Comment by jason-bragg** [comment]
The silo lifecycle, which is used to run startup tasks, is executed within the context of a system target.  This is done so that startup tasks (and other lifecycle participants) can make grain calls.  This doesn't allow for streaming.

In #587 we mention that one should be able to use streaming in startup tasks if they use the hosted client.  The hosted client is only used when running outside an orleans threading context, so yes, to use streaming in a startup task, one would first need to break out of the system target's threading contex.

This is not an intended use of streams, so we've no testing around this pattern, but it 'should' work.

**Comment by jsteinich** [comment]
Thanks for the response. I'm fine if this issue is closed, since the "workaround" is simple enough.
However; as more people begin to use the direct client, I could see this type of issue arising for others (I didn't check if non-streaming uses of the direct client from a startup task would cause issue).

**Comment by jason-bragg** [comment]
Somewhat related is pr https://github.com/dotnet/orleans/pull/5445.

That PR may fix this as well.  Startup tasks use a system target context and system targets didn't support grain extensions.  The streaming infrastructure uses grain extensions, so streams could not be used with system targets (and indirectly by grain services or startup tasks).  Adding the ability for system targets to use grain extensions 'should' allow them to use streams.  In theory, this 'should' also allow startup tasks to use streams.  Please note that, to my knowledge, this is still not a pattern we actively support so we've no testing around it, but it 'should' work in theory. :)
