### ISSUE TITLE
Simple call chain reentrancy deadlock A->B->C->A (with repro)

### ISSUE THREAD

**Issue by MelnikovIG** [dotnet/orleans#5456]
There is call chain reentrancy deadlock with simple call flow A -> B -> C -> A.

[Grains.zip](https://github.com/dotnet/orleans/files/2979656/Grains.zip)

UPD:  Not reproducing on 2.1.0 version.

**Comment by JorgeCandeias** [comment]
Confirming repro.

Works:
* Marking `GrainA` with `[Reentrant]`.
* Downgrading to 2.1.0.

Does not work:
* Recursive call to `AGrain.Act()` instead of `AGrain.Act2()`
* `.Configure<SchedulingOptions>(_ => _.AllowCallChainReentrancy = true)`.
* Upgrading to 2.3.0-rc2.

Surprised this wouldn't get picked up by automated tests.
Was there a planned change in default reentrancy behaviour since 2.1.0?

**Comment by sergeybykov** [comment]
It looks like the issue that @andhesky attempted to fix with #5145. However, we ended up reverting it last minute before releasing 2.2.0 final due to performance regression caused by it (via #5249).

I think 2.1.0 works because of #4382 that we reverted in 2.1.2 via #5086.

**Comment by MelnikovIG** [comment]
@sergeybykov Any news with this issue? I think it is critical issue.

**Comment by ReubenBond** [comment]
I believe we should go with a design something along these lines:

* Change `ActivationData.RunningRequestsSenders` from a `HashSet<ActivationId>` to `HashSet<Message>` or `HashSet<Guid>` and rename to `RunningMessages` or `RunningCallChains`
* Add a `CallChainId` property (a Guid or long) to `Message.HeadersContainer` which is set automatically if it's not already set on the current `Message` (I believe `MarkSameCallChainMessageAsInterleaving` is the right place to set it - remove the code which sets `IsAlwaysInterleave` to true, the determination should be made on the receiving side, not the sending side)
* Modify `Catalog.CanInterleave` to check if the current message's `CallChainId` is present in `RunningMessages`/`RunningCallChains`

How does that sound?

**Comment by andhesky** [comment]
I don't know the architecture that well, but the solution sounds reasonable. I especially like doing the check on the receiver side. I was a bit surprised that is not how it worked initially, but didn't want to change it. For my own interest, why will that perform better than my solution? Is it because it is not using RequestContext?

I think the tests from my PR should still be good so you may be able to reuse them. My change also tried to reconcile some code duplication between deadlock checking and call chain reentrancy.  If you can save that it might make maintenance simpler in the future.

**Comment by ReubenBond** [comment]
@andhesky primarily because it's not sending a [list of `ActivationId`s along the call chain](https://github.com/andhesky/orleans/blob/c39e794e3789c89617002ca5acf9fe0d2138d266/src/Orleans.Runtime/Core/Dispatcher.cs#L366). Avoiding `RequestContext` is part of it, too.

The cost of the check is primarily paid when a call would not otherwise be admitted.

Note that this change would break rolling update compatibility unless `AllowCallChainReentrancy` is disabled on all clients/silos prior to the upgrade

**Comment by MelnikovIG** [comment]
@ReubenBond Looks nice, ill try to fix this within few next days

**Comment by MelnikovIG** [comment]
@ReubenBond i think i can't fix this without deep knowlege of Orleans

**Comment by Lionhunter3k** [comment]
Any news on this? I think i might have the same problem....

**Comment by Arshia001** [comment]
@ReubenBond 

> I believe we should implement something along these lines:

One of my production systems just got hit hard by this issue; as in half of our users were essentially locked out for a couple days before we could pinpoint the problem and publish the fix. These call chains get rather hard to decode once they're long enough.

Your suggestion here is exactly what I was just going to suggest, though with less technical details. It seems simple enough. Is there a reason why it hasn't been implemented yet (performance issues perhaps)? I could try to implement it, though I'm not making any promises.

**Comment by randrewy** [comment]
Waiting for this to be fixed as well.

**Comment by EdeMeijer** [comment]
May I suggest, if this would be implemented at some point, to also give us the option to wipe the call chain information for consecutive requests. For example for many OneWay call scenario's it's desirable to stop call chain reentrancy. I currently have fully disabled call chain reentrancy because of unintended reentrancy happening in addition to the problem described in this issue and it would be nice to be able to opt out / reset the behaviour on a per-request basis.

**Comment by MrMint** [comment]
I ran into this as well, are there plans to review the PR submitted by @Arshia001 ?

**Comment by randrewy** [comment]
@ReubenBond any news on this? There are so many open issues about reentrancy and not a single one gives a clear answer what is happening with this feature. 
Feature was reverted (https://github.com/dotnet/orleans/pull/5249) 3 years ago and it's future is unclear.

If you need a hand on this, I'm willing to try. Are there any other concerns besides performance issues?

**Comment by ReubenBond** [comment]
@randrewy I had a go at this: #7770

**Comment by randrewy** [comment]
awesome news!
