### ISSUE TITLE
Should require many grains one time or multiple time?

### ISSUE THREAD

**Issue by ryanzll** [dotnet/orleans#5474]
If there are many tasks, and each task should create a grains. Should create those grains one time ? 
I think Orleans know its work load, can cache all tasks(grains) required by client and then dispatch tasks to soils intelligently. If not, what is strategy? Should client cache all tasks and then require grains in batch ? but how much should require one time for client don't know work load of Orleans and soil?

Furthermore, Can Orleans scale in and out automatically according work load with something like K8t, Swarm?

Thanks

**Comment by JorgeCandeias** [comment]
What do these *tasks* need to do exactly? Do they require long-lasting consistent state between multiple calls? Or are they one-shot stateless compute workloads?

**Comment by ryanzll** [comment]
Maybe there are something misunderstand. Take a example, there are 100k independent tasks that should create 100k grains, and Orleans cluster can process 10k tasks one time. So the solution may be
solution 1: split all tasks into 10 batch which contains 10k tasks, send first batch to Orleans and then second batch after first batch finished.
solution 2: send all tasks to Orleans, it will cache all grains and then dispatch to soils intelligently.

BTW: one task may take several minutes, and no need to keep state between tasks/grains.

**Comment by JorgeCandeias** [comment]
Option 3: To maintain some steady workload on the cluster, we can make use of the [AsyncPipeline](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Async/AsyncPipeline.cs).

> one task may take several minutes,

Orleans limits task execution to 30 seconds by default and will log warnings about task executions longer than 200ms. This is for a good reason: Orleans uses a turn-based cooperative scheduler with fixed thread count, highly tuned for massive concurrency of short-lived interactive workloads against stateful actors. The drawback is that a run-away long-lived task can hog a cooperative thread and impact performance. While we can lift both these limits, it's often best to put long-lived workloads on the main thread pool and use grains to monitor these tasks instead and possibly recover them if the host *silo* (not "soil") collapses.

> and no need to keep state between tasks/grains.

`[StatelessWorker]` grains always activate in the silo where they are called from or in the gateway silo, if called from a client. They are activated in a pool of grains, sized to the number of cores by default, though we can configure this. They are perfect for stateless workloads, as we pay no extra hops across the cluster and the pool scales as needed up its limit. However we still needs to keep in mind the execution time limit.

Question: Why do these tasks take several minutes? Are they pure compute or are they mostly waiting on external systems to respond?

**Comment by ryanzll** [comment]
Thanks for your detailed explaination!

1. Do you mean that my two solutions are workable and AsyncPipeline is another solution?  If that

- For solution 1, **how can know the count of grains that Orleans can process one time**? 

- For solution 2, currently Orlean already can cache all request to grains if exceed total workload, right? 

2. long-run task. I have known that it is better to use external task(default thread pool).

3. StatelessWorker. According to official document - https://dotnet.github.io/orleans/Documentation/grains/stateless_worker_grains.html, "Requests made to Stateless Worker grains are always executed locally", it seams that StatelessWorker only incur in one silo. I don't quite understand that document.

4. The tasks are getting geometry datas from database, get new values via geometry and math compution and then write back to database; after that, it will compute summary values from new values and write back to database. 
    Currently, I just do some experiment and not get accurate time-comsuming, and not sure 30s is enough only for geometry and math compution or summary calculation.
    I can use other technologies like redis, message queue with background worker to write back to database.

**Comment by JorgeCandeias** [comment]
> * For solution 1, **how can know the count of grains that Orleans can process one time**?

I'm not sure whether there's some misunderstanding with concepts here. Grains are *not* tasks. Orleans does not *process grains*.

Grains are *actors* in the [Actor Model](https://en.wikipedia.org/wiki/Actor_model) sense of the word. Orleans *activates* a grain instance somewhere in the cluster, as defined by your application, and upon the first request to it. A grain *activation* is nothing but an instance of a grain class held in memory somewhere in the cluster. We can have millions of grains activated on the cluster at any time, if memory allows. This does not mean all the grains are doing work all the time.

Orleans *executes* requests sent to these grains as defined by your application. This is when actual work happens. The limitations here are no different from any other system. Only as many threads will ever run *at the same time* on a box as cores that box has. Multitasking is an illusion, only achieved by stopping some threads to allow other to proceed, which sabotages overall throughput. Orleans avoids this problem by using a cooperative fixed-thread scheduler with only as many worker threads as cores the host has. This scheduler is tuned to churn through a ridiculous amount of *tasks* ([in the .NET sense of the word](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=netcore-2.1)), provided we use the [async await](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/) pattern diligently within the task code to yield whatever thread that task is running on.

As for performance guidelines, in my experience, the most realistic way to find how many *tasks* Orleans can process *per unit of time* is to prototype the particular use case and swamp the cluster gradually  to see when we start getting diminishing returns. This is where the [Async Pipeline](https://github.com/dotnet/orleans/blob/master/src/Orleans.Core/Async/AsyncPipeline.cs) comes in handy. Also the super neat [Orleans Dashboard](https://github.com/OrleansContrib/OrleansDashboard).

With that in mind...

> solution 1: split all tasks into 10 batch which contains 10k tasks, send first batch to Orleans and then second batch **after first batch finished**.

This works but it's inneficient. The initial fan-out is fine, but while we are waiting for the tail of the first batch to complete, there's a fair chance most of the cluster is just sitting there twiddling its thumbs, until we decide to start the second batch.

> * For solution 2, currently Orlean already can cache all request to grains if exceed total workload, right?

By *caching*, do you mean *queing* requests if the target actors are busy? If so, then yes. If not, I don't understand what you mean.

> 2. long-run task. I have known that it is better to use external task(default thread pool).

The reason for this is that the default thread pool can create more threads as required by the workload. The drawback is that having more threads than cores induces the underlying preemptive scheduler of the operating system to go happy on suspending threads in order to allow every thread a share of the resources. This is less than optimal but at least it provides the illusion of multitasking and doesn't block other short-lived grain requests from running.

> 3. StatelessWorker. According to official document - https://dotnet.github.io/orleans/Documentation/grains/stateless_worker_grains.html, "Requests made to Stateless Worker grains are always executed locally", it seams that StatelessWorker only incur in one silo. I don't quite understand that document.

Stateless Workers are created in a dynamic pool, as opposed to being individual actors. When you make a request from some grain to a stateless worker, that request is always routed to a pool of these stateless workers *in the same silo* where the requestor itself is. If the request is coming from a grain client (not from a grain in some silo) that is talking to a gateway silo, the request is routed to the pool in that very gateway silo. In either case, the request will not hop anywhere else.

> 4. The tasks are getting geometry datas from database, get new values via geometry and math compution and then write back to database; after that, it will compute summary values from new values and write back to database.
>        Currently, I just do some experiment and not get accurate time-comsuming, and not sure 30s is enough only for geometry and math compution or summary calculation.
>        I can use other technologies like redis, message queue with background worker to write back to database.

It would be interesting to see how much time is spent on actual computation and how much time is spent on external i/o.

Also, do you need a request/response behaviour for this workload? If not, this opens up...

Option 4: Use a [Stream Queue Adapter](https://dotnet.github.io/orleans/Documentation/streaming/stream_providers.html).

**Comment by ryanzll** [comment]
Thanks very much, I get much information about internal operations from your reply.

- "For solution 2, currently Orlean already can cache all request to grains if exceed total workload, right?"
It doesn't means that queing requests if the target actors are busy. If there are 100 cores in cluster and 10k requests to different grains, i understand that Orleans will create 10k of grains, cached them in memory and then run them in turn.

- Async Pipeline. I can't find any documents about this, and don't how to use it.

I think solve these problems may need to dig into source code and know more about internal of Orleans, and the official documents about architecture or implement that help understanding source code are not enough, hope can improve in future.

**Comment by JorgeCandeias** [comment]
> It doesn't means that queing requests if the target actors are busy. If there are 100 cores in cluster and 10k requests to different grains, i understand that Orleans will create 10k of grains, cached them in memory and then run them in turn.

Ah got it. Grains will stay activated until some time of inactivity is reached. I think the default is two hours. This is configurable silo-wide or per grain type. We can also deactivate at will by calling `DeactivateOnIdle()` from within an individual grain.

> Async Pipeline. I can't find any documents about this, and don't how to use it.

``` csharp
// define a pipeline with a max count of parallel requests
var pipeline = new AsyncPipeline(100);

// add a single task - will block until the task can execute
pipeline.Add(client.GetGrain<ISomeGrain>("SomeId").DoSomethingAsync());

// adds 10000 tasks
// this works by enumerating through them and blocking as appropriate to keep at capacity
// this makes it safe to pass a linq enumeration as tasks will only be started once the enumerator gets to them
pipeline.AddRange(
    Enumerable
        .Range(1, 10000)
        .Select(n => client.GetGrain<ISomeGrain>("SomeId").DoSomethingAsync()));

// block and wait for remaining tasks to complete
pipeline.Wait();
```
The above is from the top of my head. With some luck it may even compile! 😄

**Comment by PccCodesix** [comment]
@JorgeCandeias 
  I read the answer above, and I have some questions.
  If I activate two grains of the same type in different silos, and  silos in different hosts , in clusters,
  is that means these two grains are in a pool? how can guarantee their sequential execution?
  or that this activation will not happen. The same grains will only be activated in the same silo, even if 
  two soils can carry this type of grains

**Comment by sergeybykov** [comment]
@PccCodesix Each grain has a unique identity within a grain type. If you call two different grains (with two different keys), they will both get activated in the cluster, but are treated as completely unrelated to each other. If you make two calls to the same grain (same grain key), only one instance will be activated in the cluster, and both calls will get invoked on it, serially.

You can use N grain keys to get N respective grains activated and distribute requests to those grains in some fashion, for example, randomly or round-robin. That way your application logic will treat those N grains as a logical pool of grains. However, from the Orleans perspective, they will be treated as N independent grains.

Does this answer your question?

**Comment by PccCodesix** [comment]
@sergeybykov  
Thank you for your answer.
Can I understand that，because treat those N grains as a logical pool of grains，so Whatever soil they areactivated , they can be executed sequentially.This is controlled by Orleans。

**Comment by sergeybykov** [comment]
It's the opposite - these N grains viewed by Orleans as just N independent grains. No sequential execution across them and no coordination will be done by Orleans.

The application code can decide how to invoke these N grains. For example, you can pick a random grain out of these N grains for each request. That can help parallelize processing of such requests. But Orleans will treat them as completely independent requests.

**Comment by PccCodesix** [comment]
@sergeybykov 
Thank you for your answer  ,I understand how they work.

**Comment by sergeybykov** [comment]
Can we close this now?

**Comment by PccCodesix** [comment]
> Can we close this now?

For me, I have no more questions about this issues. 
But I don't know if 	ryanzll  does, Maybe it can be close

**Comment by ryanzll** [comment]
Thanks for help. I have no more questions, it can be closed.
