### ISSUE TITLE
What is the Relaese date for Microsoft Orleans which can support service fabric?

### ISSUE THREAD

**Issue by SandeepRCH** [dotnet/orleans#5613]
Hi Team, 

We are planning to introduce Microsoft Orleans to our Service Fabric Cluster, but we observed some limitation in existing Orleans, as per few documentation Microsoft.Orleans.Clustering.ServiceFabric is not available since the release of orleans 2.0. 
So can we know by when a new version will be released which is capable to host in Service Fabric? 

We believe the new version supports both .NET Core and .NET Framework. 

Thanks Sandeep.

**Comment by Liversage** [comment]
The `Microsoft.Orleans.Clustering.ServiceFabric` package allows you to use Service Fabric itself for cluster membership. However, I believe there is a flaw in the implementation (see #4588).

Fortunately, you can use an existing cluster membership provider (like Azure Storage or whatever aligns with how you store state in your cluster) and then host the cluster as a stateless Service Fabric service. To integrate Orleans with Service Fabric you have to use the `Microsoft.Orleans.Hosting.ServiceFabric` package. I don't believe there is any documentation but the [Orleans.Hosting.ServiceFabric](https://github.com/dotnet/orleans/tree/master/src/Azure/Orleans.Hosting.ServiceFabric) sample gives you a good starting point.

**Comment by sergeybykov** [comment]
Like @Liversage already said, you a clustering provider like the Azure Storage one is the easiest way to run Orleans on SF today. The flaw in the original implementation has to do with the need for a complete linearizable history of the cluster state, and that requires some significant rewriting of the provider logic. Since there's already a working and proven solution, the priority of the rewrite is rather low for us at the moment.
