### ISSUE TITLE
Reminders with long period invoked before their due time

### ISSUE THREAD

**Issue by shlomiw** [dotnet/orleans#5659]
We've encountered cases of reminders are invoked before their due time.

Log example:
"reminder tickStatus:<1/10/2019 12:00:03 AM, 1.00:00:00, 5/28/2019 11:59:44 PM>"
<FirstTickTime, Period, CurrentTickTime>

As you can see the period is daily and the reminder should be invoked at time >= 12:00:03 AM, but it was invoked at 11:59:44 PM which is almost 20 seconds before its time.

We've seen this in many cases for reminders with periods of hours (usually a day) or multiple days.

I looked at the reminders code and it seems fine. Internally it uses `System.Threading.Timer`. I've tried to stress it on my local workstation with long period timers but couldn't reproduce this behavior yet.
Though our production environment is Google Cloud VM's and maybe it's related (I'll try to stress there too).
We've validated that all the silo's VM's clocks are synchronized with NTP.

Please consider simple defense mechanism of when the timer invoked, to validate 'now' against the expected 'dueTime', and if it was invoked ahead of time, then reschedule.

Thanks!

**Comment by shlomiw** [comment]
I've stressed our GCP environment with many timers and I can confirm there are timers which are invoked ahead of time. For now I've seen diff of above 100ms. 

I'll try to see if there's something in the VM environment that can help.

> Please consider simple defense mechanism of when the timer invoked, to validate 'now' against the expected 'dueTime', and if it was invoked ahead of time, then reschedule.

This should solve it!
Sometimes it's unacceptable for reminders to tick ahead of time, and Orleans can help prevent this :)

**Comment by sergeybykov** [comment]
We rely on .NET timers to fire at the right time. While we could detect a prematurely firing .NET timer and schedule another tick at the originally requested time, I wonder if it's worth the complexity to essentially work around .NET timers. Reminders are even trickier because they are persistent.

**Comment by shlomiw** [comment]
@sergeybykov - it apparent that .Net timers are not reliable enough, probably especially on VM's. If you consider the reminders only as a mean to activate the grain periodically, and the exact time is not essential, then maybe it's not worth the effort. 

We're using reminders also for cron jobs with exact scheduling, and if it fires ahead of time, it's really bad for us (I can give some examples if needed). For the long period reminders (days ahead) I've seen drifts of 20-30 seconds (!!).
For now, I've added a defense in one of the essential logics, but I'd rather not putting this defense everywhere, I believe it should be on Orleans responsibility to handle it.

At-least, reminders should guarantee of not firing **before** their time, then instead of complicated recurring timers (for rescheduling in case of drift before or after), just add a small (I hope) defense that if it woke up before of its time, in relation to the system clock, then reschedule the timer again.

Thanks in advance for your consideration.

**Comment by sergeybykov** [comment]
It would really help to have a repro. I see three possibilities here.

1. A bug in Orleans code. Seems unlikely (but not impossible) because we don't perform any serious manipulations with time values.
2. A bug in .NET runtime code. Seems unlikely in Windows environment because of how widely timer have been used.
3. Environment specific issue, such as GCP, Linux (this is on Linux, right?). Hard to tell.

In case of 2 or 3, a repro doesn't require Orleans. Seem like scheduling a .NET timer several days ahead would be sufficient. If that's the case, then such a bug should be reported to the .NET team I think.

Regardless of all of this, note that it's a risky pattern to schedule a reminder for a very long time ahead. The reminder service does not track or record successful delivery of reminder ticks. That means that if the cluster or the silo responsible for delivering a particular tick happens to be down at the exact moment when a reminder is scheduled to fire, the tick will be missed, and only the next tick will get fired. With long reminder intervals it might not be what you want.

Because of that, the pattern we recommend is to schedule reminders to fire more frequently, and have the grain check if it's now time to execute the scheduled action. That way, even if an individual tick is missed, for example, due to an upgrade of the cluster, the subsequent tick wouldn't be too far off. If, say, you need a 24 hour reminder, you can schedule a recurring 6 hour reminder instead, and check every 6 hours if the time is now.

Also in general, reminders aren't meant to be very precise because of their dependency on storage, messaging, and the time it takes to reconfigure during a cluster state change. For more precise execution, the recommendation is to use a combination of a reminder and a timer. Timer is local, and hence can fire more accurately.

**Comment by shlomiw** [comment]
Thanks for your thorough reply! appreciated as always!

1. I don't think it's an Orleans bug since it's using normal .Net timers internally.
2. From what I read - .Net timers might not be fully aligned with the system clock:  https://stackoverflow.com/a/2432601/712004.
3. We currently host on GCP with windows environment (we plan to move to full .Net core and Linux to cut expenses in the future).

> Regardless of all of this, note that it's a risky pattern to schedule a reminder for a very long time ahead. The reminder service does not track or record successful delivery of reminder ticks. That means that if the cluster or the silo responsible for delivering a particular tick happens to be down at the exact moment when a reminder is scheduled to fire, the tick will be missed, and only the next tick will get fired. With long reminder intervals it might not be what you want.

I'm fully aware of that. What we usually do, is to schedule a due time in the future, and always have an interval period of 1 minute to allow error handling or failure to fire on time due to silo host is down.

> Because of that, the pattern we recommend is to schedule reminders to fire more frequently, and have the grain check if it's now time to execute the scheduled action. That way, even if an individual tick is missed, for example, due to an upgrade of the cluster, the subsequent tick wouldn't be too far off. If, say, you need a 24 hour reminder, you can schedule a recurring 6 hour reminder instead, and check every 6 hours if the time is now.

Maybe, in case we do need a very precise timing, I should do something similar and make sure I'm scheduling to a time near my due time (1 hour.. or mintues), then reschedule again. I can add a general logic to handle it.

But that will help only our team... maybe others also rely of precise scheduling.  I do think that Orleans should at least guarantee that reminders run at time >= dueTime. This could be achieved with the simple (?) aforementioned defense.
If not - maybe note that in the reminders docs?

Anyway up to you guys. Thanks again! Should I close this issue?

**Comment by sergeybykov** [comment]
@shlomiw 
>I do think that Orleans should at least guarantee that reminders run at time >= dueTime. This could be achieved with the simple (?) aforementioned defense.

I guess we could add a defensive check and delay firing a reminder if we determine that it's too early, to compensate for potential drifts of .NET timers. If that doesn't add much complexity to the logic and impacts performance. Are you interested in contributing such a feature?

**Comment by shlomiw** [comment]
@sergeybykov 
Of course I'm interested :smile: 
As most of us, my hands are full at the moment, will keep this one in my backlog.
