### ISSUE TITLE
Journaling grain and event sourcing

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/orleans#5676]
Hello,

First of all I want to give my appreciation to the team and contributors to Orleans, it's a great solution for distributed computing. I've been working with it for awhile now and I'm very pleased with both functionality and how nicely it fits with modern architecture and design.

This issue is more about the documentation and somewhat about events with journaled grains in the context of event sourcing. Let me give my observations.

At the heart of event sourcing is the statement that an event signals that a state has changed, meaning that any subscriber to the event can rest assure that the state is consistent with the event. The journaled grain however uses the event as to signal that the state should change, e.g. with this event persist update to storage.

This is a typical call chain with Orleans.EventSourcing.CustomStorage (never mind the ReadStateFromStorage that might or not happen before the chain described):

1. RaiseEvent tells the provider that an event is to be fired
2. ApplyUpdatesToStorage is called to persist the event to storage
3. Apply (or TransitionState) is called to update aggregate state

As I understand it and see from other event sourcing solutions, the chain maybe should be this:

1. ApplyUpdatesToStorage (to change the domain state, meaning persist event(s))
2. RaiseEvent tells the provider that domain state has changed
3. Apply (or TransitionState) is called to update aggregate state

It's kind of backwards in the implementation of Orleans with the semantics of events in the context of event sourcing. This initially caused me confusion and I had to try to figure out what was going on before I finally realized the mechanics. I don't propose to do anything, rather maybe in the documentation try to highlight if needed the difference.

Kind regards,
//Jan

**Comment by sergeybykov** [comment]
@jan-johansson-mr 
Sorry about responding to this with such a delay!

Your feedback is totally fair. Thank you for that! The approach in `JournaledGrain` and its surrounding infrastructure does not match the typical approach in Event Sourcing. The main reason for the discrepancy was the attempt to use the same abstraction also for multi-cluster replication.

Our view is that instead of trying to get a single authoritative abstraction for each pattern, we should embrace multiple overlapping approaches, so that each of them would be good for a particular goal. In that sense, we are open to a parallel abstraction for Event Sourcing that would match the typical approach in the industry without worrying  about being compatible with the multi-cluster replication.
