### ISSUE TITLE
hot grain best way to do?

### ISSUE THREAD

**Issue by gwhzh21** [dotnet/orleans#5725]
The grain is designed to obtain the tenant token. The token is from a third party and will be refreshed and updated every 2 hours. But there are more customers who visit a tenant token at the same time, and may reach thousands. Is this hot grain? If so, how to avoid it. Note that the token is not related to the customer and is only relevant to the tenant.

**Comment by ReubenBond** [comment]
@gwhzh21 here are two ways to alleviate pressure on a hot grain here:

1. Create a local cache for the tenant token, eg a class which caches the value. Other grains can access the value using that cache.
2. Use stateless workers so that there are multiple copies of the grain on each silo.

I recommend option 1, since it's simple and most of the time you can avoid making a grain call.

**Comment by gwhzh21** [comment]
@ReubenBond good idea.thanks.
