### ISSUE TITLE
TimeoutException when OnDeactivateAsync call other deactivating grain

### ISSUE THREAD

**Issue by adampapp** [dotnet/orleans#5736]
There is an issue in our production system. When a grain is deactivating we want to call other grain to do its operations. But if the other grain is in deactivation state at the same time it seems the code came in deadlock (or something) and we got a timeout exception.
With the attached minimal sample code the issue can be reproduce.
[sample.zip](https://github.com/dotnet/orleans/files/3363091/sample.zip)
Our workaround is shift the collection ages' the grains.

Is it a bug or is there a better solution? 

Enviroment:
ubuntu 16.04
dotnet sdk 2.2.300
orleans 2.3.5

**Comment by sergeybykov** [comment]
At a first glance, this looks to me like a 'normal' deadlock between two non-reentrant grains calling each other at exact same time. If you make one of both of the grain classes as `[Reentrant]`, the timeout might go away.

That being said, we generally discourage people from putting any significant logic into `OnDeactivateAsync` because a) it may never execute, for example, in case of a silo failure or ungraceful shutdown; and b) deactivation of grain is supposed to happen very fast, which leaves little room for handling failures of calls or operations a deactivating grain is trying to execute. The advise is to use `OnDeactivateAsync` mostly for best effort notification or an attempt to unsubscribe from another grain or a stream.

**Comment by adampapp** [comment]
In our system the grains don't calling each other, the pipeline is A grain calls B grain and B grain calls C grain in onDeactivateAsync but the error is the same as the example.
Is it also a 'normal' deadlock?

**Comment by sergeybykov** [comment]
In the sample code you attached, `FirstGrain` does call `SecondGrain` from within its `OnDeactivateAsync` while `SecondGrain` calls `FirstGrain` from within its. That may cause a deadlock with both grains getting deactivated at exact same time.
