### ISSUE TITLE
Silo fail to start if have other active silos in membership table

### ISSUE THREAD

**Issue by stgolem** [dotnet/orleans#5781]
We've detected some unwanted behavior with single silo start after whole cluster fail unexpectedly.
We use SQL membership Provider and here is sample reproduce code:

```csharp
            var host = new SiloHostBuilder()
                .Configure<ClusterOptions>(options =>
                {
                    options.ClusterId = "dev";
                    options.ServiceId = "dev";
                })
                .ConfigureEndpoints(11111, 30000)
                .UseAdoNetClustering(options =>
                {
                    options.Invariant = "System.Data.SqlClient";
                    options.ConnectionString = "Data Source=localhost;Initial Catalog=OrleansTest;Integrated Security=true";
                })
                .Build();

            try
            {
                await host.StartAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

           await host.StopAsync();
```

And suppose we have 3 silos before crash occured:

```sql
insert into OrleansMembershipTable (DeploymentId, Address, Port, Generation, SiloName, HostName, Status, ProxyPort, StartTime, IAmAliveTime)
values
    ('dev', '192.168.18.113', 11111, 301637233, 'Silo_11111', 'siloserver1', 3, 30000, DATEADD(MINUTE, -10, SYSUTCDATETIME()), DATEADD(MINUTE, -1, SYSUTCDATETIME()))
   ,('dev', '192.168.18.114', 11111, 301637233, 'Silo_11112', 'siloserver2', 3, 30000, DATEADD(MINUTE, -10, SYSUTCDATETIME()), DATEADD(MINUTE, -1, SYSUTCDATETIME()))
   ,('dev', '192.168.18.115', 11111, 301637233, 'Silo_11113', 'siloserver3', 3, 30000, DATEADD(MINUTE, -10, SYSUTCDATETIME()), DATEADD(MINUTE, -1, SYSUTCDATETIME()))
```

Then we start silo only at **siloserver1**.
We expect that this silo will drop all others and start succesfully but we get timeout at `host.StartAsync();`.

I am aware of some similar issues #5463 #3009 and the behavior implemented in #3261 
But the problem is we cannot start other nodes - cluster should be self aware and self healing in this scenario. Also with this in mind we do now want to get unexpected errors when some silo got network split from other silos (but not the database).

Can you provide help with that? Can MembershipTable handle this OR we should implement it in our way?

**Comment by stgolem** [comment]
Also here is some logs from starting silo: [orleans.logs.zip](https://github.com/dotnet/orleans/files/3425657/orleans.logs.zip)

**Comment by sergeybykov** [comment]
To clarify, you are killing the cluster and then try to start another silo/cluster with the same cluster ID 'dev'? If that's the case, then this is the expected behavior.

The silo that is starting thinks that there are two other silos already in the cluster, and (by default) it is trying to check that it can communicate with them, to prevent a network partitioned silo from joining the cluster. You can turn the check off via `ClusterMembershipOptions.ValidateInitialConnectivity`, but the silo will still believe those two other silos are in the cluster until they are voted dead, which by default requires one more runing silo.

Eventually (after a few minutes, configurable) the outdated silo entries in the table will expire, and the silo will be able to join the cluster even if you do nothing.

All this logic is to protect production clusters from split-brain cases of silo being network partitioned from each other. For development/testing scenarios, the general recommendation is to generate a new cluster ID for every run or to wipe the table or to use the grain-based membership table instead.

**Comment by srollinet** [comment]
> The silo that is starting thinks that there are two other silos already in the cluster, and (by default) it is trying to check that it can communicate with them, to prevent a network partitioned silo from joining the cluster. You can turn the check off via ClusterMembershipOptions.ValidateInitialConnectivity, but the silo will still believe those two other silos are in the cluster until they are voted dead, which by default requires one more runing silo.
> 
> Eventually (after a few minutes, configurable) the outdated silo entries in the table will expire, and the silo will be able to join the cluster even if you do nothing.

I have the same issue but the lonely silo never starts, even after hours. I also tried to disable `ClusterMembershipOptions.ValidateInitialConnectivity` but it doesn't change anything.

I ended up by doing my own cleanup in the membership table

**Comment by sergeybykov** [comment]
@srollinet Can you still reproduce the problem and provide logs? This shouldn't be happening after 10 minutes (by default).
