### ISSUE TITLE
Blazor Sample does not post Todos

### ISSUE THREAD

**Issue by theorye** [dotnet/orleans#5788]
To replicate, just load as README instructs.  Everything boots and I can get the weather data; however, I can't post a Todo.

**Comment by JorgeCandeias** [comment]
What do you mean by *can't post a todo*?
What exact steps are you performing in this test and what are your expectations?

**Comment by theorye** [comment]
1. Clone the Orleans repo
2. Navigate to the 2.3 Sample for Blazor
3. Run the silo, run the 2 client examples
4. Add a Todo

Expectations:  A Todo is added and is listed.

Atm, the button to submit the Todo does nothing.  No error messages.
I am able to get the weather information.

**Comment by JorgeCandeias** [comment]
Are you able to test all the endpoints as described in the readme?

For example http://localhost:8081/swagger/index.html should give you direct access to the rest api, where you can issue direct requests. Does this work?

Otherwise, are you using any browser interceptors, such as Fiddler?
If so, do they show anything noteworthy?

**Comment by theorye** [comment]
This issue is resolved by adding @ to "bind"

```
<input placeholder="Something todo" @bind="@newTodo" />
```
