### ISSUE TITLE
Curious: what is difference between this technology and the old fashion EJB?

### ISSUE THREAD

**Issue by andy-yx-chen** [dotnet/orleans#5853]
As the title

**Comment by philbe** [comment]
Most developers find it much easier to write scalable, distributed, elastic, fault-tolerant applications in Orleans than in EJB.

Last I looked, EJB requires static placement of objects, e.g., by mapping class-to-server or class-partition-to-server. By contract, Orleans supports the virtual actor model, so grains are active in memory only while they’re being used. Orleans maps grains to servers dynamically, and hence is elastically scalable. It's also fault tolerant, because grains that are lost in a server failure are immediately re-activated on another server on their next invocation.

EJB is intended to support at most a moderate number of objects, i.e., thousands, not millions as in Orleans.

EJB objects are multithreaded servers, so programs need to synchronize access to shared memory, and they communicate via synchronous RPC. For better programmability, Orleans grains are normally single-threaded, so no synchronization is required to shared state, and to support parallelism they communicate by asynchronous RPC using .NET's async/await.

**Comment by andy-yx-chen** [comment]
All these points are valid, however, 
1. Theoretically, EJB can also do dynamic activation, with the support of JPA, in that case, it could be scaled to millions of objects as well.
2. async/await could be replaced with completableFuture in java
3.  the following point could be implemented by zookeeper based CV liked sementic
> grains that are lost in a server failure are immediately re-activated on another server on their next invocation

So, overall, this sounds to me like a modern EJB that helps the IoT world

**Comment by sergeybykov** [comment]
I personally try to stay away from direct comparisons between technologies that are different enough that it quickly becomes meaningless. They started from different goals in mind, targeting different developer audiences and different environments, and evolved differently. So, I would advise against distilling it to something like "Orleans is like Uber, but for EJB." 🙂

**Comment by andy-yx-chen** [comment]
I am in a different perspective though, say, technically, if this look like EJB framework, then we should learn lessons from EJB about why EJB got kicked out from the world, so that we can do something different to help developers. One thing that I don't see from the examples is the cancellation token, which is very important to save the system resources but it's not there.

writing a service in this framework looks very similar to writing an EJB, I don't know how we can ask developers going back to 90's  but it looks like we could

**Comment by sergeybykov** [comment]
I can say that Orleans was designed without EJB in mind. It was built for emerging (at the time) cloud workloads to help developers that are not distributed systems experts be successful and productive in the cloud era. Hence, I disagree with your characterization of "we can ask developers going back to 90's." Inevitably, there are parallels with previous systems, be it EJB or Erlang. But I don't think it's fair to pidgenhole Orleans as modern X. It's a different system with its own set of choices and tradeoffs.

>One thing that I don't see from the examples is the cancellation token, which is very important to save the system resources but it's not there.

Orleans does have a notion of [cancellation tokens](dotnet.github.io/orleans/Documentation/grains/cancellation_tokens.html). However, it's more of a fringe feature, considering that Orleans is optimized for more interactive workloads where long running operations are more of an exception.

**Comment by andy-yx-chen** [comment]
Thanks for the cancellation tokens example @sergeybykov
