### ISSUE TITLE
Race condition with streams when AllowCallChainReentrancy is enabled.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [dotnet/orleans#5885]
When A sends a message through a stream to B1 and B2 and both of them calls A in the event handler, the calls B1->A and B2->A interleave.

```
      /-------> B1 -------------\
     / (Stream)    (Direct call) \
A ---                             ---> A
     \ (Stream)    (Direct call) /
      \-------> B2 -------------/
        ^^^^^^
These two arrive at the same time and both are allowed to interleave because of
call chain reentrancy. They should be allowed to interleave individually but not each other.
```

**Comment by kehigginbotham** [comment]
@yusuf-gunaydin Are you using SMS Streams?

I believe we have the same issue happening when developing locally using SMS, but we've yet to encounter it in our other environments (testing / production use Azure Event Hubs).

We added semaphores as a hack.  We're considering disabling AllowCallChainReentrancy (we use FireAndForget on our SMS stream) if it is indeed the correct functionality.

**Comment by yusuf-gunaydin** [comment]
@kehigginbotham Yes, I am using SMS provider. In my case FireAndForget does not change the behavior. If I recall correctly, SMS's `OnNextAsync` calls are processed in parallel. So, both callbacks run at the same time.

There should not be a need for mutexes or semaphores. One of the most important promises of Orleans is the guarantee that a grain executes only one message at a time and this issue breaks that promise.

**Comment by sergeybykov** [comment]
`OnNextAsync` in case of the SMS provider acts as a direct fan-out call to all subscribers. This is equivalent to A calling B1 and B2 in parallel *within the same call chain*. From that perspective, it seems to me that the observed behavior is expected. With any storage-based stream provider this wouldn't be the case because there producer is truly decoupled from consumers.

SMS is a weird provider in that sense. In the hindsight, maybe it was a mistake to even introduce it. I guess we could look at intentionally breaking the call chain for SMS. I wonder if that will disrupt people relying on the existing behavior.
