### ISSUE TITLE
OrleansQuery table rationale versus stored procs

### ISSUE THREAD

**Issue by mv10-work** [dotnet/orleans#5931]
I found it curious that Orleans uses inline queries stored in the `OrleansQuery` table (at least, for ADO.NET SQL Server, I didn't look at other providers or targets). I'm wondering why stored procedures weren't used. I realize modern RDBMS query processing results in approximately equivalent performance after the first run of a given inline query. However, you have to provide setup scripts anyway, and Orleans seems to be the kind of system where every last ounce of performance helps, so this was an unexpected choice. Fewer permissions required to get the system up and running, perhaps?

Just curious. I'm an architecture guy considering this as the basis for a microservice layer and I expect somebody will ask, sooner or later. I'd like to know if there's a better answer than "approximately equivalent performance."

**Comment by veikkoeeva** [comment]
@mv10-work I'm glad you asked. There is no special reason to favour queries as opposed to stored procedures. One reason originally was that it would look "approximately the same" across all ADO.NET providers since not all have stored procedures.

I can expand to this a bit. As you may have noticed, Orleans basically just cares only that it has the right names and types of parameters and it sends the script along with the parametrized data to the database. So you could just update the scripts to have, say, a compiled procedure and make the script to `exec` that procedure (which isn't 100% the same as using the protocol, I suppose).

The reason for this design was that one likely wants to apply schemas, filegroups and other things per project basis. One's physical machine, license and combination with data may differ too and maybe there's a need to update things on-the-fly and just update the queries the engine uses. The security and/or DBAs may want to be sure they at all times know what kind of queries come to the DB (no unexpected changes as ORM updates might do, or priviledges can be tightly managed). Also not all features are available on all tiers. One example in SQL Server being natively compiled stored procedures and in-memory tables for `Storage`, but this way it can be updated by those who have those. You may perhaps see other uses too, such as splitting `Storage` to cold data going to Hadoop. Or in enterprise setting going to disk instead of more expensive SSD and so on. Or perhaps using multiple tables without table partitioning by just updating the queries.

I have an example coming using DACPAC at https://github.com/dotnet/orleans/pull/5909 that splits the scripts, does schemas and filegroups and all that what comes to database. Beyond that, I have working code that uses IdentityServer in same fashion as the API (sets up test users, call the APIs and retrieve them etc.), I think, based on the example you've set without using ORM. Though coming as a separate update later unless you want to amend the example later. :)

There are some old tickets that go deeper into practicalities about this that I can dig up if you are interested. This is lightly touched also in documents too. There is room for improvements, especially now that 3.0 is coming anyhow, for instance reminders when there's a lot of them. One can even now add indexes, but I think it'd be better to use narrow index (like `Storage`) and see the range queries are really efficient.


I also noticed a small problem in the membership protocol in the tests if I start something like 8-16 siloes at once, there'll be a primary key violation. I added a locking hint and it fixed it but I should make a PR to the main scripts too. These are low traffic tables, so not that easily bitten by these problems, but should naturally fixed (and the INSERTs could be more robust without forcing the hand of the engine with hints, but back in the day I though that it's easier if things are fairly similar across all the ADO.NET vendors).

**Comment by veikkoeeva** [comment]
As this touches security and GDPR, I'll link a recent note on differential privacy extensions and homomorphic data discussion at https://gitter.im/dotnet/orleans?at=5d71347b767de913fc890c42.

**Comment by veikkoeeva** [comment]
As for history, let's record here, one of the scripts (at some point) to add data and test things was https://gitter.im/dotnet/orleans?at=5d2ef182f4fe9439712316d2

```
INSERT INTO Storage
(
    GrainIdHash,
    GrainIdString,
    GrainTypeHash,
    GrainTypeString,
    ServiceId,
    PayloadBinary,
    PayloadJson,
    PayloadXml,
    ModifiedOn,
    Version
)
SELECT
    A.x,
    (N'GrainIdString_' + CAST(A.x AS NVARCHAR)),
    B.x,
    (N'GrainTypeString_' + CAST(B.x AS NVARCHAR)),
    N'TestService',
    NULL,
    N'{ "SomeObjectPayload": "' + (N'GrainIdString_' + CAST(A.x AS NVARCHAR)) + N'__' + (N'GrainTypeString_' + CAST(B.x AS NVARCHAR)) + N'" }',
    NULL,
    GETUTCDATE(),
    1
FROM
(    
    SELECT(kilo * 1000 + hecto * 100 + deca * 10 + unit + 1) AS x
    FROM
    --(
        -- SELECT 0 AS myria
        -- UNION ALL SELECT 1
        -- UNION ALL SELECT 2
        -- UNION ALL SELECT 3        
    --) AS my,
    (
        SELECT 0 AS kilo
        UNION ALL SELECT 1
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
        UNION ALL SELECT 8
        UNION ALL SELECT 9
    ) AS k,
    (
        SELECT 0 AS hecto
        UNION ALL SELECT 1
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
        UNION ALL SELECT 8
        UNION ALL SELECT 9
    ) AS ha,
    (
        SELECT 0 AS deca
        UNION ALL SELECT 1
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
        UNION ALL SELECT 8
        UNION ALL SELECT 9
    ) AS da,
    (
        SELECT 0 AS unit
        UNION ALL SELECT 1
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
        UNION ALL SELECT 8
        UNION ALL SELECT 9
    ) AS u
) AS A CROSS JOIN
(
    SELECT(hecto * 100 + deca * 10 + unit + 1) AS x
    FROM
    (
        SELECT 0 AS hecto
        UNION ALL SELECT 1
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
        UNION ALL SELECT 8
        UNION ALL SELECT 9
    ) AS ha,
    (
        SELECT 0 AS deca
        UNION ALL SELECT 1
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
        UNION ALL SELECT 8
        UNION ALL SELECT 9
    ) AS da,
    (
        SELECT 0 AS unit
        UNION ALL SELECT 1
        UNION ALL SELECT 2
        UNION ALL SELECT 3
        UNION ALL SELECT 4
        UNION ALL SELECT 5
        UNION ALL SELECT 6
        UNION ALL SELECT 7
        UNION ALL SELECT 8
        UNION ALL SELECT 9
    ) AS u    
) AS B;

DECLARE @GrainIdHash AS INT = 1;
DECLARE @GrainIdString AS NVARCHAR(150) = N'GrainIdString_1';
DECLARE @GrainTypeHash  AS INT = 1;
DECLARE @GrainTypeString AS NVARCHAR(150) = N'GrainTypeString_1';

DECLARE @PayloadBinary AS VARBINARY(MAX);
DECLARE @PayloadJson AS NVARCHAR(MAX);
DECLARE @PayloadXml AS XML;

DECLARE @GrainStateVersion AS INT = 0;

-- The application code will deserialize the relevant result.
SELECT    
    PayloadBinary,
    PayloadXml,
    PayloadJson
FROM
    Storage
WHERE
    GrainIdHash = @GrainIdHash
    AND GrainTypeHash = @GrainTypeHash    
    AND GrainIdString = @GrainIdString
    AND GrainTypeString = @GrainTypeString OPTION(FAST 1, OPTIMIZE FOR(@GrainIdHash UNKNOWN, @GrainTypeHash UNKNOWN));


-- With the INCLUDE columns the effect of the previous definition
-- should be more like this in "procedural SQL".
SELECT
    PayloadBinary,
    PayloadXml,
    PayloadJson
FROM
(
    SELECT
        PayloadBinary,
        PayloadXml,
        PayloadJson,
        GrainIdString,
        GrainTypeString
    FROM
        Storage
    WHERE
        GrainIdHash = @GrainIdHash
        AND GrainTypeHash = @GrainTypeHash        
) AS collidedRows
WHERE
    collidedRows.GrainIdString = @GrainIdString
    AND collidedRows.GrainTypeString = @GrainTypeString OPTION(FAST 1, OPTIMIZE FOR(@GrainIdHash UNKNOWN, @GrainTypeHash UNKNOWN));

EXEC sp_estimate_data_compression_savings 'dbo', 'Storage', NULL, NULL, 'None';
```

**Comment by veikkoeeva** [comment]
@mv10-work Almost forgot, I'm often in https://gitter.im/dotnet/orleans, but can answer questions equally much here if you prefer. There are things that may not be visible at first look and that maybe in a way or another due to legacy reasons. One legacy reason I would like to fix for .NET 3.0 is [DbProviderFactory](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/obtaining-a-dbproviderfactory) now that it's back in existence. Especially since people may want to choose a different connector library, such as https://github.com/mysql-net/MySqlConnector. So either need to add that or an overload to choose a different library. The ADO.NET provider string is a bit of legacy from times when configuration options were more limited.

**Comment by mv10-work** [comment]
Thanks @veikkoeeva -- I appreciate the detailed response. Very interesting stuff. Unfortunately my company blocks access to gitter, but I'll keep that in mind for the occasions that I'm working on these things from home.

Speaking of ADO.NET (which I'm just now switching to after playing around with the in-memory dev-local stuff) it seems the docs are out of date relative to the 2.4.2 packages. Actually this probably warrants opening a new issue, but since you're here and this came up literally five minutes ago, the code shown in [Configuring ADO.NET Providers](http://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/configuring_ADO.NET_providers.html) does not work. I suspect the Configuration Guide in general should be updated for the generic host `UseOrleans()` approach, but using that or the `new SiloHostBuilder()` approach (which I think is older and going away?) results in a "call is ambiguous" error for the various extension methods (this happens with the provider, reminder, and cluster packages for ADO.NET).

![image](https://user-images.githubusercontent.com/54578900/64422919-375a6c00-d073-11e9-9938-b083b45cefcb.png)

I haven't really dug into it yet though.

**Comment by veikkoeeva** [comment]
@mv10-work The docs should be updated, in fact rearranged too. If you open a new ticket, I'll cross-link them.

The sample at https://github.com/dotnet/orleans/pull/5909 should get you going if you aren't in the mood of debugging docs and libraries. You need to Debug/run the DB project (may need to set connection string first in project pages) or publish it (may require opening the publish profile settings).

It's not the latest code since it's over a year old basically, but fairly close.
