### ISSUE TITLE
String grain id interceptor

### ISSUE THREAD

**Issue by dsarfati** [dotnet/orleans#5933]
@ReubenBond Just moving the conversation to here from Gitter. As I mentioned, we have the issue where string differences (capitalization, extra whitespaces...) in string grain Ids are causing us to activate different grains. 

Right now our team uses `ToUpperInvariant()` any time we use a string id, but we may need to have different rules based on the different grain type. Ideally the logic to make the ids conform to the standard would be something that the grain with the string id would define, not the grain that is trying to access the grain. The proposed solution is to add an id interceptor that could be added to the silo configuration that would allow a developer to convert the requested string id into a "standardized" string.

I'd love to get some feedback and/or ideas on this before writing the code. If this seems like an idea that has support within the community, I can make the changes and open up a PR within the next week or so.

**Comment by SebastianStehle** [comment]
For me this would be a use case for: https://github.com/dotnet/orleans/issues/4519

**Comment by SebastianStehle** [comment]
Have you thought about implementing a custom grain factory as a wrapper around the default implementation?

**Comment by ReubenBond** [comment]
I'm uneasy about exposing a mechanism for mutating grain ids from within the framework, so I endorse @SebastianStehle's comment about wrapping grain factory for this purpose.

My primary concern is about multiple grain references pointing to the same logical entity and what happens when the user changes mutation rules (are persisted references updated, for example).

Assuming there was some out-of-the-box mechanism for this, how should it look/behave and where should the interceptor run?

**Comment by ReubenBond** [comment]
Closing - I think we have an answer here, plus this is inactive.

In 4.0 we will have a more string-friendly grain id
