### ISSUE TITLE
Storage Provider option to use Data Protection API

### ISSUE THREAD

**Issue by MV10** [dotnet/orleans#5952]
I'm wondering if others would see value in a standardized opt-in to have Storage Providers apply encryption via the [Data Protection API](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-3.0) built into ASP.NET Core. It's pretty easy to configure and use -- in a nutshell it ensures data-at-rest (primarily web app session state) is encrypted with a shared key such that any instance of the app in a cluster or another DC can still decrypt the data.

We have been experimenting with an Orleans-based distributed caching mechanism. While it's easy ([one line of code](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection?view=aspnetcore-3.0)) to build this into our caching grains, every time I go back to that code, it "feels like" something that should be configured during startup, rather than a dependency pulled in by a specific grain (given DPAPI itself must also be configured at startup).

I imagine the actual implementation would either be alternate serializers, or given the simplicity, just an options check in the current serializers. (I'm entirely ADO.NET-focused, so I'm not sure exactly how this might map to other Providers.)

It would probably be important to document that DPAPI encryption isn't meant to be used with all state persistence. For instance, we use `StorageProvider` attribs to separate the cache data from other types (although it feels like a very leaky abstraction to tie a hard-coded string value in a grain assembly to a config string value in the silo startup -- an issue for another day, I guess).

**Comment by MV10** [comment]
Oh I forgot to mention another idea that had crossed my mind, which is a serializer attribute like `[Encrypt]` on grain members. When an indexing feature is finally available, it would be very handy to only have sensitive data encrypted in the persisted state.

**Comment by veikkoeeva** [comment]
@MV10 There has been sporadic discussion (similar to the spirit in the other thread). Do you see if there is room to consider a pluggable design?

To consider something more concrete:
- End-to-end where the customer sends something encrypted and even the silo operator doesn't know it. Could fit with [Microsot SEAL](https://github.com/Microsoft/SEAL) or some zero-knowledge-proof systems.
- [Shared secrets](http://www.moserware.com/2011/11/life-death-and-splitting-secrets.html), one example, e.g. to protect in-memoy secrets in case of partial breach to a faction or production servers. A term for search engine: _multi-sig_.

Somehow define "general rails" that it's easy to make use of features with relative ease or maybe produce separate Nuget packages that can be configured and taken into use with relative ease instead of doing an "end-to-end implementation" with all the research of where and how to insert code to do these sort of things. It may be this could be done with the Orleans interceptor design already. I'm already thinking to add an example to [OneBoxDeployment](https://github.com/dotnet/orleans/tree/master/Samples/OneBoxDeployment) that forwards claims from the API to Orleans cluster so that the grains could act on them.

This may be a good case for digital twin scenarios where grains may take semi-automatic action on behalf of users. Also perhaps enrich information, which prompts into consideration if Orleans should adapt some of [Microsoft.AspNetCore.Authentication](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication?view=aspnetcore-2.2).

Having a good pipeline here would make per-client per-operation billing operations easier to build and also tracking messages as per the new distributed tracing (cross-referencing https://github.com/dotnet/orleans/issues/4992).

Or put otherwise, maybe there is a need to see what could be the cross-cutting concerns and build rails that many cases can benefit of, this being one of them.

**Comment by SebastianStehle** [comment]
I think a lot of the storage providers use JSON.NET. You could just write a serializer for annotated fields.

**Comment by MV10** [comment]
To me (again, having only messed with ADO.NET providers) exposing the serializer pluggability to config would be the most flexible approach, but I don't know how realistic that is from an architectural standpoint.

**Comment by veikkoeeva** [comment]
@MV10 Explicitly for ADO.NET the configuration should be exposed better and if it helps here I think doesn't need architecture considerations. I'm entirely sure how the current (de)serializer pluggability could be deployed here, but I know ADO.NET configuration surface isn't well exposed currently and if nothing else, it gives full access to the data.

What one wants to look at is at https://github.com/dotnet/orleans/tree/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider, specifically https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs#L560 is where the (de)serializers are configured. How to (de)serialize ar arbitrary granularity is discussed at https://github.com/dotnet/orleans/issues/5492#issuecomment-482031619 (probably the clearest) and the intention was/is that arbitrary transformations can be done so that data errors can be fixed, refactoring accounted for (renaming etc.) so no data is orphaned, (de)serialization type can be changed (e.g. JSON -> Parquet) and so on. Even encryption or decryption as per security and GDPR if the DB functionality isn't what's desired.

That dates back to Orleans 1.n configuration where it was fixed to XML with one configuration string for connection string and code assuming SQL Server, so had to smuggle ADO.NET variant first through the system and then later refactor to support all ADO.NET and `DbProviderFactory` (which was then yanked, now coming back). There are a few issues discussing about cleaning the configuration interface and exposing the the provider functionality better now that there's an IoC system in place.

**Comment by MV10** [comment]
I have realized the encrypt-everything approach only makes sense for binary serialization. It's obvious in hindsight, but after encryption, neither JSON nor XML would be valid. For similar reasons, a seemingly-simple `[Encrypt]` attribute for grain state fields/properties also means the member type would effectively change (you're no longer serializing an `int` for example,  you're serializing the encrypted version, most likely `byte[]`).

As Sebastian alluded to, value interception for JSON.NET is probably an option, but I was mistakenly under the impression that Orleans used custom serializers for all use cases. The off-the-shelf .NET XML serializer is particularly inflexible.

I had thought maybe the non-Immutable deep-copy system would introduce an opportunity to support this, but if I'm reading the code right, copying relies on the serializers too -- and in any case, capability within deep-copy wouldn't help with deserialization.

**Comment by veikkoeeva** [comment]
Very good points. I should have remembered poking a bit about this back in the day. Reminds me to always mention VETRO (the integration pattern, not necessarily the micro services pattern) and how much work it would be to have a per-call configurable pipeline between clients and siloes, between siloes, between grains and persistene, between grains and queues etc. that would then allow these sort of things.

**Comment by MV10** [comment]
I don't think addressing is stored as part of persisted internal grain state, is it? If not, I don't see how addressing would be relevant, the encryption I've proposed was only meant to apply to state. An encryption indicator might be something that could be added to the `[StorageProvider]` grain attribute:

```csharp
[StorageProvider(ProviderName = "SecureSQL", EncryptState = true)]
public class Customer : Grain<CustomerFinancials>
{ ... }
```

I was going to say that an exception could be thrown if a serializer is chosen which does not support encryption (e.g. non-binary), probably by checking a new flag on `IExternalSerializer`.

However, I'm guessing the storage provider name isn't matched up to a hosted grain until that grain is activated, which may be rarely or never. It would seem preferable that a storage provider / serializer / state encryption mis-match is recognized at silo startup. I haven't looked at what the builder actually does internally, so I'm not sure if that's a reasonable expectation.

**Comment by veikkoeeva** [comment]
@MV10 Apologies for veering the discussion a bit off-rails. I was thinking more how to fit end-to-end encryption into the system and then which parts it would touch etc.

How to configure that `EncryptState = true` so that is flexible?

As another part, you could perhaps improve https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/SiloBuilderExtensions.cs so it would allow to use any (de)serializer or so that it allows you to insert your own https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/StorageSerializationPicker.cs that can do whatever is needed with the data passing through. This is from 1.n era so not fully exposed and no IoC, but you can see it is used like https://github.com/dotnet/orleans/blob/master/src/AdoNet/Orleans.Persistence.AdoNet/Storage/Provider/AdoNetGrainStorage.cs#L223 just before or after going to the database. So you could use DB encryption, then do something in-memory just after reading etc.
