### ISSUE TITLE
Issues with silo joining and work distribution.

### ISSUE THREAD

**Issue by Telavian** [dotnet/orleans#596]
I simulated a heavy load by loading many grains concurrently. Each grain artificially took 15 seconds and I immediately created 500 of these requests. This seems to work for a single silo however if there is more than a few outstanding requests then a second silo trying to join times out waiting to join the cluster.

It also seems that if the second silo gets in then the work that is still outstanding from the first silo is never load balanced to the second silo. 

http://stackoverflow.com/questions/31358131/work-distribution-in-orleans

**Comment by ReubenBond** [comment]
In your Stack Overflow question, you are using Thread.Sleep(). What happens when you use 'await Task.Delay(...)'?

Orleans is highly tuned for performance and a part of that includes saturating the cores with work by selecting the right number of physical threads and using tasks for concurrency.

-----Original Message-----

**Comment by gabikliot** [comment]
Ok, so I see 2 issues:
1) The new silo fails to join the cluster: **This should never be happening**. Even if the silo is heavily overloaded, like in your example with Thread.Sleep within the grains effectively causing all application grain threads to block, we should still be able to join the silo. Silo operations (system activities within the silo) should not be impacted by any overload the application is creating. Specifically, for this case, we have a separate set of reserved threads for silo activities.
I would like to see the logs for that repro and investigate. Of course bug is possible and I would love to fix it.

2) Load balancing - it depends on how your test is written. If what you do is first send a set of msgs to a predefined set of grains, let it work for a while and then join the 2nd silo and just keep using the same grains, that what you are seeing is expected. We currently do not migrate active activations. That means that if you had 1 silo, all activations were created on this silo and once you join the 2nd silo, they still stay on the 1st silo. This is almost never a problem in real workloads, since it real workloads we see in production, the set of grains is changing dynamically and new grains are placed evenly on both new and old silos, while old activation are gradually GCed. So overall the system is pretty balanced.
In your test, you should add more grains and gradually let old one be inactive.
In addition, you can try marking your grains with `[ActivationCountBasedPlacement]`. It will not cause old activations to migrate, but all new activations will be preferentially placed on the new silo.

We do plan to add migration of active grains in the future, but this has not been a big priority for us, as of now, based on customers feedback.

**Comment by Telavian** [comment]
I changed it to Task.Delay and did see that things improved. Thanks.
