### ISSUE TITLE
Exception deserialization failure

### ISSUE THREAD

**Issue by u-less** [dotnet/orleans#5978]
When the client does not refer to the server's Exception type, Client will fail and timeout error will be raised.I think there should be a general approach.

**Comment by HermesNew** [comment]
This may be a bug, because the Type can't be found, causing a serialization error, causing the exception to handle the infinite loop, and finally thow out of timeoutexception.
I also encountered the same problem. PgSQL throws an exception because Orleans can't find a reference to Npgsql.dll, so Orleans finally throws a timeoutexception.

**Comment by ReubenBond** [comment]
@luohuazhiyu the explanation (other than the infinite loop) which @HermesNew provided is also my strongest suspicion. I agree that there should be a general approach. Do you have any suggestions for how this should be done generally?

**Comment by luohuazhiyu** [comment]
@ReubenBond Grain is similar to the microservice API,Detailed exception information should be handled by the server,The client should have a generic Exception type to throw simple exception information Or handle only unknown types of exceptions.

**Comment by veikkoeeva** [comment]
Can we ensure there is some kind of an identifier the very least that flows from silo to client in order to match exceptions? On one hand one might want to enforce a [trust boundary](https://en.wikipedia.org/wiki/Trust_boundary) on exception propagation here, on another hand it may not always be the case. Also intriguing is [RFC 7807](https://tools.ietf.org/html/rfc7807) or `Either` type of solution that would be easy to assemble, like installing a global exception handler as in ASP.NET Core.

**Comment by HermesNew** [comment]
@ReubenBond IIncomingGrainCallFilter can get specific exceptions, and the client can only wait for a timeout. An infinite loop is my guess because the server won't have any return until it times out.It is easy to reappear, I think it is a serious problem.

**Comment by ReubenBond** [comment]
Good feedback, thank you! I am considering various improvements to the experience here.
One such improvement is #5998

**Comment by ReubenBond** [comment]
The main issue here was fixed in #5998, so at least *some* exception will come back to the original caller very quickly. That exception may be a serialization/deserialization exception but at least it's something which you can identify and use to fix issues quickly.

**Comment by ReubenBond** [comment]
I'm going to shift this to 3.1.0 for now so that we have time to properly design the feature. As mentioned above, the experience will be much better in 3.0 regardless

**Comment by ReubenBond** [comment]
3.5.0 supports exception deserialization with fallback when run on .NET 5.0 (since it will use `ILBasedSerializer` by default, given that `BinaryFormatter` is disabled on .NET 5.0 by default) and 4.0 includes a new serializer which also supports exception deserialization using a fallback type for cases where the deserializer does not have the available exception type.
