### ISSUE TITLE
Configure task scheduler?

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6011]
Hi,

is it possible to configure the task scheduler somehow? 

The problem is that under high load the system can become unresponsive, but some of the tasks would have a higher priority than others, e.g. the health checks have a high priority.

Then the application can be restarted due to unresponsive health checks.

**Comment by veikkoeeva** [comment]
I'll link https://github.com/dotnet/corefx/issues/37755 since the current mechanism is explained well there. I wonder if this would currently technically mean prioritizing tasks across `WorkItemGroup`s? Also would moving to `IThreadPoolWorkItem` make this easier and even further, should one have some way to prioritize amongsts Orleans tasks or even over all system tasks. In the general case it looks like currently one needs to write a custom [TaskScheduler](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler?view=netframework-4.8) (e.g. https://github.com/martin-nikolov/Scheduler.TaskPrioritization/blob/master/Scheduler.TaskPrioritization/Infrastructure/Scheduler/PriorityScheduler.cs).

**Comment by ReubenBond** [comment]
@SebastianStehle do you want to replace the internal TaskScheduler used by individual grains, all grains, or the entire system?

**Comment by SebastianStehle** [comment]
I would like to great groups of grains with different priorities.

**Comment by ReubenBond** [comment]
BTW, if Ping messages are responded to with too-low a priority then the silo will be declared as dead. The argument for having them at higher priority (they're handled inline) is that it's better to run slowly than not at all.

I'm all for providing more options here, I'm looking for your viewpoint/input on what those options should be.

Worth noting #5682 here. Thanks for the links, @veikkoeeva :) The priority scheduler is interesting
