### ISSUE TITLE
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Dependency missing in Orleans 3.0 RC1?

### ISSUE THREAD

**Issue by emilekberg** [dotnet/orleans#6028]
I might be a bit quick to jump the gun, but i wanted to try out orelans-3.0.0-RC1 after it got released. going from 3.0.0-Beta1 broke to me, seems like Microsoft.Bcl.AsyncInterfaces is missing. 
got this error: 
```
Exception has occurred: CLR/System.IO.FileNotFoundException
An exception of type 'System.IO.FileNotFoundException' occurred in Orleans.Runtime.dll but was not handled in user code: 'Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Det går inte att hitta filen.'
   at Orleans.Hosting.DefaultSiloServices.AddDefaultServices(IApplicationPartManager applicationPartManager, IServiceCollection services)
   at Orleans.Hosting.CoreHostingExtensions.<>c.<ConfigureDefaults>b__6_0(HostBuilderContext context, IServiceCollection services)
   at Orleans.Hosting.SiloBuilder.Build(HostBuilderContext context, IServiceCollection serviceCollection)
   at Microsoft.Extensions.Hosting.GenericHostExtensions.<>c__DisplayClass0_0.<UseOrleans>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at TestOrleans.ServiceHost.Program.<Main>d__0.MoveNext() in E:\dev\orleans\TestOrleans.ServiceHost\Program.cs:line 18
```
installing it made it work however. Wanted to drop the info somewhere in case it got missing somewhere. Saw no info in the release notes about this

**Comment by ReubenBond** [comment]
@terrajobst did we make a silly packaging mistake here concerning IAsyncEnumerable? I don't believe we're referencing `Microsoft.Bcl.AsyncInterfaces` explicitly anywhere.

**Comment by terrajobst** [comment]
What platform are you on (.NET Core 2.x or .NET Core 3.0)?

Someone in your transitive closure probably does. Looks like `Microsoft.AspNetCore.Connections.Abstractions` for example does, but only for .NET Standard 2.0.

**Comment by ReubenBond** [comment]
This reproduces when targeting `netcoreapp3.0` and pulling in one for those packages. Orleans itself targets `netstandard2.0` only at the moment.

**Comment by terrajobst** [comment]
Here is the situation:

* `Microsoft.AspNetCore.Connections.Abstractions` pulls in `Microsoft.Bcl.AsyncInterfaces` for .NET Standard 2.0, it doesn't for .NET Standard 2.1.
* It exposes the reference to `Microsoft.Bcl.AsyncInterfaces` by any public type that implements those interfaces (e.g. `IConnectionFactory` extends `IAsyncDisposable`)
* Anybody in your closure that
	1. Is compiled against `Microsoft.AspNetCore.Connections.Abstractions`
	2. Is .NET Standard 2.0
	3. Uses `IAsyncDisposable` or `IAsyncEnumerable<T>` will end up having a reference to `Microsoft.Bcl.AsyncInterfaces`
* However, `Microsoft.AspNetCore.Connections.Abstractions` also provides a custom binary for .NET Strandard 2.1 which doesn't depend on `Microsoft.Bcl.AsyncInterfaces`. Since your apps is targeting .NET Core 3.0, the implicit reference to `Microsoft.Bcl.AsyncInterfaces` gets dropped.

The best fix is to make sure that whoever in your closure only implicitly depends on `Microsoft.Bcl.AsyncInterfaces` should be updated to explicitly depends on `Microsoft.Bcl.AsyncInterfaces`.

The easiest workaround is to add `Microsoft.Bcl.AsyncInterfaces` as a dependency to your console app.

**Comment by ReubenBond** [comment]
Thank you for the explanation @terrajobst. We will add an explicit dependency for each package which also includes `Microsoft.AspNetCore.Connections.Abstractions`

Is this something which ASP.NET Core folks should be made aware of?

**Comment by terrajobst** [comment]
> Is this something which ASP.NET Core folks should be made aware of?

Yes. I've started a mail thread with the right folks (SDK, NuGet, and ASP.NET).

**Comment by emilekberg** [comment]
Sorry should have mentioned versions, but as you already figured out, it was running `netcoreapp3.0` with dotnet core SDK 3.0.100.
Thank you for the quick feedback!

**Comment by amittyyy** [comment]
Simple and short Answer:- 

Make sure your EFCore installed version and EF related Other NuGet packages have same version. 

Like:- EFCore v5.0.0 Preview 3.2.....
Than all packages has same version.
Like:- EFCore.Sql

Hope this will help you,
