### ISSUE TITLE
sending per grain info to storage system when saving

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [dotnet/orleans#6052]
When I was trying to implement a playfab based storage system for grains and also previously when I wanted to make some settings per grain (not per grain type) in a storage provider to save my data in a different manner, the storage system couldn't do that.

Let's say we have a set of player grains.  
Also assume that for saving data for each user in playfab you need the user's ID which the grain has at runtime and it cannot be deduced from grain key, how can we send this info to our storage provider when we initialize the grain/when calling WriteStateAsync so the provider can do its job? 

One easy/dirty way of solving it is to have an object argument for WriteStateAsync and ReadStateAsync but probably it can be done better.

@sergeybykov  @ReubenBond  I saw you were looking for feedback for Orleans 3, probably this is late for that but I hope still is useful

**Comment by jason-bragg** [comment]
If the user's id can't be deduced from grain key, where would that data come from when the grain is being initialized?  The reason grain key is used in storage, is because that's a piece of information that's guaranteed to be there.  Presuming you want the state loaded when the grain activates, it must have some way of getting the users ID.

If the Id is only available after the grain has been activated, then you'd need to have some lazy, or on demand load that can be called when the user id shows up.  This isn't how Orleans grain storage currently works. :/

Two options come to mind.
Option 1) Use the userId as part of the grain Id. - This would allow storage to parse out this info and use it in the provider.
Option 2) Have the main grain call a second storage grain that uses the users Id to read or write the state once the users Id shows up.
