### ISSUE TITLE
No storage provider named "xxx" found loading grain type

### ISSUE THREAD

**Issue by PccCodesix** [dotnet/orleans#6094]
orleans 3.0
I used as the  document say injected IPersistentState<TState> into the grain as constructor parameters,  silo  has been configured with the name "profileStore".
but client throw an exception: No storage provider named "xxx" found loading grain type
inheriting from Grain< TState > This is still supported but is considered legacy. injected IPersistentState< TState > is it the recommended way?
Is there anything wrong here?

```
public class UserGrain : Grain, IUserGrain
{
  private readonly IPersistentState<ProfileState> _profile;
  private readonly IPersistentState<CartState> _cart;

  public UserGrain(
    [PersistentState("profile", "myGrainStorage")] IPersistentState<ProfileState> profile,
    [PersistentState("cart", "cartStorage")] IPersistentState<CartState> cart,
    )
  {
    _profile = profile;
    _cart = cart;
  }
}
```

**Comment by sergeybykov** [comment]
I suspect this is cause by a mistake in the doc page. Instead of "myGrainStorage" it should have "profileStore", to match the provider name down at the Getting Started step. I submitted #6107 to fix that.

I also submitted #6106 to update the HelloWorld sample to better illustrate how to use `IPersistentState<T>`.

**Comment by PccCodesix** [comment]
Thank you for your answer.
Maybe I need your advice
I just want Write a small and simple program,Use the efcore to Implement an Custom StorageProvider to Storage the Custom status. But I had some injection error on injection  dbcontext. i know the dbcontext is not thread safe.what life cycle can inject into Custom StorageProvider? I'm confused about the life cycle of injecting dbcontext  in Custom StorageProvider .
Is there some suggestions to me?or Maybe there's an example useing efcore.

**Comment by sergeybykov** [comment]
If you want to implement an EF Core storage provider, I suggest to look at [MemoryGrainStorage provider](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/Storage/MemoryStorage.cs#L39) as a simple example. It "saves" state in a special set of grains instead of writing to an actual data store.

It has builder extension methods defined in https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/Hosting/MemoryGrainStorageSiloBuilderExtensions.cs#L15.

I'm not sure what dbcontext is and what is the best way to handle it. Maybe other people do, and can advise.

**Comment by PccCodesix** [comment]
thank you for your suggestion.
the dbcontenxt is Database context in EF core.yes maybe someone use it in orleans ,could know what life cycle inject into StorageProvider.

**Comment by sergeybykov** [comment]
Can you elaborate on how you want to use dbcontext? Can't it simply be injected into the DI container?

**Comment by PccCodesix** [comment]
I know how to injected into the DI container,just confused about what life cycle used when read/write grains state.

**Comment by sergeybykov** [comment]
State is loaded automatically during the `GrainLifecycleStage.SetupState` lifecycle phase. Writes are explicitly triggered by grain code.
