### ISSUE TITLE
Transactions & OnActivateAsync

### ISSUE THREAD

**Issue by RamanBut-Husaim** [dotnet/orleans#6115]
Hello colleagues,

As part of the investigation process for Olreans Transactions I've faced the following issue. One of my grains operates with streams. In order to work properly it requires streams to be resumed as part of `OnActivateAsync` as per official docs. All required information to resume on the interested streams sits inside the state of the grain.

However when I've tried to utilize `ITransactionalState` facet as part of `OnActivateAsync` I've faced the following error:

```cs
2019-11-12 20:05:35,439 [9] Error Lifecycle start canceled due to errors at stage 2000: Orleans.Transactions.OrleansTransactionException: A transaction context is required for access. Did you forget a [Transaction] attribute?
   at Orleans.Transactions.TransactionContext.GetRequiredTransactionInfo[T]()
   at Orleans.Transactions.TransactionalState`1.PerformRead[TResult](Func`2 operation)
   at ReviewItEasy.Webhooks.Host.Webhooks.Grains.WebhookGrain.RetrieveEventStreams() in /home/rakkattakka/Development/rie/ReviewItEasy.Webhooks/src/ReviewItEasy.Webhooks.Host/Webhooks/Grains/WebhookGrain.cs:line 138
   at ReviewItEasy.Webhooks.Host.Webhooks.Grains.WebhookGrain.RetrieveSubscriptions() in /home/rakkattakka/Development/rie/ReviewItEasy.Webhooks/src/ReviewItEasy.Webhooks.Host/Webhooks/Grains/WebhookGrain.cs:line 121
   at ReviewItEasy.Webhooks.Host.Webhooks.Grains.WebhookGrain.OnActivateAsync() in /home/rakkattakka/Development/rie/ReviewItEasy.Webhooks/src/ReviewItEasy.Webhooks.Host/Webhooks/Grains/WebhookGrain.cs:line 46
   at Orleans.LifecycleSubject.<OnStart>g__CallOnStart|7_0(Int32 stage, OrderedObserver observer, CancellationToken cancellationToken)
   at Orleans.LifecycleSubject.OnStart(CancellationToken ct)
```
Performed two experiments with no success:
1. Marked `OnActivateAsync` with `[Transaction(TransactionOption.CreateOrJoin)]`;
1. Added a method `OnActivateAsync` to my grain interface and marked it with `[Transaction(TransactionOption.CreateOrJoin)]`;

Both of them failed with the error displayed above. 

I'm wondering whether this is generally not supported or I'm doing something wrong. Could you please advise?

Thanks.

@sergeybykov @ReubenBond  @jason-bragg

**Comment by RamanBut-Husaim** [comment]
@jason-bragg Hello.

Sorry for pinging you with this. Maybe some additional info is required regarding the issue?

Thanks.

**Comment by jason-bragg** [comment]
I apologize for the delayed reply.

Transactions can only operate within a grain call marked as a transaction, so they can't be performed within OnActivateAsync.  If you need subscribe to the stream at activation then I don't see a good way to store the subscription information in a transactional state on the same grain.

If during activation you know the stream Id, you can query any active subscriptions using GetAllSubscriptionHandles() then resume consumption of the stream, but you'd need create the subscription (SubscribeAsync) somewhere else where the full information is available (possibly the transactional call which set's this information?).

An alternative is to store the subscription information in an IPersistentState<> facet, wired up to non-transactional storage.  This would only be possible if you weren't modifying the subscription as part of  a transaction.

Another option is to manage the subscription from elsewhere in the system via IStreamSubscriptionManager and having the grain wire up it's observer by implmenting the IStreamSubscriptionObserver, rather than on activation.

**Comment by RamanBut-Husaim** [comment]
Hello @jason-bragg,

Thanks a lot for the response and sorry for the delay. It seems that my use-case is that I have dynamic streams and the grain should subscribe to them as part of the grain methods (eg. webhooks & event streams). So I fear that the first two options are not suitable for my use-case.

 Regarding `IStreamSubscriptionManager`. Is there any documentation or info available for this feature to understand what is the idea behind it? The quick search does not provide clue except source code.

Maybe you could advise as well what was the underlying difficulty of adding transaction support to `OnActivateAsync`?

Thanks.

**Comment by jason-bragg** [comment]
>I have dynamic streams and the grain should subscribe to them as part of the grain methods (eg. webhooks & event streams). So I fear that the first two options are not suitable for my use-case.

There are two parts that are critical; The creation of the subscription and the attachment of the observer to the subscription.  Both the SubscribeAsync and ResumeAsync attach the observer.  The main difference is that Subscribe creates a new subscription, whereas Resume uses an existing one.  If the grain subscribes during a call it needs not subscribe on activate, because the subscription has already been created, it needs only attach the observer, which can be done via the IStreamSubscriptionObserver hook. See: https://github.com/dotnet/orleans/blob/master/test/Grains/TestGrains/StreamBatchingTestConsumerGrain.cs

Regarding IStreamSubscriptionManager, I'm not aware of any docs for that.  It is a surface introduced so that users could manage subscriptions outside the context of the subscribing grain.  Best we have for that is our test harness.  In general, I'm of the view that our tests are better than most docs I've read, but we should still document this feature.  See: https://github.com/dotnet/orleans/tree/master/test/Tester/StreamingTests/ProgrammaticSubscribeTests for usages of stream subscription manager.

Regarding using transactions during activation, transactions in Orleans are a distributed operation which requires setup prior to the grain call.  The grain call is just the application layer part of the distributed operation.  None of this setup exist at the time of grain activation.

**Comment by RamanBut-Husaim** [comment]
Hello @jason-bragg ,

Thanks for the response. 

> There are two parts that are critical; The creation of the subscription and the attachment of the observer to the subscription. Both the SubscribeAsync and ResumeAsync attach the observer. The main difference is that Subscribe creates a new subscription, whereas Resume uses an existing one.

Yep, this is how I'm doing it as part of my code.

> Regarding IStreamSubscriptionManager, I'm not aware of any docs for that.

Thanks a lot for this. I'll take a look at tests them for inspiration. :)

> None of this setup exist at the time of grain activation.

Ok, understand then. I think it could make sense to update the documentation with such information to avoid the confusion for other people.

@jason-bragg Are you ok if I create a PR with the updated info regarding `OnActivateAsync` case?

**Comment by jason-bragg** [comment]
@RamanBut-Husaim, we're always open to PR's from the community, especially those that deal with bugs or deficiencies in our docs.  That would be great!  Thanks.

**Comment by RamanBut-Husaim** [comment]
Hello @jason-bragg ,
A PR with doc update has been created - https://github.com/dotnet/orleans/pull/6186.

**Comment by RamanBut-Husaim** [comment]
Hey @jason-bragg ,
Closing this as PR has been merged into master.
