### ISSUE TITLE
[Question] Possible integration scenario using Event Hub streaming

### ISSUE THREAD

**Issue by cosmintiru** [dotnet/orleans#6129]
Hello all,

I was able to find a couple of topics around Orleans Streaming + Event Hub, but I haven't been able to find something around the scenario that I've just tried.

I'd like to integrate a couple of applications and I'd like to take advantage of the rewindable streaming support from Orleans+Event Hub. Direct connection between those products is not doable, but the following setup seems to work fine. 

If each application bootstraps their own localhost silo and configure the same Event Hub stream provider, they will be able to pass events between each other, maintain their own cursor, or if I start a new silo and create a new subscriber, it will just ingest everything until it catches up. Fortunately, this is exactly what I need.

Am I missing something? Is this a valid approach? What are the possible issues I can get into (from the Orleans standpoint/Event Hub standpoint)?

**Comment by sergeybykov** [comment]
As I understand, you are looking to connect two Orleans-based applications via EventHub streams. If that's indeed the case, I don't see a problem with your approach. It's the easiest case when events are produced to and consumed from streams by Orleans.

A more elaborate case is when either producer or consumer of event is non-Orleans code. In that case one has to take care of formatting the event data, so that it would be correctly interpreted by both sides.

**Comment by cosmintiru** [comment]
Thank you @sergeybykov , from my point of view this can be closed.
