### ISSUE TITLE
How to Log TestCluster Output to xUnit ITestOutputHelper?

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/orleans#6157]
I'd like to get the logs from the `TestCluster` and forward them to the xUnit `ITestOutputHelper`. How can I achieve this from `TestClusterBuilder`?

In a production app, I'd set the logger on the generic `IHostBuilder` but I don't have access to that level of setup with the `TestCluster`.

```c#
public class ClusterFixture : IDisposable
{
    public ClusterFixture(ITestOutputHelper testOutputHelper)
    {
        // How can I use testOutputHelper to log output from Orleans????

        this.Cluster = this.CreateTestCluster();
        this.Cluster.Deploy();
    }

    public TestCluster Cluster { get; }

    public TestCluster CreateTestCluster() =>
        new TestClusterBuilder()
            .AddClientBuilderConfigurator<TestClientBuilderConfigurator>()
            .AddSiloBuilderConfigurator<TestSiloBuilderConfigurator>()
            .Build();

    public void Dispose() => this.Cluster.Dispose();
}
```

**Comment by ReubenBond** [comment]
As far as I know, this is not something which you can easily accomplish. It's an issue of the lifetime of a given test and the silos/clients which run as a part of the test (silos often start earlier and live longer). Typically, we reuse a single test cluster for many tests, so that lifetime issue is especially apparent.

You can try creating an `ILoggerFactory` adaptor for `ITestOutputHelper`, but I think you'll run into the mentioned lifetime issue, unless you create and destroy the cluster during each test case.

I've found it is sufficient to log to txt files and use that for debugging tests.

**Comment by RehanSaeed** [comment]
I guess what I'm asking is, are there any plans to re-platform the test cluster on the generic host? I want to be able to call `UseSerilog` on `IHostBuilder` instead of manually configuring it on ISiloHostBuilder.

As an aside, with my ASP.NET Core integration tests, I fire up a new web app for each test ([so I can run integration tests while also mocking services using Moq](https://rehansaeed.com/asp-net-core-integration-testing-mocking-using-moq/)) and performance is pretty good with tests running in parallel for less than a second each but with Orleans I am seeing each test take about 6 seconds to run. Is there some way to reduce that?

**Comment by ReubenBond** [comment]
You can call UseSerilog either way, by calling `.ConfigureLogging(l => l.UseSerilog())`.

We should replatform onto the generic host. I don't have immediate plans to do that work, but it would be welcome

**Comment by RehanSaeed** [comment]
I've figured out [how to do it](https://github.com/Dotnet-Boxed/Templates/commit/8d18064b2715daf7ca94de3f71b3c699d0c9f6f1)! Going to add that to the Dotnet Boxed Orleans template.

Will keep an eye out for generic host. Thank you.
