### ISSUE TITLE
Feature request: Support inheriting from collections.

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#6158]
I have a few classes that inherit from collections, e.g.

```class LocalizedText : Dictionary<string, string>```

The reason is mainly to give the classes more meaning. But the serializer cannot handle these cases and passes over empty collections.

**Comment by ReubenBond** [comment]
@SebastianStehle I understand the desire. These inherited types were never handled correctly by code generation / serialization and when "ref-only assemblies" came along, everything fell apart (because the types have no implementation/fields/properties during build time, only at execution time).

It is possible for us to implement some support for this by recognizing certain well-known types and behaving accordingly, although it's rather complex unless we put some kind of restriction on the user. Eg, you must implement a certain constructor signature which matches one of `Dictionary<K, V>`'s constructors. Part of the complexity is that the serializer has to serialize not just the data in the collections but also the behavior. In particular, the comparers need to be serialized, and they cannot be set after construction without some runtime hackery.

An alternative approach would be to implement the `IDictionary<K, V>` interface instead of inheriting from the class.

What do you think, should we try to proceed and implement some kind of support for this, perhaps with some agreed upon contract for classes inheriting from a collection base class or perhaps with runtime hackery (IL Emit/reflection) instead?

**Comment by SebastianStehle** [comment]
If we talk about priorities it would not close to the top items at all. 

You can also think about what a collection is. For example a list could be anything that implements `IEnumerable` and has an `Add` or `Push` method. This does not cover behavior that is injected such as the comparer but I guess there is the same problems with Dictionaries today as well.

**Comment by ReubenBond** [comment]
xref: https://github.com/dotnet/orleans/issues/5029

Note that this issue also occurs with `Tuple` types (I never knew people made classes which inherit from `Tuple<T>`)

**Comment by ReubenBond** [comment]
Implemented in 4.0.0-preview1
