### ISSUE TITLE
[Question] Best way to get data by "friend list"

### ISSUE THREAD

**Issue by vyshkant** [dotnet/orleans#6180]
Hi!

I have long been worried about the question: how do Orleans developers propose to receive the following kind of information from Silo.

Suppose we have a `UserGrain` that stores a list of "friends" (or other entities). In what way should I get data about "friends" of the user? Suppose I need username, level an few more fields.

The naive way is that I simply call the corresponding UserGrains in the cycle:

```
public Task<FriendInfo[]> GetFriends()
{
    var friendInfoCollection = new List<FriendInfo>();

    foreach(var friendId in State.FriendIds)
    {
        var friendInfo = await GrainFactory.GetGrain<UserGrain>().GetFriendInfo();

        friendInfoCollection.Add(friendInfo);
    }

    return friendInfoCollection;
}
```

Suppose the user has 500 friends.

In this case I'll awake 500 `UserGrain`s, which will result in 500 read operations on the DB (reading state of each grain), although outside the MS Orleans paradigm it might be a single read operation (just some kind of "select * from Users where UserId in (...)").

Do Orleans developers see this as a problem? Are there any best practices for such cases?

**Comment by vyshkant** [comment]
Perhaps the solution could be the `IGrainFactory` method, such as
```
TGrainInterface[] GetGrains <TGrainInterface> (long primaryKey, string keyExtension);
```
?

And when we call this method, the grains will going to be activated in some special way, which involves just one DB read operation?

**Comment by sergeybykov** [comment]
Orleans doesn't provide a built-in way to do what you described. It wouldn't be easy to activate a number of grains with a single DB read because these grains would get activated on different  silos and asynchronously.

The typical approach is to cache state of friends within the user grain state. That does allow to load it with a single read. However, the challenge now is how to update that cached state consistently with changes to friends states. Depending on the application requirements, it might be okay to return stale cached data for a period of time.

**Comment by vyshkant** [comment]
Thanks @sergeybykov. The way to cache everything does not sound good :(

What do you think, is it possible to reduce read operations count to the "just one" but to the "number of silos"?

**Comment by sergeybykov** [comment]
I don't believe there's a way to get a free lunch here. If we have 500 distributed entities that can be updated independently, one would have to either query the underlying data store directly, hence bypassing the grains, or hold a cached snapshot of their state in memory, hence potentially stale, or perform 500 reads. Am I missing something?
