### ISSUE TITLE
Add MySqlConnector AdoNet Provider

### ISSUE THREAD

**Issue by TsengSR** [dotnet/orleans#6230]
Would it be possible for the next release to add the [MySQLConnector](https://github.com/mysql-net/MySqlConnector) ADO.NET Driver support to Orleans? 

MySQLConnector Provider is a drop in replacement for Oracle's MySQL Provider, but provides true async support (rather than the "sync over async" that Oracle's MySQL Provider implements). 

While the namespaces are unchanged to `MySql.Data.MySqlClient`, using `InvariantNameMySql` is not working, because the provider is [hard-coded](https://github.com/dotnet/orleans/blob/dad62cc16d4d6de671563f6b1e54196f617926a5/src/AdoNet/Shared/Storage/DbConnectionFactory.cs#L30) to look for `MySql.Data` assembly, but MySqlConnector assembly is called `MySqlConnector` and hence can't be accessed when using the `AdoNetInvariants.InvariantNameMySql`.

Due to true lack of async support, Oracle's MySQL Provider is 6 times slower than similarly setup MSSQL Provider (a load test on MSSQL Server does run in 22 Seconds where Oracle's MySQL Provider takes 5 minutes and 30 seconds)

**Comment by sergeybykov** [comment]
Tagging @veikkoeeva.

**Comment by veikkoeeva** [comment]
@TsengSR Yes it would and maybe should for the reasons you note. Depending on how much you have time (or maybe I should?) the quickest option is to change the hardcoded path and then have the change announced in release notes and tell about it to people when something breaks and they come to ask.

The "right way" would be to refactor support to [https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbproviderfactories?view=netframework-4.8](DbProvideFactories) now that it is back in .NET Core and Orleans is on newer .NET Core also. This is how it worked before.

Going a bit further, and/or alternatively, expand the configuration surface so that one can supply a lambda function and one case being to load the connector library as needed and can set a few attributes (some set by default as currently). The default attributes is the ones like asynchronity you note, look at https://github.com/dotnet/orleans/blob/master/src/AdoNet/Shared/Storage/RelationalStorage.cs#L274 (the other one is streaming). It appears that besides this particular MySql issue, connector libraries may have version specific bugs also.

@TsengSR Do you have time and inclination to at minimum change the hardcoded library or refator even more?

@sergeybykov If just switching the hardcoded library, would it be OK to have this "small breakage"?

I would be willing to address this, but I'm preparing to some business events and travelling and can get back to this sometime on the first week of February.

**Comment by veikkoeeva** [comment]
Sorry to bother everyone again, looking quickly some pointers to someone that it looks like https://weblog.west-wind.com/posts/2017/nov/27/working-around-the-lack-of-dynamic-dbproviderfactory-loading-in-net-cor. One idea I got from there could be to just list known providers in preference order so that when one isn't found, another one is tried. Even if this would be refactored so that that there is a possibility to give the connector library via an explicit configuration or using the configuration section (there are tens of providers out there).

**Comment by veikkoeeva** [comment]
A quick note here that I'm onto this, either doing it like in the closed PR or as in the SQL Server case. Have to scrutinize how the invariant is used (likely dependent on the namespace).

**Comment by veikkoeeva** [comment]
@TsengSR See at https://github.com/dotnet/orleans/issues/6230. This is pending a bit but if you are in a good sport, you can take the branch and see if you can use the open source MySQL client.
