### ISSUE TITLE
Best practices for single process applications.

### ISSUE THREAD

**Issue by BernhardGlueck** [dotnet/orleans#6249]
Hi !

I am writing an application that includes both then ASP.NET Core web stack and a Grain Silo in one application/process... 

What is the best approach here, do i still need to create a GrainClient or can i somehow access a GrainFactory directly from my web controller code ? (It seems a bit redundant to have to do a loopback network interaction for this otherwise ) ..

**Comment by ReubenBond** [comment]
I think you want this sample: https://github.com/dotnet/orleans/tree/master/Samples/3.0/AspNetCoreCohosting

That sample splits things out into multiple projects, but you can merge them all into one if you prefer that.

Calls made within the local process *do not* use networking or serialization, not even on the loopback interface.

However, currently your silo needs to bind to an address regardless of how many silos you end up deploying. In the future, we will allow that networking to be essentially removed (no-op) or replaced with an in-process pipe so that you don't need a TCP socket.

**Comment by BernhardGlueck** [comment]
Thanks ! 

As far as i can see the sample uses no Client, just takes a dependency on IGrainFactory directly. That works perfectly for me ..

**Comment by ReubenBond** [comment]
Yes, you can also inject `IClusterClient` in that sample if there's something on it which your controller code needs (eg, streams) - but either way it's the same mechanism under the hood. Direct calls, no networking or serialization unless a message needs to leave the process.

**Comment by ReubenBond** [comment]
If you feel the question is answered, please feel free to close the issue - otherwise we can keep discussing
