### ISSUE TITLE
RequestContext empty in incoming grain call filter, when called by framework stream handshake

### ISSUE THREAD

**Issue by rvplauborg** [dotnet/orleans#6256]
Hi,

In our system we are introducing a Grain Call Filter to verify that the `RequestContext` contains an expected value on all grain calls if certain other requirements are met. This works for all intents, other than when receiving events. 
The `RequestContext` does not contain the value on the receiving side when intercepting an incoming call on the interface method `GetSequenceToken`, which seems to be related to stream handshake from what I can see in the debugger. 
We then fail to validate that the `RequestContext` contains the expected value and throw an exception.
It seems to work if I in the filter specifically ignore invokes where ` context.InterfaceMethod.Name -== "GetSequenceToken"`. So it seems when that method is called, it is not the same RequestContext?

Is there something we can do to get around this?

Best regards

**Comment by jason-bragg** [comment]
That's correct.  In streaming, the context is set per event batch, assuming the batch has a context in it.  The handshake does not have a batch yet, so it has no context.  This is expected behavior.

**Comment by rvplauborg** [comment]
Thanks for the reply. But that narrows down what filters can be used for unless we hardcode it to ignore the handshake calls. Is it planned that the context is included in the handshake at some point, so one can count on the RequestContext to survive streaming fully?

**Comment by rvplauborg** [comment]
Or if not, is there any recommended ways to get around it other than checking for specific handshake methods?

**Comment by jason-bragg** [comment]
It's unclear what "so one can count on the RequestContext to survive streaming fully" means in this case.  The handshake is part of stream offset negotiation, so it doesn't really have a RequestContext, at least no caller generated context.  What RequestContext would you expect to see in this case?

We currently have no plans to change this behavior, in part because it's not clear what RequestContext should be used, or what utility it would provide.  If you can clarify the expected behavior, we'd consider adding a context.

If the goal is to develop a general filter for application calls, without hard coding for unknown calls which may be injected by infrastructure (like the handshake calls which are injected into the grain via a grain extension) I'd suggest using reflection to only hook calls in the grain's interface.  Since reflection is heavy, this call sight map can be cached by grain type.  This would allow the filter logic to only be performed on the application code.  It may be simpler an faster to ignore all calls for grain extensions, assuming that the application isn't using grain extensions, but I've not looked into how hard this is.

**Comment by rvplauborg** [comment]
Ah, I see your point, so the handshake is not initiated by a call from where the RequestContext was set before firing an event - which makes sense I suppose. In that case, I do not have a good guess on how the RequestContext could be used.

Yes, the goal is to intercept all interface methods for a given grain type - so we are actually not interested in intercepting framework calls or grain extension methods.

For now, we work around it by simply ignoring incoming calls with an empty value for our given key in the RequestContext - since we have an outgoing filter on the silo that sets the given value in the RequestContext, we know that it will only be empty on calls from i.e. framework like handshake or other calls.

If at some later point we decide this assumption is not enough, we will look into using reflection as you suggest. 
Thank you for the answers!
