### ISSUE TITLE
Common way to obtain grain factory

### ISSUE THREAD

**Issue by yevhen** [dotnet/orleans#626]
As of 1.0.9 `IGrainFactory` interface was introduced as way to obtain grain references in common way. Unfortunately, obtaining `IGrainFactory` itself is not uniform between client (outside-silo) and cluster (inside-silo) environments. That breaks code which deals with obtaining grain references in a generic way (think shared utils), since getting a reference to `IGrainFactory` inside silo is only possible from inside of a grain and that utility code in question, doesn't have any traces to a grain.

Please consider adding the following static property to `GrainFactory` class which will return default implementation of `IGrainFactory`:

```cs
GrainFactory.Current.GetGrain<IA>(id)
```
When invoked inside client environment it will use the `IGrainFactory` from `GrainClient`, and when invoked inside cluster it will return the reference to `IGrainFactory` singleton, which it returns via `Grain.GrainFactory` by default.

NOTE: that doesn't require any changes to current design. Grains will still have a way to mock out `IGrainFactory` by mocking `IGrainRuntime`. The static `GrainFactory.Current` property will be readonly and not mockable (and it should not, by design). That should satisfy all use cases.

**Comment by nehmebilal** [comment]
While this **doesn't** break the unit testing story as you noted, it can easily trick people into thinking that `GrainFactory` cannot be injected into a `Grain` because all they see is a static call. In other words, the level of indirection that the user must understand to figure out that the `IGrainFactory` can be replaced with a test double is not obvious.

Why not use a non-static class for utility that takes an `IGrainFactory` in its constructor? That would preferable from DI and testability perspective.

**Comment by yevhen** [comment]
> Why not use a non-static class for utility that takes an IGrainFactory in its constructor? 

Unfortunately, it's not possible. It's by design. There is no way to fix this. The class in question is [this](https://github.com/yevhen/Orleankka/blob/master/Source/Orleankka/Core/ActorEndpointFactory.cs) one.

> hat would preferable from DI and testability perspective. 

I'm not interested in unit testing of this utility class. It's actually quite opposite - I need to test it with a real stuff.

> While this doesn't break the unit testing story as you noted, it can easily trick people into thinking that GrainFactory cannot be injected into a Grain because all they see is a static call. In other words, the level of indirection that the user must understand to figure out that the IGrainFactory can be replaced with a test double is not obvious.

I don't buy this argument. If they know what unit testing is (since they want to unit test their stuff) - they will figure out. No need to bike shedding here, me think :smile:

**Comment by nehmebilal** [comment]
> Unfortunately, it's not possible. It's by design. There is no way to fix this. The class in question is this one.

I don't see why not? What prevent `ActorEndpointFactory` to be non-static? other than convenience? :smile_cat: That looks like global state to me.

> If they know what unit testing is (since they want to unit test their stuff) - they will figure out.

Well, that hearts code readability and as a result, Orleans users experience. As a developer, I really don't need to know that `GrainFactory.Current.GetGrain<IA>(id)` is forwarding the call to `IGrainFactory` passed in the grain constructor to be able to write a unit test. It is even confusing to describe :stuck_out_tongue:

**Comment by yevhen** [comment]
> I don't see why not? What prevent ActorEndpointFactory to be non-static? other than convenience?

Believe me, it's not possible.

> Well, that hearts code readability and as a result, Orleans users experience. As a developer, I really don't need to know that GrainFactory.Current.GetGrain<IA>(id) is forwarding the call to IGrainFactory passed in the grain constructor to be able to write a unit test. It is even confusing to describe

Damn, we are on different planets. Is my English is so bad? :smile:

I don't understand your concerns. As a developer, you're supposed to use DI and mocking of IGrainRuntime provided to you via [ctor](https://github.com/dotnet/orleans/blob/master/src/Orleans/Core/Grain.cs#L85) on Grain class. This has nothing to do with GrainFactory class, which is a default implementation of iGrainFactory and its `Current` read-only property, which will merely return the current ambient singleton of IGrainFactory (the runtime singleton created [here](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Silo/Silo.cs#L211) or [here](https://github.com/dotnet/orleans/blob/master/src/Orleans/Core/GrainClient.cs#L229)). 

Tell me how is this different from `GrainClient.GrainFactory`? How can I mock this?

**Comment by nehmebilal** [comment]
> Damn, we are on different planets. Is my English is so bad? :smile:

Your writing looks great, maybe it's your reading? :smile: 

It's different. `GrainClient.GrainFactory` is not accessible from within a `Grain` where `GrainFactory.Current` would. In addition, there are plan of making `GrainClient` non-static (#467). 

My concern is with people using `GrainFactory.Current` inside a `Grain` implementation which will make the Grain code not obviously testable.

Looking at the following code, I know right away that it is testable because `GrainFactory` is an attribute of the class under test and can be replaced with a test double.

```csharp
public class MyGrain : Grain, IMyGrain
{
	public Task DoSomething()
	{
		GrainFactory.GetGrain<IOtherGrain>.DoSomething();	
	}
}
```

But looking at the following code and seeing that `GrainFactory.Current` is a static attribute of `GrainFactory` would make anyone without deep knowledge of how things are wired in Orleans think that `GrainFactory.Current` cannot be easily replaced with a test double.

```csharp
public class MyGrain : Grain, IMyGrain
{
	public Task DoSomething()
	{
		GrainFactory.Current.GetGrain<IOtherGrain>.DoSomething();	
	}
}
```

In addition, this works against having a **minimal** and **consistent** Api since there will be two ways of getting a proxy to a `Grain` implementation.

So unless you can make it `internal` or make sure somehow that it doesn't get used in `Grain` implementations, it doesn't sound like a good addition.

**Comment by sergeybykov** [comment]
@yevhen Why do you have to use one `ActorEndpointDynamicFactory` across grains and clients? Can't you simply have two flavors of it, one for grains and one for clients, and inject GrainFactory accordingly?

**Comment by nehmebilal** [comment]
One other fact to keep in mind is that if we get to the point where `GrainClient` is non-static and we can connect to multiple silos from the same client (#467), there will be multiple `GrainFactory`'s, one for each silo and there simply won't be a *current* factory.

**Comment by sergeybykov** [comment]
Yes, we are getting close to making GrainClient non-static, which people have been asking for for quite some time.

**Comment by yevhen** [comment]
Well, at the moment, it's easier for me to do just this: 

```cs
static IGrainFactory GrainFactory()
{
    return (IGrainFactory) Activator.CreateInstance(typeof(GrainFactory), nonPublic: true);
}
```

... and save the time for something more important :smile: 

Thanks for help!

**Comment by sergeybykov** [comment]
Funny enough, I'm reusing your hack for now in one place in the guts of Halo code. :-)

**Comment by yevhen** [comment]
Well, I can continue arguing with you and @nehmebilal that you have some weird understanding of DI and thus making a mistake of not providing an easy way to access `IGrainFactory` but I chosen to not. Time (and people having issues with current design) will make that job better ;)

**Comment by sergeybykov** [comment]
I discovered an obscure code path where it's not possible to pass a factory. That code will be refactored, and the issue will resolve itself. So it's just a temporary hack I put there for now for expedience. :-)

**Comment by nehmebilal** [comment]
> @yevhen Well, I can continue arguing with you and @nehmebilal that you have some weird understanding of DI and thus making a mistake of not providing an easy way to access IGrainFactory but I chosen to not.

:smile:  really? 
What would you do when the client is connecting to more than one silo? (there are more than one GrainFactory). What you suggested adds a limitation on Orleans: **no more than one GrainFactory/Silo at a time**. The **static global state** approach is simply a bad practice and should not be used.

> @sergeybykov I discovered an obscure code path where it's not possible to pass a factory. That code will be refactored, and the issue will resolve itself.

Yes! not being able to pass the factory is a smell that the code should be refactored. And a DI container would help a lot with the wiring :smiley: but wiring manually is totally possible.

**Comment by sergeybykov** [comment]
:-)

**Comment by yevhen** [comment]
Oh, ye! Making funny of me is always fun! I like it. Now, my turn ... :8ball: 

- What you will do with `Grain.GrainFactory` property? What factory it will be returning?
- What you will do with `IGrainRuntime` ctor? What factory will be returned by its `GrainFactory` property?

Funny, right?  :smile:

**Comment by veikkoeeva** [comment]
@nehmebilal This factory and DI container interests me. I'm catching up and maybe this knowledge is trivially available, or this can be a use case scenario too, or a request for some documentation (it's all right if everyone's busy, I'll dig into the code in that case)... Is it possible currently to do so that I use Orleans test silo to have the turn based semantics but instead of instantiating grains A1 and B1, as in production, I'd instantiate A1 and B2 in this testing? Or perhaps put otherwise, where can I tell what is the concrete type for some grain interface?

**Comment by sergeybykov** [comment]
@veikkoeeva There is to much for such flexibility at the moment. Each silo builds a map of grain interfaces to implementation classes, and client gets it from a gateway upon initialization. You can get what you need by explicitly specifying a full name or a unique prefix of B1 or B2 classes in the `GetGrain()` overloads. By making a run time decision which string to pass based on configuration or something you can get a kind of a poor man's DI for grain classes.

**Comment by nehmebilal** [comment]
> @yevhen What you will do with Grain.GrainFactory property? What factory it will be returning?
What you will do with IGrainRuntime ctor? What factory will be returned by its GrainFactory property?
Funny, right?  :smile:

Very :smile: 

It's simple:
```csharp
GrainClient haloGrainClient = new GrainClient("HaloGrainClientConfiguration.xml");
IGrainFactory haloFactory = haloGrainClient.GrainFactory;
haloFactory.GetGrain<IHumorist>("Sergey").MakeFunOf("Yevhen");

GrainClient pingPongClient = new GrainClient("PingPongGrainClientConfiguration.xml");
IGrainFactory pingPongFactory = pingPongClient.GrainFactory;
haloFactory.GetGrain<IPlayer>("Yevhen").Ping();
```

`HaloRuntime` and `PingPongRuntime` live in two completely different processes/VMs/Clouds and they have nothing to do with each other (so `IGrainRuntime` has no issues here).

**Comment by nehmebilal** [comment]
@veikkoeeva I would suggest doing some reading on a DI container and trying on (I am currently using unity). Otherwise, it's hard to answer your question. But swapping your implementation during testing is certainly on of the things that DI containers do very well and seamlessly.

**Comment by yevhen** [comment]
@nehmebilal not so fast! You just didn't get it.

```cs
class GrainLivingInHaloCluster : Grain
{
    public Task YevhenStrikesBack()
    {
        var uncomprehending = this.GrainFactory.GetGrain<GrainLivingInPongCluster>("Nehme");
        uncomprehending.MakeFunTogetherWith("sergey");
    }
}
```
Now, to what factory `this.GrainFactory` is pointing to? :grin:

**Comment by sergeybykov** [comment]
From within a grain `this.GrainFactory` points to the factory representing the same cluster, unless injected in test scenarios. Am I missing something here?

**Comment by nehmebilal** [comment]
:smile_cat: No one ever said anything about two Grain clusters talking to each other (but that's certainly achievable if the `GrainLivingInHaloCluster` creates a `GrainClient` to connect to pong cluster and uses it to get the appropriate factory; which can all be done inside `OnActivateAsync`).

However, for now, the goal is to allow one non-Orleans client (e.g. web api) to connect to two Orleans clusters.

**Comment by sergeybykov** [comment]
Cross-cluster communication is part of the geo-distribution project we are collaborating on this summer with MSR. We'll start putting out documentation and code in a few weeks as the PhD interns that have been working on the project approach the end of their internships. A lot of great stuff there.

**Comment by yevhen** [comment]
Well, I did an example as a follow up to your comment about additional confusion that global `GrainFactory.Current` will bring. To me, once you implement ability to have multiple grain factories - it will be even more confusion than what I've asked for.

**Comment by yevhen** [comment]
I think we can close this one. Closing ...

**Comment by veikkoeeva** [comment]
@nehmebilal I'll rephrase a bit: Is there documentation on registering an object graph and then using it? For what @sergeybykov wrote, I gather it's a simple interfaces to grains mapping currently. A more concrete question is what if I want to either define a mapping *IB -> B1* or *IB -> B2* depending on environment (e.g. production/UAT/QA/DIT/dev)?  Are you using Unity in conjunction with Orleans DI? If so, can you share a bit code (I'm familiar with Unity)?

With regard to use cases, mine is similar to: For example ASP.NET MVC/WebAPI (with or without OWIN) project, I could register depending on the environment either *B1* or *B2* to be resolved when *IB* is requested (or in fact, even by some variable) when the runtime creates object (e.g. controllers).

I understand this is still shaping, taking form, and we are busy people and maybe this thread got a bit poignant. This DI seem to something everyone has an opinion, so maybe we should build a mechanism for everyone to just plug in their favourite container (:wink:). I tried to fish a bit if there are good pointers with a bit poor phrasing. I think I need to dig in the code (tests?), mull this thing and ask if I get stuck into something more concrete. As you perhaps can guess, I have read about and used various containers all the way since Spring.NET became into existence.

@sergeybykov Hmm, I think you answered my question. I haven't had need for these prefix things. Will look into those.

**Comment by yevhen** [comment]
@sergeybykov 

> From within a grain this.GrainFactory points to the factory representing the same cluster, unless injected in test scenarios. Am I missing something here?

Hehe, isn't it the same as `GrainFactory.Current`?

**Comment by nehmebilal** [comment]
> @sergeybykov

From within a grain this.GrainFactory points to the factory representing the same cluster, unless injected in test scenarios. Am I missing something here?

> @yevhen Hehe, isn't it the same as GrainFactory.Current?

It isn't in the following scenarios:
* In the same process, I start a cluster and I connect to another cluster.
* Cluster to cluster communication (two GrainFactory's there).
* Unit testing.
* Other kinda of testing.
* Many other reasons why you should not use static and global state.

**Comment by nehmebilal** [comment]
I personally haven't used a DI container to create grains yet but only to inject the IGrainFactory. However, you can certainly do so and it might be very useful in some scenarios.

Here is an example with Unity. Simply register a different set of grains depending on your environment as follows.

```csharp
public static class DIUtils
{
	public static void RegisterTypes(IUnityContainer container)
	{
		RegisterGrainFactory(container);
		container.RegisterType<MyClassThatUsesOrleans>();
		if (Environment.IsProduction())
		{
			RegisterProdGrains(container);
		} else 
		{
			RegisterDevGrains(container);
		}
	}

	private static void RegisterGrainFactory(IUnityContainer container)
	{
		container.RegisterType<IGrainFactory>(new ContainerControlledLifetimeManager(), new InjectionFactory(
			c =>
			{
				GrainClient.Initialize("OrleansClientConfiguration.xml");
				return GrainClient.GrainFactory;
			}));			
	}
	
	private static void RegisterProdGrains(IUnityContainer container)
	{
		container.RegisterType<IHelloGrain>(new ContainerControlledLifetimeManager(), new InjectionFactory(
			c =>
			{
				IGrainFactory grainFactory = c.Resolve<IGrainFactory>();
				return grainFactory.GetGrain<IHelloGrain>("A");
			}));	
	}

	private static void RegisterDevGrains(IUnityContainer container)
	{
		container.RegisterType<IHelloGrain>(new ContainerControlledLifetimeManager(), new InjectionFactory(
			c =>
			{
				IGrainFactory grainFactory = c.Resolve<IGrainFactory>();
				return grainFactory.GetGrain<IHelloGrain>("B");
			}));	
	}
}


public class MyClassThatUsesOrleans
{
	public MyClassThatUsesOrleans(IHelloGrain helloGrain)
	{
		// do something with helloGrain
	}
}
	
public static void Main()
{
	IUnityContainer unityContainer = new UnityContainer();
	DIUtils.RegisterTypes(container);

	// the DI container will take care of instantiating dependencies in order and wiring.
	MyClassThatUsesOrleans myObject = container.Resolve<MyClassThatUsesOrleans>();
}
```

I hope that helps.
