### ISSUE TITLE
Fire&Forget SMS stream interleaving

### ISSUE THREAD

**Issue by OndrejKraus** [dotnet/orleans#6277]
As I have learned there should be no interleaving of stream deliveries inside a single grain, at least a non-reentrant one. According to my tests it seems that current stable Orleans version prevents interleaving only for grain calls.

Orleans 3.0.2
.NET Core SDK 3.1.101
platform win10-x64

Here is a testing project:

https://github.com/OndrejKraus/OrleansTests/tree/master/StreamInterleavingTest

There is one Master grain and two Slave grains. Master creates 2 streams, Cmd and Ack and sends a command to Cmd stream. All grains (including Master) listen to Cmd stream. Slaves react to comand with acknowledgement to Ack stream.

Master also listens to Ack stream. According to this scenario Master should receive three messages and it does. But if we add arbitrary awaited delay to observer method, these deliveries start to interleave. Test fails with interleaving factor of 3, where should be a factor of 1. Test generates this (partial) output:

```
...
Master: Proceed
Master: > OnCmd
Master: ProcessMember:1 delaying
Master: > OnAck
Master: ProcessMember:2 delaying
Master: > OnAck
Master: ProcessMember:3 delaying
Master: ProcessMember:1 seen:1
Master: < OnCmd
Master: ProcessMember:2 seen:2
Master: < OnAck
Master: ProcessMember:3 seen:3
Master: < OnAck
```

While this is expected:

```
...
Master: Proceed
Master: > OnCmd
Master: ProcessMember:1 delaying
Master: ProcessMember:1 seen:1
Master: < OnCmd
Master: > OnAck
Master: ProcessMember:1 delaying
Master: ProcessMember:1 seen:2
Master: < OnAck
Master: > OnAck
Master: ProcessMember:1 delaying
Master: ProcessMember:1 seen:3
Master: < OnAck
```

I catch output from tests with static ITestOutputHelper. It is a dirty hack and I would assume that there can be problems with default two silos configuration. But surprisingly it does work for me with no issues.

**Comment by sergeybykov** [comment]
This is an artifact of two factors:
1) SMS isn't a queue-based stream provider. With it, events are delivered to subscribers as immediate direct grain calls.
2) By default, call chain reentrancy is enable. This allows the call chain of the producer grain to reenter into it.

If you add 
```c#
.Configure<SchedulingOptions>(options => options.AllowCallChainReentrancy = false)
```
to the host builder code, you'll start seeing timeouts instead of reentrancy.

**Comment by OndrejKraus** [comment]
I am not sure, that we are on the same page. I thought that standard SMS works in this way. We use it regularly and it is a very nice mechanism. 

But in this case we talk about fire&forget and I was under the impression that this works in a similar way as other streams. If it is not the case, it represents a little complication. We can of course move to some external stream, just it is only additional layer, which does not bring any benefit to our system. But more importantly, it makes all stream tests much more complicated as we would have to bring up some external infrastructure to do the tests.

**Comment by sergeybykov** [comment]
>But in this case we talk about fire&forget and I was under the impression that this works in a similar way as other streams.

SMS doesn't work the same way as other providers. It doesn't truly decouple producers from consumers.

It would help to understand what your goals are. The use of SMS in the test project creates call cycles. Those calls reenter for the reasons above. Or the grain class can be explicitly marked as `[Reentrant]`.

If you don't want reentrancy, you have two options: eliminate the call cycles or use a different stream provider that would decouple producers from consumers for real.

**Comment by OndrejKraus** [comment]
Ok, I think that I understand:

``` cs
if (fireAndForgetDelivery) task.Ignore();
```

Basically we are looking for two things:

- The ability to unit test queue-based stream functionality without the need to erect some external infrastructure.
- Queue-based internal provider for production use. We do not need high reliability, we need speed. And therefore I am trying to avoid additional layer of external broker.

To be more precise, in my example:

- Cmd stream should be reliable with retries
- Ack stream can be a little bit unreliable, i.e. there is no need for delivery retries

I hoped that we would be able to use fire&forget SMS, it seemed to be an ideal candidate. But it looks like that without locking SMS is safe only for one-way direction.

**Comment by sergeybykov** [comment]
>The ability to unit test queue-based stream functionality without the need to erect some external infrastructure.

You might be able to use the in-memory queue provider for that. Tagging @jason-bragg for more information on it.

>Queue-based internal provider for production use. We do not need high reliability, we need speed. And therefore I am trying to avoid additional layer of external broker.

If you are okay with losing some events in case of a node failure, then in-memory queue provider might work here, too.

>Cmd stream should be reliable with retries

Does this mean that the producer needs to know if an event wasn't delivered, so that it would retry? If that's the case, then FireAndForget won't work here, will it?

>I hoped that we would be able to use fire&forget SMS, it seemed to be an ideal candidate. But it looks like that without locking SMS is safe only for one-way direction.

If you explicitly enable reentracy, then I think it should just work, one direction or both.

**Comment by jason-bragg** [comment]
Memory streams (AddMemoryStreams<T>(...)) use the persistent stream infrastructure, as if the events were being kept in an external persistent queue, but instead store the events in in-memory queue grains.  This allows it to mimic much of the behaviors of a persistent queue (like decoupled production and consumption, and ordered recovery) without the need for an external queuing system, at the cost of reliability should any of the in memory queues be lost.

This stream implementation was initially developed to allow developers using persistent streams to locally tests stream processing logic without the need to configure an external queue, but since its introduction it's replaced some usages of SMS as it fits some scenarios better.  This is not a recommendation, as persistent streams and their configuration can be far more complex than SMS.

As for your scenario, using persistent streams (as opposed to SMS), production and consumption of events are decoupled.  When an OnNextAsync task resolves on the producer side, this means only that the event has been queued for processing.  Independently events are pulled from the queue and the OnNextAsync of the consumer is called.  What you should be able to expect is that events on a stream will be processed in the same order in which they were enqueued.  So if a single grain generates events Cmd1, Cmd2, and Cmd3, and the same stream processor grain processed all three commands, then the resulting ack stream should be ack1, ack2, ack3.

**Comment by OndrejKraus** [comment]
@jason-bragg Excellent, it is exactly what I was looking for, works almost as expected. There is just one mild issue - when I send a message to the stream, first subscriber receives it after about 30ms. Therefore process, which originally took 50ms is now on steady 500ms. Is there some setting which can change this behavior?

@sergeybykov The producer of Cmd stream does not need to know if an event was delivered or not. Consumers need to receive it, even with retries. We plan to use some external stream provider for this and we will use MemoryStream for unit testing.

**Comment by jason-bragg** [comment]
@OndrejKraus, The response time using persistent streams (in this case Memory Streams) may be higher in some cases, but the throughput should be good.  I suggest running the service under load and  seeing how it performs.  It's not been tuned for responsiveness under sparse throughput.

Events are pulled from the queue and delivered as long as there are events, but when the queue is queried and there are no more events, the pulling agent will delay for a bit before retrying (as not to spam an empty queue with requests).  The delay time is configurable.  If you wish to improve response time under low throughput, you may want to consider configuring StreamPullingAgentOptions.GetQueueMsgsTimerPeriod, which controls the delay time.  By default this value is 100ms, but can probably be reduced as low as 1ms without significant harm.  It is only used when the queue is empty.
Something like:

                    .AddMemoryStreams<DefaultMemoryMessageBodySerializer>("blarg", b =>
                    {
                        b.ConfigurePartitioning(partitionCount);
                        b.ConfigurePullingAgent(ob => ob.Configure(options =>
                            options.GetQueueMsgsTimerPeriod = TimeSpan.FromMilliseconds(5)));
                        ...

Also there is some setup necessary for each stream, which may exceed that performed for SMS, so delivery time of first messages will likely be orders of magnitude worse than the delivery time of following messages.  If first message delivery time is critical to the system behavior, by all means, measure and optimize, but it shouldn't be understood as indicative of overall system performance.

If performance is primary consideration, beyond reliability/recoverability, consider use of implicit subscriptions, as they do not require storage calls for stream subscription management.  If explicit subscriptions are necessary, may want to consider the use of memory storage for pubsub, as it would likely be faster than remote storage service.  Both these options have trade-offs, but significance of each depends on the service.

**Comment by OndrejKraus** [comment]
@jason-bragg works like a charm.

Thank you very much for all the help and recommendations. And most importantly for such a great product.
