### ISSUE TITLE
Orleans for distributed and highly available monitoring

### ISSUE THREAD

**Issue by JosephGarrone** [dotnet/orleans#6278]
Hi, posting here after suggestion from gitter.

Original post:
>How well does Orleans cope with single connections to endpoints. i.e. Say you have an endpoint that only allows at most 1 connection to it to monitor it/fetch some data/etc. There may be many of these endpoints, each with a 1 connection limit. Additionally, this endpoint might be polled anywhere from say every 100ms up to potentially 1-2 minutes, depending on some configuration. Further to this, some of these endpoints are established in a pub/sub manner, where the Orleans service would subscribe the endpoint and then handle changes that are pushed through by the endpoint.
>
>How achievable does this sound within the Orleans framework (i.e. distributed and highly available)

To add some more context, take say [DNP3](https://en.wikipedia.org/wiki/DNP3) where only a single master is allowed and data comes across in deltas after the initial interrogation or [modbus](https://en.wikipedia.org/wiki/Modbus) where a single master exists and all data might be scanned at each interval.

In this case I assume that the "master" for a specific device would be a single grain (i.e. all modbus devices might be speaking to a different physical server, but would have at most 1 active master). The part of the issue I am trying to solve at the moment, is how would one go about triggering relatively precise timers (i.e. from say 100ms through to 60 seconds) on a regular and highly available interval, to ensure that a "master" grain is polling/receiving data is being done so regularly - i.e. similar tolerance to a dedicated thread that polls a device using `Thread.Sleep(100ms)`, so we're probably talking within 5-10ms in the 100ms case).

Further to this, if we consider a case (no longer DNP3 or modbus) where the "master" grain activates and subscribes to an endpoint, and then the endpoint communicates back at its own discretion to the "grain" with events and/or data (This could be at the TCP/UDP level, or at the HTTP level), would Orleans be able to cope with this, or would it require a wrapper application above it to handle the request and pass it onto Orleans? If the latter, then this adds another level of complexity.

**Comment by sergeybykov** [comment]
>In this case I assume that the "master" for a specific device would be a single grain (i.e. all modbus devices might be speaking to a different physical server, but would have at most 1 active master). The part of the issue I am trying to solve at the moment, is how would one go about triggering relatively precise timers (i.e. from say 100ms through to 60 seconds) on a regular and highly available interval, to ensure that a "master" grain is polling/receiving data is being done so regularly - i.e. similar tolerance to a dedicated thread that polls a device using Thread.Sleep(100ms), so we're probably talking within 5-10ms in the 100ms case).

I see three potential options here, from most embedded to least.

1. A grain with a timer. It can be set to fire every 100ms. The actual performance and consistency of this approach, I suspect, will depend on how many other parallel activities would interfere with the polling and how many such polling grain will run within a silo.

2. A grain that starts an external dedicated _thread_, holds its handle, and restarts the thread if needed. The grain would handle control flow: start/stop polling, etc., but the thread would execute `Thread.Sleep(100ms)`-style code. Consistency of execution would be independent from the Orleans scheduler, but would still run within the same process.

3. A grains that starts an external _process_, holds its handle, and restarts the process if needed. The grain would handle control flow: start/stop polling, etc., and the process will communicate with the cluster via an Orleans client.

I would start with option 1, and then would progress down if results aren't sufficient.

>Further to this, if we consider a case (no longer DNP3 or modbus) where the "master" grain activates and subscribes to an endpoint, and then the endpoint communicates back at its own discretion to the "grain" with events and/or data (This could be at the TCP/UDP level, or at the HTTP level), would Orleans be able to cope with this, or would it require a wrapper application above it to handle the request and pass it onto Orleans? If the latter, then this adds another level of complexity.

Such a grain can initialize a listener for an endpoint. The callback of the listener will execute outside of the grain scheduling context, and so it would have to make a grain call, to the original or some other grain, and not invoke its methods directly. Otherwise, it would violate the single-threaded guarantee of the grain.

**Comment by JosephGarrone** [comment]
If we consider option 1, the grain with a timer, how does this fit into the grain activation across the silos? If its active on Silo 1 and then Silo 1 goes down, would this grain then re-activate on Silo 2 and restart the timer? 

Trying to get my head around how this could be used in a high availability scenario, whereby endpoints/devices must always be monitored. Minimal downtime is to be expected during a "failover" type event (i.e. Silo 1 going down and Silo 2 picking up the slack).

**Comment by sergeybykov** [comment]
In most cases grains are reactive - they get invoked by an external request, and that makes them reactivate after a silo failure.

If the grain in your case only executes from timer ticks, it needs an additional reactivation mechanism. In order to keep the grain in memory and get reactivated in case of a silo failure, it needs to get periodically invoked. Typically, that is accomplished via a reminder. If frequency of a reminder isn't enough, you could have N other grains periodically call the polling grain to ensure it gets reactivated right away.

**Comment by JosephGarrone** [comment]
Ok thanks for that. If I understand you correctly, then the maximum downtime between a failed grain and a new grain being activated would be ideally frequency of reminder / N grains (i.e. if reminder fires every 5 seconds, and you have 5 grains ensuring the polling grain is active, you would ideally see the polling grain being re-activated every 1 seconds, if the 5 reminder grains are equally spaced in their startup?)

**Comment by sergeybykov** [comment]
That's generally correct. However, consider also the time it takes to detect a silo failure (configurable) and to reconfigure the cluster (e.g. redistribute reminder service partitions). After that, the grain recovery time kicks in.
