### ISSUE TITLE
Cannot find an implementation class for grain interface: "custom grain". Make sure the grain assembly was correctly deployed and loaded in the silo.

### ISSUE THREAD

**Issue by nofate83** [dotnet/orleans#6288]
Hello every one.
I get this exception on orleans 3.0.2
I'm sure it is not by localization (i have win 10 rus), because i'v tried run this app on centOS 7, dotnet 3.1 and got the same exception
Then the silo is started - i can see that both my grains is loaded correctly (9 grains total)
I saw similar topics about this ex, but dont find answer.... Can anyone help me. Silo is local, code below.

```C#
private static async Task<ISiloHost> StartSiloAsync() 
        {
            ISiloHost silo = new SiloHostBuilder()
                .UseLocalhostClustering()
                .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Loopback)
                .ConfigureApplicationParts(parts => parts.AddFromApplicationBaseDirectory())
                 .ConfigureLogging(logging =>
                    logging.AddConsole().SetMinimumLevel(LogLevel.Information)
                    )
                .UseEnvironment("Dev")
                .AddSimpleMessageStreamProvider("MessageProvider")
                .AddMemoryGrainStorage("MemStorage")
                //.AddMemoryGrainStorageAsDefault()
                 .Build();
            await silo.StartAsync();
            return silo;
        }
```

sorry for code markup, it just ignored, don't understand how its works

**Comment by nofate83** [comment]
clear nuget cache - has no effect

**Comment by ReubenBond** [comment]
Hi @nofate83, check these things:

* Your grain class inherits from the `Grain` base class
* Your grain interface and grain class projects have the `Microsoft.Orleans.CodeGenerator.MSBuild` NuGet packages installed
* Your silo project references your grain interface and grain class projects

In your example, you have a call to `ConfigureApplicationParts` - I'd remove that if I were you. That alone may solve your problem

**Comment by nofate83** [comment]
Hello, @ReubenBond 

Of course all this things are checked and its allright. (Actually reference to the interface project is not necessary) About ApplicationParts - how i told, than the silo is started i can see that both my custom grains are loaded. 
![silo1](https://user-images.githubusercontent.com/60349728/74448804-45af7e00-4e84-11ea-908f-e96bd0386bf6.jpg)
if i will delete ConfigureApplicationParts how silo knows about custom grains? Or you mean to load custom grains separately? Ive tried - all the same.

**Comment by ReubenBond** [comment]
The silo will load grain assemblies referenced by the silo by default. Manually configuring application parts overrides that default behavior (so it doesn't load referenced assemblies anymore)

**Comment by ReubenBond** [comment]
I'll need to see more information. What are your custom grain interface and class names?

**Comment by nofate83** [comment]
@ReubenBond 
this?
![silo2](https://user-images.githubusercontent.com/60349728/74451713-b8225d00-4e88-11ea-8625-e99ebc182c6c.jpg)

**Comment by nofate83** [comment]
@ReubenBond  also you can see it in the first screenshot (in the red rect)

**Comment by ReubenBond** [comment]
Do you know which grain is not able to be activated? If you change the culture to invariant, does it still occur? Try adding this to the top of Main:

``` C#
CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.InvariantCulture;
```

**Comment by nofate83** [comment]
just tried - nope. still get this error. I think  - localization it doesn't matter here, because ive get this error in windows and linux (cent os)

**Comment by ReubenBond** [comment]
Thanks. Could you provide more information on the grain which is causing trouble?

Where is the call coming from - a client? Have you still got the ConfigureAssemblyParts line removed? It should not be there. If you upload your code somewhere, I can investigate

**Comment by nofate83** [comment]
@ReubenBond My silo client its a part of server application. I use websocket server (DotNetty), so client connect to server via websocket, and than websocket frames deserialized to my classes (request/response) which operate with silo client. No problem to share my project

**Comment by fdbeirao** [comment]
Came here with the same problem. During the investigation to complete the issue, I discovered that indeed I was being silly. One of my grains was trying to communicate with another method, and I was using `.GetGrain<Implementation>` instead of `.GetGrain<Interface>`. The confusing part for me was that this error was showing up in the frontend logs, not in the silo logs. Don't write code tired.

Small remark @ReubenBond : removing `ConfigureApplicationParts` breaks everything. My custom grains no longer show in the SiloStart up. Bringing it back makes things work, so I'm sticking with it.

Oh, and it's the way the documentation states we should configure [clients](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/client_configuration.html) and [servers](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/server_configuration.html).

Cheers and thanks for the good work.

**Comment by Radytz** [comment]
I also found this to be happening when on FIRST build of the project the grain has a specified StorageProvider but that provider does not exist, i think that the code generator skips that specific grain class. After you correctly configure the required storage provider (in memory in my case)  and rebuild, it works. I find this hard to reproduce though.

**Comment by cojocaru-dragos-alexandru** [comment]
> * Microsoft.Orleans.CodeGenerator.MSBuild

This always gets me

**Comment by oising** [comment]
> Came here with the same problem. During the investigation to complete the issue, I discovered that indeed I was being silly. One of my grains was trying to communicate with another method, and I was using `.GetGrain<Implementation>` instead of `.GetGrain<Interface>`. The confusing part for me was that this error was showing up in the frontend logs, not in the silo logs. Don't write code tired.
> 
> Small remark @ReubenBond : removing `ConfigureApplicationParts` breaks everything. My custom grains no longer show in the SiloStart up. Bringing it back makes things work, so I'm sticking with it.
> 
> Oh, and it's the way the documentation states we should configure [clients](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/client_configuration.html) and [servers](https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/server_configuration.html).
> 
> Cheers and thanks for the good work.

I just tried removing `ConfigureApplicationParts` also, v3.4.1, and my silo project references my grain projects -- immediately breaks everything. Can't find any implementations. I had to also put it back -- are you sure @ReubenBond  ?

**Comment by leonids2005** [comment]
Any resolution here? I have the same problem when create a HelloWorld example from the manual :(

**Comment by kdenney** [comment]
Can we please get an answer  on this or an update? 

I am now having this issue and typically the instructions from Reuben above tend to work but this time it showed up out of nowhere. The only big thing that changed was that I had to uninstall and reinstall docker because of an unrelated issue. After this was all connected and finished, this error started showing up, even on code that had previously worked with no issue. Is there possibly some sort of cache that I need to clear? Any guidance is appreciated.

**Comment by ReubenBond** [comment]
Are you using the OrleansDashboard project in your application, @kdenney? If so, it appears to inadvertently add application parts which stops Orleans' default behavior and that may be messing with your (rightly) expected results. I'll submit a fix to the dashboard project. The troublesome expression is .WithReferences() here: https://github.com/OrleansContrib/OrleansDashboard/blob/5d53f2e49caf45ccabc63f693914ea982dd2bc91/OrleansDashboard/ServiceCollectionExtensions.cs#L86

If not, do you have reminders in your application? Reminders which were targeted at a grain type which has since been deleted can cause this. Eg, if you have a reminder for a grain of type PlayerGrain but then you delete that class, this will occur when the reminder eventually fires.

Alternatively, are you using a heterogeneous cluster with a Web frontend and is this happening during startup of one of the machines? This could be a race during startup where a client tries to message a grain before the process knows of any compatible silo in the cluster. If that's the case, it's a bug which we need to fix.

**Comment by kdenney** [comment]
Sadly, the answer to all 3 of your first questions are "no". 

I have a simple console app silo with clustering and uses ConfigureApplicationParts to reference the assembly that the grains are contained in. Then, I have a web api project that simply creates a client, uses it to get grains, and call the methods. This has worked even as recently as earlier today.

All in .NET5, by the way.

The only thing that I know of that has changed has not even been code-related. I can back my git repo up 2 days when I know it worked, and I'm still getting the error about Grain missing. That's all the relevant information I can think of for now.

**Comment by kdenney** [comment]
I have been able to consistently recreate this issue. I am trying to add OpenTelemetry to my orleans stack using the video you did as a guide, and if I add this line to my silo Program.cs file - 

            Activity.DefaultIdFormat = ActivityIdFormat.W3C;

It causes the "Cannot find an implementation class for grain interface" issue.

Now, I'm not convinced that the silo needs this line because I believe in your example, only the client-side (the webapi) needs that, but it does consistently recreate the issue if that helps.

**Comment by ReubenBond** [comment]
@kdenney could you upload a repro?

**Comment by kdenney** [comment]
Sure, I'll try and get something simple thrown together and push it up and once I'm finished, I'll post the repo here. Might be a few days.

**Comment by kdenney** [comment]
Well, I have bad news and good news.

The bad news is that I can not consistently reproduce this....and it keeps happening. Maybe twice a day, my web api randomly begins throwing this exception and I have no idea what triggers it.

The good news is that this seems to be a Rider issue for me and I can fix it every time by using "Restart and Invalidate Caches" in Jetbrains Rider.  So if you are getting this error in Rider, try doing that to fix!

**Comment by kdenney** [comment]
@ReubenBond  I have a working recreation of this finally that I have uploaded to here:
https://github.com/kdenney/OrleansErrorCreation

You should be able to follow the steps in the readme and recreate the issue every time.

This does seem specific to using Orleans as a client in a Grpc Api project, however. Let me know if you'd rather I make a new issue.

**Comment by kdenney** [comment]
Ok now I am even more confused, sorry for this. I implemented what I thought fixed it in our business project (which is working fine now somehow) but the above example repo is still erroring. So I guess you can still look into that if you want an example of grains not being loaded properly.

**Comment by kdenney** [comment]
@ReubenBond This is happening again in our business project for a new silo that I added. One silo works fine, the other doesn't find the grains and there's no seeming difference between the two. Could you look at my repro github repo above and perhaps track down what could be causing it? At this point, we are very close to having to remove Orleans from our project and I really don't want to have to do because of this small issue. Thanks so much for any help you can provide!
