### ISSUE TITLE
How to configure pressure in Azure Streams

### ISSUE THREAD

**Issue by rallets** [dotnet/orleans#6300]
I'm using a Persisted stream via Azure Queue, running in Storage Emulator, using a VM as development machine. It looks like the pulling agents are keeping my CPU at 100%, slowing down everything and making difficult to work.
I was wondering if it was possible to change the behaviour of the polling, as example changing the number of pulling agents to 1, with a 1 second interval between each poll. I'm not able to find any documentation about this configuration option.
Thank you

**Comment by jason-bragg** [comment]
The number of pulling agents is same as the number of queues.  See AzureQueueOptions.QueueNames

The pulling agents will pull repeatedly until their are no more messages on a queue, then delay for a configurable period (by default 100ms) before continuing to pull.  This would mean that their would need to be quite a bit of messages in the queue for them to continually pull.

Further, the pulling agents place messages in a cache (one cache per queue) for delivery to consumers, but will stop reading if the cache fills up.  Messages are removed from the cache once consumers process the messages, so the read rate should roughly be throttled by the processing rate of the consumers.

I'm surprised the pulling agents would use that much CPU, as most of their behavior should be asynchronous calls to storage or to grains.  What led to the conclusion the cpu burn is due to pulling agents?

**Comment by rallets** [comment]
> The number of pulling agents is same as the number of queues, default of 8 queues. See AzureQueueOptions.QueueNames

I tried with 
`options.QueueNames = List<string> {"queue1"};`
and now it runs with only 1 queue. Perfect, thanks. This helps a lot.

> The pulling agents will pull repeatedly until their are no more messages on a queue, then delay for a configurable period (by default 100ms) before continuing to pull. This would mean that their would need to be quite a bit of messages in the queue for them to continually pull.

I haven't found this config. Can you please point me out where it is?

> Further, the pulling agents place messages in a cache (one cache per queue) for delivery to consumers, but will stop reading if the cache fills up. Messages are removed from the cache once consumers process the messages, so the read rate should roughly be throttled by the processing rate of the consumers.

This means that I can also reduce the cache size, right?

> I'm surprised the pulling agents would use that much CPU, as most of their behavior should be asynchronous calls to storage or to grains. What led to the conclusion the cpu burn is due to pulling agents?

I'm working on a test project using Asp.net core WebApi with direct client, using Azure Storage Emulator (tables, blobs and queues). The client is a console application that calls the Api. Console logging is reduced to the minimum. 
If no calls, there is only a timer triggering every 5 seconds (but no I/O is made), and only negligible low grain activity every 10 seconds. 
At some point I have added the queue and a grain consuming the messages, and everything did slow down with high cpu load.

As I mentioned, it's a VM with a low amount of resources (4 GB ram, 4 core on i5, SSD), and I'm running with the VS 2019 debugger attached.

- Attached two screenshot, running in the VM machine, VS2019: the system without activity (so only the negligible activity and the queue with default config) with CPU ~80% and the system during activity hits 100%.

- Attached two screenshot, running in the physical machine, VS2019: the same project running on another physical machine (16Gb Ram, 6 core i7-8750H, SSD), the system is still well responsive and no cpu burn.

- Attached one screenshot, running in the physical machine with only 1 queue, VS2019: the CPU load is now a lot lower. When the activity is paused, the CPU is close to zero.

![orleans running in VM](https://user-images.githubusercontent.com/379999/74419953-f6009080-4e4a-11ea-8551-30f2199e7b80.jpg)
![orleans paused in VM](https://user-images.githubusercontent.com/379999/74419956-f6992700-4e4a-11ea-86f7-cb7148fecf11.jpg)
![orleans running in physical machine](https://user-images.githubusercontent.com/379999/74419958-f731bd80-4e4a-11ea-977d-090458233a0d.jpg)
![orleans paused in physical machine](https://user-images.githubusercontent.com/379999/74419960-f731bd80-4e4a-11ea-9cb9-b7cbbc5ed16a.jpg)
![orleans running in physical machine with 1 queue](https://user-images.githubusercontent.com/379999/74419963-f7ca5400-4e4a-11ea-9abb-cfde1d363751.jpg)

**Comment by rallets** [comment]
I found this documentation page: [Orleans Streams Implementation Details](https://dotnet.github.io/orleans/Documentation/implementation/streams_implementation.html)

There's no mention to `.AddAzureQueueStreams<AzureQueueDataAdapterV2>` and to `AzureQueueOptions.QueueNames`. 
Do you like if I provide a PR with some more details about this specific scenario? Or do you think there is a better place?

**Comment by jason-bragg** [comment]
>  I haven't found this config. Can you please point me out where it is?

StreamPullingAgentOptions.GetQueueMsgsTimerPeriod, should be able to use ConfigurePullingAgent(...) to configure it.

> This means that I can also reduce the cache size, right?

Yes, should be able to use ConfigureCacheSize(...) for this.  Default is 4096 messages.  See SimpleQueueCacheOptions.

> There's no mention to .AddAzureQueueStreams<AzureQueueDataAdapterV2> and to AzureQueueOptions.QueueNames.

Yeah, that section is very general, whereas each stream provider (azure queues, eventhub, sms, sqs, ...) has it's own queue specific details and configuration, much of which, unfortunately is not documented.

> Do you like if I provide a PR with some more details about this specific scenario? Or do you think there is a better place?

Always welcoming of contributions.  Since this is related to azure queue streams, I'd suggest adding an azure queue streams page, document what you can, and note that the pages is incomplete, as we'd not want to give the perception that what you document covers the everything.  @sergeybykov, may have better guidance on this.

As far as finding information about configuring and using azure queue streams, i'd suggest looking at the streaming tests.  Specifically AQClientStreamTests, and AQSubscriptionMultiplicityTests, as well as the extension functions for IAzureQueueStreamConfigurator (in AzureQueueStreamConfiguratorExtensions) and ISiloPersistentStreamConfigurator (in SiloPersistentStreamConfiguratorExtensions).  Those contain most of the configuration options.

**Comment by rallets** [comment]
I sent a PR [6306](https://github.com/dotnet/orleans/pull/6306) with a new documentation page.
Thank you
