### ISSUE TITLE
Error doing DeleteMessage for Azure storage queue + Receiving events multiple times

### ISSUE THREAD

**Issue by rallets** [dotnet/orleans#6345]
Hi, it looks like I've encountered the same behaviour as in [Receiving events from Azure Queue Stream Provider multiple times #890](https://github.com/dotnet/orleans/issues/890) and I was wondering if it still the same situation.
I've a project using Orleans 3.0.2 (with Storage emulator) and I've a grain that generate 1000 msg (from a integration/load test) and are processed pretty slowly. It looks like that exactly after 1 minute the queue is not purged, all messages are back to the queue and then some are re-processed. Others messages are not processed at all and they keep to stay in the queue (800/1000). That means it's not just a transient error, it's not recoverable. 
So I get a ton of:

```
fail: Orleans.AzureUtils.AzureQueueDataManager[103211]
      Error doing DeleteMessage for Azure storage queue yourprefix-azurequeueprovider-0
      Exception = Microsoft.Azure.Storage.StorageException: The specified message does not exist.
```

I tried to increase ConfigurePullingAgent.MaxEventDeliveryTime to 60 minutes, but after a silo startup (webapi w/direct client-cohosting) it process some hundred messages and then is back to the same error. The same if I clean the queue and restart the process.

I was wondering which are the possible workaround. Should I just reduce the CacheSize? or it's possible to increase a timeout?
Thank you

**Comment by sergeybykov** [comment]
Have you tried running the code against the actual Azure Queue, not the emulator? Sometimes the emulator behaves differently from the actual service and might have its own bugs.

**Comment by rallets** [comment]
Hi @sergeybykov, sorry for the delay. I just tried with a real Azure Queue, and the behaviour is the same.

**Comment by jason-bragg** [comment]
What is the visibility timeout on the queue?  I believe the default is 30 seconds.
How long does it take to process a message in your service?

Events are read, put in the cache, then delivered for processing by the consumers.  Once successfully delivered, they are deleted from the queue.  If this sequence takes longer than the 'visibility time' the queue will regenerate the message.

**Comment by rallets** [comment]
I was using the default (null), and by the [docs ](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages) it looks like it's 30 seconds.
I tried increasing `AzureQueueOptions.MessageVisibilityTimeout` and all went fine, but then I got a ton of
`warn: Orleans.AzureUtils.AzureQueueDataManager[103213]
      Slow access to Azure queue yourprefix-azurequeueprovider-0 for DeleteQueueMessage, which took 00:00:03.6667778.`

My service process around 800 msgs in a minute, then I get back the messages (and the "delete" errors). So a message takes circa 75 ms (it's a small grain with state persistence, I believe it's slow due to the local storage low performance).

So I was just wondering what could be a correct approach... 1) increase the `MessageVisibilityTimeout`, 2) decrease the `CacheSize` or 3) something else?
I think the default for the `CacheSize` is set to `4096` because is tuned on more/faster queues.
Thank you

**Comment by jason-bragg** [comment]
In general much of the tuning of azure queue streams needs be service specific, unfortunately, but there are some factors one should consider when tuning.

First, most of the settings are per queue, so if you've a large number of streams, the load on each queue can be reduced by configuring more queues.
Since streams process messages in order per stream, the gating factor will be the number of events being sent on a single stream.
A reasonable balance of cache time vs visibility time is that the visibility should be configured to double the time messages are expected to be in the cache.

For example:
assuming:
  100 streams
  10 queues
  Each stream processing 60 messages per minute
  Each message takes around 30ms to process.
  1 minute worth of messages in cache

It would be reasonable to expect:
  Around 20 streams per queue - Even balancing of streams across queues would be 10 streams/queue (100/10), but since streams won't always be evenly balanced over the queues, doubling (or even tripling) the ideal is safer than expecting ideal distribution.  Hence 20 is probably reasonable.
  This means each queue will be expected to process up to 1200 messages per minute (60*20)

If we configure the cache to hold 1 minute of messages (1200 messages), and each takes 30 ms to process, then we can expect messages to spend up to 36 seconds in the cache, so the visibility time would need be over 72 seconds (time in cache * 2).  A bigger cache would require a longer visibility time.
  Since order is only per stream, it's likely that messages will be processed across multiple streams in parallel and we'll burn through the cache in far less time, but if we plan for worse case it will give the system room to continue to function well even under intermittent delays and transient errors.

Regarding the slow delete, I'm unsure why deletes are taking that long.  You'll need to investigate that with azure queue.  I'm unaware of the azure queue performance expectations in this area.

**Comment by rallets** [comment]
Thank you @jason-bragg for the deeply explanation! I found it very interesting and helpful, so I made a [PR 6441](https://github.com/dotnet/orleans/pull/6441) to docs, collecting your input. 
I consider this issue closed too.
