### ISSUE TITLE
Expose configuration for Azure Storage timeouts

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#6383]
See `AzureTableDefaultPolicies`. These values should be configurable on a per-provider basis.

Currently, users do not have any mechanism for customizing these timeouts or other policies.

* [ ] Expose for all providers
* [ ] Ensure all storage methods in (eg) AzureTableDataManager and AzureBlobGrainStorage respect policies

**Comment by veikkoeeva** [comment]
@ReubenBond Does that "expose for all providers" mean all that can be used in Orleans and so a general mechanism that storage providers can rely on configuring user customizable retries? I take that "(eg) AzureTableDataManager" means as for an example but not excluding others.

If so, such a mechanism would be welcome and I think it should be dynamic since a real world scenario would be SLA per customer per time of day or some other event (that then extends to dynamic billing).

**Comment by ReubenBond** [comment]
@veikkoeeva I'm not sure about a general mechanism. Different policies are relevant to different instances of a provider. I think as a first pass, we should just try to make sure that the relevant knobs are accessible and consistently put to use

**Comment by veikkoeeva** [comment]
@ReubenBond I think some kind of a layered approach would be needed. So that the way they are exposed looks similar across all providers even if the provider specific knobs may vary. Then maybe some convenience functions that can be provider specific. I think lambdas, naturally.

An example way of thinking, for ADO.NET some improvements could already be like `.UseMysql` whereas it would then apply the right constants, use lambda to load the right connector (or by default like now try to load either of the most used ones) and so on. To be explicit about one thing, I don't suggest creating a Nuget package per ADO provider to have these functions.

**Comment by ReubenBond** [comment]
I believe this was fixed by #6432
