### ISSUE TITLE
Documentation: Manual/Minimal Hello World

### ISSUE THREAD

**Issue by andrewalex** [dotnet/orleans#641]
I'm not sure if this is the best place to track a Documentation item. Let me know if there is a better location.

I've created a tutorial for Orleans that would fit well in the Step-by-Step tutorials.  It is a simple example that just uses the Nuget packages (not the SDK).  It's quite similar to the current hello world page, and a little more up to date.

If it's useful I'd  be more than happy to tailor it to any suggestions and put it in the best format that works for you. 

https://dl.dropboxusercontent.com/u/77885423/MinimalOrleansExample.docx

**Comment by sergeybykov** [comment]
Yes, this is a good place to track doc issues. Thank you for taking time to put together such a guide. Looks great!

Did you notice that we recently published Orleans VS project templates in the VS gallery - https://visualstudiogallery.msdn.microsoft.com/36903961-63bd-4eec-9ca4-cf2319dc75f4/view/Reviews? It seems to me using the Dev/Test Host template in particular would reduce the amount of boilerplate code you had to write. Since the extension can be downloaded and installed without the need for the SDK, wouldn't that be the easiest way to start?

It is likely we'll deprecate the SDK altogether soon, as it only installs the extension (which we don't need anymore) and a bunch of links in 1.0.9.

**Comment by andrewalex** [comment]
Awesome, I did not catch that they were released.   Do you know if the template is supported in the Express/Community versions of Visual Studio? I can track down a test machine to try 2015 community otherwise.

Either way I'll put together a tutorial that uses the templates if these are useful for you. Is word the best format?

**Comment by sergeybykov** [comment]
Good question. I assume the templates will work in Express/Community but we never checked.

A tutorial like that will be absolutely useful. We have a rather outdated step-by-step guide that we need to update. I think updating "My First Application" is the best option.

We keep docs in .md format in https://github.com/dotnet/orleans/tree/gh-pages, so that it's easy to edit and contribute to them.

**Comment by andrewalex** [comment]
I just confirmed that the templates work within Community.  I do notice, however, the templates use the IGrain interface still. I thought that was deprecated in favor of the more precise ones?

**Comment by sergeybykov** [comment]
Thanks for the confirmation.

Yes, it's an interesting question what the template should use as a base grain interface. We thought `IGrain` is the least evil for know because otherwise we would have to ask for a key type, which requires a wizard as I understand. Maybe we need to add a comment there that `IGrain` is a placeholder. But then people get irritated with "unnecessary" comments in every project.

Any better idea?

**Comment by jthelin** [comment]
Long (Int64) keys are probably the simplest to understand and use, so would probably make a decent default. 

Anyone that has more complex key requirements (For example: Guid or String) can [and probably should] read the docs to understand the API usage pattern for those key types.

**Comment by andrewalex** [comment]
In my opinion the challenge is making a new user not think they made a
mistake when they see missing interfaces.

This is not a concern for a user familiar with the system.  But that sort
of user has less need for a template anyhow.

To me a sensible default (like proposed above) makes sense, but I can also
see why you may not want the templates biased to a specific key type. If
thats case comments would be useful.

**Comment by gabikliot** [comment]
Closed via #658 .
