### ISSUE TITLE
SerializationManager memory optimization

### ISSUE THREAD

**Issue by HermesNew** [dotnet/orleans#6422]
According to my observation, a ClusterClient will have a SerializationManager. If I connect N Silo with one Silo, there will be N + 1 SerializationManager. If I have more types, then a SerializationManager probably uses (N + 1) * 5MByte memory space. I think this memory usage is a bit too large.
![12](https://user-images.githubusercontent.com/22929457/77220718-f0027b80-6b7d-11ea-8ff4-fe2de37b3d6a.png)

This is what I found after long observation and found that the most memory usage is here. I think this is worth optimizing.

The following two reference counts are the most：
1.Orleans.Serialization.SerializationManager.typeKeysToQualifiedNames ->
System.Collections.Generic.Dictionary<System.String, System.String>._entries ->
System.Collections.Generic.Dictionary+Entry<System.String, System.String>[36353]

2.Orleans.Serialization.SerializationManager.deserializers ->
System.Collections.Generic.Dictionary<System.Type, Orleans.Serialization.Deserializer>._entries ->
System.Collections.Generic.Dictionary+Entry<System.Type, Orleans.Serialization.Deserializer>[4049]

**Comment by KevinCathcart** [comment]
Interesting. A few thoughts: it is not necessarily possible to actually share the serialization manager between different clients, since different clusters may have different serializers. This could be different custom serializers for the same type, or different sets of external serializers. You can also have the circumstance where one cluster is using a generated serializer for some shared type via a `[assembly: KnownType(Type)]` attribute, while a different cluster does not, and ends up using a fallback serializer like the ILBasedSerializer. 

None of this is meant to imply that no sharing is possible, but merely that it would need to be done carefully, and things might be trickier than they first seem. One of the biggest issues comes from the fact that each client uses its own dependency injection container, which is deliberate, to allow each client to be configured differently. That makes sharing between them difficult except by using static values. 

As for typeKeysToQualifiedNames, while it has a lot of dictionary entries, it should not be using a lot of memory, since both the key and values should be interned strings (since they come from string literals in the generated code), and thus are shared across the clients, and the dictionary entries should be small enough that they are not a huge deal.

The type to deserializer dictionary on the other hand might be more promising. The value instances for those could potentially be shared between clients whenever they are instances of the same implementation type.
