### ISSUE TITLE
Breaking changes in future versions

### ISSUE THREAD

**Issue by yannolaf** [dotnet/orleans#646]
Great work guys. This is a great product.
BUT we are using this in production. This means breaking changes are really a pain. The new version 1.0.9 introduced nice new features but breaks our builds, we fixed our product but: 

Are there any plans to maintain backward compatibility in future 1.x versions?

Regards yann

**Comment by sergeybykov** [comment]
Thank you! Glad to hear you are running Orleans in production. Can you add your company to http://dotnet.github.io/orleans/Who-Is-Using-Orleans?

Our general feeling is that maintaining backward compatibility at this point would constrain evolution of the codebase too much. We understand it's sometimes pain to upgrade, and we go through it ourselves, e.g. currently upgrading Halo services from 1.0.8 to 1.0.9.

One can always create a private branch off a particular release tag and merge only commits they want to bring to it. But at some point it'll be an inevitable choice between migrating to the latest version or keeping the particular product/service on that private branch.

**Comment by gabikliot** [comment]
I would just add over what Sergey said that we do try hard not to break backward compatibility in general. Allowing our customers to run hassle free without disruptions is among our highest priorities.

However, sometimes we have to make non-backward compatible changes. For example, most of the non compatible changes in 1.0.9 were due to introduction of DI in Orleans, a subject we debated at length with the community and finally decided to do it, since the community was very interested in that. 

In the next release we may want to do 467 and this will also be non backward compatible. [Port to coreclr](#368) may require a couple of other non backward compatible changes.

But we will try to minimize those and provide upgrade instructions.

**Comment by yannolaf** [comment]
Thanks for this information. I am happy to hear that this product will evolve quickly. So we will adapt our architecture to handle the rapid change of Project Orleans. 
I am especially looking forward to the ideas concerning state migration because this is still an issue for us.
So thanks and continue this great work.

**Comment by BenjaminGibbs** [comment]
@yannolaf What do you mean by 'I am especially looking forward to the ideas concerning state migration because this is still an issue for us'

Do you mean between version 1 and 1.1 of your application? or between Orleans upgrades?

**Comment by yannolaf** [comment]
I meant if you change the state structure the deserialization fails using the Azure Table Storage provider. So there have to be a migration between the old state and new state structure. Perhaps Orleans will provide a common way to handle this problem, one day.
