### ISSUE TITLE
Missing method info in grain call filter when using ImmutableDictionary argument

### ISSUE THREAD

**Issue by EdeMeijer** [dotnet/orleans#6464]
Orleans version 3.1.4
Dotnet core 3.1.100

A grain implements IIncomingGrainCallFilter, but all method info in the Invoke() context is null.
I found that this happens when the called function contains an `ImmutableDictionary` argument. When changing it to for example `IDictionary`, the method info is present.

`Repro.cs`
```csharp
using System;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Orleans;

namespace Repro
{
    public interface IRepro : IGrainWithGuidKey
    {
        Task TestFunc(ImmutableDictionary<string, object> data);
    }
    
    public class ReproGrain : Grain, IRepro, IIncomingGrainCallFilter
    {
        public async Task TestFunc(ImmutableDictionary<string, object> data)
        {

        }

        public Task Invoke(IIncomingGrainCallContext context)
        {
            if (context.ImplementationMethod == null)
            {
                throw new NullReferenceException("Fail");
            }

            return Task.CompletedTask;
        }
    }
}
```
Call it with
```csharp
var repro = GrainFactory.GetGrain<IRepro>(Guid.Empty);
await repro.TestFunc(ImmutableDictionary<string, object>.Empty);
```
And see an exception appear.

**Comment by ReubenBond** [comment]
Which code generator package is installed? Does this reproduce in a single project?

**Comment by EdeMeijer** [comment]
```
<PackageReference Include="Microsoft.Orleans.CodeGenerator.MSBuild" Version="3.1.4">
```

Yeah, it's all in a single project with an internal cluster client that calls the function.

**Comment by ReubenBond** [comment]
My first guess would be that ImmutableDictionary changes assemblies between build & run (what a hassle). To test that theory, what happens if you change the type to `Dictionary`? If that is the issue, we likely have an open issue on it, it's something that we need to fix

You can work around this by adding `[MethodId(1)]` (for example) on the method.

**Comment by EdeMeijer** [comment]
With a `Dictionary` everything works fine. Well, good to know, another workaround for now would be to just use a Dictionary argument when interceptors are used. But still not very nice.

**Comment by KevinCathcart** [comment]
Why would changing assemblies matter here? `System.Collections.Immutable.ImmutableDictionary<,>` should omit the assembly due to  `IsSystemNamespace()` returning true, right? Oh, right.

The `InterfaceToImplementationMappingCache` uses `GrainInterfaceUtils.ComputeMethodId()` which uses `RuntimeTypeNameFormatter`, which does not include that system namespace logic, but still does the 'same assembly as typeof(int)` check. Yeah, that would indeed cause the lookup to fail, since it would calculate a different ID than codegen did.

**Comment by ReubenBond** [comment]
This is the same root issue as #5470. I haven't found time to invest in a fix yet, but I recognize that it's an annoying shortcoming.

If you can come up with a fix, @KevinCathcart, that would be fantastic

**Comment by EdeMeijer** [comment]
Well it shouldn't be closed, I think the issue is still there. I was playing around with trying to add tracing support using call grain filters recently, and again ran into not being able to determine which method was being called.
