### ISSUE TITLE
ActivationCollector found an active activation in it's last bucket. This is violation of ActivationC ollector invariants. For now going to defer it's collection

### ISSUE THREAD

**Issue by clement128** [dotnet/orleans#6471]
Hi there,  I saw this warning quite a lots. Any idea to figure out what's the root cause?

Thanks

**Comment by KevinCathcart** [comment]
ActivationCollector is the component of Orleans designed to deactivate grains if they have been unused for long enough.  This warning is intended to indicate that there may be a bug in the ActivationCollector (or in other functionality that it uses), because when it was about to deactivate such a grain, it noticed that it was actually processing a message. It does the correct thing in this case, and resets the countdown to deactivation. 

However, there are a few possible causes other than an Orleans bug. The main one is if a grain method call somehow lasts for longer than the CollectionAge value. The default value for that is 2 hours, so that would be a crazy long time, but if there is some form of accidental infinite (or at least absurdly long) loop in the grain (perhaps some form of retry loop around some async call), or you await some task that never completes this could happen. And of course if you have lowered the Collection age, this could happen much easier.

I believe there is another possible non-bug cause for this, namely a race condition. However if I am correct about that, the window for this to happen is extremely small, and Therefore it seems unlikely that you could see this warning for that reason “quite a lot”. Therefore I believe the other case is more likely the cause of what you are seeing.

Some technical details about the suspected race condition case:
>I'm pretty sure that the `IsActive` and `IsStale(now)` warning messages can be triggered as a race condition, simply on the basis that (as far as I can tell) nothing prevents them those activations from getting a message between the time that the bucket is grabbed in `DequeueQuantum`, and `ScanStale()` reaching and locking that particular `ActivationData`. This is not necessarily a problem, because it merely warns, and then does what is indisputably the correct thing for those cases, but the warning text sounds a bit more alarming than seems reasonable for something that can validly occur as a race condition.

**Comment by clement128** [comment]
hi @KevinCathcart thanks for your comments.

> The main one is if a grain method call somehow lasts for longer than the CollectionAge value. The default value for that is 2 hours, so that would be a crazy long time

For my case, I set `[CollectionAgeLimit(Minutes = 1.1)]` for my Grain. I was want to set to `Minutes=1` but that's not allow and I need it to be deactivate if no message after 1 minute.

My business logic is:

1. If the Grain no message at all for 1 minutes, deactivate it.
2. If the Grain keep receive message in 1 minutes, continue process and keep it alive.
3. But sometime, my Grain waiting on external service response maybe need to wait more than 2~3 minutes.

Here is the pseudo code

```c#
namespace MyProject.Grains
{
    // If no message at all in 1.1 minutes, I want it to be deactivate
    [CollectionAgeLimit(Minutes = 1.1)]
    public class Worker : Grain, IWorker
    {
        private readonly IExteranlService externalService;

        public Worker(IExteranlService externalService)
        { 
            this.externalService = externalService;
        }

        public override async Task OnDeactivateAsync()
        {
            // Here this method might take more than 3 minutes
            await externalService.NofityNoMessage();
            await base.OnDeactivateAsync();
        }

        public async Task ProcessMessage(MyCommand command)
        {
            // Here this method might take more than 3 minutes
            await externalService.Process(command);
            // .. and some other logic to process the message
        }
    }
}

```

Should I use `CollectionAgeLimit` for this scenario? or better use `Timer` + `DeactivateOnIdle`?

**Comment by KevinCathcart** [comment]
Collection age is always based on when processing of the most recent message started. Please note that that is not necessarily when the message was received, since if the previous message was still being processed, the new one will queue up behind it. 

Ideally you would try to avoid tying the no-message for 1 minute logic to grain deactivation. It might potentially be a reasonable solution for your specific problem, but actually caring about when your grain gets deactivated means you outside the intention of the virtual actor model. It can also have some unwanted side effects. For example, the grain deactivation code gets called for all grains when you shut the silo down, and you might or might not want to call the external method in that case.

So how should you handle this requirement? You probably do want to use a timer for this, as trying to use the ActivationAge for this is pretty much guaranteed to cause that warning, and can potentially also negatively impact the performance of the ActivationCollector. Just be careful with the timers. The timer callbacks are basically `[AlwaysInterleave]`, which is often important to take into account.

Beyond using a timer in some manner, a lot will depend on the exact details of your one minute requirement. For example, if you get a message, but your external call takes 2 minutes, does that mean you should immediately notify of no messages? Or is one minute from the end of the last external call what you really need? Think about the answer to questions along those lines when adding the time based system.

Hope this helps.

**Comment by clement128** [comment]
hi @KevinCathcart thank you, after adjust the `CollectionAgeLimit` now seems good now, so far no warning.

**Comment by clement128** [comment]
Btw, I think we should add this to the documents for what you explain to me here :)
