### ISSUE TITLE
Multiple Cards

### ISSUE THREAD

**Issue by mohamedhammad** [dotnet/orleans#6486]
i have a server machine with Orleans installed, this server machine have two network cards,i have configured the silo to listen to all network cars IPs, but in the membership data base only one IP is advertised to the table.
this is causing problems in connectivity to some of the clients connected to one of the network cards that is not advertised to the membership database

**Comment by mohamedhammad** [comment]
Did you manage to confirm the issue?

**Comment by benjaminpetit** [comment]
The current membership provider does not support publishing multiple IP addresses.

It's not a trivial thing to implement, because we would need:

- Change the membership storage without breaking backward compatibility
- Use some kind of network discovery protocol: how clients/silos will know which IP listed to use?

Can you share more info on your network infrastructure to see if there is any possible work around?
