### ISSUE TITLE
Segmenting the pulling agents in an heterogeneous cluster

### ISSUE THREAD

**Issue by peter-maude** [dotnet/orleans#6489]
Hi,

Does anyone know if it is possible to have a heterogenous cluster, effectively split into one "half".  where one half has the pulling agents, and the other has your own customer grains

Should the pulling agents respect the excluded types in the silo config ?

Thanks

**Comment by KevinCathcart** [comment]
The only way to control the placement of the persistent stream pulling agents is via an `IStreamQueueBalancer`. All the existing balancers are using various methods to try to keep the pulling agents evenly distributed across all silos.

It is entirely possible to create a queue balancer that only allows the pulling agents on a specific subset of silos. However actually doing so would be rather a pain, because a lot of functionality that the built in balancers use is internal, so it would not be very easy to create a new one based on one of them.

Why would you want to separate out the pulling agents like that in the first place?
