### ISSUE TITLE
Reoccuring "Dropping expired message" warning

### ISSUE THREAD

**Issue by oleggolovkovuss** [dotnet/orleans#6512]
Hello, I've already reported a similar bug with warnings being spammed to logs every minute or so.
This time the message from each silo is 

`Dropping expired message "Request S10.0.4.179:8952:325434882*cli/6674aabc@88c1f993->S10.0.4.179:8952:325434882*grn/205D0BBF/a7ab9f84@e9dc8796 #214: " at phase Respond`

The issue started happening after a cluster redeployment. It went bad: my clients stopped being able to use silos (which I think is a very serious issue, but I don't have 100% exact steps to reproduce) with errors like "timed out waiting after 30 seconds" though the silos seemed to operate fine. I fixed that by rebooting the clients but the warning that I posted above just won't go away

ASP.NET Core 3.1
Orleans 3.1.4
3 Silos
MySQL clustering

**Comment by ReubenBond** [comment]
Sounds like your messages are taking a very long time to complete processing.

There's no general solution to this: you need to analyze what your code is doing. A profiler is a good start, but even logs can provide some insight.

**Comment by oleggolovkovuss** [comment]
The problem is that from what I can see which are:
1. the dashboard from the "contrib" project
2. Zipkin telemetry with 100% sampling rate
3. Just common user experience using the site
everything is completely fine. Looks more like a problem with "self-healing" after some crashes or redeployments like for example if I turn down all the silo VMs at once and then turn them back on the cluster won't be able to operate until I manually delete everything from the clustering table. Also I think you fixed a similar issue with warnings in logs because some timer wasn't correctly disposed on exception. 
Overall I'm raising these issues because it feels like either I'm using not a very well supported implementation (like the error messages in logs saying something like "cleanup defunct silos not supported", but which ones do have it supported and what's the impact?) or my config needs adjustment and I can't find any documentation with suggested production-proven architecture samples

**Comment by ReubenBond** [comment]
Cleanup of the clustering table shouldn't be a major issue here, and the warning is not related. Neither of those things will affect messaging/performance.
A 100% Zipkin sampling rate would likely cause major/catastrophic performance issues at scale.

It's potentially an issue caused by your architecture/messaging topology. Eg, if all calls come through a single grain, and they take a long time to process, then you will of course start to see problems like what you describe at some load level. I.e, if admission rate is higher than servicing rate, then you will see increasing latency and eventually timeouts & expired messages.
The same thing is true for any kind of fan-in at some level of load, but other issues can cause this. For example, if there's a deadlock.

It's not clear from your comment whether you've profiled the application yet, but in addition to looking at that, we should consider what your messaging topology (your architecture) looks like.

**Comment by oleggolovkovuss** [comment]
By 100% rate I meant that I observe all the metrics, this is an internal module not serving HTTP in which I construct traces manually only for the scenario where I need them (payments) and this performs great under load tests, thanks for the concern however.

Ok, I don't have any 100% shareable & reproducible steps at the moment so I'll close it until I figure out what actions are causing this behavior

**Comment by ReubenBond** [comment]
You don't need to close the issue, we can look at what your service is doing which would cause such delays. If Zipkin is only tracing a small amount of the actions on certain paths, then it may be fine - tracing every single interaction would be overly expensive (and the reason it's rarely done at scale).

Please consider profiling & analyzing messaging patterns.
