### ISSUE TITLE
Azure table exceptions cant be serialized

### ISSUE THREAD

**Issue by mchandler-manticore** [dotnet/orleans#6516]
Getting this a lot in our error logs:

`Type 'Microsoft.Azure.Cosmos.Table.StorageException' in Assembly 'Microsoft.Azure.Cosmos.Table, Version=1.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is not marked as serializable.`

Would it make sense to wrap these exceptions if they cant be sent over orleans?

**Comment by JorgeCandeias** [comment]
It would.

This issue happens when an exception class does not implement the [exception serialization pattern](https://docs.microsoft.com/en-us/archive/blogs/agileer/the-correct-way-to-code-a-custom-exception-class). It's rare to see this in Microsoft code though it does pop up here and there.

You can handle that call-by-call or you can use an [outgoing call filter](https://dotnet.github.io/orleans/Documentation/grains/interceptors.html#outgoing-call-filters) to handle it across the board.

**Comment by SebastianStehle** [comment]
I think it would be great to provide a default behavior for that.

**Comment by icanhasjonas** [comment]
.. chances are that any client that connects to the cluster won't have the `Microsoft.Azure.Cosmos.Table.StorageException` type to deserialize anyway. I agree, better to filter exotic exceptions and replace them with more generic exceptions that are sure to exist on all sides of the cluster.

**Comment by ReubenBond** [comment]
We implemented fallback exception serialization recently: https://github.com/dotnet/orleans/pull/6917

I may be able to port it to the 3.x branch and include it in an eventual 3.5 release

**Comment by sgordon5** [comment]
We are currently running into this issue as well. Is there any update on if this will be included in 3.5 and when 3.5 is target for release? Thanks!

**Comment by ReubenBond** [comment]
3.5.0 adds the `ILBasedSerializer` as a fallback by default if `BinaryFormatter` is not enabled (#7198).
4.0.0 adds better exception support (via #7070), but it's not something which can be easily backported to 3.x

If an exception is not serializable by the configured fallback serializer (eg, `BinaryFormatter`), there's not that much which can be done. An exception should still be propagated back to the caller to tell them that an exception could not be serialized.
