### ISSUE TITLE
Use azure storage built-in retry mechanisms

### ISSUE THREAD

**Issue by jdom** [dotnet/orleans#653]
Since Azure Storage 2.0, the client APIs provide built-in behavior for preforming retries on transient faults.
I think it would be useful to use the built-in ways instead of using the custom `AsyncExecutorWithRetries` (which was very useful before 2.0 was released). The built-in mechanism has a better domain understanding of what is a transient fault, and also it would be useful if in methods like `AzureTableDataManager.ReadTableEntriesAndEtagsAsync` in case of a transient failure reading from one of the segments, it doesn't retry the entire operation from scratch.

**Comment by gabikliot** [comment]
Good idea.

**Comment by sergeybykov** [comment]
@jdom Do you think you can craft a PR with this change?

**Comment by evanization** [comment]
Hi,

Is this work in progress?
I am totally new to GitHub and wish to contribute to this task. Will that be possible?

Thanks.

**Comment by veikkoeeva** [comment]
@evanization My two small moneys. :) I don't think this is a work in progress. Sure it's possible to contribute, just fork Orleans and give it a go. I think there's roughly two ways you can go with this:
* Have a short spike to see how things could be done. Maybe make a PR so it's for others easier to see. Maybe it transforms to a serious effort while spiking, maybe not.
* Do tell here if you are seriously working on this and you the bandwidth to make progress, perhaps opening a PR. See the others as en example.

I think one source of difficulty here is that the exceptions should be preserved at least mostly like they are now due to dependencies.

If you need help with practices, Git, Github etc., the people on Orleans Gitter channel are of help.

**Comment by gabikliot** [comment]
@evanization , sure, go ahead. No one is working  on this, as far as I know.

**Comment by jdom** [comment]
yeah, I'm not, I didn't have the bandwidth to even start looking at it. I opened the issue as I thought it might be something that was easy to grab by others, as it doesn't require deep knowledge of the Orleans core. So great :)

**Comment by gabikliot** [comment]
We just learned that this is not a good idea. Orleans's critical system tables are better use their own retry policy, even if this is on top of a built-in Azure retry policies, for extra safety. @sergeybykov has the details.

**Comment by onionhammer** [comment]
@sergeybykov It was mentioned "has the details" - what are the details? :)
