### ISSUE TITLE
Use case scenario

### ISSUE THREAD

**Issue by dodyg** [dotnet/orleans#6532]
I have no experience using an Actor based system. There's a pilot project coming up that involves just connecting to two different SOAP APIs (one payment system and another billing aggregator) and store the results in the DB. It looks simple enough.

The goal of the project though is to be able to eventually process 300 million transactions a year.

Now is this the kind of problem that Orleans designed for? It looks like it but I have no experience style of programming so I can't tell for sure. This is obviously can be done by a straightforward ASP.NET Core app but I wonder if Orleans will make the issue of upgrading, deployment and resiliency easier.

**Comment by sergeybykov** [comment]
I think the first question to answer here is if the project would benefit from being a stateful app, that is one that keeps state in memory and tries to executes a series of requests against that in-memory state instead of going to storage to load the state upon every request. If the answer is yes, then the next step is typically to decide how that state would be partitioned, so that:

1) requests would be able to execute in parallel without a central lock or other expensive synchronization point;
2) execution of the requests could be distributed across a cluster of servers.

The typical state models that partition naturally are per-user/per-device/per-session states that are easy to encapsulate in respective grain classes in Orleans.

I hope this provides an initial idea for your question. Sorry about delayed response.

**Comment by dodyg** [comment]
Thank you for your response. 

I think for this use case we would have to go back to the database every time. There isn't any temporary actions such as filling up cart or building flight itinerary. Every payment is either successful or not.

**Comment by sergeybykov** [comment]
Even in that case you might benefit from serializing database operations for each entity (by routing them through respective grains) to prevent attempts of concurrent updates. I guess it depends how big of a problem that it in your case. May or may not be worth it.
