### ISSUE TITLE
Support for platforms like IOS that do not allow JIT code

### ISSUE THREAD

**Issue by GaLeGayGay** [dotnet/orleans#6536]
I am currently developing the Orleans Client using Unity
I see Orleans using Rolsyn to generate assemblies at runtime.
This doesn't work on IOS. Is there an AOT way of generating code?
Or how do I use Orleans on a platform that doesn't support JIT

**Comment by jsteinich** [comment]
The code generation can either be done at runtime or at build time via an MSBuild task (which could be done in a project outside of Unity).

Using the Orleans Client directly from a client is generally not recommended due to the amount of access it has to your servers. Typically an API is exposed that controls the amount of access. https://github.com/OrleansContrib/Orleans.Http is a way of doing that via http, but you could use whatever protocol you like.

**Comment by benjaminpetit** [comment]
As @jsteinich said, you should not expose the silo port to internet. I think [the documentation](https://dotnet.github.io/orleans/Documentation/resources/frequently_asked_questions.html#can-i-connect-to-orleans-silos-from-the-public-internet) isn't worded strong enough.

It is necessary to have a front-end API (HTTP, Websocket, ect.) that would be used by your IOS devices. Note that you can cohost silos and webapi in the same process using [the hosted client](https://github.com/dotnet/orleans/tree/master/Samples/3.0/AspNetCoreCohosting)

**Comment by GaLeGayGay** [comment]
Thank you all. I can finally communicate with Orleans in Unity
