### ISSUE TITLE
Subscribing to a stream from the oldest available message

### ISSUE THREAD

**Issue by fdbeirao** [dotnet/orleans#6541]
First of all, Thank you for Orleans! I have been having a blast exploring it and learning on how it differs from the traditional actor model/Erlang/Akka.net. The following is a question and not really an issue.

**What I wish to achieve**

I have a grain in my cluster which will write to a stream a bunch of messages. It can write them for hours, no issue.

What I wish is for a consumer to arrive later (minutes, hours) and be able to "catch-up" from as far behind as possible and then continue receiving new messages as they become available. I also do not wish to use EventHub, since I want to be able to run everything from my own docker-compose/kubernetes, and not dive into managed services this early. After some digging around I _believe_ MemoryStreams would be able to accomplish what I am looking for.

The consumer is not a grain. It is a SSE (server-side-events) endpoint powered by AspNetCore.

In my SiloBuilder I have configured 
```csharp
builder
.AddMemoryStreams<DefaultMemoryMessageBodySerializer>("MemoryStreamProvider", ConfigureMemoryStreams)
.AddMemoryGrainStorage("PubSubStore")
(...)

private static void ConfigureMemoryStreams(ISiloMemoryStreamConfigurator configurator) =>
  configurator.ConfigureCacheEviction(ConfigureCacheEviction);

private static void ConfigureCacheEviction(OptionsBuilder<StreamCacheEvictionOptions> options) =>
  options.Configure(ConfigureStreamCacheEvictionOptions);

private static void ConfigureStreamCacheEvictionOptions(StreamCacheEvictionOptions options) =>
  options.DataMaxAgeInCache = TimeSpan.FromDays(1);
```

On my cluster client I have:

```csharp
new ClientBuilder()
.AddMemoryStreams<DefaultMemoryMessageBodySerializer>("MemoryStreamProvider")
(...)
```

What I am trying to do in my endpoint/action is:

```csharp
var subscriptionHandle = await stream.SubscribeAsync(streamWriterObserver, new EventSequenceTokenV2(0)).ConfigureAwait(false);
```

I have observed the following exception when I tried this approach: `Item not found in cache.  Requested: [EventSequenceTokenV2: SeqNum=0, EventIndex=0], Low: [EventSequenceToken: SeqNum=637256091846275259, EventIndex=0], High: [EventSequenceToken: SeqNum=637256091846275266, EventIndex=0]`

I see the following in [the docs](https://dotnet.github.io/orleans/Documentation/streaming/streams_programming_APIs.html#rewindable-streamsa-namerewindable-streamsa): `A null token means the consumer wants to receive events starting from the latest.`

What I wish is sort of the opposite. I need a mechanism to signal to the stream "give me messages from as far back as you can, let me catch-up and remain subscribed to new messages".

PS: I am aware this could cause some kind of flacky message delivery, since I could be competing with the eviction policy. I am okay if I miss a few messages like I would see `[1,3,5,6,7,8]` because I took too long to process `1` so `2` had been evicted meanwhile, and same thing happened for `4`. That is okay for my use case.

Once again, thank you so much! 🙏🏻

**Comment by sergeybykov** [comment]
>What I wish is for a consumer to arrive later (minutes, hours) and be able to "catch-up" from as far behind as possible and then continue receiving new messages as they become available.

I don't believe there's a way to do this today. However, you could probably make it work by tweaking the provider code to interpret a special value of token as "rewind to the earliest event in cache".

I wonder what @jason-bragg thinks about it.

**Comment by jason-bragg** [comment]
I suspect that Sergey is correct about that a custom token could be introduced which signals the reading from the back of the cache, but I don't believe that alone will be sufficient without further changes to Orleans.

This issue is how the pulling agent interprets cache misses.  To help prevent services from falling over when they get in a bad state, such as large numbers of consumers getting far behind and throwing data not found (cache miss) exceptions repeatedly, on cache miss, the pulling agent jumps the cursor to the most recent data, electing to send the consumer a single cache miss for a large block of data, but giving it the opportunity to process the most recent data without interruption.  This design decision has always been controversial, and some services have requested that we skip only the item in question, so adding a config switch for this would likely be a welcomed change by the community.  Without such a change, assuming the cache had items 1-8 in it (from your example) the cache miss that occurs for event 2 would jump the cursor to the most recent data, so what a consuming grain would see is 1, cache miss, 9, not the desired 1,3,5,6,7,8.

Presuming a config switch were added for the pulling agent such that a cache miss triggered delivery of the oldest remaining data, and not the most recent, Sergey's suggestions 'could' work.  I say could because I've not explored this, thus lack confidence in that assertion.

It may be possible to introduce an IQueueCache decorator which intercepts the GetCacheCursor call and looks for a 'marker' token that selects the sequence token of the oldest item in the cache.  The persistent stream providers (such as azure queue streams, eventhub streams, memory streams, ...) should support customization of the cache, but I don't believe there is a common pattern for this yet (unfortunately) so you'll likely need to customize the adapter factory.

The risk of this sort of pattern, and why we've not seriously considered it in the past, are the reasons you've speculated.   It would result in cache misses being more common.  Further, referencing very old data is only expected if consumers aren't keeping up with processing, so the backpressure system would likely interpret cache reads of the oldest messages that way, which could trigger back pressure, reducing the rate events are read.

As for missing data, assuming the pulling agent were modified as described above, a 1,3,5,6,7,8 scenario could occur, but the consumer 'should' be notified of errors for each lost message, so application side mitigations may be possible.  For instance:

If OnNextError was wired up the consuming grain should see 1, cache miss, 3, cache miss, 5, 6, 7, 8.  Cache miss's are technically DataNotFound exceptions like the "Item not found in cache" exception you reported.  If a contiguous set of data is needed for accurate processing, the results could be thrown out on any cache miss, so the result of processing the 1,3,5,6,7,8 scenario could be the processing of the contiguous 5,6,7,8 block, but that would be a consumer side implementation detail.
