### ISSUE TITLE
Zookeeper based membership: frequently created client sessions.

### ISSUE THREAD

**Issue by leimou** [dotnet/orleans#655]
Hello,

After experimenting with Zookeeper based Membership table, I found that each time the membership table needs to be accessed, a new TCP connection to Zookeeper server is created, and closed after the access is done. I understand that the Znode created for each Silo is not ephemeral, and closing the connection doesn't affect anything. Just out of curiosity: Is there any special considerations of this? What about maintaining the connection to Zookeeper server instead of establishing the connection each time?

I'm relatively new to Orleans and Zookeeper, please forgive me if this is a dumb question. Many thanks for adding Zookeeper as an option for membership storage, our work will greatly benefit from this.

**Comment by shayhatsor** [comment]
@leimou, I've contemplated on this while developing the ZooKeeper membership implementation. My perspective was that I should not keep a persistent connection from each silo to the ZK service because [traffic to the table is very light](http://dotnet.github.io/orleans/Runtime-Implementation-Details/Cluster-Management). There's an overhead to keeping the connection open, on both server and client, therefore there's no correlation between the number of silos and the number of open connections. If you have any questions or suggestions I'll be happy to hear.

**Comment by gabikliot** [comment]
That's an interesting point.
I don't think reopening a socket to ZK on every request is indeed a big problem for now. The traffic is indeed light - by default we read once a minute. So every silo will open a socket to ZK once a minute. Should probably be fine.
Longer term it might be a worthy optimization - open a socket, cache it and re-use. If broken upon use, try to re-open once and if can't fail the operation.

When we use AzureTable for Membership table it uses Azure storage client library that uses REST API underneath. As per [here](https://convective.wordpress.com/2010/08/18/examples-of-the-windows-azure-storage-services-rest-api/), the Http connection is kept open  (`Connection: Keep-Alive`) and socket is reused.

@shayhatsor , is the code  to reopen sockets in the ZK client library or in `OrleansZKUtils`? I am almost sure it is in the ZK client library.  If it is indeed in the ZK client library it may be worth implementing longer term, sine this is a generic client, and the usage should apply beyond Orleans. How does Java client do that?

**Comment by shayhatsor** [comment]
An open ZK client, tries to keep an open connection to the ZK service as long as its "close" method isn't called. This is done in a background thread(or task) that's randomly trying to connect to one of the ZK servers. It allows the client to receive push notifications (using ZK watches) and to be always ready for action. When a connection is established, it is kept alive using heartbeats from client to server. The server will expire the session when the heartbeats stop. this also means that you can't just keep an open socket, the socket must be sending pings to the server. that's how the java and the c# client work.

When implementing the ZK membership I chose to close the connection because of relatively low traffic and because the implementation doesn't use ZK watches.
I can change the implementation to create one ZK client and reuse it. This can be done relatively easily in OrleansZooKeeperUtils. It can also be configurable, but I'm not sure we have enough real-world data to know if it's needed.
We are testing the current implementation in production and will fine tune as we gain more experience.
thanks @leimou for pointing this out.

**Comment by gabikliot** [comment]
:+1:

**Comment by leimou** [comment]
Thanks a lot for explaining. I'll have more tests and experiments. Again, thanks @shayhatsor for your work on Zookeeper.
