### ISSUE TITLE
Checkpoints for Event hub are not updated

### ISSUE THREAD

**Issue by drano** [dotnet/orleans#6581]
When my server is started, I can see data in checkpoints using by Event Hub (with offset is not zero).
Offsets are not updated after the first call.

My config:

```
                .AddEventHubStreams("eventhub", configurator =>
                {
                    configurator.ConfigureEventHub(ob => ob.Configure(options =>
                    {
                        options.ConnectionString = "XXX";
                        options.ConsumerGroup = "XXX";
                        options.Path = "XXX";
                    }));
                    configurator.UseAzureTableCheckpointer(ob => ob.Configure(options =>
                    {
                        options.ConnectionString = storageConnString;
                        options.PersistInterval = TimeSpan.FromSeconds(5);
                    }));
                    configurator.ConfigureStreamPubSub(StreamPubSubType.ImplicitOnly);
                })
```

**Comment by jason-bragg** [comment]
> Offsets are not updated after the first call.

I assume by first call you mean after the first checkpoint is written you don't see them updated in the 5 second interval you expect (and have configured).  Is this assumption correct?

**Comment by jason-bragg** [comment]
The partition checkpoints are written as events are purged from the message cache since they mark the start of the cache.  The interval is primarily used to throttle storage calls so we don't update the checkpoint on every cache purge, but it don't trigger a checkpoint update, cache purges do that.

A side effect of this behavior is that a newly acquired partition, either through silo startup or queue rebalancing, will not write a new checkpoint until sufficient messages have been read to fill the message cache and begin purging.  The default message cache stores 30 minutes of messages by ingestion time, and keeps them available for processing for at least 5 minutes.  These settings can be changed, but unless configured otherwise, no new checkpoints will be written for at least 5 minutes after startup.

**Comment by drano** [comment]
@jason-bragg Thank you for your response.
Yes, after 5 second interval, no update on checkpoint.

How to change these settings ? and how to force store checkpoints when cluster is shutdown ?

**Comment by jason-bragg** [comment]
To adjust cache eviction settings one could use ConfigureCacheEviction(..) on the stream provider configurator.

There is no way to force a write on shutdown, not out of the box anyway. To avoid reprocessing events, grains are expected to keep their own checkpoints for what they have consumed.  It is done this way because there are multiple streams in a partition, so a single partition checkpoint is insufficient.

As an example, if a silo came up and read events for 3 minutes (with default eviction settings) it's checkpoint would not move, so the next time it came up it would start reading from the same position in the partition.  However, any grains processing events should store the sequence token of the last event they processed with any results.  That token can be used upon restart to subscribe where the consumer left off, ignoring all events read between the partition checkpoint and the consumers sequence token.

If the silo was up for more than 5 minutes, it would start writing checkpoints in the configured interval.

**Comment by drano** [comment]
Thank you.
