### ISSUE TITLE
Is it possible to implement MySql persistent and cluster table without Procedure?

### ISSUE THREAD

**Issue by vrecluse** [dotnet/orleans#6587]
We are planning to migrate our data from MySQL to [TiDB](https://github.com/pingcap/tidb) in the future, because MySql is not good at scaling out when data grows, TiDB supports most parts of MySql driver, but without stored procedure.
Is it possible to replace the stored procedure  in .sql files with non-procedure version?

**Comment by sergeybykov** [comment]
I suspect it might be easier to 'fork' the ADO.NET provider code for that into a new provider, and specialize the code.

/cc @veikkoeeva who might have a better idea.

**Comment by veikkoeeva** [comment]
@vrecluse I do not think of a reason why not to do it if it is possible.

I do not remember a reason it would be make impossible. I think an easy way to test is:

1. Deploy tables as usual.
2. Change scripts so that they do not have stored procedures.
3. Test scripts by hand by just setting variables and let the scripts use them and see if there are errors.
4. Run through the tests.

I can do number 4 if using the test system becomes difficult. It should automatically pick up the scripts, create a test database, deploy the scripts and use them. If it is possible, I think we should make a PR.

Worth noting:
- Choosing https://github.com/mysql-net/MySqlConnector instead of the official connector improves performance.
- The MySQL script could probably be improved already now, but this applies also to script without procedures.

In general Orleans provider works so that it reads in the scripts that operate on the database (e.g. `INSERT`, `SELECT`, `UPDATE`, `DELETE`) by the identifier as seen when added to the table where they are read from. Then Orleans adds the information in parameters that it passes to the provider. So basically it treats the script and database as an opaque execution engine, a sort of analogue is JavaScript `eval` on scripts. So almost everything works except things like changing the input/out variables if the DB supports it.

**Comment by vrecluse** [comment]
> @vrecluse I do not think of a reason why not to do it if it is possible.
> 
> I do not remember a reason it would be make impossible. I think an easy way to test is:
> 
> 1. Deploy tables as usual.
> 2. Change scripts so that they do not have stored procedures.
> 3. Test scripts by hand by just setting variables and let the scripts use them and see if there are errors.
> 4. Run through the tests.
> 
> I can do number 4 if using the test system becomes difficult. It should automatically pick up the scripts, create a test database, deploy the scripts and use them. If it is possible, I think we should make a PR.
> 
> Worth noting:
> 
> * Choosing https://github.com/mysql-net/MySqlConnector instead of the official connector improves performance.
> * The MySQL script could probably be improved already now, but this applies also to script without procedures.
> 
> In general Orleans provider works so that it reads in the scripts that operate on the database (e.g. `INSERT`, `SELECT`, `UPDATE`, `DELETE`) by the identifier as seen when added to the table where they are read from. Then Orleans adds the information in parameters that it passes to the provider. So basically it treats the script and database as an opaque execution engine, a sort of analogue is JavaScript `eval` on scripts. So almost everything works except things like changing the input/out variables if the DB supports it. This is the reason of one set of code but different scripts for the different vendors besides that one may want to do per-deployment optimizations that may not make sense to others (e.g. in SQL Server change on in-memory tables, use compiled procedures and limit storage payload length, /cc @sergeybykov).

Ok, I'll try. After looking into cluster.sql and persistent.sql, I found that replacing stored procedure simpler than I thought.Thanks.

**Comment by sergeybykov** [comment]
@vrecluse Do you want to keep this issue open until you get the solution to work or you already got the answer you were looking for?

**Comment by vrecluse** [comment]
> @vrecluse Do you want to keep this issue open until you get the solution to work or you already got the answer you were looking for?

I think it's ok for now. Thanks, I'll reopen this issue if any question occurs when migrating.

**Comment by Jacktomyw** [comment]
Hey @vrecluse , I'm doing the same thing just like you but I got some difficulties when rewrite the procedure part of the script: I don't know how to transform the IF-THEN expressions. I tried to use google search to solve this but failed. Could you just teach me how to handle this?

**Comment by buzzers** [comment]
@vrecluse I've also recently been planning to migrate our system from MySQL to TiDB, but I'm not familiar with SQL stored procedures. Can I share your SQL script file?

**Comment by Jacktomyw** [comment]
@buzzers I've done such thing but I gave up using TiDB. So the script has not been checked in production environment. Just check it before using it. Hope this will help you.
我曾经做过类似的工作，但是这之后我放弃了使用TiDB，所以这份经过修改的脚本没有在生产环境下受到检验。如果您想要使用它，请在使用之前进行检查。希望这能帮到您。
[MySQL scripts.zip](https://github.com/dotnet/orleans/files/5032129/MySQL.scripts.zip)

**Comment by buzzers** [comment]
@Jacktomyw Thank you very much, we'll try to see if this works.

**Comment by veikkoeeva** [comment]
@buzzers If it works, it could be useful to submit to the repository so it can be used both with MySQL and TiDB.
