### ISSUE TITLE
PostgreSql - connection open timeout

### ISSUE THREAD

**Issue by debarisi** [dotnet/orleans#6607]
We are using Orleans from version 1.5, and thank you for the great work you do!

We have six servers in a cluster serving a significant number of requests in a multitenant environment.
We noticed that from time to time, when a connection to our DB needs to open, and we receive a timeout, not a command timeout, our node needs to be restarted.

After an open timeout, in a table `OrleansMembershipTable`, there are no suspects, `IAmAlive` field is regularly updated, but all our clients are unable to send requests to a node. 
All of them are failing with Failed to forward error.

We are hosting our Orleans servers in docker env. (a same issue we had without a docker) on Ubuntu 18.06 OS.
Before any grain call invoke, we are using `IIncomingGrainCallFilter` that is used for logging, DB open connection, save changes and rollback. All those actions are wrapped in try-catch.
For DB connection we are using Npsql.EnttyFrameworkCore.PostgreSQL and Npgsql  (4.1.3.1) nugets.

We are not collecting any detailed logs from our production servers as those issues happen every few days.
We will try to reproduce an issue in separate Repo and will come with more information.

Are you familiar with similar or exact issues with Postgresql?

Best,
Dean

**Comment by sergeybykov** [comment]
My recollection is that Npgsql had multiple issues with seemingly async calls actually blocking threads. I don't know if that issue has been fixed since. I wonder if you hitting those. If you can take a memory dump of a silo in that state, that could help shed some light.

What exact version of Orleans are you running? In general, 1.5 is a very old version that we don't really support. Even then, there were important fixes all the way through 1.5.10. I hope you at least run it. Obviously, an upgrade to a modern version (we just published 3.2.1) is strongly advised.
