### ISSUE TITLE
Is it possible to get cancellation token source for an already running grain?

### ISSUE THREAD

**Issue by KirillJK** [dotnet/orleans#6634]
Hello.
For example I have a grain like: 
``` 
public class GrainA : Grain, IGrainA
{
        public async Task LongWork(string message, GrainCancellationToken tc)
        {
            while(!tc.CancellationToken.IsCancellationRequested)
            {
                 Console.WriteLine(message);
                 await Task.Delay(1000);
            }
        }
|
```
The grain is initialized from a client code.
```
 var grain = client.GetGrain<IGrainA>("GrainA1");
 var tcs = new GrainCancellationTokenSource();
 await grain.LongWork("Hello!", tcs.CancellationToken);
```
If Client is down or a load balancer redirected call to an another client, then the cancellationTokenSource is lost. Is it possible to cancel running task on the GrainA? Can I get a copy of the CancellationTokenSource by Grain name from the orleans infrastructure ?
For example some sort of:
```
 var cts = client.GetCancellation<IGrainA>(
"GrainA1", //GrainId
nameof(IGrainA.LongWork)//Method name
)
 await tcs.Cancel();
```

**Comment by sergeybykov** [comment]
There's no built-in support for sharing cancellation tokens. While something like that could be added, I'm of the opinion that cancellation tokens are an anti-pattern here, and we made a mistake of adding `GrainCancellationToken`.

I think the right pattern is to add an explicit `Cancel` method to the grain interface and make the grain reentrant, so that it can process a cancellation call while awaiting another async operation..

**Comment by KirillJK** [comment]
Ok. Thanks. My two cents. I understand the idea of single threaded grain. But unfortunatelly it means there is no way to stop a running flow of synchronious operations if the calling context is lost. It's an antipattern due to the asynchronius concept and internal implementaion of the framework.  Wouldn't be better to keep one place with 1 bit concurrency in order to have possibility to stop synchronious process? I believe anyway people may overcome this limitation by trying to come up with a workaround that includes a critical section or db-sync

**Comment by sergeybykov** [comment]
I think it is important to stress a distinction here between a logically sequential operation/method and synchronous execution of code on a thread. I our experience, the vast majority of logically sequential operations take very little synchronous execution on a thread, and spend most of the time waiting for asynchronous dependency calls (IO and other services) with nothing to execute locally while waiting.

Non-reentrant (default) grains don't allow any other requests in while in that idle waiting state. That's why the `GrainCancellationToken` feature helps but in a clumsy way because the grain code needs to be running and periodically checking the token for it to work.

A reentrant grain though allows a cancellation call (or any other call for that matter) in while it is idle waiting for a dependency operation to complete. Unlike with `GrainCancellationToken`, it doesn't have to be cancellation and can also be a status or progress check call, for example. This will not work if the grain is busy executing a major computation synchronously on the thread. But like I said, the heavy compute cases are rather rare.

Reentrancy/interleaving requires a more careful handling of grain's state compared to the default non-reentrant case. That's the tradeoff one has to make of simplicity vs. power.
