### ISSUE TITLE
OrleansJsonSerializer failing with Orleans.MembershipTableData

### ISSUE THREAD

**Issue by pughua** [dotnet/orleans#6647]
I tried to configure Orleans.Serialization.OrleansJsonSerializer to SerializationProviders and started Silo wrong
Exception during Silo.Start
![11111](https://user-images.githubusercontent.com/780726/87297149-86e2b180-c53a-11ea-8787-649a974810b5.png)
![111121](https://user-images.githubusercontent.com/780726/87297159-8a763880-c53a-11ea-87ba-17a8668612b5.png)

**Comment by sergeybykov** [comment]
You are correct - `MembershipTableData` is incompatible with `OrleansJsonSerializer`, as I'm sure some other runtime types. Because of that, `OrleansJsonSerializer` cannot really be used today as the default serializer. `OrleansJsonSerializer` is being too aggressive  to return `true` from `IsSupportedType` unconditionally.

Depending on what you are trying to achieve with JSON, you might consider defining your own serializer class that would be more selective about what types it supports, and delegate the actual serialization calls to `OrleansJsonSerializer`. That way your serializer class would act as a thin wrapper on top of ``OrleansJsonSerializer`.

**Comment by pughua** [comment]
@sergeybykov 
Thanks, I've been able to serialize custom objects as you suggested.
