### ISSUE TITLE
Question: Regarding UseOrleans and IClusterClient

### ISSUE THREAD

**Issue by govenkat-ms** [dotnet/orleans#6730]
I see that the extension method UseOrleans enables the injection of IClusterClient through DI. Is this client already connected to all available silos, as in can it activate grains in all silos that are present in the membership table? Or do we have to explicitly call .Connect() to ensure that the connection is ready?

I'm asking this question so that I can effectively setup our K8s readiness probe to only accept requests when grains can be activated.

**Comment by alexrp** [comment]
See these sections of the documentation:

* https://dotnet.github.io/orleans/Documentation/clusters_and_clients/index.html#client-connectivity
* https://dotnet.github.io/orleans/Documentation/clusters_and_clients/index.html#dependency-injection

In your case, since you're calling `UseOrleans`, the `IClusterClient`/`IGrainFactory` in the DI container will be connected and usable out of the box.
