### ISSUE TITLE
Give StreamHandle a public identifier

### ISSUE THREAD

**Issue by onionhammer** [dotnet/orleans#675]
The workaround is to use gethashcode() to determine the StreamImpl's unique identifier, or something based on it, but it would be nice if the stream handle exposed a public identifier other than to the stream itself.

**Comment by gabikliot** [comment]
@onionhammer , what exactly do you mean by streamhandle?
Do you mean unique identifier for `StreamSubscriptionHandle`?
Or for `IAsyncStream`?
Where would you need to use such an identity? I am trying to understand the scenario.

**Comment by onionhammer** [comment]
When a grain is the consumer, on reactivation  it needs to know what is handle is in order to resume the stream

**Comment by gabikliot** [comment]
1) So you are talking about ` StreamSubscriptionHandle `?
2) Why the key is important/useful for you? Just so you can use something as a primary key to Azure Table?

**Comment by onionhammer** [comment]
Yes. The subscription handle, not the stream itself. 

Example scenario:
We have an event hub processor consuming events and pushing them onto a Orleans stream

We have several consumer grains, of different types, subscribed to the stream

When a message is passed to the Orleans stream, the grains are automatically reactivated because they are subscribed, but they won't receive things from the stream until they call resume on the stream handle.

The way we're getting the stream handle is by querying the stream for all open consumer handles, but there is no obvious way to differentiate between stream handles so an IGrainX doesn't resume an IGrainY's subscription handle.

I can't easily persist the stream handle itself with my storage providers because the stream handle impl class is internal

**Comment by gabikliot** [comment]
Ok, let me just first say that in general I am not against exposing the unique identifier.  I am just trying first to understand you usage pattern to make sure we are using it as expected.

The pattern you described is totally correct and OK to use: the grains are automatically reactivated, the need to resume on the stream handle, you query the stream for all open consumer handles and resume.

When you query the stream for all open consumer handles it will only give you back the handles for that grain. So it is not possible to for IGrainX to  resume an IGrainY's subscription handle, since each grain gets its own handle.
So the situation you are describing can only happen if you have multiple subscriptions to the SAME stream from the same grain. Is this your case? You subscribe multiple times to the same stream from the same grain? It is totally allowed, but is it in deed what oyu are doing?

As for persisting the handle : StreamSubscriptionHandleImpl is [Serializable]. That means you can serialize the StreamSubscriptionHandle with .NET binary serializer or with Orleans serializer (SerializatioManager) even despite the fact that the impl is internal.
Are you trying to serialize it with json and that does not work? I think it should work if you set Newtonsoft.Json.TypeNameHandling.All

**Comment by onionhammer** [comment]
Okay, IGrainX vs IGrainY thing is good to know. Using "GetHashCode()" has the same effect, I just think it would be nice to be able to distinguish between handles easily.

**Comment by gabikliot** [comment]
Its not just for IGrainX vs IGrainY. It is also for different grains of the same grain type (IGrainX key 5 vs. IGrainX key 7).

And just to be sure - you can serialize `StreamSubscriptionHandle`, like I described above, right?

**Comment by onionhammer** [comment]
I was able to serialize it, my issues came during *de*serialization. I didnt want to hack in a bunch of reflection to find expected types, so I avoided it altogether by only serializing an int (the hashcode).

**Comment by onionhammer** [comment]
So.. looking at the code for StreamImpl, how does it know which consumer is invoking 'GetAllSubscriptionHandles' (and only return the handles for 'IGrainX key 7' as you say?

**Comment by gabikliot** [comment]
Ohh, this is a bit complicated (maybe not so much). The call to 'GetAllSubscriptionHandles'  happens in the context of this grain and it knows to ask the PubSub for handles created by that grain.
https://github.com/dotnet/orleans/blob/master/src/Orleans/Streams/Internal/StreamConsumer.cs#L170

**Comment by gabikliot** [comment]
Closed via #679.
