### ISSUE TITLE
How to correctly expire old persisted state records?

### ISSUE THREAD

**Issue by highlyunavailable** [dotnet/orleans#6757]
I'm wondering if there is a recommended way to "expire" state. My use case is that I have an Orleans service that has people log in and do various things, then disconnect. I'm saving state to DynamoDB as part of their actions. If they don't log back in within, say, 24 hours, I want to clean up their persisted state.

I could use Reminders but they incur the code cost of storing the reminder/activating the grain just to clear its state. DynamoDB has a feature to [expire data using a TTL field](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html). I'm wondering if there is any way to directly expose a field of the record (let's call it `Expires`) to DynamoDB directly instead of serializing it into the BinaryState field so I can direct DynamoDB to use the Expires field as the TTL field.

I could of course add this to my own fork of the AWS storage provider but I'd rather use whatever the idiomatic Orleans way to do this is. Ideally I'd avoid using Reminders and use the DDB TTL feature, but if Reminders are the way, then I'd rather know that.

**Comment by sergeybykov** [comment]
I can't think of an idiomatic Orleans way of expiring state. Conceptually, it goes somewhat against the idea of grain virtually living forever. For example, if a grain like somehow managed to stay in memory for over 24 hours, but its state in storage vanished from underneath it, the in-memory copy of the state would become invalid.

I guess the idiomatic way would be to use a reminder and explicitly delete the state after the expiration period. But like you mentioned, that's not very practical in your case. I think extending the AWS storage provider to support state expiration is probably the better way to go. You could configure multiple instances of it with different expiration settings, and then map them to different types of states, so that expiration would apply only to the states that you need it to.

A more extensive way would be to add the notion of state expiration to the storage abstraction. But that's a bigger undertaking I think.

**Comment by highlyunavailable** [comment]
I'm not sure it's against the concept of a grain living forever. The classic "shopping cart" might be an example. Let's say you're using the [UserGrain](https://dotnet.github.io/orleans/Documentation/grains/grain_persistence/index.html) in the example of Persistence, and you chose to store a User in the Users DDB table and the Cart in the Carts DDB table. After some time, you may wish to clear a user's shopping cart to free up storage or make sure they don't have products you no longer sell. What I'm asking is similar to this - since the "cart" is a separate storage provider, I was wondering if I could use some DDB-level thing to clear it after a period of time.

A reminder certainly would be a more flexible way, simply because it would let me configure what is cleared or reset at a much more granular level than simply dropping all the data in a specific storage provider. It's unfortunately more expensive, since it costs Write Units, and I'll be seeing if I can put together a PR to do something specifically for AWS, but thanks for talking it over with me!
