### ISSUE TITLE
Silo: Access to GrainFactory outside Grain

### ISSUE THREAD

**Issue by Lesslimit** [dotnet/orleans#681]
I cannot find a way to create a Grain outside of Grains other than passing GrainFactory property as a dependency to all objects that would need to create a Grain, but are not derived from Grain base class.

**Comment by veikkoeeva** [comment]
@Lesslimit This is not currently possible. See an exchange of thoughts [on the Orleans Gitter channel](https://gitter.im/dotnet/orleans?at=55a94a6e854106d36bd1adfb).

**Comment by gabikliot** [comment]
@Lesslimit , if you need a `GrainFactory ` on the client, you have it available via `GrainClient.GrainFactory`. iIf you need it on the silo, as part of a grain code, then it is available as a property in the Grain base class. If you need it inside some other class that is used on the silo, than indeed the only way is to pass it around as a dependency. This is by design, to support DI and mocking.

**Comment by gabikliot** [comment]
You can also use this trick: https://github.com/dotnet/orleans/issues/626#issuecomment-124869361

**Comment by Lesslimit** [comment]
Thanks for your answers
