### ISSUE TITLE
[Question] How to properly persist grain reference.

### ISSUE THREAD

**Issue by Ilchert** [dotnet/orleans#6835]
Hello!

I am trying to write some generic code to store any grain reference into persistent storage, but I can't find documentation about it. 

Code:
```C#
class State
{
// GrainReference, Grain Identity property?
public ICallbackBaseInterface Callback {get;set;} // is it ok?
}


IPersistentState<State> _state;
public async Task Start(ICallbackBaseInterface callback)
{
// code to store callback reference?
 _state.State.Callback=callback;
await _state.WriteStateAsync();
}

public async Task OnActivate()
{
  // code to restore callback reference, if it exists. 
}

```
 

Thanks, Ilya.

**Comment by sergeybykov** [comment]
I would suggest to store grain IDs, not grain references, and "materialize" them back into grain references with `GetGrain()`.

**Comment by Ilchert** [comment]
Thanks for the answer! How to get the correct grain interface or grain type in this case? Imagine I have several grains that implement `ICallbackBaseInterface ` from the provided example?

**Comment by sergeybykov** [comment]
I assume `ICallbackBaseInterface` is a grain interface. Is that correct? If so, then you would call `clusterClient.GetGrain< ICallbackBaseInterface>(id)` to "materialize" grain references from IDs. Is that a problem?

**Comment by Ilchert** [comment]
In short yes, there are many grains, that implement `ICallbackBaseInterface`.
Let me show a little bit more complex example:

```//C#
public interface IOperationCallbackGrain : IGrain
{
     Task StateChanged(IOperationGrain operation, OperationState state);
}

public interface IOperationGrain : IGrainWithGuidKey
{
    Task Start(IOperationCallbackGrain callback);
}

public interface IOperation1 : IOperationGrain // there are many operations
{
}

public class Operation1:IOperation1
{
     private IOperationCallbackGrain _callback;
     Task Start(IOperationCallbackGrain callback)
     {
           // here I have to save callback grain to persistenet storage.
           _callback = callback;
           RegisterTimer(Do, null, TimeSpan.FromMinutes(1) , Timeout.InfiniteTimeSpan); // long polling operation. Use reminder instead.
      }
     private async Task PollData(object obj)
     {
          _callbackGrain.InvokeOneWay(p => p.StateChanged(this, OperationState.Completed));
     }
}

public interface ISomeGrain1:IGrainWithGuidKey, IOperationCallbackGrain 
{
}

public class SomeGrain1: Grain, ISomeGrain1 // the first grain, that uses IOperation1
{
   public override async Task OnActivateAsync()
   {
      await GrainFactory.GetGrain<IOperation1>(Guid.NewGuid()).Start(this);
   }

    public Task StateChanged(IOperationGrain operation, OperationState state)
    {
        // some code, that handles the result of the operation.
    }
}

public interface ISomeGrain2:IGrainWithGuidKey, IOperationCallbackGrain 
{
}

public class SomeGrain2: Grain, ISomeGrain2 // the second grain, that uses IOperation1
{
   public override async Task OnActivateAsync()
   {
      await GrainFactory.GetGrain<IOperation1>(Guid.NewGuid()).Start(this);
   }

    public Task StateChanged(IOperationGrain operation, OperationState state)
    {
        // some code, that handles the result of the operation.
    }
}
```

In this case, `IOperationCallbackGrain` is just the base interface of all grains, that can handle callbacks from long-running operations. And I can't get a grain reference by `GetGrain<IOperationCallbackGrain>`.

Thanks, Ilya.

**Comment by Lionhunter3k** [comment]
The default Orleans JSON serialization mechanism used by Table Storage, Blob Storage and other providers that are properly written will save the required metadata to persist grain references, even polymorphic ones, where there's is one grain interface for many grain implementations, as long as you make sure that the grain implementation has a marker interface to delimitate it from other grain implementations.

Behind the scenes, JSON.NET is used, with custom converters, that allow for this behaviour. I have saved grain references extensively in grain states, in my Orleans projects.

**Comment by Ilchert** [comment]
@Lionhunter3k thanks for the answer. So, can I just set grain reference into state object and save? 

```//C#
public class State
{
    public IOperationCallbackGrain Callback {get;set;}
}
```

**Comment by Lionhunter3k** [comment]
Yes

**Comment by sergeybykov** [comment]
Another option to consider - `ToParsableString()`/`FromParsableString()`.

**Comment by Ilchert** [comment]
Thanks to everyone for the answers!

**Comment by VincentH-Net** [comment]
@sergeybykov @Lionhunter3k 
Even though this issue was closed, I would like to revisit to learn if there are any downsides to including grain references in grain state. As compared to only including grain ID's in the state.

From debugging, it seems like when a grain's state is deserialized, and it contains grain references, that the state for the referenced grains is not deserialized at that time and they are not activated. Is this guarantueed behaviour in Orleans or does it depend on which providers / serializer are used?

Also I wonder about grain state versioning.
Will persisting grain Id's versus grain references in grain state make a difference in whether e.g. renaming a grain type / namespace will cause deserialization to fail?

**Comment by sergeybykov** [comment]
>Even though this issue was closed, I would like to revisit to learn if there are any downsides to including grain references in grain state. As compared to only including grain ID's in the state.

A serialized grain reference is larger in size than a grain ID, requires more cycles for serializing/deserializing, and provides no additional benefits over just storing the ID.

>From debugging, it seems like when a grain's state is deserialized, and it contains grain references, that the state for the referenced grains is not deserialized at that time and they are not activated. Is this guarantueed behaviour in Orleans or does it depend on which providers / serializer are used?

A grain reference is just a proxy object for the target grain. Until a call to the grain is made, it does not get activated (initialized). In that sense, it's a guaranteed behavior in Orleans because the runtime doesn't make call on grain references while they are being deserialized.

>Will persisting grain Id's versus grain references in grain state make a difference in whether e.g. renaming a grain type / namespace will cause deserialization to fail?

This is a valid concern. A grain reference includes a type code of the target grain class, and that type code by default is a hash of the full class mane. If you serialize grain references, and then rename the target grain class or its namespace, you'll need to override its type code, so that it stay unchanged.

There are other reasons why renaming types isn't a good idea. But narrowly speaking, persisting grain IDs instead of grain references helps avoid this kind of compatibility issue.

**Comment by VincentH-Net** [comment]
Thanks @sergeybykov for your clarification, very helpful!
