### ISSUE TITLE
Redis Grain Directory May Get Actors Stuck

### ISSUE THREAD

**Issue by ThiagoT1** [dotnet/orleans#6850]
Currently, if one or more Silos go down abruptly, and are no capable of Unregistering it's grains, the GrainAddress will get stuck.

This means any message to the same Grain in the future will fail, if the old Silo address is no longer reachable.

@benjaminpetit, could you please confirm that observation is correct?

If so, could we discuss strategies to unstuck the address? I would be willing to send a PR.

Thanks!

**Comment by benjaminpetit** [comment]
It should not happen, because _custom_ directory implementations (Redis and Azure Table are in this category) are used behind [CachedGrainLocator](https://github.com/dotnet/orleans/blob/3.4.0/src/Orleans.Runtime/GrainDirectory/CachedGrainLocator.cs#L70`), that does check if the entry is pointing to a dead silo, and will clean the entry from directory if needed.

Did you see this issue in a real environment?

**Comment by ThiagoT1** [comment]
> Did you see this issue in a real environment?

Yes. I'll try to list minimal repro steps and post it here.

Thanks!

**Comment by ThiagoT1** [comment]
Closing as not easily reproducing for now.

Thanks!
