### ISSUE TITLE
can stream as grain params

### ISSUE THREAD

**Issue by SarcoZ** [dotnet/orleans#6862]
my grain interface like below, stream length is 4k-128k, grain only resonse hello world, I test on local machine,but ops is 5000-15000, performance is not well, I think this may be related to serialization
1. any good idea can improve ops?
2. stream as response type,when to dispose it? framework auto dispose or I need dispose manual?

```
public interface ICatalogStorage : IGrainWithStringKey 
{              
      ValueTask<string> Storage(string bucket, Stream stream);
      ValueTask<Stream> GetStream(string path);
}
```

**Comment by ReubenBond** [comment]
I wouldn't try sending a stream as a parameter or a return value. The framework isn't going to recognize that as a stream, it will be treated as a POCO. It will send the entire thing in one go, assuming it's a MemoryStream, which can probably be serialized by the fallback serializer.

Poor performance is to be expected in that case.

**Comment by oising** [comment]
@SarcoZ Another thing to ensure is that you're compiling in Release mode before testing performance :) This actually has an enormous effect for Orleans...

**Comment by SarcoZ** [comment]
@oising  yes,I compile it release.thanks
@ReubenBond In small file storage scene,use stream which avoid serialized can get good performance,any good idea suport this?

**Comment by SarcoZ** [comment]
if use Immutable<Stream> or Stream as method response,when dispose? framewok can check response type,when response send compled,should auto dispose,now,I can not find an opportunity to dispose stream

**Comment by ReubenBond** [comment]
> if use Immutable or Stream as method response,when dispose?

Orleans will not dispose your response values for you - I wouldn't recommend a system which relies on deterministic disposal (such as pooling), since the framework won't be helping you there.

> framewok can check response type,when response send compled,should auto dispose,now,I can not find an opportunity to dispose stream

Why do you need to dispose the stream? Is it to return it to a pool? You could use other pooled types, too, such as `ArrayPool<byte>`, or `MemoryPool`.

> I think when all IIncomingGrainCallContext excute completed,the reponse send ok,then is an opportunity
in asp net core,when response is stream, after httpcontext end,will auto dispose
I hope that if use stream as reponse,not need serialization,that can be very fast and use small resource

To be clear, Orleans is not built for returning `Stream`. It makes sense in ASP.NET since it's HTTP and is naturally returning a stream of data back to the user. In Orleans case, you're not streaming data into a TCP connection, you're sending values (objects) between grains. To properly support data streaming, some design and implementation would be needed.

> I think about use Immutable<byte[]> as reponse,but that I need create a byte[], and read data ,memory need more,then rely on GC dispose, when access frequently, poor performance is inb this case

You could create a custom type and register a serializer for it. The deserializer can rent the object from the pool, and the serializer can return a rented buffer to the pool. The grain would also have to rent a buffer before sending it and the receiver would have to return it after using it. There is still no guarantee that the object will be returned to the pool. You may need to make the type finalizable to capture any cases where a message is lost (eg, due to a network partition).

**Comment by ReubenBond** [comment]
Closing for now, since I believe this question has been answered. Please feel free to open a new issue if there are additional questions or clarification needed
