### ISSUE TITLE
Reliable cluster membership

### ISSUE THREAD

**Issue by agidlund** [dotnet/orleans#6866]
Maybe a silly question, but I'm starting to play with Orleans and don't find this explicitly mentioned in the documentation.

When implementing reliable cluster membership management, e.g by using Sql Server, do all silo instances and clients need to setup their own database or should they all share the same database?

If this is mentioned in the documentation, please point me to where. Otherwise it would be a good clarification to add.

**Comment by veikkoeeva** [comment]
Not a silly question at all. We all have different backgrounds and learning to do that best happens when building or using something.

They should use the same database, since they should use the same membership tables.

Maybe this should be added to documentation. Do you have a link for the location and maybe wording in mind? I'm thinking I can walk through a PR if you want to make such or maybe add it if you don't want to. But would want to have a version that feels like makes sense for someone with this need. :)

**Comment by JorgeCandeias** [comment]
They all share the same membership provider and settings. That's how they are able to find each other. So, in the case of SQL Server, all silo instances will point to the same database and they all must have the same *ClusterId* and *ServiceId* settings. You can then spin up (or down) an arbitrary number of silos. As long as they connect to the same membership provider, they will find each other and talk to each other directly from there onwards.

One can mitigate this single point of failure via the appropriate means for the particular provider, if this is what you are concerned about. In the case of SQL Server, using the built-in [disaster recovery](https://docs.microsoft.com/en-us/sql/database-engine/sql-server-business-continuity-dr?view=sql-server-ver15) options. Note that an Orleans cluster will keep accepting work, even if the membership provider is down, so long as silos can talk to each other. Just no new silos can join the cluster as they will have no way to discover existing ones. When things are set up correctly, this allows for database failover to occur without users noticing anything due to membership failure.

**Comment by agidlund** [comment]
Thanks for quick replies. My guess was that they share the same database, but my doubts were just what @JorgeCandeias mentioned about single point of failure.
Thanks @veikkoeeva! I can make a try to formulate something and make a pull request of it. I will try myself, otherwise I'll contact you for some guiding

**Comment by veikkoeeva** [comment]
@agidlund Sounds like a plan. If there is something more that comes in your mind, let's make also that clearer. Also @JorgeCandeias knows this and many others, I think both of us are in this thread and you can discuss in https://gitter.im/dotnet/orleans. :)

**Comment by ReubenBond** [comment]
I believe the questions have been so I'll close this and we can open a new issue if there are further questions. Thanks, everyone!
