### ISSUE TITLE
Grain faulted state

### ISSUE THREAD

**Issue by jenyayel** [dotnet/orleans#692]
Trying to figure out what is the approach for the following scenario.

There is operation (async method) in grain which updates the state and the state persisted at the end. In case there is failure during state change (logical Exception) or while writing to storage, I want to "rollback". By "rollback" I mean:
- Either re-read the state from storage and throw exception, so the caller will be aware that operation failed
- Or kill (deactivate?) the grain

In first case there also possibility that the re-read state will also fail, which takes me to second approach. 

What is the best practice to handle faulted state of actors in Orleans?

Thanks.

**Comment by gabikliot** [comment]
Both are valid approaches. You can force activation to deactivate by calling `DeactovateOnIdle`. On the other hand, the 1st approach allows you a more fined grained and application specific error recovery.
We deliberately did not want to constrain the system to only do 1 or 2, and allow the app to pick its own.

We do have an open work item to treat eTag mismatch exceptions from the storage automatically. We will use strategy 2 - if the grain got eTag mismatch exception upon write, we plan to automatically deactivate this activation. The reason is that eTag mismatch exception basically means we got 2 activations of that grain, which is an error condition, and one of the activations should be deactivated anyway. But for other errors we leave it to the app code to handle.

**Comment by jenyayel** [comment]
I understand. For me, instead of figuring out how to rollback in each specific case, the simpler approach is just to deactivate the grain. Thanks for clarifying.
