### ISSUE TITLE
Storing custom object into RequestContext messes up my streams

### ISSUE THREAD

**Issue by robertvra** [dotnet/orleans#6934]
I used a custom class to store some info into the Context with RequestContext.Set and after this my streams stopped working without any notice, error or crash. 
I was able to use the stored info in all the grains where I needed this info. 

My current workaround is serialize the data of this object into json and then store the json string with RequestContext.Set.
When requesting the info I use RequestContext.Get and then deserialize the info. 
Now it works fine, but it took me hours to find the problem.

The code of the object:

    public class ActiveSession
    {
        public Guid ClientSessionId { get; set; } = Guid.NewGuid();
        public Guid SessionId { get; set; } = Guid.NewGuid();
        public string ConnectionId { get; set; } = "";
        public string ConnectionServer { get; set; } = "";
        public DateTime LastActivityUtc { get; set; } = DateTime.UtcNow;
        public EActiveSessionType Type { get; set; } = EActiveSessionType.NotSpecified;
        public ActiveSession(Guid ClientSessionId, string ConnectionId, string ConnectionServer, EActiveSessionType Type)
        {            
            this.ClientSessionId = ClientSessionId;
            this.ConnectionId = ConnectionId;
            this.ConnectionServer = ConnectionServer;
            this.Type = Type;
        }
    }
    public enum EActiveSessionType
    {
        NotSpecified = 0,
        WaitForVerification = 1
    }

**Comment by ReubenBond** [comment]
Hi @robertvra, are any logs emitted in relation to this? I would expect that deserialization fails because the type is not available on the receiver (Is there an upgrade occurring?)

You should mark all serializable types with the `[Serializable]` attribute and ensure that it's defined in an assembly which is available on all silos/clients (if clients are participating) and which has code generation installed.

**Comment by robertvra** [comment]
Hi @ReubenBond,

Thanks for your reaction!

I tried again, after upgrading all modules to the latest versions (for orleans... v3.4.1), but now with a new class (available for all silos/clients) class defined as follows, the project containing this class has Orleans.CodeGenerator.MSBuild installed :

    [Serializable]
    public class Test
    {
        public string MyValue { get; set; }
    }

I use a stream to send all logging to. A logserver picks it up and processes the logs.
In the grain I use this code:

            logger.Trace("Testpoint1");
            Test test = new Test() { MyValue = "some text" };
            RequestContext.Set("Test", test);
            logger.Trace("Testpoint2");

Testpoint1 is logged, Testpoint2 is not logged, (and all logging following concerning this call/context) is also not logged).
Other streams are also not working anymore, All other functionality in the program works as planned. The logging stream is also used by servers connected to  the silo. The logging they produce is processed. (other context of course).
When I write the log to the console, 1 line before before putting it on the stream with onNextAsync, the logging is written in the console. The stream receiver(s) just don't see any message on the stream.
When I remove the RequestContext.Set line, everything works. The problem is also not the deserializing, with the original class deserializing works as a charm. (only the streams fail)
No exception, no info in VS's "output" tab.

**Comment by ReubenBond** [comment]
`RequestContext.Set` only sets some internal `AsyncLocal` state, so that shouldn't cause the subsequent line to not be logged, since it runs no serialization/etc code and is unlikely to ever throw. I wonder what is going on here.
I will close this for now because the issue has been idle for some time, but if you or anyone else runs into a problem which you think may be related to this, please open a new issue which references this one
