### ISSUE TITLE
CodeGenerator.MSBuild does not respect [NonSerialized] attribute on base classes

### ISSUE THREAD

**Issue by peter-perot** [dotnet/orleans#6962]
When I have a base class `MyBaseClass` with a field `[NonSerialized] private string baseField` the serializer does not serialize the field `baseField` - that's okay.

When I derive `MyDerivedClass` from `MyBaseClass` the field `baseField` gets serialized which is a bug.

``` csharp
[Serializable]
public class MyBaseClass
{
    [NonSerialized] private string baseField;
}

[Serializable]
public class MyDerivedClass : MyBaseClass
{
    // field 'baseField' of base class get's serialized though it's marked 'NonSerialized'
}
```

**Comment by ReubenBond** [comment]
We have a test which specifically checks for this, so I wonder what's different in this case: https://github.com/dotnet/orleans/blob/7608c19c0480eb19eefa5f198003ccfc8e0a56c9/test/Grains/TestGrainInterfaces/CodegenTestInterfaces.cs#L190. I suspect that there is something else going on here, such as a different serializer is being used which doesn't respect `[NonSerialized]`. I'll close this for now since the serializer has been replaced for 4.0. Apologies for my slow response. If this is still an issue, please open a new issue which references this one.
