### ISSUE TITLE
AdoNet Clustering with multiple silos under the same host

### ISSUE THREAD

**Issue by ldsenow** [dotnet/orleans#6976]
Hi,

I am evaluating how we can adapt Orleans into our system. Following the tutorial and all working fine until I tried to run multiple silos under my local host. 

When I start/stop the silos,  I can tell the 'status' state is inaccurate in DB, I guess, due to I didnt shut down gracefully. So when a new silo is started, it will try to establish connections to other silos, however, some of them are dead already and it seems that the new silo will try forever. It generates a lot of errors.

If the above scenario happens, client side will also have issues as well. Client side may pick up one of the "dead" silo and tries to connect and crashes after that. I thought Orleans would handle this gracefully (e.g. exclude this specific silo for a while after multiple fails or pick another one).

Bellow is my silo setting

```
builder.UseAdoNetClustering((AdoNetClusteringSiloOptions options) =>
{
    options.Invariant = "System.Data.SqlClient";
    options.ConnectionString = connectionString;
})
.Configure<ClusterOptions>(options =>
{
    options.ClusterId = "dev";
    options.ServiceId = "HelloWorldApp";
})
.Configure<EndpointOptions>(options =>
{
    options.AdvertisedIPAddress = IPAddress.Loopback;
    options.SiloPort = new Random().Next(10000, 20000);
})
```

My questions

-  do we have a way to detect the dead silos and exclude them for a while or mark it as dead until it starts again?
-  When ClusterId, ServiceId, IP and Port are the same, why do we register a new member/silo in the db?

Hope hearing from you.

**Comment by benjaminpetit** [comment]
> do we have a way to detect the dead silos and exclude them for a while or mark it as dead until it starts again?

Orleans will ignore entries that were not updated after `IAmAliveTablePublishTimeout. * NumMissedTableIAmAliveLimit`. If you are using the default configuration, that would be `5min*2` so 10min. You could lower the `IAmAliveTablePublishTimeout` in your test environment...

Or if you redeploy a cluster after all previous silos are dead, you can use a new `ClusterId`. That would be the cleanest solution.

> I thought Orleans would handle this gracefully (e.g. exclude this specific silo for a while after multiple fails or pick another one).

It will, be it will take some time by default.

> When ClusterId, ServiceId, IP and Port are the same, why do we register a new member/silo in the db?

Because the silo isn't the same. It will not have the same activations and various information on it: that's why we include a generation number in the silo identity.
