### ISSUE TITLE
Consider keeping support for .NET Standard 2.0

### ISSUE THREAD

**Issue by jsteinich** [dotnet/orleans#6992]
...at least for Orleans.Core.Abstractions

I just noticed that https://github.com/dotnet/orleans/pull/6984 was merged in (sorry, didn't see the PR before now). This will potentially be a blocker from us being able to upgrade to Orleans 4.0. We currently share grain interfaces with a Unity project. This requires us to add Orleans.Core.Abstractions to the Unity project which is currently fine because of .NET Standard 2.0 targeting. Happy to explain further if helpful.

I say potential because we are currently building our own version of Orleans (because of https://github.com/dotnet/orleans/pull/6253), but it would be nice to get back on a released version at some point.

**Comment by ReubenBond** [comment]
Thanks for commenting, @jsteinich. Could you elaborate on how the grain interfaces are used in your Unity project?
 
Which pieces of Orleans does the Unity part of your app pull in?
Does that Unity project run on the client?
Would it be possible to separate the Orleans part & the Unity part?

**Comment by jsteinich** [comment]
We actually have an `IGrainFactory` implementation on the client. It just stores grains in dictionaries, but that allows us to have shared code that can lookup grains and act upon them. All the interfaces return `ValueTask` rather than `Task` since they are actually running synchronously on the client.

We run actions optimistically on the client using the same code that the server does so splitting apart would be a significant challenge.

List of types referenced:

- IGrain / IGrainWithX
- Grain
- IGrainFactory + interfaces that it references
- Transaction / TransactionOption

I hadn't seen that post before, but previous Unity posts made it sound like it might be a year after .NET 6 before they would support it + another year before it lands in LTS.

**Comment by dzmitry-lahoda** [comment]
standard seems like dead. it was not updated to all that nullability stuff and working with slices, etc.

**Comment by nkosi23** [comment]
@ReubenBond It is really unfortunate that you abandon your vision of enabling people to use Orleans wherever they need it. It is important to keep in mind that there is still no .NET Core support for many platforms while Mono is supported everywhere. As far as we are concerned all our servers and workstations use FreeBSD so we use Mono to run all our .NET workloads, and on a different note this has become our preferred .NET platform (we are familiar with the tooling, tuning options etc...), but really we have no choice anyway. 

[The community effort to port .NET Core to FreeBSD is a disaster](https://github.com/dotnet/runtime/issues/14537#issuecomment-859935802) because Microsoft really does not care and keep breaking things with commits full of linuxism every two weeks and people have to hunt for weeks to find what happened, while in 5 years we still haven't been able to get a production ready build pipeline (we haven't even been able to build a stable version). And this is despite the fact that this community effort is largely led by highly skilled Microsoft employees volunteering their time on week-ends. If they weren't there, even this slight hope wouldn't exist, but they are starting to get tired and quit.

My point is, you are sort of throwing your customers under the bus by dropping support for .NET Standard. We trusted you and invested time and effort in learning and integrating Orleans in our projects because you claimed a vision of letting us run Orleans everywhere. I feel you should wait at least until .NET Core has a proper Unix story before making such a move. As an aside, what is the point of .NET Standard, if even a core library like Orleans will not target it, and specialize on .NET Core. Removing support for .NET Standard should really be a 2030 move, not a 2021 move because right now, Microsoft does not even cares about Unix, they only care about Linux. I increasingly feel that ironically, .NET Core is making cross-platform .NET worse rather than better because of things like this.

**Comment by jsteinich** [comment]
https://github.com/dotnet/orleans/pull/7264 actually adds support back to parts of Orleans.
