### ISSUE TITLE
Using Jsonb as the type of payloadjson for PostgreSQL Persistence 

### ISSUE THREAD

**Issue by rizaramadan** [dotnet/orleans#7014]
Hi all, I've recently trying Orleans to build [RealWorld Backend](https://github.com/gothinkster/realworld) using PostgreSQL as the persistence storage, and I made a small changes to the [payloadjson](https://github.com/dotnet/orleans/blob/c3a0f70ab2ada30106ae9cdcbd6ad3f4ec8d4e49/src/AdoNet/Orleans.Persistence.AdoNet/PostgreSQL-Persistence.sql#L12)  using [JSON/JSONB](https://www.postgresql.org/docs/current/datatype-json.html) type instead of text and I think [it works](https://github.com/rizaramadan/Conduitorleans/blob/6a7d713e9fce34a1ce1e7058674535e95938115d/scripts/conduitorleans_all.sql#L491).
Would it be okay if I submit a PR to change those text into jsonb in Orleans repo?

**Comment by veikkoeeva** [comment]
@rizaramadan Firstly, it's OK to make such changes as per deployment. I would like to know if it is faster or slower or use less memory or what is the benefit of doing so. The reason I think is that PostgreSQL does some work when it transforms a string into JSON but Orleans as a system does not use this in any way. For Orleans the data is just a blob of data and as a convenience for use can use deployment specific features (e.g. JSONB).

So concluding from this, it seems load on database would incrase but is there an upside we could consider?

**Comment by rizaramadan** [comment]
@veikkoeeva thanks for the comment, I haven't done any benchmarking and it make sense to have that as the justification for the changes. I'll get back when its ready.

**Comment by rizaramadan** [comment]
I've tried benchmarking with `pgbench` on my local PostgreSQL 13, using custom the script (basically just insert 1 row and done), the findings are:
- `jsonb` is slower than text, difference is about by +-5% slower compare to text
- `jsonb` take more disk space, maybe because it also [contains the metadata](https://www.postgresql.org/message-id/0b22e3eaa74646828008000e5697dabf@USEPRDEX1.corp.kns.com)

So the only benefit of using `jsonb` is that it can be indexed, enabling us to search grains ids based on its properties or attributes. Is this strong enough to consider using `jsonb` instead of `text`?

**Comment by veikkoeeva** [comment]
@rizaramadan I would not make the change since:
- It has an observable performance impact.
- The impact is on a system that is not so easy to scale.
- Orleans system does not see the change.
- The user can make the change on per deployment basis if it's useful for some reason (e.g. joining to individual states by property, altering queries and indexing based on some property, using the payload as JSON in other queries and needing to do the change upfront).

To be clear, it's very much appreciable you went through the trouble and got some numbers. The numbers are useful since it's now documented and someone may want to do the change for other reasons. So, I myself don't oppose the idea as such. It's more like that as it can be done by deployment basis and otherwise it has a negative performance and consequently a cost impact on a component that is not the easiest to scale.

**Comment by rizaramadan** [comment]
@veikkoeeva I agree, it can be done on deployment basis, thanks.  I'm closing this issue.
