### ISSUE TITLE
GrainCallFilters contains unexpected null values when using Protobuf generated classes in grain interfaces

### ISSUE THREAD

**Issue by rikbosch** [dotnet/orleans#7031]
Hi,

We're experiencing an issue in using the orleans msbuild code generator in combination with the protobuf generator.
I've included a minimal repro here: https://github.com/rikbosch/orleans-grpc-repro

When building the project the Orleans codenerator logs the following warnings:

```
1>EXEC : warning : attempted to get TypeSyntax for unknown (error) type, "Event1". Possible reason: None. Possible candidates:
1>EXEC : warning : attempted to get TypeSyntax for unknown (error) type, "Event1". Possible reason: None. Possible candidates:
1>EXEC : warning : attempted to get TypeSyntax for unknown (error) type, "Event1". Possible reason: None. Possible candidates:
1>EXEC : warning : attempted to get TypeSyntax for unknown (error) type, "Event1". Possible reason: None. Possible candidates:
```
Looking at the binlog of

 the build, I see that the Orleans Codegenerator runs before the protobuf generator:
![image](https://user-images.githubusercontent.com/549975/111772404-19e3a080-88ad-11eb-9fb5-1955591aae6a.png)

Grain calls work just fine, but in GrainCallFilters, the context properties contain unexpected null values:

![image](https://user-images.githubusercontent.com/549975/111772756-852d7280-88ad-11eb-9def-ae3029110645.png)

![image](https://user-images.githubusercontent.com/549975/111772820-970f1580-88ad-11eb-8c13-5ce711f30423.png)

Is it possible to change the order of the orleans code generator? or somehow put the protobuf compiler in front of the orleans code generator?

We're using Orleans 3.4.1 with Microsoft.Orleans.CodeGenerator.MSBuild generator on .net 5

**Comment by BrianSakhai** [comment]
Not sure if you are still dealing with this, but I had this same issue, which I previously just worked around (I didn't know this was the cause). 

Due to running into more issues, I've ended up pulling all my proto files into a separate project and having that project responsible for generating the proto based classes, and then referencing that project, which will of course cause the code to be generated by the protobuf compiler prior to orleans.

On a similar note, the new record types can also cause the same warnings/issues as they also generate code, so I also put those in the same project.

**Comment by ReubenBond** [comment]
Hi @rikbosch, I recommend what @BrianSakhai suggested. You may be able to get the Orleans code generator to run after ProtoBuf's generator, but I am not sure exactly how. You might be able to find the right properties to set while looking through the msbuild files. If that requires a change to Orleans to allow specifying some ordering properties, we are open to that.
