### ISSUE TITLE
Save state without using the serialize attribute

### ISSUE THREAD

**Issue by nkosi23** [dotnet/orleans#7069]
Hello,

I am new to Orleans and have been digging into the documentation for quite a few weeks now to use it in a major project.

I have two questions:
1. Is it possible to use state persistence without marking the state class as serializable? (for example, using a custom storage provider)
2. Is it acceptable/safe to store state without using orleans' built-in state management infrastructure (for example by manually managing database repositories from inside a grain class)

To provide context, we practice Domain Driven Design, and as such thrive to keep the domain model pure of any infrastructure-related concern (such as attributes and annotation to help the persistence layer). Generally speaking, we cannot modify the domain model.

What we'd like to do is use Orleans in the following manner:

1. Create rich domain model classes, for example a User class
2. Create a generic MyApplicationGrain<T> class, having a property public T DomainObject { get; }
3. In the OnActivate method, load the DomainObject property from the database (or let the built-in state management mechanism do so)
4. In our application code, get a grain reference and then call directly MyApplicationGrain<T>.DomainObject.SomeMethodOrProperty() to run our business logic (without defining an interface at the Grain level)
5. Call a generic Save method on our generic Grain class

Our goal is to avoid duplicating the logic of the domain model in the Grain Layer (and similarly to avoid duplicating the data model in the Grain Layer by having to create custom persistence objects). With this approach the Grain layer would be very thin (only containing a single generic grain class).

What we'd still get from Orleans is concurrency management and the ability to assume that only one instance of the grain is loaded across nodes (which is a game changing guarantee), as well the ability to use advance features such streams and reminders in an opt-in manner.

So beyond the two questions above, I am also trying to understand if our intended usage would be an antipattern, and if Orleans was meant to be used in this manner.

Thanks you

**Comment by JorgeCandeias** [comment]
There is a lot to unpack here beyond two questions, especially if you are following DDD. Orleans fits in great with DDD and repositories by the way, we just need to understand where to put what. An appropriate project structure will help with this. I will assume you know how to use [Automapper](https://docs.automapper.org/en/latest/Getting-started.html) as it is very useful in keeping ddd business code clean.

> 1. Is it possible to use state persistence without marking the state class as serializable? (for example, using a custom storage provider)

Yes. When using the built-in persistence mechanism, Orleans will use whatever serializer it has configured. The default Orleans serializer can handle just about anything, however, it is not version tolerant, and therefore should not be used for built-in persistence beyond prototyping. It's best to attach a version tolerant serializer to Orleans such as protobuf-net.

The above said, on a larger project with ddd, you'll usually see yourself take full control of persistence and use a repository pattern instead of the built-in persistence mechanism. I'll talk about how to model this below.

> 2. Is it acceptable/safe to store state without using orleans' built-in state management infrastructure (for example by manually managing database repositories from inside a grain class)

Yes, as noted above.

> 
> To provide context, we practice Domain Driven Design, and as such thrive to keep the domain model pure of any infrastructure-related concern (such as attributes and annotation to help the persistence layer). Generally speaking, we cannot modify the domain model.
> 
> What we'd like to do is use Orleans in the following manner:
> 
> 1. Create rich domain model classes, for example a User class
> 2. Create a generic MyApplicationGrain class, having a property public T DomainObject { get; }

Note that Grains do not support properties, only async methods. Every call can potentially be remote, so synchronous property accessors don't make sense. Also note that thinking about grains as just "data objects" will make you unable to take the most benefit from Orleans. Grains are *agents*, meaning they have *agency*. They can both hold data and make decisions of their own accord, not only in response to external actions.

> 3. In the OnActivate method, load the DomainObject property from the database (or let the built-in state management mechanism do so)

That's totally fine.

> 4. In our application code, get a grain reference and then call directly MyApplicationGrain.DomainObject.SomeMethodOrProperty() to run our business logic (without defining an interface at the Grain level)

Grains *are* application code, and can, in fact, be the best place to put application logic, in a DDD-style Orleans based-system. Orleans fits in the business layer of DDD like a glove. Grains are great at representing DDD aggregates. Any API that the system supports can then act simply as a translation mechanism and nothing else. Same as with the repositories, they only exist to translate DTOs. Grains hold not only data but logic as well, in the very same place. You can get orders of magnitude in performance improvements when you keep the data and the code close together, as you remove the need to move about large amounts of data on the network. That is one of the great benefits of actor models. You can, of course, keep the application logic somewhere else and only use grains as blobs of data, but you won't get much benefit on that apart from the caching and concurrency handling effects and maybe the streaming features.

> 5. Call a generic Save method on our generic Grain class
> 
> Our goal is to avoid duplicating the logic of the domain model in the Grain Layer (and similarly to avoid duplicating the data model in the Grain Layer by having to create custom persistence objects). With this approach the Grain layer would be very thin (only containing a single generic grain class).

As noted above, that works fine, but you'll only get the caching and concurrency benefit of grains and not much else.

> 
> What we'd still get from Orleans is concurrency management and the ability to assume that only one instance of the grain is loaded across nodes (which is a game changing guarantee), as well the ability to use advance features such streams and reminders in an opt-in manner.
> 
> So beyond the two questions above, I am also trying to understand if our intended usage would be an antipattern, and if Orleans was meant to be used in this manner.

Your intended usage is totally fine. It's not so much as an *antipattern* as it is a *you can do so much more with it*.

Regarding DDD, here's a suggested project structure that follows [microsoft practices](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/ddd-oriented-microservice) for microservices. For the sake of example, let's assume your solution is named *MySolution*, only has one silo type, has a co-hosted api, and your data store is, say, SQL Server.

* *MySolution.Domain*: Holds your shared domain models and any shared auto-mapper profiles for domain-to-domain model conversions.
* *MySolution.Data.Abstractions*: Interfaces for the repositories. References *MySolution.Domain*.
* *MySolution.Data.Sql*: Sql Implementation for the repositories: References *MySolution.Data.Abstractions*.
* *MySolution.Database*: Sql database deployment project for the solution in this example.
* *MySolution.Grains.Abstractions*: Interfaces for the grains. References *MySolution.Domain*.
* *MySolution.Grains.Implementations*: Implementation for the grains. References *MySolution.Grains.Abstractions*
* *MySolution.MySolutionHost*: Host for the silo type and the co-hosted api. References *MySolution.Domain*, *MySolution.Data.Sql* and *MySolution.Grains.Implementations*.

Having such a project setup will help keep this clean. Further separations than these can make sense, depending on the solution.

Here's some pseudo-code for each DDD layer from the top of my head, based on the setup above and your *User* class. This doesn't include any DI boiler plate, error handling or auto mapper profiles.

*MySolution.Domain*:
```csharp
public record User(string Name, string Address);
```

*MySolution.Data.Abstractions*:
```csharp
public interface IUserRepository
{
    Task<User> GetUserAsync(string name);
    Task SetUserAsync(User user);
}
```

*MySolution.Data.Sql*
```csharp
internal record UserEntity(string Name, string Address);
internal class SqlUserRepository: IUserRepository
{
    /* .... */
    public Task<User> GetUserAsync(string name)
    {
        using var connection = new SqlConnection(_options.ConnectionString);
        var entity = await connection.QuerySingleOrDefaultAsync<UserEntity>("dbo.GetUser", new { name }, /* .... */);
        return _mapper.Map<User>(entity);
    }
    public Task SetUserAsync(User user)
    {
        using var connection = new SqlConnection(_options.ConnectionString);
        var entity = _mapper.Map<UserEntity>(user);
        await connection.ExecuteAsync("dbo.SetUser", entity, /* ... */);
    }
}
```

*MySolution.Grains.Abstractions*:
```csharp
public interface IUserGrain: IGrainWithStringKey
{
    Task<User> GetAsync();
    Task SetUser(User user);
    Task SetAddressAsync(string address);
}
```

*MySolution.Grains.Implementations*
```csharp
internal class UserGrain: Grain, IUserGrain
{
    private string _name;
    private User _user;
    override async Task OnActivateAsync()
    {
        _name = this.GetPrimaryKeyString();
        _user = await _repository.GetUserAsync(_name);
    }
    public Task<User> GetAsync() => Task.FromResult(_user); /* this is caching at work */
    public async Task SetUserAsync(User user)
    {
        if (user.Name != _name) throw new InvalidOperationException();
        await _repository.SetUserAsync(_user);
        _user = user;
    }
    public async Task SetAddressAsync(string address)
    {
        if (_user is null) throw new InvalidOperationException();
        _user.Address = address;
        await _repository.SetUserAsync(_user);
    }
}
```

* *MySolution.MySolutionHost* or wherever the api is:
```csharp
public record UserApiModel(string name, string address);
public async Task<ActionResult<UserApiModel>> SomeApiMethodToGetTheUserAsync(string name)
{
    var user = await _factory.GetGrain<IUserGrain>(name).GetAsync();
    var model = _mapper.Map<UserApiModel>(user);
    return Ok(model);
}
public async Task<ActionResult> SomeApiMethodToOverrideAUser(UserApiModel model)
{
    var user = _mapper.Map<User>(model);
    await _factory.GetGrain<IUserGrain>(name).SetUser(user);
    return Ok();
}
public async Task<ActionResult> SomeApiMethodToSetTheUserAddressOnlyAsync(string name, string address)
{
    await _factory.GetGrain<IUserGrain>(name).SetAddressAsync(address);
    return Ok();
}
```

The example above uses three layers of models:
* Business models in *MySolution.Domain*. The shared business models, that every other layer knows about.
* Entity models *MySolution.Data.Sql*. These exist for the sole purpose of representing data in the format of the chosen data store, hence why they are *internal*. Automapper is used to convert back and forth between business and entity models as needed.
* Api models in *MySolution.MySolutionHost* (assuming co-hosting). These exist for the sole purpose of representing data in the format of the public api and also to mitigate the probability of accidental exposure of sensitive data in the business models. Automapper is used here as well.

Phew, that went longer that I expected. Let me know if you have any other questions.

**Comment by nkosi23** [comment]
Thank you so much, I cannot state how grateful I am for your comprehensive answer, this was massively helpful. I have even just made a prayer for you so that your life is blessed. Thank you again
