### ISSUE TITLE
The GrainReference in the GrainState should be binded to the GrainRuntime

### ISSUE THREAD

**Issue by linluxiang** [dotnet/orleans#7074]
The GrainFactory.BindGrainReference should be called in the OnActivateAsync of PubSubRendezvousGrain.

https://github.com/dotnet/orleans/blob/10af0f4af588cd4aa45cb3e250dfbffa389d59c7/src/Orleans.Streaming/PubSub/PubSubRendezvousGrain.cs#L49

**Comment by ReubenBond** [comment]
@linluxiang BindGrainReference should be called by the GrainReference serializer

**Comment by linluxiang** [comment]
@ReubenBond  Will the GrainReferenceSerializer be called that PubSubGrainState instance is stored in the database?

And I've found another problem related to this serde problem.

The Consumer property at this line below is null after the PubSubSubscriptionState instance is deserialized from storage.

https://github.com/dotnet/orleans/blob/main/src/Orleans.Streaming/PubSub/PubSubSubscriptionState.cs#L37

The consumerReference must be converted to IStreamConsumerExtension manually.

The producerReference has the same problem.

**Comment by ReubenBond** [comment]
Yes, the serializer should be called when retrieving the grain's state from the database. If you were using the Redis storage provider, that was broken until the Orleans.Redis v3.2.0 release (released today). Apologies for the slow response. I believe this issue is likely fixed so I will close now. Please open a new issue or message me directly on Gitter if this is still an issue and we can investigate further.
