### ISSUE TITLE
Can we configure orleans so that SiloHostedService runs after other IHostedServices?

### ISSUE THREAD

**Issue by SebastianStehle** [dotnet/orleans#7110]
Hi,

when you use a simple setup like this

```
 public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseOrleans(...)
                .ConfigureWebHostDefaults(builder =>
                {
                    builder.UseStartup<Startup>();
                });
```

The SiloHostedService  always runs first. Before other services. It is a little bit strange, because when you have a grain with a timer it might start before other services implementing IHostedService are configured.

How can I configure Orleans to run last?

**Comment by nkosi23** [comment]
After digging into the source code I couldn't find an obvious configuration option to solve this, however a possible workaround may be to [register a silo-wide filter](https://dotnet.github.io/orleans/docs/grains/interceptors.html) checking that all your services are running, and if not discarding the call. Once services are started, you can then cache the result of the check so that the filter has no footprint on your workload.

Otherwise, a simpler and probably better solution - if this is an option for you - may be to split your services into multiple programs/executables, so that you have an easier time starting them in the right order. I tend to think that as soon as your Silo depend on an external service, these services should probably be started in separate processes. Co-hosting should probably be reserved for the simplest scenarios because it looks quite easy to get lost in circular runtime dependencies.

**Comment by SebastianStehle** [comment]
In our case my application is a broker for IOT messages which has several dependencies to function properly:

1. It listens on 3 ports to accept different protocols.
2. It connects to kafka
3. it connects to a DB
4. it Connects to a mqtt cluster 
5. It connects to a xmpp cluster 

All these connections are implemented as IHostedService for initialization (is there a better interface). The idea is to fail early.

There is a critical bug in our case when Orleans starts too early, but I think it would be easier of Orleans can just be registered with "services.AddOrleans()".

We use autofac and the workaround is this:

```
containerBuilder.Register<IEnumerable<IHostedService>>(c =>
                {
                    var services = c.Resolve<IHostedService[]>().ToList();

                    var orleans = services.Find(x => x.GetType().Name == "SiloHostedService");

                    // Ensure that orleans runs last.
                    if (orleans != null)
                    {
                        services.Remove(orleans);
                        services.Add(orleans);
                    }

                    return services;
                });
```

**Comment by krasin-ga** [comment]
Hosted Services are started in order they were registred, so in theory you can just place  .UseOrleans(...) after .ConfigureWebHostDefaults(...)
