### ISSUE TITLE
Question: What is the execution model of IGrainObserver methods?

### ISSUE THREAD

**Issue by zeinali0** [dotnet/orleans#7112]
According to [docs](https://dotnet.github.io/orleans/docs/grains/reentrancy.html) :

> Grain activations are single-threaded and, by default, process each request from beginning to completion before the next request can begin processing.

**The question is:** Does same behavior true for `IGrainObserver `? Or `IGrainObserver ` execution is not limited to a single thread.
If it limited to single thread is there any way to change it?

**Comment by ReubenBond** [comment]
Great question, @zeinali0. This is something which needs documentation.

`IGrainObserver` implementations which are registered by calling `IGrainFactory.CreateObjectReference<T>(IGrainObserver obj)` execute requests one-at-a-time with no interleaving. You can see the implementation of that behavior here: https://github.com/dotnet/orleans/blob/2259e3097abcc457b210bcd8799568dce26361d4/src/Orleans.Core/Runtime/InvokableObjectManager.cs#L194

I will keep this issue open until this explanation appears in documentation

**Comment by zeinali0** [comment]
Does `[AlwaysInterleave]` attribute change the execution model?

**Comment by ReubenBond** [comment]
No, there is no way to customize the interleaving of those calls. If the result of the call is not important (eg, a void method) then you could handle the request in the background by calling Task.Run.

What is your scenario and what are you intending to achieve?

**Comment by zeinali0** [comment]
I gonna scale SignalR in an Efficient way.
**Current way (which I think is in-efficient) is**:  I have UserGrain, GroupGrain and ClientGrain.
On side of `Hubs` each connection would subscribe to these Grains if it need. For example if there be 10 connection on same node at a group then there would be 10 `IGrainObserver` subscribed to that grain. so if we call to that grain to send message to your observers it would send it 10 time (probably over network) while all connection are in one node.

**What I gonna achieve is**: Create one `IGrainObserver` per node (and per hub) then that node would subscribe to that GroupGrain if it had 1 or more connection of that group then GroupGrain would deliver message only once per node not more (message would contain group name) and the node will do the other by itself as it knows the group name. But i'm not sure the current execution model of `IGrainObserver` would be bottleneck in this model or not Since there could be thousands of group and all are sending messages to one `IGrainObserver`.

**Comment by ReubenBond** [comment]
I have been working on updating samples and one of them may be relevant to you: https://github.com/ReubenBond/orleans/tree/update/samples/Samples/GPSTracker

The GPS Tracker sample uses SignalR. There is an `IGrainObserver` which has an instance of `IHubContext<LocationHub>` which it uses to broadcast messages to clients: https://github.com/ReubenBond/orleans/blob/1ce09c90c2b20ea3ca8586e2e4dd3d55190de3f2/Samples/GPSTracker/GPSTracker.Service/Grains/RemoteLocationHub.cs#L11

Please take a look and provide feedback on how the sample documentation could be improved. The sample takes some shortcuts which would hurt scalability but it should still be useful for you. There is a singleton `PushNotifierGrain` for example, whereas you might want to have multiple of those, or potentially make that a regular (non-grain) singleton service registered in DI. `HubListGrain` is also a singleton, but that should be fine since there should be fairly low load on it and it holds minimal data.

**Comment by zeinali0** [comment]
Sorry, Why `RemoteLocationHub`(s) just don't subscribe to `PushNotifierGrain` directly (like observer sample in orleans docs) and we used a `HubListGrain` in middle?

Another thing I couldn't find in documentation was difference between Streams and Observers. In many situation they are like each other (You observe a Grain is like You subscribe to a stream) and I even saw some users think Streams are replacement for Observers.
Something like when Streams are good to use and when Observers are.

Thanks for answering. I thought the example help me out find a way, I can create one `IGrainObserver` per User/Group on each node so that would cause no pressure on a single `IGrainObserver` and also we would not send same message over network for same node multiple time.

**Comment by ReubenBond** [comment]
You could certainly merge `PushNotifierGrain` and `HubListGrain`, or take the approach I mentioned and make `PushNotifierGrain` a regular service instead of a grain. Either way is fine.

Streams are for reliable, in-order processing of messages with decoupling from the producer and the consumer. Observers are for direct communication and do not offer reliability guarantees (messages are not persisted to Azure Event Hub, for example). You can often use Streams in place of Observers. I agree that some documentation on when to use one or the other would help.

You can create an `IGrainObserver` per user/group on each node if you like (is each user connecting to multiple nodes each?)

Are you seeing pressure on your `IGrainObserver`s?

**Comment by zeinali0** [comment]
> is each user connecting to multiple nodes each?

Yes as users can have multiple client so same user with 2 different client could be on multiple node.

> Are you seeing pressure on your IGrainObservers?

Yes I think But I'm not sure.
I guess there would be pressure if I use single `IGrainObserver` per node and it subscribe to thousands Grain.

**Comment by zeinali0** [comment]
Sorry just one more question:
Does creating multiple `IGrainObservers` on multi-core machine has any advantage?

**Comment by ReubenBond** [comment]
Yes, multiple `IGrainObserver` instances can execute in parallel.

**Comment by ReubenBond** [comment]
Fixed in https://github.com/dotnet/orleans-docs/pull/38
