### ISSUE TITLE
How to Extend State

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#713]
This is probably a common question, but could not find any similar entry.
Today I had to delete the State table, after adding properties to the grain state.

It is clear that the serializer needs a strong data contract, but either I did something wrong or there is no path for evolution.

Suggestions, Questions:
1) Don't support reorder, change of types or delete fields, but support appending new fields without breaking. As an example, BLE protocol uses a memory serializer that supports flexible, extensible fields. (If this is interesting I am happy to explore implementation)
2) Be tolerant for corrupted state, the silo crashed or stop responding after grains broke the state signature. What I saw was the following message from the client:
Orleans.Runtime.OrleansException: Could not find any gateway in Orleans.AzureUtils.AzureGatewayListProvider. Orleans client cannot initialize.
Note: After deleting the state table and recycle roles, everything started to work, but I lost state
3) Suggest best practices approach for versioning the state and support evolution

**Comment by gabikliot** [comment]
@ukluk , in general you are correct: the persistent state evolution story in Orleans is currently not very advanced.
 
But lets look specifically into it:
1) If we are talking about **application grain state** that this actually **is** supported, indirectly, via storage providers. One can write any storage provider and inside it deal with state schema evolution. The AzoreTable storage provider that we include by default in Orleans is not doing that, but this is merely since it is more like a sample. It is not the most advanced or feature rich storage provider. You can write your own, that will support thing like you mentioned: delete fields,  appending field, what ever. You can be tolerant to corrupted applications state there, in any way you want to.

2) **Runtime state**: we definitely need to be very careful about changing runtime state behavior and make it version tolerant. In general I think we are pretty OK on that, but could be better. Our internal runtime state changes very infrequently. For example, the membership format did not change for a while, so is reminders. And when we do change it, we try to make it backward compat.

As for the exception of "Orleans.AzureUtils.AzureGatewayListProvider. Orleans client cannot initialize.", I a not sure it was necessary related to storage format change. Unless the old version was 0.9, prio to 1.0, which was released in January.
