### ISSUE TITLE
AddGatewayCountChangedHandler from  default IClusterClient(InternalClusterClient)

### ISSUE THREAD

**Issue by sunliusi** [dotnet/orleans#7158]
IClientBuilder support AddGatewayCountChangedHandler. 

What should I do with the default  IClusterClient(InternalClusterClient)?

**Comment by ReubenBond** [comment]
@sunliusi the internal cluster client does not connect through a gateway, so the concept of a gateway count change handler isn't applicable. What are you using the handler for?

**Comment by sunliusi** [comment]
InternalClusterClient，Whether it means to connect to the current local cluster？

I want to initialize Grain when Silo starts，Reinitializes when the cluster node changes

**Comment by ReubenBond** [comment]
Ok, in that case I would recommend you create a [`BackgroundService` (see `IHostedService` .NET documentation)](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-5.0&tabs=visual-studio#backgroundservice-base-class) and register it *after* calling `.UseOrleans()` since services are started in registration order and this ensures that the silo is started and connected to the cluster before starting your service.

In that `BackgroundService` class, you can inject `IClusterMembershipService` (call it `_clusterMembershipService`, for example) and in its `ExecuteAsync(CancellationToken)` method, have an an async `foreach` loop to enumerate over `_clusterMembershipService.MembershipUpdates`. Each time you get a new value from that collection, you can perform your initialization/reinitialization action. You can also pass the `CancellationToken` to the enumeration so that you can terminate your service during shutdown.

Here is an example of what I mean:

``` C#
public class MyBackgroundService : BackgroundService
{
    private readonly IClusterMembershipService _clusterMembershipService;
    private readonly IGrainFactory _grainFactory;
    private readonly ILogger<MyBackgroundService> _logger;

    public MyBackgroundService(IClusterMembershipService clusterMembershipService, IGrainFactory grainFactory, ILogger<MyBackgroundService> logger)
    {
        _clusterMembershipService = clusterMembershipService;
        _grainFactory = grainFactory;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var myGrain = _grainFactory.GetGrain<IMyGrain>(someKey);
        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await foreach (var update in _clusterMembershipService.MembershipUpdates.WithCancellation(stoppingToken))
                {
                    await myGrain.InitializeAsync();
                }
            }
            catch (Exception exception)
            {
                _logger.LogError(exception, "Exception processing membership updates");
            }
        }
    }
}
```

**Comment by sunliusi** [comment]
Great, it works. @ReubenBond thanks
