### ISSUE TITLE
Question: Migrating stream providers

### ISSUE THREAD

**Issue by benthepoet** [dotnet/orleans#7164]
Currently we use AWS SQS for persistent streams in our and we're going to be switching over Azure Event Hubs. We're trying to find a migration strategy that will allow us to do the following while live migrating.

* Read remaining messages from SQS
* Read new messages from Event Hubs
* Write new messages to Event Hubs

Ideally would like to find a solution that allows us to have multiple readers from different providers like this (not long-lived, just until the old queue is cleared out) without changing the stream provider name that is referenced in our grains. Below are the approaches we've come up with.

1. Implement a custom stream provider that allows reading from one-or-more named stream providers and writes to one. This seems like the most complicated option and not really worth the effort.
2. Implement a hosted service that operates outside of Orleans and directly pulls any remaining messages from SQS and pushes them to Event Hubs.
3. Use some kind of interceptor/extension to proxy reads from both stream providers?

Are there any tricks we could take advantage of to do this easily? If not, I'm thinking that the second one probably sounds like the most reasonable solution.

**Comment by nkosi23** [comment]
I am by no mean an authority on Orleans, but since there has not been an authoritative answer since you posted your question just wanted to add my 2 cents in case it is helpful.

If I were you, I'd go with option 2 as well, it is the simplest and probably the most architecturally sound solution (the single responsibility of the migration is encapsulated in clean independent component). It is also the most transparent and the less risky (you do not dependent on the hazards of the Orleans runtime which could make certain subtle assumptions that may make your life more difficult).

**Comment by ReubenBond** [comment]
I agree with @nkosi23 - and thank you for answering. I'll close this, since there has been no follow-up to @nkosi23's response. We can re-open and move to discussion if someone wants.
