### ISSUE TITLE
Silo Stopped and remote client disconnected when run on Asp.Net Core hosted by IIS

### ISSUE THREAD

**Issue by dannypang** [dotnet/orleans#7183]
The Silo would stopped and need to restart after about 5 minutes. The only way to re-start it is to send a http request to the co-hosted website on IIS. The log is attached with internal IP masked.

[stdout_20210803230949_5108_error.log](https://github.com/dotnet/orleans/files/6927838/stdout_20210803230949_5108_error.log)

**Comment by ReubenBond** [comment]
Orleans never shuts itself down (though it will *fast kill* the process in some cases, that is not what is happening here). Something external is telling your application to shut down. The important line in your log is this (originating from the Microsoft.Extensions.Hosting package):
``` 
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```
That tells us that something told your application to stop. My initial hunch is that IIS is configured to stop the application because it has not received a request recently. I would look into how to configure IIS to prevent that behavior.

**Comment by dannypang** [comment]
Thanks Reuben, I think I've found the culprit again. There is a setting in IIS which would shutdown the website due to inactivity. In my case it is set to be 120 seconds (5 minutes). I followed the link below and found there is another variable in my IIS' advanced setting under Limits; the variable "Connection Time-out(seconds)" and I set it to be "0" and that would serve the trick to not kill my poor Silo. 

https://stackoverflow.com/questions/35993968/how-to-prevent-iis-from-shutting-down-web-site-when-not-in-use

**Comment by dannypang** [comment]
Actually, I am too quick to rejoice, my silos just get killed again. This time is longer than 5 minutes. When you get a moment, can you continue to look for how to configure IIS please?

**Comment by ReubenBond** [comment]
I can't help you with IIS configuration, sorry

**Comment by dannypang** [comment]
Never mind, thanks a lot for your help. I will continue to research this issue.

**Comment by ReubenBond** [comment]
Good luck, @dannypang, I hope you find the answer without too much hassle

**Comment by ReubenBond** [comment]
I'll close this for now, since it is an IIS issue, unrelated to Orleans
