### ISSUE TITLE
[Question] - Same silo deployment for associated grains

### ISSUE THREAD

**Issue by sheeri185adidam** [dotnet/orleans#7206]
I am implementing a game application using orleans. For every instance of the game, I have `GameGrain`, `PlayerGrain `and `WeaponsGrain`. `GameGrain ` is keyed using a GameGuid. `PlayerGrain `is keyed using GameGuid+PlayerGuid and `WeaponsGrain `is keyed using GameGuid. I could potentially have hundreds of instances of games running. I want to implement a placement strategy that enables for any game instance i.e. `GameGrain `the associated `PlayerGrain `and `WeaponsGrain `to be activated on same silo.

Hashbased placement strategy could achieve something like this but that doesn't guarantee same silo placement because silos could go offline in a cluster. 

Wondering if guys have any suggestions?

**Comment by nkosi23** [comment]
The difficulty here is that you are interested in an implementation detail that you shouldn't be interested in as Orleans is supposed to take care of that for you. What you would need is being able to override the PlacementService.GetCompatibleSilos(PlacementTarget target) method to alter the definition of what is is a compatible silo. Right now the only discriminant is whether or not your grains are versioned and if the silo has the right version of the grain it is deemed compatible. But this class is marked internal as users are not expected to be interested in this level of implementation details.

But even if the wasn't internal, while your id generation scheme allows you to have convenient access to the id of the game grain, the Placement runtime has no API allowing you to know which grains are currently activated in a Silo. You are not supposed to be interested in the content of individual silos, this is out of intended usage.

Once this is said, what you could do is segment your silos in subnetworks and  create a variation of the HashBased placement strategy (since the placement runtime gives you have access to the addresses of compatible silos). This would allow you to ensure that a particular game id is only serviced by a particular silo.

However, once you have done that, keep in mind that you will have no way to load balance the silo under heavy load (which is one of the key benefits of using Orleans). And if you want to add this capacility, you are back to square as this is exactly the behavior of built-in placement strategies.

I strongly feel that you do not actually want to do that. Just ensure that your silos are all based in the same data center and latency shouldn't ever be an issue. Lans are very fast these days. I have a sense that this may be an unnecessary optimization concern. The magic of Orleans is that it takes of that and many other things extremely well.

**Comment by sheeri185adidam** [comment]
@nkosi23 The more I think about this now the more I agree with you. I am leaning towards _prefer_ to have this placement. I am thinking to write a custom placement director that does the following. It will to some extent place these grains on same silo but if not, not a big deal. 

```
public Task<SiloAddress> OnAddActivation(PlacementStrategy strategy, PlacementTarget target,
            IPlacementContext context)
{
	var allSilos = context.GetCompatibleSilos(target).OrderBy(s => s).ToArray();
	var key = GetTargetPrimaryKey(target);
	var hash = key.GetHashCode() & 0x7fffffff;

	var index = hash % allSilos.Length;
	return Task.FromResult(allSilos[index]);
}

private static string GetTargetPrimaryKey(PlacementTarget target)
{
	var key = target.GrainIdentity.PrimaryKeyString;
	var result = key;
	if (key.Contains("__"))
	{
		result = key[..key.IndexOf("__", StringComparison.Ordinal)].Trim();
	}

	return result;
}
```

**Comment by benjaminpetit** [comment]
I agree with @nkosi23 , you should not **force** placement on a specific silo. Generally, the default random one is the best to use long term.

However, you could experiment with `PreferLocalPlacement`. If the `GameGrain` is the one that do the first call to `PlayerGrain` `WeaponsGrain`, then they will be placed on the same silo if possible.
