### ISSUE TITLE
Question : Reminders are scalable or not?

### ISSUE THREAD

**Issue by wangjia184** [dotnet/orleans#7267]
I see [#6555](https://github.com/dotnet/orleans/issues/6555) thread saying Orleans can easily handle millions of reminders.

While [#947](https://github.com/dotnet/orleans/issues/947) says silo does not partition reminders and load all of them on startup.

I am confused, may someone explain the situation of current reminders?  e.g. what if I have millions of persistent reminders?

**Comment by nkosi23** [comment]
@wangjia184 This is a question I had as well, and the answer is that reminders are scalable, they scale horizontally very well as they are partitioned across the whole cluster. You can have millions of reminders and Orleans will balance them across silos in your cluster (they will not all be loaded in the memory of a single silo).

The second thread you mention ( #947 ) actually also says that reminders are scalable, the first post reads:
> Orleans currently loads the entire reminders table into memory on Silo startup, partitioning reminders across available silos in the cluster, regardless of the time that reminders are set for.
> This causes a limitation on the number of reminders that can be set at any given time, because of memory constraints across the cluster

What #947 says is that in order to make reminders **even more** scalable, it would be possible to only keep in memory the reminders that are about to occur. Currently, a reminder will be kept in memory even if it will only tick many days in the future. #947 proposes to only keep in memory reminders that are about to occur soon, to make an even better use of hardware resources. 

However, even without this optimization, reminders can already scale to millions of reminders, you just need to keep in mind that every reminder you create will use memory somewhere in your cluster. But you can always add additional silos to your cluster to increase the memory available across your cluster (I do not know if there is a hot rebalancing of reminders when a new silo is added, but at the very least they will be rebalanced on restart).

This is not the case for example of streams which do not scale well if they have a huge number of subscribers as per the issue #7254 I created (the problem is that the list of subscribers of a stream is currently kept in memory on a single node - it is not partitioned across the cluster. You can have millions of streams having each a relatively small number of subscribers - even tens of thousands - but not streams with millions of subscribers). Reminders do not have this kind of limitation.
