### ISSUE TITLE
SimpleAzureQueueStreamOptions should extend AzureQueueStreamOptions

### ISSUE THREAD

**Issue by shmurchi** [dotnet/orleans#7361]
Currently one of AzureQueueDataManager's ctor takes in AzureQueueStreamOptions but does not support SimpleAzureQueueStreamOptions. 
I propose that AzureQueueStreamOptions and AzureQueueAdapter should be treated as base classes for SimpleAzureQueueStreamOptions and SimpleAzureQueueAdapter respectively. Additionally, SimpleAzureQueueStreamAdapter should be using SimpleAzureQueueStreamOptions instead of AzureQueueStreamOptions.

Tagging for visibility and awareness: @ReubenBond @benjaminpetit

**Comment by ReubenBond** [comment]
The codebase has changed since this issue was opened, and it is no longer as relevant: `SimpleAzureQueueStreamOptions` doesn't exist in 'main' and the apparent duplication is acceptable for 3.x because `AzureQueueStreamOptions` and `SimpleAzureQueueStreamOptions` are different: the former has a property for multiple queues and the later only supports a single queue. A relationship between the two could exist, but I think any relationship should involve extracting the common properties into a base class... regardless, I think this is not something we should fix anymore
