### ISSUE TITLE
Question: Does Orleans 3.5.0 support code generation with the C# 10 features enabled in a proper way?

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/orleans#7374]
I fell over some issues today where some (previously working) grains threw an exception `"System.InvalidOperationException: 'Cannot find generated GrainReference class for interface ...`.

There are only two things I changed:
* I added implicit usings (C# 10 feature) to the grains and grain interfaces projects and moved to file scoped namespaces (c# 10 feature)
* I renamed 2 grains (and all references)

Afterwards, the exception occurs whenever a service tries to access a grain by calling `orleansClient.GetGrain<ISomethingGrain>`.

I have already checked the following things:
* Your grain class inherits from the Grain base class 👍 
* Your grain interface and grain class projects have the Microsoft.Orleans.CodeGenerator.MSBuild NuGet packages installed 👍
* Your silo project references your grain interface and grain class projects 👍
* Check the Orleans interface project's .orleans.g.cs file --> References seem to be mapped correctly here 👍
* Did you get the exception when you called GetGrain<SomethingGrain> instead of GetGrain<ISomethingGrain>? --> No, we use the interfaces everywhere, not the implementation 👍
* Are your grain assemblies in the bin\Debug directory? --> Yes, interfaces and grains dll are there  👍

As I mentioned, the grains run in the "old" state properly.
Our projects are running in Net6, RC2 (Latest version).
I have tested locally with the same error messages.

So, the question is: Does Orleans or Orleans.CodeGenerator.MsBuild in version 3.5.0 (Latest) support C# 10 features already or not?

**Comment by SeppPenner** [comment]
References to the issues I checked already: https://github.com/dotnet/orleans/issues/6288, https://github.com/dotnet/orleans/issues/3121, https://github.com/dotnet/orleans/issues/1189, https://github.com/dotnet/orleans/issues/4028, https://github.com/dotnet/orleans/issues/1860, https://github.com/dotnet/orleans/issues/4052, https://github.com/dotnet/orleans/issues/6231.

**Comment by nkosi23** [comment]
I believe this is unlikely since C# 10 will only be part of .NET 6 which has not been officially released yet, and as such adding csharp 10 features to Orleans' Code Generator would have been programming against a moving target as the API could be subject to change. I also see no commit related to C# 10 new features in [the history of the Code Generator](https://github.com/dotnet/orleans/commits/main?before=4b7c62d05fd91bb20e52aadd5de4ad8e2a5b8f20+35&branch=main&path%5B%5D=src&path%5B%5D=Orleans.CodeGenerator), for example you can [see a commit](https://github.com/dotnet/orleans/commit/2259e3097abcc457b210bcd8799568dce26361d4#diff-09afa259d87bc9a435a1854ec2cb6b6046dd6b3b38246f401d408fd9f757c3aa) when support for C# 9 record types was added. 

I have no knowledge of their plans to add support to the features you mention, but if record type support can give us any clue, C# 9.0 was officially released on November 2020, but support for record types was only added to Orleans on June 2021.

**Comment by ReubenBond** [comment]
This is indeed an issue with Orleans 3.5.0 and below on .NET 6. We are hoping to release 3.5.1 as soon as we can to fix this. Apologies for the hassle

**Comment by ReubenBond** [comment]
In future, it will hopefully be somewhat easier to support most new language features while they're still in preview, since we will use a Source Generator instead of packaging a self-contained app.

**Comment by SeppPenner** [comment]
> This is indeed an issue with Orleans 3.5.0 and below on .NET 6. We are hoping to release 3.5.1 as soon as we can to fix this. Apologies for the hassle

Hi, thank you for the confirmation. As far as I know, the file scoped namespaces didn't break anything (We're running on a version with that feature right now). Just the implicit / global usings caused some trouble 😅

**Comment by SeppPenner** [comment]
@ReubenBond Do the currently released packages for Orleans (3.5.1) already contain the fix or not (Since you wrote about version 3.5.1)?

**Comment by ReubenBond** [comment]
Yes, it ought to be fixed now. Is it not working for you?

**Comment by SeppPenner** [comment]
> Yes, it ought to be fixed now. Is it not working for you?

I just recently updated the NuGet packages and didn't yet test if it works. On my current branch, I change the code back to before the changes to have a running version with 3.5.0. I will tell you soon if it works.

**Comment by SeppPenner** [comment]
It works as expected now, I'm just struggeling with https://github.com/dotnet/orleans/issues/7381 now.
