### ISSUE TITLE
Silos cannot find each other after a re-run when using RedisClustring

### ISSUE THREAD

**Issue by zeinali0** [dotnet/orleans#7451]
Hi 
I'm trying to run orleans locally for development  but i'm using redis clustring.
I have 2 silo each host different kind of grains. On first run everything work fine but when i try to re-run my silos they cannot find each other and they try to connect to dead silos for about 10 minutes.

`Failed to get ping responses from 1 of 1 active silos. Newly joining silos validate connectivity with all active silos that have recently updated their 'I Am Alive' value before joining the cluster. Successfully contacted: []. Silos which did not respond successfully are: [S10.163.245.127:11111:378287550]. Will continue attempting to validate connectivity until 12/27/2021 08:08:04. Attempt #3`

Here my configurations for silos:
```
    siloBuilder.UseRedisClustering(options => 
                    { 
                         options.ConnectionString = redisConnectionString; options.Database = 0; 
                    })
                    .ConfigureEndpoints(siloPort: 11111, gatewayPort: 30000)
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "dev";
                        options.ServiceId = "OrleansBasics";
                    })
                    .ConfigureLogging(logging => logging.AddConsole())
```

```
siloBuilder
                    .UseRedisClustering(options => 
                    { 
                        options.ConnectionString = redisConnectionString; options.Database = 0; 
                    })
                    .ConfigureEndpoints(siloPort: 11112, gatewayPort: 30002)
                    .Configure<ClusterOptions>(options =>
                    {
                        options.ClusterId = "dev";
                        options.ServiceId = "OrleansBasics";
                    })
                    .ConfigureLogging(logging => logging.AddConsole())
```

**Comment by benjaminpetit** [comment]
It's expected, previous silo instances did not shutdown properly. 

Two solutions:

- make sure that your silo can shutdown properly (might not be practical in dev environment, but you need to make sure it actually works for production)
- use another `ClusterId`  every time you deploy a new cluster

**Comment by zeinali0** [comment]
Even in production there is possibility to silo not shutdown properly 
what should we do if we want to immediately replace dead silo with new one?
Is there any reason it configured such a long time to detect a silo is dead?
Using new `ClusterId` mean if one silo died we should re-run all other silos again with new clusterId. this may cause no problem in development but it can be problematic in production.

**Comment by benjaminpetit** [comment]
What you are experiencing here is only happening because all silos from the cluster are dead. When a silo tries to join an existing cluster, it will tries to ping all silos marked alive (ignoring values not updated for more than `NumMissedTableIAmAliveLimit * IAmAliveTablePublishTimeout`, by default 10min).

If you have a 3-silo cluster, and one of them crashes, the two remaining would vote the 3rd dead quite quickly, updating the membership table. A new silo would be able to start without any troubles.

In your case the silo trying to join the cluster is a bit stuck: why it is not able to ping the silo marked `Alive` in the membership table? Is it because they are dead? Is it because of a network/config issue? It is safer in this case to just give up with a clear error message.

**Comment by zeinali0** [comment]
That make sense. I didn't know this happen only when all silos is dead. I thought it always happen for new silos when they gonna join cluster.
Thanks for Details.
