### ISSUE TITLE
Support server-side interceptor

### ISSUE THREAD

**Issue by Plasma** [dotnet/orleans#749]
Hi,

As per http://dotnet.github.io/orleans/Advanced-Concepts/Interceptors it would be good to also include server-side interceptor for pre/post processing of a grain message.

I would like to use a server side interceptor so that I can set/unset the `Principal.Current` context for each Grain message processed, which I would send as part of `Orleans.RequestContext` using `GrainClient.ClientInvokeCallback`.

**Comment by Plasma** [comment]
Thinking further, I think I may just want an optional callback method that I can wire up at the silo level that gets called when RequestContext is set as part of preparing to process a grain message.

That way when RequestContext gets given its data (implicitly done on sender side via the callback) it can execute some custom code (where I take advantage of the request context data that was just set, eg set Principal.Current) and perhaps if I return it as IDisposable when the request finishes I can have my context disposed of.

If I were to do a PR related to this (eg static property on RequestContext called ````IDisposable SetContextCallback```` would this be a good route to go?

**Comment by gabikliot** [comment]
I would not go the `RequestContext` callback route, for 2 reasons.
1) General purpose server-side interceptor will work for any scenario, even one that does not involve `RequestContext`  (lets say you just want to start some logging, or init something in the interceptor even if you don't use the RequestContext  at all).
2) SWith callback there are a lot of questions about when it executes, and in which context and what you are allowed to do there (does it run in the grain context or not, are you allowed to make grain calls, what happens if you throw, ...).

Alternatively, if we do implement server-side interceptor I would suggest putting the call to them [here](https://github.com/dotnet/orleans/blob/master/src/OrleansRuntime/Core/InsideGrainClient.cs#L359), just before the actual grain method is invoked. In this case it is clear that:
1) Interceptor code runs inside the grain context (this whole method already runs in grain context).
2) Interceptor code can make grain calls, any in general anything the grain can do (interceptor callback will need to return Task which will be awaited).
3) If the interceptor throws, we abort the current grain method call and return the exception back to the caller, just like done for a grain call.

This way, implementation and the semantics are actually quite easy.
The only real challenge, as happens a lot in Orleans, is with the programming model. How and where do we define the code for interceptors? Would it be an "interceptor provider"? Maybe some other way?  I would focus on deciding on that first. Implementation would most probably be easy.

**Comment by Plasma** [comment]
Thanks @gabikliot that sounds better

I'd propose then something like GrainClient.ClientInvokeCallback but for server side usage (eg, perhaps set as part of a bootstrap provider) to keep it simple; but I'm not as familiar with the ecosystem to make the best recommendation.

Alternatively, maybe a bootstrap provider could implement an optional interface (IInterceptGrainMessages ?) that could be checked for and ran before processing each message?

**Comment by gabikliot** [comment]
Bootstrap provider is definitely one option, but there are more. I see at least the following options:
1) Bootstrap provider will register the interceptor callback via the `IProviderRuntime` that is passed to it. We will add a call `IProviderRuntime.RegsiterPreInvokeInterceptor` and the Bootstrap  provider will call it with an arbitrary delegate.
2) Come up with a new `InterceptorProvider`. 
3) Something along the lines of what you wrote: "Alternatively, maybe a bootstrap provider could implement an optional interface ( IInterceptGrainMessages  ?) " 
4) Don't use providers at all for interceptors. Define some new attribute or interface and application would define a class that is marked with that attribute (or that implements that interface) and at runtime during loading we will discover that class and invoke it as interceptor if we found it.
5) Other ideas?

I personally prefer the idea number 1, but open for other opinions.

**Comment by sergeybykov** [comment]
I think option 2 is cleaner abstraction wise than 1. Not a strong preference though. 4 seems easiest, no providers, but then @nehmebilal will say that it's not testable. :-)

**Comment by Plasma** [comment]
I'm looking at maybe implementing Option 1 as this seems like the smaller code change (I'm not as familiar with Orleans codebase to make wider changes).

I'm also wondering what you think about having a request context flow into reminders/timers, if this is a concept already?

**Comment by gabikliot** [comment]
Lets please open a separate issue about "request context flow into reminders/timers" and discuss it there, ok? I am not very clear on what this would mean, but lets capture all those thoughts separately, in a clean Git Hub context.

**Comment by yevhen** [comment]
I'd like to be able to intercept messages on a per-grain basis. Virtual `OnReceive(req)` method (or similar) available on `Grain` base class would be great to have. Please consider that.

**Comment by ReubenBond** [comment]
Fixed via #963 & #965

**Comment by gabikliot** [comment]
Great closure on the whole interceptors topic @ReubenBond !
Thank you!

We now need to update the documentation: http://dotnet.github.io/orleans/Advanced-Concepts/Interceptors. It still says: "We currently do not have an implemention of server side interceptors"
