### ISSUE TITLE
how can orleans server response load balancing

### ISSUE THREAD

**Issue by liuzhixin405** [dotnet/orleans#7497]
i want orleans server can like consul,because i use  orleans cluster for my project.
if i startup three server thesame but SiloPort and GatewayPort different,the result is all client request in the one server，if
 the one server stop,other server bear the request。but，i want the scenes is i make some require，all server do the work in time.

the last i find a method, the same server i copy to ,and rename the server and change the  SiloPort and GatewayPort,i can get the scence i want.but it has a little trouble,more server i must build.
this is the sample
https://github.com/liuzhixin405/exercise/tree/master/Orleans/Orleans.MultiClient-Test

**Comment by suraciii** [comment]
Please clarify the topology of your scenario ,

> if i startup three server thesame but SiloPort and GatewayPort different,the result is all client request in the one server，if
the one server stop,other server bear the request。but，i want the scenes is i make some require，all server do the work in time.

In this situation, you configured **1 Orleans cluster** with **3 nodes(silos)**, when you send requests to **1 certain grain** by referencing its grain identity, the request will be processed by 1 nodes since the certain grain only exists in 1 node by default. it is the expected behavior.

> the last i find a method, the same server i copy to ,and rename the server and change the SiloPort and GatewayPort,i can get the scence i want.but it has a little trouble,more server i must build.

In this situation, you configured **3  isolated Orleans cluster**, and **each cluster has a single node**, requests processed by which cluster depends on which one you send requests to.

You can also contact me in Gitter or Discord so we can talk about your issue in detail.

**Comment by sanzor** [comment]
Hello i am also interested in this cluster-node scenarios .

**Comment by liuzhixin405** [comment]
> Hello i am also interested in this cluster-node scenarios .

can you have solution。this is my replace solution，https://github.com/liuzhixin405/exercise/tree/master/Orleans/Orleans.MultiClient-Test 。in orleans ,i have not find what to do ,i have researching.

**Comment by ReubenBond** [comment]
@liuzhixin405 are you starting a server 3 times with the same ports on 1 host? That cannot work: the last process to start will steal the socket and will be the only one listening on it

**Comment by liuzhixin405** [comment]
this is my load balacing, https://www.cnblogs.com/morec/p/15806332.html
