### ISSUE TITLE
Please add a more descriptive exception when a multi-instance stateless worker attempts to subscribe to a stream

### ISSUE THREAD

**Issue by MarkNickeson** [dotnet/orleans#7516]
### Current Behavior
When a stateless worker is configured with maxLocalWorkers > 1 the first worker instance on a silo is able to manually subscribe to a stream successfully. However, subsequent worker instances on the silo that attempt to subscribe to the same stream throw an Orleans.Runtime.GrainExtensionNotInstalledException with a message similar to:

> Extension not installed on grain Fully.Qualified.StatelessWorkerGrain attempting to invoke type Orleans.Streams.OrleansCodeGenStreamConsumerExtensionMethodInvoker from invokable Orleans.Runtime.ActivationData

This exception and message make it very challenging to narrow down the source of the problem.

### Desired Enhancement
A desirable enhancement would be to throw a very specific runtime error that directly identifies the cause as an invalid/unsupported stream subscription by a second or subsequent instance of a stateless worker . As well, since it appears that stream subscriptions work correctly for [StatelessWorker(1)], it is desirable to ensure that configuration continues to function and is not flagged as invalid/unsupported.

**Comment by brunolins16** [comment]
@benjaminpetit / @ReubenBond I have been looking into this issue and I have a repro scenario: https://gist.github.com/brunolins16/fc56fa40a114acfbb7471e6b235c3127.

The issues happens when a producers publish a new message to the stream and the activated Stateless Worker instance is not the same as the one that subscribed to the stream. I have been trying to find a good way to be more effective and throw the exception when the subscription is created, however, I am not able yet to find a good way to identify it during the subscription. Any good ideas?

One thing that might be useful is at least include an analyzer to warn about the issue

**Comment by brunolins16** [comment]
@MarkNickeson I talked with @benjaminpetit  offline and we agreed with a simple fix here, that I am working on. One thing that I would like to make sure is clear is with that we will start not support stream subscriptions for [StatelessWorker(1)], not even publishing to a stream from a StatelessWorker. 

We are changing to this approach because, as stated in the documentation [Stateless Worker Grains](https://docs.microsoft.com/en-us/dotnet/orleans/grains/stateless-worker-grains), you might have 1 or more activation per **silo**, so, if StatelessWorker A one silo 1 subscribe to events, and, if the pulling agent lives on silo 2, silo 2 will try to send events to an activation on Silo 2, not silo 1, and will end up causing the same issue.

![image](https://user-images.githubusercontent.com/12376385/154746159-c19922c2-abfa-4239-b394-516c735c8828.png)

@ReubenBond, are you ok with this?

**Comment by MarkNickeson** [comment]
Perhaps there is a better way for me to achieve what I'm using [StatelessWorker(1)] for as the image below attempts to depict. The state in question is entirely ephemeral and a given inbound event sequence is replicated to egress sessions where the number of sessions is potentially large (>10,000). I found that egress sessions as direct observers of an ingress event stream incurred significant overhead. So a work around was to change to something akin to a fan out topology. [StatelessWorker(1)] handles this beautifully. 

However since [StatelessWorker(X)] is destined to lose its ability to subscribe to streams, I would seek the community's guidance on how a similar topology could be achieved, perhaps via custom placement strategy or other means.

Thank you,
Mark

![image](https://user-images.githubusercontent.com/41964308/154774370-c0ec25b7-1e9b-4248-a498-8448ca31d159.png)
