### ISSUE TITLE
Cannot use orleans 3.6.0 on net48 + AspNetCore.Mvc 2.1

### ISSUE THREAD

**Issue by remcoros** [dotnet/orleans#7608]
The 3.6.0 update of Orleans updated the minimum MS.Extensions packages to 6.0.0, this forces any users to upgrade.

Although the MS.Ext packages support netstandard2.0, in practice, some of them are incompatible with AspNetCore.Mvc/Kestrel 2.1

This results in the following error when used with AspNetCore.Mvc 2.1 (latest supported version on net48):

System.TypeLoadException: Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=6.0.0.0

This is because InplaceStringBuilder has been removed, but AspNetCore.mvc 2.1 is still depending on it.

Downgrading packages which use Microsoft.Extensions.Primitives to 3.x.x is the solution. (e.g. MS.Ext.Options has a reference to .Primitives)

But in our host project, which targets net48 and uses AspNetCoreMvc 2.1 and Orleans 3.6, we cannot lock those packages to 3.1.x, because orleans has the MS.Ext packages locked to >= 6.0.0

Proposed solution: release Orleans 3.6.1 which, for the netstandard2.0 target, uses ">= 3.0.0" for the MS.Ext packages (like it was in 3.5.0)

edit: and we cannot upgrade to net5/6 yet, since we heavily rely on a closed source commercial library which is still on win-x64/net48.

**Comment by ReubenBond** [comment]
Apologies for the slow response. This is an issue with ASP.NET Core 3.x that I don't believe we will be able to fix. We're doing our best to support as many configurations as possible, but this is one place where we cannot offer a solution because the issue is an internal break between Microsoft.Extensions.Primitives & ASP.NET Core 2.1.

I think the only answer I can suggest is to wait until the closed source commercial library is upgraded to support .NET Core or .NET, unfortunately.

**Comment by ReubenBond** [comment]
xref: https://github.com/dotnet/aspnetcore/issues/40255

We discussed this on [Discord](https://discord.com/channels/333727978460676096/922948121619751012/956941288828190741) (invite: https://aka.ms/orleans-discord). I'll add a note about this unfortunate break to the release notes.
