### ISSUE TITLE
[Question] Request ordering during grain activation

### ISSUE THREAD

**Issue by Fitch24** [dotnet/orleans#7648]
Hi. I want to implement 'Fire and forget' behavior for grain.

Just for example. Let, I have this grain interface and implementation:
```cs
public interface ISample : IGrainWithGuidKey
{
    Task DoSomeWork(string msg);
}

public class Sample : Grain, ISample
{
    public override async Task OnActivateAsync()
    {
        await base.OnActivateAsync();
        Console.WriteLine("Activated");
    }

    public async Task DoSomeWork(string msg)
    {
        await Task.Delay(1000);
        Console.WriteLine(msg);
    }
}
```

And I use it like this:
```cs
IGrainFactory gf = Services.GetRequiredService<IGrainFactory>();
var grain = gf.GetGrain<ISample>(Guid.NewGuid());
for (var i = 0; i < 4; i++)
{
    grain.DoSomeWork(i.ToString())
        .Ignore();
}
// Expected results:
// Activated
// 0
// 1
// 2
// 3

// Actual results:
// Activated
// 1
// 3
// 0
// 2
```

As I understood from log messages it is happen because of _duplicate activation_. Each invocation of grain method (without await) tries to activate the same grain. It leads to requests forwarding and ordering broke.

Awaiting the first request is solving the problem:
```cs
var grain = gf.GetGrain<ISample>(Guid.NewGuid());
await grain.DoSomeWork("Await grain activation");
for (var i = 0; i < 4; i++)
{
    grain.DoSomeWork(i.ToString())
        .Ignore();
}
// Activated
// Await grain activation
// 0
// 1
// 2
// 3
```
But it is not compatible with 'Fire and forget' behavior.

**Is it possible to preserve requests ordering during grain activation** (without activation awaiting)?

**Comment by ReubenBond** [comment]
Without awaiting, no, certainly not something which can be guaranteed. There are various forms of non-determinism which may be involved. Here are some examples of cases where ordering can be lost:

* The .NET Thread Pool doesn't guarantee that tasks are executed in the order that they were enqueued
* A client can send one message to one gateway and another to another gateway, maybe because of an internal change
* If there are multiple connections between two endpoints (configurable, and can occur when both connect to each other simultaneously), then messages can be sent on either channel.

The await operator is the operator used to insert sequencing points. If you want order, you should use await. There are alternatives: you could have an ordered stream similar to a TCP window, or you could use explicit sequence numbers and reorder messages.

The issue regarding duplicate activations will be much less frequent now and should not occur in the case you describe anymore (starting in 4.0.0-preview1) due to some internal work.

**Comment by Fitch24** [comment]
In my use case there are no remote clients. Just one silo running on ASP.Net application host (all message producers and all message consumers are in the same process).
For me, the await operator is also not guarantee request ordering. Requests (to a grain) can be maid from a random thread in a web api controller. So, if the grain is not activated and the web api received two (or more) http-requests in a short period of time (not enough to activate the grain), the order may be lost. Also I found that [one-way requests](https://dotnet.github.io/orleans/docs/grains/oneway.html) has this behavior too: all request made while a grain is not activated are forwarded and their order may be lost (even if use await operator and make requests from the same thread)

> The issue regarding duplicate activations will be much less frequent now and should not occur in the case you describe anymore (starting in 4.0.0-preview1) due to some internal work.

Thanks. I will try it.
