### ISSUE TITLE
ADO.Net grain storage for MySQL missing primary key

### ISSUE THREAD

**Issue by ElanHasson** [dotnet/orleans#7878]
For MySQL, the `OrleansStorage` table does not have a primary key defined. This causes issues with MySQL replication.

See: https://dev.mysql.com/blog-archive/enforce-primary-key-constraints-on-replication/
and http://vettabase.com/blog/why-tables-need-a-primary-key-in-mariadb-and-mysql/#:~:text=hard%20to%20understand.-,Primary%20key%2C%20the%20binary%20log%20and%20replication,-The%20recommended%20binary

I did find https://github.com/dotnet/orleans/blob/main/src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql#L82-L85

However that was 5 years ago @attilah, what are your thoughts on this since you wrote the comments, and @veikkoeeva also did lots of work in this area :)

**Comment by veikkoeeva** [comment]
@ElanHasson Maybe that comment is copied over, looks like mine too. :)

**With a brief tour to reasoning before going to the problem**

In any case, the comment at https://github.com/dotnet/orleans/blob/main/src/AdoNet/Orleans.Persistence.AdoNet/MySQL-Persistence.sql#L82-L85 means that indexing arbitrary length strings regardging `{ grain ID, type, silo }` takes CPU and database memory. Instead of doing that the index is constructed using the same hash function Orleans uses. So this is the same idea as if putting data into `Dictionary` in .NET.

There may be hash collisions that are then resolved by comparing to the unhashed data. Going first by the hashed keys from the index allows one to pick either one key or all the collided ones and in this case comparison to unhashed data is fast and does not use that much resources either.

In addition: The way Orleans grains work ensures there can only be "one grain of a type".

The idea is [heap table](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/heaps-tables-without-clustered-indexes) in SQL server. Also reverse index in Oracle. There's some discussion of this on old tickets, I can dig if someone is interested.

**The problem and solving it**

Maybe one way to solve this is to introduce a random number that is set on first time a row is created (retrying if a hash collission occurs). This random number is then added to the index and so the index will be unique. This would keep the index slim and be backwards compatible also so that this technical number does not leave the database.

I make this note like this as indexing arbitrary length indexes may be slow. Of course it may not be so, one may even know the lengths will be short.

**Further notes**

For lurkers here, as noted in the comments, the ADO.NET design is such that Orleans needs only the parameter types and names. It basically sends the data and the SQL script to the database. So modifying the table designs and if needed the queries works as long as parameter names and types are kept (compatible with the queries).

I think the SQL Server doesn't use the most efficient locking in general case (and certainly one can change it to a in-memory table and limit `NVARCHAR` fields if it's certain values stay within those limits).

Certainly PostgreSQL can be more efficient.

**Comment by ElanHasson** [comment]
Thanks @veikkoeeva, I was thinking about that key length, may make sense to add a primary key that is SQL managed auto increment for the sake of row based replication.

Doesn't have to be added here, can add in my project as I'm the one with row based replication 😂

**Comment by ElanHasson** [comment]
I don't think the SQL part of the change needs to be in Orleans as it's very specific to my use case and others may have different goals / options for MySQL and replication depending on their Orleans usage patterns and environment.

Hopefully this helps someone in the future who runs into the same problem I did with regards to MySQL Row Based Replication (RBR) and not having a primary key on `OrleansStorage` table.

**Comment by ElanHasson** [comment]
If there is interest, We can also introduce the concept of "Optional" scripts to apply for MySQL (with a README.MD of course). 

@ReubenBond, let me know if you'd like me to add the alter statements to allow others to easily apply the change, or of you agree with not including this in the core repo.
