### ISSUE TITLE
Some statistics values may exceed default SQL column size

### ISSUE THREAD

**Issue by Liversage** [dotnet/orleans#796]
The [`CreateOrleansTables_SqlServer.sql`](https://github.com/dotnet/orleans/blob/master/src/OrleansProviders/SQLServer/CreateOrleansTables_SqlServer.sql) script creates a `OrleansStatisticsTable` table with a `StatValue` column having type `NVARCHAR(250)`.

The `APP_REQUESTS_LATENCY_HISTOGRAM` statistic known in the database as `App.Requests.LatencyHistogram.Millis` may generate a string value that is longer than 250 characters. This makes it impossible to update the statistics in the database because a `SqlException` is thrown:

> String or binary data would be truncated.

The histogram contains 31 (NUM_APP_REQUESTS_EXP_LATENCY_HISTOGRAM_CATEGORIES) buckets. Each bucket is formatted as a time range and a count (with a trailing space):

    [99999.9999:99999.9999]=9999999, 

The format above is quite pessimistic as some of the values will not use all digits indicated here. However, I have had situations where the formatted string was close to 500 characters because of latency problems.

The pessimistic format above uses 33 characters per bucket and there are 31 buckets leading to a pessimistic estimate on the maximum statistic length of `31 x 33 = 1023` characters. I have fixed my problem by changing the column type to `NVARCHAR(1000)`.

However, other solutions are also possible. The bucket format could perhaps be slimmed down to only include the upper limit of the bucket. With 31 buckets divided into 250 characters each bucket should not use more than about 8 characters on average so another option could be to reduce the number of buckets.

I also noticed that the code that formats the histograms (and perhaps other statistics) uses `CultureInfo.CurrentCulture` (the default) for number formatting. This means that the statistics stored in the database depends on the Windows regional settings of the silo process. Using software to read the statistics may fail if the reading software uses different regional settings. This can be avoided by using `CultureInfo.InvariantCulture` for all number formatting of string values stored in the statistics database.

**Comment by veikkoeeva** [comment]
@Liversage I guess this was discussed with @amccool in Gitter.
* Formatting: you are right, there are some values like that. They should be fixed. If needed, I can look for a more complete list, dumped from my db (Finnish locale, comma as a separator).

* Column length. Maybe an intermediary fix would be to set the length to 1023 characters. The longer term fix to statistics reporting, I feel, would be to put in numeric values, but it would require some redesign and coding (*maybe* normalizing the ``[SuspectingSilos]`` and ``SuspectingTimes]`` column design too).

You can see some ideas mulled at #255 (and also at #634, and additionally not recorded yet, move relational code out of the core). One option would be to have it like now, but have an additional structure that is more amenable to warehouse type reporting. Related to this idea, one could alter the tables and queries so that all operations would be non-destructive, in which case it could make an interesting tool with statistics to track deployment behavior in various situations. Also, additionally, there has been some ideas around saving grain communication data. I'm personally interested on "communications heat map" and see if there are things like *cliques*.

Phew. That was a lot of writing, but that's the bigger picture. Please, do share if you have ideas.

**Comment by gabikliot** [comment]
We should definitely change the ` CultureInfo.InvariantCulture `, no brainer.
Column length: we can reduce the number of digits after decimal point to 2 instead of 4. I would prefer to keep the number of buckets and their format like now, for readability.
Increasing the ` NVARCHAR(250) ` sounds like the simplest fix.

@Liversage , would you be able to submit a PR for that? Thanks!

**Comment by Liversage** [comment]
@gabikliot Sure, I will submit a PR when I can fit into my schedule.

I haven't looked into how the buckets are created but I noticed a pattern of powers of 2 so perhaps I can do a better estimate of the maximum width of the widest string.

**Comment by gabikliot** [comment]
Is it worth the trouble? Does it cost anything to extent that limit in NVARCHAR?

**Comment by Liversage** [comment]
I guess not. It is probably just my slightly obsessive need to fully understand what is going.

**Comment by veikkoeeva** [comment]
@Liversage In addition to what you and @gabikliot agreed on (I support on increasing the column width), if you have time and feel inclined to thinkg about this further, pop by to Gitter to have a chat sometime. Maybe an idea or even better, a concrete action plan emerges that can be written down to a issue and discussed. One I think is easier handling of the values (i.e. changing them to numeric ones) in SQL.

**Comment by gabikliot** [comment]
@Liversage, I fixed the NVARCHAR issue.

Regarding `CultureInfo.InvariantCulture` , I actually checked and it looks like we are using  `CultureInfo.InvariantCulture` everywhere we need to. I remember we had that issue in the past and we fxixed it. For example, see here: https://github.com/dotnet/orleans/blob/master/src/Orleans/Statistics/FloatValueStatistic.cs#L141

Maybe there is some other place that we missed? Where did you see that?

**Comment by veikkoeeva** [comment]
@gabikliot In case somebody (I'd like to, but unsure) doesn't get to check this, running for a while and for SQL Server providers:

``SELECT StatValue, Statistic FROM OrleansStatisticsTable WHERE StatValue LIKE N'%[0-9],[0-9]%';``
* [13,1072:26,2143]=1, [26,2144:52,4287]=1, [104,8576:209,7151]=1, 	App.Requests.LatencyHistogram.Millis
* gen0=40960,00, gen1=1267,77, gen2=26398,09	Runtime.GC.GenSizesKb

For OrleansSiloMetricsTable:
* 33,8664321899414, CPU

For OrleansClientMetricsTable
* 27,6199512481689, CPU

The strings are formatted [here]https://github.com/dotnet/orleans/blob/40ce3fa99a109539b8c7c71705dfa4fcdab8faa3/src/Orleans/RelationalStorage/OrleansRelationalExtensions.cs#L261).

An additional note, as tangentially mentioned in Gitter too, I think the real fix would be to transform these into a numeric form (maybe refactoring otherwise too), in which case running analytic queries would be easier and more efficient.

**Comment by Liversage** [comment]
@gabikliot I have created pull request https://github.com/dotnet/orleans/pull/812 to fix the two places where I noted that `CultureInfo.CurrentCulture` was implicitly used. I tried to locate the other places that @veikkoeeva pointed out but I was not able to pinpoint the calls to `ToString`/`string.Format` that creates the specific strings.
