### ISSUE TITLE
Loading StorageProvider Connection string from ServiceConfiguration in Azure worker role

### ISSUE THREAD

**Issue by ponsakthi** [dotnet/orleans#800]
Can Silo automatically load DataConnectionString for StorageProvider from ServiceConfiguration of a Worker role.

Instead of hardcoding it in OrleansConfiguration.xml like this,

```
<StorageProviders>
      <Provider Type="Orleans.Storage.AzureTableStorage" Name="AzureStore" DataConnectionString="<ConnectionString>" /> 
    </StorageProviders>
```

Is there any other way that it can take this Connection string from ServiceConfiguration of a Worker role as most of the connection string details are part of ServiceConfiguration file and I dont want to duplicate it and update this XML file during the deployment.

**Comment by sergeybykov** [comment]
Noting prevents the provider code from loading connection strings from service configuration. However, it would probably be best to generalize that somehow, so that the runtime will do that instead of each provider doing it on its own.

It's easy to put a variable name like <ConnectionString> to provider config. It is less clear to me how to make the runtime resolve it without taking a dependency on Azure libraries. Seems like we would need a resolver plugin to stay generic.

**Comment by veikkoeeva** [comment]
@sergeybykov I think we have a good change to tackle these if @attilah (and whoever has the change to help) champions the v1 of DI code.

**Comment by sergeybykov** [comment]
@veikkoeeva Good point.

**Comment by gabikliot** [comment]
@ponsakthi , there is also a programmatic API now to specify/update provider configuration. So you do not have to duplicate the string in the config xml, you can update your provider config object in your role code, before starting the silo.

**Comment by gabikliot** [comment]
Check this out - it does that exactly: https://github.com/dotnet/orleans/blob/master/Samples/AzureWebSample/OrleansAzureSilos/WorkerRole.cs#L76

**Comment by gabikliot** [comment]
@ponsakthi, did it solve your problem?

**Comment by ponsakthi** [comment]
@gabikliot . Thanks it solved the problem
