### ISSUE TITLE
Create Storage Provider targeting SQL Server 2008+

### ISSUE THREAD

**Issue by amccool** [dotnet/orleans#815]

**Comment by sergeybykov** [comment]
We are working on bringing the SQL storage provider created by the Azure CAT team to the Orleans codebase.

**Comment by sergeybykov** [comment]
https://github.com/sergeybykov/orleans/tree/ORSA is the preliminary version that we are going to turn into a PR.

**Comment by amccool** [comment]
YAY!
I'm reviewing quickly.  Is there an azure dependency lurking within this tree?

**Comment by sergeybykov** [comment]
It does use Microsoft.Azure.SqlDatabase.ElasticScale.Client  https://github.com/sergeybykov/orleans/blob/ORSA/src/OrleansSQLUtils/packages.config#L4. Not sure how important that is.

**Comment by grahamehorner** [comment]
@sergeybykov why not use EF then any EF data provider can be used?

**Comment by amccool** [comment]
for automated tests, using azure makes sense.  However my company's usage will require the removal of the azure dependency.

@grahamehorner I totally prefer codebases using ORM's.

**Comment by sergeybykov** [comment]
This is a snapshot of the code written for a concrete project. Consider it just a starting point open for all these changes. The original author can answer better why not EF. I personally don't have an opinion here. Let's try to morph it into a better shape.

**Comment by veikkoeeva** [comment]
I suppose the idea here is to spread state across databases in order to avoid saturating any one database. That might be a valid concern if there are a lot of traffic as the number of connections (connection pool limit) is limited and so is I/O. It's cool that others are taking a look at this too as I'm a bit of a bind currently. By the way, does the current provider do streaming?

@amccool, @grahamehorner  You may notice the current SQL provider does not use EF either, though there is what one might call a micro-ORM (such as Dapper) that allows for hand-tuning queries. Allow me to elaborate a bit on that as only the "high level surface" is on official documentation and some other opinions and implementation decisions are spread over issues and Gitter. I'm not what you might call an expert, but maybe this is something like an informed opinion formed over the years.

* Initially I was not sure what use cases there might be, so I wanted to remain as flexible as possible and not rule any use case as not supported. Relational storage is used in so various ways that it's not  possible to count them.
* Support all ADO.NET providers. EF has some connector libraries, but not nearly all of the DBs that have an ADO.NET provider -- not for free at least. Traditionally they've been buggy too. EF is also rather bulky, EF7 is better, but it wasn't here then, and not even yet. This shouldn't at least raise a bar for adoption.
* EF produces fairly gnarly SQL in many cases and it is not easy to control and/or fine-tune locking. Gnarly SQL certainly hurts performance, might also induce incorrect results (incorrect locking). Personally I've come to the conclusion as of late that writing everything in by procedures and functions and reading out by views is the easiest way to make locking behaviour correct, make it contained in one place where it matters the most, have all the security controls available and making hot application maintenance easier. Article about this: [Using Stored Procedures to Provide an Application’s Business-Logic Layer](https://www.simple-talk.com/sql/t-sql-programming/using-stored-procedures-to-provide-an-application%E2%80%99s-business-logic-layer/). As a tangential, I don't support moving computation to the DB, just how the data is laid down.
* The set of queries is finite, so writing and tuning them by hand is a choice. Even better, one can tune the queries with vendor, version and deployment hardware specific tricks and it should work even hot DBs without changing the code. One case could be that for SQL Server 2014 and newer one uses compiled stored procedures to insert statistics data to in-memory tables, for older the batch insert there is now.
* I'm aware of use cases where the DBAs (there still are them) want to know fairly well what kind of queries will be introduced to their databases. So, instead of locking the queries to code, one could put them to the database and arrange it so that as long as column names and types match, Orleans then load the queries by handle and uses them and it all should function. See the previous point. Maybe some of the good trickles back to Orleans if some DBA somewhere tunes a query or a table (when they get more complex than now).
* As mentioned, doing it like that allows for deployment specific query and table tuning. When streaming support (or ES in this example might work too) comes, one should be able to use something like [PipelineDb](https://www.pipelinedb.com/) just by finding a query with the appropriate key and target it to a different table. 
* Doing it like this allows for using multiple database, even from different vendors, even simultaneously a bit easier.
* One could replace the whole DB layout. One example I have in mind is to provide alternative tables and queries that are non-destructive (e.q. selecting returns the latest). That way it would be easier to correlate statistics and metrics with silo events and perhaps find out why a silo went down by running analytic queries on the DB.
* Try to be as much as CoreCLR compliant as possible. Early in spring I was gauging opinions if something like Dapper would be fine. It's fast and widely in use. But there were some issues about CoreCLR compatibility and concerns if they could be resolved. It would have been an additional dependency too.

What's interesting here is that is sharding important to some potential customers and if so, how should it be supported.

**Comment by sergeybykov** [comment]
Should we close this one as the initial version of the SQL storage provider has been merged, and open separate issues for individual improvement ideas?

**Comment by veikkoeeva** [comment]
@sergeybykov I believe it's easier to have individual PRs. Or one PR doing what is needed. This looks like being a more general purpose rationale to avoid "big ORM" (sorry about that).

**Comment by sergeybykov** [comment]
@veikkoeeva Are you saying we should keep it open for the "big ORM" issue?
