### ISSUE TITLE
Fallback serializer for Orleans 7

### ISSUE THREAD

**Issue by christallire** [dotnet/orleans#8163]
Hey guys, I've been migrating and testing Orleans 7 and I have some concerns regarding the way we serialize.

My concern is related to https://github.com/dotnet/orleans/issues/8127, enhancement of `GenerateSerializer` analyzer,
regarding `Orleans.Serialization.CodecNotFoundException: Could not find a codec for type SomeUserDefinedException`

It's been okay as long as the silo does not come online, we can annotate all the `GenerateSerializer` until it gets up.
But there's something we can't annotate `GenerateSerializer` until we go runtime is the user-defined `Exception`.

The canary release failed because of Exceptions, as we don't know when it will be thrown until runtime.
We need a fool-proof way to not generate `CodecNotFoundException` at runtime, or a fallback serializer will be my next choice
because it's easy to miss and it's easy to slip through peer review. I didn't expect to serialize exceptions at first time too.

What do you think?

**Comment by stephenwelsh** [comment]
We have a scenario where we are passing unknown types (with a container class) i.e.

```csharp
[Immutable]
[GenerateSerializer]
public class InvocationRequest
{
    [Id(0)]
    public string Target { get; set; }
    [Id(1)]
    public object?[] Arguments { get; set; }
}
```
So we are getting CodecNotFoundException once we start to pass arguments, the arguments are externally provided so will never be able to create Surrogates.
The only idea I have so far is to serialise the Arguments to say a Json string and separately de-serialize when the message arrives at its destination.
Not a show stopper for us, but interested to see if there is (or planned) way to have a fall back serialization capability to handle these edge cases.

**Comment by ReubenBond** [comment]
There is a kind of fallback serializer: you can configure Orleans to use JSON serialization to serialize any types you'd like. Here are docs for how to do it: https://learn.microsoft.com/en-us/dotnet/orleans/host/configuration-guide/serialization-configuration?pivots=orleans-7-0

We don't intend to offer a catch-all fallback out of the box, though, because our experience has been that it tends to hide problems which come back to bite later on. Fallback serialization has always been fragile.

So the recommendation would be to use Newtonsoft.Json as a general-purpose serializer for specific assemblies or namespaces.

**Comment by ReubenBond** [comment]
The bot is a bit eager on closing issues, but please feel free to ask more questions or open a new issue
