### ISSUE TITLE
Running Orleans in a desktop application

### ISSUE THREAD

**Issue by emailnike** [dotnet/orleans#8236]
We are looking for some assistance with the following:

- We use Orleans in our code base as we needed it to run in the cloud. However, we now have a change in focus and only need to ship as a desktop application. 
•	Is it better if we remove Orleans if we want our code base to run as a desktop application or 
•	Is there a way to configure Orleans so it can effectively run on a single desktop box for production?

**Comment by ReubenBond** [comment]
Hi @emailnike, both of those options are likely viable. The fastest option (given your application has already been developed) is to host Orleans within your desktop application. Orleans was designed for cloud services, however, and not desktop applications.

To the point, if you want to host Orleans within your desktop application:
* You will need to configure clustering using `UseLocalhostClustering()` so that the silo doesn't try to connect to some remote service
* It will still listen on TCP ports 11111 and 30000 by default. You can set `EndpointOptions.GatewayPort` to `0` to disable the latter, but the former is a requirement. There is an in-memory-only transport which could be used instead, but it is not accessible from user code. Still, if that would help, I may be able to extract it into a gist for you so that you have no TCP ports open on your desktop application, since those open ports would be a vulnerability unless otherwise secured.

If your grains require storage, reminders, or streams, you will need to either use in-memory options or find persistence options which are suitable for a desktop application.

Alternatively, you can remove the dependency on Orleans from your application entirely. That's application-specific, so I am unable to help there.

**Comment by ScarletKuro** [comment]
As ReubendBond said, the fastest way would be probably to start the Orleans on the host PC.
It's also possible to use Orleans as remote service in cloud and make WPF to connect to it like I did in this topic https://github.com/dotnet/orleans/issues/6895. I'm still using my application like this: 700 PC clients are connected to single(or more) Orleans that is hosted in our cloud.
However, Orleans was not designed for this, and the most correct way would be to add another layer between your Orleans and desktop application. For instance - GRPC. The GRPC would act like a getaway that communicates with your Orleans, they both would be in cloud, and client is connected to the GRPC service. It can be any other RPC framework like MagicOnion, SignalR, or even REST.

**Comment by untoldbyte** [comment]
Did we get to creating that gist?
Akka.net can be used to create a desktop app or background service.
What are they challenges to do so in Orleans?

**Comment by ScarletKuro** [comment]
> What are they challenges to do so in Orleans?

I think the first thing is security, Orleans, it doesn't have any protection against usual attacks like buffer overflow etc.
It's still possible expose Orleans outside, I have one project where Orleans is exposed to internal work network and desktop applications connect to Orleans directly without any additional layers.
