### ISSUE TITLE
Protobuf support in version 7.x

### ISSUE THREAD

**Issue by chemhack** [dotnet/orleans#8276]
We are trying to use Protobuf serialization in version 7.x, however ProtobufSerializer is only available in version 3.x.

Is there any plan to make it available in version 7.x as well?

**Comment by bradygaster** [comment]
@adityamandaleeka, this feels like a good idea.

**Comment by ReubenBond** [comment]
@chemhack, are you looking for Google.ProtocolBuffers or protobuf-net support? We could add support for either or both, like we support JSON today. Largely, I wanted to wait until someone requested it rather than speculatively create one or both packages.

**Comment by chemhack** [comment]
@ReubenBond thanks for the response. we are looking support of Google.ProtocolBuffers. The use case we are looking at is reuse the same serialized classes in existing GRPC services, so that we don't have to create another set of data models and do the extra mapping.

**Comment by larsfjerm** [comment]
Here's a proposal: https://gist.github.com/larsfjerm/6b393353e8bbb611c2960dd1600777fc

I refactored it from https://github.com/dotnet/orleans/blob/main/src/Serializers/Orleans.Serialization.Protobuf/ProtobufSerializer.cs

**Comment by abe545** [comment]
I just want to add my +1 for this feature. Without it, we're blocked from upgrading our various orleans based services to v7, since we rely on protobuf heavily for our grain apis. I did have to tweak the gist slightly... for the `ITypeFilter` method implementation, it is important to return `null` if the type isn't an `IMessage`. Otherwise, I found it preventing some of the built-in serialization from working. I saw errors with it trying to serialize `GrainReference`, for instance. I'm fine implementing this myself for now, but would love if this was a supported nuget package.

**Comment by ReubenBond** [comment]
@abe545 do you have an updated version of the gist?

**Comment by ReubenBond** [comment]
>  I did have to tweak the gist slightly... for the ITypeFilter method implementation, it is important to return null if the type isn't an IMessage. Otherwise, I found it preventing some of the built-in serialization from working.

The `bool? IsTypeSupported(Type type)` method return values have the following meanings:
* `null`: unknown (use default, or a value from another `ITypeFilter`)
* `false`: no, the type is not supported. Ignore subsequent providers.
* `true`: yes, the type is supported. Ignore subsequent providers.
It is primarily a security concern: whether or not Orleans will instantiate a type depends on this value.

**Comment by abe545** [comment]
> * ITypeFilter

Thanks @ReubenBond. It would be great if that were documented on the interface, so it is obvious for implementers. I was able to read the code in this repo to figure that out, but it did take me some time. It was quite surprising that adding a codec would break the serialization of built-in types, but also without that interface implementation, the codec wouldn't work for protobuf messages, so it was clear it was needed.

**Comment by ReubenBond** [comment]
Opened a PR to add that info to the doc comments: https://github.com/dotnet/orleans/pull/8328

**Comment by larsfjerm** [comment]
Yea sorry, I see my first gist there had some flaws. I've done some more changes to what we currently use internally. 

Updated the gist to align it closer to the STJ serializer: https://gist.github.com/larsfjerm/6b393353e8bbb611c2960dd1600777fc
I can prepare a PR for it and discuss further changes.

```c#
// To include all IMessage types
services.AddSerializer(c => c.AddProtobufSerializer(
    isSerializable: type => typeof(IMessage).IsAssignableFrom(type),
    isCopyable: type => typeof(IMessage).IsAssignableFrom(type)));
```

**Comment by abe545** [comment]
Thanks @larsfjerm. I also made some similar changes yesterday when I was doing additional testing, and was going to update my gist (I'll do so after I've worked out some more kinks). Although, for my use case, I'd *always* want every `IMessage` to be supported, so I didn't follow the json codec's approach to registration.

**Comment by abe545** [comment]
Ok, I updated my [gist](https://gist.github.com/abe545/d4aa171d6be4c633b0a45bc49e9df0d6). Sorry for the delay, I was making sure my changes to the protocol weren't to blame for my failing tests that I was encountering that I reported in #8335. Anyway, I made a few changes from the one provided by @larsfjerm:
1. I wound up implementing `ISpecializableCopier` instead of the `IGeneralizedCopier` to avoid the need to use `dynamic` to run the `Clone`. 
2. I kept the registration simple, as I don't think the json style registration is helpful for this protocol - you likely don't want to opt-in to being able to serialize a protobuf message (you might have different use cases than me, but I feel like the default scenario is to be able to serialize all protos).
3. I liked his use of spans so much for writing, I also switched to the span based APIs for parsing the message also
