### ISSUE TITLE
Azure TableStorage 5.0.2 fails on CreateIfNotExistsAsync

### ISSUE THREAD

**Issue by ukluk** [dotnet/orleans#829]
I am using a custom State provider with Table Storage (Json serializer)

OnActivate
{
await CloudTable.CreateIfNotExistsAsync(requestOptions, operationContext);

// Does not throw an error but never completes

This works
CloudTable.CreateIfNotExists(requestOptions, operationContext);
}

**Comment by gabikliot** [comment]
Did you try to test it outside Orleans? Sounds like unrelated to Orleans at all, since this call `CloudTable.CreateIfNotExistsAsync(requestOptions, operationContext);` does not call anything in Orleans. One general tip we have about storage is to try to it against the real Cloud account and not against storage emulator (if indeed you used the storage emulator), since we saw sometimes hiccups in the storage emulator. Besides from that advice, did you try our built in Azure Storage Provider?

**Comment by gabikliot** [comment]
Another thing to note about AzureTable is if you delete the table, you cannot create a table with the same name for some time (I sometime saw it for minutes). Again, completely unrelated to Orleans.

**Comment by ukluk** [comment]
I did try outside Orleans.The problem only manifests OnActivation.
I suspect is a threading issue.
Again, let me point out that it produces no exception, but hangs


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by gabikliot** [comment]
`CloudTable.CreateIfNotExistsAsync` is not called from `OnActivation`. It is called when silo is initializing and calling storage provider `Init`. Unless in your custom storage provider you did it differently. Is this the case?

**Comment by ukluk** [comment]
If it doesn't belong I will change it, but actually on my custon provider I do have a singleton invoking CreateIfNotExists OnActivation


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by gabikliot** [comment]
Yes, it does not belong there. You can init the table when silo inits, or when provider is loaded, or pre-create it manually before you start and never delete it again.

**Comment by gabikliot** [comment]
Uri, did that fix your problem?

**Comment by ukluk** [comment]
Thx Gabi, you guys are am amazing support.
Yes it did, but if you let me explain the entire scenario it could help the community:
The same code worked wuth TableStorage 4.3, As soon as we upgraded to 5.0.2 it broke.
Seams that some async conditions are not supported OnActivate, but i can read state no problem async.
The challenge was that it doesn't throw exceptions, it just hangs that thread.
If you have some best practices about what can break the grain activation and how to handle error, it will be greatly appreciated!
Best regards,Uri


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by gabikliot** [comment]
Thank you Uri, you are mostly welcome!

All async conditions are fully supported in `OnActivate`. You can do all the things in OnActivate just like inside a regular gain method. My speculation would be that it is not related to `OnActivate` but rather either a different behavior of  5.0.2  or just the mere call to `CloudTable.CreateIfNotExistsAsync`. I don't think you want to call  `CloudTable.CreateIfNotExistsAsync ` on every `OnActivate`, since why adding an extra storage hop for every grain. Instead it is much better to create the table once and stick with that fact. In Orleans we use a wrapper object to do that exactly: AzureTableManager, it initializes the connection to the table once and caches it and keeps reusing it. This is its only state, otherwise it is stateless. You can use the same pattern in the Storage Provider and initialize the table in the Provider Init call.

**Comment by sergeybykov** [comment]
I'm sure @gabikliot actually meant "most welcome". :-)

**Comment by gabikliot** [comment]
I did. ;-) And Uri specifically is even more than just "most welcome", as being on one of our earliest external customers.

**Comment by sergeybykov** [comment]
+1
