### ISSUE TITLE
OnActivateAsync does not use MayInterleave() & Co - bug or by design?

### ISSUE THREAD

**Issue by Jens-G** [dotnet/orleans#8349]
Hi, not sure if bug or by design, but I have a grain that gets called in an re-entrant way. What's strange is, that after upgrade to  Orleans 7 that call got stuck, even though I tried all possible attributes available to enable re-entrant calling properly. But it kept that way and to my astonishment not even the `MayInterleave()` callback got invoked. 

Then it somehow dawned on  me that it may have something to do with the fact that the deadlock-causing call is made during `OnActivateAsync()` .... And right, after I moved the call out of OnActivateAsync() to some other routine  - now it gets called later after the activation phase - all of a sudden it started to behave. 

Now I wonder if that behavior (i.e. completely ignoring re-entrancy attributes when inside `OnActivateAsync`) is by design or a bug? At least I did not find any documentation stating that it would be illegal generally or with Orleans 7 in particular. Plus I had that same code working in 3.x before, and never had that particular issue.

**Comment by ReubenBond** [comment]
Generally, you should not make calls in OnActivateAsync if that call needs to call *back* into your grain because the grain cannot handle requests until it has completed activation. Perhaps this worked in 3.x because of call [chain reentrancy](https://learn.microsoft.com/en-us/dotnet/orleans/grains/request-scheduling#call-chain-reentrancy), which was enabled by efault (but rather broken). I'll close this now, but please open a new issue if you come across something else.

**Comment by Jens-G** [comment]
Ok, thanks for the confirmation/explanation.
