### ISSUE TITLE
Redis grain directory single-activation guarantee question

### ISSUE THREAD

**Issue by bill-poole** [dotnet/orleans#8418]
I have some questions about the degree to which the Redis grain directory provides a "single-activation" guarantee. I was unfortunately unable to find the information I was looking for in the documentation. However, if such documentation exists, please point me to it.

Does using the Redis grain direction provide a "single-activation" guarantee under _all_ circumstances? Or are there some failure modes that can cause multiple simultaneous activations of the same grain for limited time windows? 

For example, what happens if the leader Redis instance crashes? Replication between Redis instances is asynchronous, so what happens if the leader node crashes and a follower node is appointed leader, but some data was lost?

It is important for a few of my grain types to have a single-activation guarantee at the expense of availability. i.e., for some grain types, I need invoking a grain to temorarily fail rather than spin up a new grain instance if the cluster cannot guarantee a single activation. I need to know whether Orleans can provide me that guarantee, or whether I need to implement a separate mechanism outside of Orleans.

**Comment by ReubenBond** [comment]
The providers for Redis rely on Redis being reliable and don't try to provide stronger guarantees than Redis does.

Indeed, Redis is not as reliable as people tend to assume.

There is an Azure Storage grain directory which provides stronger guarantees.

Ultimately, though, it's always possible to have multiple instances of a grain because a silo may have been declared dead and may not have learned of that fact yet so it will blissfully continue with that grain still active. Meanwhile, other hosts are free to host the grains which were on the defunct silo. If you want stronger guarantees than that, you either need leases or per-operation consensus (eg, using storage on each operation gives you that). See #2428

**Comment by bill-poole** [comment]
Thanks @ReubenBond. We're using AWS, so Azure Storage grain directory isn't an option for us. Is there an AWS option, perhaps using DynamoDB? Or in the absence of that, do you have any advice how one would best implement their own lease-based solution?

**Comment by bill-poole** [comment]
Okay no worries. Thanks for all your help so far. I read through the `AzureTableGrainDirectory` source and have a few questions:

- [Line 87](https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs#L87) has a comment "Possible race condition?" Is this still an outstanding question? If so, what needs to be done to resolve it?

- The public [UnregisterMany](https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs#L107) method isn't found on `IGrainDirectory`. Should this be implemented on a DymamoDB grain directory implementation?

- The [UnregisterSilos](https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs#L124) method isn't implemented (with a comment stating it is too costly to implement using Azure Table). What are the ramifications of not implementing this method? Does it mean that if a silo is gracefully removed from the cluster then the directory entries for the grains hosted on that silo are not removed from the directory and remain there as is until activated on another grain?

Am I correct in assuming that directory entries corresponding to grains on a silo that crashes are not cleaned up - i.e., they remain in the directory until activated on another grain and then eventually later gracefully deactivated? And if such a grain is never reactivated, then its entry remains in the directory forever?

If so, I assume there is no way to automatically clean up such entries because it isn't possible to determine which entries correspond to still-running grain activations?

**Comment by ReubenBond** [comment]
cc @benjaminpetit for the [AzureTableGrainDirectory.cs:87 comment](https://github.com/dotnet/orleans/blob/01475f531c27c1c1fa7bc6f20827ffc8a50e5636/src/Azure/Orleans.GrainDirectory.AzureStorage/AzureTableGrainDirectory.cs#L87).

Regarding `UnregisterMany`, if it's not on the interface, you don't need to implement it.

Regarding `UnregisterSilos`, registrations pointing to known-dead silos are ignored and treated as if they do not exist (i.e, they will be overwritten eventually). The method is used to eagerly clean up the table, but there is little need to do this for Azure Table Storage.

**Comment by bill-poole** [comment]
> they will be overwritten eventually

However, is that only if/when those grains are activated again? i.e., am I right in saying that registrations for grains that are never activated again will remain in the database forever?

**Comment by ReubenBond** [comment]
Since we are talking about guarantees in distributed systems, I want to be very clear about what is and is not possible.

You cannot have a *guarantee* of single activation ever in a fault-tolerant distributed system because a machine may be suspended for an arbitrary period of time (eg, a VM migration, very long GC, debugger pause, space-time rift). If the system is allowed to heal while this machine is suspended (as far as everyone knows, it's never coming back), then it cannot guarantee that that existing activation is gone before it creates a new one. The suspended machine may wake up and run some already-enqueued request. Leases do not guarantee this either because they cannot be checked constantly (for every single instruction, before every side-effect) and because of general relativity (i.e, read [Time, Clocks, and the Ordering of Events in a Distributed System](http://lamport.azurewebsites.net/pubs/time-clocks.pdf)).

That is true for all distributed systems and it's true in the strict sense of "single-activation guarantee". However, if you add some more restrictions, then you can guarantee nice things. For example, Orleans guarantees linearizability for storage operations (reliant on the backing store), so you can make sure that updates to grain state do not clobber each other.

You can also use leases to get a close approximation of single activation guarantee (just know that it's not an actual guarantee) by repeatedly checking that the held lease is not due to expire for some sufficient amount of time before/during/after each operation.

The points that you laid out are akin to leasing. i.e, you could make silos self-destruct if they are unable to periodically re-assert that they are in good standing with the rest of the cluster. I think it would be a good addition and would give people a close approximation of single-activation while remaining cheap.

**Comment by bill-poole** [comment]
> a machine may be suspended for an arbitrary period of time (eg, a VM migration, very long GC, debugger pause, space-time rift)... The suspended machine may wake up and resume some already-running request.

Fair point. However in a Kubernetes cluster where the underlying nodes are autoscaled and always started fresh (never suspended/resumed), then that problem is avoided.

> There is still the issue of trading off availability, though. By default, it takes around 15 seconds to declare a host dead. If we want a reasonable buffer, we could say that a host declares itself dead if it does not receive positive acknowledgement ("we promise not to kill you in the next 10s") within 10s (giving it a 5s margin to shutdown running activations). Those margins are rather tight. We'd need to think through the acceptable failure scenarios.

Yes I agree. A short margin means silos will self-destruct more often, reducing availability, and a long margin means grains on dead silos will take longer to be reactivated, also reducing availability. Furthermore, the membership refresh interval would need to be compatible with the chosen margin, and there's a limit to how often silos can refresh their membership list.

Perhaps if the feature were opt-in with a setting in `ClusterMembershipOptions`, also with a setting to configure the time after a dead silo membership entry timestamp before silos recognize that the silo is dead. The membership refresh interval would presumably need to be less than that time as well.

> I think it would be a good addition and would give people a close approximation of single-activation while remaining cheap and within the realm of possibility.

I would certainly find the feature very useful.

**Comment by bill-poole** [comment]
> However in a Kubernetes cluster where the underlying nodes are autoscaled and always started fresh (never suspended/resumed), then that problem is avoided.

Okay, so now having done more reading and thinking, you've convinced me that _guaranteed_ single-activation is impossible for the reasons you stated - although, the longer the "lease" expiry window, the stronger the guarantee.

Unfortunately, using the backing store to "linearize" operations (using e-tags) only works if:
- the state being written is in a single record; or
- the storage technology provide atomic writes.

Consider writing parent/child records. We ordinarily try to write the parent/children in a single record when using a key-value database, in which case each write of parent and all children is atomic. But that isn't always possible. Sometimes, each write adds/removes a small number of children, and the total number of children is very large, which makes writing all children on each write impractical.

In these situations, we need to use some kind of distributed locking mechanism (such as a lock record with an expiry timestamp). Without that, we end up with "zombie" child records floating around the database. That is, we can guarantee correctness by using an optimistic lock on the parent record, but we cannot prevent child records belonging to an earlier version of the parent from being written; nor can we guarantee that child records belonging to an earlier version of the parent will be removed after being written.

Of course, DynamoDB provides atomic writes up to 100 records, which is fine unless you have some operations requiring writes of more than 100 records, which unfortunately is the situation I'm in.

We can build a record locking mechanism ourselves, acquiring/releasing the lock on each write, or we can rely on Orleans to provide a strong single-activation constraint (albeit not guaranteed) at the grain level. The limitations/reality that make it impossible for Orleans to provide a single-activation _guarantee_, also make it impossible for a distributed lock to provide guaranteed single-access to any process protected by a distributed lock. The same constraints apply - the longer the lease (lock expiry window), the better the guarantee.

It therefore makes sense to me for Orleans to provide "locking" at the grain level (opt-in and configurable) to provide the same "best effort" single-activation guarantee that any custom-built distributed locking mechanism could provide.

This would not only require less reinvention of wheels, but also result in systems that are more cost effective because locking at the grain level requires fewer database writes than locking at the record level.

I'm hoping a mechanism similar to that discussed here could be added to Orleans in the near future to provide this capability.

**Comment by bill-poole** [comment]
Thanks @ReubenBond!
