### ISSUE TITLE
Unable to start Redis reminder. 'Orleans.Timers.IReminderRegistry' has not been registered.

### ISSUE THREAD

**Issue by idanbenyehoshua** [dotnet/orleans#8446]
Hi,
Trying to use reminder backed by Redis but when I try to get an reminder or register new reminder I get the message (in exception):
The requested service 'Orleans.Timers.IReminderRegistry' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
I register the reminder like that: 
`siloBuilder.UseRedisReminderService((opt) =>  opt.ConfigurationOptions = myRedisConfiguration).
 Configure<ClusterOptions>((opt) => opt.ServiceId = "myService");`
when I replace the reminder with UseInMemoryReminderService it works perfect.
** I register the Redis persistence storage exactly like UseRedisReminderService (opt.ConfigurationOptions = myRedisConfiguration) and it works as excepted.
Nuget: Microsoft.Orleans.Reminders.Redis 7.1.2-beta1

**Comment by idanbenyehoshua** [comment]
I think I found the problem, AddReminder is missing.
When I manually add `siloBuilder.AddReminders();` it works.

**Comment by snovak7** [comment]
@ReubenBond was this perhaps fixed in 7.2.1? Based on https://github.com/dotnet/orleans/blob/28256dba1681e7fafde850ecb10c20b25faaf720/src/Redis/Orleans.Reminders.Redis/Hosting/SiloBuilderReminderExtensions.cs#L27-L31
It's missing AddReminders() like here:
https://github.com/dotnet/orleans/blob/28256dba1681e7fafde850ecb10c20b25faaf720/src/Orleans.Reminders/Hosting/SiloBuilderReminderMemoryExtensions.cs#L21-L28

**Comment by ReubenBond** [comment]
Good point, @snovak7. I've opened a PR to fix it: #8629
