### ISSUE TITLE
Long running task under IStartupTask?

### ISSUE THREAD

**Issue by kwemou** [dotnet/orleans#8659]
Dear all,
is it a best practice to execute long running tasks using startup tasks?
I am looking for the best place to execute some grains that perform migration of grain states from old to new versions.
I think about GrainService or IStartupTask.

Thank you in advance
Emeric

**Comment by ReubenBond** [comment]
I'd use `IHostedService` instead: https://learn.microsoft.com/en-us/dotnet/core/extensions/timer-service?pivots=dotnet-7-0
Inject `IGrainFactory` so you can get and call grains.
Add it after your call to `UseOrleans` so that it's started after Orleans starts.

An `IStartupTask` must complete before the silo starts. We would not have made them if `IHostedService` existed already.

**Comment by kwemou** [comment]
Thank you so much :)
