### ISSUE TITLE
What is grainid in outside cluster client

### ISSUE THREAD

**Issue by spingee** [dotnet/orleans#8690]
Hello what is grainid in case of outside cluster stream client.
I want to know boundary of where can be subscription shared (GetAllSubscriptionHandles).
Is it whole process? Or thread?
Thanks for answer

**Comment by ReubenBond** [comment]
Hi @spingee, I must apologize in case I do not understand the question. Are you asking whether calling `GetAllSubscriptionHandles()` on a client will return all client stream subscriptions in the entire application or just the process or thread? The answer is that it will return subscriptions in the current process, since every client generates a new, random `GrainId` when they initialize and that `GrainId` is used for the lifetime of the process.
