### ISSUE TITLE
The call order of await is not used?

### ISSUE THREAD

**Issue by 17723010593** [dotnet/orleans#9138]
Can I ensure that the Startup method is called before the ClientOnline method without awaiting?
![image](https://github.com/user-attachments/assets/0d94ca9c-ea92-485e-a6c4-95d24d9fc49b)
![image](https://github.com/user-attachments/assets/ecb5d617-586c-41fc-b0fe-b247c3a16b15)

**Comment by ledjon-behluli** [comment]
Like you showed, No! But you can do:
```
playerGrain.Startup().Wait();
playerGrain.ClientOnline().Wait();
```

Though you should NOT do that, as those calls can be remote calls and you'll be blocking the current thread for an IO operation which is never a good thing

**Comment by MickaelThumerel** [comment]
Try with the attribute OneWayAttribute on you method "Startup" on the interface.
https://learn.microsoft.com/en-us/dotnet/orleans/grains/oneway

At least you will correctly use the await on the method called but the execution will not be blocked by the execution.

Add this attribute and await will only ensure that call request to "Startup" leave before than "ClientOnline". Grain are one thread by default. Then you should have your expected behavior to have the two method called after the other in the good order without blocking your calling thread
