### ISSUE TITLE
Dependency Injection: strongly-typed configuration method

### ISSUE THREAD

**Issue by ReubenBond** [dotnet/orleans#989]
Currently the DI container is configured by creating a class containing a method with this signature:

``` C#
IServiceProvider ConfigureServices(IServiceCollection services);
```

and specifying that class by name in the configuration.

We should be able to specify the configuration class by providing an instance of it instead. That allows us to provide an existing (pre-populated) container more easily.

The class should also implement an interface rather than have a magic method name/signature.

**Comment by jason-bragg** [comment]
>"We should be able to specify the configuration class by providing an instance of it instead. That allows us to provide an existing (pre-populated) container more easily"

We have programmatic ways of setting configuration information (for example, adding providers) before silo startup.  Would something comparable for the service provider be sufficient?  Main thing here is that this would limit the ability to set the service provider to the configuration setup (before silo construction).

>"The class should also implement an interface rather than have a magic method name/signature."

This was my first impression as well.  It would definitely make the code cleaner.  My assumption was that this was not initially done because it would introduce a dependency on Orleans into the service provider concrete class.  I don't see this as a problem, but it's something that we should be aware of.

**Comment by ReubenBond** [comment]
> We have programmatic ways of setting configuration information (for example, adding providers) before silo startup. Would something comparable for the service provider be sufficient?

Something like `config.RegisterServiceProvider<MyType>()` or `config.RegisterServiceProvider(myServiceProvider)` (or both) would be good, I think.

> My assumption was that this was not initially done because it would introduce a dependency on Orleans into the service provider concrete class.

If that's an issue, we could allow specifying a configuration delegate directly.

**Comment by ReubenBond** [comment]
*bump* locally I've added a new config parameter:
```C#
/// <summary>
/// The delegate used to configure dependency injection.
/// </summary>
/// <remarks>This property and <see cref="StartupTypeName"/> are mutually exclive: at most one can be specified.</remarks>
public Func<IServiceCollection, IServiceProvider> ServiceProviderBuilder { get; set; }
```

What do people think of that approach? It's proving itself very useful for me.

This pattern fixes inversion of control issues with the current DI pattern whereby Orleans instantiates a class itself. Consumers have no good way of configuring that class in order to provide it with context.

For example, if I want to configure Orleans to leverage Service Fabric, I need to provide some bits like the current service's name, partition, replicator, etc. The current approach does not allow me to do that without using statics.

By the way, we should also be using DI on the client.

**Comment by amccool** [comment]
@ReubenBond we are currently struggling with the current DI implementation in our unit tests where we use moq, and wish to be able to query the mock using `.Verify()`.  By injecting the mocks into the Startup class it would seem that would give us back access to the mocks.

That all said @jdom reminded me that the due to the way app domains are used by the TestCluster that that use case probably wont work as the mock in a different app domain from the unit test.

Still, we would be interested to see your implementation using the Func<T,T> property style. Injecting the injection as it were.

**Comment by ReubenBond** [comment]
Resolved by https://github.com/dotnet/orleans/pull/3302
