### ISSUE TITLE
Serializer specification with attributes

### ISSUE THREAD

**Issue by Carlm-MS** [dotnet/orleans#993]
This is an attempt to capture the points regarding external serializers.

An attribute type will be able to be applied on:
- method parameters - a single parameter will be serialized using the specified serializer
- method - all of the parameters being serialized will use the specified serializer
- type - all instances of that type will use the specified serializer
- grain interface - all methods in the grain interface will be serialized using the specified serializer

The functionality will be rolled out in phases starting with:
1) single/multiple serializer support
2) type-specific serializer
3) grain interface serializer
4) parameter serializer

Modify built-in storage providers to utilize those attributes
- Question: How would we guarantee that the data isn't corrupted if the attributes change?

**Comment by ReubenBond** [comment]
Serialization is pluggable now and fairly flexibile, even on the method parameter (per-parameter [Immutable] attributes for example), but we haven't received strong signal for this level of granularity in picking serializer: serializer selection is currently per type and I believe thst is a good decision since it leads to a simple mental model.
