### ISSUE TITLE
Microsoft.Framework.DependencyInjection.Abstractions Missing from dependencies in 1.1.0-beta1

### ISSUE THREAD

**Issue by andre-realroi** [dotnet/orleans#998]
The nuget package Microsoft.Framework.DependencyInjection.Abstractions is not in the dependencies , and will make the silo not start correctly unless it's manually installed.

**Comment by amamh** [comment]
I had this same problem sometimes. I'm on 1.0.10. I'm not sure why it happened, I had to manually add that package.

**Comment by sergeybykov** [comment]
Yes, there is a dilemma here. We can easily add those packages as dependencies for Microsoft.Orleans.OrleansRuntime. However, that would only work for -beta releases because those packages aren't stable releases, and hence cannot be dependencies of our stable 1.1.0 release.

We can document in 1.1.0 that these dependencies need to be added. But that would be weak, relying on RTFM. If we could make the DI code dynamically loaded until a stable release of the dependencies, I think that would be a better dev experience.

I wonder if @attilah has an opinion here.

**Comment by gabikliot** [comment]
That was fixed by #1007, right?

**Comment by sergeybykov** [comment]
Yes.
